### ISSUE TITLE
Do UDOs with k-type output return k-values at init-time too? Unfortunately, yes...

### ISSUE THREAD

**Issue by maurocsound** [csound/csound#1000]
Joachim Heintz noticed a strange behaviour in the UDOs returned values at init-time.
Let's make a very simple example:

```
opcode giveMe5atKtime, k, 0
	kTemp	=	5
		xout	kTemp
endop

instr 1
	k1	init	123456
		printk	1, k1
	k1	giveMe5atKtime
endin
```

We know, from the reference docs (https://csound.com/docs/manual/init.html), that in the first statement of "instr 1" (k1 init 123456), k1, despite being a k-type variable, is valued at i-time and that 'init' should be the only opcode that can modify a k-type variable during the i-time pass. 
So, in the above example, we would expect the first printed value to be 123456... Instead, the first printed value will be 0!! This happens because the UDO "giveMe5atKtime" is called at init-time too, to let Csound run any eventual i-time statements inside it. This is ok, but then, when the UDO returns from its init-pass, in the k-time variable k1 it is copied the value from "giveMe5atKtime->kTemp", that is ZERO, being that at init-time the "=" statement inside the UDO is correctly skipped (because it is a k-time assignment).
This behaviour is, in my opinion, wrong. It does not follow what the reference docs say (init opcode should be the only case of k/a-type variables valued during the init-pass) and it's just confusing for the user that a k-time UDO could change a k-type variable from the caller "at init-time". 
The right behaviour should be that at init-time the UDO would run all its i-type statements, as it does now, but then the output variables in the caller statement should be valued ONLY if they are i-type variables.
	
Summarizing: native opcodes that returns k/a-type variables are correctly skipped during the init-time, so, for coherence (and adherence to the reference docs), the user expects that this should be the case for User Defined Opcodes too, but actually it is not.

**Comment by maurocsound** [comment]
A little addendum on this matter...
Steven Yi pointed out to me that, from the [reference docs](https://csound.com/docs/manual/opcode.html), you can use 'k' and 'K' types in an opcode definition... With 'k', the variable should be updated only at init-time (similar to the native opcodes behavior). With 'K' the variable should be updated both at init and performance-time.
But, in Csound 6.11, strangely, 'k' behaves as if it were 'K', so the k-type output variables are always copied both at init and performance-time.

**Comment by vlazzarini** [comment]
Fixed in git.
