### ISSUE TITLE
A possible optimization for assignment

### ISSUE THREAD

**Issue by maurocsound** [csound/csound#1001]
Take a look at the following code:

```
opcode myBiquad, a, aiiiiii
	axn, ib0, ib1, ib2, ia0, ia1, ia2 xin
	setksmps 1
	
	kxn_1, kxn_2, kyn_1, kyn_2 init 0
	
	ib0	/=	ia0
	ib1	/=	ia0
	ib2	/=	ia0
	ia1	/=	ia0
	ia2	/=	ia0

	ayn	=	ib0 * axn + ib1 * kxn_1 + ib2 * kxn_2 - ia1 * kyn_1 - ia2 * kyn_2
	
	kxn_2	=	kxn_1
	kxn_1	=	axn[0]
	kyn_2	=	kyn_1
	kyn_1	=	ayn[0]
	
		xout	ayn
endop
```
I noticed that in the above code, if I replace these two:

	kxn_1	=	axn[0]
	kyn_1	=	ayn[0]

with these:

	kxn_1	vaget	0, axn
	kyn_1	vaget	0, ayn

the performance of the UDO at runtime will be better.

Problem is, generally speaking, in a sample-by-sample computation:

`kVar = aVar[0]`

is about 2x slower than:

`kVar vaget 0, aVar`

I think that many users would prefer and use the first version, because it's easier to understand, but they don't know that it is 2 times slower than the second one, probably because it writes the contents of aVar[0] into a temp variable before assigning it to kVar... Ideally, the Csound engine should recognize that, in this specific case, the temp variable is not needed.

**Comment by jpffitch** [comment]
This issue confuses a special case of ksmps=1 with a general case. I know I wrote this code somewhere

**Comment by maurocsound** [comment]
Thanks! I hope I'll be able to build Csound from sources, so that I could test all the new mods. I had some trouble in past to build Csound on Windows, so now I will try again.

**Comment by kunstmusik** [comment]
From my message in #999, I realized just now that the code is actually supposed to generate as vaget and array_get.  So there are two issues here, one that there's an additional assignment, the other that array_get is being generated rather than vaget. Of the two issues, it might be the latter is actually the bigger performance hit. I'll plan to look at the second issue first.

**Comment by kunstmusik** [comment]
Nevermind, I think it was a red herring: there's an overloaded version of array_get that is for asigs that that has the same code as vaget.  @jpffitch has commited code for the multiple assignments so perhaps we can close this once confirmed by @maurocsound. BTW: You should be able to use the AppVeyor MSVC build of Csound for testing, but use the one after the commit I just pushed that has NULL checks.

**Comment by maurocsound** [comment]
I don't know how it works AppVeyor... I've tried to make a build giving to it the git url of csound, but then I have:

```
Build started
git clone -q --branch=master https://github.com/csound/csound.git C:\projects\csound-pkw54
msbuild "C:\projects\csound-pkw54\Opcodes\AbletonLinkOpcodes\AbletonLinkOpcodes.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.
  ableton_link_opcodes.cpp
c:\projects\csound-pkw54\opcodes\ableton_link_opcodes.cpp(311): fatal error C1083: Cannot open include file: 'ableton/Link.hpp': No such file or directory [C:\projects\csound-pkw54\Opcodes\AbletonLinkOpcodes\AbletonLinkOpcodes.vcxproj]
Command exited with code 1
```

Anyway I've downloaded and installed the csound build from your link. I tried it and:

1) the mods works. The assignment optimization works. Now the performance is the same with array notation or with vaget. The multiple assignment works.

2) if I try to use this new version with my faust plugin faustops.dll, Csound crashes when it parse the statement faustplay. If I reinstall the previous Csound installer "Csound6.11.0-Windows_x64-installer.exe", faust opcodes return to work.

**Comment by maurocsound** [comment]
A little update: I uninstalled Csound, cleaned its directory in "C:\Program Files", then reinstalled and reinserted the faustops.dll in the plugins64 dir. Now it doesn't crashes but the result is the same. The "faustplay" opcode from the plugin faustops.dll is not executed. On the console I can see that it complains about a wrong number of input args for the faustplay opcode... Strange, being that with the previous csound build it works.

This is the error I have in the console when I try to play a note with the virtual keyboard of CsoundQT:
```
INIT ERROR in instr 1 (opcode cascBQ3) line 88: wrong number of input args

 from file C:/Users/Mauro/Desktop/prova.csd (1)
aSignal	faustplay	idsp	aSignal	
		   T  1.625 - note deleted. instr 1 had 1 init errors

```

The Csound code, as reference:
```
<CsoundSynthesizer>
<CsOptions>
;-odac -d
-n -d -+rtmidi=NULL -M0 -m0d --midi-key-cps=4 --midi-velocity-amp=5
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

; A biquad implementation in Csound language:
; P.S.: from my experiments, this 'setksmps 1' verions is faster than an implementation that directly changes the elements of the a-rate input vector within a while loop iteration.
opcode csndBQ, a, aiiiiii
	axn, ib0, ib1, ib2, ia0, ia1, ia2 xin
	setksmps 1
	
	kxn_1,	\
	kxn_2,	\	
	kyn_1,	\	
	kyn_2	init	0
	
	ib0	/=	ia0
	ib1	/=	ia0
	ib2	/=	ia0
	ia1	/=	ia0
	ia2	/=	ia0
	
	ayn	=	ib0*axn + ib1*kxn_1 + ib2*kxn_2 - ia1*kyn_1 - ia2*kyn_2
	
	kxn_2	=	kxn_1
	kxn_1	= 	axn[0]
	kyn_2	=	kyn_1
	kyn_1	= 	ayn[0]
	
		xout	ayn
endop

; A BIQUAD implementation as a Faust expression with params... Let's compile it:
; P.S.: to achieve better performance, this version supposes b0,b1,b2,a1,a2 are already divided by a0
giBQhandle faustcompile2 {{
	b0 = nentry("b0",0.5,0,1,0.001);
	b1 = nentry("b1",0.5,0,1,0.001);
	b2 = nentry("b2",0,0,1,0.001);
	a1 = nentry("a1",0,0,1,0.001);
	a2 = nentry("a2",0,0,1,0.001);
	process(xn) = 
		(b0*xn + b1*xn' + b2*xn'' - _) ~ (_ <: (a1*_ + a2*_'));
}}, "-vec"


; using NATIVE biquad opcode:
opcode cascBQ1, a, aiiiiiip
	aSignal, ib0, ib1, ib2, ia0, ia1, ia2, iN xin
	
	if (iN > 0) then
		aSignal biquad	aSignal, ib0, ib1, ib2, ia0, ia1, ia2
    		aSignal	cascBQ1	aSignal, ib0, ib1, ib2, ia0, ia1, ia2, iN - 1
	endif
	
		xout	aSignal
endop

; using biquad implemented in Csound language:
opcode cascBQ2, a, aiiiiiip
	aSignal, ib0, ib1, ib2, ia0, ia1, ia2, iN xin
	
	if (iN > 0) then
		aSignal	csndBQ	aSignal, ib0, ib1, ib2, ia0, ia1, ia2
    		aSignal	cascBQ2	aSignal, ib0, ib1, ib2, ia0, ia1, ia2, iN - 1
	endif
	
		xout	aSignal
endop

; using a JIT-compiled faust code with i-type parameters passed by faustctl:
opcode cascBQ3, a, aiiiiip
	aSignal, ib0, ib1, ib2, ia1, ia2, iN xin
	
	if (iN > 0) then
		idsp 	faustdsp	giBQhandle
	    		faustctl 	idsp, "b0", ib0
	    		faustctl 	idsp, "b1", ib1
	    		faustctl 	idsp, "b2", ib2
	    		faustctl 	idsp, "a1", ia1
	    		faustctl 	idsp, "a2", ia2
	    	aSignal	faustplay	idsp, aSignal
    		aSignal	cascBQ3		aSignal, ib0, ib1, ib2, ia1, ia2, iN - 1
	endif
	
		xout	aSignal
endop

; using a JIT-compiled faust code without i-type params passing:
opcode cascBQ4, a, aiiiiiip
	aSignal, ib0, ib1, ib2, ia0, ia1, ia2, iN xin
	
	if (iN > 0) then
		idsp 	faustdsp	giBQhandle
		; NO PARAMS PASSED TO THE FAUST CODE INSTANCE!
		aSignal	faustplay 	idsp, aSignal
    		aSignal	cascBQ4		aSignal, ib0, ib1, ib2, ia0, ia1, ia2, iN - 1
	endif
	
		xout	aSignal
endop

instr 1
	aNoise 		rand 	p5 / 2, 0.5
	iDelayLdur 	= 	1 / p4
	aLine 		linseg 	1, iDelayLdur, 1, 0, 0
	aDL 		delayr 	iDelayLdur
	aDL 		+= 	aNoise * aLine
	; for the test use one of the following cascBQx versions, commenting the others:
	;aDL 		cascBQ1	aDL, 0.5, 0.5, 0, 1, 0, 0,  30 ; native biquad
	;aDL 		cascBQ2	aDL, 0.5, 0.5, 0, 1, 0, 0,  1 ; Csound biquad
	aDL 		cascBQ3	aDL, 0.5, 0.5, 0, 0, 0,  1 ; Faust biquad with params passing
	;aDL 		cascBQ4	aDL, 0.5, 0.5, 0, 1, 0, 0,  30 ; Faust biquad without par.passing
			delayw 	aDL
				
	aDL		=	aDL * madsr(0.001, 0, 1, 20)
			outs 	aDL, aDL
endin

instr Monitor
			printk2	active:k(1) ; <-- display the currently active notes in polyphony
endin

</CsInstruments>
<CsScore>
f 0 z
i "Monitor" 0 z
</CsScore>

```

**Comment by jpffitch** [comment]
Cannot see what this has to do with assignment optimisation.

⁣Sent from TypeApp ​

**Comment by maurocsound** [comment]
Me neither... I don't understand why it works with the installer downloadable from the csound main site, but not from this one kindly linked by Steven Yi... 
Anyway, thanks for the optimizations! :-)
