### ISSUE TITLE
Lisp interface: segmentation fault on emacs slime

### ISSUE THREAD

**Issue by azimut** [csound/csound#1002]
Issue: csound segfaults when I have an incorrect statement on the emacs session.

Desired result: I would like csound on lisp to be resilient to the errors I make on emacs/slime.

Setup: I am using the :sb-sound wrapper for sbcl within emacs slime. I quickload it along :cm and :cl-heredoc.

How to replicate:
- On emacs, open SLIME
```
CL-USER> (ql:quickload '(:cl-heredoc :cm :sb-csound))
```
- then on a new file, example.lisp, evaluate each line.
```
(in-package :cl-user)
(defvar *tmp* nil)
(setf *tmp* (sb-csound:csoundcreate 0))
(+ a)
```
The last line will trigger an error. Instead of having a new windows appear with it slime/sbcl just quits with this on the buffer `*inferior-lisp*`:
```
time resolution is 1000.000 ns
0dBFS level = 32768.0
--Csound version 6.12 beta (float samples) Aug 29 2018
[commit: 9b19ad44a81916d322588d061e4eabfe64e9a705]
libsndfile-1.0.28
Csound tidy up: Illegal instruction
backtrace() returned 3 addresses
/usr/lib64/libcsound.so(+0x43d2c) [0x7fa871b59d2c]
/lib64/libc.so.6(+0x37380) [0x7fa8726bd380]
[0x21ce310d]
end of score.		   overall amps:      0.0
	   overall samples out of range:        0
0 errors in performance
Elapsed time at end of performance: real: 8.777s, CPU: 0.020s

Process inferior-lisp exited abnormally with code 1
```

More information: I should note that a more complex examples work fine and I get audio output like the one at https://github.com/csound/examples/blob/master/lisp/sb-test.lisp

**Comment by gogins** [comment]
Sorry but I can't help with this as I don't use Emacs...

**Comment by azimut** [comment]
And that was it I just remove these lines https://github.com/csound/csound/blob/develop/Top/csound.c#L1259-L1261 and it works fine for me, thanks!

**Comment by vlazzarini** [comment]
Instead of removing the lines, did you try passing CSOUNDINIT_NO_SIGNAL_HANDLER ?

**Comment by gogins** [comment]
Thanks for the feedback, I'm glad the CFFI bindings are working for you!

My next step is get all of this loading and working in OpenMusic.

Regards,
Mike

**Comment by azimut** [comment]
@vlazzarini  I am not sure how to do that, what I did with was add it as a cmake arguments:
```
-DCSOUNDINIT_NO_SIGNAL_HANDLER=1
```
or with =0 , but didn't make a difference. I am using it through my package manager, so might be that changes something. Any chance it can be enabled/disabled without re-compiling in the future?

**Comment by vlazzarini** [comment]
That would be an argument to the Csound constructor (csoundCreate() in C, not sure how this translates to lisp, perhaps @gogins would know).

**Comment by azimut** [comment]
Aha! clearly I don't read C code well. I fix it with:
```
CL-USER> (csound:csoundinitialize 3)
0
CL-USER> (csound:csoundcreate (cffi:null-pointer))
```
Borrowing it from the emacslisp project https://github.com/hlolli/csoundAPI_emacsLisp/blob/ab8182f3d8eda015252e010be7951cd943c5e84e/csoundAPI_example/example1.el

Thanks for the help

**Comment by gogins** [comment]
Great!
