### ISSUE TITLE
Winsound does not build

### ISSUE THREAD

**Issue by jpffitch** [csound/csound#1004]
Despite restoring the deleted file it fails inside cmake

make -f Frontends/CMakeFiles/winsound.dir/build.make Frontends/CMakeFiles/winsound.dir/build
make[2]: Entering directory '/home/jpff/csound6'
make[2]: *** No rule to make target 'Frontends/CMakeFiles/winsound.dir/build'.  Stop.
make[2]: Leaving directory '/home/jpff/csound6'
make[1]: *** [CMakeFiles/Makefile2:2568: Frontends/CMakeFiles/winsound.dir/all] Error 2
make[1]: Leaving directory '/home/jpff/csound6'
make: *** [Makefile:166: all] Error 2

**Comment by vlazzarini** [comment]
Did you try a clean build? E.g. getting rid of CMake caches etc?

**Comment by vlazzarini** [comment]
I pulled from git just now and was able to build Winsound.

**Comment by jpffitch** [comment]
Killed the cache and it seems OK -- except
1: Why did deleting a file give that errors?

2: After restoring the file it did not build winsound but the binary is there from before the outage!  How come?

Leaves me with a lack of comnfidence

**Comment by vlazzarini** [comment]
Not sure, but it is to do with the cache being out of sync with what's on disk.
