### ISSUE TITLE
printf and printf_i don't work without optional parameters

### ISSUE THREAD

**Issue by maurocsound** [csound/csound#1005]
This is the syntax of printf and printf_i from the reference docs:

```
printf_i Sfmt, itrig, [iarg1[, iarg2[, ... ]]]
printf Sfmt, ktrig, [xarg1[, xarg2[, ... ]]]
```
So, this should work:

`printf_i "blablabla...", 1`

instead Csound complains with the following output:

```
error:  Unable to find opcode entry for 'printf_i' with matching argument types:
Found: (null) printf_i Sc
```

**Comment by jpffitch** [comment]
I think it is nothing to do with the string, but the type in the sources 
has inputs SiTN
So 3 arguments muonimum.  The nanual is not inline with the code

**Comment by joachimheintz** [comment]
it would be nice to have some more similarity between the different 
print opcodes, in case it were easy to implement.  currently we can write
	print(k)s "mama\n"
but not
	printf(_I) "mama\n", 1
as printf(_i) needs a third argument.

on the other hand, we can write
	printf(_i) "%s", 1,  "mama\n"
but not
	print(k)s "%s", "mama\n"
as print(k)s cannot deal with %s.

so, if possible: allow only two arguments for printf(_i), and add %s for 
print(k)s would be desirable.

**Comment by jpffitch** [comment]
There is also a problem wit the N in printf_i as it accepts k-rate values 
to an i-rate operation which does not do what is expected.

I have no objection to most of his but it needs type-inference changes.

**Comment by maurocsound** [comment]
I don't know how much it would be hard to do, but I totally agree with Joachim.

**Comment by jpffitch** [comment]
I tried an experiment to allw 0 or more arguments after te trigger and it 
does not work.  The implementation of *printf* opcodes is excessively 
complex and previous attempts to fix things have been problematic. 
Multiple authors with different strategies.....

**Comment by jpffitch** [comment]
I have committed a patch that I think works for printf without any % stuff 
in it.

Not good code and the use of k-rate values in printf_i remains

**Comment by jpffitch** [comment]
Please try code in github.  I _think_ I have made both adjustments.

**Comment by maurocsound** [comment]
Could you build a binary for Windows x64?  Unfortunately I could not compile STK library in the MSYS2-MinGW64 environment, so actually I'm not able to build Csound. I think I will switch to MSVC but until now I have not had the opportunity yet. I wanted to try appveyor but I don't know how to use it... When I start a build it always complains that it didn't find ableton/Link.hpp and other ableton-related errors...

**Comment by vlazzarini** [comment]
you don't need the STK library, just build Csound without it.

**Comment by vlazzarini** [comment]
you can also download the appveyor build artefact. Just go in the latest successful appveyor build and select 'artifacts' 

The latest was not successful, but one of the following will be

**Comment by maurocsound** [comment]
Ok, I thought STK was needed. 
Just tried in building Csound without STK (using MSYS2-MinGW64), but there are so many errors in the process that I gave up. I think that the actual MSYS2 building instructions and scripts inside the csound/mingw64/ dir are too old or incomplete and I haven't the expertise to fix them.

As for appveyor, I would need a step-by-step guide, because I don't ever know where to download those appveyor build artefacts and what to do with them...

**Comment by vlazzarini** [comment]
The errors are probably due to somethin else, STK is definitely not needed.

The build artefact is just the installer. It should work just like an installer.
In fact, the distributed installer and zip
come straight from appveyor.

**Comment by rorywalsh** [comment]
Try here :
https://ci.appveyor.com/project/csound/csound/history

That should have all the latest builds. Click on a link and get the
artifact.

**Comment by maurocsound** [comment]
Thanks Rory. 
I noticed the build with John's latest mods (that I would like to test) failed so I will wait for a successfull build.

**Comment by kunstmusik** [comment]
Error in build seems to be unrelated to John's change, but rather one due to change of MSVC runtime redistributable. This has happened before but I don't remember how to fix it. @stekyne : could you assist here?

**Comment by stekyne** [comment]
Sure I'll take a look

**Comment by joachimheintz** [comment]
thanks, john; i tried, and this is the result for simple tests:
- printf_i and printf now working also with only two arguments
- prints accepts also %s
- but printks does not.

**Comment by jpffitch** [comment]
Hum.  as far as i can tell printks uses the samecode as prints
Can you mail be(maybe iff line?) you test program that shows the problem 
with printks? I could try to construct an example but it will take time

**Comment by jpffitch** [comment]
Sorry -- a typo now fixed.  will commit in a minute or so

**Comment by joachimheintz** [comment]
yes works now.
super to have this now more consistent.

**Comment by maurocsound** [comment]
Hi, thanks to John for the changes. Tested and working. :-)

**Comment by jpffitch** [comment]
closing for now
