### ISSUE TITLE
cosseg outputs wrong envelope

### ISSUE THREAD

**Issue by gesellkammer** [csound/csound#1006]
This code should render a fade-in of 0.5 seconds and a fade-out of 0.8. 

csound: 6.11, platform: linux

```
instr 1
  ifadein = 0.5
  ifadeout = 0.8
  a0 oscili 0.5, 1000
  aenv cosseg 0, ifadein, 1, p3 - (ifadein + ifadeout), 1, ifadeout, 0
  a0 *= aenv
 outch 1, a0
endin

```

**Comment by jpffitch** [comment]
Yes; lengths are correct but the shanpe of the "fade-out" is rubbish.

**Comment by jpffitch** [comment]
Fixed in github.  Was a botched optimisation now corrected
