### ISSUE TITLE
Missing opcodes in WASM build

### ISSUE THREAD

**Issue by hlolli** [csound/csound#1013]
Some opcodes that should be included in WASM binary but aren't: GENpadsynth, exciter, doppler, ampmidid, GENfarey, scanu, scans, urandom. Some of these are C and some C++, can't really figure out why they get filtered out.

**Comment by kunstmusik** [comment]
These look like opcodes that are part of opcode libraries.  I had seen
something in Emscripten's documentation that would allow us to dynamically
load opcode libraries (perhaps requiring some manual coding in JS, but
something we could add to CsoundObj). I'm not sure anyone has investigated
it elsewhere, but it'd be the ideal solution in terms of extensibility to
have a path where 3rd parties could add opcodes separately from core
libcsound.js.

**Comment by hlolli** [comment]
Yes it is possible, CMake even makes a static library Make method for all these opcodes. One just needs to run emmake make [insert make method here], and then include the file in emcc like we do with libsndfile. After some hacking around I got padsynth into the wasm. But, I just couldn't avoid the c++ symbol mangling to go away (`_ZL12padsynth_gen`), the extern should do the trick but doesn't, so I tried 

```
  set_target_properties(padsynth PROPERTIES
    LINK_FLAGS "-s LINKABLE=1 -s EXPORTED_FUNCTIONS=\"['_padsynth_gen']\" -s ERROR_ON_UNDEFINED_SYMBOLS=1")
```
also didn't do it. I give up on this rabbit hole and leave this up to the experts :)

**Comment by Penguinum** [comment]
Not sure if it's related but I have these opcodes missing in non-WASM (amd64) build. Just a usual build on Ubuntu 18.04 as described in BUILD.md, on master and on latest release. The build that comes from repo has these opcodes. Didn't dig further yet.

**Comment by hlolli** [comment]
some of these are available today in the new wasm setup, those missing are probably c++ and can't be easily implemented
