### ISSUE TITLE
Make error stacktraces more meaningful

### ISSUE THREAD

**Issue by hlolli** [csound/csound#1014]
When hit with something like this, especially with a csound api this can be quite hard to decrypt

```
error:  Unable to find opcode entry for '=' with matching argument types:
Found: i = a
Line: 98
Parsing failed due to syntax errors
Stopping on parser failure
```

Line 98 doesn't mean much in a case where all the expressions are string. I understand that the error is indicating that some a-rate signal is being assigned to a i-rate variable. But in which opcode, and more specifically, which i and a rate symbols are these?

P.s just creating a ticket to open a discussion and/or request an improvement in the long-run.

**Comment by jpffitch** [comment]
There is no stack to trace at that time and the opcode is clearly defined 
as '='
The line number is usually sufficient in my experience

**Comment by jpffitch** [comment]
nd an example csd wold help.  I looked at the code and it is unclear what 
data is available

**Comment by jpffitch** [comment]
error:  Unable to find opcode entry for '=' with matching argument types:
Found: i = a
       iii = abc
Line: 24
 from file ass.csd (1)

**Comment by hlolli** [comment]
I agree that in most cases, the line number suffices. But with controling csound from the csound-api, I may end up storing many csound instruments in a array of string.

I reproduced this error message, and the `=` operator is actually more meaningful than I realized. It's nothing to reproduce just assigning `ival = asig`.
But if the error would emit the symbol names, or some english explaination "Can't assign audio signal to a variable" would always be a plus, after sitting for hours doing Csound, it's not certain the brain is 100% :)

Anyway, here's an example of very good error message in Csound, if it was everywhere this way, it would be a bonus!

```
Invalid ftable no. 2177.000000
INIT ERROR in instr 0: table: could not find ftable 2177
	tablew	gindx	#i1	giWaveTrimmed	0	0	0
```

**Comment by hlolli** [comment]
Tough I could comment on that error message I said was good,

```
tablew gindx, tab_i(4323 + gindx, giWave), giWaveTrimmed
```

the #i1 I take to be intermediate value, tough the 3 0's at the end I can't figure out what they mean. But still very meaninful nevertheless.

**Comment by hlolli** [comment]
Yes indeed, my most common typos in english: wether/weather, tough/though, witch/which. But they are only the tip of the iceberg.

I will recompile Csound and let you know (probably tomorrow), nevertheless, as you point out, this is a compile time error and doesn't stop the anything, and most of the time, I would encounter these during live performance with code, so I would see it right away as I compile a csound string. For my use case good. I'll close this ticket for now (reopen if unlikely I have more comments or questions on this topic).

**Comment by jpffitch** [comment]
tablew gindx, tab_i(4323 + gindx, giWave), giWaveTrimmed 

[the #i1 I take to be intermediate value,]  Any variable starting with a # is an internally generated variable usually for  an expression.  the extra zeros are the optional arguments you did not provide so were added by the opcode decisions.

**Comment by hlolli** [comment]
Yes, that makes sense.

So I tested the changes, for

```
instr 1
  asig poscil 0.000001, 100
  ires = asig
endin
```

I get
```
error:  Unable to find opcode entry for '=' with matching argument types:
Found: i = a
       ires = asig ...
Line: 14
 from file bug.csd (1)
Parsing failed due to syntax errors
Stopping on parser failure
cannot compile orchestra
```

this makes a HUGE difference, thanks a million. This will make my life easier!

**Comment by hlolli** [comment]
A question @jpffitch how difficult would it be to implement column number alongside line number, it could potentially help frontends highlight the errors.
