### ISSUE TITLE
Csound wasm stdout and stderr callback names

### ISSUE THREAD

**Issue by hlolli** [csound/csound#1017]
So when I start libcsound like this
```
require("./libcsound.js")({print: (msg) => console.log(msg), printErr: (msg) console.log(msg)})
```

I'm getting the errors printed trough `print` and the stdout trough `printErr`, I assume this should be the other way around? A bonus point would be if the strings would omit the xterm color characters.

**Comment by kunstmusik** [comment]
No longer applicable due to move to wasi-sdk
