### ISSUE TITLE
fprints fails under win7

### ISSUE THREAD

**Issue by cvrn** [csound/csound#1021]
Using the example fprints.csd coming with csound (v. 6.12) the file (my.sco) is generated under
Linux and WIN7. The generated file under Linux is as expected,but the file generated on Windows is empty.

**Comment by jpffitch** [comment]
Looking at the code I was wondering if this relates to flushing the buffer.  The file is set to IOLBF by setvbuf
and the flush is commented out in the opcode.  could it be that this does not work on Windows?  I do not have access to a recent Windows computer to check.

**Comment by stekyne** [comment]
The example didn't work for me either.

https://docs.microsoft.com/en-ie/cpp/c-runtime-library/reference/setvbuf?view=vs-2017 Reading the API doc, it won't accept 0 as the size. 2 is the lowest in the range so it will fail.

**Comment by jpffitch** [comment]
I see suggestions that it should br UFSIZE but in my Linux world that is 
not defined.  If it in <stdio.h> on MSVC?  One source suggested it was.

There are many other calls to setvbuf so tis is nore that just that 
example!

**Comment by jpffitch** [comment]
If you change Opcodes/fout.c about line 1306 to use
setlinebuf(p->f.f)
does it work?

**Comment by stekyne** [comment]
That command doesn't exist for MSVC unfortunately. BUFSIZ does exist and it doesn't seem to complain. Other than that, we'd have to IFDEF out that call and put in place another one that works for MSVC.

**Comment by jpffitch** [comment]
Stephen, can you test with latest sourced from GitHub,?, I think it is fixed

⁣Sent from TypeApp ​

**Comment by stekyne** [comment]
I've tested the change, it compiles and runs without error but I'm not seeing the file output for some reason. It's probably my own mistake. Maybe the original tester can try?

**Comment by jpffitch** [comment]
OH!  That was the original complaint.

I have a plan b to use fflush instead of setvbuf.  Will look again


⁣Sent from TypeApp ​

**Comment by stekyne** [comment]
The original issue, the file was created but empty. I don't see a file at all. I'm assuming it's supposed to be in the same directory as the CSD? I'm using the fprints.csd example.

**Comment by jpffitch** [comment]
Stephen, could you try with latest commit?  I changed to using fflush and it is still OK on Linux, and hoping that it works for Windows.

**Comment by stekyne** [comment]
Still the same result for me. It looks like it should be working but I can't see where the output dir should be. At any rate, the file isn't ending up where I'm running the CSD.

**Comment by jpffitch** [comment]
Reported working now.  We will wat a while for confirmation
