### ISSUE TITLE
OSX Installer actually seems to install 6.04 rather than 6.11

### ISSUE THREAD

**Issue by melting-wax** [csound/csound#1022]
Ran the installer, tried to run CsoundQt, which complained it need 6.09 or newer. Considering it _should_ have installed 6.11, I was surprised by this, but using csound reavealed that it was actually "Csound version 6.04 (double samples) Oct 10 2015".

**Comment by vlazzarini** [comment]
I don't know how that is possible. Have you ever had 6.04 in that machine? The only thing I can think is that installation failed and you are running an older version that was installed elsewhere in the system.

You can check the date of the files in
/Library/Frameworks/CsoundLib64.framework

**Comment by vlazzarini** [comment]
Just to confirm, I have downloaded and installed 

https://github.com/csound/csound/releases/download/6.11.0/Csound6.11.0-OSX-universal.dmg

and then run it from the terminal, getting

```
MacBook-Pro:~ victor$ csound
0dBFS level = 32768.0
--Csound version 6.11 (double samples) Aug 24 2018
```

also:

```
MacBook-Pro:~ victor$ ls -l /Library/Frameworks/CsoundLib64.framework/Versions/Current/CsoundLib64 
-rwxrwxr-x  1 root  wheel  6275208 24 Aug 18:54 /Library/Frameworks/CsoundLib64.framework/Versions/Current/CsoundLib64
```

**Comment by kunstmusik** [comment]
Could be:

* there's a version of Csound in ~/Library/Frameworks that's old. This
would override /Library/Frameworks
* The version of CsoundQt maybe one where it came with its own version of
Csound framework. If you overwrote a previous CsoundQt install, I suppose
it's possible the old framework might still be there as part of the app
bundle.

**Comment by melting-wax** [comment]
@kunstmusik Yeah, it was an old version of Csound in ~/Library/Frameworks. Thanks for the help.
