### ISSUE TITLE
GEN 2 deferred size

### ISSUE THREAD

**Issue by gesellkammer** [csound/csound#1027]
When using gen 2, I get the error "deferred size for GENs 1, 23, 28 or 49 only"
I would assume that since the size is known out of the number of pargs passed, there should be no need to ask for the size of the table.

**Comment by rorywalsh** [comment]
Sounds like a good idea to me. We can currently fill a table with default values by NOT putting in all values, for instance, the following will fill a table with 1s:

```f1 0 128 2 1```

I guess if a 0 is passed the number of args should be the size, otherwise take it from the p3?

**Comment by jpffitch** [comment]
On Mon, 24 Sep 2018, Rory Walsh wrote:

> 
> Sounds like a good idea to me. We can currently fill a table with default
> values by NOT putting in all values, for instance, the following will fill a
> table with 1s:
> 
> f1 0 128 2 1

Does it?  That is not what the manual says.  It states clearly that 
additional fields are zero
"any table locations not filled will contain zeros"

Or are you wanting an incompatible change?
> 
> I guess if a 0 is passed the number of args should be the size, otherwise take
> it from the p3?
>

Could, but at present size is a power-of-two-plus-optional-one

**Comment by gesellkammer** [comment]
As I understood it, the size limitation was a limitation of some opcodes, which rely on the power-two-size to optimize indexing. In fact, I can create a gen 2 table of any size using a negative size. This report was about the possibility of, in absence of an explicit size (size=0), relying on the amount of pargs to determine this size, to be interpreted as a negative value, allowing any kind of size.

**Comment by vlazzarini** [comment]
A table of any size can be created, it does not need to have a negative size anymore (since 6.00).

**Comment by jpffitch** [comment]
So the manual should be changed?

**Comment by vlazzarini** [comment]
if it says that you need a negative number, yes.

**Comment by jpffitch** [comment]
it says must be a power of 2 or power of 2 plus guard

Just commented it out.  If my new version is OK (in git now)  will add 
that to the manual.

**Comment by vlazzarini** [comment]
I suppose we need to revise this whole area in the manual. That is, any GEN can generate tables of any size (up to the maximum). Some opcodes required table sizes of power of 2 or power of 2 + 1

**Comment by joachimheintz** [comment]
it's great to have this simplification.  thanks to john for 
implementing, and to eduardo for the idea.  first test is fine.
