### ISSUE TITLE
Mixer utility problem - segmentation violation

### ISSUE THREAD

**Issue by hjano** [csound/csound#1028]
When calling from the mixer utility from the command line under Windows 10:

mixer -F 0.4 5s_n.wav -F 0.4 A_non.wav

I get 

0dBFS level = 32768.0
--Csound version 6.11 (double samples) May 11 2018
[commit: eabe0dc8662062d4f9fd7cfcd6d9bbb2d286a495]
libsndfile-1.0.29pre1
util mixer:
audio sr = 22050, monaural
opening WAV infile 5s_n.wav
mixing 110250 sample frames (5.0 secs)
audio sr = 22050, monaural
opening WAV infile A_non.wav
mixing 92201 sample frames (4.2 secs)
WARNING: Failed to open test: Format not recognised.

mixer: error opening output file 'test': No Error.
end of score.              overall amps:      0.0
           overall samples out of range:        0
0 errors in performance
Elapsed time at end of performance: real: 0.010s, CPU: 0.010s

The resulting "test" file is empty.
When I add the -W option to make sure the default "test" file will be wav, a segmentation violation occurs:

mixer -W -F 0.4 5s_n.wav -F 0.4 A_non.wav

0dBFS level = 32768.0
--Csound version 6.11 (double samples) May 11 2018
[commit: eabe0dc8662062d4f9fd7cfcd6d9bbb2d286a495]
libsndfile-1.0.29pre1
util mixer:
audio sr = 22050, monaural
opening WAV infile 5s_n.wav
mixing 110250 sample frames (5.0 secs)
audio sr = 22050, monaural
opening WAV infile A_non.wav
mixing 92201 sample frames (4.2 secs)
writing 131072-byte blks of shorts to test.wav (WAV)
Csound tidy up: Segmentation violation

The resulting "test" file has the 44-byte wave header.
This happens with other valid wavs with sampling rates (tried 44100 Hz), and in stereo as well.

**Comment by jpffitch** [comment]
I do not understand the double arguments.  Does it work with
mixer -W -F 0.4 5s_n.wav ?

I would expect the -W to be neeed, but it should default to something like 
IRCAM format.  Will look at the code.

==John ff

**Comment by hjano** [comment]
mixer -W -F 0.4 5s_n.wav
produces the same error. 

(The double arguments should be useful for mixing the two wav files with different amplitude multiplyers)

**Comment by jpffitch** [comment]
Sorry -- ignore last message.   I have it crasing on Linux so it is geeric 
and I can investigate (but I have -W as default)

I have it fixed and will commit soon.
