### ISSUE TITLE
inch segfaults when given more than 1 channels

### ISSUE THREAD

**Issue by hlolli** [csound/csound#1030]
This here should segfault as is.

```csd
<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
nchnls_i = 2
0dbfs = 1.0

instr 1
  aIsntConnected1, aIsntConnected2 inch 0, 1
endin

</CsInstruments>
<CsScore>
i 1 0 1
</CsScore>
</CsoundSynthesizer>
```

In my use case I wanted to make an fx in my jack graph so I had these options

```csd
<CsOptions>
-iadc:null -odac:system:playback_ -B 4096 -b 1024 -+rtaudio=jack  --0dbfs=1 -+jack_client=master
</CsOptions>
```

null is here only to prevent autoconnect, otherwise csound connects to itself (feedback). In no case didn't it segfault, be it alsa or jack, or something is connected or not. I'm planing to use `ins` since I don't need more than 2 input channels, and that works fine. Just a friendly bug report.

**Comment by vlazzarini** [comment]
I suspect 0 is not allowed and should have thrown an error rather than segfaulting.

**Comment by vlazzarini** [comment]
Actually there was a bug overwriting memory when channel was set < 0. fixed in git.

**Comment by hlolli** [comment]
Another thing with `inch` as a symbol. I noticed that when I'm playing some of Hans Mikkelson's music, he uses `inch` as variable. Maybe it's unavoideable non-backwards compatability? For example newage.orc and newage.sco, if you have that somewhere, you'll see what I'm talking about.

**Comment by jpffitch** [comment]
As a general run we do not create opcodes starting with i, k or a for this 
reason.  Sometimes there are overriding reasons to break the rule.

Note a number of opcodes beginning with k were made deprecated years ago; 
maybe time to delete them

**Comment by hlolli** [comment]
What about overriding the meaning of an opcode if a variable is assigned to it, then only locally scoped? It seems to me to be a big hammer to avoid opcodes starting with i,k or a. What about f and w?

**Comment by hlolli** [comment]
Also  ga, gk, gi, gf not to be forgotten in that sense.

**Comment by hlolli** [comment]
Just an idea :) but if avoiding opcodes starting with rate indicator character is what is needed, then so it is. In lisp languages, it's common to override symbols, so it's a thing I'm used to. But the errors when I've assigned a function name to a symbol and want to call that function later on, are sometimes annoying, but it's a price to pay.
