### ISSUE TITLE
Error on multiply with zero in outs

### ISSUE THREAD

**Issue by Oeyvind** [csound/csound#1031]
An audio signal multiplied with zero as a constant gives a parser error.
The error occurs with Csound build from develop yesterday (on Sept 27th 2018).

```
<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

instr 1
a1 = rnd31(1,1)
outs a1*0.5, a1*0.0
endin

</CsInstruments>
<CsScore>
i1 0 3	
e
</CsScore>
</CsoundSynthesizer>
```

**Comment by jpffitch** [comment]
What do you expect?  There is no multiply symbol and . is not allowed in a variable.

⁣Sent from TypeApp ​

**Comment by rorywalsh** [comment]
Hi @jpffitch, I think there was a formatting issue in @Oeyvind first post. I wasn't seeing the * either.

**Comment by Oeyvind** [comment]
Yes, the code example should read :
outs a1*0.5, a1*0.0




Den fre. 28. sep. 2018, 12.56 p.m. skrev Rory Walsh <
notifications@github.com>:

**Comment by vlazzarini** [comment]
I don't get a syntax error, but this

```
SECTION 1:
new alloc for instr 1:
WARNING: Excess channels ignored
```

if I add 

```
nchnls = 1
```

it runs

**Comment by jpffitch** [comment]
Yes the optimisation would.  Should I remove it fot audio vlues or should 
we allow constants as audio rate values?

**Comment by jpffitch** [comment]
Optimisation removed in git
