### ISSUE TITLE
add optional output for pvstrace

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#1034]
pvstrace returns an f-signal containing only the N loudest bins.  can it also report which bins these are at a certain time?

perhaps there could be an additional output with an array of size fftsize/2+1, and the kn first positions of this array carry this information?

**Comment by vlazzarini** [comment]
sure, should be simple enough. I'll have a look.

**Comment by joachimheintz** [comment]
cheers!  yes, the data must be already there in the algorithm.

**Comment by joachimheintz** [comment]
how do you look for the N loudest bins if not creating a sorted list and 
take the N first elements?

**Comment by vlazzarini** [comment]
I find the position of the Nth element with a dedicated algorithm and filter out all bins that have amp below the Nth element.  Only the N loudest are kept.

**Comment by joachimheintz** [comment]
would it be easy to output the bin number and the corresponding 
amplitude?  then the user could sort it in case it is needed.

the format of the array would be bin,amp, bin, amp, ... — and the first 
N*2 elements of the array return the N loudest bins, not ordered but 
with the corresponding amps.

**Comment by vlazzarini** [comment]
that's possible, although sorting inside the opcode is faster. options

1) unsorted bins
2) sorted bins
3) unsorted bin and amp
pairs.

I guess a fourth option is to have another parameter to switch sorting on and off

**Comment by vlazzarini** [comment]
Ok, it's there now, completely untested

```
fsig, kBins[] pvstrace  fsigin, ibins[, isort]
```

**Comment by joachimheintz** [comment]
i am happy to test.  but i don't understand the syntax.  i tried:

  kBins[] init 5
  fTrace, kBins pvstrace fIn, 5, 1

but:
error:  Unable to find opcode entry for 'pvstrace' with matching 
argument types:
Found: fk[] pvstrace fcc
        fTrace pvstrace fIn ...

and (second question): did you really put the number of bins to 
init-rate now?  i hope it was a typo for k and you meant:
    fsig, kBins[] pvstrace fsigin, kbins[, isort]

**Comment by joachimheintz** [comment]
can the kBins[] array be created if not already there, as diskin and 
other opcodes do?

**Comment by vlazzarini** [comment]
yes, that's the best way to use it. I had the out and in types confused in my code, that's why it didn't work. Try it now

```
fsig,kMax[] pvstrace fsigin, kN, 1
```

**Comment by joachimheintz** [comment]
i get another error now:

INIT ERROR in instr 1 line 18: fsig format not supported
  from file /home/jh/Desktop/test_pvstrace.csd (1)
fTrace	kBins	pvstrace	fIn	5	1	
	  B  0.000 - note deleted.  i1 had 1 init errors

the code is:

  Sfile = "..."
  p3 filelen Sfile
  aIn diskin Sfile
  fIn pvsanal aIn, 1024, 256, 1024, 1
  kNumBins linseg 1, p3, 10
  fTrace, kBins[] pvstrace fIn, 5, 1
  aOut pvsynth fTrace
  out aOut, aOut




On 30/09/18 16:53, vlazzarini wrote:
> yes, that's the best way to use it. I had the out and in types
> confused in my code, that's why it didn't work. Try it now
>
> |fsig,kMax[] pvstrace fsigin, kN, 1 |
>
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub
> <https://github.com/csound/csound/issues/1034#issuecomment-425726471>,
>
>
>
>
or mute the thread

**Comment by vlazzarini** [comment]
sorry, my fault, forgot to adjust the number of ins and outs. Should be OK now.

**Comment by joachimheintz** [comment]
yes. will test more later and report.

**Comment by vlazzarini** [comment]
Tested with this

```
instr 1
  ain vco2 0dbfs, A4
  fIn pvsanal ain, 1024, 256, 1024, 1
  kNumBins linseg 1, p3, 10
  fTrace, kBins[] pvstrace fIn, 5, 1
  aOut pvsynth fTrace
  printf "%d %d %d %d %d \n", metro(10), kBins[0], kBins[1], kBins[2], kBins[3], kBins[4]
  out aOut
endin
```

got 

```
new alloc for instr 1:
0 1 2 3 4 
10 11 20 21 9 
10 11 20 21 9
```

which looks correct to me (loudest bins are the bins around 440 and 880Hz)

**Comment by joachimheintz** [comment]
i tested now, too, and all seems to work very fine.

would it be easy to add an optional parameter at which bin to start? 
frequently we want to exclude bin 0,  the input arguments could be:
	
	fSigIn, kNumBins [, iOrdered [, iFirstBin [,iLastBin]]]

where iFirstBin defaults to zero and iLastBin defaults to fftsize/2. for 
instance,

	fTrace, kBins[] pvstrace fIn, 5, 1, 1, 20

would return the 5 loudest bins, ordered, starting at bin 1, up to bin 20.

**Comment by jpffitch** [comment]
Is this issue sorted?  Just a year since the last comment.

**Comment by jpffitch** [comment]
No response since October.   I will close this soon if no one says anything.
