### ISSUE TITLE
add tabensure / array ensure to the api

### ISSUE THREAD

**Issue by gesellkammer** [csound/csound#1035]
I keep copying this function for each opcode which needs to deal with arrays, and I see the same function, with slight variations, sprinkled along the codebase. Could it be possible to add it to the api? For reference, this is the version I am using:

```c
static inline void
arrayensure(CSOUND *csound, ARRAYDAT *p, int size) {
    if (p->data==NULL || p->dimensions == 0 ||
        (p->dimensions==1 && p->sizes[0] < size)) {
        size_t ss;
        if (p->data == NULL) {
            CS_VARIABLE* var = p->arrayType->createVariable(csound, NULL);
            p->arrayMemberSize = var->memBlockSize;
        }
        ss = p->arrayMemberSize*size;
        if (p->data==NULL)
            p->data = (MYFLT*)csound->Calloc(csound, ss);
        else
            p->data = (MYFLT*) csound->ReAlloc(csound, p->data, ss);
        p->dimensions = 1;
        p->sizes    = (int*)csound->Malloc(csound, sizeof(int));
        p->sizes[0] = size;
    }
}
```

**Comment by jpffitch** [comment]
That function is replaced in the sources.

**Comment by jpffitch** [comment]
We need a good name as well, or could place in a separate file to #include

**Comment by vlazzarini** [comment]
If it is a function then it's best to place in the API. Otherwise we can make it a macro and place in a header file.

**Comment by kunstmusik** [comment]
Maybe could be kept with data types code? (csound_standard_types.c/.h)  I'd
argue let's leave it for now and design better for CS7, since we need to
expose data type handling anyways over channels for arbitrary data types,
and would need to expose more than just tabensure/arrayensure.

**Comment by jpffitch** [comment]
In effect it isthere now as a header file arrays.h

**Comment by gesellkammer** [comment]
Yes, thanks.
