### ISSUE TITLE
genarray:k(...) doesn't work

### ISSUE THREAD

**Issue by maurocsound** [csound/csound#1040]
This works:

```
kArr[]  genarray    1, 128
        printk      1, lenarray:k(kArr)
```

But this theoretically equivalent code gives to me an error message in the console output:

```
kArr[]  =           genarray:k(1, 128)
        printk      1, lenarray:k(kArr)
```

The error is:

```
error:  Unable to find opcode entry for '=' with matching argument types:
Found: k[] = @
       kArr = genarray ...
```

Why genarray doesn't accept the hint ":k" in function syntax?

**Comment by jpffitch** [comment]
Which version of csound?  Commit or date.

⁣Sent from TypeApp ​

**Comment by maurocsound** [comment]
I'm using this artifact: Csound6_x64-6.12.0-beta-2061.exe

**Comment by jpffitch** [comment]
No idea; this needs Steven I think.

**Comment by kunstmusik** [comment]
genarray:k() is trying to say k as output, not k[].  I think type hint for
functions don't work for arrays though, so you can't say genarray:k[]().
You should be able to force a krate version of genarray with:

kArr[] = genarray(k(1), 128)

**Comment by maurocsound** [comment]
Ok, I thought that with genarray:k(...) I was just suggesting Csound that I wanted the k-rate version of the overloaded genarray opcode. I didn't think about the fact that, theoretically speaking, you could overload an opcode with array-types too, but then in such cases the "opcode:k[](...)" syntax would be needed. Is this planned in Csound 7 ?

**Comment by kunstmusik** [comment]
I think you're mistaking what the :k means. It's not "k-rate version of"
it's "use the opcode with the return type of k-type vars".  You can use
chnget:S("somename") for example to use the chnget version that returns
S-type values (Strings).  That might be an opcode that is init-time only or
perf-time as well, but the type hint is not related to the rate of the
opcode.

**Comment by maurocsound** [comment]
Maybe I didn't express myself well but that's exactly what I meant in my previous message, and that's why I said Csound should allow array types too as type hints.

**Comment by maurocsound** [comment]
Ok, I opened a new issue here: https://github.com/csound/csound/issues/1043
