### ISSUE TITLE
chnget/chnset for arrays..

### ISSUE THREAD

**Issue by rorywalsh** [csound/csound#1042]
I would like to send k and i rate array data to and from a host. I don't think it's currently possible? How tricky would it be to have support for this? The current option would is to parse strings and manual assign the data at both ends, but I think passing arrays to and from a host would be extremely useful. 

Sorry if this came up before, I couldn't find an mention of it.

**Comment by kunstmusik** [comment]
https://github.com/csound/csound/issues/444 is related, we need to design
the system for all data types, including user-defined types.  CS7 work
should start after 6.12, so let's do it the right way there rather than add
array-specific features just for k or i or a-rate signals.

**Comment by rorywalsh** [comment]
Thanks Steven. For now I can just work with function tables. Not as tidy, but they will do.  Being able to pass user defined types is going to really enhance the way hosts can work with Csound. I can't wait.

**Comment by rorywalsh** [comment]
I thought of that, but then I'd have to implement OSC on the host side too. Don't really fancy doing that. Tables should be fine ;)
