### ISSUE TITLE
Grammar

### ISSUE THREAD

**Issue by nublug** [csound/csound#1044]
Not in the program, just on the website homepage itself. "Csound has traditionally being used in a..." Should be 'been'.  Probably not the right place for this, but why not? Not another easy way to tell ya! :P

**Comment by maurocsound** [comment]
There is a [github project for the website](https://github.com/csound/csound.github.io/issues) too. So, you should open the issue there and close this one. ;-)

**Comment by nublug** [comment]
Oh! Will do, thanks!
