### ISSUE TITLE
MIDI issue..

### ISSUE THREAD

**Issue by rorywalsh** [csound/csound#1045]
I'm having an odd MIDI issue which I can't get to the bottom off. I have the following simple instrument which outputs a MIDI note at a fixed rate with -Q0. MIDI is also opened for reading with -M0 (this in itself could be the issue). If I trigger a note out using ```noteondur2 1, 60, 120, 1``` at the same time as I play a MIDI note in, ```noteondur``` will play the current MIDI note rather than note 60. Is this expect behaviour?  Code is here:

```
massign 1, -1; prevent triggering of instrument with MIDI

instr 2
    if metro(1) == 1 then
    event "i", 3, 0, 1
    endif
endin

instr 3
    noteondur2 1, 60, 120, .5
endin
```

I know it's hard to test this unless you have devices that can send and receive MIDI. I recording a short [screencast](https://www.dropbox.com/s/v9i7sk7bz9ofqe1/MIDIIssue.mov?dl=0) of the issue within Ableton Live. As far as I understand, I shouldn't be hearing any note but c60. There is no MIDI thru, so any notes other than 60 are somehow slipping through the net. 

Any ideas?

**Comment by vlazzarini** [comment]
Sorry I can't reproduce this issue here on Mac OSX (6.11) using CsoundQT or the terminal,
or using the latest from the repo.

**Comment by rorywalsh** [comment]
Can you explain how you tested it exactly? I'd like to recreate your test
here to see if it's a problem only on Windows.

**Comment by rorywalsh** [comment]
I'll try with Live on OSX tomorrow and see if I can produce the same
results as on Windows.

**Comment by rorywalsh** [comment]
Same problems with Live on OSX, but no issues from the command line like you said. (I missed your setup details yesterday, hence the question about it).

If I remove the `noteondur` opcode I got no notes slipping through in Live. I'm sure the unwanted notes are being played with `noteondur`, but I can't figure out why.

**Comment by vlazzarini** [comment]
Well, if it were the opcode, then the command-line would also confirm it. Is this your own MIDI backend?

**Comment by vlazzarini** [comment]
So you are implementing your own MIDI backend.
You should try Cabbage outside of Ableton in the same arrangement as you tested the command-line, then you will know better.

**Comment by vlazzarini** [comment]
Removing noteondur should have the effect of the MIDI output callback being non-op (as the number of bytes to be sent out is 0). If for some reason the buffer is being shared between input and output, you need the callback to be called with nbytes > 0 for that to become apparent in the output.

**Comment by rorywalsh** [comment]
Thanks Victor. I'll take a look at that. I'll close this out now.
