### ISSUE TITLE
linenr issue reappeared

### ISSUE THREAD

**Issue by Oeyvind** [csound/csound#1048]
This issue was fixed (ca April 2016), but has reappeared now.
When using linenr, and p3 is shorter than the attack time, there is a discontinuity in the envelope.
From the value reached by the attack segment, it jumps to 1.0 and processes the release segment from there. Rather, it should process the release segment from the value reached by the incomplete attack segment.

```
<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

	sr = 48000
	ksmps = 64
	0dbfs = 1

	instr 1
        iamp    = ampdbfs(p4)
	icps    = cpsmidinn(p5)
        iattack = 0.5
        idecay  = 0.5
        isust   = 0.5
        irel    = 0.5
	
	amp	linenr 1, iattack, irel, 0.01
	; for the first score event, linenr jumps to 1 after p3 and does the release segment from there
	; this creates an unexpected discontinuity
	; it would be better if it process the release segment from the value reached by the incomplete attack segment
	; as is the case if we use linsegr instead of linenr, see next line:
	; amp	linsegr 0, iattack, 1, idecay, isust, irel, 0
	a1	oscili amp*iamp, icps
		out a1
	endin


</CsInstruments>
<CsScore>
;	start	dur	amp     note
i1	0	0.2     -10     72
i1	1	0.7     .       .
i1	3	1.2     .       .
i1	5	2.2     .       .
f0 8
e
</CsScore>
</CsoundSynthesizer>

```

**Comment by jpffitch** [comment]
Code was changed 2018 Jan 26 I note, but not sre why; also cosmetic 
changes in 2018 Feb 6

Time to lookat January.....

**Comment by jpffitch** [comment]
Believed fixed in github now

**Comment by Oeyvind** [comment]
Actually, no, it seems that the release stage is not processing the
envelope now.
The note is extended by the time specified in the release segment, but the
envelope stays at 1 during the release segment.

Den man. 15. okt. 2018 kl. 16:05 skrev John ffitch <notifications@github.com

**Comment by jpffitch** [comment]
OK not what I saw.  Will look again

⁣Sent from TypeApp ​

**Comment by Oeyvind** [comment]
Do you see the behaviour I describe when rendering the example csd?


Den tir. 16. okt. 2018 kl. 12:46 skrev John ffitch <notifications@github.com

**Comment by jpffitch** [comment]
I changed the example so it was stereo, left your example and right linsegr
The first note looked the same both.  Not at computer yet.  Few more minutes

⁣Sent from TypeApp ​

**Comment by jpffitch** [comment]
OK; my mistake.  Will try again
```<CsoundSynthesizer>

<CsInstruments>
sr = 48000
ksmps = 64
0dbfs = 1
nchnls = 2

instr 1
    iamp    = ampdbfs(p4)
    icps    = cpsmidinn(p5)
    iattack = 0.5
    idecay  = 0.5
    isust   = 0.5
    irel    = 0.5

    amp     linenr 1, iattack, irel, 0.01
; for the first score event, linenr jumps to 1 after p3 and does the release segment from there
; this creates an unexpected discontinuity
; it would be better if it process the release segment from the value reached by the incomplete 
; attack segment as is the case if we use linsegr instead of linenr, see next line:
        amp1   linsegr 0, iattack, 1, idecay, isust, irel, 0
a0      oscili  amp*iamp, icps
a1      oscili  amp1*iamp, icps
          out    a0,a1
endin

</CsInstruments>

<CsScore>
; start dur amp note
i1 0 0.2 -10 72
i1 1 0.7 . .
i1 3 1.2 . .
i1 5 2.2 . .
f0 8
e

</CsScore>

</CsoundSynthesizer>
```

**Comment by jpffitch** [comment]
Try now from github.  I runs my test OK

**Comment by Oeyvind** [comment]
confirmed.
 All ok here too,
and tested all release segment envelopes for completeness.
all ok.


Den tir. 16. okt. 2018 kl. 18:32 skrev John ffitch <notifications@github.com
