### ISSUE TITLE
build csound6~ object for windows 64 bit

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#1053]
the last build of the csound6~ object for pd was 32 bit (i think in the csound 6.07 installer).
for using csound inside pd, a 64 bit version to add to https://github.com/csound/csound_pd/releases would be necessary for most systems.

**Comment by vlazzarini** [comment]
I think so.

**Comment by vlazzarini** [comment]
In fact, the csound pd project is CMake-based, so it could be just a case of building it on Windows, in the presence of a Csound installation.

**Comment by vlazzarini** [comment]
moved https://github.com/csound/csound_pd/issues/7
