### ISSUE TITLE
issue in r2c example

### ISSUE THREAD

**Issue by Oeyvind** [csound/csound#1054]
An issue surfaced with recent csound versions (sometime after May 2018), where an orchestra of mine will crash. Part of the issue seems related to r2c, so I tested the r2c example in the manual. There is an error message here from ifft

error: syntax error, unexpected T_IDENT  (token "ifft") from file r2ctest.csd (1)
 line 19:
>>> kCmplx ifft  <<<

Although r2c seems to not complain here, 
I thought it relevant to bring the ifft error in as an issue.

```
<CsoundSynthesizer>
<CsOptions>
-d -o dac
</CsOptions>
<CsInstruments>
ksmps = 64

instr 1
ifftsize = 1024
kcnt init 0
kIn[] init  ifftsize
kOut[] init ifftsize

a1 oscili 0dbfs/2, 440

if kcnt >= ifftsize then
 kCmplx[] r2c kIn
 kSpec[] fft kCmplx
 kCmplx ifft kSpec
 kOut c2r kCmplx
 kcnt = 0 
endif

kIn[] shiftin a1
a2 shiftout kOut
kcnt += ksmps
   out a2
endin
</CsInstruments>
<CsScore>
i1 0 10
</CsScore>
</CsoundSynthesizer>
```

**Comment by vlazzarini** [comment]
This must have been a leftover from development. The opcode used to be called ifft but then was changed to fftinv.
