### ISSUE TITLE
array version of passign

### ISSUE THREAD

**Issue by gesellkammer** [csound/csound#1057]
A version of `passign` which outputs an array would be very helpful, since the data can be further manipulated using the array opcodes

Something like

iArgs[] passign iStart [, iEnd]

**Comment by jpffitch** [comment]
Simple version without iEnd and ignoring strings written

Will consider adding iEnd to this and simpler version

**Comment by jpffitch** [comment]
Written, lightly tested, not yet in manual

**Comment by gesellkammer** [comment]
Works as expected, thanks!
