### ISSUE TITLE
Csound file output..

### ISSUE THREAD

**Issue by rorywalsh** [csound/csound#1060]
I'm not sure if this is a fault of Csound or not, but I can't get SciPy to read any files that have been created by Csound. I get the following error:

`Traceback (most recent call last):
  File "spectro.py", line 11, in <module>
    samplingFrequency, signalData = wavfile.read(filenameWithPath)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/io/wavfile.py", line 236, in read
    file_size, is_big_endian = _read_riff_chunk(fid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/io/wavfile.py", line 168, in _read_riff_chunk
    "understood.".format(repr(str1)))
ValueError: File format b'FORM'... not understood.`

They won't can't play in html5 either. The only workaround is to open them in a DAW and re-save. If you feel this is more of an issue with the other tools mentioned please feel free to close it, but it would be nice if these tools could work together. Btw, it's teh same if I use `-o filename.wav` or the `fout` opcode.

**Comment by vlazzarini** [comment]
soundfiles are created by libsndfile, not Csound, so if there is an issue with them, it needs to be followed up there.

**Comment by vlazzarini** [comment]
Just tested and could not reproduce the problem, using the following script

```
from pylab import *
from scipy.io import wavfile
import sys
name = sys.argv[1]

figure(figsize=(8,3))
(sr,sig) = wavfile.read(name)
start = 1000000
dur = 2048
plot(sig[start:dur+start]/32768., 'k', linewidth=2)
xlim(0,dur)
ylim(-1.1, 1.1)
xticks([])
tight_layout()
show()
```
on MacOS, Python 2.7 and Python 3.6.5

**Comment by rorywalsh** [comment]
Thanks for testing. Might just be something weird with my Csound setup then. I'll close for now and try again tomorrow.
