### ISSUE TITLE
can setMessageCallback strings be simplified?

### ISSUE THREAD

**Issue by hlolli** [csound/csound#1062]
In any csoundAPI that I use that imports `csound64.h`, the messageCallback strings tend to be pain. I've seen some API's print these out just right, so it could be that I'm doing something wrong. To clarify what is happening for me, then here are some examples, of messages being broken down into multiple callbacks (and therefore multiple strings).

amps:

```
"  rtevent:\t   T  2.968 TT  2.968 M:"
"      0  "
"      0  "
"\n"
"new alloc for instr 1:\n"
```

prints:

```
"instr 0:"
"  2 = 2.000"
"\n"
```

token error (for endinn):

```
"\nerror: syntax error, unexpected NEWLINE  (token \"\n\")"
" line 5:\n>>>"
" "
" "
" "
" "
" "
" "
" "
"e"
"n"
"d"
"i"
"n"
"n"
" <<<\n"
"Unexpected untyped word endinn when expecting a variable\n"
"Parsing failed due to invalid input!\n"
"Stopping on parser failure"
"\n"
```

I compensate these usually by queueing these messages up and concat in the end them when a string arrives which I expect to be the last of a single message bundle. Better would be if one message line arrived as 1 solid string from csound from the beginning.

But I imagine when this is printed into a terminal, then it wont matter, where newline isn't emitted on every print (or just print vs println). But printing this into a browser dom (like with wasm), into emacs buffer (my emacs csound-repl), or in my most common case Clojure. Then it's not certain that everything is in sequence, or a terminal is what is being printed on.

**Comment by rorywalsh** [comment]
Have you looked at the message buffer methods? You have to poll for messages, but I find it simpler and less prone to problems.

**Comment by hlolli** [comment]
Yes I've used that before. I think I use that in my emacs package. But creating a buffer in my host language does the exact same. So it won't avoid how the strings are passed.

That said, I did realize that I can cope with this data in most cases by avoiding println and just use print, in most cases. So this isn't such a big deal maybe that it behaves like this. But for wasm it would be cool still to append <p> elements to every message callback, for that to behave well, this would need to arrive in lines (the strings).

**Comment by vlazzarini** [comment]
I had a problem with the Emscripten-produced binary where newlines were being inserted. I spent some time replicating the problem until they agreed it was a problem at their end.

Csound's message callback system works correctly if the host does not mess up by introducing newlines. What happens is that code inside Csound and in opcodes will sometimes break the string into multiple calls to csoundMessageCallback() for various reasons, and that will not work correctly if line breaks are inserted in the stream.

I am closing this as there is nothing to do about this.
