### ISSUE TITLE
Did you accidentally lose the 'ro' translation?

### ISSUE THREAD

**Issue by yurivict** [csound/csound#1065]
It was present in ```6.06.0``` and is absent from ```6.12.2```.

**Comment by jpffitch** [comment]
The ro translation was almost empty; morea promise than of any use.

I still have the old files if anuyone wants to assist wit a Romanian 
translation

**Comment by yurivict** [comment]
I only reported it because I noticed that it disappeared. Otherwise, I don't care about translations.
