### ISSUE TITLE
Warning 453: Can't apply (std::vector< double > *INPUT). No typemaps are defined.

### ISSUE THREAD

**Issue by yurivict** [csound/csound#1066]
It prints this warning:
```
Starting language-specific parse...
/usr/ports/audio/csound6/work/csound-6.12.2/interfaces/CppSound.hpp:37: Warning 453: Can't apply (std::vector< double > *INPUT). No typemaps are defined.
```

**Comment by jpffitch** [comment]
Yes it does

**Comment by jpffitch** [comment]
I always ignore this having no idea what it means;  just another example of C++ obscurity.

**Comment by yurivict** [comment]
> I always ignore this having no idea what it means; just another example of C++ obscurity.

No, it's the obscurity of swig. Swig is a bad idea.
