### ISSUE TITLE
Linear algebra plugin is broken: no matching function for call to 'lu_factor'

### ISSUE THREAD

**Issue by yurivict** [csound/csound#1069]
```
/usr/ports/audio/csound6/work/csound-6.12.2/Opcodes/linear_algebra.cpp:3504:14: error: no matching function for call to 'lu_factor'
    *isize = gmm::lu_factor(lhs->mr, pivot__);
             ^~~~~~~~~~~~~~
/usr/local/include/gmm/gmm_dense_lu.h:129:13: note: candidate function not viable: cannot bind base class object of type 'std::vector<size_t>' (aka 'vector<unsigned long>') to derived class reference 'gmm::lapack_ipvt &' for 2nd argument
  size_type lu_factor(DenseMatrix& A, lapack_ipvt& ipvt) {
            ^
/usr/ports/audio/csound6/work/csound-6.12.2/Opcodes/linear_algebra.cpp:3541:14: error: no matching function for call to 'lu_factor'
    *ksize = gmm::lu_factor(lhs->mr, pivot__);
             ^~~~~~~~~~~~~~
/usr/local/include/gmm/gmm_dense_lu.h:129:13: note: candidate function not viable: cannot bind base class object of type 'std::vector<size_t>' (aka 'vector<unsigned long>') to derived class reference 'gmm::lapack_ipvt &' for 2nd argument
  size_type lu_factor(DenseMatrix& A, lapack_ipvt& ipvt) {
            ^
/usr/ports/audio/csound6/work/csound-6.12.2/Opcodes/linear_algebra.cpp:3575:14: error: no matching function for call to 'lu_factor'
    *isize = gmm::lu_factor(lhs->mc, pivot__);
             ^~~~~~~~~~~~~~
```

**Comment by vlazzarini** [comment]
I suspect you have the wrong version of gmm. It builds elsewhere, so it is definitely not broken,@gogins may be able to help.

**Comment by yurivict** [comment]
I have:
```
gmm++-5.3                      Generic matrix template library
```

Repology says that this is the latest version: https://repology.org/metapackage/gmm++/versions

**Comment by gogins** [comment]
In that case define a preprocessor macro GMM_VERSION as something. The GMM
library should do this, but does not. This code

#if defined(GMM_VERSION)
  gmm::lapack_ipvt pivot__;
#else
  std::vector<size_t> pivot__;
#endif

conditionally compiles for the type the GMM library actually uses for the
LU pivots.

Hope this helps,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by jpffitch** [comment]
But csound does not use the latest version.  Been discussed recently

⁣Sent from TypeApp ​

**Comment by gogins** [comment]
But the BSD packager may use the latest version.

Best,
Mike

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by yurivict** [comment]
This workaround works, thanks!
