### ISSUE TITLE
Csound finds libmusicxml but doesn't link with it

### ISSUE THREAD

**Issue by yurivict** [csound/csound#1073]
configure finds it:
```
-- Found MUSICXML: /usr/local/lib/libmusicxml2.so
```
But leaves ```HAVE_MUSICXML2``` undefined, and doesn't link binaries with ```libmusicxml2.so```.

**Comment by vlazzarini** [comment]
I've fixed CMakeLists.txt to set this variable. Updated FindMUSICXML.cmake to look for libmusicxml2.so as well.
