### ISSUE TITLE
Error compiling: missing 'elements.h'

### ISSUE THREAD

**Issue by kmkrebs** [csound/csound#1077]
I've been successfully building from git for ages, but recently I'm getting an error during compilation:

```
[ 77%] Building CXX object interfaces/CMakeFiles/libcsnd6.dir/CsoundFile.cpp.o
/home/kmkrebs/git/csound/interfaces/CsoundFile.cpp:38:10: fatal error: elements.h: No such file or directory
 #include "elements.h"
          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [interfaces/CMakeFiles/libcsnd6.dir/build.make:76: interfaces/CMakeFiles/libcsnd6.dir/CsoundFile.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2398: interfaces/CMakeFiles/libcsnd6.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```
If it helps, I'm running Antergos Linux (based of Arch).

**Comment by vlazzarini** [comment]
looks like it thinks you have MUSICXML2

**Comment by vlazzarini** [comment]
Check in your CMake configuration for this line
```
-- Could NOT find MUSICXML (missing:  MUSICXML_LIBRARY MUSICXML_INCLUDE_DIR)
```

It should be there if you don't have  MUSICXML2 installed. If the token `HAVE_MUSICXML2` is
defined, then it will look for the elements.h header.

**Comment by kmkrebs** [comment]
I checked the CMake output and saw:
`-- Found MUSICXML: /usr/lib/libmusicxml2.so`

I confirmed that MusicXML is installed with my package manager, too.

**Comment by vlazzarini** [comment]
ok, something's wrong with this musicxml code. I've commented out the token setting code, which should fix the build for you.

**Comment by kmkrebs** [comment]
Thanks for the quick attention. I can successfully compile with the latest update.
