### ISSUE TITLE
error: static declaration of 'psignal' follows non-static declaration

### ISSUE THREAD

**Issue by yurivict** [csound/csound#1081]
```
/usr/ports/audio/csound/work/csound-6.12.2-58-g9b2523f90/Top/csound.c:1164:13: error: static declaration of 'psignal' follows non-static declaration
static void psignal(int sig, char *str)
            ^
/usr/include/signal.h:119:6: note: previous declaration is here
void    psignal(int, const char *);
        ^
1 error generated.
```

**Comment by yurivict** [comment]
You need to build with gcc+clang. gcc just doesn't catch errors any more. This happens all the time with different projects.

**Comment by vlazzarini** [comment]
psignal is a  C library function

https://www.freebsd.org/cgi/man.cgi?query=psignal&sektion=3&apropos=0&manpath=freebsd

**Comment by kunstmusik** [comment]
This is building alright Ubuntu Xenial with Clang 7:

https://travis-ci.org/csound/csound/jobs/462288700

OSX Clang also builds.  

@yurivict Is this on FreeBSD 11.2? I downloaded a VHD and am setting something up now for development to see if I can reproduce.

**Comment by kunstmusik** [comment]
I can reproduce here on 11.2, looking at it now.

**Comment by kunstmusik** [comment]
I can get past the first issue if I add an additional check for !defined(__FreeBSD__) around line 1024 in csound.c. After that, I get issues with fdclose being defined in prototyp.h not matching up with fdclose defined in /usr/include/stdio.h, then issues with no PTHREAD_SPINLOCK_INITIALIZER being defined.  

For fdclose, we can rename that and other fd* functions in prototyp.h and within our codebase. @jpffitch and @vlazzarini can you confirm that this is okay to do?  Seems better to do so like we did with mmalloc.

I suspect the other issues with PTHREAD would have to do with some assumptions that don't hold true for FreeBSD as it does for Linux, OSX, and MinGW.  

We don't have any maintainers who use/work with FreeBSD, and I suspect not many in the user community either if this is the first time we're hearing about these issues.  I can try to look at this when I can, but someone with more time could probably do a better/faster job at this.

**Comment by yurivict** [comment]
> I suspect the other issues with PTHREAD would have to do with some assumptions that don't hold true for FreeBSD as it does for Linux, OSX, and MinGW.

On FreeBSD, you need to build from the port: ```cd /usr/ports/audio/csound && make install```.
There are patches there that resolve all such issues.

For other revisions, lines like these need to be added:
```
DISTVERSION=    6.12.2-63
DISTVERSIONSUFFIX=      -g850b96227
```
and ```make makesum``` should be run.

**Comment by jpffitch** [comment]
I have renamed fdclose and in doing so I noted it is in the CSOUND structure.  psignal is only static in some OS.  (android, cygwin and beos)

Did not understand the last comment from yurivict

**Comment by fsateler** [comment]
> I can get past the first issue if I add an additional check for !defined(**FreeBSD**) around line 1024 in csound.c.

Why not add a check for psignal in cmake? It's better than guessing which OSes have it.

**Comment by fsateler** [comment]
> There are patches there that resolve all such issues

@yurivict maybe they could be posted as PR so that they can be integrated?

**Comment by jpffitch** [comment]
9 months and no response.  Will close issue if no response by the end of the month
