### ISSUE TITLE
regression in String handling

### ISSUE THREAD

**Issue by fsateler** [csound/csound#1087]
Forwarded from the [Debian BTS](https://bugs.debian.org/916047). Consider this CSD:

```csd
<CsoundSynthesizer>
<CsInstruments>
0dbfs=1
sr=44100
nchnls=4

instr 1, 10
  Sfile strget p4
  amic = 0
  a1, a2 diskin Sfile, 0.997, -2.3

  vincr amic, a1
  outq amic, amic, amic, amic
endin

</CsInstruments>
<CsScore>
i 10.000244140625 10.135534524917603 -1 "/home/hartmans/.cache/djcli/Bobina - Music Box (Album Mix).wav" 1 1.0 10.135534524917603 0.0 422.2395255249176 1.0 0 50 1.0
f0 20.0
</CsScore>
```

Running this with current git develop yields the following error:

```
INIT ERROR in instr 10 line 9: diskin2: /home/hartmans/.cache/djcli/Bobina - Music Box (AlbumMix).wav: failed to open file (No Error.)
```

Note that the file lost a space between Album and Mix.

I have tracked down the error to commit e33cd5ab895868469b6e374feb9ffdcdea82aa27 , and indeed, reverting that commit fixes the problem.

It seems to me the match for NM is too broad.

**Comment by jpffitch** [comment]
Whoops!  Stupidity wins again! I think it is fixed now, or at least it 
runs your example. In github now

**Comment by fsateler** [comment]
Thanks! This appears fixed now
