### ISSUE TITLE
hetro wrong analysis

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#1090]
the hetro analysis has a major and a minor issue.
1. major issue
the analysed frequency is wrong.  a hetro analysis of a sine with 400 hz with these settings:
  hetro -s44100 -f200 -h3 -n4 sine_400hz.wav hetro_200_3_4.het
returns this output:
>>
0dBFS level = 32768.0
--Csound version 6.13 beta (double samples) Nov 10 2018
[commit: e5073d3f22c77c5bfa270d51db31a3266671ef56]
libsndfile-1.0.27
util hetro:
audio sr = 44100, monaural
opening WAV infile sine_400hz.wav
analysing 44096 sample frames (1.0 secs)
analyzing harmonic #0
freq estimate  200.0, max found  200.0, rel amp   11.8
analyzing harmonic #1
freq estimate  400.0, max found  449.9, rel amp 1802258.5
analyzing harmonic #2
freq estimate  600.0, max found  600.0, rel amp   11.8
scale = 0.018181
harmonic #0:	amp points 1, 	frq points 1,	peakamp 0
harmonic #1:	amp points 3, 	frq points 3,	peakamp 32766
harmonic #2:	amp points 1, 	frq points 1,	peakamp 0
wrote %64 bytes to hetro_200_3_4.het
<<
the breakpoints for harmonic #1 in the file hetro_200_3_4.het are indeed showing this 449 hz maximum:
-1,0,0,249,32766,749,0,32767
-2,0,400,249,449,749,449,32767

and that is how it sounds in the resynthesis: a fast glissando from 400 to 449 hertz:
-> hetro.csd (inlcluded in the -zip attachment)

2. minor issue
the terminal output reports 449.9 as frequency, but in the file 449 is written.  so there might be a mistake in only writing the integer part in the analysis file.

[hetro.zip](https://github.com/csound/csound/files/2683067/hetro.zip)

**Comment by jpffitch** [comment]
First response -- if you use the old format is it still wrong?

Will take me a while to understand the code as it is years since i last looked

**Comment by joachimheintz** [comment]
thanks.

how to use the old format?  i tried with the sdif output, and the result 
was the same.

**Comment by jpffitch** [comment]
Old format is -x but I checked it.  Work going on

⁣Sent from TypeApp ​

**Comment by jpffitch** [comment]
Looking at your minor issue as far as I can tell as yet the magnitude and frequency are stored as 16bit ints and as such have no fractional part  It has always been thus; looking at code from the early 1990s.

I answered the question about old format - results identical.
Showing my ignorance what do you expect it to report and synthesis like?

**Comment by joachimheintz** [comment]
thanks for looking into it.

i expect that for the simple case i added as example (sine = 400 hz) the 
frequency does not rise to a value of 449 hz after 249 milliseconds. 
this is clearly wrong, and i was told that it was not like this in the 
1990s, so i was hoping that any commit induced this bug.

**Comment by jpffitch** [comment]
I have a 1987 version almost running and unfortunately it generates a different format and much less running information.  It also does not settle on 400Hz but  think 459Hz.  I do not know the algorithm but the code has not changed substantially since 2000.  Do you have a source for the algorithm?

**Comment by joachimheintz** [comment]
no but i asked my collegue who was using hetro with different results in 
the 90s.  perhaps he can find something which helps.

**Comment by jpffitch** [comment]
Slight correction -- feeding the 1987 version with a 16bit raw 44100Hz and -h3 -n2 (and initial guess of 200Hz) gives analysis well-nigh perfect; I reformatted the output to text)
HETRO 
-1,0,0,1102,999,999,
-2,0,200,1102,181,181,
-1,0,0,1102,7, 7,
-2,0,400,1102,181, 181,
-1,0,0,1102,2,2,
-2,0,600,1102,181,181

so something has changed.

**Comment by jpffitch** [comment]
I have a version that gets the frequency correct, but all amplitudes are zero(!).  Not sure what I have done wrong but will look soon.

**Comment by jpffitch** [comment]
I have a version that gets the frequency correct, but all amplitudes are zero(!).  Not sure what I have done wrong but will look soon.

**Comment by jpffitch** [comment]
Improvements.  Analysis is correct but the resulting break-point file when rendered with your program has a short fade-in to start and a very long fade-out and essentially no sustain.   With n=2 this results in silence.  If I up the n to say 50mthe affect it clearer.

I am not sure what to expect

**Comment by joachimheintz** [comment]
sounds promising.  once you have a version which is good to test, please 
let me know.

**Comment by joachimheintz** [comment]
first test is successful!
i have asked my hetro-using collegues to test, too.  i will report.

**Comment by joachimheintz** [comment]
all tests successful -- thanks john!!
from my part, in can be closed.
