### ISSUE TITLE
add array output to loscilx

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#1098]
as loscilx can read up to 16 audio channels from a table, it would be nice to have an audio array as output here, like
  aArr[] loscilx xamp, kcps, ifn [, iwsize, ibas, istrt, imod, ibeg, iend]
as in diskin, the array would be generated automatically with the same size as the number of channels is.

**Comment by jpffitch** [comment]
I looked at the code for this and it is remarkably difficult without duplicating the entire collection of functions.
Having said that I have a version written.  Could you provide an example to see if it is correct?

**Comment by jpffitch** [comment]
Just to add it runs an array version of the manual example.  But may need more testing.

**Comment by jpffitch** [comment]
OK; will close.
--sample-accurate was different in array version and I expected it to work.  Still uncertain about the original case
