### ISSUE TITLE
tableiw not deprecated

### ISSUE THREAD

**Issue by Oeyvind** [csound/csound#1099]
When using the tableiw opcode in a csd, I get the warning

opcode deprecatedWARNING: Opcode "tableiw" is deprecated

I assume this is not correct(?)

**Comment by vlazzarini** [comment]
I think it is, tablew provides the same functionality, afaik.

**Comment by Oeyvind** [comment]
Yes, but will it write only once?
Say e.g.
tablew isig, indx, ifn
Does this write once, or on every k-pass?

Den tir. 8. jan. 2019 kl. 15:03 skrev vlazzarini <notifications@github.com>:

**Comment by vlazzarini** [comment]
this confirms it. 
../Engine/entry1.c:  { "tablew",  S(TABL),TW, 1,    "",   "iiiooo", (SUBR)tablew_init, NULL, NULL},

it means that there is an overload of tablew to match tablew isig, indx, ifn that will run only at
init time.

**Comment by Oeyvind** [comment]
Ok. Thanks.
In the meantime I also tested it, and confirm that it works this way.
Then maybe the manual should be updated to reflect this.


Den ons. 9. jan. 2019 kl. 09:34 skrev vlazzarini <notifications@github.com>:

**Comment by vlazzarini** [comment]
Ok I thought it was. I'll open up a ticket there.
