### ISSUE TITLE
testPerfThread hangs on mips

### ISSUE THREAD

**Issue by fsateler** [csound/csound#1103]
Build failure was observed on debian buildds: https://buildd.debian.org/status/fetch.php?pkg=csound&arch=mips&ver=1%3A6.12.2~dfsg-2&stamp=1545519725&raw=0

There is apparently a deadlock in which the main thread is waiting on the perf thread, and the perf thread is waiting on the recording thread, but apparently nobody told the recording thread to stop.

The following diff (which was applied as a workaround in the debian package) appears to fix the issue, but I'm not sure if this is the correct fix. It looks a bit better to me anyway: the recording thread should not survive the perf thread, or should it?

```diff
diff --git a/interfaces/csPerfThread.cpp b/interfaces/csPerfThread.cpp
index 842201a02..f9e854583 100644
--- a/interfaces/csPerfThread.cpp
+++ b/interfaces/csPerfThread.cpp
@@ -676,15 +676,15 @@ int CsoundPerformanceThread::Join()
     int retval;
     retval = status;
 
-    if (perfThread) {
-      retval = csoundJoinThread(perfThread);
-      perfThread = (void*) 0;
-    }
     if (recordData.running) {
         recordData.running = false;
         csoundCondSignal(recordData.condvar);
         csoundJoinThread(recordData.thread);
     }
+    if (perfThread) {
+      retval = csoundJoinThread(perfThread);
+      perfThread = (void*) 0;
+    }
 
     // delete any pending messages
     {
```

**Comment by vlazzarini** [comment]
I think you are right. The code is by Andres, we coukd ask him.

**Comment by fsateler** [comment]
cc @mantaraya36

**Comment by mantaraya36** [comment]
Yes, that makes sense. The recording thread should be joined before the perf thread

**Comment by vlazzarini** [comment]
Thanks for confirming  @mantaraya36. @fsateler can you submit a PR?
