### ISSUE TITLE
Wrong case for CoreMIDI framework leading to framework not found by compiler

### ISSUE THREAD

**Issue by darius522** [csound/csound#1105]
While trying to compile csound-2555792 on macOS 10.14.3 using LLVM-GCC compiler from latest Xcode dev:
```
ld: framework not found CoreMidi
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libcmidi.dylib] Error 1
make[1]: *** [InOut/CMakeFiles/cmidi.dir/all] Error 2
```
Going in manually and changing "CoreMidi" to "CoreMIDI" in ⁨"InOut⁩ ▸ ⁨CMakeFiles⁩ ▸ ⁨cmidi.dir⁩" seemed to do the trick for me.

Seems like the issue was already addressed and fixed few years ago (sf bugs #148) but somehow reintroduced ?

**Comment by vlazzarini** [comment]
fixed in git
