### ISSUE TITLE
ogg files with csound-wasm

### ISSUE THREAD

**Issue by rorywalsh** [csound/csound#1107]
It seems .ogg files cannot be read in csound-wasm using diskin2. I get the following error:

`INIT ERROR in instr 1 line 8: [mdiskin2: 1.ogg: failed to open file (File contains data in an unimplemented format.)[m
`

I'm sure I'm importing the files correctly because swapping it out for a .wav works fines.

**Comment by jpffitch** [comment]
ogg files are read with libsndfile so the library must be deficient.

**Comment by vlazzarini** [comment]
I guess we will need to build and link libsndfile to these libs statically.

**Comment by rorywalsh** [comment]
Any updates on this? Is it a big job?

**Comment by vlazzarini** [comment]
needs a little time to figure out how to build the libsndfile dependencies and then make libsndfile link to it.

**Comment by rorywalsh** [comment]
Thanks Victor. I'm not familiar with how you prepare these WASM packages, but I'm happy to test it once some headway has been made.

**Comment by rorywalsh** [comment]
Thanks @kunstmusik, I'm not able to use .ogg and .flac files with CsoundWASM. I'll close this out.

**Comment by kunstmusik** [comment]
(I'm pretty sure @rorywalsh meant to say "now" rather than "not". 😄 )

**Comment by rorywalsh** [comment]
I could edit it, but it wouldn't be as funny then!
