### ISSUE TITLE
{ statements in score produce segfault

### ISSUE THREAD

**Issue by adamfreese** [csound/csound#1108]
I'm using Csound 6.12.2-2 on Arch Linux, but get the same error in the same cases with the latest development version. Minimal working example:

```
<CsoundSynthesizer>

<CsOptions>
-odac
</CsOptions>

<CsInstruments>
sr = 44100
kr = 4410
ksmps = 10
nchnls = 1
0dbfs = 1

instr 1
  aMono oscil 1/6, p4, 1
  out aMono
endin

</CsInstruments>

<CsScore>

f1   0  4096  10   1

t 0 192

i1      0     1     440
{2 cnt
i.      +     .     .
}

</CsScore>
</CsoundSynthesizer>
```

**Comment by vlazzarini** [comment]
I can confirm this is also segfaulting on MacOS

**Comment by vlazzarini** [comment]
But it does not segfault when running under the debugger. So I suspect it might be some memory issue,.

**Comment by vlazzarini** [comment]
actually now I managed to have a couple of runs outside the debugger with no problems as well. 
```
MacBook-Pro:debug victor$ ./csound loop.csd
time resolution is 1000.000 ns
0dBFS level = 32768.0
--Csound version 6.13 beta (double samples) Jan 24 2019
[commit: 2555792234804534abb8351c981e43b71330c478]
libsndfile-1.0.28
UnifiedCSD:  loop.csd
STARTING FILE
Creating options
Creating orchestra
closing tag
Creating score
rtaudio: PortAudio module enabled ...
using callback interface
rtmidi: PortMIDI module enabled
Elapsed time at end of orchestra compile: real: 0.002s, CPU: 0.002s
sorting score ...
	... done
Elapsed time at end of score sort: real: 0.002s, CPU: 0.002s
graphics suppressed, ascii substituted
0dBFS level = 1.0
orch now loaded
audio buffered in 1024 sample-frame blocks
PortAudio V19-devel (built Feb 12 2010 09:42:54)
   0: dac0 (Built-in Output [Core Audio])
   1: dac1 (Soundflower (2ch) [Core Audio])
   2: dac2 (Soundflower (64ch) [Core Audio])
   3: dac3 (Aggregate Device [Core Audio])
PortAudio: selected output device 'Built-in Output'
writing 1024 sample blks of 64-bit floats to dac
SECTION 1:
ftable 1:
ftable 1:	4096 points, scalemax 1.000
               .-''''''-._
            _-'           '.
          _-                '.
         -                    '_
       .'                       -
      -                          '_
    _'                             .
   .                                -
  -                                  '_
_'_____________________________________._______________________________________
                                        -                                     .
                                         -                                   -
                                          '_                               _'
                                            .                             .
                                             -                           -
                                              '.                       _'
                                                -_                    -
                                                  -_                .'
                                                    -_           _.'
                                                      '-._____..'
new alloc for instr 1:
B  0.000 ..  1.000 T  0.312 TT  0.312 M:  0.16667
B  1.000 ..  2.000 T  0.625 TT  0.625 M:  0.16667
B  2.000 ..  3.000 T  0.937 TT  0.937 M:  0.16667
Score finished in csoundPerform().
inactive allocs returned to freespace
end of score.		   overall amps:  0.16667
	   overall samples out of range:        0
0 errors in performance
Elapsed time at end of performance: real: 1.219s, CPU: 0.045s
closing device
41 1024 sample blks of 64-bit floats written to dac
```

**Comment by jpffitch** [comment]
Believed fixed in gitub

**Comment by adamfreese** [comment]
Unfortunately, while the example I gave works now, none of my actual music using the { statement compiles, with the error alternating (at random, apparently) between a segfault and invalid free().

I've not yet been able to construct another minimal working example. I've been trying to strip down one of my pieces that fails to compile to see how little is needed for the segfault to occur, and apparently irrelevant things influence whether the piece segfaults. Having a comment more than 17 characters long a few lines after the #include statement for the score causes a segfault, but not including a comment (or a shorter comment) allows compilation to occur just fine. Including empty lines between <CsInstruments>, an #include statement for the orchestra, and </CsInstruments> allows compilation but removing the empty lines causes segfaults.

But the segfault only actually happens if there is a { statement in the score, and commenting out all { and } statements allows compilation without segfault regardless of these other changes.

On the other hand, I've not been able to make the minimal example above segfault just by making minor changes like these.

I'll share a minimal example when I've managed to create one, but the issue isn't resolved for large, complicated Csound projects.

**Comment by adamfreese** [comment]
Sorry for taking so long to get back on this. Ultimately I could not produce a truly minimal example, so I'm sharing a less-than-minimal example of something that segfaults instead. I've uploaded a Csound project to GitHub, which should be available here: https://github.com/adamfreese/PerfectSquares

In the latest version of Csound from GitHub, main.csd fails to compile, with the error alternatively being either a segfault or an invalid free(). If the line `#include "loops.sco"` is commented out and the line for `#include "noloops.sco"` is uncommented, the music is output with no errors. The difference between the files is that in noloops.sco I've replaced the loops enclosed by `{...}`, so I believe the issue is still with the { and } statements.

A few peculiarities I've run into that I feel might be worth noting:
- If the line `#include "loops.sco"` is replaced by all of the text in loops.sco, the music renders with no errors.
- If I remove most of the unused opcodes and instruments from Alice.orc, the music renders with no errors. (This is why I included such a massive orchestra with so many unused instruments and opcodes in the example, and why I can't make a truly minimal example.)

**Comment by jpffitch** [comment]
I have seen a memory error relating to #include possibly related to { 
opcode.   Looks hard to understand but will work on it.

**Comment by jpffitch** [comment]
A stack coherence error was detected and removed.  So no valgrind errors now and I believe this is fixed in github

Many thanks for the example.  It required a { } loop inside an #include to fail.

Hope tat will allow me to close the issue?

**Comment by adamfreese** [comment]
Just built the latest GitHub commit, and everything runs fine. Thanks so much!
