### ISSUE TITLE
nonexisting named instrument in score causes confusion

### ISSUE THREAD

**Issue by gesellkammer** [csound/csound#1111]
The following example schedules instr 10 twice. The expected behaviour would have been an error, either indicating that a named instrument must be quoted, or that this instrument does not exist.

```csound

<CsoundSynthesizer>
<CsInstruments>

instr 10
	print p1
	turnoff 
endin

instr foo
	print p1
	turnoff 
endin

</CsInstruments>

<CsScore>
i 10    0   1
i coocoo  0.5 1    ; <---------------------- no quotes here!
</CsScore>

</CsoundSynthesizer>
```

**Comment by jpffitch** [comment]
Did you look at the score it used? Optio -t0 and file score.xtr

⁣Sent from TypeApp ​

**Comment by gesellkammer** [comment]
I don't quite follow what you mean with 'score.xtr'. Adding -t0 to the 
options does not seem to change anything.

**Comment by jpffitch** [comment]
No it does not change behaviour but is an easy way to start diagnosis.  It writes the score to a file and then one can see what a mess is being made.

Sorry not start computer yet so was trying to expedite an investigation.

⁣Sent from TypeApp ​

**Comment by gesellkammer** [comment]
File: score.srt
w 0 60
i 10 0x0p+0 0x0p+0 0x1p+0 0x1p+0
i 10 0x0p+0 0x0p+0 0x1p+0 0x1p+0
e
e

**Comment by jpffitch** [comment]
Ok will get to computer soon

⁣Sent from TypeApp ​

**Comment by jpffitch** [comment]
It is quietly dropping the ill-formed score line.  Not found out where 
yet.  Investigating....

**Comment by jpffitch** [comment]
Slight insight.  c starts a comment but not dealt with in the lexer, so 
the line
i coocoo  0.5 1

is an i statement with no pfields beyond p0.  This is not properly checked 
and it thus replicates the values from the earlier i statement

I wonder if anyone knows about the c starting comments?

If you change coocoo for foo you get an error message but still the 
duplication.

Questions arise about what it should do if the i statement is shortened. 
Actually what it is doing is the correct thing according to the 
specification, missing fields are copied from before to strictly this 
program is correct.

Any discussion about the behaviour should be on one of the mailing lists.

**Comment by gesellkammer** [comment]
cc'ing to the mailing list

I for sure did not know about c starting a comment. For me (csound from 
dev branch) many names produce the same behaviour, as long as they are 
not quoted (any name not starting with n, p or z)

**Comment by jpffitch** [comment]
From the manual on scores....

  <para>
    Comments are denoted by semicolon (;), double slash (//) or the
    character c and last until a newline.  Also C-style comments /*
    ... */ are allowed.
  </para>
