### ISSUE TITLE
request for new opcode "nstrstr"

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#1112]
for some situations with named instruments it would be desireable to get the name back from csound (in a way the reverse of nstrnum).  so
S_name nstrstr instrnum
S_name nstrstr knstrnum
would return for instance:
S_this nstrstr p1
puts S_this, 1
-> "Bla"

**Comment by jpffitch** [comment]
I think it is doable but will be slow as the names are the key to a hash table so this would need to do an exhaustive search of the table.

**Comment by jpffitch** [comment]
I have an apparently working version; just need to check memory leaks etc

**Comment by joachimheintz** [comment]
super -- give me a sign when you pushed and want me to test.

**Comment by joachimheintz** [comment]
i have checked and it works well for me (i-rate only).
i noticed that it segfaults in two cases:
1. when i ask for an instrument number which does not exist. for instance nstrstr(3) but there are only the instruments Bla and Fasel.
2. when i ask for an instrument number which is given as a number rather than a string. for instance nstrstr(2) when there are the instruments Bla and 2.

**Comment by jpffitch** [comment]
THese all relate to what answer one expects if there is no such named 
instruemt.  At present it (fails to) return a nukk string.  It coud return 
an empty string or a partculr string linee "unknown" or "no such 
instrument" or "??".

What would you prefer?

**Comment by joachimheintz** [comment]
i think an empty string would be best.

**Comment by jpffitch** [comment]
done

**Comment by joachimheintz** [comment]
yes ...
thanks -- closing this now

**Comment by gogins** [comment]
Agreed.
