### ISSUE TITLE
array outout of monitor opcode not correct

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#1113]
in the following example, aOut[1] should be zero, but this is not the case.
(it works in the traditional way; a1, a2 monitor rather than aOut[] monitor).

nchnls = 2
0dbfs = 1
instr 1
 outch 1, rand:a(.1)
endin
schedule(1,0,5)
instr 2
 aOut[] monitor
 printk 1, k(aOut[0])
 printk 1, k(aOut[1]) 
endin
schedule(2,0,5)

the printout is for me:
 i   2 time     0.00000:     0.05000
 i   2 time     0.00000:     0.09769
 i   2 time     1.00063:    -0.06728
 i   2 time     1.00063:    -0.08288
 i   2 time     2.00054:     0.03682
 i   2 time     2.00054:    -0.09597
 i   2 time     3.00045:     0.04092
 i   2 time     3.00045:    -0.00905
 i   2 time     4.00036:    -0.05498
 i   2 time     4.00036:    -0.02214

**Comment by jpffitch** [comment]
yes code is a mess.  Will look soon.

**Comment by jpffitch** [comment]
Believed fixed in gitub

**Comment by joachimheintz** [comment]
yes -- i also tested with a four channel case and all looks good.
thanks for the quick fix!
