### ISSUE TITLE
audio array operations not respecting --sample-accurate

### ISSUE THREAD

**Issue by jpffitch** [csound/csound#1115]
At least aa= arr[..] does not and I suspect others.

**Comment by jpffitch** [comment]
This is very hard.  Consider a[] = b[] op c[]
if a,b and c are local then it should respect the early/offset
if a,b and c are all global then it should be as now
if b and c are local but a is global it needs to zero the part outside the k-cycle
if one of b and c are global but a is local it is like case 1
if a is global and b and c are not both the same then it needs to act with zeros outside the k-cycle (I think)

Trouble is determining which case is correct in the parser/semantics

**Comment by vlazzarini** [comment]
How is it done for single audio variables?

**Comment by jpffitch** [comment]
Some time back I introduced =.g and =.l to attack this problem with a-values.  Since then the optimisation for the last assignment in an arithmetic expression may have bypassed this hack.  It is done in csound_orc_semantics.c if you want to look.  The more I think about this the more confused I am getting.  I am not sure what the intent is.  There was an issue that was reported that led to me making a change.  I will see if I can identify it.

**Comment by jpffitch** [comment]
Reference issue #683 which is the same problem

**Comment by vlazzarini** [comment]
but that was fixed, was it not?

**Comment by vlazzarini** [comment]
I see now, you fixed it, but the optimisation has bypassed this now.

Looks hairy.

**Comment by jpffitch** [comment]
a-Arrays are now just like a-vars in this respect. Final assignments are global/local aware
Closing this for now as any more is very difficult/impossible
