### ISSUE TITLE
wrong result for escape sequences when using kkeydown in sensekey

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#1116]
the return values for escape sequences are not the same when using the second (optional) output.  i attach a .csd which shows the issue.
[test2.csd.zip](https://github.com/csound/csound/files/2926165/test2.csd.zip)

**Comment by jpffitch** [comment]
I have code that seems to work but not sure why!

Willl test more and maybe commit tomorrow

**Comment by jpffitch** [comment]
Seems to  be ok; can you test?  I committed it

**Comment by joachimheintz** [comment]
yes works for me, too.
thanks for the fix.
