### ISSUE TITLE
changed2 doesn't accept strings..

### ISSUE THREAD

**Issue by rorywalsh** [csound/csound#1117]
The `changed `opcode can tell if a string has changed, but `changed2` doesn't seem to accept string arguments at all?

```
instr 1
    SMessage sprintf "message_%d", rnd(100)
    chnset SMessage, "message"
endin

instr 2
    SMessage chnget "message"
    ;this works
    ;if changed:k(SMessage) == 1 then
    ;this doesn't
    if changed2:k(SMessage) == 1 then
        printks "Message changed\n", 0
    endif
endin

schedule(2, 0, 1000)
schedule(1, 1, 1)
schedule(1, 3, 1) 
```

**Comment by jpffitch** [comment]
I cannot understand this.  changed2 is the same code as changed apart from the initial state.
What am I missing?

**Comment by rorywalsh** [comment]
This is the error I get:

```
error:  Unable to find opcode entry for 'changed2' with matching argument types:
Found: k changed2 S
       #k0 changed2 SMessage ...
```

**Comment by jpffitch** [comment]
That is because changed2 (like changed) take a number of k-variables or an array
I can add a list of strings but I think that does not work for other reasons.  Basically the whole idea/code predates strings.

**Comment by rorywalsh** [comment]
But `changed` does work with strings, even though the manual states otherwise. It's a Csound secret!

**Comment by jpffitch** [comment]
Oh!  found another definition of changed in str_ops.  Will take a closer look but it is probably trivial (famous last words)

**Comment by rorywalsh** [comment]
Thanks John. If I'm not mistaken it was I who requested string support for changed! And I'm pretty sure you were the one who implemented it ;)

**Comment by jpffitch** [comment]
If you are hapy with the changed opcode on a single string then it iseasy to add the other name.  I seem to remember the difference was behaviour at starting but it looks as if the string version is more like changed2 anyway -- not sure though

**Comment by rorywalsh** [comment]
It seems to me that `changed(SString)` will report a change during the init pass, just as `changed(kVar)` does?

**Comment by jpffitch** [comment]
I think this is fixed or at last circumvented
