### ISSUE TITLE
diskgrain fails when file sr != orchestra sr

### ISSUE THREAD

**Issue by hartmans** [csound/csound#1119]
back in csound 6.08, diskgrain didn't attempt to do anything with the file sample rate.  You could adjust for it in your orchestra.
Now, after 8aaf6a7f3b8e4 it scales the pitch and the initial position in the file but not the pointer rate proportionally to the difference in file sample rate and orchestra sample rate.

The biggest problem is that if the initial position is non-zero there appears to be a disconuity in the sound.  It's almost as if the position calculation for the first buffer read isn't the same as for subsiquent buffers.  I'm not that familiar with csound code, but it may be exactly what's going on:

The initial seek:
```c
    if (*p->ioff >= 0)
      sf_seek(p->sf,*p->ioff * CS_ESR, SEEK_SET);
```

But the initial position is calculated as follows:
```c
    p->pos = *p->ioff*p->sr;
```
Note that `p->sr` is the file samplerate not the orchestra sample rate.
I think that seek probably wants to be based on the file samplerate, not the orchestra samplerate.

There's a second problem.  Your orchestra still needs to know about the difference between orchestra sr and file sr because the pointer rate is not scaled. Since the pitch is scaled, the pitch will sound natural, but you'll get likely unintended time compression or expansion in the current code.
I find this mixed behavior is unlikely to be what anyone wants.
I think either of the following behaviors is more rational:

* The old csound 6.08 behavior.  Since the code is not going to resample the file, it leaves things entirely to the orchestra.  Ugly and user hostile, but depending on your grain size and sample, and desired effect, adjusting the pitch to account for the sample rate might not even produce acceptable results.

* Go all the way and  adjust the pointer rate too.  For some applications, like transposing a track with a relatively small grain size, that's likely to sound fine and it lets the orchestra be independent of the difference between sound file and orchestra sr.

Either way, fixing the discontinuity in initial playing would be greatly appreciated.

**Comment by vlazzarini** [comment]
clearly a bug, solution 2 is what needs to be implemented.

**Comment by vlazzarini** [comment]
Ok, I think I made the correct changes, would you be able to check if they fix the bug?

**Comment by hartmans** [comment]
I confirm both from running the code and inspection that f23c45efcef fixes the issue.  Thanks so much.

**Comment by vlazzarini** [comment]
Thx, will check if the same needs applying to syncgrain and syncloop
