### ISSUE TITLE
csound iOS download does not contain prebuilt libraries

### ISSUE THREAD

**Issue by manowargoblin** [csound/csound#1121]
Hi,
  I notice the IOS builds don't contain prebuilt library files libcsound.a & libsndfile.a

  https://csound.com/download.html then IOS sdk 6.12.1

  I managed to get a 2017 version, but not sure how to get the latest build?

  regards
tony saunders

**Comment by vlazzarini** [comment]
yes you are right, the build scripts failed and we did not notice it. 
Now fixed.
