### ISSUE TITLE
Add the posibility of using the line opcode in a p field.

### ISSUE THREAD

**Issue by pablozoani** [csound/csound#1125]
Hello Developers, this is my first post here. Sometimes, one needs a variable to change over time but just for only one instance. So by doing this you need to rewrite the orchestra code (and so all the p fields in the score).
 
This would be VERY VERY BIG.

The idea.
```
<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>
sr			= 		96000
ksmps 			= 		1
nchnls 			= 		2
0dbfs 			= 		1
instr 1
 k_freq			=		p4
 a_sig			poscil		1, k_freq
 			outch		1, a_sig, 2, a_sig
endin
</CsInstruments>
<CsScore>
a 0 0 0
t 0 60
i 1 0 3 440
i 1 3 5 660
i 1 8 3 line:k(880,2,1760)
e
</CsScore>
</CsoundSynthesizer>
```
How to solve this problem by the moment. Notice you need to rewrite. This can be very tedious in large scores with large orchestra code.
```
<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>
sr			= 		96000
ksmps 			= 		1
nchnls 			= 		2
0dbfs 			= 		1
instr 1
 k_freq			=		p4
 a_sig			poscil		1, k_freq
 			outch		1, a_sig, 2, a_sig
endin
instr 2
 k_freq			=		line(p4,p5,p6)
 a_sig			poscil		1, k_freq
 			outch		1, a_sig, 2, a_sig
endin
</CsInstruments>
<CsScore>
a 0 0 0
t 0 60
i 1 0 3 440
i 1 3 5 660
i 2 8 3 880 2 1760
e
</CsScore>
</CsoundSynthesizer>
```
Regards

**Comment by kunstmusik** [comment]
This is related to https://github.com/csound/csound/issues/322 and something I proposed in 2015 for Csound 7 at the ICSC in St. Petersburg.  The proposal was to allow it from orchestra code though as the score system would require a large change and it naturally fits in with orchestra event code.

For reference, I implemented this kind of event system in my own system [Pink](https://github.com/kunstmusik/pink/blob/master/doc/events.md) as "higher-order events". It works (though there are caveats to handling when you want an opcode instance to be initiated, either at time of event creation or at time of event firing) and was the impetus for the proposal for Csound 7.

**Comment by vlazzarini** [comment]
This confuses the orchestra/Csound code with the numeric score, which is a controller. I think Steven's suggestion is correct. 

Alternatively, there is nothing stopping anyone designing their own 'score language', we even have a mechanism to facilitate that via the bin attribute in the <CsScore> tag, where a translating program or script can be employed to create a standard numeric score from a user-defined input.

**Comment by pablozoani** [comment]
> 
> 
> This is related to #322 and something I proposed in 2015 for Csound 7 at the ICSC in St. Petersburg. The proposal was to allow it from orchestra code though as the score system would require a large change and it naturally fits in with orchestra event code.
> 
> For reference, I implemented this kind of event system in my own system [Pink](https://github.com/kunstmusik/pink/blob/master/doc/events.md) as "higher-order events". It works (though there are caveats to handling when you want an opcode instance to be initiated, either at time of event creation or at time of event firing) and was the impetus for the proposal for Csound 7.

Thanks Steven, reading pink's documentation right now, its very big.

> 
> 
> This confuses the orchestra/Csound code with the numeric score, which is a controller. I think Steven's suggestion is correct.
> 
> Alternatively, there is nothing stopping anyone designing their own 'score language', we even have a mechanism to facilitate that via the bin attribute in the tag, where a translating program or script can be employed to create a standard numeric score from a user-defined input.

Thanks for replying Victor. Just "user level" here, i can not desing my language yet, have to improve programming skills wich are in progress.

Regards

**Comment by hlolli** [comment]
I agree that calling opcodes belongs to the orchestra code. Score should just be data. In js terms, the score is json and the orchestra is javascript. Just to cleanup old tickets, I think we can safely close this?

**Comment by vlazzarini** [comment]
yes!
