### ISSUE TITLE
printks can be skipped incorrectly on rekinit

### ISSUE THREAD

**Issue by hartmans** [csound/csound#1127]
I have some complex control flow logic working between a python controller and a csound orchestra.  The csound orchestra consumes function tables and when it runs out of table uses printks to notify the python code that it wants more.  For a variety of reasons mostly surrounding avoiding to have tight time synchronization between the non-realtime python code and csound, my orchestra is filled with reinit mostly to implement my own timing logic independent of the score, but also because diskgrain2 and diskin2 only let you change file position on an init pass.
because of the lack of time synchronization, it's possible that csound will have used up the entire function table the first time it looks at it. 
I ran into a few cases where the notification of this happening got lost, and ended up looking through ugrw1.c to try and understand why.
What I think is happening is that on a reinit pass, you can get the k-time version of the printks code running in the same k-cycle as the i-time code, and printat hasn't yet happened, so the print doesn't trigger.
I then produced a relatively simple test case of my problem:

In the following code, unless I'm misunderstanding something massively, if `kended` ever becomes 1, the print statement should fire, but for me the orchestra never prints foo.
I don't understand the code well enough to safely fix this.

I'm sure the core developers are aware, but to anyone else reading the issue, remember that an if expression with a k-rate variable evaluates both the then and else body at i-time.
```
kr=441
opcode bar,0,0
kended init 0
if kended != 1 then
printks "foo\n", 0
kended = 1
endif
printks "running\n", 0.02
endop

instr 1
      kskip init 1

      start:
      if kskip == 0 then
            bar
      endif


      rigoto done
      if kskip == 1 then
            kskip = 0
            reinit start
      endif
      done:
endin
```
run that with a score that gives the instrument a quarter-second or so to run.
What I see is `running` printed several times.
I'd also expect `foo` to print, but it does not.

**Comment by vlazzarini** [comment]
If I replace printks with `printf "foo %d\n", 1, kended`, I get this:
```
foo 0
running
running
...
```
Would that solve the problem for you for the moment?

**Comment by hartmans** [comment]
O, yeah printf will work great, and is better than my hackish word
around.  I have read most of the csound opcode descriptions, but I
skipped printf because it seemed obvious, and I assumed that since it
didn't have k in the name it ran at i-time.

Thanks for such a great product and for the amazing responses with
issues.

**Comment by vlazzarini** [comment]
Thanks. We'll keep this open and try to fix it, but at least your immediate problem has
been solved.

**Comment by vlazzarini** [comment]
this is now fixed in git develop.
