### ISSUE TITLE
Nested macros cause segfault  (arch linux)

### ISSUE THREAD

**Issue by moongodjon** [csound/csound#1128]
For example a score file along the lines of
`#define X#440# `
`#define XY# $X #`
`i1 0 1 0.25 $XY`

seems to cause a segfault during score sorting in csound 6.12 beta. The above example works fine in 6.08.

**Comment by jpffitch** [comment]
Cannot reproduce on Linux and latest github sources.  Can you run your example under gdb and post the backtrace when it crashes?  And/or run with -v option to see what the macros are, an/or run under valgrind?

Sorry for delay in response -- did not see the original message and just t stumbled on the issue while looking at a different one.

**Comment by moongodjon** [comment]
I compiled the latest github source [commit:
500770c4864ad09a7f5115bc54540b2021587679] and I can't reproduce the error.
Sorry for the bother.
