### ISSUE TITLE
scsort binary has an absolute runpath to the build directory

### ISSUE THREAD

**Issue by hlolli** [csound/csound#1138]
When building csound with static I get, note that I build with chroot.

```
 0x0000000000000001 (NEEDED)             Shared library: [libcsound64.so.6.0]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000001d (RUNPATH)            Library runpath: [/build/source/build::/usr/local/lib]
```

I build with

```
      mkdir build && cd build
      cmake -DBUILD_STATIC_LIBRARY=YES ../
      RELEASE=true make -j8
```

Being on a very strict Os (NixOs) all reference to build are forbidden, since they are only temp directories.

```
RPATH of binary /nix/store/35dybw71jzg9mjzmfvfgsxlw3rjsg2hm-csound-6.12.0-0/bin/scsort contains a forbidden reference to /build/
```

Priority: low (normal csound installation works fine for me and I can patch this easily).

**Comment by vlazzarini** [comment]
is that only with `scsort`? I would have thought that this is a CMake issue and therefore all binaries would be affected. Or at least, all of the utilities.

**Comment by hlolli** [comment]
Yup that's true, cs, makecsd and mixer also affected, so I assume all binaries. static library doesn't seem to be a factor in this.

**Comment by jpffitch** [comment]
I have been trying to fix that for ages.  it stopd building an openSuse 
rpm

**Comment by hlolli** [comment]
Could be related? https://github.com/csound/csound/blob/develop/CMakeLists.txt#L61-L62

**Comment by vlazzarini** [comment]
looks like a good candidate

**Comment by fsateler** [comment]
Are you installing (`make install`) the result? AFAIU, this runpath is for allowing running the tools from the build directory, and cmake relinks the files without runpath on install.

**Comment by hlolli** [comment]
@fsateler this is from the build directory, this doesn't happen if I do `make install`. Then some runpath changes take place. I guess it would be fine to just use relative runpaths from within the build directory instead of absolute? That would allow to build csound and move the build directory anywhere without needing to run make install?

I will have a go at solving this, I had a gig last night and was very busy before that.

**Comment by fsateler** [comment]
@hlolli why don't you make install the result? I think if you explained the bigger picture an alternative solution can be found. I'm pretty sure this is standard cmake behavior, so not easily changeable from within the build files

**Comment by vlazzarini** [comment]
I did not realise this was not with `make install`. @fsateler is right, this is standard cmake behaviour. You should set your install prefix and `make install`.

**Comment by jpffitch** [comment]
Is this solved?

**Comment by hlolli** [comment]
Sorry was very busy, will look into this now.

The install prefix works fine, and this is all according to the book. Not that I have such a case at the moment, but I could imagine building csound as a 3rd party dependency without installing.

**Comment by hlolli** [comment]
Ah yeh

```
By default if you don't change any RPATH related settings, CMake will
link the executables and shared libraries with full RPATH to all used
libraries in the build tree. When installing, it will clear the RPATH of
these targets so they are installed with an empty RPATH.
```

And of course I can just prefix to a 3rd party directory during build and install there. So I close it (learned something new :) )
