### ISSUE TITLE
OSCsend segfaults if given wrong types

### ISSUE THREAD

**Issue by gesellkammer** [csound/csound#1143]
OSCsend will segfault if any parameter is of wrong type besides the first three parameters

Example: here I forgot to set the type (a string) and started setting values
 
OSCsend kwhen, Shost, iport, "/dest", ifoo, ibar

Maybe the signature is wrong?

**Comment by jpffitch** [comment]
Signature is kSk* which looks rather too general.  Te old version OSCsend_lo 
has signature kSkSS*

**Comment by jpffitch** [comment]
I have adjusted the signature as I cannot see why it differs from the earlier one.
Runs basic test.  Now in github
