### ISSUE TITLE
Tracking of include directories on Windows

### ISSUE THREAD

**Issue by jpffitch** [csound/csound#1150]
The code assumes the directory separator is / but \ is used in Windows.  It should use a macro here

**Comment by hlolli** [comment]
Which code are you referring to?

**Comment by jpffitch** [comment]
Cde in the pre-lexers that expands #include #includestr statements. 
It attemps to track the last directory used to allow local paths.  t 
present it does not allow for any eparator but /

Will fix when I have done the current hard issue.

**Comment by jpffitch** [comment]
Fixed; about to commit

**Comment by kunstmusik** [comment]
Doesn't this change make projects no longer cross-platform? Seems like this
will break existing work. I thought the use of / was intentional (seem to
recall some kind of conversation about this from years ago).

**Comment by kunstmusik** [comment]
Nevermind, seems this is related to internal tracking of paths, and not user supplied paths for include files.
