### ISSUE TITLE
event_i and fractional instrument numbers

### ISSUE THREAD

**Issue by Oeyvind** [csound/csound#1152]
It seems event_i discards the fractional part of the instrument number.
Testing with version 6.13.282 from 
https://ci.appveyor.com/project/csound/csound/build/artifacts

The csd posted below prints:
SECTION 1:
new alloc for instr 1:
new alloc for instr 2:
instr 2:  p1 = 2.000
B  0.000 ..  1.000 T  1.000 TT  1.000 M:      0.0
Score finished in csoundPerform().

I should print
instr 2:  p1 = 2.100
and it does so if I use event instead of event_i

```
<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

instr 1
event_i "i", 2.1, 0, 1
endin	

instr   2
print p1
endin	

</CsInstruments>
<CsScore>
i1 0 1
e
</CsScore>
</CsoundSynthesizer>
```

**Comment by jpffitch** [comment]
Looks that way.  Readung the code I am a little confused as the string 
version of the instruent gets confused with the rest ...  I will see if I 
can trace it through.

**Comment by jpffitch** [comment]
I have a fixed version here.  It made an injudicious cast to integer. 
Will commit next.

**Comment by jpffitch** [comment]
Please check it is OK so the issue can be closed.  Appveyor should build it soon

**Comment by Oeyvind** [comment]
Works wonderfully. Thanks!
