### ISSUE TITLE
Implement consistent naming convention for release artifacts

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#1157]
The release artifacts have inconsistent naming convention at this time (as of 6.13.0) with different usages of - and _.  We need to make this consistent between Csound releases as well as with the manual releases.  

I prefer the older convention we had used:

csound-[buildKind]-[versionNumber].zip

examples:

* csound-windows_x86_64-6.14.0.zip
* csound-ios_x86_64-6.14.0.zip
* csound-web-6.14.0.zip
* csound-linux_x86_64-6.14.0.zip

with used hyphens to separate the parts and underlines for subparts (like CPU type).

**Comment by jpffitch** [comment]
Modified appveyor.ml to be in line with this pattern

**Comment by vlazzarini** [comment]
I think this is implemented now.
