### ISSUE TITLE
Fractional instrument numbers in eventOpcode_

### ISSUE THREAD

**Issue by ErrorThink** [csound/csound#1159]
As per an issue raised for Csound for Android - [https://github.com/gogins/csound-extended/issues/98](https://github.com/gogins/csound-extended/issues/98)

As I understand of what's been relayed, both eventOpcode_ and eventOpcodeI_ are used for event generation. eventOpcode_ - used on Android - doesn't work with fractional instrument numbers.

**Comment by gogins** [comment]
I will try to make this clearer. The Csound for Android app maintained by me for which this issue originally was opened runs Csound slightly differently than the Csound command line program, and may run Csound slightly differently than the CsoundAndroid library (which the app does not use, I maintain my own version of this library that has more compatbility with the other Csound APIs).

At any rate, `event_i` in the orchestra header ends calling `eventOpcodeI_` in desktop Csound which does not round off insno, and calling `eventOpcode_` in the Csound for Android app which does round off insno.

**Comment by vlazzarini** [comment]
ok all we need to do is apply the same fix for event_i to event. I thought it did not need it,
but it looks like it does.

**Comment by ErrorThink** [comment]
Same behaviour with schedule.

**Comment by vlazzarini** [comment]
it uses the sane code

**Comment by vlazzarini** [comment]
fixed in git.
