### ISSUE TITLE
pvstrace zero output

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#1161]
pvstrace followed by pvsynth always outputs 0 as amplitude for me, for instance in the manual example:
kn = p4
asig  diskin2	"beats.wav", 1
fsig  pvsanal   asig, 1024, 256, 1024, 1; analyse it
ftps  pvstrace   fsig, kn		; keep kn bins
atps  pvsynth   ftps			; synthesise it
      outs      atps, atps

it definitely worked in october 2018.

**Comment by jpffitch** [comment]
There seem to be two definitions of pvstrae both in Opcodes/pvsops.cpp
377  csnd::plugin<PVTrace>(csound, "pvstrace", csnd::thread::ik);
378  csnd::plugin<PVTrace2>(csound, "pvstrace", csnd::thread::ik);

I do not read c++ very well but which od f these you get is unclear.

This is new code on 29 Sep 2018

**Comment by vlazzarini** [comment]
yes, two overloads, the second one using an array as output for the bin numbers.

**Comment by vlazzarini** [comment]
I can confirm both opcodes are broken. I don't know why yet.

**Comment by jpffitch** [comment]
OK as I said I do not read C++ well.

Still it givessilence in the manual examle and the onlty code changes I 
could see were in the PVTrace2 code.

**Comment by vlazzarini** [comment]
Fixed in git develop. This problem was due to the removal of threads 4, 5, 7, which required changes to plugin.h and the C++ opcode registration. The changes I made were wrong and cause all kperf opcodes to break. Hopefully it only affected pvstrace.

**Comment by joachimheintz** [comment]
i pulled from git and rebuilt.  now the manual example for pvstrace 
hangs for me.
is it working for you?

**Comment by jpffitch** [comment]
Hangs for me too.

**Comment by vlazzarini** [comment]
It worked for me yesterday, but I'll check again

**Comment by vlazzarini** [comment]
stupid mistake in later commit. Now fixed.

**Comment by joachimheintz** [comment]
yes works now
