### ISSUE TITLE
comma in score ignored rather than throwing error or warning

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#1162]
when i start any instrument, for instance
instr 1
aSine poscil .2, 400
      out aSine, aSine
endin
with a score line which contains a comma, for instance
i, 1 0 3	
this line is simply ignored.
i think it should throw a warning or even an error.

**Comment by jpffitch** [comment]
Works for me, so presumable my example is not yours.  Can you provide a 
simple csd file that shows the problem?
==John ff

**Comment by joachimheintz** [comment]
my example (note the comma in the score after "i"):

<CsoundSynthesizer>
<CsOptions>
-odac
</CsOptions>
<CsInstruments>
instr 1
  print p3
endin
</CsInstruments>
<CsScore>
i, 1 0 1
</CsScore>
</CsoundSynthesizer>

for me (debian linux, csound 6.13) it simply runs without reporting 
anything about the wrong score line.

what is your output?

**Comment by jpffitch** [comment]
Did my output get through?

I get a clear message

Elapsed time at end of orchestra compile: real: 0.004s, CPU: 0.003s
sorting score ...
sread: unexpected char ,
  section 1:  at position 1
WARNING: Internal error in print_input_backtrace()
      remainder of line flushed
        ... done

**Comment by joachimheintz** [comment]
ah, i see --- yes you are right.
the reason i overlooked it is that i expected it after

writing 512 sample blks of 64-bit floats to dac
SECTION 1:

do you see any possibility to put the error message at this place?

**Comment by jpffitch** [comment]
> 
> do you see any possibility to put the error message at this place?

Not really.  The error is detected when the score is read before it is 
sorted.  That seems to me the correct place.  Like gross errors in 
orchestras do not wait for the instrument to be activated

**Comment by joachimheintz** [comment]
ok thanks
