### ISSUE TITLE
Beta releases and turning off stderr output

### ISSUE THREAD

**Issue by dieggsy** [csound/csound#1164]
I noticed that the source code checks for macro `BETA` to print certain messages to stderr. This sorta jarring when using the C api, as it produces unexpected output. Is there a way to turn these off?

Additionally, it seems the latest 6.13 release (at least for linux) is built with `BETA`, despite not seeming to be a beta release.

**Comment by vlazzarini** [comment]
probably a mistake of mine when building for linux. I'll replace the package.

If you want to turn off BETA, build with Release configuration.

**Comment by dieggsy** [comment]
@vlazzarini I think the issue was the way it's packaged for my distro - in any case, it's actually not a BETA problem i'm experiencing - even when building with release configuration, a bunch of info is printed. My code is directly from the csound website:

```C
#include <csound/csound.h>

const char *orc_text =
 "instr 1 \n"
 " out(linen(oscili(p4,p5),0.1,p3,0.1)) \n"
 "endin \n";

const char *sco_text = "i1 0 1 1000 440 \n";

int main(int argc, char **argv) {
    void *csound = csoundCreate(0);
    CSOUND_PARAMS p;
    csoundGetParams(csound, &p);
    p.message_level=1;
    csoundSetParams(csound,&p);
    int result = csoundSetOption(csound, "-d");
    result = csoundSetOption(csound, "-odac");
    result = csoundStart(csound);
    result = csoundCompileOrc(csound, orc_text);
    result = csoundReadScore(csound, sco_text);
    while (1) {
        result = csoundPerformKsmps(csound);
        if (result != 0) {
            break;
        }
    }
    result = csoundCleanup(csound);
    csoundReset(csound);
    csoundDestroy(csound);
    return result;
}
```
And it prints:
```
0dBFS level = 32768.0
--Csound version 6.13 (double samples) Aug  2 2019
[commit: none]
libsndfile-1.0.28
rtaudio: ALSA module enabled
rtmidi: ALSA Raw MIDI module enabled
displays suppressed
0dBFS level = 32768.0
orch now loaded
audio buffered in 256 sample-frame blocks
ALSA output: total buffer size: 1024, period size: 256
writing 256 sample blks of 64-bit floats to dac
SECTION 1:
```
(and then some more after it's interrupted). Is there no way to turn off these messages?

**Comment by vlazzarini** [comment]
-m0 will suppress performance messages. If you want to get rid of almost everything you can define an empty message callback
(check the API reference).

**Comment by dieggsy** [comment]
@vlazzarini the code I posted above with `csoundSetOption(csound,"-m0");` added still prints pretty much exactly what I posted. With an empty callback, the following is still printed:
```
0dBFS level = 32768.0
--Csound version 6.13 (double samples) Aug  2 2019
[commit: none]
libsndfile-1.0.28
```
As well as a backtrace when interrupting, and some tidy up/peformance messages at the end. Is there no other option for disablng all this output? 

I'm sure I could copy some file descriptiors to `/dev/null` or something in the C code, I feel I shouldn't have to. In any case, it seems like a weird default to print stuff (especially when using from a C api) and have to turn off messages - in my experience the default is to not print and request higher verbosity as needed.

**Comment by vlazzarini** [comment]
The first messages are printed by the Csound constructor, pre-callback setting. The csound: tidy up, I am not yet sure where it hails from, but it could be from the OS. I guess redirecting stderr will silence these.

@jpff might have more to say.

**Comment by dieggsy** [comment]
@vlazzarini I've found what I want:
```c
csoundInitialize(CSOUNDINIT_NO_SIGNAL_HANDLER);
csoundSetDefaultMessageCallback(callback);
void *csound=csoundCreate(0);
...
```
I had been using `csoundSetMessageCallback`, but the default version works before initialization. Initializing with the signal handler flag gets rid of the messages after interrupt that I was talking about. Thanks for your patience and the info, and for your work on this super interesting library :)

**Comment by vlazzarini** [comment]
OK, but make sure you really mean not to use a signal handler. Killing Csound might not work as well.

**Comment by vlazzarini** [comment]
Part of the tidy up message is issued by Csound, and part by the OS signalling, 
in Top/csound.c:1219:

```
 psignal(sig, "Csound tidy up");
```
