### ISSUE TITLE
sfplay crashes (too?) easily

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#1167]
according to the manual - and the manual is right!: "ipreindex must contain the number of a previously assigned preset, or Csound will crash."

Can someone have a look at the code and perhaps have a solution for sfplay and friends to not crash in this case but give a warning instead?
This would facilitate just going through different presets without having to remember exactly what those preset numbers were or use an external program like Viena, Swami or Polyphone open for checking if a preset exists or not.

**Comment by jpffitch** [comment]
I suppose it would be possible for the error to be just a warning after giving an answer (zero or negative?).  Then every use of the preset answer would give an error if the bad value is presented.  

Not sure how difficult this would be.

Alternatively fire off a instrument instance to protect the error.

**Comment by jpffitch** [comment]
I have changed the init error to a warning message which  what I think you want.  Can you try this some time?  In particular does it cause any new problems?

**Comment by tjingboem** [comment]
just build Csound and gave it a try, but from my point of view nothing has changed. I still get:

INIT ERROR in instr 2 line 308: sfplay: invalid or out-of-range preset number
 from file /tmp/tempCsd6620101823361886000.csd (1)
asigFL	asigFR	sfplay3	#i33	inumber	#i34	#k38	gir2	1	istart_sample	0	
	  B  1.084 - note deleted.  i2 had 1 init errors

so errors, instead of warnings.
Would be nice to get no error report but something like:
WARNING: sfplay: invalid or out-of-range preset number

But i think i'm nitpicking. These errors do not influence the other instruments that are playing at the same time, and i think due to some initialization corrections done by Victor a few weeks ago, sfplay is more stable.
If you agree about the nitpicking bit, you can close the issue.
Thanks!

**Comment by jpffitch** [comment]
Not giving an error is inconsistent with how csound works in my opinion.  I propose leaving the current state alone for now
