### ISSUE TITLE
sflooper plays (sometimes) wrong samples

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#1168]
i find 2 issues when dealing with sflooper:
1. loop mode 2 back-and-forth makes Csound crash
2. sometimes not the right samples are found; it plays a 'borrowed' sample that is not part of the preset.

i have made an example that shows the issue, with the Soundfont sf_GMbank.sf2 that is part of the Csound distrubution: https://github.com/csound/csound/tree/develop/samples

The first note with the lowest velocity reveals a faulty sample that is not part of the preset:
![Screenshot from 2019-08-09 14-35-20](https://user-images.githubusercontent.com/6670911/62779474-a0ba7f80-bab3-11e9-83b9-4eb19aada7bd.png)
The sounding result is an mp3 (please remove .txt after download):
[sflooperissue.mp3.txt](https://github.com/csound/csound/files/3486370/sflooperissue.mp3.txt)

This is but one example- bigger Soundfonts tend to create bigger chaos in this respect.

**Comment by jpffitch** [comment]
>  1. loop mode 2 back-and-forth makes Csound crash

I failed to reproduce this.  I modified the manual example to use mode 2 
and it ran.  Example please.

**Comment by tjingboem** [comment]
_Concerning the first issue i have with sflooper:_

i managed to bring my Blue instrument back to a simple example: 
[sflooperissueJohn.csd.txt](https://github.com/csound/csound/files/3487527/sflooperissueJohn.csd.txt)
(please remove .txt to bring it back to a normal csd)

I've set imode to 2 and it crashes everytime Blue and from terminal (Linux Mint). 
Setting imode to 0 or 1 works fine here.

Output from terminal:
menno@menno-P5K ~ $ csound /media/menno/datae/onderzoek/csound/sflooperissueJohn.csd
time resolution is 1000.000 ns
0dBFS level = 32768.0
--Csound version 6.14 beta (double samples) Jul 15 2019
[commit: none]
libsndfile-1.0.28
UnifiedCSD:  /media/menno/datae/onderzoek/csound/sflooperissueJohn.csd
STARTING FILE
Creating orchestra
closing tag
Creating score
rtaudio: ALSA module enabled
rtmidi: ALSA Raw MIDI module enabled
Elapsed time at end of orchestra compile: real: 0.001s, CPU: 0.001s
sorting score ...
	... done
Elapsed time at end of score sort: real: 0.001s, CPU: 0.001s
graphics suppressed, ascii substituted
0dBFS level = 1.0
del: -2228.000000
del: -7664.000000
del: -4870.000000
del: -1704.000000
del: -2246.000000
del: -916.000000
del: -2228.000000
del: -7664.000000
del: -11902.000000
del: -4870.000000
del: -1704.000000
del: -2246.000000
del: -1704.000000
del: -2246.000000
del: -7664.000000
del: -2228.000000
del: -4870.000000
orch now loaded
audio buffered in 256 sample-frame blocks
writing 1024-byte blks of shorts to /home/menno/csound/Output/test.wav (WAV)
SECTION 1:
new alloc for instr 2:
instr 2:  inumber = 60.000
 i2   261.62557

csound command: Segmentation fault
inactive allocs returned to freespace
end of score.		   overall amps:  0.00000  0.00000
	   overall samples out of range:        0        0
0 errors in performance
Elapsed time at end of performance: real: 0.255s, CPU: 0.005s
512 1024 sample blks of shorts written to /home/menno/csound/Output/test.wav (WAV)

**Comment by jpffitch** [comment]
OK; I have the crash with your example.

**Comment by jpffitch** [comment]
Victor has fixed the mode 2 problem.  Runs your example

**Comment by jpffitch** [comment]
That still leaves your issue 2, "borrowed samples".  No idea how to start on this.  Do you have a simple csd file that provokes it?  Not sure how that helps but it might be possible to see the route through the opcode.   Is it always the first call?

**Comment by vlazzarini** [comment]
Maybe my fix could have had an effect on this too. It was an initialisation bug that left somethings uninitialised.

If not, a simple test case would help.

**Comment by tjingboem** [comment]
just tried to build Csound to test first issue, but:
[ 79%] Building C object Frontends/CMakeFiles/csound-bin.dir/csound/csound_main.c.o
[ 79%] Building C object Frontends/CMakeFiles/csound-bin.dir/csound/sched.c.o
[ 80%] Linking C executable ../csound
/usr/bin/ld: cannot open output file ../csound: Is a directory
collect2: error: ld returned 1 exit status
Frontends/CMakeFiles/csound-bin.dir/build.make:122: recipe for target 'csound' failed
make[2]: *** [csound] Error 1
CMakeFiles/Makefile2:2565: recipe for target 'Frontends/CMakeFiles/csound-bin.dir/all' failed
make[1]: *** [Frontends/CMakeFiles/csound-bin.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
 

i build Csound once a month. Has something changed?

**Comment by vlazzarini** [comment]
looks like there is a directory called csound in the place where the program was going to be built. Check your build directory

**Comment by tjingboem** [comment]
yes my error- solved and build Csound now.

The first issue: "loop mode 2 back-and-forth makes Csound crash" is indeed off of the list of issues of sflooper. It is now solid as a rock. Thanks Victor & John!

For  issue 2, "borrowed samples", i need some time to experiment and come up with a simple example- if the problem is still there.

I think i found a 3rd issue: with imode = 1 (backward direction) the start of the soundfont is not heard. I can now compare between all the 3 modes; 
imode 0: forward looping, where the start is heard
imode 1: only backward looping WITHOUT start of soundfont?
imode 2: forward and backward looping with start of soundfont

this can easily be tested with bank:0 and program:0 of sf_GMbank.sf2 from the Csound repo: https://github.com/csound/csound/tree/develop/samples.
mode 1 & 3 plays the piano start, while mode 2 skips it entirely and directly goes into looping.

**Comment by tjingboem** [comment]
regarding issue,"borrowed samples",i've tried several hours with different Soundfonts but i think this issue is solved also.
( i found another issue in the process for which i will file as a new issue...)

so: issue 1 & 2 are solved.

That leaves issue 3. Copied from my comment above:

> I think i found a 3rd issue: with imode = 1 (backward direction) the start of the soundfont is not heard. I can now compare between all the 3 modes;
> imode 0: forward looping, where the start is heard
> imode 1: only backward looping WITHOUT start of soundfont?
> imode 2: forward and backward looping with start of soundfont
> 
> this can easily be tested with bank:0 and program:0 of sf_GMbank.sf2 from the Csound repo: https://github.com/csound/csound/tree/develop/samples.
> mode 1 & 3 plays the piano start, while mode 2 skips it entirely and directly goes into looping.

Here is the simple example that show mode 1: only backward looping WITHOUT start of soundfont
[sflooper_backwards.csd.txt](https://github.com/csound/csound/files/3489755/sflooper_backwards.csd.txt)

**Comment by tjingboem** [comment]
Please ignore my latest post as i suspect issue 3 has to do with the opcode sfpassign where i should have used sfpreset instead.
I will continue at a later time and report back.

**Comment by jpffitch** [comment]
I thought that mode 1 worked backwards so from the end of the sound.  Is that not what it is supposed to do?

**Comment by tjingboem** [comment]
According to the manual of sflooper:  "It is a cross between sfplay and flooper2." 
For this issue to test, i went back to flooper2 and found that mode 1 indeed has the same behavior; it goes right away to the end of the loop and plays the loop backwards.
And in the manual i read:"Mode 1 for imode will only loop backwards from the end point to the start point."
So, according to the manual, the part of the sound BEFORE it goes into looping is not played.
While mode 0 and 2 start from the beginning of the sound, then going into loop- 0: forward or 2: back-and-forth  
But the mode 1: backward, is the only mode where the part of the sound before the loop is not played. 

I would argue that _mode_ should only affect the direction of the _loop_, not the whole sound, not what happens before it goes into this looping.

This now has become a sflooper AND flooper2 issue. This code has been there for over 11 years.

On the other hand, i just might be wrong. It was just something i noticed. "Hey, where is the beginning of my sound??" Some confusion...

In the case all works as is designed , you can close the issue.
