### ISSUE TITLE
reverb and chorus reversed in fluidEngine

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#1169]
Using the fluid opcodes, i found that the Reverb and Chorus options in fluidEngine are reversed:
giengine fluidEngine  0,  1, 256, 256 ; 1 = reverb in this case
giengine fluidEngine  1,  0, 256, 256 ; 1 = chorus

So, from the manual:
ienginenum fluidEngine [iReverbEnabled] [, iChorusEnabled] [,iNumChannels] [, iPolyphony] 
should be
ienginenum fluidEngine  [iChorusEnabled]  [,iReverbEnabled][,iNumChannels] [, iPolyphony]

**Comment by jpffitch** [comment]
The manual does not agree with the code.  I will fix.
