### ISSUE TITLE
kperf() not being called in plugin opcodes

### ISSUE THREAD

**Issue by 1bpm** [csound/csound#1170]
When using plugin.h, the kperf member function does not seem to be called when it should be. This is observable in the 6.13 release and current develop branch. However I arbitrarily tried 6.11 and it works ok with that.

The following is derived from the plugin examples in the csound repo, the message is not shown and the output is 0.

simple.cpp
```
#include <plugin.h>

struct Simplek : csnd::Plugin<1, 1> {
  int shown;
  int kperf() {
    outargs[0] = inargs[0];
    if (!shown) {
      csound->message("kperf called");
      shown = 1;
    }
    return OK;
  }
};

#include <modload.h>
void csnd::on_load(Csound *csound) {
  csnd::plugin<Simplek>(csound, "simple", "k", "k", csnd::thread::k);
}
```

compiled with
```
g++ -shared -o simple.so -fPIC simple.cpp -DUSE_DOUBLE -std=c++11 -fpermissive -w -I/usr/local/include/csound
```

test.csd
```
<CsoundSynthesizer>
<CsOptions>
-odac --opcode-lib=simple.so
</CsOptions>
<CsInstruments>
sr = 44100
kr = 4410
nchnls = 2

instr 1

  kx line 1, p3, 99
  ky simple kx
  printk 0.1, ky

endin
</CsInstruments>
<CsScore>
i 1 0 1
</CsScore>
</CsoundSynthesizer>
```

**Comment by vlazzarini** [comment]
I fixed this in the develop branch. Can you check again?

**Comment by 1bpm** [comment]
Sorry didn't realise I was a few commits behind actually. Thanks, does work.
