### ISSUE TITLE
OPCODE6DIR64 as command line flag --env:OPCODE6DIR64=/some/path not working

### ISSUE THREAD

**Issue by hlolli** [csound/csound#1172]
In any OS, when calling

```
csound --env:OPCODE6DIR64=/some/path
# or
csound --env:OPCODE6DIR64+=/some/path
```

has no effect.

But the following works fine on all OS (and powershell with env:OPCODE6DIR64="c:\\..etc..")
```
OPCODE6DIR64=/some/path csound
```

I did some println statements in the c code some weeks ago trying to debug it, but could only see that this flag had no effect on the value of OPCODE6DIR64.

**Comment by jpffitch** [comment]
As far as I can tell from a simple read of the code the OPCODE6DIR64 
environment value is used before the arguments are decoded.  I may be 
wrong on this as there is some baroqueness still in that area of code.

The value is used in csoundReset but arguments are not decoded until 
argdecode.  Tried using gdb




Using host libthread_db library "/lib64/libthread_db.so.1".
time resolution is 1000.000 ns

Breakpoint 1, csoundReset (csound=csound@entry=0x628f10)
     at /home/jpff/csound6/Top/csound.c:3346
3346    {
(gdb) c
Continuing.
0dBFS level = 32768.0
--Csound version 6.14 beta (double samples) Aug 12 2019
[commit: 5e15cc2047260291bc89c8fee506c2ba7b335e6c]
libsndfile-1.0.29pre1

Breakpoint 2, argdecode (csound=csound@entry=0x628f10, argc=argc@entry=1,
     argv_=argv_@entry=0x7fffffffddf8)
     at /home/jpff/csound6/Top/argdecode.c:1205
1205    {




==John ff

**Comment by hlolli** [comment]
I will research this, I must find a way to set the OPCODE6DIR64 from the api without relying on environment variables.

**Comment by jpffitch** [comment]
I will think about it.  What is wrong with environment variables?  One could wrap the command in a script that sets the environment. And then calls csound?  Would that not work?





⁣Sent from TypeApp ​

**Comment by hlolli** [comment]
In my case, I'm trying to run csound from java-jna, and java-jna has no sense of its own environment variables, the native calls receives the environment from the java process. And if I intend to ship precompiled opcodes with java-jna based csound apps, I'd need to ask the users to set their own OPCODE6DIR64 paths, which doesn't make much sense.

I actually do wrap it in a app that I'm working on when the users start a GUI, but using it directly as a library isn't possible due to this limitation.

**Comment by kunstmusik** [comment]
We may also need this for WebAudio Csound for loading plugins from the
Emscripten FS. I'm not aware of a way to set environment variables
accessible by WebAssembly code.

**Comment by hlolli** [comment]
By accident I bumped my eyes on `--opcode6dir64=${CMAKE_BINARY_DIR}` in the cmake file included in the soak_tests. This could be exactly what I'm looking for. Will report!
