### ISSUE TITLE
message off flag for fluidControl

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#1175]
can fluidControl get an optional flag to tell it to print the midi message output or not?
atm, it is always ON, so when using fluidControl for pitch bending, it prints hundred of messages, slowing down the computer because of this printing.

i am aware that i could turn off by a different -m setting in the command line, but that would also affect all other warning messages of the csd.

Something like:
_fluidControl ienginenum, kstatus, kchannel, kdata1, kdata2 [, imsg]_

where imsg = 0 by default and thus printing messages. 
When imsg = 1: no printing

Output example as it is now:
Render Command ( csound -+msg_color=false -+rtaudio=JACK -o dac:system:playback_ -d -m135 /media/menno/datae/onderzoek/soundfont/tempCsd6437950082981146316.csd --env:SFDIR=/media/menno/datae/onderzoek/soundfont )
UnifiedCSD:  /media/menno/datae/onderzoek/soundfont/tempCsd6437950082981146316.csd
............
Created fluidEngine 0x0x7f7d0509edf0 with sampling rate = 48000.000000, chorus on, reverb on, channels 256, voices 4096.
Loading SoundFont : /media/menno/datae/soundfonts/Diato.sf2.
fluidSynth: 0x0x7f7d0509edf0  soundFontId: 1.
.............
Result: -1, Pitch bend:     c:1 b:8192
Result: -1, Pitch bend:     c:1 b:8192
Result: -1, Pitch bend:     c:1 b:8320
Result: -1, Pitch bend:     c:1 b:8320
Result: -1, Pitch bend:     c:1 b:8448
Result: -1, Pitch bend:     c:1 b:8448
Result: -1, Pitch bend:     c:1 b:8576
Result: -1, Pitch bend:     c:1 b:8576
Result: -1, Pitch bend:     c:1 b:8704
..................etc. etc.
and hundreds more......

**Comment by jpffitch** [comment]
It seems wrong to have two ways of suppressing messages.  Current code 
suppresses messages if the value of -m has the bottom 3 bus set (ie 7 | 
any).  You are suggesting another way.  I have sympathy but this need some 
discussion and thought.

Code is in C++ so I would prefer not to touch.

**Comment by jpffitch** [comment]
Also I note that the conditions for printing messages is not documented so perhaps it can just be changed.

**Comment by tjingboem** [comment]
i have been testing and am pleased with the result of this addition. If you want, you can close this issue- and thanks!

**Comment by jpffitch** [comment]
Optional argument imsgs introduced  which stops printing when zero, otherwise prints.  Default is 1
In code and manual.
