### ISSUE TITLE
fluidSetInterpMethod crashes Csound

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#1176]
the example in the manual for the fluidSetInterpMethod opcode is crashing, as are other examples i tried with this opcode.

A few years ago it was i that created the example and i am sure it worked back then.

Output from terminal:
Created fluidEngine 0x0x55ac2d4d0790 with sampling rate = 48000.000000, chorus on, reverb on, channels 256, voices 4096.
Loading SoundFont: /home/menno/csound/Samples/07AcousticGuitar.sf2.
fluidSynth: 0x0x55ac2d4d0790  soundFontId: 1.
SoundFont:   1  Bank:   0  Preset:   0  Seagul Acoustic Git
orch now loaded
audio buffered in 256 sample-frame blocks
ALSA output: total buffer size: 1024, period size: 256
writing 512 sample blks of 64-bit floats to dac
SECTION 1:
new alloc for instr 1:

csound command: Segmentation fault

**Comment by jpffitch** [comment]
I can reproduce.  Crash in thread locking.  Code in C++ .....

backtrace below



```Thread 1 "csound" received signal SIGSEGV, Segmentation fault.
0x00007ffff766fea0 in pthread_mutex_lock () from /lib64/libpthread.so.0
(gdb) where
#0  0x00007ffff766fea0 in pthread_mutex_lock () from /lib64/libpthread.so.0
#1  0x00007fffea1cf4e7 in csound::LockGuard::LockGuard (this=0x7fffffffdb10, 
    csound_=0x628f10, mutex_=0x0)
    at /home/jpff/csound6/./include/OpcodeBase.hpp:80
#2  0x00007fffea1d1555 in FluidSetInterpMethod::init (this=0x22755f8, 
    csound=0x628f10)
    at /home/jpff/csound6/Opcodes/fluidOpcodes/fluidOpcodes.cpp:638
#3  0x00007fffea1d1f21 in csound::OpcodeBase<FluidSetInterpMethod>::init_ (
    csound=0x628f10, opcode=0x22755f8)
    at /home/jpff/csound6/./include/OpcodeBase.hpp:129
#4  0x00007ffff78e81b9 in init_pass (ip=0x2274e50, csound=0x628f10)
    at /home/jpff/csound6/Engine/insert.c:116
#5  insert_event (csound=0x628f10, insno=1, newevtp=0x62c880)
    at /home/jpff/csound6/Engine/insert.c:472
#6  0x00007ffff78e9115 in insert (csound=csound@entry=0x628f10, 
    insno=insno@entry=1, newevtp=newevtp@entry=0x62c880)
    at /home/jpff/csound6/Engine/insert.c:298
#7  0x00007ffff78eee6e in process_score_event (csound=csound@entry=0x628f10, 
    evt=evt@entry=0x62c880, rtEvt=rtEvt@entry=0)
    at /home/jpff/csound6/Engine/musmon.c:829
#8  0x00007ffff78f17db in sensevents (csound=csound@entry=0x628f10)
    at /home/jpff/csound6/Engine/musmon.c:1038
#9  0x00007ffff78cc94a in csoundPerform (csound=0x628f10)
    at /home/jpff/csound6/Top/csound.c:2237
#10 0x0000000000401599 in main (argc=2, argv=0x7fffffffddd8)
    at /home/jpff/csound6/Frontends/csound/csound_main.c:326
```

**Comment by jpffitch** [comment]
One suspects the line that changed  
Michael Gogins 2019-08-13 20:36:42 -0400
line 638 which calls the lock

**Comment by jpffitch** [comment]
Mutex was not initialised.  I added similar code from other fluid opcodes and it seems to work.
Closing but need checks beyond the manual example.
