### ISSUE TITLE
audio artifacts with socksend / sockrecv

### ISSUE THREAD

**Issue by Oeyvind** [csound/csound#1177]
It seems I get heavy dropouts when trying to send audio over UDP with socksend/sockrecv.
Testing on localhost.
I tried adjusting the length of the package, but to no avail. The suggested value in the manual (200) sends packets that Wireshark reports to be of size 1600, and then the transmission fails (as the manual also states that packets must be smaller than 1456). It seems odd that the udp packet size is 8 times the value set in the csd.

[socksend1.txt](https://github.com/csound/csound/files/3524444/socksend1.txt)
[sockrecv1.txt](https://github.com/csound/csound/files/3524446/sockrecv1.txt)

**Comment by vlazzarini** [comment]
audio data is double precision, 8 bytes. The number in the opcode is size in samples, I suspect. Maybe the docs should indicate this.

My experience with sending audio via UDP is that it is not very reliable.

**Comment by Oeyvind** [comment]
Oh, thanks, that makes perfect sense now.

I also tried stsend/strecv but it seems they do not want to connect. I
start the reciever first, then when I start the sender they both just quit
their Csound instance. No error message from Csound.

If I record the audio coming in via sockrecv, I see small snippets (equal
to one package length) of the audio signal interspersed with long sections
(random length, up to around 50 times the package length) with a constant
value. It looks to me like there is something wrong with this. On
localhost, there should be no reason for such a gigantic package loss.


ons. 21. aug. 2019 kl. 11:40 skrev vlazzarini <notifications@github.com>:

**Comment by vlazzarini** [comment]
Maybe @jpffitch has a better idea about these.

**Comment by jpffitch** [comment]
Which platform?

**Comment by jpffitch** [comment]
Sending audio has been a problem for a while.  Did you try using OSC?   I am investigating but no time today.

**Comment by Oeyvind** [comment]
No problem with the delay in reply,
it is not acutely urgent, but would be nice to solve within a week or so.

This is on windows here.

Tried with OSC also today, but I was not able to transmit audio.
I tried sending an audio signal directly, and also tried sending a k-rate
array with buffered audio.

If using an array to buffer audio, it seems I get problems lining up the
buffers correctly on recaive, so I can not determine if the contents are
correctly transmittted.
This is what I tried (perhaps naively?)

*sender
a1 poscil 0.5, 220
kbuf[] init ksmps*4
kbuf[] shiftin a1
ksend metro kr/4
OSCsend ksend, "127.0.0.1", 7777, "/superstrings", "A", kbuf

*receiver
kbuf[] init ksmps*4
osc:
kflag OSClisten gihandle, "/superstrings", "A", kbuf
if kflag > 0 then
kgoto osc
endif
a1 shiftout kbuf

If I send an audio signal directly, it seems I also get similar (but worse)
artifacts.

If it is helpful, I can do more work on writing the received signal to file
to be able to inspect it better.
However, it might be useful to hear of it works as expected on your system.

all best
Oeyvind


tor. 22. aug. 2019 kl. 18:55 skrev John ffitch <notifications@github.com>:

**Comment by jpffitch** [comment]
I am looking at socksend/sockrecv mono UDP.  My sample data to send ids a line
from 0 to 1 over 1 minute which ought to produce a recognisable signal at the
receiver.

What I am seeing is such a straight line but over much longer which suggests
repeated packages or nothing being received in time so output just repeats
last values.  Not really understood what it expects  to happen if there is no
data.  As far as I can tell it inserts data into a circularbuffer but I see no
code to pause if there is no data.  Not sure what it should do either.  Might
be interesting to replace receiver by a C program that prints the data when it
arrives.

more to do....
ReadCircularBuffer returns the number of things read, but if 0 does noting odd.  One could argue that once started the code should loop until data arrives, but that would cause a hang on ending.  I cannot see any sequence counter either.

stsend/strecv ought to be more coherent wrt this problem but I have not looked at the code yet.

**Comment by jpffitch** [comment]
stsend/strecv worked perfectly at least until the sender stopped sending data.

[strecv.txt](https://github.com/csound/csound/files/3535498/strecv.txt)
[stsend.txt](https://github.com/csound/csound/files/3535499/stsend.txt)

**Comment by vlazzarini** [comment]
I think I might be the guilty party in adding the circular buffer to the UDP code. It used to be blocking originally I think and that was problematic so I added the buffering. It might need to be improved.

**Comment by jpffitch** [comment]
I have improved stsend and strecv so they close the communication down cleanly and work with differing ksmps on the sender and receiver.  There are still cases of dropouts if the sender's ksmps is smaller than the receiver and if the sender is also using -o dac

Tested on Linux as I have nothing else.  Examples are
[strecv.txt](https://github.com/csound/csound/files/3538614/strecv.txt)
[stsend.txt](https://github.com/csound/csound/files/3538615/stsend.txt)

**Comment by Oeyvind** [comment]
Tested these on windows now, using the Csound 6.14.54 version from Appveyor
https://ci.appveyor.com/api/buildjobs/2wg9l3lfgarmedd2/artifacts/msvc%2FCsound6_x64-6.13.0-54.exe

There seems to be a problem connecting, and this was the same problem on
the previous Csound version (reported in the issue above).
The receiver halts, waiting for the connection. Then when the sender
starts, both the sender and receiver quit without printing an error.

The reason I know the receiver halts, is that I added this
k1 metro 1
printk2 k1
and it does not print anything until the sender starts,
then it prints a single 1.0 and quits.

The fout in your instrument (jpff) does not produce a valid sound file.
All this suggests to me that perhaps the instrument effectively only run
for one k-cycle.

Finally, the use of an extra k-rate output argument from strecv is
unfamiliar to me, but looks very useful.
a1,kk strecv "127.0.0.1", 7777
I can not find any documentation of it. Is it usually available, or just
something you added for debug?



søn. 25. aug. 2019 kl. 22:41 skrev John ffitch <notifications@github.com>:

**Comment by vlazzarini** [comment]
Ok, socks code on Windows is different from unixes, so we need help here, @kunstmusik, @skyne?

**Comment by jpffitch** [comment]
> 
> There seems to be a problem connecting, and this was the same problem on
> the previous Csound version (reported in the issue above).
> The receiver halts, waiting for the connection. Then when the sender
> starts, both the sender and receiver quit without printing an error.

Oh dear!  If the sender quits then the creation of the TCP datastream 
would seem to be wrong.  I can search through windows help pages but 
without much direction.

The reciever is expected to wait until there is a data connection.

The receiver should not quit of itself.  With the extra output it will 
returm a -1 if there is an error, or a positive number if it receiver 
anything


> The fout in your instrument (jpff) does not produce a valid sound file.
> All this suggests to me that perhaps the instrument effectively only run
> for one k-cycle.

Not on Linux.  I transmiten a straight line so I could inspect the receipt 
via th fout and the xxx.wav file.  A simle edit to the sender wil send a 
sine wave instead, whixh was correct for me

> 
> Finally, the use of an extra k-rate output argument from strecv is
> unfamiliar to me, but looks very useful.
> a1,kk strecv "127.0.0.1", 7777
> I can not find any documentation of it. Is it usually available, or just
> something you added for debug?
>

It is in the manual sources

"    <synopsis>asig[,kstate] <command>strecv</command> Sipaddr, iport</synopsis>2

and

"    <para>
       <emphasis>kstate</emphasis> -- optional output to give the state
       of the receipt.  Gives the number of bytes transferred in the
       current performance cycle or -1 if the sender has ceased writing.
     </para>
"

<

**Comment by jpffitch** [comment]
> Ok, socks code on Windows is different from unixes, so we need help here, @kunstmusik, @skyne?

As far as I can tell the functions stsend/strecv use are in winsock as well.  One could replace the write by a call to send but the documentation suggests they are the same when flags is 0.  Similarly recv instead of read

**Comment by jpffitch** [comment]
Oeyvind, do you see the message "closing stream" on the sender?  or even a message of the form 
 "close = -1 errno=88"
for some number where 88 s as an example?

**Comment by Oeyvind** [comment]
Hi,
I see no messages from the stsend/recv actions at all.

man. 26. aug. 2019 kl. 17:49 skrev John ffitch <notifications@github.com>:

**Comment by jpffitch** [comment]
Does it crash, stop with usual csound messages or just return to the shell?  Do both processes stop the same way and at the same time?  I am getting more confused now.

**Comment by Oeyvind** [comment]
it just returns with no messages.

Here is the console from running strecv (I run that with -n in this case,
but acts the same with -odac):

Microsoft Windows [Version 10.0.17134.950]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Oeyvind>cd /

C:\>cd Cabbage_VST

C:\Cabbage_VST>cd CabbageEfx

C:\Cabbage_VST\CabbageEfx>cd socksend

C:\Cabbage_VST\CabbageEfx\socksend>csound strecv_jpff.csd
0dBFS level = 32768.0
--Csound version 6.14 (double samples) Aug 25 2019
[commit: 392dfe09b4f4ab333be84c983e64dcea44b38e14]
libsndfile-1.0.29pre1
UnifiedCSD:  strecv_jpff.csd
STARTING FILE
Creating options
Creating orchestra
closing tag
Creating score
rtaudio: PortAudio module enabled ...
using callback interface
rtmidi: PortMIDI module enabled
Elapsed time at end of orchestra compile: real: 0.004s, CPU: 0.004s
sorting score ...
        ... done
Elapsed time at end of score sort: real: 0.004s, CPU: 0.004s
graphics suppressed, ascii substituted
0dBFS level = 1.0
orch now loaded
audio buffered in 4096 sample-frame blocks
not writing to sound disk
SECTION 1:
new alloc for instr 1:
 i1     1.00000

C:\Cabbage_VST\CabbageEfx\socksend>


man. 26. aug. 2019 kl. 21:02 skrev John ffitch <notifications@github.com>:

**Comment by Oeyvind** [comment]
Similar for stsend:

C:\Cabbage_VST\CabbageEfx\socksend>csound stsend_jpff.csd
0dBFS level = 32768.0
--Csound version 6.14 (double samples) Aug 25 2019
[commit: 392dfe09b4f4ab333be84c983e64dcea44b38e14]
libsndfile-1.0.29pre1
UnifiedCSD:  stsend_jpff.csd
STARTING FILE
Creating options
Creating orchestra
closing tag
Creating score
rtaudio: PortAudio module enabled ...
using callback interface
rtmidi: PortMIDI module enabled
Elapsed time at end of orchestra compile: real: 0.005s, CPU: 0.005s
sorting score ...
        ... done
Elapsed time at end of score sort: real: 0.006s, CPU: 0.006s
graphics suppressed, ascii substituted
0dBFS level = 1.0
orch now loaded
audio buffered in 4096 sample-frame blocks
PortAudio V19.6.0-devel, revision unknown
   0: dac0 (Microsoft Sound Mapper - Output [MME])
   1: dac1 (Speakers (Realtek High Definiti [MME])
   2: dac2 (Primary Sound Driver [Windows DirectSound])
   3: dac3 (Speakers (Realtek High Definition Audio) [Windows DirectSound])
   4: dac4 (Generic Low Latency ASIO Driver [ASIO])
   5: dac5 (ReaRoute ASIO (x64) [ASIO])
   6: dac6 (Speakers (Realtek High Definition Audio) [Windows WASAPI])
   7: dac7 (Speakers (Realtek HD Audio output) [Windows WDM-KS])
   8: dac8 (SPDIF Out (Realtek HDA SPDIF Out) [Windows WDM-KS])
PortAudio: selected output device 'Speakers (Realtek High Definiti'
writing 4096 sample blks of 64-bit floats to dac
SECTION 1:
new alloc for instr 1:

C:\Cabbage_VST\CabbageEfx\socksend>

man. 26. aug. 2019 kl. 21:36 skrev Oeyvind Brandtsegg <obrandts@gmail.com>:

**Comment by jpffitch** [comment]
Can you try again?  Appveyor build. Had more fish ostocd but I am not sure there is any change.

⁣Sent from TypeApp ​

**Comment by Oeyvind** [comment]
Ah. Great. It connects, sends and receives.
Some dropouts in the file, quite a lot, but in total there is more good
data than dropouts now, so I can start tweaking.

console print from stsend csd:
(...)
SECTION 1:
new alloc for instr 1:
closing stream


Console from strecv csd:
new alloc for instr 1:
 i1     1.00000
 i1 kk =   800.00000
 i1     0.00000
 i1     1.00000
PERF ERROR in instr 1 line 15: read from socket failed
 from file strecv_jpff.csd (1)
a1      kk      strecv  "127.0.0.1"     7777
   note aborted
Closing file 'xxx.wav'...
  rtevent:         T  1.002 TT  1.002 M:  0.99884
new alloc for instr 2:
Early return from csoundPerform().
inactive allocs returned to freespace
end of score.              overall amps:  0.99884
           overall samples out of range:        0
1 errors in performance
Elapsed time at end of performance: real: 15.431s, CPU: 15.431s
no sound written to disk

**
I think the perf error happens when the sender stops sending,
which was after 1 second in this case



ons. 28. aug. 2019 kl. 00:37 skrev John ffitch <notifications@github.com>:

> Can you try again?  Appveyor build. Had more fish ostocd but I am not sure
> there is any change.
>
> ⁣Sent from TypeApp ​
>

**Comment by Oeyvind** [comment]
with ksmps = 64 on both ends I have no dropouts. Great!

ons. 28. aug. 2019 kl. 11:24 skrev Oeyvind Brandtsegg <obrandts@gmail.com>:

**Comment by jpffitch** [comment]
Good!  There are a few more similar fixes to make when I get time.

⁣Sent from TypeApp ​
