### ISSUE TITLE
sfpreset/sfplay allows only 1 soundfont

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#1179]
i'd like to use more than 1 soundfont in parallel, something that can be achieved with sfpreset: "Assigns an existing preset of a SoundFont2 (SF2) sample file to an index number."

(header)
gir	sfpreset 50, 0, gisf1, 0
(instr)	
a1,a2	sfplay3	ivel, inum, kamp*ivel, kfreq, gir

works fine. gir = 0

But
(header)
gir	sfpreset 50, 0, gisf1, 1
(instr)	
a1,a2	sfplay3	ivel, inum, kamp*ivel, kfreq, gir

does not. It outputs:

instr 0:  gir = 1.000
orch now loaded
....
INIT ERROR in instr 1 line 39: invalid soundfont
 from file /media/menno/datae/onderzoek/soundfont/sfpreset.csd (1)
a1	a2	sfplay3	ivel	inum	#k1	kfreq	gir	0	0	0
	  B  0.000 - note deleted.  i1 had 1 init errors
B  0.000 ..  2.250 T  0.840 TT  0.840 M:      0.0      0.0
INIT ERROR in instr 1 line 39: invalid soundfont
 from file /media/menno/datae/onderzoek/soundfont/sfpreset.csd (1)
a1	a2	sfplay3	ivel	inum	#k1	kfreq	gir	0	0	0
	  B  2.250 - note deleted.  i1 had 1 init errors
B  2.250 ..  4.500 T  1.681 TT  1.681 M:      0.0      0.0
INIT ERROR in instr 1 line 39: invalid soundfont
 from file /media/menno/datae/onderzoek/soundfont/sfpreset.csd (1)
a1	a2	sfplay3	ivel	inum	#k1	kfreq	gir	0	0	0
	  B  4.500 - note deleted.  i1 had 1 init errors
B  4.500 ..  6.750 T  2.521 TT  2.521 M:      0.0      0.0
INIT ERROR in instr 1 line 39: invalid soundfont
 from file /media/menno/datae/onderzoek/soundfont/sfpreset.csd (1)
a1	a2	sfplay3	ivel	inum	#k1	kfreq	gir	0	0	0
	  B  6.750 - note deleted.  i1 had 1 init errors
Score finished in csoundPerform().
inactive allocs returned to freespace
end of score.		   overall amps:      0.0      0.0
	   overall samples out of range:        0        0
4 errors in performance
Elapsed time at end of performance: real: 0.016s, CPU: 0.016s
512 1024 sample blks of shorts written to /home/menno/csound/Output/test.wav (WAV)

Should not gir	sfpreset 50, 0, gisf1, 1 work as well? Or any number?

the simple csd:
[sfpreset.txt](https://github.com/csound/csound/files/3540476/sfpreset.txt)

**Comment by jpffitch** [comment]
Without seeing the complete csd I think that the problem is that there is 
an internal count of the number of loads of sound fonts which is checked 
in sfPlay* to check that the index is in range.  But if there is only one 
load it is not.

I am not sure what the correct use of this code is so am uncertain what to 
tweak.  It could set the count to max of count and the result of the 
preset but do not know if this is correct.

**Comment by tjingboem** [comment]
You are right, after experimentation i found there must be a counter that counts the loaded soundfonts, starting at 0 and counting up.
This means that it is **not** up to the user, using sfpreset, to assign a specific number to a preset. 

The manual: "Assigns an existing preset of a SoundFont2 (SF2) sample file to an index number." There is no talk about a counter from 0 to xx - hence my confusion when i tried to assign whatever number as an index number. That was what i am looking for.
ALso the manual: "ir -- output to be used by other SF2 opcodes. For sfpreset, ir is ipreindex." This confirmed my believe to be able to give it whatever number. 

the example beneath works. There are 2 sfplayers, so the loaded soundfonts are counting 0 and 1. Changing "gir	sfpreset 50, 0, gisf1, 0" to "gir	sfpreset 50, 0, gisf1, 5739" produces the error  i found.

I would like it to be independent on this counter and was thinking along the lines of "gir	sfpreset 50, 0, gisf1, instr number". In the example below that would mean "gir	sfpreset 50, 0, gisf1, 1" and "giv	sfpreset 50, 0, gisf1, 2".

Is that possible or just to much work or a bad idea, please let me know.

working example with 2 sfplayers:

        gisf1	sfload	 "/media/menno/datae/soundfonts/sf_GMbank.sf2"
	sfplist	 gisf1	
        gir	sfpreset 50, 0, gisf1, 0 		
        gisf2	sfload	 "/media/menno/datae/soundfonts/sf_GMbank.sf2"
	sfplist	 gisf2	
        giv	sfpreset 0, 0, gisf2, 1					

	instr 1	;play from score

        inum	init	p4
        ivel	init	p5
        ivel	init	ivel/127					;make velocity dependent
        kamp	= kamp/5000						;scale amplitude
       a1,a2	sfplay3	ivel, inum, kamp*ivel, 1, gir
	outs	a1, a2
		endin

	instr 2	;play from score

        inum	init	p4
        ivel	init	p5
        ivel	init	ivel/127					;make velocity dependent
        kamp	= kamp/5000						;scale amplitude
        a1,a2	sfplay3	ivel, inum, kamp*ivel, 1, giv
	outs	a1, a2
	endin

**Comment by tjingboem** [comment]
i'd like to add some more information: i find that sfpreset in combination with sfplay NEEDS to have the right count number, starting from 0 and counting up if i use more than one sfpreset/sfplay instruments.

With the sfpreset/sflooper combination, this is different: it does not matter what index number i use, as long as the number set in sfpreset is the same as the one set in sflooper, it works.
This is the behavior i am looking for.
Can sfplay be changed accordingly?

**Comment by jpffitch** [comment]
Any chance of an example of what does not work at present?  I am not do not sure where to look as I have no experience with these opcodes.

**Comment by tjingboem** [comment]
thanks for your patience.

The issue is all about the preindex (= preset index) of sfpreset.

_sfpreset used together with sflooper instruments can take any number_
but
_sfpreset used in sfplay instrument should start at 0 and counts up in the case one uses more than 1 of these instruments in the composition_.

The fact that a counter is used in sfplay is, in my case as a user, counterproductive and non-intuitive. I would like to assign whatever number as a preindex to sfpreset and thus give sfplay that same unique number too. Just like it seems to work with sflooper.

I would like to decide at any point in the composition to add more sfplay instr or perhaps remove one, without checking if the counter still goes from 0 to xx step 1. In my case, using Blue, i would like to assign the unique number of the instrument. 

If sfplay can modified to work the way sflooper handles the preindex, i think there will be no problems with backwards compatibility, as those compositions will still work with their once given unique preindeces going from 0 to xx.

**Comment by PeteCA** [comment]
I believe there is a general misunderstanding here... (:-))  I just ran into the same issue myself while trying to use a slightly modified sfplay.csd from the examples, with the general 'sf_GMbank.sf2' replacing the  single-preset font in the original.  The actual bug is that any preset number you supply greater than the number of loaded fonts will cause the error!

The culprit is the test introduced in commit c3885cf (line 348 of sfont.c):

    if (UNLIKELY(index>=(DWORD)globals->currSFndx))
 
'index' is the number of the preset desired (which could be in the tens or hundreds) while 'currSFndx' is just the number of actual fonts loaded -- maybe one or two.

Not sure if there is a simple fix for the test, as I don't see any direct record of the maximum current preset number to compare the index with.  I've simply commented out the test in my build, and everything works again.

**Comment by jpffitch** [comment]
Thanks.  I think that test should be
index>=MAX_SFPRESET

Just about to test

**Comment by tjingboem** [comment]
my issue is not addressed here, i am looking for something else.

The example below can hopefully explain. Here you see me loading 2 Soundfonts: giSF and giSF2. The first sfpreset is assigned number 11, the second giSF2 has number 12.
Now, this example does not work, because giSF has to be assigned the number 1 and giSF2 has to be number 2...
 This is not the behavior i am looking for, i want to assign them numbers of my choice. In my case,  I want the number to be the number of the instrument, so that, in Blue, i can create encapsulated sfplay instruments without worrying about some sequence of numbers.  This would allow me to activate the instruments when i want to, or add one, deleting one, without concerning myself with some counter.

Is that counter necessary? SFinstr and sflooper don't have this counter and i can assign whatever number. 

> <CsoundSynthesizer>
> 
> <CsInstruments>
> sr=48000
> ksmps=32
> nchnls=2
> 0dbfs=1
> 
> 
> 
> 
> gitwelve ftgen 1, 0, 16, -2, 12, 2, 440, 69, 1, 16/15, 9/8, 6/5, 5/4, 4/3, 7/5, 3/2, 8/5, 5/3, 9/5, 15/8, 2 
> givife   ftgen 2, 0, 16, -2, 5, 2, 261.659, 60, 1, 1.1486, 1.3195, 1.5157, 1.7411, 2.00
> giSF	sfload	"/home/menno/csound/Samples/07AcousticGuitar.sf2" 
>         sfplist giSF 
> gipre	sfpreset 0, 0, giSF, 11
>  
> giSF2	sfload	"/home/menno/sf_GMbank.sf2"
>         sfplist giSF2
> gipre2	sfpreset 10, 0, giSF2, 12
> 
> 
> 
> 
> 	instr 1	;untitled
> event "e", 0, 0, 0.1
> 	endin
> 
> 	instr 11	;
> print gipre
> ikey	= p4
> ivel	= p5
> aenv    linsegr	1, 1, 1, 1, 0			;envelope
> icps    cpstuni	ikey, gitwelve 			;12 tones per octave
> iamp    = 0.0004				;scale amplitude
> iamp    = iamp * ivel * 1/128 			;make velocity-dependent
> aL, aR	sfplay3 ivel, ikey, iamp, icps, gipre, 1 
> aL      = aL * aenv 
> aR      = aR * aenv 
>         outs aL, aR 
> 
> 	endin
> 
> 	instr 12	;
> print gipre2
> ikey	= p4
> ivel	= p5
> aenv    linsegr	1, 1, 1, 1, 0			;envelope
> icps    cpstuni	ikey, givife			;5 tones per octave
> iamp    = 0.0004				;scale amplitude
> iamp    = iamp * ivel * 1/128 			;make velocity-dependent
> aL, aR	sfplay3 ivel, ikey, iamp, icps, gipre2, 1 
> aL      = aL * aenv 
> aR      = aR * aenv 
>         outs aL, aR 
> 
> 	endin
> 
> 
> </CsInstruments>
> 
> <CsScore>
> 
> i1	0.25	1	60	100
> i1	1.25	1	62	80.0
> i1	2.25	1	65	60.0
> i1	3.25	1	69	40
> i2	0.578125	1	60	100
> i2	1.578125	1	62	80.0
> i2	2.578125	1	65	60.0
> i2	3.578125	1	69	40
> i1	4.9375	0.1	
> e
> 
> </CsScore>
> 
> </CsoundSynthesizer>

**Comment by jpffitch** [comment]
That example runs without any errors on the latest version in github

**Comment by tjingboem** [comment]
it appears i did not have the latest version- it works great. 
thanks!
