### ISSUE TITLE
Dangling pointer

### ISSUE THREAD

**Issue by mgehre** [csound/csound#1181]
Detected by clang trunk:
```
interfaces/CppSound.cpp:130:40: warning:  object backing the pointer will be destroyed at the end of the full-expression [-Wdangling-gsl]
      const char *argv_[] = {"csound", getFilename().c_str(), 0};^M


```
because `getFilename()` yields a temporary `std::string`, and thus this the return value of `c_str()`, i.e. argv, will dangle after the end of this line.

See https://github.com/csound/csound/blob/bafb7f542eaf3ede4ac6ec930c5e2a352520e1df/interfaces/CppSound.cpp#L130

**Comment by vlazzarini** [comment]
Author is @gogins I believe.

**Comment by gogins** [comment]
I tested this with clang and clang++ version 8, the latest packages for Ubuntu. CppSound.cpp builds without warnings. I do not have clang and clang++ HEAD but I expect the behavior is the same.
