### ISSUE TITLE
Fluid opcodes not releasing memory

### ISSUE THREAD

**Issue by MeijisIrlnd** [csound/csound#1183]
Hi all, was asked to do a bug report after testing this after emailing the mailing list: 
When using the Fluid opcodes from ctcsound (Python 3.7, manjaro linux, Visual Studio Code), specifically fluidLoad, if the csound code isn't allowed to play for the entire duration, (f/e by using the debugger and restarting), the memory allocated to the soundfont isn't freed, confirmed to free it both by using Csound from the terminal and by stopping the performance thread on destruction of the thread that calls it. (When not allowed to finish the performance, the engine will load the 1gb soundfont 5 times before throwing an Out of Memory exception with 8gb ram). 
Realise this might be a desired thing, but it's quite jarring when making small changes to the code and repeatedly restarting or stopping the debugger before the 4ish minutes of runtime finish!
Cheers, Syl

**Comment by jpffitch** [comment]
Looking at the code the sound fonts are released at module reset but not otherwise.
I suspect the issue is that the sf load opcode does not look to see if it is already loaded, so if you load again the memory use increases.  No idea about the debugger or ctcsound.

**Comment by MeijisIrlnd** [comment]
I guess that's sometimes desired behavior, I wonder if it would be useful to have an opcode to clear loaded fluidSynth soundfonts, or do you think the use case is too niche?

**Comment by jpffitch** [comment]
It should e possible to check the name against the loaded list and rewrite the data or free the old one.  Will look at that.  Just hope that will not break something elsewhere.

**Comment by jpffitch** [comment]
Code in github now detects multiple loads of a sound font and does not use space.  If you have the setup I would appreciate more testing.

**Comment by MeijisIrlnd** [comment]
Oh I'm really sorry I didn't check my emails! Will test this this evening sorry again!
