### ISSUE TITLE
Build failure on macOS with libwebsockets

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#1184]
To reproduce on macOS Mojave 10.14.6:

1. Install Homebrew by following the instructions at https://brew.sh.

2. Enter in Terminal:

    ```sh
    brew install libsndfile libwebsockets
    curl --location --remote-name --remote-header-name https://github.com/csound/csound/archive/6.13.0.tar.gz
    tar -xf csound-6.13.0.tar.gz
    mkdir build
    cd build
    cmake ../csound-6.13.0 -Dssl_library="$(brew --prefix openssl)/lib"
    export CPATH="$(brew --prefix openssl)/include"
    make
    ```

The build fails with:

```
make[2]: *** No rule to make target `/usr/local/lib/libssl.a', needed by `libwebsocketIO.dylib'.  Stop.
make[1]: *** [Opcodes/websockets/CMakeFiles/websocketIO.dir/all] Error 2
make: *** [all] Error 2
```

This may not be relevant, but the location of libssl.a appears to be hard-coded:

https://github.com/csound/csound/blob/1078eea3b4fa8788bdca732457785aa93faac5c7/Opcodes/websockets/CMakeLists.txt#L39-L41

**Comment by kunstmusik** [comment]
Reproduced error here. That Cmake file as a whole is a bit of a mess, but looking around I see that there's a number of "quick fixes" that are hardcoding things in other CMake files. In particular, searching for headers but then not adding the found paths to the target, nor using the found paths for libraries.  Needs a fix here and elsewhere.

**Comment by vlazzarini** [comment]
@eddyc  is that your code? Could you take a look?

**Comment by kunstmusik** [comment]
I could get things to build using finder, but I'm not sure this would work on non-homebrew:

```diff --git a/Opcodes/websockets/CMakeLists.txt b/Opcodes/websockets/CMakeLists.txt
index ccfad7cf0..ccf5728b9 100644
--- a/Opcodes/websockets/CMakeLists.txt
+++ b/Opcodes/websockets/CMakeLists.txt
@@ -37,7 +37,12 @@ if(BUILD_WEBSOCKET_OPCODE)
  	target_link_libraries(websocketIO ${websockets_library} ${CSOUNDLIB})
 
   if(APPLE)
-   target_link_libraries(websocketIO /usr/local/lib/libssl.a /usr/local/lib/libcrypto.a  z)
+      set(OPENSSL_USE_STATIC_LIBS TRUE)
+      set(OPENSSL_ROOT_DIR /usr/local/opt/openssl) 
+      find_package(OpenSSL)
+
+      target_link_libraries(websocketIO ${OPENSSL_LIBRARY} ${OPENSSL_CRYPTO_LIBRARY} z)
+   target_include_directories(websocketIO PRIVATE ${OPENSSL_INCLUDE_DIR})
   endif()
 
   if(WIN32 AND NOT MSVC)
```

In particularly, the ```set(OPENSSL_ROOT_DIR /usr/local/opt/openssl) ``` line.

**Comment by stekyne** [comment]
We should be trying to use Find_*.cmake modules to link these modules instead of doing it manually. Here is an example: https://github.com/apache/qpid-dispatch/blob/master/cmake/FindLibWebSockets.cmake

**Comment by kunstmusik** [comment]
We should probably figure out our best practice for all of this, document it, and do a larger audit of our build system.

**Comment by stekyne** [comment]
I think the big limitation on that last time was the requirement for a fairly old Cmake version. Is that still the case? Wasn't there a pull request to update a lot of it?

**Comment by eddyc** [comment]
I'll have a look at this over the weekend.
Ed

**Comment by jpffitch** [comment]
Any  progress?  over 3months since last action.

**Comment by stekyne** [comment]
It should be easy to just add the FindWebsockets.cmake I linked to earlier into the cmake/modules folder and use that in the CMakeLists.txt in the websockets folder to find and link it to the CMake target. I'd do it but I don't have access to a Mac at the minute.

**Comment by nwhetsell** [comment]
Websocket opcodes were moved to [csound/plugins](https://github.com/csound/plugins) with—

* https://github.com/csound/csound/commit/0e1584c297748c891dbb19b51b6bbebf7d8514f9
* https://github.com/csound/plugins/commit/c514d7f4dc290b9668ad762950a53e019f5b6ca3

—so this issue no longer applies here. However, the hard-coding of library locations on macOS remains in csound/plugins—

https://github.com/csound/plugins/blob/766022d68a2c2c7933d95ef8943af9bdd5fa0d51/websockets/CMakeLists.txt#L41-L43

—so it’s unlikely that websocket opcodes can be built on that platform.

**Comment by vlazzarini** [comment]
OK, since the author never fixed this, I can try and have a go later.

**Comment by vlazzarini** [comment]
I fixed this now, removing the hard-coded paths
