### ISSUE TITLE
undefined reference to `csoundCreate', `csoundInitialize', `csoundDestroy'

### ISSUE THREAD

**Issue by marcoippolito** [csound/csound#1185]
I installed csound in Ubuntu 18.04.02 Server Edition through the official Ubuntu repository:

    (base) marco@pc:~$ sudo aptitude install libcsound64-6.0 libcsound64-dev libcsoundac6.0v5 
    libcsnd-dev libcsnd-dev csound csound-utils

and I'm trying to understand how to compile a csound program in C++:

    #include <stdio.h>
    #include "csound.hpp"

    int main(int argc, char* argv[])  {
        CSOUND*csound=csoundCreate(0);
        csoundInitialize(argc);
        csoundDestroy(csound);
    }

    g++ -std=c++17 -DUSE_DOUBLE -I /usr/include/csound -L /usr/lib/csound -lcsound64 
    csound_capiTest01.cpp -o csound_capiTest01
    /tmp/ccqW9XZ4.o: In function `main':
    csound_capiTest01.cpp:(.text+0x15): undefined reference to `csoundCreate'
    csound_capiTest01.cpp:(.text+0x23): undefined reference to `csoundInitialize'
    csound_capiTest01.cpp:(.text+0x2f): undefined reference to `csoundDestroy'
    collect2: error: ld returned 1 exit status

    g++ -std=c++17 -DUSE_DOUBLE -I /usr/include/csound -L /usr/lib/csound/plugins64-6.0 -lcsound64 
    csound_capiTest01.cpp -o csound_capiTest01
    /tmp/ccoTCbmh.o: In function `main':
    csound_capiTest01.cpp:(.text+0x15): undefined reference to `csoundCreate'
    csound_capiTest01.cpp:(.text+0x23): undefined reference to `csoundInitialize'
    csound_capiTest01.cpp:(.text+0x2f): undefined reference to `csoundDestroy'
    collect2: error: ld returned 1 exit status

    gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)

How to correctly compile this simple file?
Marco

**Comment by vlazzarini** [comment]
Try putting the .cpp filename before -lcsound64 in the command line,

g++ csoundCapiTest_01.cpp ...

Prof. Victor Lazzarini
Maynooth University
Ireland

On 6 Sep 2019, at 18:00, Marco Ippolito <notifications@github.com<mailto:notifications@github.com>> wrote:


I installed csound in Ubuntu 18.04.02 Server Edition through the official Ubuntu repository:

(base) marco@pc:~$ sudo aptitude install libcsound64-6.0 libcsound64-dev libcsoundac6.0v5
libcsnd-dev libcsnd-dev csound csound-utils


and I'm trying to understand how to compile a csound program in C++:

#include <stdio.h>
#include "csound.hpp"

int main(int argc, char* argv[])  {
    CSOUND*csound=csoundCreate(0);
    csoundInitialize(argc);
    csoundDestroy(csound);
}

g++ -std=c++17 -DUSE_DOUBLE -I /usr/include/csound -L /usr/lib/csound -lcsound64
csound_capiTest01.cpp -o csound_capiTest01
/tmp/ccqW9XZ4.o: In function `main':
csound_capiTest01.cpp:(.text+0x15): undefined reference to `csoundCreate'
csound_capiTest01.cpp:(.text+0x23): undefined reference to `csoundInitialize'
csound_capiTest01.cpp:(.text+0x2f): undefined reference to `csoundDestroy'
collect2: error: ld returned 1 exit status

gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)


How to correctly compile this simple file?
Marco

**Comment by vlazzarini** [comment]
I am closing this as it is not an issue with the system. Please sign up to email list if you need support from other users.

**Comment by marcoippolito** [comment]
Thanks for your kind reply. I'm going to sign up to the email list. Kind regards. Marco
