### ISSUE TITLE
ftgenonce with GEN01 ignores the filename for indexing 

### ISSUE THREAD

**Issue by yrechab** [csound/csound#1186]
hi,
may be this is intended (had this idea when reading the the source code of ftgenonce) but
it prevents to have more samples encapsulated in a reusable instrument. 
Here is a simple example, on the second call with another file the same table number is returned -  the second file is not loaded at all.
It behaves correctly if e.g the skip parameter is set to 0.001 on one call.

`<CsoundSynthesizer>
<CsOptions>
</CsOptions>
; ==============================================
<CsInstruments>

sr	=	44100
ksmps	=	32
nchnls	=	2
0dbfs	=	1

instr 1	
it0   ftgenonce   0, 0, 0, 1, "kickroll.wav", 0, 0, 0
it1   ftgenonce   0, 0, 0, 1, "mary.wav", 0, 0, 0
;it1   ftgenonce   0, 0, 0, 1, "mary.wav", 0.001, 0, 0 behaves correctly
print it0,it1
endin

</CsInstruments>
; ==============================================
<CsScore>
i 1 0
e
</CsScore>
</CsoundSynthesizer>

--Csound version 6.13 (double samples) Jul 20 2019
[commit: 297845a370b8b5e1b555a60a0be3c5c757599530]
[...]
ftgenonce: created new func: 101
ftgenonce: re-using existing func: 101.000000
instr 1:  it0 = 101.000  it1 = 101.000
`

Best Regards,
Christian

**Comment by gogins** [comment]
Thanks for the information. I did not consider this case when I designed
ftgenonce. I think it can be fixed but I have to look once more at the code.

Regards,
Mike

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by gogins** [comment]
The ftgenonce code in signalflowgraph.cpp SHOULD have worked. However, there seems to be some subtle misbehavior in std::isnan. I have replaced the use of that with a pointer to CSOUND.ISSTRCOD and that seems to solve the problem.

**Comment by yrechab** [comment]
Hi,
i get still the same table numbers
--Csound version 6.14 (double samples) Sep 17 2019
[commit: 3fe9f8a41159ab28e59150c2c9e1f5298f2de52b]
libsndfile-1.0.28
UnifiedCSD:  ftgeonce.csd
STARTING FILE
Creating options
Creating orchestra
closing tag
Creating score
[...]
SECTION 1:
new alloc for instr 1:
ftable 101:
deferred alloc for kickroll.wav
audio sr = 44100, stereo, reading both channels
opening WAV infile kickroll.wav
  defer length 37792
ftable 101:	75585 points, scalemax 1.000
[...]
ftgenonce: created new func: 101
ftgenonce: re-using existing func: 101.000000
instr 1:  it0 = 101.000  it1 = 101.000

when calling with different skip parameter
instr 1	
it0   ftgenonce   0, 0, 0, 1, "kickroll.wav", 0, 0, 0
it1   ftgenonce   0, 0, 0, 1, "mary.wav", 0.001, 0, 0
print it0,it1
endin
it works:
ftable 101:
deferred alloc for kickroll.wav
audio sr = 44100, stereo, reading both channels
opening WAV infile kickroll.wav
  defer length 37748
ftable 101:	75497 points, scalemax 1.000
[...]
ftgenonce: created new func: 101
ftable 102:
deferred alloc for mary.wav
audio sr = 44100, monaural
opening WAV infile mary.wav
  defer length 154390
ftable 102:	154390 points, scalemax 1.000
[...]
ftgenonce: created new func: 102
instr 1:  it0 = 101.000  it1 = 102.000

**Comment by yrechab** [comment]
Sorry i forgot that i had installed the libs, it works now after a make install

**Comment by jpffitch** [comment]
Did not compile for me

/home/jpff/csound6/Opcodes/signalflowgraph.cpp:197:5: error: multi-line comment [-Werror=comment]
     // i, a.evtblk.pcnt, a.evtblk.p[i], &b, i, b.evtblk.pcnt, b.evtblk.p[i]);\
     ^
cc1plus: all warnings being treated as errors
make[2]: *** [Opcodes/CMakeFiles/signalflowgraph.dir/build.make:66: Opcodes/CMak
