### ISSUE TITLE
OSCraw only returns two string parameters (path and types)

### ISSUE THREAD

**Issue by yrechab** [csound/csound#1187]
hi,
i have tested the provided test script in the documentation for OSCraw.
The script only returned 
--Csound version 6.13 (double samples) Jul 20 2019
[commit: 297845a370b8b5e1b555a60a0be3c5c757599530]
libsndfile-1.0.28
[...]
SECTION 1:
: /foo/bar : ,f 2 items
: /foo/bar : ,f 2 items
: /foo/bar : ,f 2 items
: /foo/bar : ,f 2 items
: /foo/bar : ,f 2 items

so the sended value was not returned.
the reason seems to be in the line 
sockrecv.c -  init_raw_osc line 616 (current dev branch): 
tabinit(csound, p->sout,2);

this causes sout->sizes[0] = 2 regardless of the size of the input array
and this stops the processing of the osc message after the types argument.

i have changed it locally to 
tabinit(csound, p->sout,p->sout->sizes[0]);
and now it works fine.
: /foo/bar : ,f : 1.000000 3 items
: /foo/bar : ,f : 2.000000 3 items
: /foo/bar : ,f : 3.000000 3 items
: /foo/bar : ,f : 4.000000 3 items
: /foo/bar : ,f : 5.000000 3 items

well, i dont know if this is correct for all cases please have a look.
Thanks,
Christian

**Comment by vlazzarini** [comment]
looks like the recent changes to arrays broke this opcode too

**Comment by vlazzarini** [comment]
The manual says:

"Smess[] -- an array of strings containing the message components: address, types, and data items. If the array does not exist (ie. has not been initialised), one will be created with size 2. Arrays cannot grow with the size of the message, so if a message with more than 2 items (ie. with any data items) is to be fully copied into the output, a larger array needs to initialised before it is used. If a message has more items than an array has space for, it is truncated."

So clearly the change in the arrays code resulted in the code behaving as if the array did not exist. 

Your proposed fix will work for all cases where there is an existing output array. We need to make sure it also works as per the manual when there is no existing array.

**Comment by yrechab** [comment]
ok, got it something like
tabinit(csound, p->sout,p->sout->data!=NULL?p->sout->sizes[0]:2);
(this code worked with an undeclared array like 
Smess[],ka OSCraw 10000)

**Comment by vlazzarini** [comment]
yes, it would be something like that, thanks

**Comment by vlazzarini** [comment]
Fixed in git
