### ISSUE TITLE
GENsone is printing overwhelming amount of logs

### ISSUE THREAD

**Issue by hlolli** [csound/csound#1201]
Running gensone.csd prints some thousands of lines of this, it's definitely coming from c, will fix.

```
writing 1024-byte blks of shorts to tmp/gensone.wav (WAV)
SECTION 1:
0.000000 -> 0.000000
1.953125 -> 0.032189
...etc...
```

**Comment by hlolli** [comment]
I include the fix in my soak-test PR, since it wont run with logs without commenting this out (maximum log size causes Travis to fail).

**Comment by jpffitch** [comment]
Fixed
