### ISSUE TITLE
Is linseg broken? 

### ISSUE THREAD

**Issue by rorywalsh** [csound/csound#1202]
The following instrument doesn't play as expected. I'm running a build from the dev branch on the 18th of Oct.

```
instr 1
    aEnv linseg 0, 5, 1, 5, 0
    a1 oscili aEnv, 400
    outs a1, a1
endin

schedule(1, 0, 10)
```

I'm certainly not hearing a 5 second fade in or fade out? 

FWIW - `expseg` works just fine..

**Comment by jpffitch** [comment]
What value for 0dbfs?

⁣Sent from TypeApp ​

**Comment by rorywalsh** [comment]
I should say, this is on Windows with an Appveyor build. I haven't tried
it yet on any other platforms. What I hear is a very short fade in and fade
out.

**Comment by jpffitch** [comment]
Bizarrrrrr

If I run to file I get a silent file.  If I run with -odac and -v it 
works, fade in and fade out.


Bust try other combinations.  I note that just remving the enveope also 
fails.
==Jon

**Comment by jpffitch** [comment]
If I add an e 12 to te score it works to file or dac.  Suggests the the 
infinite score if trumping (sory) the schedule

**Comment by vlazzarini** [comment]
not here; works for dac and file. DId you remember to add a "e 10" to close csound after 10 s?
```
victor@MacBook-Pro debug % ./csound -otest.aif linseg.csd
time resolution is 1000.000 ns
0dBFS level = 32768.0
--Csound version 6.14 beta (double samples) Oct 18 2019
[commit: 56bac354c36246bc0ff0c9a29dc32228853c71d9]
libsndfile-1.0.28
UnifiedCSD:  linseg.csd
STARTING FILE
Creating options
Creating orchestra
closing tag
Creating score
rtaudio: PortAudio module enabled ...
using callback interface
rtmidi: PortMIDI module enabled
Elapsed time at end of orchestra compile: real: 0.002s, CPU: 0.002s
sorting score ...
	... done
Elapsed time at end of score sort: real: 0.002s, CPU: 0.002s
displays suppressed
0dBFS level = 1.0
orch now loaded
audio buffered in 1024 sample-frame blocks
writing 4096-byte blks of shorts to test.aif (AIFF)
SECTION 1:
new alloc for instr 1:
B  0.000 .. 10.000 T 10.000 TT 10.000 M:  0.99957  0.99957
Score finished in csoundPerform().
inactive allocs returned to freespace
end of score.		   overall amps:  0.99957  0.99957
	   overall samples out of range:        0        0
0 errors in performance
Elapsed time at end of performance: real: 0.056s, CPU: 0.055s
2048 4096 sample blks of shorts written to test.aif (AIFF)
```

**Comment by rorywalsh** [comment]
Strange, if I run it to file it works fine. But I can't get the same result when running in real time, even with an e statement in my score...

This is my full file:

```
<CsoundSynthesizer>
<CsOptions>
-odac
<CsInstruments>
0dbfs = 1
nchnls = 2
ksmps = 32

instr 1
    aEnv linseg 0.0001, p3/2, 1, p3/2, 0.0001
    a1 oscili 1, 400
    outs a1*aEnv, a1*aEnv
endin

</CsInstruments>
<CsScore>
i1 0 10
e 10
</CsScore>
</CsoundSynthesizer>
```

**Comment by vlazzarini** [comment]
the "e 10" is only needed if you were using schedule. If the problem is RT, then it's to do with the rt audio module on Windows.

Nothing wrong with linseg

**Comment by vlazzarini** [comment]
oh sorry just saw you are using the audio version, try k-rate.

**Comment by rorywalsh** [comment]
Same thing there. This is really strange. If I write to disk it is fine. And even more strange, if I write to disk with `fout`, it's still fine.  I've just spent the last ten minutes trying to do a simple stereo mix recording on Windows 10 to illustrate the problem, but it turns out MS got rid of that feature somehow. I'm going to reboot into Linux now and see if things are the same there.

**Comment by vlazzarini** [comment]
ok, did you try running anything else, other csds?
What about in Cabbage?

**Comment by rorywalsh** [comment]
It runs fine for me in Cabbage. I can hear the 5 second fade in and fade out. Before I spent any more time on this let me just install the very latest build and see things are better there.

**Comment by rorywalsh** [comment]
I'm going to close this, as it looks like an issue local to my machine. @stekyne tested the MME drivers on his windows PC and it works fine there so I think it's safe to assume it probably works fine for everyone else too.

**Comment by vlazzarini** [comment]
MME is VERY old, surprised it's still used.

**Comment by kunstmusik** [comment]
I wrote about WASAPI running well in a separate thread some time ago. I
filed an issue now to keep track of it:

https://github.com/csound/csound/issues/1203

I'll start another thread about portaudio on the dev list I'm curious to
ask about.
