### ISSUE TITLE
HRTF data files not installed using `make install`

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#1206]
It looks like there are no CMake options that allow installing HRTF data files in the [samples](https://github.com/csound/csound/tree/develop/samples) directory using `make install`. This prevents packaging HRTF data files with Csound on [Homebrew](https://brew.sh).

**Comment by vlazzarini** [comment]
Done in git.

**Comment by nwhetsell** [comment]
Thanks, although putting these in CsoundLib64.framework on macOS—

https://github.com/csound/csound/blob/94bb8b367e27134763c110557add72495daeb1e5/CMakeLists.txt#L1436-L1443

—seems unintuitive, especially since `share` is already used on macOS for things like FindCsound.cmake:

https://github.com/csound/csound/blob/94bb8b367e27134763c110557add72495daeb1e5/CMakeLists.txt#L1432-L1434

It may be better to put HRTF data files in their own folder in `share`:

```cmake
install(
  DIRECTORY ${CMAKE_SOURCE_DIR}/samples
  DESTINATION ${CMAKE_INSTALL_PREFIX}/share/hrtf-data
)
```

(Also, the `SAMPLES_INSTALL_DIR` variable—

https://github.com/csound/csound/blob/94bb8b367e27134763c110557add72495daeb1e5/CMakeLists.txt#L30

—appears to be unused.)
