### ISSUE TITLE
bug in conditionals introduced last 2 months

### ISSUE THREAD

**Issue by Oeyvind** [csound/csound#1211]
There seems to be a bug with  conditionals like this
ktest = (k2>k1?1:0)

With the latest appveyor build 6.14.290 5th Nov it outputs zero even if k2 is greater than k1.
Tested with an earlier build  6.14.101 12 oct and the same problem appears there.
It works fine with the build 6.14.61 29th Aug

```
<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

instr 1
k1 = 1
k2 = 2
ktest = (k2>k1?1:0)
printk2 ktest
endin
; Problem in 6.14.290 5th Nov
; Problem in 6.14.101 12 oct
; OK in 6.14.61 29th Aug
</CsInstruments>
<CsScore>
i1      0     1
e
</CsScore>
</CsoundSynthesizer>

```

**Comment by kunstmusik** [comment]
I tested here with a recent build and also get 0. With 6.13.0 I get 1. @jpffitch this seems to be related to code you had changed recently?

**Comment by jpffitch** [comment]
Looks like rate problem. First look says it is OK apart from the answer.....

**Comment by jpffitch** [comment]
ktest = (k2>k1?1:0)
generates
```
#b1 = k2>k1
if #b1 goto L1
#i1 = 1
goto L2
L1:
#i1 = 0
L2:
ktest = \#i1
``` 
which looks right except if it had #k1 insteat of #i1 the rates would work.
If that is correct analysis I need to force the type of the intermediate to rate of test.  Wonder how to do that!

**Comment by kunstmusik** [comment]
This looks off to me, seem like it should #B1 rather than #b1 for a k-rate boolean.

**Comment by jpffitch** [comment]
My typo; anyway fixed in git now

Was type of jumps being wrong in one case
