### ISSUE TITLE
Opcodes `connect` and `alwayson` don't compile in Csound WASM

### ISSUE THREAD

**Issue by andy-fillebrown** [csound/csound#1213]
The `connect` and `alwayson` opcodes don't compile when using Csound WASM.

**Comment by vlazzarini** [comment]
These are in plugin libs and at the moment WASM does not allow for dynamic lib loading.

**Comment by gogins** [comment]
These and other plugins work in the version of Csound for WASM maintained
by me in my csound-extended repository. The code is statically linked with
distinguished names for the csoundModuleCreate etc. functions. With a tiny
bit of work this could be done in the canonical version. The required code
already exists in the canonical repository and simply needs to be used.

**Comment by vlazzarini** [comment]
As they run on your csound-extended, the best thing is for @andy-fillebrown to be referred to that version.

**Comment by kunstmusik** [comment]
Emscripten does permit dynamic linking (dlopen). It's an open item to
research on my list, but others are welcome to go for it. :)

**Comment by vlazzarini** [comment]
I should have qualified WASM Csound does not allow dynamic linking (i.e. loading of plugins), this did not mean that WASM in general does not allow it. 

First step is to enable dlopen() and friends in the build (csmodule.c). Then create the plugins and introduce JS code to bring the plugin files into the sandbox.

**Comment by andy-fillebrown** [comment]
Interesting. Thank you all for the info.
