### ISSUE TITLE
CSD `//` comments don't compile in the CsOptions section

### ISSUE THREAD

**Issue by andy-fillebrown** [csound/csound#1214]
`//` comments compile in the `<CsInstruments>` and `<CsScore>` sections of a .csd file, but not in the `<CsOptions>` section.

`;` comments compile in the `<CsOptions>` section but it would be nice to have `//` comments work in all sections of a .csd file.

**Comment by jpffitch** [comment]
There is code to take notice of // comments, but I think not at the start of a line.  I added another check but not properly tested yet
