### ISSUE TITLE
CMake JAVA_MODULE_INSTALL_DIR ignored on macOS, build folder is used for @rpath

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#1216]
The `JAVA_MODULE_INSTALL_DIR` cache entry is set at

https://github.com/csound/csound/blob/2e02be236b35c8f77e576c729349c88c50d78078/CMakeLists.txt#L214

Since `JAVA_MODULE_INSTALL_DIR` is a cache entry, it’s expected to be able to set it when building Csound, for example:

```sh
cmake -DJAVA_MODULE_INSTALL_DIR:PATH=/usr/local/opt/csound/libexec ../csound
```

However, on macOS `JAVA_MODULE_INSTALL_DIR` is usually overwritten to always be `~/Library/Java/Extensions` (line 461):

https://github.com/csound/csound/blob/2e02be236b35c8f77e576c729349c88c50d78078/CMakeLists.txt#L457-L467

In addition, as reported by `otool -l lib_jcsound6.jnilib`, lib_jcsound6.jnilib looks for CsoundLib64 (and libcsnd6.6.0.dylib) using run-path–relative pathnames:

```
Load command 10
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libcsnd6.6.0.dylib (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 6.0.0
Load command 11
          cmd LC_LOAD_DYLIB
      cmdsize 80
         name @rpath/CsoundLib64.framework/Versions/6.0/CsoundLib64 (offset 24)
   time stamp 2 Wed Dec 31 19:00:02 1969
      current version 0.0.0
compatibility version 6.0.0
```

However, the value of `@rpath` is the CMake build folder—

```
Load command 14
          cmd LC_RPATH
      cmdsize 72
         path /tmp/csound-20191110-1827-1v4s842/csound-6.13.0/build (offset 12)
```

—which may not survive after installation. Homebrew, for example, builds Csound in a temporary folder that’s deleted immediately after installation, so lib_jcsound6.jnilib can’t find CsoundLib64.

**Comment by vlazzarini** [comment]
happy to take a PR if you know what needs fixing.

**Comment by nwhetsell** [comment]
PR #1217 removes the overwriting of `JAVA_MODULE_INSTALL_DIR` on macOS. I’m not familiar enough with how Csound is using CMake to attempt anything more.

**Comment by vlazzarini** [comment]
merged, thx, does that solve the ticket?

**Comment by nwhetsell** [comment]
Yes.

**Comment by kunstmusik** [comment]
1. This breaks 'make install' now and installs the Java library into a
subfolder of the build directory
2. The overwriting of the framework destination happens for the csound
framework too

set(CS_FRAMEWORK_DEST "~/Library/Frameworks" CACHE PATH "Csound framework
path")

I don't think this is the whole solution. I think it'd be good to install
the Java interface into a sensible location by default.

**Comment by nwhetsell** [comment]
> This breaks `make install` now and installs the Java library into a subfolder of the build directory

You can pass

```
-DJAVA_MODULE_INSTALL_DIR:PATH=~/Library/Java/Extensions
```

to `cmake`, right?

> The overwriting of the framework destination happens for the csound framework too
>
> https://github.com/csound/csound/blob/e1379366e934044ed0092c1f85aed9f66f5a5864/CMakeLists.txt#L28

No, this [sets a cache entry](https://cmake.org/cmake/help/latest/command/set.html#set-cache-entry) with a default value of `~/Library/Frameworks`. This doesn’t overwrite a previous value of `CS_FRAMEWORK_DEST`. If you pass

```
-DCS_FRAMEWORK_DEST:PATH=/usr/local/Frameworks
```

to `cmake`, `CS_FRAMEWORK_DEST` will be `/usr/local/Frameworks`, not `~/Library/Frameworks`.

> I don't think this is the whole solution. I think it'd be good to install the Java interface into a sensible location by default.

I agree. My only goal with pull request #1217 was to eliminate the overwriting of `JAVA_MODULE_INSTALL_DIR` so it can actually be used as a cache entry.

**Comment by kunstmusik** [comment]
Okay, so this needs additional work since it needs a sensible default. I'll
take a look at an alternative.

**Comment by kunstmusik** [comment]
I pushed a change that has a fix. It defaulted here to
~/LIbrary/Java/Extensions when no value set on commandline, but also
overrides when commandline value given. @nwhetsell if you could verify
that'd be appreciated.

**Comment by nwhetsell** [comment]
I can verify that on macOS 10.14.6 `JAVA_MODULE_INSTALL_DIR` can be set as expected at commit 261a6ab748ad43c0644a9bca34b21c3242081f7c.
