### ISSUE TITLE
Ubuntu 18.04 package (6.10) is broken, issues with latest (6.13) release

### ISSUE THREAD

**Issue by maximecb** [csound/csound#1219]
Hello,

I'm running Ubuntu 18.04 (x86-64). I ran into issues with examples straight from the CSound manual. I think it might be time to update this package.

This example gives me a segmentation fault:
http://www.csounds.com/manual/html/examples/tbvcf.csd

```
0dBFS level = 32768.0
--Csound version 6.10 (double samples) 2018-01-27 
[commit: none]
libsndfile-1.0.28
UnifiedCSD:  diode_ladder.csd
STARTING FILE
Creating options
Creating orchestra
closing tag
Creating score
rtaudio: ALSA module enabled
rtmidi: ALSA Raw MIDI module enabled

csound command: Segmentation fault
end of score.		   overall amps:      0.0
	   overall samples out of range:        0
0 errors in performance
Elapsed time at end of performance: real: 0.252s, CPU: 0.002s
```

This example gives me samples out of range, and stops making any sound after the 5th note is played. I'm assuming that's not normal:
https://csound.com/docs/manual/examples/diode_ladder.csd

I then tried installing the latest release from GitHub (6.13), but I couldn't get either of these examples to work. I'm getting segmentation faults. Also getting a warning about libncurses 6 not being loaded, which may or may not be related. There is no package for libncurses 6 available on Ubuntu 18.04. I would strongly advise that you link your build with libncurses 5 by default, to make everyone's life easier. In addition to this, you might want statically link everything with your precompiled releases, because IMO the point of a precompiled release is to simplify things and avoid many of the annoying surprises (dependency hell) that can come when building from source.

**Comment by vlazzarini** [comment]
We don't package for ubuntu, the released binaries were built with Debian so not guaranteed to work elsewhere.

The advice for Linux is to build from
sources, which is straghtforward, check the instructions in BUILD.md.

We'll check these examples. Please always refer to the manual from the community site csound.com, not csounds.com, because that is the only one guaranteed to be updated regularly.

Btw, the correct name is Csound, not CSound.

**Comment by vlazzarini** [comment]
I checked tbvcf and it appears to get unstable with some values of Q > 2 (which is said in the manual to be the top of the range). So we need to fix the manual example (done in git). I guess you need to be careful. Here's the fixed example:

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
; Audio out   Audio in    No messages
-odac           -iadc     -d     ;;;RT audio I/O
; For Non-realtime ouput leave only the line below:
; -o tbvcf.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

;---------------------------------------------------------
; TBVCF Test
; Coded by Hans Mikelson December, 2000
;---------------------------------------------------------
  sr =  44100   ; Sample rate
  ksmps =  10   ; Samples/Kontrol period
  nchnls =  2        ; Normal stereo
  0dbfs = 1


          instr 10

  idur	=	p3			; Duration
  iamp	=	p4			; Amplitude
  ifqc	=	cpspch(p5)		; Pitch to frequency
  ipanl	=	sqrt(p6)		; Pan left
  ipanr	=	sqrt(1-p6)		; Pan right
  iq	=	p7
  idist	=	p8
  iasym =	p9

kdclck		linseg	0, .002, 0.9, idur-.004, 0.9, .002, 0	; Declick envelope
kfco		expseg	10000, idur, 1000			; Frequency envelope
ax		vco		1, ifqc, 2, 0.5			; Square wave
ay		tbvcf		ax, kfco, iq, idist, iasym		; TB-VCF
ay		buthp	ay/1, 100				; Hi-pass

		outs		ay*iamp*ipanl*kdclck, ay*iamp*ipanr*kdclck
          endin


</CsInstruments>
<CsScore>

f1 0 65536 10 1

; TeeBee Test
;   Sta  Dur  Amp    Pitch Pan  Q    Dist1 Asym
i10 0    0.2  0.5    7.00  .5   0.0  2.0   0.0
i10 0.3  0.2  0.5    7.00  .5   0.8  2.0   0.0
i10 0.6  0.2  0.5    7.00  .5   1.6  2.0   0.0
i10 0.9  0.2  0.5    7.00  .5   1.8  2.0   0.0
i10 1.2  0.2  0.5    7.00  .5   2.0  2.0   0.0
i10 1.8  0.2  0.5    7.00  .5   0.0  2.0   0.25
i10 2.1  0.2  0.5    7.00  .5   0.8  2.0   0.25
i10 2.4  0.2  0.5    7.00  .5   1.6  2.0   0.25
i10 2.7  0.2  0.5    7.00  .5   1.8  2.0   0.25
i10 3.0  0.2  0.5    7.00  .5   1.9  2.0   0.25
i10 3.3  0.2  0.5    7.00  .5   2.0  2.0   0.25
i10 3.6  0.2  0.5    7.00  .5   0.0  2.0   0.5
i10 3.9  0.2  0.5    7.00  .5   0.8  2.0   0.5
i10 4.2  0.2  0.5    7.00  .5   1.6  2.0   0.5
i10 4.5  0.2  0.5    7.00  .5   1.8  2.0   0.5
i10 4.8  0.2  0.5    7.00  .5   1.9  2.0   0.5
i10 5.1  0.2  0.5    7.00  .5   2.0  2.0   0.5
i10 5.4  0.2  0.5    7.00  .5   0.0  2.0   0.75
i10 5.7  0.2  0.5    7.00  .5   0.8  2.0   0.75
i10 6.0  0.2  0.5    7.00  .5   1.6  2.0   0.75
i10 6.3  0.2  0.5    7.00  .5   1.8  2.0   0.75
i10 6.6  0.2  0.5    7.00  .5   1.9  2.0   0.75
i10 6.9  0.2  0.5    7.00  .5   2.0  2.0   0.75
i10 7.2  0.2  0.5    7.00  .5   0.0  2.0   1.0
i10 7.5  0.2  0.5    7.00  .5   0.8  2.0   1.0
i10 7.8  0.2  0.5    7.00  .5   1.6  2.0   1.0
i10 8.1  0.2  0.5    7.00  .5   1.8  2.0   1.0
i10 8.4  0.2  0.5    7.00  .5   1.9  2.0   1.0
i10 8.7  0.2  0.5    7.00  .5   2.0  2.0   1.0
e


</CsScore>
</CsoundSynthesizer>
```

**Comment by vlazzarini** [comment]
The diode ladder example works fine with 6.13. 
I am closing this ticket. If you need to ask question about these opcodes, please do so in the mailing list 
or in the slack forum, see https://csound.com/community.html

**Comment by maximecb** [comment]
> I checked tbvcf and it appears to get unstable with some values of Q > 2 (which is said in the manual to be the top of the range). So we need to fix the manual example (done in git). I guess you need to be careful. Here's the fixed example:

Thanks. I just tried your updated example. It no longer says samples out of range, but it does still stop making sound after 4-5 notes on csound 6.10.

By the way, can I assume that code from manual examples is in the public domain, free to use and modify?

> The advice for Linux is to build from sources, which is straghtforward, check the instructions in BUILD.md.

I was going to build from sources, but then I saw that the AppVeyor badge had "build failing", and that made me feel unsure. I see looking at the log that your tests seem to have passed, so I'll give it a shot.

> We don't package for ubuntu, the released binaries were built with Debian so not guaranteed to work elsewhere.

I still think it would be very helpful if you statically linked libraries for your binary releases. That makes it easier for people running on other Linux distributions to run your software. It seems like a good default.

**Comment by vlazzarini** [comment]
Appveyor is Windows-only, it won't affect you. The failure is also because we have done too many builds in the period. If you are unsure, you can also build from the master branch which is the released code.

The tbvcf now works on 6.13. The reason it stops making sound is that it goes unstable and produces signalling NaN so all the processing stops working from then on. I think this filter is fairly unstable and may be needed to be carefully used in any case.

**Comment by vlazzarini** [comment]
Sorry, I just checked again and the code I posted here was still unstable, so try this now:

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
; Audio out   Audio in    No messages
-odac           -iadc     -d     ;;;RT audio I/O
; For Non-realtime ouput leave only the line below:
; -o tbvcf.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

;---------------------------------------------------------
; TBVCF Test
; Coded by Hans Mikelson December, 2000
;---------------------------------------------------------
  sr =  44100   ; Sample rate
  ksmps =  10   ; Samples/Kontrol period
  nchnls =  2        ; Normal stereo
  0dbfs = 1


          instr 10

  idur	=	p3			; Duration
  iamp	=	p4			; Amplitude
  ifqc	=	cpspch(p5)		; Pitch to frequency
  ipanl	=	sqrt(p6)		; Pan left
  ipanr	=	sqrt(1-p6)		; Pan right
  iq	=	p7
  idist	=	p8
  iasym =	p9

kdclck		linseg	0, .002, 0.9, idur-.004, 0.9, .002, 0	; Declick envelope
kfco		expseg	10000, idur, 1000			; Frequency envelope
ax		vco		1, ifqc, 2, 0.5			; Square wave
ay		tbvcf		ax, kfco, iq, idist, iasym		; TB-VCF
ay		buthp	ay/1, 100				; Hi-pass

		outs		ay*iamp*ipanl*kdclck, ay*iamp*ipanr*kdclck
          endin


</CsInstruments>
<CsScore>

f1 0 65536 10 1

; TeeBee Test
;   Sta  Dur  Amp    Pitch Pan  Q    Dist1 Asym
i10 0    0.2  0.5    7.00  .5   0.0  2.0   0.0
i10 0.3  0.2  0.5    7.00  .5   0.8  2.0   0.0
i10 0.6  0.2  0.5    7.00  .5   1.6  2.0   0.0
i10 0.9  0.2  0.5    7.00  .5   1.8  2.0   0.0
i10 1.2  0.2  0.5    7.00  .5   2.0  2.0   0.0
i10 1.8  0.2  0.5    7.00  .5   0.0  2.0   0.25
i10 2.1  0.2  0.5    7.00  .5   0.8  2.0   0.25
i10 2.4  0.2  0.5    7.00  .5   1.6  2.0   0.25
i10 2.7  0.2  0.5    7.00  .5   1.8  2.0   0.25
i10 3.0  0.2  0.5    7.00  .5   1.9  2.0   0.25
i10 3.3  0.2  0.5    7.00  .5   2.0  2.0   0.25
i10 3.6  0.2  0.5    7.00  .5   0.0  2.0   0.5
i10 3.9  0.2  0.5    7.00  .5   0.8  2.0   0.5
i10 4.2  0.2  0.5    7.00  .5   1.6  2.0   0.5
i10 4.5  0.2  0.5    7.00  .5   1.8  2.0   0.5
i10 4.8  0.2  0.5    7.00  .5   1.9  2.0   0.5
i10 5.1  0.2  0.5    7.00  .5   2.0  2.0   0.5
i10 5.4  0.2  0.5    7.00  .5   0.0  2.0   0.75
i10 5.7  0.2  0.5    7.00  .5   0.8  2.0   0.75
i10 6.0  0.2  0.5    7.00  .5   1.6  2.0   0.75
i10 6.3  0.2  0.5    7.00  .5   1.8  2.0   0.75
i10 6.6  0.2  0.5    7.00  .5   1.9  2.0   0.75
i10 6.9  0.2  0.5    7.00  .5   2.0  2.0   0.75
i10 7.2  0.2  0.5    7.00  .5   0.0  2.0   1.0
i10 7.5  0.2  0.5    7.00  .5   0.8  2.0   1.0
i10 7.8  0.2  0.5    7.00  .5   1.6  2.0   1.0
i10 8.1  0.2  0.5    7.00  .5   1.8  2.0   1.0
i10 8.4  0.2  0.5    7.00  .5   1.9  2.0   1.0
i10 8.7  0.2  0.5    7.00  .5   2.0  2.0   1.0
e


</CsScore>
</CsoundSynthesizer>
```

**Comment by maximecb** [comment]
> Sorry, I just checked again and the code I posted here was still unstable, so try this now

Thanks. It works on 6.10.
