### ISSUE TITLE
Csound~ 6.07 OSX with max 8.1.0 and/or 8.1.1

### ISSUE THREAD

**Issue by zseramnay** [csound/csound#1225]
Hello
Impossible to instantiate csound~ since max 8.1.1
All the best

Yan

csound~: unable to load object bundle executable
 2019-11-16 12:08:58.479 Max[23862:1174170] Error loading /Users/yanmaresz/Dropbox/_Max/PRTM/ENGINE/CSOUND/csound~.mxo/csound~:  dlopen(/Users/yanmaresz/Dropbox/_Max/PRTM/ENGINE/CSOUND/csound~.mxo/csound~, 265): Library not loaded: /Users/M/Documents/Csoun
 dXcode/Release/CsoundLib64.framework/Versions/6.0/CsoundLib64
   Referenced from: /Users/yanmaresz/Dropbox/_Max/PRTM/ENGINE/CSOUND/csound~.mxo/csound~
   Reason: image not found

**Comment by rorywalsh** [comment]
That's a very old version of Csound~ you're using. Try this one, it's
recently built with the latest version of Csound:
https://github.com/csound/csound_tilde/releases

**Comment by zseramnay** [comment]
Oh thanks rorywalsh !
all good now..

I wont use the direct download link in the csound website anymore !
Best

Yan

**Comment by rorywalsh** [comment]
I'll update those links. They are way out of date!

**Comment by joachimheintz** [comment]
i was just about to fix this, and also the wrong download link for osx.
did you already, rory?

**Comment by rorywalsh** [comment]
Done 😉

**Comment by joachimheintz** [comment]
yes ... so i learned my first real git merge, haha.
i think this can be closed now.
