### ISSUE TITLE
Remove error message from api function FTnp2Find

### ISSUE THREAD

**Issue by gesellkammer** [csound/csound#1229]
When querying if a table exists, error messages should be done at the callsite, or a new api function FTExists could be provided for this. At the moment it is not possible from a plugin to query if a table exists without outputting an error message for every miss.

```c
typedef struct {
    OPDS h;
    MYFLT *iout, *ifn;
} FTEXISTS;

static int32_t ftexists_init(CSOUND *csound, FTEXISTS *p) {
    FUNC *ftp = csound->FTnp2Find(csound, p->ifn);
    *p->iout = (ftp != NULL) ? 1.0 : 0.0;
    return OK;
}
```

**Comment by jpffitch** [comment]
Done
