### ISSUE TITLE
how to run WASM demonstration in a local browser

### ISSUE THREAD

**Issue by xenophoria** [csound/csound#1235]
I am trying to run https://waaw.csound.com in a local browser. It took some time to work out how the local directory should be organised. I also changed the background colour of html files so it is easier to recognise when web assembly is being tested locally or on-line.

So far all examples work using either both Chrome and Safari except the following :

1 **Reverb** - microphone does not work locally in Safari browser but works in Chrome which asks permission to use a microphone (probably an issue with Safari set up).
2 **MIDI** player does not play locally.
3 **Stria** - **Stria.csd** plays on-line but does not play locally unless it is loaded using csdplayer.html
4 In the local browser the [**here**](https://waaw.csound.com/docs) link to https://waaw.csound.com/docs does not work.

I am working on these issues. Suggestions are welcome. 
Assuming others would like the site to include a working example of how to run the WASM demonstration in a local browser (with Victor Lazzarini’s approval) then I can provide my files either in zip format or as a git. I have a git address set up but have never organised a git so I would need help setting it up. 

My question is : is it better to provide the files as a zipped file using DropBox ? or as a git ?

Greg S

**Comment by docb** [comment]
at least chromium does play stria.html with: **chromium-browser --allow-file-access-from-files stria.html** -- seems otherwise be got difficult due to security reasons to load hardcoded files (i.e. not intended by the user via browse dialog)

**Comment by vlazzarini** [comment]
Are you using a local http server? These pages need to be served. I think I ran them
all locally back when I did the examples.

**Comment by docb** [comment]
what i meant is i could start stria.html without a local http server with chromium-browser passing  --allow-file-access-from-files on the command line. Without this parameter or e.g. on firefox i got a CORS error, which forbids loading local files which are addressed inside an opened local html file -- Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///......../stria.csd. (Reason: CORS request not http). My understanding was that this ticket also addresses this issue - may be i am wrong. So currently all examples work on my side without local http server.

**Comment by vlazzarini** [comment]
as far as I know the Wasm code and Audio Worklet code require the https protocol, so you can't open the page and run it just with the file protocol.
@kunstmusik or @hlolli should be able to confirm it.

**Comment by kunstmusik** [comment]
Apologies, just got around to replying. AudioWorklets require serving over a secure domain which can be either https or localhost, and they can not be loaded from a file URL. See https://developer.mozilla.org/en-US/docs/Web/API/AudioWorklet for more information.

**Comment by kunstmusik** [comment]
Closing as out-of-date. Local Csound Web applications should be tested/run using a web server (e.g., `npx http-server`, or using Live Server plugin for VS Code).
