### ISSUE TITLE
downsamp inaccuracy

### ISSUE THREAD

**Issue by Oeyvind** [csound/csound#1238]
There seems to be something odd happening when downsampling a pulse. Depending on the value of ksmps some pulses go missing. 

The example use mpulse to generate pulses and send them out to the left stereo channel.
The pulses are downsampled and then upsampled again, output to the right stereo channel.

Using ksmps = 1 in the example below allows all pulses in the left stereo channel to also appear in the right stereo channel. With higher values of ksmps, more an more pulses disappear in the right channel.

I would expect this to work the same independent of ksmps value.

```
<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

ksmps = 32
nchnls = 2
0dbfs = 1

instr 1
apulse mpulse 1,.1
kpulse downsamp apulse
outs apulse, a(kpulse)
endin

</CsInstruments>
<CsScore>
i1 0 4
</CsScore>
</CsoundSynthesizer>

```

**Comment by vlazzarini** [comment]
The manual says

```
iwlen (optional) -- window length in samples over which the audio signal is averaged to determine a downsampled value. Maximum length is ksmps; 0 and 1 imply no window averaging. The default value is 0.
```
so I am not surprised you are getting different results with ksmps changing.

**Comment by Oeyvind** [comment]
oh oh, I had all forgotten about the optional flag, and did not think I needed to look at the manual page for downsamp (!).
Sorry for the noise.
