### ISSUE TITLE
Android: Request for flexible widget interface

### ISSUE THREAD

**Issue by highfellow** [csound/csound#1239]
This is about the CSound for Android app. I have an application in mind for which I would like to have the use of a trackpad interface which uses as much of the available screen area as possible. (I would like to use the trackpad area as a drum pad). At the moment the trackpad is in quite a small area at the bottom of the screen. Would it be possible to make the widget interface flexible so that the user can choose which parts of the interface they want to see, so as to save screen space by hiding parts that are not needed? My suggestion is as follows:

* Give the console area at the bottom a hide button which collapses that area down to a minimum height.
* Give the row of buttons a hide button.
* Make the trackpad expand automatically to cover the whole available area that is not taken up by other widgets.
* Make the border between the buttons and the sliders draggable, so that the buttons and the top of the trackpad could be dragged up over the slider area, so users can choose how many sliders they wish to see.

However there may be better ways of implementing this feature, for example by using configuration options instead.

**Comment by gogins** [comment]
All of this can be done using HTML in the Csound for Android app and, with few if any changes, also in the csound.node addon for NW.js and in CsoundQt, which supports HTML in the same way.
