### ISSUE TITLE
Request for more fine grained information about trackpad touches

### ISSUE THREAD

**Issue by highfellow** [csound/csound#1240]
Would it be possible for the CSound for Android to return more fine grained information about the touches on the trackpad widget? At the moment there are just x and y coordinates but it would be good to have pressure as well, and an indication of the duration of the last touch. Some way of handling multitouch could be useful as well.

**Comment by kunstmusik** [comment]
Csound for Android is not a part of this repository or project. You'll have to ask @gogins who maintains that application about where to file issues for that.

**Comment by gogins** [comment]
This can be already be done in the Csound for Android app by using HTML and
JavaScript to define the trackpad and handle the trackpad events.

Regards,
Mike

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by highfellow** [comment]
Thanks for the information.
