### ISSUE TITLE
Segfault on syntax error...

### ISSUE THREAD

**Issue by rorywalsh** [csound/csound#1242]
The following syntax error results in a segfault, which presents fatal problems for frontends.

```
gitab[] fillarray 0,1,2
instr 1
    // NEXT LINE CRASHES DUE TO PAREN
    icrash = 1 +   ( gitab[1]
endin 
```

**Comment by jpffitch** [comment]
Fixed in github.  There may be other similar problems I have not found yet.

**Comment by rorywalsh** [comment]
Thanks John. A fast and efficient as ever!
