### ISSUE TITLE
OSCraw still broken - Only two parameters returned

### ISSUE THREAD

**Issue by pmanionatacm** [csound/csound#1245]
Hello there,
I am using: Csound version 6.13 (double samples) Jul 28 2019
on Mac OS X 10.13.6 (High Sierra)
The error occurs using either csoundqt-9.6 or the command line version.
OSCraw (which worked in earlier versions of csound) now only returns 2 parameters. This is also evident when running the code example from the manual. The output string array is sized '3' and the opcode only returns two values.

**Comment by vlazzarini** [comment]
afaik it's been fixed on git beta 6.14, waiting for the next release

**Comment by pmanionatacm** [comment]
Thank you! I'll check it out...
