### ISSUE TITLE
Segfault with printk command 

### ISSUE THREAD

**Issue by mikerodd** [csound/csound#1246]
I encountered this  when coding my synth in Cabbage, but it seems to be linked to CSound (see file)
the `printk` line 42 causes a segfault when playing a note in midi, removing this line or placing it somewhere else works.

[test6.zip](https://github.com/csound/csound/files/4050864/test6.zip)

Maybe it's caused by the loops ? 
I use Ubuntu 19.04, bug occurs in CSound 6.13 or 6.12

**Comment by jpffitch** [comment]
I cannot reproduce any crash.   Can you give detailed instructions?

Or this may be the bug I fixed a couple of days ago.  If so 6.14 shoud 
solve it in about 1 week
==John ff

**Comment by mikerodd** [comment]
Yes, it's corrected with 6.14, thanks :-)
