### ISSUE TITLE
Monotone output from sinsyn when phase info not given

### ISSUE THREAD

**Issue by iskunk** [csound/csound#1247]
I am testing analysis/resynthesis using Csound's TRACKS PV-related opcodes, and found a curious bug in a current Git build (0ce67f7c).

If `sinsyn` is called without having been given phase information in the preceding `partials` call, then the output is rendered in a monotone. With `fox.wav`, you get a classic bad-1950s-sci-fi-robot take on the original.

Here is the CSD to reproduce:
```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
;-odac     ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if real audio input is needed too
; For Non-realtime ouput leave only the line below:
 -o sinsyn-bug.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 1
0dbfs  = 1

instr 1
  aorig     diskin2 "fox.wav"

  ffr,fphs  pvsifd   aorig, 2048, 512, 1

  ftrk      partials ffr, ffr, 0, 1, 3, 500
  ;ftrk      partials ffr, fphs, 0, 1, 3, 500

  ares      sinsyn   ftrk, 1, 500, 1
  ;ares      resyn    ftrk, 1, 1, 500, 1
  ;ares      tradsyn  ftrk, 1, 1, 500, 1

  out ares

endin
</CsInstruments>
<CsScore>
f 1 0 4096 10 1

i 1 0 2.7
e
</CsScore>
</CsoundSynthesizer>
```

Note that the bug does not occur if (1) phase information is passed to `partials`, or (2) `resyn` or `tradsyn` is used instead. It appears to be only this combination which yields incorrect output.

**Comment by vlazzarini** [comment]
This is not a bug in the code, sinsyn requires phase info. We'll add to the manual page.

**Comment by iskunk** [comment]
I was under the impression that `sinsyn`, `resyn` and `tradsyn` were equivalent when the latter two get `kpitch = 1`. Is it reasonable behavior for `sinsyn` to yield a monotone in this case when the latter two don't? Especially as it's not obvious why withholding the phase info would lead to that result.

(This could be interesting as an effect, though it should probably be exposed in a different way...)

**Comment by vlazzarini** [comment]
No, they use different code altogether, sinsyn() needs phases otherwise the synthesis equation won't work.
