### ISSUE TITLE
CMake error re mp3out

### ISSUE THREAD

**Issue by PeteCA** [csound/csound#1248]
I grabbed the release version of 6.14 to ensure that it still compiles under Haiku [and I'm glad to say it does... (:-))] but I wanted to enable the new 'mp3out' code as well, and -- out of the box -- I couldn't get Cmake to recognize it (after setting 'BUILD_MP3OUT_OPCODE to 'ON', of course).  

It seems there's a mismatch in the names in Opcodes/CMakeLists.txt:

   check_include_file(lame.h LAME_HEADER)

and later:

  check_deps(BUILD_MP3OUT_OPCODE LAME_H)

I changed the latter to also be LAME_HEADER, and
it finally worked.

**Comment by PeteCA** [comment]
...and when I actually tried to compile, I found another one!

        make_plugin(mp3out lame.c $LAME_LIB})

 is missing an opening brace         ^

**Comment by jpffitch** [comment]
Tjank you.  Looks like I was asleep when that was written.  I think I have 
corrected develop branch but it sort of worked for me earlier.

**Comment by PeteCA** [comment]
Thanks for fixing.  Sadly the test csd in the release notes crashes Csound in Haiku (in mp3out_perf, but I can't tell any more right now).
It may be that the mp3lame library i have doesn't match -- it's supposedly from the lame 3.99 release, which is a few years old, but looks to be just about current.  Digging deeper may have to wait a while.

BTW the demo csd in the release notes is also missing some close-tag brackets!

**Comment by jpffitch** [comment]
I have v3.100 on linux and thatexample runs OK.  Would be interesed in 
whay is wrong with your run of the example.  When you have enou time that 
is.
