### ISSUE TITLE
building some opcodes requires -std=c++11

### ISSUE THREAD

**Issue by giuliomoro** [csound/csound#1252]
e.g.: `Opcodes/signalflowgraph.cpp` and `Opcodes/mixer.cpp` use `>>>>` , which is only allowed from c++11 onwards ( I think)

example, from `Opcodes/mixer.cpp`:
```
  std::map<CSOUND *, std::map<size_t, std::vector<std::vector<MYFLT>>>>
```

Maybe `cmake` should ensure that c++11 or higher is used?

**Comment by stekyne** [comment]
There are a couple of cmake flags like "CMAKE_CXX_STANDARD_REQUIRED" that can be added but I think the plan is to remove these opcodes into an external repo anyways. You could submit a PR adding these flags to the opcodes directory cmakelists.txt if you want.

**Comment by vlazzarini** [comment]
I see that either C++11 or gnu++11 are defined in CMakeLists.txt. I am closing this issue. If there are build problems, please open another issue with clearer diagnostics.
