### ISSUE TITLE
OSCraw array resize

### ISSUE THREAD

**Issue by Oeyvind** [csound/csound#1254]
OSCraw it seems to initialize the output array in another way than has been done before.

If I do this:
gSmess[] init 32
print lenarray(gSmess)
gSmess,ka OSCraw 9001
print lenarray(gSmess)

it will print size 32 on the first print, then it prints size 2 on the second print.

**Comment by vlazzarini** [comment]
I believe this might be fixed. Running the code above I get

```
new alloc for instr 1:
instr 1:  #i0 = 32.000
instr 1:  #i1 = 32.000
OSCraw: Closing socket
```
