### ISSUE TITLE
mfcc thing

### ISSUE THREAD

**Issue by Oeyvind** [csound/csound#1255]
There seems to be a problem processing the values in the array resulting from mfcc processing
I have the usual:
 if kcnt == gifftsize then
  kFFT[] = rfft(kIn)
  kPows[] = pows(kFFT)
  kMFB[] = log(mfb(kPows,300,8000,32))
  kmfcc[] = dct(kMFB)
  kcnt = 0
 endif

And this does not crash, but, when I later try to access the output array it crashes:

        kmfcc1          samphold kmfcc[1]*imfccscale, kgate
        kmfcc2          samphold kmfcc[2]*imfccscale, kgate
        kmfcc3          samphold kmfcc[3]*imfccscale, kgate
        kmfcc4          samphold kmfcc[4]*imfccscale, kgate
        kmfcc5          samphold kmfcc[5]*imfccscale, kgate
        kmfcc6          samphold kmfcc[6]*imfccscale, kgate

If I disable these lines by doing
          kmfcc1          =0;samphold kmfcc[1]*imfccscale, kgate
if does not crash and everything works (except mfcc output is always zero)

Could be that the array contains NaN, but this happens on a colleague's computer, so I can not curently investiage further.

We tried with Csound 6.14 and also with Csound 6.12 binary installers. Same problem with both versions. Mac OSX Catalina.

**Comment by vlazzarini** [comment]
Ok, I tried this code (manual example + your samphold)
```
<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>
ksmps = 64
instr 1

 ifftsize init 1024
 ibins init ifftsize/2
 kIn[] init ifftsize
 kcnt init 0
 p3 = filelen("fox.wav")
 asig diskin "fox.wav"
 kIn shiftin asig
 kcnt += ksmps
 if kcnt == ifftsize then
  kFFT[] = rfft(kIn)
  kPows[] = pows(kFFT)
  kMFB[] = log(mfb(kPows,300,8000,32))
  kmfcc[] = dct(kMFB)
  kcnt = 0
  kfb = 0
  while kfb < 32 do
   printf("mfcc[%d] = %.3f \n", kfb+1, kfb, kmfcc[kfb])
   kfb += 1
  od
  imfccscale = 1
  kgate = 1
    kmfcc1          samphold kmfcc[1]*imfccscale, kgate
    kmfcc2          samphold kmfcc[2]*imfccscale, kgate
    kmfcc3          samphold kmfcc[3]*imfccscale, kgate
    kmfcc4          samphold kmfcc[4]*imfccscale, kgate
    kmfcc5          samphold kmfcc[5]*imfccscale, kgate
    kmfcc6          samphold kmfcc[6]*imfccscale, kgate
  
 endif
               
endin
</CsInstruments>
<CsScore>
i1  0 1
</CsScore>
</CsoundSynthesizer>
<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>
ksmps = 64
instr 1

 ifftsize init 1024
 ibins init ifftsize/2
 kIn[] init ifftsize
 kcnt init 0
 p3 = filelen("fox.wav")
 asig diskin "fox.wav"
 kIn shiftin asig
 kcnt += ksmps
 if kcnt == ifftsize then
  kFFT[] = rfft(kIn)
  kPows[] = pows(kFFT)
  kMFB[] = log(mfb(kPows,300,8000,32))
  kmfcc[] = dct(kMFB)
  kcnt = 0
  kfb = 0
  while kfb < 32 do
   printf("mfcc[%d] = %.3f \n", kfb+1, kfb, kmfcc[kfb])
   kfb += 1
  od
  imfccscale = 1
  kgate = 1
    kmfcc1          samphold kmfcc[1]*imfccscale, kgate
    kmfcc2          samphold kmfcc[2]*imfccscale, kgate
    kmfcc3          samphold kmfcc[3]*imfccscale, kgate
    kmfcc4          samphold kmfcc[4]*imfccscale, kgate
    kmfcc5          samphold kmfcc[5]*imfccscale, kgate
    kmfcc6          samphold kmfcc[6]*imfccscale, kgate
  
 endif
               
endin
</CsInstruments>
<CsScore>
i1  0 1
</CsScore>
</CsoundSynthesizer>
```
and it doesn't crash. Maybe you can send me the complete code that does?

**Comment by Oeyvind** [comment]
Ok. Sorry about this. But I need to send you the whole analyzer plugin.
Run the analyzer.csd in Cabbage



fre. 14. feb. 2020 kl. 22:40 skrev vlazzarini <notifications@github.com>:

**Comment by vlazzarini** [comment]
I think I need a simple CSD showing any crashes, that I can run on desktop. I can't debug it on Cabbage.

**Comment by Oeyvind** [comment]
Sorry for the delay. Just tested the complete csd again now and it runs
without problems. We can close this issue.

fre. 3. jul. 2020 kl. 14:35 skrev vlazzarini <notifications@github.com>:
