### ISSUE TITLE
Fractional part of a named instrument?

### ISSUE THREAD

**Issue by laserbat** [csound/csound#1272]
Documentation for [i statement](https://csound.com/docs/manual/i.html) says it is possible to add a fractional part to p1 of an instrument to specify a particular note in a cluster:

>  p1 -- Instrument number, usually a non-negative integer. An optional fractional part can provide an additional tag for specifying ties between particular notes of consecutive clusters. A negative p1 (including tag) can be used to turn off a particular “held” note. In the case of a named instrument it can be negated by having a `-' as the first character of the string. 

Is it possible to do the same with named instruments?

**Comment by jpffitch** [comment]
I think thee is no simple way to add fractional buts t named instruments. 
However if in the orchestra one can use nstrnum to convert a name to 
number and then add the required tag.  Niot always possible and not easy I 
admit.

I shoud be possible to change the sntax of a name to add a tag after say a 
: or a .  This would need careful thought to see that it did not break 
backwad compatiblity or give semantic issues.  I can see problems all 
over here......

**Comment by laserbat** [comment]
That makes sense to me. I think the best option would be something along the lines of

`i "inst":1    0    1   "4A"    -20`

What do you think?

If this is okay, I might make a pull request implementing this tomorrow.

**Comment by jpffitch** [comment]
I as thinking more
i "inst.1" 0 1

**Comment by laserbat** [comment]
This makes sense but creates a problem when it comes to backwards compatibility: if a composition had named instruments with names ending in dot + number, the behavior will be different now.


That's why I'm thinking about an alternative syntax.




---- On Tue, 25 Feb 2020 23:15:28 +0000 notifications@github.com wrote ----


I as thinking more
i "inst.1" 0 1

**Comment by jpffitch** [comment]
A dot is not valid in a instrument name

**Comment by laserbat** [comment]
Ah, I see. Thanks for tht clarification



---- On Tue, 25 Feb 2020 23:24:55 +0000 notifications@github.com wrote ----


A dot is not valid in a instrument name

**Comment by jherzenach** [comment]
Any word on this?  This would be extremely useful for my current project so I don't have to just label everything numbers haha.  My program is dependent on being able to init new instances of instruments with a fractional part

**Comment by jpffitch** [comment]
Sorry not t reply earlier but gitub oes not like my browser

The adding of .12 (for example) to a name `tags` the instance with the fraction.  Seems to work is all the examples I could find
