### ISSUE TITLE
Three soak tests yield infinite loop on missing file

### ISSUE THREAD

**Issue by iskunk** [csound/csound#1285]
In the course of my testing, I found three soak tests that cause Csound to enter an infinite loop when a file used by the test cannot be loaded. Specifically, the tests are
```
csound -d -W -m0 -i /dev/null /path/to/csound/tests/soak/fmmetal.csd -o fmmetal.wav
csound -d -W -m0 -i /dev/null /path/to/csound/tests/soak/fmrhode.csd -o fmrhode.wav
csound -d -W -m0 -i /dev/null /path/to/csound/tests/soak/fmwurlie.csd -o fmwurlie.wav
```
The files used by these are `twopeaks.aiff`, `fwavblnk.aiff`, and `fwavblnk.aiff` respectively. The files are loaded into function tables, so it is really the missing function tables that cause the error.

The bug is easy to reproduce, but I'm not clear enough on what exactly is wrong with the logic to submit a fix with reasonable confidence.

**Comment by jpffitch** [comment]
The problem is in the deactt code somewhere.  It is running OK until in 
csoundPerform it calls csoundDestroy.  Not very familiar with this area 
but I am looking.  May need Victor's expertese.

**Comment by jpffitch** [comment]
Foxed inithub.  It got confused by calls to csound->PerfError which should have been csound->InitError.  Only in these FM instruments. (I hope!)
