### ISSUE TITLE
Various input files missing for soak tests

### ISSUE THREAD

**Issue by iskunk** [csound/csound#1287]
Various soak tests make use of the following files, which are not present in the `csound/tests/soak/` directory. These can largely be copied from the `csound/manual` repo, or be generated from files in same:
```
	128,8-cylinderX
	128,8-gridX
	128,8-torusX
	128-left_rightX
	128-spiral-8,16,128,2,1over2
	128-stringcircular
	128-stringcircularX
	128-stringX
	beats.pvx
	cylinder-128,8
	eee.aiff
	flute.pvx
	mary.pvx
	spiral-8,16,128,2,1over2  (see note below)
	string-128.matrix
```

Note that the `scans-2.csd` test references `spiral-8,16,128,2,1over2`, but this file is named `128-spiral-8,16,128,2,1over2` in the `csound/manual` repo. This appears to be a typo.

**Comment by jpffitch** [comment]
Fix I committed enough of them
