### ISSUE TITLE
image.dll error pop up

### ISSUE THREAD

**Issue by danishang** [csound/csound#1288]
Just downloaded it then when opened "The procedure entry point inflateValidate could not be located in the dynamic link library C:\Program Files\Csound6_x64\plugins64\image.dll" popped up.

Im not good at tecnical stuff since im new to it and ive tried everything but failed

**Comment by rorywalsh** [comment]
It looks like an issue with zlib. Can you try removing that dll from the
plugins64 folder. That should work, although you will not be able to use
that image opcodes.

**Comment by rorywalsh** [comment]
I was rather hoping @stekyne might be able to take a look?

**Comment by stekyne** [comment]
Any chance of a sample CSD? Tried the manual examples but they're complaining about syntax errors.

**Comment by stekyne** [comment]
I got my example working in the end, silly mistake. It runs fine for me both from the latest develop version of the code and the latest installed Windows version. 

Does that image.dll actually exist at the location given?

**Comment by rorywalsh** [comment]
It should be in "C:\Program Files\Csound6_x64\plugins64"?

**Comment by andypea** [comment]
I ran into the same issue and resolved it by deleting the copy of "zlib64.dll" that was located in "C:\Program Files\Intel\WiFi\bin".

![image](https://user-images.githubusercontent.com/764764/78842946-85927c00-7a55-11ea-81ac-668f70dd5a47.png)
