### ISSUE TITLE
Popping when connecting new node to `CsoundObj.node`

### ISSUE THREAD

**Issue by rorywalsh** [csound/csound#1289]
I've been trying to create new nodes on the fly and connect them to CsoundObj.node for playback but I keep getting pops. When I do the same thing with a standard AudioContext it works fine. 

Here is a simple example here that illustrates the problem. 

[CsoundWASM](https://repl.it/@RoryWalsh1/meSpeek)

Just hit the play button and follow the on-screen instructions.

**Comment by kunstmusik** [comment]
Not quite apples to apples, as the Csound test is connecting to the Csound node while the other test is connecting directly to audio context output. It might be that this only happens when connecting to an AudioWorklet or ScriptProcessorNode rather than and issue of AudioContext

**Comment by hlolli** [comment]
I had this once, which I solved it by nulling the sound out buffer before connecting it to csound. But I don't have time atm to look into your exmple.

**Comment by rorywalsh** [comment]
Hi @kunstmusik, in [this](https://repl.it/@RoryWalsh1/meSpeek-Worklet) example I'm connecting the audioSourceBuffer node to an AudioWorkletProcessor*. This seems to model what happens with CsoundWASM a little closer. Still no pops.   

* at least that how I understand it. WebAudio is still very new to me.

**Comment by hlolli** [comment]
```
    var buffer = new ArrayBuffer(stream.length);
    new Uint8Array(buffer).set(stream); 
```

this part looks suspicious. You probably shouldn't create refernecelss Uint8Array buffer and I'd recommend initializing the buffer with 0 on every index.

**Comment by rorywalsh** [comment]
I've updated that code. Does this look better:

```
var buffer = new ArrayBuffer(stream.length);
    for (var i = 0 ; i < buffer.length; i++)
        buffer[i] = 0;

    var myArray = new Uint8Array(buffer);
    myArray.set(stream);
```

But I'm still getting pops 😞

**Comment by kunstmusik** [comment]
@rorywalsh Is this still an issue? If so I'll schedule for 7.0.0, otherwise will close.

**Comment by rorywalsh** [comment]
@kunstmusik I gave up on it in the end. But this was in the older wasm version right? I'm happy for you to close this as so much of that older version has been updated.

**Comment by kunstmusik** [comment]
@rorywalsh Thanks for the follow-up. I'll close this ticket and feel free to file a new ticket if you come across it again with the newer Csound Web.
