### ISSUE TITLE
setksmps not working correctly in instr

### ISSUE THREAD

**Issue by francesco66** [csound/csound#1291]
seems that setksmps in instr block is not working. I get segfault.

**Comment by francesco66** [comment]
I'm on ubuntu 16.04 with Csound version 6.14 (double samples) Mar  4 2020.
minimal test:

<CsoundSynthesizer>
<CsOptions>
-odac
</CsOptions>
<CsInstruments>
sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

instr 1

setksmps 2

aout poscil 0.5, 100
outs aout, aout
endin

</CsInstruments>
<CsScore>
i 1 0 1
</CsScore>
</CsoundSynthesizer>

**Comment by jpffitch** [comment]
Might be fixed now; runs your test OK I think

**Comment by jpffitch** [comment]
Fixed the distortion.
