### ISSUE TITLE
Qtsound-Csound error on macOS Lion

### ISSUE THREAD

**Issue by gianare** [csound/csound#1298]
Hi all guys, i hope someone can help me 'cause i need this help for university study. I
have already tried to check something on internet but i can't find nothing can help me. The problem is this:
i begin with installation of Csound from their site https://csound.com/download.html
after that, i have to installate 2 component: Csound.pkg and QTsound.dmg; the Csound.pkg has no problem to install it but QT has some problems, so i have downloaded another version of QTSound that can play on my Mac. The problem is that i have a specific error in the output console that put in red the writing (i will attach the screenshot here).
Now, if i render the audio, i can listen the exported file from my score, a cycle or fm or whatever it is, but in my QTsound console i can't see the result and i can't run and/or listen nothing from csound until i render the score. Thanks for your attention, and for help (i hope)
#Csound #macOS #QTsound #bug #error #console #help wanted

![Screenshot_2020-03-12-19-26-24-406](https://user-images.githubusercontent.com/30700192/76630073-b0191400-653f-11ea-8746-0f839db353d3.jpg)

**Comment by jpffitch** [comment]
Looking at your output in the screenshot I see no errors.  I do not 
perceive red but all the output is as I would expect.  The problem you 
report looks as if it related to csoundQt which is not the subject of this 
issues list.  You might get better help from either the csound mailing 
list or the csoundQt list.

**Comment by gianare** [comment]
@jpffitch  okok, sorry but i'm new Csound users. So the problem could it be that QTsound don't respond as it should when i want to run code from it. Do you think that i can solve this problem donwloading another version of QT ? And, can i play my Csound score from command line (with the same code) for text only Csound?

**Comment by jpffitch** [comment]
I knownothig aout csoundQt expcept its existence.  Never us it.

Not sre I uderstand your probe but if you want ti hear the sound as it irs 
created att te option "-o dac" to the command line.  Without that or any 
other -io option it will create a file test.wav.

If that is not wha you are asjin either ask on the mailing list or emal be 
directly and I will try tisort out commandline problems.

==John ff aka jpff [at] codemist.co.uk

**Comment by joachimheintz** [comment]
i have replied on the csoundqt tracker; this can be closed.
