### ISSUE TITLE
f-sig arrays not working

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#1300]
using f-sig arrays in the code does not return an error but always outputs zero when re-synthesized by pvsynth:

instr 1
 fArr[] init 1
 aSig[] = diskin("fox.wav")
 fArr[0] = pvsanal(aSig[0], 1024, 256, 1024, 1)
 aMix pvsynth fArr[0]
 out aMix, aMix
endin
schedule(1,0,3)

**Comment by jpffitch** [comment]
Agreed there is a problem with f arrays.  Will look more closely.

**Comment by jpffitch** [comment]
As fa as  can tell there is no support for f-arrays.  it does not cras as 
it asse anytng not a string is either a scalar or a array.  What it 
aurally does is a mystery to me at present.

May have to wait for cs7?

**Comment by joachimheintz** [comment]
yes, no problem, then i will not mention it in the description of arrays.
thanks for looking in it; this was not clear to me.

**Comment by vlazzarini** [comment]
I think we need to first define an fsig[] init overload or perhaps overload pvsinit? Not sure what is the best thing.
Csound 7 for sure. For the moment, I have made it so that init will fail on anything that is not i,k,a or S. 
That'll sort the bug.
