### ISSUE TITLE
reshapearray 2D>1D not working

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#1302]
reshapearray works as expected from 1D to 2D, but not vice versa:

iArr[] init 3, 4
iArr fillarray 1,2,3,4,5,6,7,8,9,10,11,12
printarray iArr, "%d", "2D array:"
reshapearray iArr, 12
printarray iArr, "%d", "1D array:"

this only prints the 2D array and nothing else.  also the second manual example is not working.

--Csound version 6.14 (double samples) Mar 12 2020
[commit: f544db802d738bb79ccedc2e0c8b768b0c02cd1c]

**Comment by joachimheintz** [comment]
first line in my code should probably read:
iArr[][] init 3, 4

but it makes no difference for me.

**Comment by jpffitch** [comment]
This is Eduardo's code; should be referred to him

**Comment by joachimheintz** [comment]
yes but i cannot do it, as far as i see

**Comment by jpffitch** [comment]
as it stads if numcols is omitted it deauts to 0 so te test tat te sizes 
matcgh wil fail.  try respapearray iArr, 12, 1

**Comment by joachimheintz** [comment]
this seems to work:
iArr[] init 3, 4
iArr fillarray 1,2,3,4,5,6,7,8,9,10,11,12
printarray iArr, "%d", "2D array:"
reshapearray iArr, 1, 12
printarray iArr, "%d", "1D array:"

but the manual states:
isize0 - The size of the first dimension
isize1 - The size of the second dimension (0 for 1D arrays). Defaults to 0 

so when i want to transform 2D in 1D, my input should be
reshapearray iArr, 12[, 0]

not?

**Comment by jpffitch** [comment]
The code for reshapearray was multiple problems and needsa rethink.  No 
error messae o size mismatch; troble when numrows is zero, wrong treatmnt 
to omitted nucols......

**Comment by jpffitch** [comment]
No; the code is wrong in at least 3 aspects.  \trying to finda contact for 
the autor

**Comment by gesellkammer** [comment]
This is fixed in the PR (unrelated subject but...): https://github.com/csound/csound/pull/1290

**Comment by jpffitch** [comment]
Fixed in ithub with minimal testing

**Comment by joachimheintz** [comment]
yes works for me now.  this is an example code, perhaps for the manual page:

instr 1
iArr[][] init 3, 4
iArr fillarray 1,2,3,4,5,6,7,8,9,10,11,12
printarray iArr, "%d", "2D array:"
reshapearray iArr, 12
printarray iArr, "%d", "1D array:"
endin
schedule(1,0,0)

printout:

2D array:
    0: 1 2 3 4
    1: 5 6 7 8
    2: 9 10 11 12
1D array:
  1 2 3 4 5 6 7 8 9 10 11 12

**Comment by jpffitch** [comment]
Apoogies; coe exists ur not yet committed
