### ISSUE TITLE
setcol mismatch

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#1303]
code:
iArr[][] init 3, 4
printarray iArr, "%d", "2D array empty:"
iCol[] fillarray -1, -2, -3
iArr setcol iCol, 3
printarray iArr, "%d", "2D array with fourth column:"

result:
2D array empty:
   0: 0 0 0 0 
   1: 0 0 0 0 
   2: 0 0 0 0 
2D array with fourth column:
   0: 0 0 0 -1 
   1: 0 0 -2 0 
   2: 0 -3 0 0

**Comment by jpffitch** [comment]
Fixed
