### ISSUE TITLE
note triggering with opcodes does not work anymore

### ISSUE THREAD

**Issue by docb** [csound/csound#1306]
commit: 025cc5191a61ee91bacbabca547a808e1fa0140e unfortunately i have cloned today ....
may be it is not ready implemented but i want to give here the hint that now my triggering system does not work any more:

opcode notetrigger2,0,iiiii
  insno,ip4,ip5,ip6,ip7 xin
  print insno,ip4,ip5,ip6,ip7
  if ip4 == 1 then
    event "i",insno+(ip5 * 0.001)+ip7 * 0.0001,0,-1,ip5,ip6,ip7
  else
    turnoff2	insno+(ip5 * 0.001)+ip7 * 0.0001,4,1
  endif
endop

it is called form a trigger instrument which is either activated via osc or via the C API (i need this indirection for some reasons)

instr fm2trigger
   insno nstrnum "fm2"
   notetrigger2 insno,p4,p5,p6,p7
   turnoff
endin

instr fm2
....
endin

the result is that only one note on is triggered after startup and then nothing happens anymore.

when switching back to commit fd3f3cd314f1390b731096c32091dbe1149944b3 Mar 24 all works perfect again.

**Comment by kunstmusik** [comment]
Looks like the fix I did for turnoff within UDOs introduced a bug. I can reproduce using a similar bit of code here, will look at it now.

**Comment by kunstmusik** [comment]
@docb I think I fixed the bug. If you could verify that would be appreciated.

**Comment by rorywalsh** [comment]
Thanks Steven. This was not caught in my tests :+1:

**Comment by docb** [comment]
@kunstmusik it works now thx.

**Comment by kunstmusik** [comment]
Fantastic, thanks for verifying!
