### ISSUE TITLE
Issue with strings and ternary comparisons?

### ISSUE THREAD

**Issue by tgrey1** [csound/csound#1307]
This code used to work on csound 6.13 official release OSX, but it no longer works with 6.14 official OSX:
```
kButton chnget "button"

if (changed(kButton)==1) then
  chnset strcpyk((kButton==1) ? "visible(1)" : "visible(0)"), "widget-ctl"
endif
```

I also tried this, but it didn't work either:

`chnset (kButton==1) ? "visible(1)" : "visible(0)", "widget-ctl"
`

I'm not sure, but this feels like it might be a regression.  Ironically I had reported a very similar issue to the mail list *years* ago.  It was worked on with discussion on the list by jpff, but I'm not sure if there was a correlating git issue to reference.

**Comment by jpffitch** [comment]
In what way "does not work"?  It would help to hve a complete example.

Tis area of the languagewas totally rewritten as the 6.13c version was 
seriously wrong.

**Comment by jpffitch** [comment]
I think this is beause there is no support for strings in ?: code.

**Comment by jpffitch** [comment]
Actually there is no support for expressions as strings.  It needs a temporary variable  for the result of the test, and expressions are numeric.  Result is an attempt to assign a string to a k-rate variable which is illegal.

It may be possible to patch this case but as soon as one of the string opcodes is used in either true or false branch that will fail.  It needs a lot of work to allow the type detection to allow i, k or S results.  I will look at the code but it is delicate.

**Comment by kunstmusik** [comment]
Note: this should leverage the type system so that it works for any types
and not be a patch for specific types.  Also, @tgrey1 mentioned this worked
in earlier versions. It would be interesting to understand how that was
possible.

**Comment by jpffitch** [comment]
Previous "version" did not use a temporary variable so the string was used in place.

**Comment by jpffitch** [comment]
I have just committed what may be a fix.  My previous analysis was pessimistic.

**Comment by tgrey1** [comment]
Sorry I forgot to include the error message, this was discussed a little in slack before I submitted, and it had beed provided there.  In case it matters, this is for OSX 10.13.6, with the official release installations of both versions of csound.

Unfortunately I can't test the changes, this mac has a broken homebrew system and can't setup the build environment needed.

Here is a distilled example cabbage instrument.  It works properly in 6.13, the button makes the image (a white box) appear/disappear when pressed.

```
<Cabbage>
form caption("String Test") size(400, 300), colour(58, 110, 182), pluginid("test")
button bounds(50,50,50,20), channel("button")
image bounds(50,100,50,50), identchannel("widget-ctl")

</Cabbage>
<CsoundSynthesizer>
<CsOptions>
-n -d -+rtmidi=NULL -M0 -m0d 
</CsOptions>
<CsInstruments>
ksmps = 32
nchnls = 2
0dbfs = 1

instr 1
    kButton chnget "button"

    if (changed(kButton)==1) then
      chnset strcpyk((kButton==1) ? "visible(1)" : "visible(0)"), "widget-ctl"
    endif
endin

</CsInstruments>
<CsScore>
i1 0 z
</CsScore>
</CsoundSynthesizer>

```

In 6.14 for me it errors with:

```
error:  Unable to find opcode entry for '=' with matching argument types:
Found: k = S
       #k3 = "visible(0)" ...
Line: 0
Parsing failed due to syntax errors
Stopping on parser failure
cannot compile orchestra

[Finished in 10.9s]
```

**Comment by rorywalsh** [comment]
A vanilla .csd is always better for demonstrating issues, as many devs
don't use a frontend.

**Comment by jpffitch** [comment]
So we have to wait for someone else to test.  I have no Cabage, csoundQT 
or non-CLI system.

I can parse your code so I suspect it is fixed.

**Comment by kunstmusik** [comment]
I did a quick test live coding with the following code:

`prints((0 < 1) ? "a" : "b")`

and I got the letter b printed.  Seems improved but something is still off.

**Comment by jpffitch** [comment]
Does it work with numbers?

⁣Get TypeApp for Android ​

**Comment by kunstmusik** [comment]
Yes, it appears to work with

`print (1 <0) ? 0 : 1`

to print 1

**Comment by kunstmusik** [comment]
No. It prints correctly for numbers but incorrectly for strings.

```csound 
<CsoundSynthesizer>
<CsOptions>
</CsOptions>
; ==============================================
<CsInstruments>

sr	=	48000
ksmps	=	1
nchnls	=	2
0dbfs	=	1

instr 1	
  print((0 < 1) ? 0 : 1)
  print((0 > 1) ? 0 : 1)
  prints((0 < 1) ? "a" : "b") 
  prints((0 > 1) ? "a" : "b")
  turnoff
endin

</CsInstruments>
; ==============================================
<CsScore>
i1 0 0.01


</CsScore>
</CsoundSynthesizer>

```

**Comment by tgrey1** [comment]
Thanks for looking into this guys.

I have no idea if it would help shed any light on things, but I dug a little bit into my inbox and found that this had previously come up in October 2015 in the thread titled "bug: can't use ternary operator with strings?"

**Comment by jpffitch** [comment]
No help i am afraid. The code was totally rewriten recently

⁣Sent from TypeApp ​

**Comment by tgrey1** [comment]
Reopening, sorry for the delay... I can't build from source, so I wasn't able to test until Rory helped get me a build.

While it no longer segfaults, it doesn't actually treat strings at krate:

This line is functionally static, not activating a change even when kBypass does:
      chnset strcpyk((kBypass==1) ? "visible(1)" : "visible(0)"), "bypass-tint"

Meanwhile this works as expected:
      if(kBypass==1) then
        chnset "visible(1)", "bypass-tint"
      else
        chnset "visible(0)", "bypass-tint"
      endif

**Comment by jpffitch** [comment]
oh dear!

I will look again

**Comment by jpffitch** [comment]
I have a (somewhat ugly) fix,  ACtually was related to assignment for 
strings being i-rate only.

**Comment by jpffitch** [comment]
Closing again
