### ISSUE TITLE
mp3out computes pointers wrongly (segment violation)

### ISSUE THREAD

**Issue by PeteCA** [csound/csound#1309]
I found that trying to use the 'mp3out' opcode immediately crashes my system.
On investigation I found the following bit of code in mp3out_init:

`    p->mp3buffer = p->auxch.auxp;
    p->leftpcm = p->auxch.auxp+p->mp3buffer_size;
    p->rightpcm = p->leftpcm + sizeof(MYFLT)*nsmps;
`
But both leftpcm and rightpcm are declared as pointers to MYFLT, so the third line above has an increment of MYFLTs rather than  bytes.  The result is slightly out of range!

Either just use 'nsmps' as increment, or cast the pointer.

**Comment by jpffitch** [comment]
Thank yu; I have applied your change

**Comment by PeteCA** [comment]
Thanks, John.  I realized afterward that it might have been easier just to submit a PR, but I guess it was trivial to patch.
