### ISSUE TITLE
Please make LIBRARY_INSTALL_DIR configurable

### ISSUE THREAD

**Issue by bigon** [csound/csound#1310]
Hello,

Could it be possible to make LIBRARY_INSTALL_DIR configurable at build time? ATM, it's either (/usr)lib or lib64

This is needed so the libraries (and the plugins) can be installed in a "multiarch" path

See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=956109

**Comment by gogins** [comment]
Possibly, it would suffice to set your library directory on the CMake
command line:

cmake -DLIBRARY_INSTALL_DIR=mypath

Did you try this?

Regards,
Mike

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by bigon** [comment]
Hello,

No this is not working.

I'm passing `-DLIBRARY_INSTALL_DIR=/usr/lib/x86_64-linux-gnu` and this results in the build system telling me: `-- LIBRARY INSTALL DIR: lib`

**Comment by jpffitch** [comment]
I note that in the make_install.cmake file it says

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
   set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()

s I woud guess setting CMAKE_INSTALL_PREFIX  might be useful.

But I never use install so am ignorant.

**Comment by kunstmusik** [comment]
@bigon I modified the CMakeLIsts.txt file to permit setting LIBRARY_INSTALL_DIR. You should be able to do some thing like

```
cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DLIBRARY_INSTALL_DIR=lib/x86_64-linux-gnu
```

Does this work for you?

**Comment by bigon** [comment]
Setting `-DLIBRARY_INSTALL_DIR=lib/x86_64-linux-gnu` (without the prefix) is apparently working

**Comment by kunstmusik** [comment]
Thanks for confirming, will close this out now.
