### ISSUE TITLE
wrong durations with --sample-accurate

### ISSUE THREAD

**Issue by andreaagostini** [csound/csound#1317]
The duration of notes appears to be wrong with --sample-accurate, if the start and end time are aligned with the k cycle.

See provided score and screenshots.
![Screen Shot 2020-04-15 at 17 51 11](https://user-images.githubusercontent.com/33197553/79359675-2cd64e00-7f43-11ea-8b83-4035d866ee82.png)
![Screen Shot 2020-04-15 at 17 50 54](https://user-images.githubusercontent.com/33197553/79359677-2d6ee480-7f43-11ea-9c13-fcef2731f021.png)

```
<CsoundSynthesizer>
<CsOptions>
--sample-accurate
</CsOptions>
<CsInstruments>
sr = 44100
ksmps = 4410
nchnls = 1
0dbfs = 1
instr 1
		a1 = 0.5
		out a1
endin
</CsInstruments>
<CsScore>
i1 0 5
i1 10 5
</CsScore>
</CsoundSynthesizer>
```

**Comment by jpffitch** [comment]
kWhat ersion are you using?  Some code in tis area was recently rewritten 
so I would like to know which to debug!

**Comment by andreaagostini** [comment]
I'm using CsoundQt Version 0.9.5.1 Using Csound version:6121 Precision:double (64-bit) under MacOS 10.13.6

**Comment by jpffitch** [comment]
Thanks; I can reproduce it am looking into it.

**Comment by jpffitch** [comment]
A rather ugly fix applied to sources.  Apologies for the error
