### ISSUE TITLE
libcurl mess 

### ISSUE THREAD

**Issue by giuliomoro** [csound/csound#1322]
It seems that Ubuntu18.04 and Debian Buster have uselessly broken `libcurl4`, so that running a csound package compiled for `stretch` wouldn't work on `buster` (I get:
```
belacsound: /usr/lib/arm-linux-gnueabihf/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /usr/lib/libcsound.so.6.0)
```
and so I should rebuild `csound` differently for each version of the Bela image.
)

Could you please point out what is libcurl used for? I have seen that there is a way for excluding it at build time, but I wanted to know what I'd miss out on. If that's only [strfromurl](https://csound.com/docs/manual//strfromurl.html), then - given how the board is normally not connected to the internet - I'd be in favour of dropping CURL support from the Bela builds so that I can run the same build across the board(s).

**Comment by jpffitch** [comment]
libcurl is used/may be used in #include to read from a URL.  It is lso 
used for the opcode strfromurl

It is certainly ignorable and is controlled by a compiler macro

**Comment by giuliomoro** [comment]
PS: if anyone is interested in fixing this for Buster, I copied the following libraries from `Stretch` into `~/` on Buster:

`libssl.so.1.0.2`, `libcrypto.so.1.0.2`, `libcurl.so.4.4.0`

then  I can run `LD_PRELOAD="$HOME/libcrypto.so.1.0.2 $HOME/libssl.so.1.0.2 $HOME/libcurl.so.4.4.0" csound` for the win.

**Comment by jpffitch** [comment]
I do not understand this.  I run Debian buster on one of my machines and it builds the curl code in csound as expected

**Comment by giuliomoro** [comment]
the issue is only if trying to run a on Buster a binary that was built for Stretch.
