### ISSUE TITLE
bug in pvstrace

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#1323]
there is a bug in PVTrace2 in Opcodes/pvsops.cpp:
1. input args 4 and 5 (line 106-107) are not documented in the manual:
    int start = (int) inargs[3];
    int end = (int) inargs[4];
2. i think (not sure) they were supposed to look only for the N loudest bins between start and end as option. but why is the default pp (perhaps oo is meant?)
3. currently always the whole f-sig is returned, so the kn input is igrnored.  example:
instr 1
 aSig diskin "fox.wav"
 fSig pvsanal aSig, 1024, 256, 1024, 1
 fTrace, kBins[] pvstrace fSig, 1
 aTrace pvsynth fTrace
 out aTrace, aTrace
endin
schedule(1,0,3)
should only return the loudest bin, but returns the full f-sig.
(it works with fTrace, kBins[] pvstrace fSig, 1, 0, 0, 0)

**Comment by joachimheintz** [comment]
just to note that i had a closer look.  the simple solution, as far as i see, would be to revert the changes in commit 41a37c1f82c6bd1abdd8f838f958311c609880d5, or (more simple but leaving odd code) to change "fkopp" in line 73 to "fkooo".

both changes would make the code compliant with the manual description.

**Comment by vlazzarini** [comment]
thanks. fixed and adjusted the man page.
