### ISSUE TITLE
Windows 6.14 doesn't recognize PortMidi as default or via -+rtmidi

### ISSUE THREAD

**Issue by arthunkins** [csound/csound#1324]
6.14, with -M0 flag, gives console output:
csound command: Segmentation violation
then closes. It gives same response to -+rtmidi=PortMidi.
-+rtmidid=mme or winmm work fine.
Windows 6.13 experiences no such problems.
Demo file follows.

<CsoundSynthesizer>
<CsOptions>
-odac -M0
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
  
instr 1

kamp ctrl7 1, 20, 0, 8000
ain lfo kamp, 440
outs ain, ain

endin

</CsInstruments>
<CsScore>

i 1 0 20

e

</CsScore>
</CsoundSynthesizer>

**Comment by stekyne** [comment]
Hmm I dont get the same error. Have you tried another machine?

**Comment by arthunkins** [comment]
My machines are all Windows 10, and I get the same results ( = Windows Csound4.13 works with MIDI PortMIDI; 4.14 doesn't) on a second machine.

I've also done different disposition of environment variables: either with or without them (I've paid particular attention to these). I've also tried different MIDI devices (all of which were pretested to communicate with the computers). Note: I've run everything from the command line.

The only other thing I can say is that I've sometimes gotten these (2) other failure messages:

        error: -+rtmidi='portmidi': unknown module
 *** error opening MIDI in device: -1 (Unknown MIDI error)

0: MC-8 (portmidi)
PortMIDI: Activated input device 0: 'MC-8' (MMSystem)
csound command: Segmentation violation
C:\Csound6_x64\bin>

**Comment by stekyne** [comment]
It must be that portmidi can't be found I guess? Are you sure your path is correct and you don't have multiple portmidis installed by any chance? Make sure the csound bin dir is at the start of the path and see if that makes a difference.

**Comment by rorywalsh** [comment]
I just tried the latest build on Windows and I can't get any realtime audio
to work? I'm just trying some of the examples from the manual, and I get:

unknown rtaudio module: 'PortAudio', using dummy module
rtaudio: dummy module enabled

I will take a proper look tomorrow.
