### ISSUE TITLE
FLTK broken on Mac

### ISSUE THREAD

**Issue by csounder** [csound/csound#1325]
On the Mac, running from CsoundQt or from the Terminal, any instrument that uses the FLTK opcodes puts up a panel that is blank - no sliders, knobs, buttons, text or check boxes appear.

**Comment by jpffitch** [comment]
Indeed FLTK is suspect on Mac even without csound -- Something to do with threads I think.

**Comment by vlazzarini** [comment]
FLTK is no good on the Mac and there is no fix. This is a problem with the FLTK library. Basically, FLTK cannot run windows on separate threads on the Mac, they needs to be run on the main thread, therefore it interrupts audio processing. This is a well-know restriction. Maybe we should note it in the manual.
