### ISSUE TITLE
Wrong line number reported for "Variable ... used before defined"

### ISSUE THREAD

**Issue by gesellkammer** [csound/csound#1328]
The error message is always off by 1. In the example, the error is in line 5, but the error message says line 6

```csound
<CsoundSynthesizer>
<CsInstruments>

instr 1
	print ifoo
endin

</CsInstruments>
<CsScore>
i1 0 1 
</CsScore>
</CsoundSynthesizer>

**Comment by jpffitch** [comment]
The problem is that it is not until the next line that it can identify that there is an error.

⁣Sent from TypeApp ​

**Comment by jpffitch** [comment]
I subtracted 1 from the line number for this message.  I suspect there are other similar off-by-one error messages. They could be simlary fixed.
