### ISSUE TITLE
wrap in table opcode not working

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#1329]
when using the wrap=1 option in table, the output is always 0 rather than reading the table again from start.

instr 1
 iTab ftgen 0, 0, 6, -2, 1, 2, 3, 4, 5, 6
 kIndx = 0
 while kIndx < 10 do
  kVal table kIndx, iTab, 0, 0, 1
  printk 0, kVal
  kIndx += 1
 od
 turnoff
endin
schedule(1,0,.1)

 i   1 time     0.00000:     1.00000
 i   1 time     0.00000:     2.00000
 i   1 time     0.00000:     3.00000
 i   1 time     0.00000:     4.00000
 i   1 time     0.00000:     5.00000
 i   1 time     0.00000:     6.00000
 i   1 time     0.00000:     0.00000
 i   1 time     0.00000:     0.00000
 i   1 time     0.00000:     0.00000
 i   1 time     0.00000:     0.00000

**Comment by jpffitch** [comment]
Thecodeassums the length is a power of 2 if wrap is set.  Fix iseasy as 
long as it does not break something else

**Comment by vlazzarini** [comment]
probably a left over from when we made the code not dependent on power-two sizes. If it uses the  floating-point addressing, then it should be ok. Funny that it took seven years for this bug to surface.

**Comment by jpffitch** [comment]
Fixed in github
