### ISSUE TITLE
copy&paste text in editor is failing after play sound

### ISSUE THREAD

**Issue by Parlazo** [csound/csound#1339]
the copy and paste function is failing after i play a sound in the qt editor by csound 6.14 which is have downloaded just yesterday on windows 7
it did work well but after some howers i did try this FLTK widget thing and since then i have this bug
restart does not solve the problem and cleaning the csd file from FLTK stuff by commenting it all out does not help
but before i did try this it did work and since i did try it copy and paste does not work even if i deactivate FLTK by commenting and restart qt editor
in the widget panel i have just an osciloscope and i would like to keep at least this
the FLTK code stuff is actually not so interesting to me as i am new to csound
i saw postings around the net about this problem date to 2009 and others
a solution should be to deactivate widgets.dll and virtual.dll in the csound plugin folder
but as i said i would like to keep the osciloskope in the widgets panel and be able to use copy and paste in the editor at the same time
some where i saw a posting and they said its a solved problem
they said csound and this FLTK stuff is using the clipboard at the same time and this is not possible in windows and they had fixed it in a early version of csound
but now i have the exactly same error in 2020
please if possible refix this problem
thank you any way

**Comment by jpffitch** [comment]
Sounds like a csoudQT issue rather than csound.

**Comment by Parlazo** [comment]
ok... your probably right... i will search an check there... i did not notice the difference ... sorry
