### ISSUE TITLE
src_conv cannot write outfile

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#1343]
`src_conv -r48000 -o fox48k.wav fox.wav` creates an empty file for me and outputs the message:
"cannot open fox48k.wav."
(debian10, recent csound)

**Comment by jpffitch** [comment]
Works for me.Wht is your ciurret directory and what are its permissions?

**Comment by joachimheintz** [comment]
strange.  it is on my Desktop dir, so i definitely have write permissions.
i tried now in another dir, but always the same.

**Comment by fggp** [comment]
Same problem here (ubuntu 18.04.4, csound just built from sources). The
error message comes from line 412 in new_srconv.c

Regards

François

Le sam. 27 juin 2020 à 09:57, joachimheintz <notifications@github.com> a
écrit :

**Comment by jpffitch** [comment]
Oh dear!  It still works for me.  However I have added some debugging code to the sources so if you could rebuild from sources and try again it might show something

**Comment by joachimheintz** [comment]
the output is now:
src_conv -r48000 -o fox2.wav fox.wav
filetyp=0 outformat=2
cannot open fox2.wav (Error : major format is 0.).

**Comment by jpffitch** [comment]
That tells us a lot.  Not sure why your versio differs from mine but o to 
the nexr search.

I get

xenakis:~/csound6> ./src_conv -r48000 -o fox48k.wav fox.wav
filetyp=10000 outformat=2
wrote 132320 frames converting sr 44100.00 to 48000.00

**Comment by jpffitch** [comment]
OK I understand.  I hve a .csound6.rc fie that specifies -W as a defaut. 
If you do not set -W, -A -J or -h it does not know tat fomat you want.

Tre is no attemp to guess from te input format.

**Comment by joachimheintz** [comment]
ah yes, that does the trick.
so the solution is to say in the manual that specifying the format is 
mandatory?
or can we set -W as default?

**Comment by jpffitch** [comment]
I set wave as default

⁣Get TypeApp for Android ​

**Comment by joachimheintz** [comment]
perfect; this works now for me, too.
i get two lines of printed output:

filetyp=10000 outformat=2
wrote 132320 frames converting sr 44100.00 to 48000.00

i'd suggest to keep only the second line.

i will send a pull request to update the manual page (including that 
srconv is marked as deprecated).

**Comment by jpffitch** [comment]
Yes that istracing i forgot to remove.
