### ISSUE TITLE
Implement LUFS opcode

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#1347]
As mentioned on the Csound list, an opcode for measuring LUFS (momentery, short-term, and integrated) would be great in Csound.  Some notes:

* Spec in https://www.itu.int/dms_pubrec/itu-r/rec/bs/R-REC-BS.1770-2-201103-S!!PDF-E.pdf
* Fons' ebumeter for reference (https://kokkinizita.linuxaudio.org/linuxaudio/ebumeter-doc/quickguide.html)

**Comment by gleb812** [comment]
ITU-R BS.1170-2 standardizes mono, stereo or 5.1 format. It doesn't deal with 8 channel system typical for computer music. Should we go for up two channels only so far?

**Comment by kunstmusik** [comment]
I think up to two channels would be great to start and ignoring 5.1 is fine.  If someone really wants it we can revisit.  

Looking through all of this I forgot that getting dB True Peak would be useful too as an opcode.  Perhaps something we can look at after this.

**Comment by gleb812** [comment]
Just finished the core part

**Comment by gleb812** [comment]
Completed for both mono and stereo versions. But I need to make some EBU standard compliance tests to make sure it works correct
