### ISSUE TITLE
partials / part2txt bugs

### ISSUE THREAD

**Issue by awelex** [csound/csound#1348]
1. `part2txt` or `partials` occasionally emits the same track (including same track ID) multiple times for a given time point. Consider the following .csd:

```
<CsoundSynthesizer>
<CsOptions>
-n -d
</CsOptions>
<CsInstruments>

sr = 48000
kr = 48000
nchnls = 1
0dbfs = 1
	
instr 1
	kfreq = 500 + rand(200)
	ain buzz .5, kfreq, 10, 1
	ffr, fphs pvsifd ain, 4096, 64, 0
	ftrks partials ffr, fphs, 0.3, 10, 0.05, 50
	part2txt "partials.txt", ftrks
endin


</CsInstruments>
<CsScore>
f1 0 65536 10 1

i1 0 3

</CsScore>
</CsoundSynthesizer>
```
The resulting file `partials.txt` will contain many time points with repeated tracks (with the repeated tracks always at the end).

2. Low values of `imaxtracks` create large .txt files with garbage values in them. In the above .csd, change the `partials` line to:
`ftrks partials ffr, fphs, 0.3, 10, 0.05, 30`
Lower values of `imaxtracks` will create successively bigger files. The threshold from sane to pathological value of `imaxtracks` seems to be related to some extent to the sound being analyzed.

3. `part2txt` opcode is not documented.

**Comment by vlazzarini** [comment]
Fixed in git.

**Comment by vlazzarini** [comment]
it does have an example 

https://github.com/csound/manual/blob/master/examples/part2txt.csd

and manual entry 

https://github.com/csound/manual/blob/master/opcodes/part2txt.xml

in git
