### ISSUE TITLE
MIDI backend for Bela

### ISSUE THREAD

**Issue by giuliomoro** [csound/csound#1350]
Hi there,
@csounder has [pointed out to me](https://github.com/BelaPlatform/Bela/issues/636) that Bela's way of handling Midi on Csound is limited. The original developers make use of Bela's `Midi` class, which implements a Xenomai-safe threaded approach, where one non-RT thread is reading MIDI data from an input interface, and passing it on to the audio thread via a Xenomai pipe. Similarly, the audio thread can pass MIDI out data via a Xenomai pipe to another thread which then writes it to the device. Now, this is a very efficient and RT-safe way of dealing with that, but it's also very Bela-specific, which adds to the development and maintenance burden.

Before I go into fixing that code to support multiple devices, I'd like to see whether there is an easy way to use of the existing MIDI implementation (e.g.: ALSA MIDI or Portmidi). Could anyone please
a) confirm whether which (if any) of the existing MIDI implementations has lock-free queues between the audio thread and a separated MIDI thread
b) in light of that, point me in the right direction to how simplify the [BelaCsound.cpp](https://github.com/csound/csound/blob/develop/Bela/BelaCsound.cpp) file to use one of the existing MIDI implementations
?
Thanks

**Comment by vlazzarini** [comment]
Hi Giulio,

I think both would work, but portmidi has a more complete implementation, allowing multiple port access. 

The way to enable this is to comment out the code that sets the MIDI callbacks in the Bela frontend code, and include portmidi in your build. It has one dependency, the portmidi library.

Once this is built and available in the plugins directory, then Csound will just use it by default.

**Comment by giuliomoro** [comment]
@vlazzarini it would seem that the Midi callback is being called from the audio thread, is that right? Any workaround to avoid I/O in the audio thread?

**Comment by vlazzarini** [comment]
For the portmidi etc backends we would need to rewrite it in an asynchronous way. 

At the moment, the callback just invokes the relevant API function to get any MIDI input data that is waiting, and passes that out.
It would be possible to have a thread that fills a circular buffer that is then read by the callback.

I wonder if it is worth it? I thought using the Bela midi functions saved us the trouble of doing this.

**Comment by giuliomoro** [comment]
> I wonder if it is worth it? I

Probably not. I was under the impression that your answer above meant that they would be real-time safe, but I clearly misunderstood that.

> I thought using the Bela midi functions saved us the trouble of doing this.

They do. I will look into adding multiple ports support  to that.
