### ISSUE TITLE
opcodedir and cmake install prefix.

### ISSUE THREAD

**Issue by vlazzarini** [csound/csound#1351]
Check that the default OPCODEDIR is set against the install prefix in CMake on Linux.

Evidence from Bela is that it is not.

**Comment by giuliomoro** [comment]
thanks

**Comment by vlazzarini** [comment]
The code in CMakeLists.txt appears to set the default opcodedir taking account of install_prefix

```
if(BUILD_RELEASE)
    add_definitions("-D_CSOUND_RELEASE_")
    if(LINUX)
        set(DEFAULT_OPCODEDIR "${CMAKE_INSTALL_PREFIX}/${PLUGIN_INSTALL_DIR}")
        add_definitions("-DCS_DEFAULT_PLUGINDIR=\"${DEFAULT_OPCODEDIR}\"")
    endif()
else()
    add_definitions("-DBETA")
endif()
```

This is enabled in the "Release" build type; I wonder if that's the problem. I don't see this being
set anywhere in the cross compile script. It can be done as an option to CMake too.

In any case, I have added the line

```
set(CMAKE_BUILD_TYPE "Debug")
```

to Bela/crosscompile.cmake.  Perhaps that will do the job.  The other thing is that if
we are not building the release version, then Csound is probably also running at about
half-speed with no optimisations.

**Comment by vlazzarini** [comment]
I looked at my VM build and found that it looks like the Release configuration is selected by default, and so
that's all good. However, I think when building I did not set the install prefix, and so everything defaulted to /usr/local/lib. However, when creating the Bela .deb package, things got installed in /usr. 

So I ran 
```
cmake  .. -DCMAKE_INSTALL_PREFIX=/usr/
```
and CMake set the default plugin to /usr/lib/csound/plugins-6. So that option needs to be set.

**Comment by vlazzarini** [comment]
I just checked again and CMAKE_BUILD_TYPE actually has no bearing on this. It's the option BUILD_RELEASE
that matters,

```
option(BUILD_RELEASE "Build for release" ON)
```

which is on by default. So that's OK. It's no harm also setting CMAKE_BUILD_TYPE=Release (to make sure all possible optimisations are turned on, although I think they already are). So it's CMAKE_INSTALL_PREFIX that needs to be set correctly for where the package eventually will be installed.
