### ISSUE TITLE
SetSpinSample method missing in Csound Android

### ISSUE THREAD

**Issue by giovannibedetti** [csound/csound#1354]
I'd like to do some tests with the Spin/Spout buffers on Android, to investigate a crash I get when using the library on Unity.
I found that while the GetSpoutSample is present in Csound.java, the SetSpinSample method is missing.
Is this intended?
The AddSpinSample method is there though, should I use this? Does this add the passed value to the current value of the buffer?

**Comment by vlazzarini** [comment]
Yes, there is no SetSpinSample in the Csound API, so you have to use AddSpinSample.

**Comment by rorywalsh** [comment]
https://github.com/csound/csound/blob/develop/include/csound.h#L1242-L1248

**Comment by vlazzarini** [comment]
It's not in the C++ interface.

**Comment by vlazzarini** [comment]
I actually don't know why we need SetSpinSample, since AddSpinSample does the job perfectly after spin is cleared.

**Comment by rorywalsh** [comment]
Who's talking about C++? Surely it has to be in the Csound API, we've been using this method for quite some time in CsoundUnity. And we don't interface to any of the C++ stuff.

**Comment by giovannibedetti** [comment]
This is where we use csoundSetSpinSample / csoundGetSpoutSample

https://github.com/rorywalsh/CsoundUnity/blob/686c51410c86d2208048cc44125660836edfd010/Runtime/CsoundUnity.cs#L1413

**Comment by rorywalsh** [comment]
We reference the API method here:
https://github.com/rorywalsh/CsoundUnity/blob/develop/Runtime/CsoundCsharp.cs#L270

**Comment by vlazzarini** [comment]
The C++ interface is used to generate the Java code. Replace SetSpinSample by AddSpinSample, and put a call to clearSpin just after performKsmps is called.

**Comment by rorywalsh** [comment]
`The C++ interface is used to generate the Java code.`

Thanks Victor. I wasn't aware of this.

**Comment by vlazzarini** [comment]
It's in csound.hpp now. SWIG generates the interface for it.

**Comment by rorywalsh** [comment]
Nice. Thanks Victor.
