### ISSUE TITLE
CTRLINIT broken

### ISSUE THREAD

**Issue by arthunkins** [csound/csound#1355]
Ctrlinit is broken from at least 6.13. Running from the console (all platforms), it has either no affect, or gives crazy results somehow related to midic7 or ctrl7 values, but not decipherable. This happens when events are triggered by MIDI events or via a score. (Ctrlinit can be placed either in instrument 0 or instrument 1.) Example below (MIDI run by virtual keyboard, showing the case of triggering by MIDI events):
```
<CsoundSynthesizer>
<CsOptions>

-odac -M0 -+rtmidi=virtual

</CsOptions>
<CsInstruments>

sr      = 44100
kr      = 4410
ksmps   = 10
nchnls  = 1
;	ctrlinit 1, 1, 500, 2, 500

        instr 1

	ctrlinit 1, 1, 500, 2, 500
kamp	midic7 1, 0, 5000
kamp	port kamp, .05
kfreq	midic7 2, 440, 880
a1	lfo    kamp, kfreq
	out    a1
        
        endin

</CsInstruments>
<CsScore>

f 0 360

e

</CsScore>
</CsoundSynthesizer>
```

**Comment by jpffitch** [comment]
There have een no changes in ctrlinit since 2017 January

**Comment by jpffitch** [comment]
and midic7 was changed in early 2019

**Comment by jpffitch** [comment]
This is user errior.  ctrliit akes raw values in the range 0-127 niw values tat are later saled as i ctrl7.

**Comment by vlazzarini** [comment]
I can confirm it works
```
ctrlinit 1,1,64

instr 1
kval ctrl7 1,1,0,1  
printk2 kval
endin
schedule(1,0,1)
```
prints

```
new alloc for instr 1:
 i1     0.50394
```

which is correct.

**Comment by vlazzarini** [comment]
I have updated the manual page and added an example (basically the one above). Maybe we just need to add the check and spit an error if the input is off the range.
