### ISSUE TITLE
Audio rate `expsegr` opcode is affected by control rate

### ISSUE THREAD

**Issue by vlazzarini** [csound/csound#1358]
When using the audio rate expsegr opcode, (specifically the version of expseg with the release segment), the results are impacted by the control rate.

Attached is a minimal example in which I have one instrument using expsegr, and a different version of the same instrument using the non release version expseg commented out so they can be quickly switched between for testing. With the first instrument, ksmps up to around 96 produce audio, but the audio varies with the ksmps value. For ksmps > 96, there is silence (I think the first trigger has infinite amplitude and I guess the rest are silenced). The second version is unaffected by the value of ksmps.

I believe linesegr works as expected.

example:

```
<CsoundSynthesizer>
<CsOptions>
-odac -d
</CsOptions>
<CsInstruments>

sr     = 48000
ksmps  = 1000
nchnls = 2
0dbfs  = 1

instr Kick
    iOctave init p5
    iAmplitude init p4
    iDuration init p3
    iStartTime init p2
    aOscAmpEnv expsegr 0.0001, 0.01, 1, 0.5, 0.0001, 0.9, 0.0001
    aOsc0 = oscili:a(aOscAmpEnv, 220)
    outs aOsc0, aOsc0
endin

</CsInstruments>
<CsScore>

t 0 60

i"Kick" 0.000000 0.125000 0.500000 6.273083
i"Kick" 0.250000 0.125000 0.169541 6.025758
i"Kick" 0.375000 0.125000 0.265359 6.299560
i"Kick" 0.500000 0.125000 0.338136 6.156609
i"Kick" 0.750000 0.125000 0.107444 6.010960
i"Kick" 0.875000 0.125000 0.189788 6.502128
i"Kick" 1.250000 0.125000 0.359605 6.290485
i"Kick" 1.375000 0.125000 0.253425 6.694606
i"Kick" 1.750000 0.125000 0.281007 6.072183
i"Kick" 2.250000 0.125000 0.437406 6.517318
i"Kick" 2.500000 0.125000 0.301804 6.185603
i"Kick" 2.625000 0.125000 0.303654 6.217183
i"Kick" 3.000000 0.125000 0.500000 6.328006
i"Kick" 3.125000 0.125000 0.120511 6.111028
i"Kick" 3.250000 0.125000 0.354486 6.277189
i"Kick" 3.500000 0.125000 0.250104 6.001258

</CsScore>
</CsoundSynthesizer>
```
reported by @IronAttorney

**Comment by vlazzarini** [comment]
I had a look at this and traced the bug to these lines in OOps/ugens1.c:1064

```
            p->curmlt = POWER((segp->nxtpt/val), FL(1.0)/segp->cnt);
            p->curamlt = POWER(p->curmlt, FL(1.0)/(MYFLT)(nsmps-offset));
```

This seems to make the multiplier `p->curamlt`  dependent on nsmps. A fix is to replace
the second line  by

```
            p->curamlt = POWER((segp->nxtpt/val), FL(1.0)/segp->acnt)
```

but that is not fully correct either since it does not take account of offsets etc in sample-accurate mode. 
Maybe @jpffitch could have a look? I commit the semi-fix.

**Comment by vlazzarini** [comment]
A suggestion was made to go with this fix for now. This closes the issue. Can we do that?

**Comment by jpffitch** [comment]
yes
