### ISSUE TITLE
strget bug ?

### ISSUE THREAD

**Issue by SashaBlondeau** [csound/csound#1360]
I have isolated a bug with strget : sometimes the reported string is not correct.
Let run the (very simple) attached patch [test-strget.zip](https://github.com/csound/csound/files/4925384/test-strget.zip) for a "certain time" and sometimes the string printed in max window is not right....maybe a threading issue or string memory allocation ?
csound~ v1.1.3(vb+)
MacOS 10.15.5
Max 8.1.5
csound 6.14
and the DSP has to be ON.
But maybe it reveals a bug in csound, because I am not able to reproduce my problem with csound 6.10 ...
Thank you for any hint !

Sasha

https://github.com/csound/csound_tilde/issues/9#issue-590474142

**Comment by vlazzarini** [comment]
Would you be able to test it directly with Csound 6.14 (not csound~)? I'll have a look.

**Comment by vlazzarini** [comment]
strget is an i-time opcode, which is run only once at i-time, setting the value of the variable Smember. In --realtime mode, all
init-time code runs on a separate thread, but this is set to run before performance (in the realtime thread) can begin. I don't have maxmsp, so I can't see what that code is doing. But in the CSD you gave me, there is only one instantiation of the instrument, and strget runs exactly once.

**Comment by SashaBlondeau** [comment]
Dear Victor, thanks a lot ! Without the "--realtime" set it seams to work !!

**Comment by vlazzarini** [comment]
ok, you don't need that option for csound~
I'll close this now.
