### ISSUE TITLE
sc_phasor does not always complete cycle to end value

### ISSUE THREAD

**Issue by Oeyvind** [csound/csound#1363]
It seems that there is something odd with sc_phasor. 
I was expecting it to be possible to use it for soft synchronization, to nudge the phase value (increment or decrement) when it receives an external trigger.  It seems that it will sometimes reinitialize to the kstart value instead of the kresetPos value when it receives a trigger input. 

To illustrate, I made a UDO that behaves like I would expect, and run that simultaneously. The example produce a stereo audio file with the phase values from my UDO in the left channel and the phase values from sc_phasor in the right channel.

```
<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 128
0dbfs = 1
nchnls = 2

opcode Syncphasor2, kk, kk
  krate, ksync_in xin
  ;setksmps 1
  kphase init 0
  kphase += krate/kr
  kphase += ksync_in
  ktrig_out trigger kphase, 1, 0
  kphase = ktrig_out > 0 ? 0 : kphase
xout ktrig_out, kphase
endop

instr 1
krate = 1
ksyncrate = 3.8
ksync_amt = 0.2
ktrig_in metro ksyncrate
ksync_in = ktrig_in*ksync_amt
kt,kp Syncphasor2 krate, ksync_in
aphase upsamp kp
a0 = 0
out aphase, a0
endin

instr 2
krate = 1
ksyncrate = 3.8
ksync_amt = 0.2
ktrig_in metro ksyncrate
ktrig_in -= 0.5
ksync_in = ktrig_in*ksync_amt
kphase init 0
kphase sc_phasor ktrig_in, krate/kr, 0, 1 , kphase+ksync_amt
ktrig_out trigger kphase, 0.5, 1
aphase upsamp kphase
a0 = 0
outs a0, aphase
endin

</CsInstruments>
<CsScore>
i1      0     10
i2      0     10
e
</CsScore>
</CsoundSynthesizer>

```

**Comment by jpffitch** [comment]
This is Eduardo code so should be directed to him.

**Comment by kunstmusik** [comment]
@gesellkammer Any thoughts on this issue?

**Comment by gesellkammer** [comment]
Sorry for the late reply. There is nothing wrong with sc_phasor, only the assumptions of the OP are off track. In fact the UDO given does not conform at all with the manual page for this opcode, so it is not very surprising that they defer.

**Comment by gesellkammer** [comment]
Can we close this issue?

**Comment by Oeyvind** [comment]
Hi, I am the OP. The UDO was not meant to replicate all functionality of sc_phasor, but to show a specific use case where it did not behave as I had reason to expect. It has been some time, and I do not have the details crystal clear no longer. Anyway I worked around it for my own use case, and only wrote the issue so someone else might be free of running into the same hole. Feel free to close it if you are happy with the way it works.
