### ISSUE TITLE
Submit csound to Chocolately to have available for installation on Windows

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#1364]
We should look at submitting Csound to https://chocolatey.org/ so that users can install easily using choco as well as developers who might want to build against Csound.

**Comment by gesellkammer** [comment]
This would be very useful for automated builds with plugins. Currently to have an azure pipeline we need to first build csound and all its dependencies only to build and test a plugin.

**Comment by stekyne** [comment]
@gesellkammer Why not just use the pre-built binaries hosted in Github? https://github.com/csound/csound/releases

**Comment by kunstmusik** [comment]
+1 I'd like to see Csound in Chocolatey repo.

**Comment by stekyne** [comment]
https://community.chocolatey.org/packages/csound

This was completed a while back. This can be closed. We can update chocolatey with Csound 7 when it is released.

**Comment by kunstmusik** [comment]
Wow, I had no idea, thanks very much!
