### ISSUE TITLE
Plugin problem from 6.14 still in 6.15 on Windows 10

### ISSUE THREAD

**Issue by markusdichtl** [csound/csound#1367]
Dear Csound Developers,
I tried in vain to get Csound 6.14 with CsoundQt running on Windows 10, so I had to fall back to 6.13.
Now I have the same problem with 6.15, namely CsoundQt complains about procedure entry point "inflateValidate" not being found in C:\Program Files\Csound6_x64\plugins64\image.dll.
I know that this problem was claimed to be fixed for 6.14, but it persists for me.
I am also in doubt whether Csound or CsoundQt is to blame, but apparently something is missing in the image.dll file which belongs to csound.
I also found some comments blaming  a Visual C redistributable file. I replaced the one in the CsoundQt directory with a current one from Microsoft, but this did not help.

Yours sincerely
   Markus Dichtl

**Comment by jpffitch** [comment]
Is this a csound issue or csoundqt?

⁣Sent from TypeApp ​

**Comment by jpffitch** [comment]
there is no inflateValidate in the csound sources

**Comment by vlazzarini** [comment]
Sounds like a libPNG function 

https://community.mypaint.org/t/error-with-inflatevalidate-in-libpng16-16-dll-on-windows-10-64-bit/2025

**Comment by vlazzarini** [comment]
Similarly to other opcodes with dependencies, these need to be moved out of the main csound repo.

**Comment by vlazzarini** [comment]
these opcodes are now solely in plugins and not part of the main repo and installer, so closing it.

**Comment by rorywalsh** [comment]
I'm a bit late to the party here, but if anyone has this issue again, just remove image.dll from the plugins folder. It has a dependency on zlib which is causing problems with it.

**Comment by vlazzarini** [comment]
The new installer will not have it. It's a now part of the separate plugin repo.
