### ISSUE TITLE
In 6.15.0, output type signatures of init seem to permit only 1-dimensional arrays

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#1369]
On macOS (this is extremely unlikely to be limited to macOS, but that’s what I have to reproduce this), install Csound 6.14.0 using [Homebrew](https://brew.sh) by running:

```sh
git -C "$(brew --repo homebrew/core)" checkout 04846677193157ed334ff902f43913931d654f8a
HOMEBREW_NO_AUTO_UPDATE=1 brew reinstall csound
```

Running  `csound --list-opcodes1` should show:

```
0dBFS level = 32768.0
--Csound version 6.14 (double samples) Jun 25 2020
[commit: 1073b4d1bc2304a1e06defd266781a9c441a5be0]
⋮
inh         aaaaaa      (null)
init        .[]         m
init        IIIIIIIIIIIIIIIIIIIIIIII m
init        S           S
init        S           i
init        f           f
init        mmmmmmmmmmmmmmmmmmmmmmmm m
init        zzzzzzzzzzzzzzzzzzzzzzzz m
initc14     (null)      iiii
⋮
```

Note the version of `init` with an input type signature of `m` (any number of i-time scalars) and an output type signature of `.[]`. I understand `.` to mean any type—`i`, `k`, `i[]`, `i[][]`—so `.[]` means an array of 1 or more dimensions of any type.

Upgrade Csound to 6.15.0 by running:

```sh
git -C "$(brew --repo homebrew/core)" checkout master
brew upgrade csound
```

Running  `csound --list-opcodes1` should now show:

```
0dBFS level = 32768.0
--Csound version 6.15 (double samples) Aug 16 2020
[commit: 18c2c7897425f462b9a7743cee157cb410c88198]
⋮
inh         aaaaaa      (null)
init        IIIIIIIIIIIIIIIIIIIIIIII m
init        S           S
init        S           i
init        S[]         m
init        a[]         m
init        f           f
init        i[]         m
init        k[]         m
init        mmmmmmmmmmmmmmmmmmmmmmmm m
init        zzzzzzzzzzzzzzzzzzzzzzzz m
initc14     (null)      iiii
⋮
```

Note that there is no version of `init` with an output type signature of `.[]`. Instead, there are versions with output type signatures of `S[]`, `a[]`, `i[]`, and `k[]`. I could be mistaken, but I believe that these are all types of 1-dimensional arrays. Going by `init`’s output type signatures, it doesn’t appear that `init` can be used to initialize arrays with 2 or more dimensions in Csound 6.15.0.

It appears that `init` can, in fact, be used to initialize arrays with 2 or more dimensions in Csound 6.15.0—the issue is that `init`’s output type signatures don’t *appear* to permit this. This is a problem when relying on output type signatures to lint Csound orchestras.

How do `init`’s output type signatures correspond to what `init` does in Csound 6.15.0?

**Comment by kunstmusik** [comment]
Looks like @vlazzarini changed this in https://github.com/csound/csound/commit/1e64bf60c65cd0bf63e2b6e05f019cfeacaca9ee which references #1300 and therefore looks intentional. I'd have to look deeper as it's been a long time since I looked at the type definition code for arrays, but this code snippet worked, which seems to indicate array dimensionality is not a part of the type definition:

```csound
ivals[] init 4,5,6
ivals[3][4][5] = 17 
print ivals[3][4][5]
```

**Comment by vlazzarini** [comment]
yes, my thinking was that the parser just looks for a type identifying an array. Dimensionality is a property of the object when constructed, and so the parser does not get in the way of it. However, I must say I never checked whether that was that assumption was right.

**Comment by nwhetsell** [comment]
This sort of seems like an ambiguity to me. Running @kunstmusik’s example indeed prints 17, and changing it to—

```csound
ivals[] init 4,5,6
ivals[0][0][0] = -1
printarray abs(ivals)
```

—prints `1.0000 0.0000 0.0000 0.0000`. However, running—

```csound
ivals[] init 4,5,6
ivals[0][0][0] = -1
printarray ivals
```

—seems to print nothing, and—

```csound
ivals[] init 4,5,6
ivals[0][0][0] = -1
printarray ivals[0][0]
```

—produces a syntax error (even though `ivals[0][0]` is an array of 6 i-time scalars):

```
error:  Unable to find opcode entry for 'printarray' with matching argument types:
Found: (null) printarray i
```

A quick sampling of opcodes also seems to show several that use `k[]` or `S[]` as input or output arguments, but arguably aren’t intended for multidimensional arrays:

* [`chnget`](https://csound.com/docs/manual/chnget.html) can read “an array of named software channels” (`S[]`) into “an array of strings” (also `S[]`); it seems like both have to be 1-dimensional string arrays

* [`directory`](https://csound.com/docs/manual/directory.html) returns “a string array” (`S[]`) of files in a directory

* [`rfft`](https://csound.com/docs/manual/rfft.html), which inputs and outputs `k[]`, computes the discrete Fourier transform of a “1-dimensional array” (the example code for this also includes a 2-dimensional array [declared as `kOut[][]`](https://github.com/csound/manual/blob/e29ffaebc9e78eec62ee010a80f37ffd8596129d/examples/rfft.csd#L24), although the second `[]` is seemingly unnecessary)

**Comment by vlazzarini** [comment]
That to me is another issue. The opcodes should check that they can deal with the input and output arrays they are passed. 

The rfft example uses a two-dimensional array, but the rfft opcode itself only does a 1-D transform.

I think the issues you raised with printarray need to be looked at, but they would have been there before the change to create explicit init() overloads for each array type.

**Comment by nwhetsell** [comment]
So in type signatures, is the actual meaning of, say, `k[]` *an array of k‑rate scalars of any dimension*?

[`OSCbundle`](https://csound.com/docs/manual/OSCbundle.html), by the way, appears to use an input type of `k[][]` to mean a 2-dimensional array (and its example code includes an array [declared as `kdata[][]`](https://github.com/csound/manual/blob/e29ffaebc9e78eec62ee010a80f37ffd8596129d/examples/oscbundle.csd#L10)), so it does seem like the meaning of `[]` in type signatures has shifted somewhat.

**Comment by jpffitch** [comment]
yes

**Comment by jpffitch** [comment]
This is not the case.  

> ivals[] init 4,5,6 ivals[0][0][0] = -1 printarray ivals[0][0]


> —produces a syntax error (even though ivals[0][0] is an array of 6 i-time scalars):


> error: Unable to find opcode entry for 'printarray' with matching argument types: Found: (null) printarray i

In csound there is no subarray

**Comment by nwhetsell** [comment]
Might be good to document that somewhere.
