### ISSUE TITLE
Xcode warnings in Csound6.14.0-iOS or Csound6.15.0-iOS - Passing 'char *[4]' to parameter of type 'const char **' discards qualifiers in nested pointer types

### ISSUE THREAD

**Issue by xenophoria** [csound/csound#1372]
When I download either `csound-iOS-6.14.0` or  `csound-iOS-6.15.0`  and launch `Csound iOS  Examples.xcodeproj` Xcode reports 23 warnings.

Xcode took care of the first 3 issues in the project file as well as 1 issue in `csound.h`

I silenced 7 deprecated methods warnings by commenting the `viewDidUnload`, `shouldAutorotateToInterfaceOrientation` and `splitViewController` methods as well as one in `AudioFileTestViewController.m` which is cannot find in the Xcode navigation window.

I also took care of the 9 motion statements by doing the fix recommended by Xcode. 

`Csound iOS Examples.xcodeproj	`
	Update to recommended settings
	Migrate “English.lproj” (Deprecated) 	
	Enable Base Internationalisation 

`csound.h `
	line 2238
	This function declaration is not a prototype (fix: insert void)

`BaseCsoundViewController 	`
	line 68	
	Implementing deprecated method	(`shouldAutorotateToInterfaceOrientation`)
	line 109 	
	Implementing deprecated method	(`splitViewController`)

`AudioFileTestViewController.m `
	line 85
	Implementing deprecated method

`MasterViewController` 	
	line 99
	Implementing deprecated method	(`viewDidUnload`)								
	line 126 	
	Implementing deprecated method	(`shouldAutorotateToInterfaceOrientation`)

`DetailViewController.m	`		
	line 76	
	Implementing deprecated method (`viewDidUnload`)
	line 103	
	Implementing deprecated method (`shouldAutorotateToInterfaceOrientation`)

`HardwareTestViewController.m`
	line 48	
	Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
	line 49
	line 50

	line 56
	line 57
	line 58

	line 64
	line 65
	line 66

The remaining 3 issues include 1 associated with the assets folder which is missing an app store icon and 2 reported previously. 

For this test I am using **Catalina 10.15.6** running on a MacBook Pro and using **Xcode Version 11.6**. I tried this previously with **Csound6.14.0-iOS** but this time I used **Csound6.15.0-iOS** with 10.2 as the iOS Deployment Target. 

When I tried to build Csound iOS Examples in  two issues are reported in `CsoundObj` at lines 421 and 457. Both lines reference line 811 in Csound.h. 

CsoundObj.m:421:36: Passing 'char *[4]' to parameter of type 'const char **' discards qualifiers in nested pointer types
CsoundObj.m:457:36: Passing 'char *[2]' to parameter of type 'const char **' discards qualifiers in nested pointer types

I tried to use `(const char *)` to clear the warning but the only way I could clear it was to change the argument in csound.h which is already published in the API. 

i.e. in csound.h, line 811 `(const char **)` was changed to `(const char *)`

`CsoundObj`, line 421
changed     
`int ret = csoundCompile(cs, 4, argv);`
    to   
`int ret = csoundCompile(cs, 4, (const char*)argv);`

`CsoundObj`, line 457
changed     
`int ret = csoundCompile(cs, 2, argv);`
    to  
` int ret = csoundCompile(cs, 2, (const char*)argv);`

`csound.h`, line 811
changed     
`PUBLIC int csoundCompile(CSOUND *, int argc, const char **argv);`
    to   
`PUBLIC int csoundCompile(CSOUND *, int argc, const char *argv);`

It is quite possible I have not caste the const char* correctly but I have no other way to clear this warning.

**Comment by xenophoria** [comment]
I found the problem.

**Comment by vlazzarini** [comment]
The Objective-C code in the Csound codebase needs to be fixed to silence these warnings, does it not? The bits you have changed are not user code. I'll reopen this until it's clear we have fixed the warnings in the repo.

**Comment by vlazzarini** [comment]
@kunstmusik: could you have a look?

**Comment by kunstmusik** [comment]
I'm not sure why I'm being asked to look at this when I haven't been maintaining the iOS port or developing iOS code for quite some time, but I'll take a quick look to see if I can reproduce this and make a change.

**Comment by kunstmusik** [comment]
Didn't need a cast; variables just needed to be defined as const.  Fixed and committed to develop branch.

**Comment by vlazzarini** [comment]
@kunstmusik  Is this orphaned now?

**Comment by kunstmusik** [comment]
I thought you were maintaining this as you are doing the releases? I don't
really have a lot of bandwidth to get back into iOS at the moment. Fielding
PR's for iOS is simple enough, but if there's larger work to be done then I
think we need a new person to take this on.

**Comment by vlazzarini** [comment]
I am doing the releases, which is
just running scripts, but I don't know anything about the Objective C code. Certainly needs someone who knows that side of things.

**Comment by xenophoria** [comment]
Thanks Stephen and Victor.
