### ISSUE TITLE
Linear Albegra Opcodes failing to build

### ISSUE THREAD

**Issue by nullr0ute** [csound/csound#1373]
In recent releases (at least 6.14 and 6.15) the Linear Albegra Opcodes have failed to build with the following error. I've tried against gmm 5.2/3/4 to no avail. This is using gcc 10, I suspect it's a little due to Fedora's tightened toolchain flags.

<pre>
cd /builddir/build/BUILD/csound-6.15.0/x86_64-redhat-linux-gnu/Opcodes && /usr/bin/g++ -DCS_DEFAULT_PLUGINDIR=\"/usr/lib64/csound/plugins-6.0\" -DHAVE_EXECINFO -DHAVE_SOCKETS -DHAVE_STRTOD_L -DHAVE_STRTOK_R -DLIB64 -DLINUX -DNO_FLTK_THREADS -DPIPES -DUSE_LRINT -D_CSOUND_RELEASE_ -D_GNU_SOURCE -Dlinear_algebra_EXPORTS -I/builddir/build/BUILD/csound-6.15.0/./H -I/builddir/build/BUILD/csound-6.15.0/./include -I/builddir/build/BUILD/csound-6.15.0/./Engine -I/builddir/build/BUILD/csound-6.15.0/./util -I/builddir/build/BUILD/csound-6.15.0/. -I/builddir/build/BUILD/csound-6.15.0/x86_64-redhat-linux-gnu -I/builddir/build/BUILD/csound-6.15.0/x86_64-redhat-linux-gnu/include -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -std=c++11 -ffast-math -mfpmath=sse -msse2 -fomit-frame-pointer -fvisibility=hidden -fvisibility=hidden -DHAVE_ATOMIC_BUILTIN -fPIC -o CMakeFiles/linear_algebra.dir/linear_algebra.cpp.o -c /builddir/build/BUILD/csound-6.15.0/Opcodes/linear_algebra.cpp
/builddir/build/BUILD/csound-6.15.0/Opcodes/linear_algebra.cpp: In member function 'int la_i_lu_factor_mr_t::init(CSOUND*)':
/builddir/build/BUILD/csound-6.15.0/Opcodes/linear_algebra.cpp:3504:45: error: no matching function for call to 'lu_factor(gmm::dense_matrix<double>&, std::vector<long unsigned int>&)'
 3504 |     *isize = gmm::lu_factor(lhs->mr, pivot__);
      |                                             ^
In file included from /usr/include/gmm/gmm_lapack_interface.h:42,
                 from /usr/include/gmm/gmm_kernel.h:52,
                 from /usr/include/gmm/gmm.h:40,
                 from /builddir/build/BUILD/csound-6.15.0/Opcodes/linear_algebra.cpp:370:
/usr/include/gmm/gmm_dense_lu.h:129:13: note: candidate: 'template<class DenseMatrix> gmm::size_type gmm::lu_factor(DenseMatrix&, gmm::lapack_ipvt&)'
  129 |   size_type lu_factor(DenseMatrix& A, lapack_ipvt& ipvt) {
      |             ^~~~~~~~~
/usr/include/gmm/gmm_dense_lu.h:129:13: note:   template argument deduction/substitution failed:
/builddir/build/BUILD/csound-6.15.0/Opcodes/linear_algebra.cpp:3504:38: note:   cannot convert '((la_i_lu_factor_mr_t*)this)->la_i_lu_factor_mr_t::pivot__' (type 'std::vector<long unsigned int>') to type 'gmm::lapack_ipvt&'
 3504 |     *isize = gmm::lu_factor(lhs->mr, pivot__);
      |                                      ^~~~~~~
/builddir/build/BUILD/csound-6.15.0/Opcodes/linear_algebra.cpp: In member function 'int la_k_lu_factor_mr_t::kontrol(CSOUND*)':
/builddir/build/BUILD/csound-6.15.0/Opcodes/linear_algebra.cpp:3541:45: error: no matching function for call to 'lu_factor(gmm::dense_matrix<double>&, std::vector<long unsigned int>&)'
 3541 |     *ksize = gmm::lu_factor(lhs->mr, pivot__);
      |                                             ^
In file included from /usr/include/gmm/gmm_lapack_interface.h:42,
                 from /usr/include/gmm/gmm_kernel.h:52,
                 from /usr/include/gmm/gmm.h:40,
                 from /builddir/build/BUILD/csound-6.15.0/Opcodes/linear_algebra.cpp:370:
/usr/include/gmm/gmm_dense_lu.h:129:13: note: candidate: 'template<class DenseMatrix> gmm::size_type gmm::lu_factor(DenseMatrix&, gmm::lapack_ipvt&)'
  129 |   size_type lu_factor(DenseMatrix& A, lapack_ipvt& ipvt) {
      |             ^~~~~~~~~
/usr/include/gmm/gmm_dense_lu.h:129:13: note:   template argument deduction/substitution failed:
/builddir/build/BUILD/csound-6.15.0/Opcodes/linear_algebra.cpp:3541:38: note:   cannot convert '((la_k_lu_factor_mr_t*)this)->la_k_lu_factor_mr_t::pivot__' (type 'std::vector<long unsigned int>') to type 'gmm::lapack_ipvt&'
 3541 |     *ksize = gmm::lu_factor(lhs->mr, pivot__);
      |                                      ^~~~~~~
/builddir/build/BUILD/csound-6.15.0/Opcodes/linear_algebra.cpp: In member function 'int la_i_lu_factor_mc_t::init(CSOUND*)':
/builddir/build/BUILD/csound-6.15.0/Opcodes/linear_algebra.cpp:3575:45: error: no matching function for call to 'lu_factor(gmm::dense_matrix<std::complex<double> >&, std::vector<long unsigned int>&)'
 3575 |     *isize = gmm::lu_factor(lhs->mc, pivot__);
      |                                             ^
In file included from /usr/include/gmm/gmm_lapack_interface.h:42,
                 from /usr/include/gmm/gmm_kernel.h:52,
                 from /usr/include/gmm/gmm.h:40,
                 from /builddir/build/BUILD/csound-6.15.0/Opcodes/linear_algebra.cpp:370:
/usr/include/gmm/gmm_dense_lu.h:129:13: note: candidate: 'template<class DenseMatrix> gmm::size_type gmm::lu_factor(DenseMatrix&, gmm::lapack_ipvt&)'
  129 |   size_type lu_factor(DenseMatrix& A, lapack_ipvt& ipvt) {
      |             ^~~~~~~~~
/usr/include/gmm/gmm_dense_lu.h:129:13: note:   template argument deduction/substitution failed:
/builddir/build/BUILD/csound-6.15.0/Opcodes/linear_algebra.cpp:3575:38: note:   cannot convert '((la_i_lu_factor_mc_t*)this)->la_i_lu_factor_mc_t::pivot__' (type 'std::vector<long unsigned int>') to type 'gmm::lapack_ipvt&'
 3575 |     *isize = gmm::lu_factor(lhs->mc, pivot__);
      |                                      ^~~~~~~
/builddir/build/BUILD/csound-6.15.0/Opcodes/linear_algebra.cpp: In member function 'int la_k_lu_factor_mc_t::kontrol(CSOUND*)':
/builddir/build/BUILD/csound-6.15.0/Opcodes/linear_algebra.cpp:3612:45: error: no matching function for call to 'lu_factor(gmm::dense_matrix<std::complex<double> >&, std::vector<long unsigned int>&)'
 3612 |     *ksize = gmm::lu_factor(lhs->mc, pivot__);
      |                                             ^
In file included from /usr/include/gmm/gmm_lapack_interface.h:42,
                 from /usr/include/gmm/gmm_kernel.h:52,
                 from /usr/include/gmm/gmm.h:40,
                 from /builddir/build/BUILD/csound-6.15.0/Opcodes/linear_algebra.cpp:370:
/usr/include/gmm/gmm_dense_lu.h:129:13: note: candidate: 'template<class DenseMatrix> gmm::size_type gmm::lu_factor(DenseMatrix&, gmm::lapack_ipvt&)'
  129 |   size_type lu_factor(DenseMatrix& A, lapack_ipvt& ipvt) {
      |             ^~~~~~~~~
/usr/include/gmm/gmm_dense_lu.h:129:13: note:   template argument deduction/substitution failed:
/builddir/build/BUILD/csound-6.15.0/Opcodes/linear_algebra.cpp:3612:38: note:   cannot convert '((la_k_lu_factor_mc_t*)this)->la_k_lu_factor_mc_t::pivot__' (type 'std::vector<long unsigned int>') to type 'gmm::lapack_ipvt&'
 3612 |     *ksize = gmm::lu_factor(lhs->mc, pivot__);
      |                                      ^~~~~~~
gmake[2]: *** [Opcodes/CMakeFiles/linear_algebra.dir/build.make:85: Opcodes/CMakeFiles/linear_algebra.dir/linear_algebra.cpp.o] Error 1
gmake[2]: Leaving directory '/builddir/build/BUILD/csound-6.15.0/x86_64-redhat-linux-gnu'
gmake[1]: Leaving directory '/builddir/build/BUILD/csound-6.15.0/x86_64-redhat-linux-gnu'
gmake[1]: *** [CMakeFiles/Makefile2:1731: Opcodes/CMakeFiles/linear_algebra.dir/all] Error 2
gmake: *** [Makefile:185: all] Error 2
</pre>

**Comment by jpffitch** [comment]
Try setting GMM_VERSION to something.  I mean the C macro
⁣Get TypeApp for Android ​

**Comment by jpffitch** [comment]
Looking again this seems deep in C++.  Without any sources to try this is way beyond my understanding.

**Comment by jpffitch** [comment]
Looking again this seems deep in C++.  Without any sources to try this is way beyond my understanding.

**Comment by jpffitch** [comment]
Looking again this seems deep in C++.  Without any sources to try this is way beyond my understanding.

**Comment by jpffitch** [comment]
Looking again this seems deep in C++.  Without any sources to try this is 
way beyond my understanding.

(Sorry if this appears twice -- github does not let me comment on their 
site)

**Comment by vlazzarini** [comment]
Can you switch off the build of these opcodes using -DBUILD_LINEAR_ALGEBRA_OPCODES=0?

I think these are tied to a specific version of the library and it does not seem possible to support them across the board.

I think the best solution is to move these out to the plugin repo. I know that doesn't help
this issue, but maybe it will help it for the future.

**Comment by nullr0ute** [comment]
> Can you switch off the build of these opcodes using -DBUILD_LINEAR_ALGEBRA_OPCODES=0?

Yes, I have already done that, I just wanted to report it so people are aware of the issue.
