### ISSUE TITLE
lame.h may not be found when building libmp3out.so

### ISSUE THREAD

**Issue by PeteCA** [csound/csound#1374]
Different sources for LAME put the lame.h header that mp3out needs in different places, and Cmake may not find it. Curently it only seems to look in the main include directory, wherever that is for the build OS, but the dev kit for libmp3lame on linux, for example, puts it in ...include/lame/lame.h (as does the one for Haiku). I assume that the Cmake configuration can be adjusted to handle this, but I'll leave that to someone who knows...

**Comment by PeteCA** [comment]
Different sources for LAME put the lame.h header that mp3out needs in different places, and Cmake may not find it.  Curently it only seems to look in the main include directory, wherever that is for the build OS, , but the dev kit for libmp3lame on linux, for example, puts it in ...include/lame/lame.h (as does the one for Haiku).  I assume that the Cmake configuration can be adjusted to handle this, but I'll leave that to someone who knows...

**Comment by PeteCA** [comment]
Different sources for LAME put the lame.h header that mp3out needs in different places, and Cmake may not find it.  Curently it only seems to look in the main include directory, wherever that is for the build OS, , but the dev kit for libmp3lame on linux, for example, puts it in ...include/lame/lame.h (as does the one for Haiku).  I assume that the Cmake configuration can be adjusted to handle this, but I'll leave that to someone who knows...

**Comment by PeteCA** [comment]
Different sources for LAME put the lame.h header that mp3out needs in different places, and Cmake may not find it.  Curently it only seems to look in the main include directory, wherever that is for the build OS, , but the dev kit for libmp3lame on linux, for example, puts it in ...include/lame/lame.h (as does the one for Haiku).  I assume that the Cmake configuration can be adjusted to handle this, but I'll leave that to someone who knows...

**Comment by PeteCA** [comment]
Different sources for LAME put the lame.h header that mp3out needs in different places, and Cmake may not find it.  Curently it only seems to look in the main include directory, wherever that is for the build OS, , but the dev kit for libmp3lame on linux, for example, puts it in ...include/lame/lame.h (as does the one for Haiku).  I assume that the Cmake configuration can be adjusted to handle this, but I'll leave that to someone who knows...

**Comment by vlazzarini** [comment]
I think the best action here is to move this plugin to the plugins repo, since it has dependencies. We are doing this with other opcodes in the same situation. Would it be ok to do this @jpff? I can do it and then close this.

**Comment by jpffitch** [comment]
Ok to makes plugin.  Note however that
shortly libsndfile will have mp134 and lame as dependancies for MP3/mpeg.


⁣Get TypeApp for Android ​

**Comment by tjingboem** [comment]
Look like mp3 support has been added:
- Version 1.1.0 (March 27 2022) Minor release, backward compatible with previous releases. Added long-awaited MP3 support. Numerous improvements and bugfixes.

https://libsndfile.github.io/libsndfile/

**Comment by vlazzarini** [comment]
yes, it looks like all you need to do now is update your libsndfile. We can close this now, also the code has been moved to the plugins.
