### ISSUE TITLE
fprintks opcode crashes when format contains one %s

### ISSUE THREAD

**Issue by andy-fillebrown** [csound/csound#1377]
The `fprintks` opcode is crashing when the format contains a single %s, i.e. `fprintks("my.sco", "%s\n", "test")`.

This occurs on MacOS but not on Windows. I haven't tried it on any other OS.

The attached .csd reproduces the issue on my Mac.

[fprintks.csd.txt](https://github.com/csound/csound/files/5210724/fprintks.csd.txt)

**Comment by vlazzarini** [comment]
Investigating this now. I can confirm that it crashes with the released version 6.15 on MacOS. However, the local build in the debug configuration does not, so it seems to be something relating to compiler optimisation.

**Comment by vlazzarini** [comment]
Found the bug and fixed it.

**Comment by andy-fillebrown** [comment]
Thank you for the quick fix. Is there a build server I can download MacOS binaries from?

**Comment by vlazzarini** [comment]
Unfortunately not, but building on MacOS should not be too complicated.

**Comment by andy-fillebrown** [comment]
No worries. I'm working around it by adding a dummy `%d` to the end of the string for now.
