### ISSUE TITLE
Csound, CsoundQt error message: The procedure entry point inflateValidate could not be located in the dynamic link library C:\Program  Files\Csound6_x64\plugins64\image.dll

### ISSUE THREAD

**Issue by Gage123456** [csound/csound#1381]
When I start CsoundQt I get this error message:  The procedure entry point inflateValidate could not be located in the dynamic link library C:\Program  Files\Csound6_x64\plugins64\image.dll
I found this thread and executed the steps they suggested, but I could not get a fix. 
http://csound.1045644.n5.nabble.com/Csnd-6-14-0-Windows-Build-Fixed-td5768447.html

**Comment by vlazzarini** [comment]
This seems to be a build/packaging issue. The problem I thin is with libpng16 that is used in the build, which does not seem to have that symbol. It affects only the image opcodes. If you don't use them, you can move
C:\Program Files\Csound6_x64\plugins64\image.dll away into a different folder. That will stop it.

**Comment by stekyne** [comment]
Hmm yeah it does seem to be some problem with libpng and zlib. zlib is being used dynamically so maybe it is a path issue. I can try and take a look today at some point.

**Comment by Gage123456** [comment]
All is well! There was a zlib file in my system 32 folder that was
impacting the program. I removed it from the path and everything works fine
now.
