### ISSUE TITLE
Jack: nchnls_i depends on nchnls

### ISSUE THREAD

**Issue by A1RO** [csound/csound#1382]
Following recommandations on #1380, I'm giving another try at `-+rtaudio=jack`.
After a while, I remembered about issue #742. Well, seems like it never been solved completely.

From what I can tell, `nchnls` must be greater than or equal to `nchnls_i` for the audio to get routed correctly.

So, to hear 4 channels _in_ (`nchnls_i = 4`), I need at least 4 channels _out_ (`nchnls = 4`). No need to output to channel 3 and 4, only need to set them. At this point, everything works fine.

But if I set `nchnls = 2`, the following happens:
- Input channels 1 and 2 get lost
- Input channels 3 and 4 are sent straight away to output channels 1 and 2, even with an empty score and empty instrument (no `inch` or `outs` statements). That's a nasty bug!
- Jack connections to external clients get created as expected, which make it _seem_ like it works, even though it _doesn't_
- No special warning or strange message gets printed on the command line. Again, everything _seems_ right

Let me know if I can help solving this one.

**Comment by vlazzarini** [comment]
Ok, looks like a proper bug alright. Need to look to see how the number of inputs are being set. Can you give us a test CSD so we know we are looking at the right thing?

**Comment by A1RO** [comment]
Sure. Here is the test file i used:

```csd
<CsoundSynthesizer>
<CsOptions>
-+rtaudio=jack
-+jack_client=csound_mixer
-i adc4
-o dac0
-b 256
-B 512
</CsOptions>
<CsInstruments>

sr = 48000
ksmps = 16
nchnls_i = 4
nchnls = 4
0dbfs = 1.0

instr 1

a1, a2 inch 1, 2
a3, a4 inch 3, 4
outch 1, a1, 2, a2
outch 1, a3, 2, a4

endin

</CsInstruments>
<CsScore>
; stay up for a week
i 1 0 604800
f 0 604800
e
</CsScore>
</CsoundSynthesizer>
```

It works fine in this state. Just need to set `nchnls = 2` to reproduce the issue.

**Comment by vlazzarini** [comment]
Thanks, I'll look at it. Is there a problem the other way round (2 in, 4 out)?

**Comment by vlazzarini** [comment]
@A1RO I spotted something wrong in the code and fixed it. It's in git now, can you try checking if it's working? I am supposing you are on Linux and can build from git.

**Comment by A1RO** [comment]
I did not try the other way around yet.

I'm on Arch Linux. I'm all setup for git, but never built the csound package myself.
I will follow the instructions on [BUILD.md](https://github.com/csound/csound/blob/develop/BUILD.md) this evening.

**Comment by hlolli** [comment]
If you're using archlinux, you should be able to just copy
https://github.com/archlinux/svntogit-community/blob/packages/csound/trunk/PKGBUILD
and change the revision, then rebuild. I don't use archlinux, but I think
it's even possible to change only the revision and have csound installed
globally on your computer. But I'm not an expert, but I know that archlinux
is very powerful and you shouldn't need to build csound as described in
BUILD.md.

**Comment by A1RO** [comment]
Well, thanks for the tip! That was my initial idea and I will definitely try this first.

With a PKGBUILD in Arch, not only can we change the revision, but we can also set it to always fetch the latest git commit for a given branch.

If it goes smoothly, I will probably submit a PR to document the process in BUILD.md.

**Comment by vlazzarini** [comment]
Let me know if my commit fixes the issue.

**Comment by A1RO** [comment]
Sure, that's the whole point!

**Comment by A1RO** [comment]
Well, that was fun! I modified the official PKGBUILD from the Arch Linux community repo to download csound latest commit. It built without complaining.

Just to make sure, I ran `csound --version` and it does refer to commit b4a2c3577dbddf1479cf565e1b31e99c55c61aac which is indeed the latest.

Sadly, I have to report that the issue described above is still there, with the same behavior.
On the bright side, seems like it didn't break anything either because it still works fine with `nchnls = 4`.

Now that i'm set, maybe we can work on this issue in a separate git branch just to play safe.

**Comment by vlazzarini** [comment]
yep, I run it in a debugger and found my mistake, I had failed to change one other line. Now it doesn't crash, but you need to check whether it does the audio processing (I only have stereo here).

**Comment by A1RO** [comment]
The problem is completely solved with commit 085947f492e9b23116c5e1d644906f3a50a41737.
Thank you very much!

It opens up many possibilities for the `-+rtaudio=jack` plugin.
Since I got a lot of I/O at my disposal, I'd like to test a few more scenarios before closing this issue.
This evening, I will try different combinations of streaming from 8 inputs and 8 outputs.

I'll post the results here when I'm done and hopefully close this issue if everything works as expected.

**Comment by vlazzarini** [comment]
Thanks for checking this. I suppose not many people used more inputs than outputs otherwise we would have spotted this bug before.

**Comment by A1RO** [comment]
For future reference, I tried:

- `nchnls_i=8` with `nchnls=2`
- `nchnls_i=2` with `nchnls=8`
- `nchnls_i=8` with `nchnls=8`

In every case, streaming from/to any of those channels worked just fine.
