### ISSUE TITLE
+= and -= missing for some audio array operations

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#1386]
this works:
 gaArr1[] init 5
 aArr2[] init 5
 gaArr1 *= aArr2

but += or -= instead of *= gives an error:
 gaArr1[] init 5
 aArr2[] init 5
 gaArr1 += aArr2
error:  Unable to find opcode entry for '##addin' with matching argument types:
Found: a[] ##addin a[]
       gaArr1 ##addin aArr2 ...

**Comment by jpffitch** [comment]
The surprise to me is that the first *= case works.  Does it do the right 
thing?

**Comment by joachimheintz** [comment]
i did not check because i needed += which i then used in the form
	gaOut[] init 5
	aOut[] init 5
	gaOut = gaOut + aOut

this worked.  is it not supposed to do so?

**Comment by jpffitch** [comment]
There is indeed no support for +=/-= in the multiple array cases. Will get round to it sometime....

**Comment by jpffitch** [comment]
Just worked out why *= and /= work on arrays.   All clearer now; should simplify the += case, maybe.

**Comment by jpffitch** [comment]
Just committed += and -= for i and k arrays.  Still to do audio arrays

**Comment by joachimheintz** [comment]
wonderful.  once you are done, i will test, and perhaps contribute a 
test csd.

**Comment by jpffitch** [comment]
all committed now.  Testing only mnimal so far

**Comment by joachimheintz** [comment]
i tried this example:

instr 1
  gaArr1[] init 2
  gaArr1[0] poscil .2, 400
  gaArr1[1] poscil .2, 500
  gaArr2[] init 2
  gaArr2[0] poscil .2, 600
  gaArr2[1] poscil .2, 700
endin
instr 2
  aOutArr[] = gaArr1
  aOutArr += gaArr2
  outch p4, aOutArr[p4-1]
endin

with score:
i 1 0 4
i 2 0 2 1
i 2 2 2 2


the sound is ok, but it does not terminate correctly.  this is the 
output, speaking about "corrupted size":

SECTION 1:
Score finished in csoundPerform().
inactive allocs returned to freespace
end of score.		   overall amps:  0.38116  0.38672
	   overall samples out of range:        0        0
0 errors in performance
Elapsed time at end of performance: real: 4.070s, CPU: 0.203s
1378 256 sample blks of 64-bit floats written to dac
corrupted size vs. prev_size

csound command: Aborted

**Comment by jpffitch** [comment]
Your example is not a += failure,  Try replacing the += line with

aOutArr = aOutArr + gaArr2

and t fails.  Will try to fix tat first

**Comment by jpffitch** [comment]
Error in array assignment fixed, and it sees that your example runs OK

**Comment by joachimheintz** [comment]
all seems to run perfect now.
i will send a pull request with my test csd.
this issue can be closed; thanks for the improvement.
