### ISSUE TITLE
Inline array get fails

### ISSUE THREAD

**Issue by hlolli** [csound/csound#1387]
The current error I'm getting, using csound on linux built from https://github.com/csound/csound/commit/53c103ca4b9013c8046813d18eb2b843b86af5d2

```
error: syntax error, unexpected '[', expecting NEWLINE or ','  (token "[")
```

```Csound
<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

sr = 48000
ksmps = 1
nchnls = 2
0dbfs = 1.0

opcode toArray, S[], S
  String xin
  SArray[] fillarray String
  xout SArray
endop

instr SUCCESS
  SArray[] = toArray("Hello world")
  prints SArray[0]
endin

instr FAIL
  String = toArray("Hello world")[0]
  prints String
endin

schedule("SUCCESS",0,0)
schedule("FAIL",0,0)

</CsInstruments>
<CsScore>
e 0 0
</CsScore>
</CsoundSynthesizer>
```

**Comment by kunstmusik** [comment]
This is not implemented nor has it been requested prior to now. We could add it but I would suggest to do so in CS7 as the grammar in the parser3 branch is easier to work with.

**Comment by hlolli** [comment]
Sounds good to me, happy to help if I can

**Comment by hlolli** [comment]
implemented in https://github.com/csound/csound/commit/a50a2bc46a2f6ce5b60597bb8698d2e22557e0e6
