### ISSUE TITLE
slicearray on array of strings doesn't work

### ISSUE THREAD

**Issue by hlolli** [csound/csound#1388]
With web-ide and linux build of https://github.com/csound/csound/commit/53c103ca4b9013c8046813d18eb2b843b86af5d2

fails to slice, it prints
```
new alloc for instr SUCCESS:
iArr2[0] is 1
iArr2[1] is 2
iArr2[2] is 3
new alloc for instr FAIL:
incorrect value for SArr2[0]
incorrect value for SArr2[1]
incorrect value for SArr2[2]
```

If you were to print the values of SArr2 after the slice operation, they'd be empty.

```Csound
<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

sr = 48000
ksmps = 1
nchnls = 2
0dbfs = 1.0


instr SUCCESS
  iArr1[] fillarray 1,2,3,4,5,6,7
  iArr2[] init 3
 ;; EDITED: was slicearray_i (same result with slicearray)
  iArr2 slicearray iArr1, 0, 2

  if iArr2[0] == 1 then
    prints "iArr2[0] is 1\n"
  else
    prints "incorrect value for iArr2[0]\n"
  endif

  if iArr2[1] == 2 then
    prints "iArr2[1] is 2\n"
  else
    prints "incorrect value for iArr2[1]\n"
  endif

  if iArr2[2] == 3 then
    prints "iArr2[2] is 3\n"
  else
    prints "incorrect value for iArr2[2]\n"
  endif
endin

instr FAIL
  SArr1[] fillarray "1","2","3","4","5","6","7"
  SArr2[] init 3
  SArr2 slicearray SArr1, 0, 2

  if strcmp( SArr2[0], "1" ) == 0 then
    prints "SArr2[0] is \"1\"\n"
  else
    prints "incorrect value for SArr2[0]\n"
  endif

  if strcmp( SArr2[1], "2" ) == 0 then
    prints "SArr2[1] is \"2\"\n"
  else
    prints "incorrect value for SArr2[1]\n"
  endif

  if strcmp( SArr2[2], "3" ) == 0 then
    prints "SArr2[2] is \"3\"\n"
  else
    prints "incorrect value for SArr2[2]\n"
  endif
endin

</CsInstruments>
<CsScore>
i "SUCCESS" 0 0
i "FAIL" 0 0
</CsScore>
</CsoundSynthesizer>
```

**Comment by hlolli** [comment]
ok so the implementation is incomplete. So it's resolving to slicearray:k here?

**Comment by gesellkammer** [comment]
No, you asked for `slicearray` yourself. slicearray is always k-time only. You can either fix slicearray_i to take strings also, or change the code to work at k-time (use strcmpk, printsk, SArr2[k(idx)], etc)

**Comment by hlolli** [comment]
If slicearray:i is === slicearray_i, it's just a matter of naming. But slicearray:i on array of numbers shouldn't be behaving differently on strings. In the end, these are array operators with expectations from any other programming paradigm, their contents are to me irrelevant.

**Comment by gesellkammer** [comment]
Maybe you don't understand how dispatch works. There is no slicearray:i. In doubt, `csound -z1` or even better `rg` are the only sources of truth.

**Comment by hlolli** [comment]
the overload of the symbol slicearray if off topic here. There is i[] that works and S[] that doesn't work, simple.

```
slicearray  S[]         S[]iip
slicearray  a[]         a[]iip
slicearray  i[]         i[]iip
slicearray  k[]         k[]iip
```

**Comment by kunstmusik** [comment]
@hlolli I think you're missing that slicearray operates at perf-time and your example is using init-time processing (i.e., prints). Also a confusion that for the function-call syntax the value after the colon is a return type and has no bearing on rate of processing. @gesellkammer 's example works fine with slicearray for me here.  Would suggest that this issue should be changed to "implement slicearray_i with S[] arguments".

**Comment by hlolli** [comment]
We can agree that the SUCCESS case works and it's printing on irate. So it's basically, that the strings are irate and empty on krate? (hence k/i rate string operators)

**Comment by hlolli** [comment]
Ah I aplogize, I didn't notice that I was actually calling slicearray_i here in my example.

**Comment by hlolli** [comment]
4wiw

```csound
instr SUCCESS
  iArr1[] fillarray 1,2,3,4,5,6,7
  iArr2[] init 3
  iArr2 slicearray iArr1, 0, 2

  if iArr2[0] == 1 then
    prints "iArr2[0] is 1\n"
  else
    prints "incorrect value for iArr2[0]\n"
  endif

  if iArr2[1] == 2 then
    prints "iArr2[1] is 2\n"
  else
    prints "incorrect value for iArr2[1]\n"
  endif

  if iArr2[2] == 3 then
    prints "iArr2[2] is 3\n"
  else
    prints "incorrect value for iArr2[2]\n"
  endif
endin
```

works fine too. I shouldn't have made my example with that _i

**Comment by hlolli** [comment]
Notabene

```c
    { "slicearray.i", sizeof(TABSLICE), 0, 1, "i[]", "i[]iip",
      (SUBR) tabslice, NULL, NULL },
    { "slicearray.k", sizeof(TABSLICE), 0, 2, "k[]", "k[]iip",
      (SUBR) tabslice, (SUBR) tabslice, NULL },
    { "slicearray.a", sizeof(TABSLICE), 0, 2, "a[]", "a[]iip",
      (SUBR) tabslice, (SUBR) tabslice, NULL },
    { "slicearray.S", sizeof(TABSLICE), 0, 2, "S[]", "S[]iip",
      (SUBR) tabslice, (SUBR) tabslice, NULL },
```


1 = i-rate
```
    { "slicearray.i", sizeof(TABSLICE), 0, 1, "i[]", "i[]iip",
      (SUBR) tabslice, NULL, NULL },
```

**Comment by gesellkammer** [comment]
You don't seem to want to understand. "i[]" means an init-rate **scalar** array, 1, means that the function tabslice will be called during the init-phase. If you look at the definitions there is no init-time S[] version:

```c
{ "slicearray.S", sizeof(TABSLICE), 0, 2, "S[]", "S[]iip",
      (SUBR) tabslice, (SUBR) tabslice, NULL },
```
This issue should be closed or renamed as @kunstmusik recommended.

**Comment by hlolli** [comment]
```
no init-time S[] version:
```

That's why it fails and hence why #1393 fixes this

**Comment by hlolli** [comment]
I don't think anybody is using slicearray as signal of strings, I fail to find logical meaning for this. Let's agree to disagree in civilized manner :D
