### ISSUE TITLE
[FLTK][bug]: FLsetVal does not work properly with "inverted range" FLsliders

### ISSUE THREAD

**Issue by artificiel** [csound/csound#1394]
An FLslider defined with an inverted range is not properly set by FLsetVal — attached .csd demonstrates the problem. 

```csound
<CsoundSynthesizer>
<CsOptions>
-odac
</CsOptions>
<CsInstruments>

FLpanel "panel", 130, 300, 100, 100
gk_1, gi_1  FLslider  "move\nme", 0, 1, 0, 2, -1, 30, 200, 10, 10
gk_2, gi_2  FLslider  "bug",      1, 0, 0, 2, -1, 30, 200, 50, 10
gk_3, gi_3  FLslider  "ok",       0, 1, 0, 2, -1, 30, 200, 90, 10
FLpanel_end
FLrun

instr MAPPING
  if changed:k(gk_1)==1 then
    printks("%f\n",0,gk_1)
    FLsetVal(1, gk_1, gi_2)
    FLsetVal(1, gk_1, gi_3)
  endif
endin

turnon("MAPPING")

</CsInstruments>
</CsoundSynthesizer>
```

tested with 6.15 on on macOS and linux

**Comment by artificiel** [comment]
seems like there should be a check if min > max for sliders and clip the range appropriately — around line 3000 of https://github.com/csound/csound/blob/ea8f14460c5172cea4f02153c8f724d461893c4b/InOut/widgets.cpp#L2999

**Comment by jpffitch** [comment]
I have attempted a fix but can you check? Or provide a test program? 
Code in github now

**Comment by artificiel** [comment]
i don't have access to a git build right now (running the installer build on a group of pi's this weekend) but above (in the github issue itself) is a test program. 

thanks!

a side question: FLbuttons (probably all widgets) do not seem to interface properly with arrays. i am wondering about the state of widgets -- are they actively supported? is reporting issues (such as array support) useful or is there another GUI that is pushed to be the minimalist one for Csound?

i don't have a particular opinion about GUI toolkits but i like one that works with the barebone csound command line.

**Comment by jpffitch** [comment]
Seems OK bit I am not sure for what I should be looking.

**Comment by jpffitch** [comment]
Can anyone confirm this is fixed?

**Comment by jpffitch** [comment]
Long time without response.  I will close in a couple of weeks if no new evidence
