### ISSUE TITLE
wterrain2 opcode is missing from Csound 6.15

### ISSUE THREAD

**Issue by csounder** [csound/csound#1398]
There seems to be an excellent manPage for the new wterrain2 opcode released in Csound 6.15, but it does not seem to be in the list of new opcodes and the console shows the following when one runs the example .csd

STARTING FILE
Creating options
Creating orchestra
closing tag
Creating score
rtaudio: PortAudio module enabled ...
using callback interface
error: syntax error, unexpected T_IDENT  (token "wterrain2") from file /private/var/folders/_k/2q5495095d53gw9b674tdxdc0000gq/T/csound-tmpkzyLhlQo.csd (1)
 line 24:
>>>asigL wterrain2 <<<
Unexpected untyped word asigL when expecting a variable
Parsing failed due to invalid input!
Stopping on parser failure
cannot compile orchestra

**Comment by jpffitch** [comment]
My error; now fixed in github
