### ISSUE TITLE
conditional with a-rate output

### ISSUE THREAD

**Issue by Oeyvind** [csound/csound#1404]
Bug in conditional processing. 
a1 = (a==b?v1:v2)
Audio rate output is always v1, regardless of the comparison (a==b).
Whereas this still works
k1 = (a==b?v1:v2)

This used to work with audio rate output (for example in 6.10), but does not work in 6.15
Here's a test:

```
instr 1
idir = 1
aphs phasor 1
aphs = (idir == -1 ? 1-aphs : aphs)
out aphs
endin
```
It always ouputs` 1-aphs` (in 6.15), whereas earlier it would be possible to switch between `aphs` and `1-aphs` depending on the value of `idir`.

**Comment by vlazzarini** [comment]
I recall there was a similar ticket and I thought we fixed it. @jpffitch wasn't there one?

**Comment by jpffitch** [comment]
Conditional expressions was completely rewritten as it was wrong.  Still finding bad cases.

⁣Get TypeApp for Android ​

**Comment by vlazzarini** [comment]
A k-rate check seems to select the output

```
instr 1
kval = 0
a1 oscili 0dbfs, A4/2
a2 rand 0dbfs
asig = kval > 0 ? a2 : a1
out asig
endin
```

but there is some sort of distortion added to the signal (it's not a sine wave). So there's a bug of some description here too.

**Comment by vlazzarini** [comment]
I just checked and it seems like the assignment is only copying a single sample (as if it were k-rate).

**Comment by jpffitch** [comment]
probaby usinf the k-rte assign.  Will lok tomorrow

**Comment by jpffitch** [comment]
=.k args:       kval    0
##div.ii args:  #i0     A4      2
oscili.a args:  a1      0dbfs   #i0     -1      0
rand args:      a2      0dbfs   .5      0       0
>.0 args:       #B1     kval    0
ckgoto args:    #B1     __synthetic_300:
=.down args:    #k2     a1      0
kgoto args:     __synthetic_301:
=.down args:    #k2     a2      0
=.k args:       #k2     #k2
=.up args:      asig    #k2
out.a args:     asig
=.k args:       kval    0
##div.ii args:  #i0     A4      2
oscili.a args:  a1      0dbfs   #i0     -1      0
rand args:      a2      0dbfs   .5      0       0
>.0 args:       #B1     kval    0
ckgoto args:    #B1     __synthetic_300:
=.down args:    #k2     a1      0
kgoto args:     __synthetic_301:
=.down args:    #k2     a2      0
=.k args:       #k2     #k2
=.up args:      asig    #k2
out.a args:     asig


worse than Victor thought.  It ignores the possibility of a-rate expressions
If it is not init time it must be k-rate.

Time to look at the code

**Comment by jpffitch** [comment]
Believed fixed; does not notice the error case of
a1 =  (kvar>0) ? a2 : kval

That needs more thought....
