### ISSUE TITLE
python lib install does not respect CMAKE_INSTALL_PREFIX

### ISSUE THREAD

**Issue by jwaldmann** [csound/csound#1406]
I did
```
cmake .. -DCMAKE_INSTALL_PREFIX=/opt/csound/csound-6.15.0
make
```
but `make install` still wants to write
```  
"/usr/local/lib/python2.7/dist-packages/_csnd6.so".
```
This is dangerous with `sudo make install`.

**Comment by jwaldmann** [comment]
when I add    `-DBUILD_PYTHON_INTERFACE=false`, cmake output looks promising 
```
...
-- PYTHON_LIBRARY: /usr/lib/x86_64-linux-gnu/libpython2.7.so                                                         
-- BUILD_PYTHON_INTERFACE is disabled.  
```
but make install still wants to write
```
  "/usr/local/lib/python2.7/dist-packages/ctcsound.py".
```

**Comment by vlazzarini** [comment]
yes, the Python2 path is independent of CMAKE_INSTALL_PREFIX, it is set to the Python site packages directory. However, you can override that by setting the option directly

```
-DPYTHON_MODULEINSTALL_DIR="/some/where"
```
