### ISSUE TITLE
How to pipe output to stdout into a pipe to ffmpeg?

### ISSUE THREAD

**Issue by cirosantilli** [csound/csound#1408]
Ubuntu 20.04, Csound 6.13.0, ffmpeg 4.2.4.

I try to output to pipe:

```
csound -W -o stdout xanadu.csd | ffmpeg -f wav -i - xanadu.ogg
```

but it fails with:

```
[wav @ 0x56093284c6c0] invalid start code d[163][3][0] in RIFF header
xanadu-cat.wav: Invalid data found when processing input
```

Any clues?

The problem seems to be with `csound` or some missing CLI option:

```
csound -W -o stdout xanadu.csd > xanadu-stdout.wav
csound -W -o stdout xanadu.csd | cat > xanadu-stdout.wav
```

since the first above works but the second does not with ffmpeg.

More details: https://stackoverflow.com/questions/64970503/how-to-pipe-csound-output-to-ffmpeg-for-conversion-without-an-intermediate-file

**Comment by jpffitch** [comment]
I suspect the issue is that .wav files require a length value in the header which can only be writen at tr end of the render with a seek back to the start.  The piping requires non seekable format.  

The work around is to use raw or IRCAM (?) fornat to write to the pipe.

**Comment by jpffitch** [comment]
>No response in monhs.  Will close issue shortly if no further comment

**Comment by cirosantilli** [comment]
Thanks John, we can close.
