### ISSUE TITLE
sflooper: add iflag

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#1411]
sflooper It is a cross between sfplay and flooper2.
can the iflag option be made available (as in sfplay) and can this be added as an option in sflooper?

Text in the manual regarding sfplay:
'When iflag = 0, inotenum sets the frequency of the output according to the MIDI note number used, and xfreq is used as a multiplier. When iflag = 1, the frequency of the output, is set directly by xfreq. This allows the user to use any kind of micro-tuning based scales. However, this method is designed to work correctly only with presets tuned to the default equal temperament. Attempts to use this method with a preset already having non-standard tunings, or with drum-kit-based presets, could give unexpected results.'

**Comment by vlazzarini** [comment]
This is done now, but I've no idea how to test it. Can you?

ar1, ar2 sflooper ivel, inotenum, kamp, kpitch, ipreindex, kloopstart, kloopend, kcrossfade \
      [, istart, imode, ifenv, iskip, iflag]

**Comment by tjingboem** [comment]
yes great, i will test soon!

**Comment by tjingboem** [comment]
yes it works well in my tests.

aL,aR sflooper ivel, 60, kamp*ivel, ifreq, 0, 0, .2, .05, 0, 0, 0, 0, 1
takes the soundfont preset sounds that belong to index 60 (in this case), and ifreq decides at which frequency those samples will be played.

Here an example where an octave is divided into 24 

https://user-images.githubusercontent.com/6670911/109858939-b591d180-7c5c-11eb-91aa-af045f2cab51.mp4

thanks!

**Comment by vlazzarini** [comment]
great, would you do me a favour and update the man page?

**Comment by tjingboem** [comment]
sure, i will one of these days.
I will update the example as well to reflect this update.
