### ISSUE TITLE
Csound no output and CsoundQT crash

### ISSUE THREAD

**Issue by nzfs** [csound/csound#1418]
anytime i hit run, or i try to change the input or output in configuration or trying to test audio, csoundqt just crushes. the problem seems to be with the audio configuration, since it don't crash with the RT audio module set to null, but i don't know what else to do. i'm using csound 6.15.0 and csoundqt 0.9.8.1, i'm running windows 10. 
for example, if i click the three dots to change de input device, it crashed. the same with the output. i try to test audio setup, it crashed. hit run, crashes. it's very frustrating.
![image](https://user-images.githubusercontent.com/31911456/103043493-c850a180-455b-11eb-8319-ac0ccfe6bbc0.png)
running in terminal gives this:
![image](https://user-images.githubusercontent.com/31911456/103043509-d0a8dc80-455b-11eb-94c7-17cd35396fb0.png)

when rt audio is set to null, this is the output:
![image](https://user-images.githubusercontent.com/31911456/103043523-db637180-455b-11eb-8605-18d20af30569.png)

any idea what the problem could be? thanks.

**Comment by vlazzarini** [comment]
You will need to open an issue in the CsoundQT project. This tracker is for Csound issues only.

**Comment by joachimheintz** [comment]
i don't think so, and i suggested him to ask the csound community for 
help, because the problem occurs when he uses the "run in terminal" 
option in csoundqt.  it seems to be an issue with audio modules on 
windows, perhaps something is missing for him, and somone from the 
csound windows users might be able to help.

**Comment by jpffitch** [comment]
a message to the list might help but not the issues

⁣Get TypeApp for Android ​

**Comment by joachimheintz** [comment]
right.  actually this was my suggestion, but i think he is snot on the 
list.  i will do it.

**Comment by vlazzarini** [comment]
Well, I think since the crash is occurring in CsoundQT when changes configuration, then it should be seen there. If the it is run on the terminal and shows a crash when run (I see no indication of that), then we take it here.

**Comment by gogins** [comment]
Similar problems have occurred when there are conflicting versions of the
PortAudio shared library or even conflicting CPU architectures. Look for
other versions of the PortAudio DLL and move them away for testing.

Regards,
Mike

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com
