### ISSUE TITLE
FLTK opcodes inside of UDOs don't return their widget's value

### ISSUE THREAD

**Issue by spinnylights** [csound/csound#1421]
If an FLTK opcode is called inside of a UDO, it renders properly, but the value held by the widget doesn't seem to make it out of the UDO. The following .csd demonstrates:

```csound
<CsoundSynthesizer>
<CsOptions>
</CsOptions>
; ==============================================
<CsInstruments>

sr    = 48000
ksmps = 1
0dbfs = 1

#define VALW    #  50   #
#define VALH    #  20   #

#define SLIDW   # 300   #
#define SLIDH   #  15   #

#define VALX    #  20   #
#define SLIDX   # 100   #
#define Y       #  20   #

#define MIN     #   0   #
#define MAX     #   1   #
#define DEFAULT #   0.5 #
#define SCALE   #   0   #

opcode Slider, k, 0
    idisp FLvalue "", $SLIDW, $SLIDH, $VALX, $Y
    khandle,ihandle FLslider "Test", $MIN, $MAX, $SCALE, 5, idisp, \
                          $SLIDW, $SLIDH, $SLIDX, $Y
    FLsetVal_i $DEFAULT, ihandle

    xout khandle
endop

#define PANELW # ($SLIDW + $SLIDH + $VALX + $VALW + 40) #
#define PANELH # ($SLIDH * 4) #

FLpanel "FLTK UDO Test", $PANELW, $PANELH, 0, 0, 3, 1
    gkslider Slider
FLpanelEnd

FLrun

instr 1
    printk 1, gkslider
endin

</CsInstruments>
; ==============================================
<CsScore>
i1 0 z
</CsScore>
</CsoundSynthesizer>
```

When run in my environment (Arch Linux kernel v5.9.13, csound 6.15), the `printk` statement in `instr 1` shows a value of `0.0` for `gkslider` regardless of the apparent value of the slider in question. I haven't tested this for every FLTK widget, although my guess is that the results would be similar.

I took a brief look at the code to see if I could write a patch, but this behavior seems to have something to do with how UDOs are scoped or the like, which seems foolhardy to share a patch for without consulting anyone first (if that would really be necessary). During initialization, the FLTK widget is set to use a callback that's passed a pointer to the opcode struct and uses it to store its current value inside the struct, allowing Csound to fish the value out soon after. Since this code doesn't provoke a crash, I'm guessing that pointer stays valid for the duration of the program, but doesn't ever actually get connected to `gkslider` as you would hope.

It's possible that the FL* opcodes aren't meant to support being used in this manner; I know the docs say that they "must be called only once per session" and that they should be "place[d]...in the header section of an orchestra, before any instrument." That doesn't seem to me to explicitly rule out use in a UDO necessarily, but maybe that's what's intended. If so, though, it would be really nice if that requirement could be changed, because as it is code using those opcodes can get very repetitive, increasing the difficulty of maintenance and so on. Obviously the FL* statements can be generated programatically from the outside or the like, but using UDOs in this manner seems less cumbersome.

**Comment by jpffitch** [comment]
Runnng wit full debug messages U get
....
***opcode=Slider thread=7 pftype=k

WARNING: Slider: perf-time code in global space, ignored
FLpanel args:   "FLTK UDO Test" 425     60      0       0       3       1
0
Slider args:    gkslider        0
FLpanelEnd args:
FLrun args:
FLvalue args:   idisp   ""      300     15      20      20
FLslider args:  khandle ihandle "Test"  0       1       0       5       idisp
300     15      100     20
FLsetVal_i args:        0.5     ihandle
xout args:      khandle
printk args:    1       gkslider        0       0       0       0

so you have krate operations in instrument 0, but instr 0 does not have a perf time.

In this case you di not want the UDO to be k rate and the k is rally a devclaration in the FLTK susystm.

Sounds lke what you dneed is a macro not a UDO

**Comment by spinnylights** [comment]
Well, yeah, in the real-world situation this example was abstracted out from I ended up using a templating system ([ERB](https://docs.ruby-lang.org/en/3.0.0/ERB.html)) to generate the CSD I wanted. I brought this up more because I thought it would be nice if those FLTK opcodes could be used in a perf-time UDO, since they're more powerful and cleaner than macros. From what you're saying, though, maybe that would be impractical—I didn't realize the FL* opcodes are done in instr 0 and thus can't use perf-time operations (although I guess it's unsurprising).

**Comment by vlazzarini** [comment]
I am closing this now, for two reasons: the issue was explained as a code problem; FLTK opcodes are reaching end of life (not fully working across platforms) and will be moved out of the project in version 7. We are not dedicating development time to them.

**Comment by tjingboem** [comment]
The fact that the FLTK opcodes will be moved out with Csound 7 is pretty important for the Csound Manual Team.
We will prioritize the replacement  of 32 examples that make use of the FLTK code so that there are none left when Csound 7 is released.

**Comment by vlazzarini** [comment]
They will be moved out of the csound repository into the opcodes repo, that is what I meant, like the other opcodes with dependencies. Just note that they don't work on MacOS anymore (and likely will never do), so what you are doing is exactly right.

**Comment by tjingboem** [comment]
Will the FLTK manual pages be moved to the Deprecated section?

**Comment by vlazzarini** [comment]
That's a decision up to you manual editors. The status of these opcodes is as I noted (broken on MacOs, work elsewhere). They may be maintained further but not as part of the core library from Csound 7 onwards.
