### ISSUE TITLE
Csound-api: csoundIsNamedGEN always returns 0

### ISSUE THREAD

**Issue by hlolli** [csound/csound#1422]
`csoundIsNamedGEN` which is documented to return the length of the NAMEDGEN string https://csound.com/docs/api/group___t_a_b_l_e.html#ga1c63376d3ae88b5fef3b55b24a51b9b7 which looks to me to be a handy thing to know before calling `csoundGetNamedGEN`, seems to always return 0. I may be misunderstanding the use of this api function but the c code looks dead simple https://github.com/csound/csound/blob/d1c186c63b44020ae364edb41ee0d21467e6381b/Engine/fgens.c#L3380-L3388 and it seems it should do as documented.

Here's a reproduction of this behavior using the c-api.

```c
#include <stdio.h>
#include <csound/csound.h>


const char* csd = "<CsoundSynthesizer>\n"
  "<CsInstruments>\n"
  "sr=44100\n"
  "ksmps=64\n"
  "0dbfs=1\n\n"
  "instr 1\n"
  "prints \"Hello namedGEN!\\n\"\n"
  "endin\n"
  "</CsInstruments>\n"
  "<CsScore>\n"
  "f 1 0 8192 \"exp\" 0 15 0\n"
  "i 1 0 2\n"
  "</CsScore>\n"
  "</CsoundSynthesizer>\n"
  ;

int main(int arg, char** argv) {
  void* thread;

  csoundInitialize(CSOUNDINIT_NO_ATEXIT);

  CSOUND* csound = csoundCreate(NULL);

  csoundSetOption(csound, "-odac");
  csoundCompileCsdText(csound, csd);
  csoundStart(csound);

  int kr = csoundGetKr(csound);
  int cnt = 0;

  while (csoundPerformKsmps(csound) == 0) {
    if (cnt == kr) {
      printf("the word 'exp' has 3 chars, csoundIsNamedGEN says it's: %d characters long\n",
             csoundIsNamedGEN(csound, 1));
    }
    cnt++;
  }
  return 0;
}
```

**Comment by vlazzarini** [comment]
Looks like the named gen list is null. Not sure why yet

**Comment by vlazzarini** [comment]
I am not sure what this function is supposed to do but

```
n->genum
```

gives the numeric GEN, not the function table number.

**Comment by vlazzarini** [comment]
I just looked at the docs and it says

"Checks if a given GEN number num is a named GEN if so, it returns the string length (excluding terminating NULL char) Otherwise it returns 0."

So it works as expected.

**Comment by hlolli** [comment]
I'm not sure where you are seeing GEN01 in my example,

```
"f 1 0 8192 \"exp\" 0 15 0\n"
```

it's GENEXP and I'd expect 3 to be returned as per the documentation. It's not working as expected.

**Comment by vlazzarini** [comment]
You are asking for GEN 1

csoundIsNamedGEN(csound, 1)

**Comment by hlolli** [comment]
Isn't this table number 1 (which in the examle is GENexp)? Otherwise, `csoundIsNamedGEN(csound, "exp")` would be a strange thing to ask the csound-api of?

**Comment by hlolli** [comment]
Ok so if I understand correctly, a named gen has a name and a number, in "exp"'s case, there's a number behind it, which, if I were to pass that number, then I'd get 3 for the strlen of exp?

**Comment by vlazzarini** [comment]
yes, it asks for a GEN number not a table number. There is no way of finding out what GEN a given table has been filled with.

**Comment by hlolli** [comment]
For an api user, is there ever a time where the number of a namedgen would cross paths. I wasn't specifically trying to find the GEN of a table, but `csoundGetTableArgs` https://csound.com/docs/api/group___t_a_b_l_e.html#ga7c21eb3d747ffa067bda29018eff66aa sound like it would. So I guess there I would discover from the first element of the array, what number lies behind the name "exp".

Thanks for clarifying. It was the concept of namedgen having a number that was in my way of understanding the purpose of the api, which I'm trying to mimic in wasm.

**Comment by vlazzarini** [comment]
you are right, that should return it as p4 of an f-event.
