### ISSUE TITLE
Insecure Permissions

### ISSUE THREAD

**Issue by Mohad0** [csound/csound#1428]
Hi Csound team,

After installing Csound from https://github.com/csound/csound/releases/download/6.15.0/csound-windows_x86_64-6.15.0-installer.exe, I noticed that the files in "C:\Program Files\Csound6_x64\bin" have insecure permissions. Using this vulnerability, attackers can modify dll and exe files in the mentioned folder. It allows local users to replace the files with arbitrary code to escalate their privileges. I hope you check this link for more details: https://cwe.mitre.org/data/definitions/732.html

**Comment by jpffitch** [comment]
I assume this is windows specific?

**Comment by Mohad0** [comment]
That is true @jpffitch

**Comment by vlazzarini** [comment]
@stekyne do you know what this is about?

**Comment by stekyne** [comment]
@vlazzarini I don't think there is an issue. The file permissions are currently set to "users-modify" so anyone in the user group on Windows can read/write/modify the files. 

https://github.com/csound/csound/blob/93aa455d27f69e264a96777674c7d4b3ea93a899/installer/windows/csound6_x64.iss#L89

It's defined by the installer. Making it more restrictive might just lead to other user issues which I'm sure we'd like to avoid. I don't think it's worth trying to fix anything here.

**Comment by vlazzarini** [comment]
OK thanks, closing ticket
