### ISSUE TITLE
cmake checks for python path even with BUILD_PYTHON_OPCODES=OFF

### ISSUE THREAD

**Issue by yurivict** [csound/csound#1437]
Here https://github.com/csound/csound/blob/develop/CMakeLists.txt#L219 it checks for python path without regard for ```BUILD_PYTHON_OPCODES```.

Is python actually used during build other than for the python opcodes?

**Comment by hlolli** [comment]
It's not called during build. Only checked for.

**Comment by yurivict** [comment]
It find an outdated python version 2.7 when it is installed. This attracts attention.

Can this check be limited to when ```BUILD_PYTHON_OPCODES=ON```?

**Comment by hlolli** [comment]
Out of curiousity. Is python 2.7 discoverable during the build? Because if you don't have python 2.7 it should be harmless. If you're packaging csound, you'd be safer so be explicit and set it to off. The problem here is perhaps many non tech people are relying on these defaults, so it would be better to find best of both worlds solutions when possible.

**Comment by yurivict** [comment]
> Out of curiousity. Is python 2.7 discoverable during the build?

Yes, it discovers python-2.7, even when ```BUILD_PYTHON_OPCODES=OFF```.

**Comment by hlolli** [comment]
Ok, I feel I've set this flag many times when installing locally with correct behavior. You're on freeBSD in this case (judging from your name)? Also what version are you running?

**Comment by yurivict** [comment]
I am on FreeBSD, running version 6.15.0.

There is a port option ```PYTHON```. It enables python when set and doesn't provide python when not set. But it begins to look for and discovers some random python version - this looks unclean.

**Comment by vlazzarini** [comment]
Python is used for interfaces too, maybe the search is on when the python interface option or whatever is set. I am speculating since I don't have the code in front of me.

**Comment by vlazzarini** [comment]
I've changed the code and it only checks the path if it needs to build the interface.
