### ISSUE TITLE
Please use ${CMAKE_INSTALL_PREFIX} instead of hardcoded /usr/local in cmake files

### ISSUE THREAD

**Issue by yurivict** [csound/csound#1438]
Here list(APPEND CMAKE_REQUIRED_INCLUDES "/usr/local/include"), here https://github.com/csound/csound/blob/develop/Opcodes/CMakeLists.txt#L307 and everywhere else.

**Comment by hlolli** [comment]
I agree that this is a bad practice. But if you do define --prefix or CMAKE_INSTALL_PREFIX, it will be respected and the installation should remain pure. If that weren't the case, it wouldn't be possible to package it to nixpkgs, which forbids any impurity.

https://github.com/NixOS/nixpkgs/blob/a70d31b11f984ae4635f4369b683b9735941b63b/pkgs/applications/audio/csound/default.nix

nix defines from cmake hook an $out variable which corresponds to the --prefix, and in csound's case you have $our/lib $out/bin and $out/shared after the installation.

**Comment by hlolli** [comment]
Also, your example is for osx. Who cares :D (osx has /Library and global stuff around, hardcoded and annoying)

**Comment by yurivict** [comment]
Ok, thanks.
