### ISSUE TITLE
confused over new --limiter

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#1439]
i read this in the manual:
--limiter,
Use a limiter when outputing audio samples. The limiting value is 0.5 or the value given in the range [0,1].

When i try this limiter, (that seems to have fixed settings), i do hear that it works quite heavily, but when you check the Csound output the sample range is unchanged when using the limiter or not.
I can see the advantage of having the real sample value range, and that i can adjust the settings of the sound that is too loud accordingly, so this must be expected behavior.  Please check the video:

https://user-images.githubusercontent.com/6670911/108700703-4b17bd80-7507-11eb-8c60-62d4fd870f77.mp4

But, is it possible to give it other value settings than the fixed 0.5? I personally prefer 0.8-0.9, for me 0.5 is too much limiting for me and would like to be able to give it another value.

**Comment by jpffitch** [comment]
Also I the manual --limiter=0.9

I think 0.5 is to low also.

⁣Sent from TypeApp ​

**Comment by tjingboem** [comment]
ah yes, i had a space in --limiter =0.9. Must be --limiter=0.9
then it works nicely
thanks :)
