### ISSUE TITLE
while() not possible in functional style

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#1441]
i can write **if** in functional style, but not **while**.

this works:
instr if_works
 ia = 0
 if(ia==0) then
  print(ia)
 endif
endin

but this ...
instr while_does_not_work
 ia[] = fillarray(1,2,3)
 indx = 0
 while(indx<3) do
  print(indx)
  indx += 1
 od
endin

... results in parser error:

error: syntax error, unexpected T_IDENTB  (token "while") from file /home/jh/Desktop/test.csd (1)
 line 19:
>>> while <<<
Parsing failed due to invalid input!
Stopping on parser failure
cannot compile orchestra

not sure it is an intentional difference, or a small bug?

--Csound version 6.15 (double samples) Feb 28 2021
[commit: 19f101ec482766cf9cc170d6958454109cd7d3c8]

**Comment by fggp** [comment]
You need to add a space between while and the condition:

<CsoundSynthesizer>
<CsOptions>
  -o dac
</CsOptions>
<CsInstruments>
instr if_works
  ia = 27
  if (ia==27) then
    print(ia)
  endif
endin

instr while_does_work
  ia[] = fillarray(10, 20, 30)
  indx = 0
  *while (indx<3) do*
    print(ia[indx])
    indx += 1
  od
endin
</CsInstruments>
<CsScore>
i "if_works" 0 0.1
i "while_does_work" 0.1 0.1
</CsScore>

Regards

François

Le dim. 28 févr. 2021 à 11:44, joachimheintz <notifications@github.com> a
écrit :

**Comment by joachimheintz** [comment]
i know, but not for the if().
i meant this difference.

best -
	joachim

**Comment by fggp** [comment]
I see. Then the question is: should the if opcode have a functional
version? In my opinion, the if ... end is a structure that could eventually
return a value of the type of the instruction executed inside the
structure. More completely, if cond then expr1 else expr2 would return a
value of the type of expr1 or expr2, provided that expr1 and expr2 have the
same type. This is what is usually done in functional programming. But, if
you consider if(cond) as a functional version of the if opcode then the
returned type is boolean which seems useless to me.

So the if cond then (with a space between the if and the condition) seems
more appropriate to me.

Regards

François


Le dim. 28 févr. 2021 à 12:43, joachimheintz <notifications@github.com> a
écrit :

**Comment by jpffitch** [comment]
François is saying what I thought when I introduced while.  The if() form is just for backward compatibility with the Vercoe parser and in my opinion "if" should be followed by a space as it is not a function.

⁣Sent from TypeApp ​

**Comment by joachimheintz** [comment]
makes sense for me.  thanks for the explanation!
