### ISSUE TITLE
nstrstr segfault when instrument doesn't exist..

### ISSUE THREAD

**Issue by rorywalsh** [csound/csound#1442]
`nstrstr` causes a segfault if the instrument does not exist. Could it be set up to return an error string? 

```
instr 1
    event_i "i", 2, 0, 1
endin

instr 2
    SName nstrstr 3
    prints SName 
endin

schedule(1, 0, 1)
```

**Comment by jpffitch** [comment]
Fixed  If no syucj istr returns "" an empty string
