### ISSUE TITLE
soundin doesn't work on Bela

### ISSUE THREAD

**Issue by giuliomoro** [csound/csound#1446]
(Bela uses libcsound (https://github.com/csound/csound/blob/develop/Bela/main.cpp))

On Bela, ~~diskin2~~ `soundin` does not work : this simple patch does not emit any sound:

```
<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>
sr       = 44100
ksmps    = 16
nchnls   = 2
0dbfs    = 1

instr    1 ; Stereo delay with normal and cross-feedback

ain      soundin  "sp_hellorcb.aif" ; NOT WORKING
outs1 ain
outs2 ain

endin

</CsInstruments>
<CsScore>
i1  0 5
e
</CsScore>
</CsoundSynthesizer>
```

I tracked it down to the fact that `*(p->kTranspose)` is never set to anything different than 0, which in turn means `p->pos_frac_inc`  and `p->pos_frac` stay zero throughout.

This seems to fix it:
```
--- a/OO--- a/OOps/diskin2.c
+++ b/OOps/diskin2.c
@@ -405,6 +405,7 @@ static int32_t diskin2_init_(CSOUND *csound, DISKIN2 *p, int32_t stringname)
     }
     p->pos_frac_inc = (int64_t)0;
     p->prv_kTranspose = FL(0.0);
+    *(p->kTranspose) = 1;
     /* allocate and initialise buffers */
     p->bufSize = diskin2_calc_buffer_size(p, MYFLT2LONG(p->BufSize));
     n = 2 * p->bufSize * p->nChannels * (int32_t)sizeof(MYFLT);
```

However, I understand that `soundin` works on other platforms and - even though I don't know about the opcode API - I could infer from the `diskin2.c` that this value is supposed to be set elsewhere (where?), but - at least on Bela - this doesn't happen. I am therefore wondering whether this is the manifestation of a deeper problem somewhere else in the code base, which may be related to `libcsound` or Bela's use of it. I would be interested in hearing any ideas you may have on the subject.

**Comment by vlazzarini** [comment]
I think that is a byproduct of the fact that things are running in separate threads. The value of *p->kTranspose is taken at performance time, when it might be too late. Perhaps your initialisation is the right thing to do.

**Comment by vlazzarini** [comment]
So I am looking at the code and I think I need a better fix. The value of *p->kTranspose needs to be passed atomically to the thread. Let me review it and then you can test it.

**Comment by vlazzarini** [comment]
Can you pull and test it now? I've pushed a fix.

**Comment by giuliomoro** [comment]
This works, thanks a lot.
Could you please - for my own curiosity - point me to the place where `p->kTranspose` is set?

**Comment by vlazzarini** [comment]
actually, it is not, in the case of `soundin` because the transpose parameter is not there. I missed that, you were not using `diskin` or `diskin2`. If you were,

```
a1 diskin "file.wav", ktp
```
the ktp variable in the csound instrument is where *p->kTranspose is pointing at.
Must look at soundin and see if all is ok there.

**Comment by vlazzarini** [comment]
By the way the title of the ticket says "diskin2" not "soundin". Can you confirm diskin2 works?

**Comment by giuliomoro** [comment]
> By the way the title of the ticket says "diskin2" not "soundin".

uops! It seems I swapped them several times in reporting the issue (I must have gotten confused after looking at the source code, where all is done as `diskin2`).
So to recap: `soundin` was not working, `diskin2` was working. 

> Can you confirm diskin2 works?

yes. Now they both work.

> EDIT3: and you can see why it does not work for 'soundin' in async mode:

yeah noticed the stashing ... didn't investigate it, though ... it seemed too deliberate to be a mistake!

> the ktp variable in the csound instrument is where *p->kTranspose is pointing at.

good to know, thanks!

**Comment by vlazzarini** [comment]
Ok, so I'm closing this now.
