### ISSUE TITLE
Gentoo QA Notice: The following shared libraries lack a SONAME

### ISSUE THREAD

**Issue by fordfrog** [csound/csound#1449]
i just enabled java interface on [csound live ebuild](https://github.com/gentoo/gentoo/blob/master/media-sound/csound/csound-9999.ebuild) on gentoo distro and got a qa issue:

```
 * QA Notice: The following shared libraries lack a SONAME
 * /usr/lib64/lib_jcsound6.so
```

could you please fix it?

**Comment by vlazzarini** [comment]
fixed cmake to do that.
