### ISSUE TITLE
superfluous operations with arrays

### ISSUE THREAD

**Issue by gesellkammer** [csound/csound#1450]
Currently in place operations for array elements (e.g. "gabuses[0] += asig") are not possible. The following code:

```csound
gabuses[] init 4 

instr 10 

  asig vco2 0.1, 1000
  gabuses[0] = gabuses[0] + asig
endin
```

Produces superfluous operations, as --verbose shows:

```
vco2 args:      asig    0.1     1000    0       0       0       0
##array_get.a args:     #a0     gabuses 0
##add.aa args:  #a1     #a0     asig
=.a args:       #a2     #a1
##array_set.a args:     gabuses #a2     0
```

which amounts to:

```
#a0 = gabuses[0]
#a1 = #a0 + asig
#a2 = #a1          ; ???
gabuses[0] = #a2
```

**Comment by vlazzarini** [comment]
Any movement on this? Can @kunstmusik  @jpffitch ?

**Comment by jpffitch** [comment]
I do not think this is a bug.  There is inefficiency in the compilation yes.  Cs7 array concepts are very different and may incorporate such changes
