### ISSUE TITLE
Plugin.h get_csound() inaccessible base

### ISSUE THREAD

**Issue by 1bpm** [csound/csound#1451]
Commit 314140473fc031eda8e1b809e88e17863a91e4d4 introduced get_csound() to plugin.h , but this results in the error 'CSOUND_' is an 'inaccessible base of csnd::Csound' when compiling plugins which use that member function.
I've patched my plugin.h from
`Csound : CSOUND {`
to
`Csound : public CSOUND {`

which makes get_csound() work as expected, and have been using this for a while, but not sure if this is the best way to address it.

**Comment by vlazzarini** [comment]
You should not need this modification. You can get a pointer to CSOUND and go from there.
I tested it here with the code

```
    CSOUND *ppp = (CSOUND *) csound->get_csound();
    ppp->GetSr(ppp);
```

**Comment by rorywalsh** [comment]
What would be the ramifications of changing to `public CSOUND`?  `get_csound()->GetSr()` seems far more accessible than:

```
CSOUND *ppp = (CSOUND *) csound->get_csound();
ppp->GetSr(ppp);
```

**Comment by vlazzarini** [comment]
That works too with no changes (except that your code example wasn't quite complete)

```
csound->get_csound()->GetSr(csound->get_csound());
```

I want to keep a mediated access to CSOUND to make the whole thing more robust and use C++ compile-time errors to minimise runtime trouble. I understand both of you know what you are doing, but not everyone may be the same,

**Comment by rorywalsh** [comment]
Thanks Victor. I rarely have any need to access the CSOUND struct in this framework. I have to say, I'm knocking great mileage out of this framework at the moment ;)

**Comment by vlazzarini** [comment]
it's great, that's the only way we can test it to get rid of bugs and poor design ideas,

**Comment by rorywalsh** [comment]
The no inputs/outputs hack is a little rough around the edges, but it works, albeit undocumented. I guess there is no cleaner way around that issue?

**Comment by vlazzarini** [comment]
You mean the special base classes for no inputs etc?

**Comment by 1bpm** [comment]
> You should not need this modification. You can get a pointer to CSOUND and go from there.
Ah OK, thank you Victor, I didn't realise that I wasn't using it correctly!

**Comment by rorywalsh** [comment]
Right now if I need 0 outputs, I reverse the ins/outs template args and use
outargs as my inputs. Is there a special base class for this kind of thing?
I remember discussing it, but I don't recall it being resolved? Sorry, I
should have started a new ticket for this..

**Comment by 1bpm** [comment]
AFAIK that's what the InPlug class is for (only inputs).

**Comment by rorywalsh** [comment]
Great. I guess I need to look in the source code for this? It's not listed
in the Docs pages? Or maybe I'm looking in the wrong place?

https://vlazzarini.github.io/cpof/annotated.html

**Comment by 1bpm** [comment]
I became aware of it via the mailing list when it was added in Sept 2019 (before that I was doing what you mentioned ie swapping in/out template args), not sure if it's in any docs, definitely in the source though!

**Comment by vlazzarini** [comment]
Sorry I have never updated those docs, there's lots of new things I guess.
