### ISSUE TITLE
chuap opcode - possible error in manual

### ISSUE THREAD

**Issue by johannphilippe** [csound/csound#1454]
```
aI3, aV2, aV1 chuap kL, kR0, kC1, kG, kGa, kGb, kE, kC2, iI3, iV2, iV1, ktime_step
```

In the example, kC2 and kC1 are inverted. kC2 is passed as 3rd argument, and kC1 as 8th. 
I looked at this source :  https://github.com/csound/plugins/blob/master/chua/ChuaOscillator.cpp
And it seems to me that kC2 is the 3rd argument and kC1 is the 8th. I'm not sure though. 

If I'm true,  the opcode description would be 
```
aI3, aV2, aV1 chuap kL, kR0, kC2, kG, kGa, kGb, kE, kC1, iI3, iV2, iV1, ktime_step
```

**Comment by gogins** [comment]
I'll check it out sometime today.

Regards,
Mike

**Comment by gogins** [comment]
Opcode input parameters in the source code:

  // Circuit elements.
  MYFLT *L_;
  MYFLT *R0_;Sig
  MYFLT *C2_;
  MYFLT *G_;
  MYFLT *Ga_;
  MYFLT *Gb_;
  MYFLT *E_;
  MYFLT *C1_;
  // Initial values...
  MYFLT *I3_;
  MYFLT *V2_;
  MYFLT *V1_;
  MYFLT *step_size_;

Signature in the Csound Reference Manual:

aI3, aV2, aV1 chuap kL, kR0, kC1, kG, kGa, kGb, kE, kC2, iI3, iV2, iV1,
ktime_step

Yes, you are correct! kC1 and kC2 should be swapped in the manual in order
to match the code. The other parameters in the manual are OK.

The parameter order in my code is the same as that in the original MatLab
source code. I didn't want to monkey with it.

I suspect that the parameter values in the examples are correct.

Thanks,
Mike

-----------------------------------------------------
Michael Gogins

Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by johannphilippe** [comment]
Yes that means the parameters values in the example are correct. Only the signature one the manual had an issue.

By the way, thank you for this opcode, it is great.

**Comment by gogins** [comment]
You're welcome!

Regards,
Mike

**Comment by tjingboem** [comment]
could (one of) you please check and see if my proposed changes for the manual page are correct?
https://github.com/csound/manual/issues/528

In the example itself, i took out all 'ignore' pfields p21/p25. Values _are_ given for these pfields, but they are not actually used in the example as far as i can see.
Also, to get a clearer overview, i ordered the pfields in rows.

**Comment by johannphilippe** [comment]
Another error in manual is that kGb is explained twice, while kE is not explained (in the arguments description). 
About your correction of the  signature, it seems to be right. 

And for the example, I also noticed that p4, p6, p7 and p16 aren't used. So I removed them from the example. I think it may be a bit more clear and readable in this way : 

```
<CsoundSynthesizer>
<CsOptions>
-odac
</CsOptions>
; ==============================================
<CsInstruments>

sr	=	44100
ksmps	=	32
nchnls	=	2
0dbfs	=	1

gibuzztable ftgen 1, 0, 16384, 10, 1

instr 1	
	
    istep_size    =       p4

    iL            =       p5
    iR0           =       p6
    iC2           =       p7
    iG            =       p8
    iGa           =       p9
    iGb           =       p10
    iE            =       p11
    iC1           =       p12
    iI3           =       p13
    iV2           =       p14
    iV1           =       p15

    iattack       =       0.02
    isustain      =       p3
    irelease      =       0.02
    p3            =       iattack + isustain + irelease
    iscale        =       1.0
    adamping      linseg  0.0, iattack, iscale, isustain, iscale, irelease, 0.0
    aguide        buzz    0.5, 440, sr/440, gibuzztable
    aI3, aV2, aV1 chuap   iL, iR0, iC2, iG, iGa, iGb, iE, iC1, iI3, iV2, iV1, istep_size 
    asignal       balance aV2, aguide
    as2           balance aV1, aguide

    ao1 = dcblock2(adamping * asignal)

    outs ao1, ao1
endin

</CsInstruments>
; ==============================================
<CsScore> 
//             time_step      kL           kR0         kC2              kG            kGa           kGb          kE          kC1           iI3                     iV2                     iV1
; torus attractor ( gallery of attractors ) 
i 1 0 20       .1            -0.00707925   0.00001647  100              1             -.99955324    -1.00028375  1          -.00222159     -2.36201596260071       3.08917625807226e-03    3.87075614929199   
; heteroclinic orbit
i 1 + 20       .425           1.3506168    0           -4.50746268737  -1             2.4924        .93          1           1             -22.28662665            .009506608              -22.2861576            
; periodic attractor (torus breakdown route)
i 1 + 20       .05            0.00667      0.000651    10              -1             .856          1.1          1           .06           -20.200590133667        .172539323568344        -4.07686233520508      
; torus attractor (torus breakdown route)'
i 1 + 20       0.05           0.00667      0.000651    10              -1             0.856         1.1          1           0.1            21.12496758             0.03001749              0.515828669            

</CsScore>
</CsoundSynthesizer>

```

**Comment by johannphilippe** [comment]
BTW I don't know what those two commented lines were used for : 
```
; sys_variables = system_vars(5:12); % L,R0,C2,G,Ga,Gb,E,C1 or p8:p15
; integ_variables = [system_vars(14:16),system_vars(1:2)]; % x0,y0,z0,dataset_size,step_size or p17:p19, p4:p5
```

**Comment by tjingboem** [comment]
yes,- less is more...better, thanks.

that list should be corrected, true:
kL -- Inductor L

kR0 -- Resistor R0

kC1 -- Capacitor C1

kG -- Resistor G

kGa -- Resistor V (nonlinearity term)

kGb -- Resistor V (nonlinearity term)

kGb -- Resistor V (nonlinearity term)


AND it would be nice to have all the parts in the scheme to reflect this list. kC1 -- Capacitor C1, that is clear, but i _assume_ kR0 -- Resistor R0 = R in the scheme.

![Screenshot from 2021-04-05 14-29-24](https://user-images.githubusercontent.com/6670911/113574144-cf3b8580-961b-11eb-88bf-576b22c466fd.png)

**Comment by johannphilippe** [comment]
You're right about the R0. I propose this list. Please tell me if I'm wrong about the annotations of kG, kGa, kGb : 

kL -- Inductor L (L1 in the scheme)

kR0 -- Resistor R0 (R in the scheme)

kC1 -- Capacitor C1

kG -- Resistor G (active resistor)

kGa -- Resistor V (nonlinearity term of the active resistor)

kGb -- Resistor V (nonlinearity term of the active resistor)

kE --  Size of the piecewise discontinuity simulating the active resistor

**Comment by tjingboem** [comment]
building on that, i hope somebody with more knowledge on the topic can confirm:

kL -- Inductor L (L1 in the scheme)

kR0 -- Resistor R0 (R in the scheme)

kC1 -- Capacitor C1

kC2 -- Capacitor C2

kG -- Resistor G (active resistor) = R1 in the scheme?

kGa -- Resistor V (nonlinearity term of the active resistor) = one of the R2

kGb -- Resistor V (nonlinearity term of the active resistor) = the other one of the R2

kE -- Size of the piecewise discontinuity simulating the active resistor

It seems to me that OPA goes into self-osculation with amplification of 290 on the positive side and the negative side. R1 goes to ground, so i think R (= R0) is the active resistor.
?

**Comment by johannphilippe** [comment]
No it's probably not R0. You can see that in the equation of the active resistor : 
f(V1) = Gb V1 + - (Ga - Gb)(|V1 + E| - |V1 - E|)
It doesn't use R0 value. 
OPA is what I think is actually the active resistor, which is not a real component (it's purely theoretical). Active resistor behave like an OPA. And this one has the particularity to be nonlinear.

**Comment by johannphilippe** [comment]
![chua_circuit](https://user-images.githubusercontent.com/36574555/113587762-8beb1200-962f-11eb-858e-b5312e8c4815.png)

**Comment by tjingboem** [comment]
How about this?

R is now known as R0 in the diagram:

![Ontwerp zonder titel (1)](https://user-images.githubusercontent.com/6670911/113591162-da9aab00-9633-11eb-81b8-7b5cf5b92d6c.png)

The list will be:

kL -- Inductor L (L1 in the diagram)

kR0 -- Resistor R0 (R0 in the diagram)

kC1 -- Capacitor C1

kC2 -- Capacitor C2

kG -- Resistor G (active resistor, R1 in the diagram)

kGa -- Resistor V (nonlinearity term of the active resistor, one of the R2's in the diagram)

kGb -- Resistor V (nonlinearity term of the active resistor, one of the R2's in the diagram)

kE -- Size of the piecewise discontinuity simulating the active resistor

**Comment by johannphilippe** [comment]
I agree with that. Perheaps it would be good to just add to kG 
kG -- resistor G (part of the active resistor, R1 in the diagram)

**Comment by tjingboem** [comment]
@johannphilippe, can you please check: https://csound.com/manual/chuap.html
is this all up to date you think?

**Comment by johannphilippe** [comment]
All good. I just noticed I forgot to keep this comment, at the top of the score 
```
;        Adapted from ABC++ MATLAB example data.
```

Thank you for taking time on it !

**Comment by tjingboem** [comment]
okay, i love good documentation!!

added ;        Adapted from ABC++ MATLAB example data. to top of score
and also
added adamping to:
 outs asignal*adamping, asignal*adamping

As far as i am concerned, someone can close this issue- i do not have that kind of power...

**Comment by johannphilippe** [comment]
Great ! I agree, it can be closed !

**Comment by gogins** [comment]
The G parameter is the time step, which is needed to get the same slope of
the piecewise discontinuity from Ga and Gb for all sampling rates.

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by tjingboem** [comment]
This might be something to add to:
kG -- Resistor G (part of the active resistor, R1 in the diagram)
?

**Comment by johannphilippe** [comment]
Yes. Chua is quite a complex oscillator (difficult to learn), and I think i would be very helpful to put as much information as we can in the manual. It is particularly relevant to add this kind of information since time step is often relative to digital implementation, rather than to the "circuit" itself

**Comment by tjingboem** [comment]
i added Michael's remark to kG.

**Comment by vlazzarini** [comment]
Can we close this or move it to the manual tracker? I don't think it belongs here.

**Comment by tjingboem** [comment]
the documentation is updated and correct.

**Comment by tjingboem** [comment]
you can close this issue- i can not
