### ISSUE TITLE
turnoff2_click

### ISSUE THREAD

**Issue by prhmi** [csound/csound#1458]
Hello
There is an issue in turnoff2 opcode, when it turns off instruments it interrupts other instrument. for example in below code I hear a click in instrument 3 sound, but if I swap the instr 2 and 3 it has no problem
Here is the code:
instr 1
	turnoff2   2, 0, 0
endin

instr 2
endin

instr 3
 aout poscil 0.2, 500
 out aout,aout
endin

and the score:
i 1 2 1
i 2 0 4
i 3 0 4

from attached you can see the result in screenshots.
thanks !
![Screenshot_2021-04-05_12-59-58](https://user-images.githubusercontent.com/77784179/113671308-0a18da00-966b-11eb-8b77-dbf0c626d1be.png)
![Screenshot_2021-04-05_12-37-35](https://user-images.githubusercontent.com/77784179/113671312-0b4a0700-966b-11eb-8675-4c34deba8682.png)

**Comment by vlazzarini** [comment]
Thanks. I can reproduce it. Looks like execution gets halted by 1 kcycle. Any ideas @jpffitch ?

**Comment by jpffitch** [comment]
No obvious ideas but it certainly looks like a k-cycle not happening.  Just finished my todo list for today so will look now.

**Comment by vlazzarini** [comment]
We found the bug and have a solution, just trying to work out if there are no further implications.
