### ISSUE TITLE
Better support for monophonic instruments.

### ISSUE THREAD

**Issue by jackxbritton** [csound/csound#1463]
Hey folks, writing monophonic (specifically MIDI-controlled) instruments is not very easy. Here's a pattern I've been using in my projects:

```csound
gacps init 0
gaenv init 0

massign 1, "midihandler"
instr midihandler

	iamp ampmidi 1
	gaenv linsegr 0, 0.1, iamp, 0.25, 0
	xtratim 0.5 ; Necessary for the envelope to zero out.
	gacps init cpsmidi()

	; Shut off on the next note so the envelope generator restarts!
	kstatus, kchan, kdata1, kdata2 midiin
	if kstatus == 144 && kchan == midichn() then
	turnoff
	endif

endin

alwayson "synth"
instr synth

	aenv tonex gaenv, 100  ; Remove clicks from the envelope.
	acps tonex gacps, 100  ; Pitch slide.

	aosc oscil gaenv, gacps
	outs aosc, aosc

endin
```

I'd like to add better support for this. The solution should fulfill the following requirements:

* The two instruments and global variables above could be replaced with one instrument.
* Allow use of existing envelope generating opcodes.

My idea for a solution is:

* An i-time opcode that makes an instrument get its timing / release information from some global per-MIDI channel or per-instrument source. This way, opcodes like `line` would restart when the instrument is "retriggered".
* A k-time opcode to pull the last pressed MIDI note from a channel.

I'd be willing to take the lead on this. My questions:

1. Is there an existing solution to my problem?
2. Does the proposed solution seem like a good one? Also, would Csound be receptive to a PR containing these features?
3. Does this look very hard to implement?

**Comment by rorywalsh** [comment]
Or you can do (courtesy of Iain McCurdy):

```
gkactive init 0     ; number of active instances of note
giMaxPolyphony  = 1 ; polyphony limit

instr 1
    ; polyphony control...
    gkactive init i(gkactive) + 1   ;increment note counter
    if gkactive>giMaxPolyphony then ;if polyphony is exceeded (through the addition of new note)
        turnoff                        ;remove this note
    endif
    
    krel release                    ;if note held = 0, if note released = 1
    ktrig trigger krel,0.5,0        ;when release flag crosses 0.5 upwards, i.e. note has been released... 
    if ktrig==1 then                ;
        gkactive = gkactive - 1        ;...decrement active notes counter
    endif

    ; make a sound...
    iCPS  cpsmidi
    iAmp  ampmidi 1
    kEnv madsr .1, .4, .5, .1
    a1 vco2 kEnv*iAmp, iCPS
    outs a1, a1
endin
```
If out of the box support was to be added for monophonic MIDI control I think it would be best added as an extra argument to `massign`. That way all synths could swap between monophonic and polyphonic playback without users having to write any extra code.

**Comment by vlazzarini** [comment]
@jackxbritton I appreciate your point and your contributions, but this is not the place for this type of discussion. Please use the Csound or Csound-developers mailing list for this. You will get more attention from users and developers there.  We want to reserve the issues tracker for bugs and particular enhancement requests. So I'll close this now, but I hope you can continue engaging with the community via the discussion channels.

**Comment by jackxbritton** [comment]
No worries, thanks Victor. I'll follow up there
