### ISSUE TITLE
calls to 'python' don't work on stock Ubuntu

### ISSUE THREAD

**Issue by joel-binarybrain** [csound/csound#1468]
The `interfaces/CMakeLists.txt` file includes an invocation of `python` which won't work out of the box on recent versions of Ubuntu because its python packages install only explicitly named python2 or python3 binaries (and no symlink to point `python` to one of these). See [here ](https://launchpad.net/ubuntu/focal/+package/python-is-python3) for details.

**Comment by joel-binarybrain** [comment]
I forgot to add, it's the one on line **142**.

**Comment by vlazzarini** [comment]
We should consider disabling the build of the Python interface altogether since it's based on the EOL Python 2.

Would that solve the problem?

**Comment by vlazzarini** [comment]
@fggp what do you think? Maybe time to let csnd6 go?

**Comment by gogins** [comment]
I think it should go.

Regards,
Mike

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by fggp** [comment]
Well Python 2 is not supported anymore since january 2020. So this makes
sense.

Francois

**Comment by kunstmusik** [comment]
+1 would rather see all effort put into ctcsound and csnd6 phased out.

**Comment by vlazzarini** [comment]
removed all Python2 interface build and that includes the offending line.
