### ISSUE TITLE
High CPU usage in daemon mode on macOS

### ISSUE THREAD

**Issue by droussel** [csound/csound#1469]
Hi,

When starting CSound with either `--port` or `--daemon`, the process jumps to 100% cpu right away.
OS used : `macOS 11.2.1 (Big Sur)`
Csound info : 
```
--Csound version 6.15 (double samples) Nov 20 2020
[commit: 18c2c7897425f462b9a7743cee157cb410c88198]
libsndfile-1.0.28
```

Console output:

`❯ csound --port=1234
0dBFS level = 32768.0
--Csound version 6.15 (double samples) Nov 20 2020
[commit: 18c2c7897425f462b9a7743cee157cb410c88198]
libsndfile-1.0.28
WARNING: could not open library '/Library/Frameworks/CsoundLib64.framework/Versions/6.0/Resources/Opcodes64/libfluidOpcodes.dylib' (-1)
WARNING: could not open library '/Library/Frameworks/CsoundLib64.framework/Versions/6.0/Resources/Opcodes64/librtjack.dylib' (-1)
scoreless operation
rtaudio: PortAudio module enabled ...
using callback interface
rtmidi: PortMIDI module enabled
Elapsed time at end of orchestra compile: real: 0.001s, CPU: 0.001s
sorting score ...
	... done
Elapsed time at end of score sort: real: 0.001s, CPU: 0.001s
UDP server started on port 1234
graphics suppressed, ascii substituted
0dBFS level = 32768.0
orch now loaded
audio buffered in 1024 sample-frame blocks
writing 2048-byte blks of shorts to test.aif (AIFF)
SECTION 1:
`

<img width="246" alt="image" src="https://user-images.githubusercontent.com/130655/116839164-327af200-ab9f-11eb-8fc6-fd997dd16523.png">

**Comment by vlazzarini** [comment]
you need `-odac` since the default is to write to file. If you start Csound with no instruments it will spin as quickly as it can writing the files and it will consume all CPU it can to do the job. You will also see a test.aiff that will quickly fill your disk. Note that `--port=N` or `--daemon` does not imply `-odac`.

**Comment by droussel** [comment]
Sorry for that, still a total beginner at CSound.  I do indeed now have a 13GB test.aif file in there!  🤦‍♂️
