### ISSUE TITLE
resample opcode

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#1481]
don't know much about licensing, but can we use zitaresample and turn it in an opcode?
![Screenshot from 2021-05-25 10-10-35](https://user-images.githubusercontent.com/6670911/119462965-91b4c800-bd41-11eb-8992-da0eb36e8c20.png)
https://kokkinizita.linuxaudio.org/linuxaudio/zita-resampler/resampler.html

**Comment by gogins** [comment]
In its own repository, yes. Not in the regular Csound repository.

Best,
Mike

**Comment by tjingboem** [comment]
just saw that Csound has the GNU Lesser General Public License. An opcode 'zitaresamp' could only exist in somebody's repo, not even the csound plugins repo (GNU Lesser General Public License).
Okay, good to know- thanks!
