### ISSUE TITLE
(m)(x)adsr have DC offset

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#1485]
when comparing (m)(x)adsr opcodes, i noticed that the notes produced have a slight DC offset
![Screenshot from 2021-06-01 13-43-52](https://user-images.githubusercontent.com/6670911/120318189-dad7bf80-c2df-11eb-8eb1-c8b179d61ba7.png)

--Csound version 6.15 (double samples) May 12 2021

**Comment by joel-binarybrain** [comment]
Can you post the score please?

**Comment by tjingboem** [comment]
yes, sure. I was now thinking: perhaps it has to do with the filter, and not so much with the adsr- not sure
It is the example adsr-group that can be found in the manual: https://csound.com/manual/adsr.html

The meaning of this group example is that the user can decide what he/she needs; adsr, xadsr, madsr and mxadsr are compared.

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac    ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o adsr-group.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

; by Menno Knevel - 2021

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

; both amplitude and filter use same ADSR curves 
instr 1		 	 
kenv	adsr	.01, .5, .5, p4    	; linear envelope 
asig	vco2	kenv, 110			; A+D+S+R = p3 	
asig	rezzy	asig, 500+(kenv*1000), 10	; same curve but scaled 
		outs	asig, asig	 
endin

instr 2	; midi behavior	 	 	 
kenv	madsr	.01, .5, .5, p4		; linear envelope
asig	vco2	kenv, 110			; A+D+S = p3, then go into Release stage 		
asig	rezzy	asig, 500+(kenv*1000), 10	; same curve but scaled  
		outs	asig, asig			
endin

instr 3 	 	 
kenv	xadsr	.01, .5 , .5, p4    ; exponential envelope
asig	vco2	kenv, 110			; A+D+S+R = p3 	 
asig	rezzy	asig, 500+(kenv*1000), 10	; same curve but scaled 
		outs	asig, asig
endin

instr 4	; midi behavior 	 
kenv	mxadsr	.01, .5 , .5, p4	; exponential envelope
asig	vco2	kenv, 110			; A+D+S = p3, then go into Release stage 	 
asig	rezzy	asig, 500+(kenv*1000), 10	; same curve but scaled 
		outs	asig, asig			
endin

</CsInstruments>
<CsScore>
s
i1 1 2 .01	; same notes for everyone!
i1 5 . .5
i1 9 . 1.5
s
i2 1 2 .01
i2 5 . .5
i2 9 . 1.5
s
i3 1 2 .01
i3 5 . .5
i3 9 . 1.5
s
i4 1 2 .01
i4 5 . .5
i4 9 . 1.5
e
</CsScore>
</CsoundSynthesizer>
```

**Comment by joel-binarybrain** [comment]
It's the filter. If you set the resonance parameter to 1 then the offset mostly goes away. Alternatively, you could use a different filter to avoid the problem completely.

**Comment by tjingboem** [comment]
mmm...do you think it makes sense to open an issue for the filter or is this behavior normal for filters in general when a higher resonance value?

**Comment by joel-binarybrain** [comment]
This is just my opinion but I don't think it should be changed. The offset isn't bad and has probably always been there and I doubt it could be resolved without otherwise affecting the character of the filter.

**Comment by tjingboem** [comment]
I think you're right. 
Anyway, the adsr does not have the DC offset, so i'll close the issue.
Thanks for checking this!
