### ISSUE TITLE
tbvcf seems blatantly wrong. 

### ISSUE THREAD

**Issue by 01GOD** [csound/csound#1486]
The seemingly very wrong tbvcf.c filter emulation has seemingly been spreading through FOSS music frameworks. Recently noticed the issue when trying an AudioKit port and then tried it in CsoundQT also. 
The main initial problem is that the filter resonance tends to do what it should do as the co frequency goes up, as it goes down instead. So it "whistles" as the co frequency goes down in that emulation. That is blatantly wrong. It should do something similar as the co frequency is near the top val (as it does in the actual roland product). 

I am not currently an audio filter math adept (that I know of anyway), so recommending it be updated by somebody that is. Contacted Hans Mikelson to notify of the issue yesterday as he was supposedly the historical author. 

If any need an example of how the filter sounds when resonance and co frequency knobs are at maximum on that filter, I can send one. The main genre of music built on that sound generally sweeps the co knob up and down though, so most of the popular songs of that genre are examples of that. The peak of most of those songs is literally the co and reso knobs at maximum vals. 

Thanks in advance to whatever skilled filter emulation programmer can update that to make it sound proper. That is something that should be in an archive of musical technology like Csound seems to intend to be.

**Comment by jpffitch** [comment]
tbvcf cannot be chsngd as it may be i use.  We are pen to a simil fiter if 
nyone writes one.

**Comment by 01GOD** [comment]
Sadly it seems to be a very wrong emulation though. Thus, some things in
downstream projects such as CsoundQT sound silly. Maybe that current
emulation can be adjusted while maintaining the same var names and ranges
to ensure compatibility with legacy projects.

Can introduce an engineer skilled at filter maths that I can collaborate
with on making a replacement filter emulation and/or an update to that
filter emulation?

**Comment by rorywalsh** [comment]
I think the point John is making is that although it might sound silly in
comparison to how it is supposed to sound, anyone who used it in a project
obviously did so because they actually liked how it sounded. If we change
it now we will potentially destroy their work. So a new opcode would
probably be a better option.

**Comment by 01GOD** [comment]
I understand that conceptually, but some may have used it in FOSS audio frameworks (like CsoundQT and AudioKit that have libraries of filters) unwittingly expecting that was how the original sounded and behaved. If suddenly the filter emulation sounds and behaves correctly, but requires some minor adjustments in downstream apps, most would likely be grateful rather than upset. 

That said, either a new emulation or an update to that one are certainly welcome. And, as I said before: I can collaborate
with an audio filter maths expert on making a replacement filter emulation and/or an update to that if such an audio filter maths expert is introduced by any on the Csound project or elsewhere. 

As a sidenote, modern software engineers are relatively accustomed to dealing with framework updates necessitating updates to the internal structure of apps. That is why package managers include ways of limiting updates to certain maximum version numbers of a framework, etcetera. Ask an Apple platform software engineer that has built Swift apps how often Apple has broken apps in the past decade. Certainly NOT saying to be like Apple, but simply saying that modern best practices have protections in place to protect apps from automatically integrating third party framework updates that have drastic changes. Obviously also wise to use versioning software such as Github.

**Comment by vlazzarini** [comment]
This opcode should not be changed: it is as it is. The "fix" is to provide an alternative filter alongside it. We're happy to take PRs on this. I'm closing this.
