### ISSUE TITLE
Build libsndfile

### ISSUE THREAD

**Issue by OxySound** [csound/csound#1497]
While using the ```download_and_build_libsndile.sh```

The last step of the file is failing my understand is this built from source why would it be missing I'm using linux ubuntu.

```
flac.c:34:10: fatal error: 'FLAC/stream_decoder.h' file not found
#include        <FLAC/stream_decoder.h>
```

**Comment by jpffitch** [comment]
You need the flac devel package I think.   Needed with libsndfile. 

⁣Sent from TypeApp ​
