### ISSUE TITLE
bin attribute in <CsScore> element is not working.

### ISSUE THREAD

**Issue by gogins** [csound/csound#1498]
The following error messages are printed when I run this Csound file: [bin_test.txt](https://github.com/csound/csound/files/6751509/bin_test.txt)

```
>cd "/home/mkg" && csound "bin_test.txt" --simple-sorted-score -odac:plughw:1,0 -m163 -+msg_color=0
time resolution is 1000.000 ns
0dBFS level = 32768.0
--Csound version 6.17 beta (double samples) Jul  1 2021
[commit: d606868f4524eda9f78c6147b68de38bd7697c3b]
libsndfile-1.0.28
UnifiedCSD:  bin_test.txt
STARTING FILE
Creating options
Creating orchestra
closing tag
Creating score


; This is a Python-generated score.

; sine
f 1 0 16384 10 1

i 1 0  9 .01	;vibrato
i 1 10 .  1
i 1 20 . 1.414	;gong-ish
i 1 30 5 2.05	;with "beat"
e

cannot open /tmp/csond-pbYu4K.sco
and cannot remove /tmp/csond-pbYu4K.sco
Reading CSD failed (No such file or directory)... stopping
end of score.		   overall amps:      0  
	   overall samples out of range:        0
1 errors in performance
Elapsed time at end of performance: real: 0.034s, CPU: 0.001s
vst3_host_t::~vst3_host_t.
>Exit code: 1
```
Inspection of the code reveals inconsistencies. The temporary files are generated _without_ a filename extension:
```
mkg@mkg-G55VW:~/csound$ ls -ll /tmp
total 52
-rw------- 1 mkg  mkg     0 Jul  1 21:07 csond-lyMvBK
-rw------- 1 mkg  mkg     0 Jul  1 21:08 csond-p33Q9m
-rw------- 1 mkg  mkg     0 Jul  1 21:11 csond-pbYu4K
-rw------- 1 mkg  mkg     0 Jul  1 20:59 csond-XOIEkf
mkg@mkg-G55VW:~/csound$ 

```
 but then Csound tries to load the files _with_ a filename extension:
```
cannot open /tmp/csond-pbYu4K.sco
and cannot remove /tmp/csond-pbYu4K.sco
```
Evidently, this is due caused in Top/one_file.c when Csound uses mktemp on Linux and the MacOS and _tempnam on Windows. There is no filename extension on the generated filepath. Instead, the filename extension is tacked onto the filepath without, however, renaming the actual temporary file.

Presumably, this was done because there is no counterpart of mkstemps, which would create a temporary file with a filename extension, for Microsoft C++.

**Comment by gogins** [comment]
I will do this in a branch and issue a pull request when finished.

**Comment by gogins** [comment]
The existing code wants to use mkstemp or mktemp in order to have no chance of the filename being hijacked between the closing of the temp file and the creation of a new file with the generated filepath.

This in turn is done because Csound always creates a file from scratch using csoundFileOpenWithType.

And this cannot be done using a low level file descriptor, but it can be done with a stream FILE object using freopen, but only if csoundFIleOpenWithType is modified.

It's probably not wise to use the rename function.

**Comment by vlazzarini** [comment]
Thanks for looking into this. This feature was working until very recently, which changes broke it?

**Comment by gogins** [comment]
This issue was opened based on a misunderstanding. It works fine as is. Nothing to merge.

My problem was I thought that the code in the <CsScore> element with the bin attribute just needed to write to stdout. No, it needs to write to the temporary filename supplied by Csound.

**Comment by gogins** [comment]
It is not broken, I was using it wrong. It works fine.

Regards
Mike
