### ISSUE TITLE
getseed

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#1499]
In creating an example for getseed, we found a possible error in getseed.

The output of getseed is pretty boring, in that it takes the seed value itself and just adds 1. The seed value = p4.

Here is the csd:

```
<CsoundSynthesizer>
<CsOptions>
-odac -d

</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs = 1

instr 1
seed p4
kseed getseed
printk2 kseed
endin

</CsInstruments>
<CsScore>
i1 0 0.1 1
i1 0.5 0.1 3
i1 1 0.1 300
e
</CsScore>
</CsoundSynthesizer>
```

The output:

```
new alloc for instr 1:
 i1     2.00000
B  0.000 ..  0.500 T  0.500 TT  0.500 M:  0.00000  0.00000
 i1     4.00000
B  0.500 ..  1.000 T  1.000 TT  1.000 M:  0.00000  0.00000
 i1   301.00000
B  1.000 ..  1.100 T  1.100 TT  1.100 M:  0.00000  0.00000
```

**Comment by jpffitch** [comment]
You ave not looked at th real use.  Ir the PRNG is seeded from te clock 
then the seed is not immediately available except via getseed.

The +1 is to avoud thpromple of seeding with zero.

**Comment by jpffitch** [comment]
...and of course the seed is updated as the random opcode(s) are called. 
So one can capture the state to restart the PRNG at a previous point if 
for example one wanted to repeat the sequence from an audio approved 
value.

**Comment by tjingboem** [comment]
yes, now i  believe i understand the idea behind getseed.
This will lead to a good example, showing its meaning.
Thanks for clarifying!
