### ISSUE TITLE
String get truncated by one character

### ISSUE THREAD

**Issue by mjmogo** [csound/csound#1500]
I've written a UDO to concatenate an array of strings into one string. It also allows for a separator string that is inserted between the strings. If you pass a string with a length of 0 for the separator, rather than doing nothing, it removes one character from the input string. I'm able to get around this by checking for the length of the separator string before concatenating the strings.

This is the output from the test program.

SECTION 1:
[0] 'one'
[1] 'two'
[2] 'three'
'ontwthree' 'one, two, three'
Score finished in csoundPerform().

```
<Cabbage>
form caption("Untitled") size(400, 300), guiMode("queue"), pluginId("def1")
keyboard bounds(8, 158, 381, 95)
</Cabbage>
<CsoundSynthesizer>
<CsOptions>
-n -d -+rtmidi=NULL -M0 -m0d --midi-key-cps=4 --midi-velocity-amp=5
</CsOptions>
<CsInstruments>
; Initialize the global variables. 
ksmps = 32
nchnls = 2
0dbfs = 1

opcode strarray, S, S[]S
    SArr[], SSep xin
    SStr = ""
    iLen lenarray SArr
    iCount = 0
    while iCount < iLen do
        SStr strcat SStr, SArr[iCount]
        if iCount < (iLen - 1) then
            SStr strcat SStr, SSep
        endif
        iCount = iCount + 1
    od
    xout SStr
endop

instr 1
    SArr[] fillarray "one", "two", "three"
    SVal1 strarray SArr, ""
    SVal2 strarray SArr, ", "
    
    iLen lenarray SArr
    iCount = 0
    while iCount < iLen do
        prints "[%d] '%s'\n", iCount, SArr[iCount]
        iCount = iCount + 1
    od
    prints "'%s' '%s'\n", SVal1, SVal2
endin 


</CsInstruments>
<CsScore>
;causes Csound to run for about 7000 years...
i 1 0 0
;f0 z
</CsScore>
</CsoundSynthesizer>

```

**Comment by vlazzarini** [comment]
ok, maybe not related to UDOs. Could you try making a version without the UDO, putting the code in the instrument and only using an empty string as a separator?

I suspect strcat, because if the problem was with passing the string array to an UDO, then you would see a problem with other terminators.

**Comment by mjmogo** [comment]
```
instr 2
  Sout = "one"
  Sout strcat Sout, ""
  puts Sout, 1
endin
schedule(2,0,0)
```

outputs "on"


Joachim Heintz put this together...

**Comment by rorywalsh** [comment]
Does the k-rate version work - strcatk?

**Comment by vlazzarini** [comment]
ok bug in strcat. thx.

**Comment by mjmogo** [comment]
It appears to only be 'strcat'...

**Comment by jpffitch** [comment]
Only happens if the destination string is t he same as a source

instr 3
  Sout = "one"
  Sout1 strcat Sout, ""
  puts Sout1b, 1
endin
schedule(3,1,0)

**Comment by jpffitch** [comment]
I think I fixed it.  in github now
