### ISSUE TITLE
csound wasm getTable/tableCopyOut cant read tables with size > 1024

### ISSUE THREAD

**Issue by docb** [csound/csound#1504]
feature/webaudio-csound c8bd89682a08729c400bc131bd8febad100c1599
getTable/tableCopyOut gives a
`RuntimeError: index out of bounds` if the size is > 1024 may be lower.
To reproduce:
Change in wasm/browser/tests/tests.js the size of the table to 2048 and run the tests.

L156 `f 1 0 2048 -2 0 1 1 2 3 5 8 13`
and
L353 `assert.equal(2048, await csoundObj.tableLength(1), "The length of the table counts as 2048");`

**Comment by hlolli** [comment]
this doesn't seem to be an issue anymore, I just tried on latest branch with 2048 length and not 8

![2022-11-08 22 21 52](https://user-images.githubusercontent.com/6074754/200678195-d7581734-250b-4716-8331-161793a52a8e.png)

note the table length log entry in the console on the right
![2022-11-08 22 22 45](https://user-images.githubusercontent.com/6074754/200678273-3e016e0d-b4a8-4d15-9346-a36214457233.png)
