### ISSUE TITLE
Csound exe downloads are being halted by Microsoft SmartScreen

### ISSUE THREAD

**Issue by zingus** [csound/csound#1510]
csound-x86_64-6.16.2.exe and csound-x86_64-6.16.1.exe and probably others are being reported as false positives by windows smartscreen. Might be because they tracked something in a dependency, there is a process to report it as safe as the author and ask for clarifications, someone should go trough it.

![image](https://user-images.githubusercontent.com/251631/128939327-046f91e6-3007-4abd-8ee3-0a85e7155485.png)

**Comment by stekyne** [comment]
I'm pretty sure it's because we don't sign the installers. Maybe we could get a cert to sign it in the CI. It's essentially a false positive which can be ignored.
