### ISSUE TITLE
https://csound.com/download.html Windows downloads don't work

### ISSUE THREAD

**Issue by zingus** [csound/csound#1511]
Links to "64bit Full Installer v6.16.2" and "64bit Binaries v6.16.2" on the csound.com site lead to 404 errors on github. 

A simple workaround would be pointing them to https://github.com/csound/csound/releases/

![image](https://user-images.githubusercontent.com/251631/128940682-a17782b9-4cdf-4a91-b2ec-53dcf70bce99.png)

Not entirely sure this the right place to report this, if you know of a better place, please tell me.

**Comment by vlazzarini** [comment]
fixed. Tickets for the website can be open at the csound.github.io repository tracker
