### ISSUE TITLE
pvsdisplay output

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#1520]
When trying to improve the example for pvsdisplay, i noticed that the output contains a lot of the same messages until note end, and i wondered why this was. 

This is a screenshot of part of the Csound output:
![Screenshot from 2021-09-03 10-11-06](https://user-images.githubusercontent.com/6670911/131973170-dfabbe78-8c2b-42f2-8e56-beb3cfe99805.png)

This is the csd:

```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
; Audio out   Audio in
-odac  ;;;realtime audio out
; For Non-realtime ouput leave only the line below:
; -o pvsdisp.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100 
ksmps = 32 
0dbfs  = 1 
nchnls = 2

instr 1

asig soundin "fox.wav"  ;select a soundifle
fsig pvsanal asig, 1024, 256, 1024, 1
     pvsdisp fsig, 10

endin

</CsInstruments>
<CsScore>
i 1 0 3
e
</CsScore>
</CsoundSynthesizer>
```

I still have the FLTK installed here on Linux, and using --displays as a command line flag, i did not get all these lines of output

https://user-images.githubusercontent.com/6670911/131973479-5c7c36e1-12b1-44e6-b45c-5e7bdfe380d5.mp4

**Comment by vlazzarini** [comment]
In this case, pvsdisp is displaying the spectrum to the terminal in ASCII and at the end it's all zeros so there is nothing to display, just the messages that accompany each plot. If you set asig = 0 you will see only messages.
It's the way it is. With FLTK you'd get a graphical plot and the messages will also be there at the top.

**Comment by tjingboem** [comment]
Clear, thanks.

And yes, i do see the messages of the FLTK display
![Screenshot from 2021-09-03 10-48-13](https://user-images.githubusercontent.com/6670911/131978022-12516ddc-641a-426b-9be0-cd8d1c189bca.png)


I think i will add a note about this on the manual page, so the user knows 'there is nothing wrong...'

**Comment by tjingboem** [comment]
And i see that 'iprd' is missing in the syntax

![Screenshot from 2021-09-03 10-53-59](https://user-images.githubusercontent.com/6670911/131979058-3bced89a-0db9-4d6e-84b6-7717c006173d.png)

**Comment by vlazzarini** [comment]
It doesn't apply here because the source is an fsig, so it prints the frames every hopsize. The iprd is probably there because the man page was a copy-and-paste from pvdisp where that parameter makes sense. You can remove it from the manual.

**Comment by tjingboem** [comment]
of course, i understand.
I'd like to add to the Description your remark:'it prints the frames every hopsize" as well.
Like:
"This opcode will display a PVS signal fsig. It prints the frames every hopsize. Uses X11 or FLTK windows if enabled, else (or if -g flag is set) displays are approximated in ASCII characters."

**Comment by vlazzarini** [comment]
sounds good to me
