### ISSUE TITLE
The STKSitar opcode can create a buildup of clipped samples as illustrated by the attached csd file

### ISSUE THREAD

**Issue by umlaeute** [csound/csound#1526]
as i don't have time right now to look into this myself, so I'm forwarding an oldish (6 years!) bug-report from Debian (here's the [original bugreport](https://bugs.debian.org/759190)), that appears to still be present in Csound-6.16

> The following CSD produces unexpected output: this may be a problem with
> Csound, or STK, or both -- I'm filing this as a Csound bug because that's the
> application I'm using when I experience the problem.
> 
> The CSD has two descending tone sequences played with the STKSitar opcode. The
> duration of each note is 0.4 seconds and they are played 0.1 seconds apart, so
> there should be no more than 4 notes playing simultaneously. Towards the end of
> the first descending sequence, the volume shoots up dramatically, creating a
> great deal of distortion.
> 
> There is a pause of 1.0 seconds before the second descending sequence, which
> should be adequate for all notes from the first sequence to complete. Yet when
> the second sequence plays, the distortion occurs almost immediately, on notes
> which played without issue during the first tone sequence.
> 
> It appears that some sort of buffer is building up and not being flushed
> adequately, but that's just speculation.
> 

find the CSD in [STKSitar_overflow.zip](https://github.com/csound/csound/files/7169214/STKSitar_overflow.zip)

**Comment by vlazzarini** [comment]
The STK opcodes have been removed from the Csound sources and put into a separate repository for plugins. So we would not deal with it here anymore. If you wish to open up a ticket there, you're welcome. However, at the moment there is no maintainer there, so it will not be looked after immediately.
