### ISSUE TITLE
add argument to tests/commandline/test.py to select csoundExecutable

### ISSUE THREAD

**Issue by umlaeute** [csound/csound#1527]
for verifying the integrity of the Debian Csound package, i would like to run a few tests with an installed version of `csound` (as opposed to running the tests at build time).

for this to work, it would be nice to have a cmdline switch in `tests/commandline/test.py` that allows me to select an alternative `csoundExecutable` (e.g. `/usr/bin/csound`).

**Comment by vlazzarini** [comment]
Ok, would you be able to send me a patch or a PR against the develop branch? That way you'll probably get what you want more precisely.

**Comment by umlaeute** [comment]
actually it seems that there already *is* such a flag:

https://github.com/csound/csound/blob/482c16c1ae90ad990a98b574be0edbdcedda2db1/tests/commandline/test.py#L262-L263

it's just not very well documented.

i was thinking about fixing the `test.py` script to use [`argparse`](https://docs.python.org/3/library/argparse.html) which comes with automatic documentation of all the flags, but that's probably an overkill...

sorry for the confusion.
