### ISSUE TITLE
no remote on Linux Mint

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#1528]
i do not get the remote opcodes to work (insremot and insglobal) and think something is wrong with the detection code of the ip addresses.

This is the error i get:
```
sr = 48000.0, kr = 375.000, ksmps = 128
0dBFS level = 1.0, A4 tuning = 440.0
unable to get local ip address.INIT ERROR in instr 0 (opcode insglobal) line 18: failed to initialize remote globals.
 from file /media/menno/datae/onderzoek/BLUEinstruments/remote/tempCsd1919008995260211695.csd (1),	insglobal	"192.168.1.114"	1	
header init errors
```

The manual: "If a computer has more than one IP address there is no way to control which IP address is found."
But perhaps there is another issue?

```
menno@mennoASUSZ170 ~ $ ifconfig
enp0s31f6: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.114  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::f05f:ff64:185b:74d5  prefixlen 64  scopeid 0x20<link>
        ether 70:4d:7b:b5:6b:f0  txqueuelen 1000  (Ethernet)
        RX packets 7313  bytes 8354551 (8.3 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 4236  bytes 778880 (778.8 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 16  memory 0xdf200000-df220000  

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 292  bytes 25957 (25.9 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 292  bytes 25957 (25.9 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

This is the csd:

```
<CsoundSynthesizer>
<CsOptions>
csound -+msg_color=false -+rtaudio=JACK -o dac:system:playback_ -d -m135
</CsOptions>
<CsInstruments>
sr=48000
ksmps=128
nchnls=2
0dbfs=1

insglobal   "192.168.1.114", 1

	instr 1	;untitled
iprint  =   600
print iprint
	endin

</CsInstruments>
<CsScore>
i1	5.5625	4	
e
</CsScore>
</CsoundSynthesizer>
```

I get the same results from Blue and the terminal.

**Comment by jpffitch** [comment]
Accoding to  the manual "by the insremot definitions made above the insglobal command"
In your csd there is no insremote.

Also "To send events to only one machine use insremot. "

I ave not looked at the code

**Comment by jpffitch** [comment]
I think that there is an assumption in the code that the ethernet is on either eth0 or wlan0, or the environment variable CS_ETHERhas the ame.  I think you nee a setting of CS_ETHER to enp0s31f6

**Comment by tjingboem** [comment]
i concentrate on one computer and another computer, both on the same network. So i will use then concentrate on insremot and report back. I will do so in a couple of days...

I did not know about CS_ETHER. Is that an undocumented Csound environment variable?

**Comment by tjingboem** [comment]
I have done some testing, and it is quite a long story.

I have set, for both computers, the CS_ETHER environment variable for their respective network cards.

This is what happens on the Master machine: 
- printenv says: `CS_ETHER=enp0s31f6`
`IP = inet 192.168.1.114`

so this must be the csd of the Master:
```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
; Audio out   Audio in
-odac     ;      -iadc     ;;;RT audio I/O
; For Non-realtime ouput leave only the line below:
; -o insremot.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 48000
ksmps = 32
nchnls = 2
0dbfs  = 1

insremot "192.168.1.125", "192.168.1.114", 1 ; destination, Master, instr

instr 1
  aq vco2 .1, 100
     outs      aq, aq
endin

</CsInstruments>
<CsScore>
i1 0 20
e
</CsScore>
</CsoundSynthesizer>
```


Slave machine, second computer:
- printenv says: `CS_ETHER=blah`
` IP = 192.168.1.125`

so the csd for the Slave must be:
```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
; Audio out   Audio in
-odac     ;      -iadc     ;;;RT audio I/O
; For Non-realtime ouput leave only the line below:
; -o insremot.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 48000
ksmps = 32
nchnls = 2
0dbfs  = 1

insremot "192.168.1.125", "192.168.1.114", 1

instr 1
  aq vco2 .1, 100
     outs      aq, aq
endin

</CsInstruments>
<CsScore>
f0 100
e
</CsScore>
</CsoundSynthesizer>

```

Manual says: "Start the client on the machine (it will wait to receive the events from the master machine) and then start the master."
But if i first run its csd on the second computer, i get errors: 
```
IP for remote: blah: 192.168.1.125
---> Could not connect
---> Could not connect
---> Could not connect
---> Could not connect
---> Could not connect
---> Could not connect
---> Could not connect
---> Could not connect
---> Could not connect
---> Could not connect
INIT ERROR in instr 0 line 16: ---> Failed all attempts to connect.

```

So that does not work.

When i first start the csd of the Master, so with the notes, i get:
```
created socket
IP for remote: enp0s31f6: 192.168.1.114
```

and then the Master is waiting....

The moment i run the csd of the second computer (the one with f0 100 in the score), the Master runs and sound is produced on the Master. 
The second computer affirms the connection:
```
IP for remote: blah: 192.168.1.125
--->  Connected.
```
The Master machine shows:
```
created socket
IP for remote: enp0s31f6: 192.168.1.114
accepted, conn=4
```

So, for sure, there is a connection here and the CS_ETHER environment variable must be set on both computers.

What i am NOT sure about is that the second machine is doing the work. I do hear sound but this coming from the Master machine. 

I was expecting the sound to be generated by the soundcard of the second machine but it does not do that.
Is this sound transferred over the network?

**Comment by kunstmusik** [comment]
@tjingboem @jpffitch : Is this a code issue or one does it work and needs more documentation? Trying to figure out where we are with this ticket and if it can be closed.

**Comment by tjingboem** [comment]
i am not in the position anymore to test this. At the time, a musical friend and i were trying to setup this system, but this musical partnership has ended prematurely. 
As far as i am concerned, this issue can be closed.

If a new musical relationship arises and this issue will come up once more, i will open a new ticket....

**Comment by kunstmusik** [comment]
Thank @tjingboem for the followup. I will close this out and yes please do file a new issue if you come across this again.
