### ISSUE TITLE
Feature request: k-rate version of filevalid

### ISSUE THREAD

**Issue by ReinerZorn** [csound/csound#1534]
There is a k-rate version of ftload, namely ftloadk, allowing to load files every k cycle. Unfortunately, if that file does not exist the instrument terminates. So it would be nice to check the existence of the file beforehand (at k rate) but filevalid only works in the i cycle. Would it be possible to implement a 'filevalidk' opcode?

**Comment by vlazzarini** [comment]
Now filevalid works both at i- and k-rate; manual updated. Tested with

```
instr 1
 printk2 filevalid:k("fox.wav")
endin
```

In git develop branch (6.17), we should have a release within the month.
