### ISSUE TITLE
diskin in realtime mode

### ISSUE THREAD

**Issue by snibod** [csound/csound#1535]
I am trying to run diskin opcode together with realtime flag and I am experiencing some issues on WIndows. Here is simplified example:
```
instr	1
    kCtrl = 1

    if (kCtrl == 0) then
        asig, ab diskin "f1.wav",1, 0, 1
    else
        asig, ab diskin "f2.wav",1, 0, 1
    endif
    
    fout "test.wav", 14, asig
    outs asig, asig
endin
```

As far as I understand, when in init thread both files are added, diskio_thread fills both circular buffer. Now, since instrument reads samples only from a single file, the other buffer remains always full. This blocks reading thread in this loop: 
https://github.com/csound/csound/blob/develop/OOps/diskin2.c#L928
Since circular buffer remains full, the thread stays in this loop forever, leading to starvation of the second circular buffer.
Locally, I solved this by making checkspace function public https://github.com/csound/csound/blob/1efa8153ab58912722b7c6216d4dcb8af5734b57/InOut/circularbuffer.c#L51 and using it to check how much space is available in circular buffer. Then I set nsmps in diskin_file_read() accordingly.
I also experienced other issues with async version of diskin caused by lack of synchronization when accessing DISKIN_INST list.
For example, when diskin2_async_deinit is called, it removes circular buffer without ensuring that in parallel it is not being used inside diskio_thread.

**Comment by vlazzarini** [comment]
if you have a PR, I'm happy to look at it. Diskin in realtime mode is not great anyway, and I am not really spending much time trying to hack this. 

If you need hard realtime performance because you are running buffer sizes that are very small (eg two samples), then you may as well load files with GEN01 and reading them with table lookup.
