### ISSUE TITLE
beeping pluck

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#1538]
i was updating the example for wgpluck, and heard in the sound produced some pulsating high frequencies. These frequencies were not really lowering in amplitude as i expected in a pluck:
![Screenshot from 2021-10-01 19-23-02](https://user-images.githubusercontent.com/6670911/135662111-8335971b-9168-4513-84ef-e3a13d6bf175.png)

Here is the csd. The csd contains the same notes as the old example csds.
```
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
; Audio out   Audio in
-odac             ;;;RT audio out
; For Non-realtime ouput leave only the line below:
; -o wgpluck.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

; by Menno Knevel 2021

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

instr 1

icps = 220
iamp = 1
kpick = 0.5
iplk = 0
idamp = p4
ifilt = p5

axcite oscil 1, 1, 1                ; used to excite the pluck
apluck wgpluck icps, iamp, kpick, iplk, idamp, ifilt, axcite
apluck  dcblock2    apluck          ; gets rid of DC offset
outs apluck, apluck

endin

</CsInstruments>
<CsScore>
f 1 0 16384 10 1        ; sine wave.

i 1 0 8     10      1000
i 1 + 8     30      10
e
</CsScore>
</CsoundSynthesizer>
```

**Comment by vlazzarini** [comment]
The artefact is because you are using a sine to excite the string and it oscillates. Replace it by a 1-shot signal like an impulse 

```
axcite mpulse 1, p3 
```

This is normal behaviour.

**Comment by tjingboem** [comment]
Interesting. A short pulse like mpulse does indeed not 'pollute' the plucked sound once it has done its job of exciting.
Here is a screenshot where the first 2 notes are excited by mpulse, then by oscil (track 1)
![Screenshot from 2021-10-02 10-52-09](https://user-images.githubusercontent.com/6670911/135709936-752dcc10-a2b0-4d4e-8d4e-c1aee9792153.png)
Then i used oscili instead, and got a much better/cleaner result as you see in the screenshot (track 2).
And the proof that oscil(i) does continue for the duration p3.

I was expecting that the exciter signal oscil(i) was only used the first few miliseconds but is, in fact, part of the pluck.

**Comment by vlazzarini** [comment]
That's because oscili is a cleaner sine wave, oscil is a little distorted and that's what excites the string. A pure sine at 1 Hz won't make fast enough vibrations to be heard.

In my opinion, that example is misleading. You don't need an excitation to make the model move, you can set aexcite = 0 and it will pluck. The purpose of that signal is to keep the model moving. Try for example using fox.wav as an excitation signal.

**Comment by tjingboem** [comment]
again: interesting!
This sets wgpluck apart from wgpluck2, and using the fox as an exciter shows its purpose. 
The example will reflect this- thanks!

**Comment by tjingboem** [comment]
i think the example is now correct https://csound.com/manual/wgpluck.html
so i will close this issue
