### ISSUE TITLE
turnoff3 and fractional instruments

### ISSUE THREAD

**Issue by NSDopen** [csound/csound#1544]
turnoff3 removes also queued events from instruments with another fractional number.
p.e. turnoff3 12.1 removes also 12.2 and 12

version 6.16
win10 / 64bit

**Comment by jpffitch** [comment]
I tougt ths ws fixed -- maybe in 6.17.  I cwrtainly rewote this 
coderecently

==John ff

**Comment by NSDopen** [comment]
Hi John,

Any idea when this fix will be available?
(Can’t seem to download 6.17)

Van: John ffitch
Verzonden: maandag 8 november 2021 18:01
Aan: csound/csound
CC: NSDopen; Author
Onderwerp: Re: [csound/csound] turnoff3 and fractional instruments (Issue #1544)

I tougt ths ws fixed -- maybe in 6.17. I cwrtainly rewote this 
coderecently

==John ff

On Mon, 8 Nov 2021, NSDopen wrote:

> 
> turnoff3 removes also queued events from instruments with another fractional
> number.
> p.e. turnoff3 12.1 removes also 12.2 and 12
> 
> version 6.16
> win10 / 64bit
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.[ABBM2QVHQG25YQV3J7IUZ4LUK57VJA5CNFSM5HR7S7EKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVG
> G33NNVSW45C7NFSM4PTJ6KZQ.gif]
> 
> 
> 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jpffitch** [comment]
Was due last month so no idea

⁣Get TypeApp for Android ​

**Comment by jpffitch** [comment]
Still waiting for 6.17;. So. I hope !
