### ISSUE TITLE
"scale" opcode breaking change (Csound 6.16)

### ISSUE THREAD

**Issue by retornz** [csound/csound#1547]
Hello, I upgraded to the latest Csound version (6.16) and I noticed something really strange with the "scale" opcode (compared to the older Csound versions)

My line of code is the same `kbitcrusher scale kbitcrusher/100,1,16`

Before, in Csound 6.15, the opcode acted like this :
![Csound15_v2](https://user-images.githubusercontent.com/12613367/140952272-958a241a-06cd-4f34-a09c-97b9a5abbc75.gif)
To me it seems to be the normal behaviour, mapping 0->1 (kbitcrusher/100) to 16->1 (or at least, that's what I expected)

Now in Csound 6.16, the opcode acts like this :
![Csound16_v2](https://user-images.githubusercontent.com/12613367/140952878-576c2508-f6ee-4689-985d-0e7edf4d0248.gif)

At the moment it is a breaking change for me. I would like to upgrade to csound 6.16 for my future plugins, but if I do so, my old plugin (ToneZ) will start to behave in a weird way unless I upgrade it too, but I can already see the issues coming if users have the old/the recent Csound version.. (and the plugin is already widely distributed, so an upgrade is not that easy)

Is this a bug or an intended modification ? 
Any help would be greatly apreciated :)

Let me know if you need more details or anything that could help.

Thanks in advance,

Retornz

**Comment by vlazzarini** [comment]
I am not quite sure what the problem is by looking at your videos, because it's not easy to tell what is going on in your code. The easiest thing for us to check is if you could isolate the issue in a very simple CSD and we can then look at it.

**Comment by vlazzarini** [comment]
I checked the manual and made this example:

```
instr 1
 k1 line 0, p3, 1
 k2 scale k1,0,16
 printf "in: %f out: %f  \n", k1, k1, k2
endin
```

which prints

```
new alloc for instr 1:
in: 0.022676 out: 0.362812  
in: 0.045351 out: 0.725624  
in: 0.068027 out: 1.088435  
in: 0.090703 out: 1.451247  
in: 0.113379 out: 1.814059  
in: 0.136054 out: 2.176871  
in: 0.158730 out: 2.539683  
in: 0.181406 out: 2.902494  
in: 0.204082 out: 3.265306  
in: 0.226757 out: 3.628118  
in: 0.249433 out: 3.990930  
in: 0.272109 out: 4.353741  
in: 0.294785 out: 4.716553  
in: 0.317460 out: 5.079365  
in: 0.340136 out: 5.442177  
in: 0.362812 out: 5.804989  
in: 0.385488 out: 6.167800  
in: 0.408163 out: 6.530612  
in: 0.430839 out: 6.893424  
in: 0.453515 out: 7.256236  
in: 0.476190 out: 7.619048  
in: 0.498866 out: 7.981859  
in: 0.521542 out: 8.344671  
in: 0.544218 out: 8.707483  
in: 0.566893 out: 9.070295  
in: 0.589569 out: 9.433107  
in: 0.612245 out: 9.795918  
in: 0.634921 out: 10.158730  
in: 0.657596 out: 10.521542  
in: 0.680272 out: 10.884354  
in: 0.702948 out: 11.247166  
in: 0.725624 out: 11.609977  
in: 0.748299 out: 11.972789  
in: 0.770975 out: 12.335601  
in: 0.793651 out: 12.698413  
in: 0.816327 out: 13.061224  
in: 0.839002 out: 13.424036  
in: 0.861678 out: 13.786848  
in: 0.884354 out: 14.149660  
in: 0.907029 out: 14.512472  
in: 0.929705 out: 14.875283  
in: 0.952381 out: 15.238095  
in: 0.975057 out: 15.600907 
```

and that is what the manual says it does. So if it was behaving differently before, it was wrong then. You can check the code above in 6.15 to see what it does.

**Comment by retornz** [comment]
@vlazzarini Thank you for your quick reply, and sorry I should have sent a simple example.

So as you noticed with your example, now in Csound 6.16, it prints (first line)
`in: 0.022676 out: 0.362812`
I just tried to run the same example with Csound 6.15, and it prints (first line) :
`in: 0.000000 out: 16.000000`

That's were I'm confused, because the manual says this :
![image](https://user-images.githubusercontent.com/76706065/140978207-094c452e-052c-4ab4-a4e0-a492b3b30249.png)

So in the example : `k2 scale k1,0,16`
0 is kmax
16 is kmin

I would expect a mapping 16 ->0 from a 0->1 input. (that's at least how it worked before)

I took a look at the code, and I saw only this change between Csound 6.15 & 6.16 for the "scale" opcode
![image](https://user-images.githubusercontent.com/76706065/140979896-794a8b0f-78c3-4677-8fb5-2e06a9ebca9a.png)

So that's why I'm not sure if it's intended or not, what do you think ?

**Comment by jpffitch** [comment]
That image is cosmetc change only.

note that scae has an init call wie scale2 does not


ore interesing would be the commit reference for the change.  I will look 
but not sure I rememer how to find ot.

**Comment by jpffitch** [comment]
There was acange about lasr Decemer to te case of the kmax being less han 
the kmin.  Originally the code took no notce of this oddity, bu the revision 
does an internal swap. It ispossinle I got this all wrong but it was 
dsupposed to fix a poblem reported to me


> So in the example : k2 scale k1,0,16
> 0 is kmax
> 16 is kmin
>

**Comment by retornz** [comment]
Thanks for the reply @jpffitch, I found the commit, it is 87f0706 (https://github.com/csound/csound/commit/87f07064e18e5bb916bc817343b163c5f4bce163#diff-f3522bde5e3d480169cdca5101b694c538528a4872a1c8407fd353f15472f488)

I tried to search in the issue tracker the linked issue to this fix, but I can't find anything relevant here.. 
I think it's because of this new checking and swapping that I noticed a change in the behaviour,  that's why it would be great to see the original reason behind it

**Comment by vlazzarini** [comment]
The manual does not say anything about the case where kmax is less than kmin, so the order reversal could have been interpreted as a bug. 

Maybe the right thing is to restore the behaviour and adjust the manual. Also the manual is wrong about what the input value needs to be.

It's a very simple expression anyway, you can replace it in your original case by

kout = 16 - kin*16

if you don't want to wait for a fix.

**Comment by retornz** [comment]
> Maybe the right thing is to restore the behaviour and adjust the manual. Also the manual is wrong about what the input value needs to be.

That is what I think to be the best solution, backward compatibility is important.
And if there is a need for an other opcode with order checking/reversal, that should be implemented in an other opcode, which would avoid breaking things.

> It's a very simple expression anyway, you can replace it in your original case by
> kout = 16 - kin*16
> if you don't want to wait for a fix.

The thing is that there are already several 1000s of copies (almost 25000) of my plugin out there, so it's not that easy...


So, it is perfectly fine for me to wait for the fix.
In the meantime I will use Csound 6.15, and add a note in my user manual about it.
And when the new Csound version with the fix will be realeased, I will be able to safely upgrade.

Thanks a lot for taking time to look into this issue.

**Comment by vlazzarini** [comment]
ok, we have a release of 6.17 almost ready, we are just waiting for some webaudio work to be integrated and then we'll release.

**Comment by jpffitch** [comment]
Code reverted

**Comment by retornz** [comment]
Thank you @jpffitch & @vlazzarini 
I will test this when 6.17 will be out !
