### ISSUE TITLE
Compile - Memory leak

### ISSUE THREAD

**Issue by NSDopen** [csound/csound#1549]
v 6.16 / win10 / ModulysCS as frontend

When recompiling (cSoundCompileCSD()) leaks in following cases happen :
case 1 -> ftGen (iGen=1) -> Memory not freed, but reused. (maybe a design choice?)
case 2 -> sfLoad -> Memory not freed, not reused. (imho=bug)
case 3 -> fluidLoad -> Memory not freed, not reused. (idem dito)

**Comment by vlazzarini** [comment]
case 3 is to do with fluidsynth and that code is not part of the Csound library, so you will need to open a ticket there (I think there is an open ticket). Case 1 seems right. Case 2 is code that is within Csound and might need to be looked at to be the same as Case 1.
