### ISSUE TITLE
Bug with mp3in and mp3len opcodes

### ISSUE THREAD

**Issue by ervoL** [csound/csound#1553]
Dear developers,

I am working with Csound version 6.16.1 on Windows and MacOS. There seems to be a bug in mp3 opcodes: mp3in and mp3len. Mp3len on both platforms always returns 0 and mp3in plays the file correctly on both platforms but on Windows problems occur afterwards; i.e. Cabbage crashes immediately if I try to play mp3 file again and my application (written in c++) throws exception when deleting csound object. This looks to me as csound comes to some bad state when mp3in is used on Windows.

Here is a sample of code that makes problems:
```
<CsoundSynthesizer>
<CsOptions>
-n -d 
</CsOptions>
<CsInstruments>
; Initialize the global variables. 
ksmps = 32
nchnls = 2
0dbfs = 1

instr 1
ilen  mp3len p4 
print  ilen

asigL, asigR mp3in p4
outs  asigL, asigR
endin

</CsInstruments>
<CsScore>
i1 0 10 "song.mp3"
</CsScore>
</CsoundSynthesizer>

```

Best regards!

**Comment by vlazzarini** [comment]
The first one of these is fixed in the develop branch now. I do not know whether I can help with the second, because I am not on Windows. Maybe @stekyne could lend a hand to diagnose this?

**Comment by stekyne** [comment]
I'll try and take a look soon.

**Comment by stekyne** [comment]
@ervoL I'm seeing the following error. Is it the same for you?

```
Program: F:\dev\GitHub\csound\build\Debug\csound.exe
File: minkernel\crts\ucrt\src\appcrt\lowio\close.cpp
Line: 49

Expression: (_osfile(fh) & FOPEN)
```

**Comment by ervoL** [comment]
Hi @stekyne 

Unfortunately, I am not on Windows right now but I don’t remember that error. 

Cabbage simply crashes every time after I use mp3in. More precisely, it doesn’t crash immediately after using mp3in but after I run again that csd file. 

When I use mp3in inside my c++ application everything is, so to say, normal but when I close my app and delete csound object, exception is thrown. I forgot exactly which one but I can tell you that if you want in a few days (after the holydays).

**Comment by vlazzarini** [comment]
Any movement on this issue? We're hoping to release 6.17 before the end of the month.

**Comment by stekyne** [comment]
@vlazzarini I'll try and take a look this week

**Comment by jpffitch** [comment]
Is this still unresolved?  I was hoping to move a way from the internal MP3 code towards libsndfile.

**Comment by stekyne** [comment]
@stekyne I can't remember getting to the bottom of this or not. I wasn't quite seeing the same behaviour as the originator of this ticket. 

Maybe it's best to switch to using libsndfile for this?

**Comment by kunstmusik** [comment]
@stekyne @jpffitch @vlazzarini - Is this issue still present?

**Comment by stekyne** [comment]
I couldn't replicate it. The user also didn't message again. Maybe moving to use libsndfile would elide the problem anyways. Might be worth opening a ticket for that and close this.

**Comment by kunstmusik** [comment]
Created #1785 and scheduled for 7.0.0.

**Comment by jpffitch** [comment]
I think that in cs7 there is no need fr these opcodes as libsndfile does 
it better.
