### ISSUE TITLE
lastcycle() triggers on the penultimate cycle

### ISSUE THREAD

**Issue by mesca** [csound/csound#1555]
When an instrument is turned off from a lower instrument, `lastcycle()` is triggered on the penultimate cycle. This happens in v6.16.

Here is an example that demonstrates the issue:

```
<CsoundSynthesizer>
<CsOptions>
-odac -m0
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

instr OffLower
    turnoff2 "Test", 0, 1
    turnoff
endin

instr Test
    printk2 lastcycle()
endin

instr OffHigher
    turnoff2 "Test", 0, 1
    turnoff
endin

</CsInstruments>
<CsScore>

; OK
i "Test" 0 -1
i "OffHigher" .1 -1

; KO
i "Test" .2 -1
i "OffLower" .3 -1

f0 z

</CsScore>
</CsoundSynthesizer>
```

This will print:

```
lastcycle: adding an extra cycle to the duration of the event
 i2     0.00000
 i2     1.00000
lastcycle: adding an extra cycle to the duration of the event
 i2     0.00000
 i2     1.00000
 i2     0.00000
```

@gesellkammer

**Comment by gesellkammer** [comment]
Thanks for the report, I will look into it

**Comment by gesellkammer** [comment]
I looked at this issue but it has no solution within the scope of the opcode: the scheduler will run the instrument one cycle too much if turned off by a higher instrument. Either we include this in the manual or the scheduler needs to be fixed.
For the OP, a much more reliable way to detect an instrument stopping is to use the `atstop` opcode:

https://csound-plugins.github.io/risset-docs/opcodes/atstop.html

**Comment by vlazzarini** [comment]
Looks like as with other things, it is important to observe instrument ordering. I think a note in the manual will suffice.
For Csound 7, we will add means of scheduling instruments in different orders that can be independent from instrument numbering.

**Comment by mesca** [comment]
Thanks. I guess a note in the manual will be enough, even if the opcode's name is now a bit misleading ;)
Is there a chance for `atstop` to make it in Csound core?

**Comment by vlazzarini** [comment]
Ok, I'm closing this and opening a ticket in the manual
