### ISSUE TITLE
Increment syntax and arrays

### ISSUE THREAD

**Issue by mesca** [csound/csound#1556]
Not a big deal, but arrays do not support the short increment syntax (v6.16):

```
i1[] init 1
i1[0] = i1[0] + 1 ; OK
i1[0] += 1        ; syntax error
```

**Comment by jpffitch** [comment]
True.  Never coded. May be in csoud7?

**Comment by jpffitch** [comment]
Parser issue; nds to be fixed in prser3 

will not fix in cs6 unles there is an urget need.
