### ISSUE TITLE
Some opcodes do not run at k-rate with functional syntax

### ISSUE THREAD

**Issue by mesca** [csound/csound#1557]
Values from `timek` and `chnget` are not updated when using the functional syntax. I detected these two examples, but there are probably others:

```
<CsoundSynthesizer>
<CsOptions>
-odac -m0
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

chn_k "test1", 3
chn_k "test2", 3

instr test_timek
    k1 timek
    k2 = timek()
    printk2 k1 ; OK
    printk2 k2 ; prints 0.00000 once
    done:
endin

instr test_chnget
    k1 chnget "test1"
    k2 = chnget("test2")
    printk2 k1 ; OK
    printk2 k2 ; prints 0.00000 once
    k1 += 1
    k2 += 1
    chnset(k1, "test1")
    chnset(k2, "test2")
endin

</CsInstruments>
<CsScore>

i "test_timek" 0 .01
i "test_chnget" 0 .01

</CsScore>
</CsoundSynthesizer>
```

**Comment by jpffitch** [comment]
LLLooig at h compilation it is a type inference oddity

timek.k args:   k1
timek.i args:   #i0
=.k args:       k2      #i0
printk2 args:   k1      0       0
printk2 args:   k2      0       0
chnget.k args:  k1      "test1"
chnget.i args:  #i0     "test2"
=.k args:       k2      #i0
printk2 args:   k1      0       0
printk2 args:   k2      0       0
##add.kk args:  k1      k1      1
##add.kk args:  k2      k2      1
chnset.k args:  k1      "test1"
chnset.k args:  k2      "test2"


One can see te .i opcodes

This is one of Victor or Steven

**Comment by vlazzarini** [comment]
If you need k-rate opcodes, you need to qualify the code with :k  or use the standard syntax which does type inference.

**Comment by mesca** [comment]
Thanks!
