### ISSUE TITLE
syncgrain-crash at k-rate

### ISSUE THREAD

**Issue by janjacobhofmann** [csound/csound#1573]
### 
Dear Victor,

I yesterday found out that blue crashes and csoundqt freezes 
when to syncgrain the arguments freq or grsize are fed with changing arguments at k-rate. I modified the example from the manual to demonstrate and attached it here. Actually both arguments should support k-rate, even if it holds changing values over time.

On Mac I am on OS X 10.12.06 with csound  6.16 and the latest version of blue (here blue crashes after rendering)
On Linux (ubuntu 20.03) I do use a self compiled version of Csound 6.17 from git and Csoundqt version Version 0.9.6-1 (here Csoundqt freezes after rendering).

Best wishes,
Jan Jacob

<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac  ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o syncgrain.wav -W ;;; for file output any platform
</CsOptions> 
<CsInstruments>

sr = 44100 
ksmps = 32 
0dbfs  = 1 
nchnls = 2
  
instr 1
		
iolaps  = 2
igrsize = 0.04
ifreq   = iolaps/igrsize
ips     = 1/iolaps

istr    = .3   /* timescale  */
ipitch  = p4   /* pitchscale */

kfreqfact	line	0.5,	p3, 1
kfreq	=	ifreq * kfreqfact

asig	syncgrain 1, kfreq, ipitch, igrsize, ips*istr, 1, 2, iolaps
	outs	  asig, asig 

endin
</CsInstruments>
<CsScore>
f1 0 0 1 "fox.wav" 0 0 0	;deferred table
f2   0   8192   20   2   1

i1 0 5 1
i1 + 5 4
i1 + 5 .8
e
</CsScore>
</CsoundSynthesizer> 
<bsbPanel>
 <label>Widgets</label>
 <objectName/>
 <x>100</x>
 <y>100</y>
 <width>320</width>
 <height>240</height>
 <visible>true</visible>
 <uuid/>
 <bgcolor mode="nobackground">
  <r>255</r>
  <g>255</g>
  <b>255</b>
 </bgcolor>
</bsbPanel>
<bsbPresets>
</bsbPresets>
[syncgrain-test.txt](https://github.com/csound/csound/files/7820302/syncgrain-test.txt)

**Comment by janjacobhofmann** [comment]
Dear Victor,
I pulled a new clone of csound from git onto my linux-computer and tested again: It works fine now! thank you so much for fixing it so quickly!
Cheers,
Jan Jacob

**Comment by vlazzarini** [comment]
Excellent. Happy New Year!

Prof. Victor Lazzarini
Maynooth University
Ireland

On 7 Jan 2022, at 20:39, janjacobhofmann ***@***.***> wrote:

﻿
*Warning*

This email originated from outside of Maynooth University's Mail System. Do not reply, click links or open attachments unless you recognise the sender and know the content is safe.

Dear Victor,
I pulled a new clone of csound from git onto my linux-computer and tested again: It works fine now! thank you so much for fixing it so quickly!
Cheers,
Jan Jacob
