### ISSUE TITLE
Problems to build on manjaro

### ISSUE THREAD

**Issue by anton-k** [csound/csound#1574]
Manjaro/arch expects headers and libs to be in 
/usr/include and /usr/lib. 
But when csound installs it to /usr/local/lib and /usr/localinclude

Csound has trouble to find so's and headers (on plugin build).
I had to manually create symlinks for that.
Otherwise I see erros that so's are not found:

**Comment by vlazzarini** [comment]
Use `CMAKE_INSTALL_PREFIX` to place Csound wherever you wnat to install it. So in this case, you can set `CMAKE_INSTALL_PREFIX=/usr`.  I'm closing this, but if you need further help you can ask at the Csound or Cs-Dev list.
