### ISSUE TITLE
Csound WASM 6.17.0-beta2 does not work correctly in BabylonJS playground

### ISSUE THREAD

**Issue by docEdub** [csound/csound#1579]
When running Csound WASM 6.17.0-beta2 in the BabylonJS playground, the .csd text compiles and Csound starts correctly but no sound is produced and strange Csound messages are output in the Javascript console for the duration of the score.

Example messages:
```
#k46	expseg	1	iPchDur	0.0001	#i45	0.0001	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
#k46	expseg	1	iPchDur	0.0001	#i45	0.0001	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
	AF_3D_Audio_ChannelGains	k_azimuth	k_elevation	k_sourceWidth	i_ambisonicOrder	0	
	AF_3D_Audio_ChannelGains	k_azimuth	k_elevation	k_sourceWidth	i_ambisonicOrder	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
kmul	transeg	0.2	#i18	-15	0.01	#i19	0	0	
could not find playing instr 10.007000
could not find playing instr 10.008000
```

https://playground.babylonjs.com/#GHJCW5 shows the issue in Chrome.

Older versions of Csound WASM work correctly. In the linked playground, change the `document.isProduction = true` line to `false` to switch to the old version from several months ago.

Running it with the newer Csound WASM version works fine outside the BabylonJS playground, so I'm not sure what's happening or how to proceed. Maybe someone else knows what's wrong when Csound WASM is running in the BabylonJS playground?

**Comment by vlazzarini** [comment]
What's the commit?

**Comment by hlolli** [comment]
can you try again with newer csound releases?

**Comment by vlazzarini** [comment]
tested now and it is working:

https://playground.babylonjs.com/#27CW1T#1

**Comment by docEdub** [comment]
It's not working for this playground: https://playground.babylonjs.com/#GHJCW5#1 using https://unpkg.com/@csound/browser@6.18.5/dist/csound.js. I don't get the `kmul` output in the console anymore, and the `could not find playing instr 10... ` errors are gone, but there doesn't seem to be any audio output.

The playground still works for the old version I was using before: https://playground.babylonjs.com/#GHJCW5#2 using
https://unpkg.com/@doc.e.dub/csound-browser@6.17.0-beta5/dist/csound.esm.js

**Comment by hlolli** [comment]
it seems the implicit realtime "-odac" is the culprit here. Just add that option somewhere and it should work?

**Comment by docEdub** [comment]
Yes, https://playground.babylonjs.com/#GHJCW5#4 works with `-odac` added in the `<CsOptions>` section of the .csd text.

Thank you!
