### ISSUE TITLE
Fixing the thread ambiguity in strings

### ISSUE THREAD

**Issue by vlazzarini** [csound/csound#1587]
Issue #1586 has raised a problem with Csound 7.0 which is that the parser  is now expanding an expression of the kind

```
S_txt = S_arr[k_index]
```

into

```
##array_get.K args:	#S1	S_arr	k_index
=.S args:	S_txt	#S1
```

where in the past it did not. This causes the problem that the assignment synthesised needs to happen at perf time (thread 2) and string assignments are set  to i-time only (thread 1). The only solution at the moment is to make  it run on both  threads.  However this means that ALL  string assignments will run at perf time and  that's stupid.

Regardless of the merits of not synthesising the expression since `S_txt = S_arr[k_index]` could be perfectly turned into a single `##array_get.K` line, the strings problem is one that needs to be tackled. Strings were originally hacked into the language without proper thought and opcodes started to be written for it. We managed to improve things by creating a self-describing  datatype in 6.0, but that did not tackle the rate ambiguity. Many users have been tripped by it. So it its time we do something about the problem.

Off the top of my head,

- Add an update flag to `STRINGDAT`
- String-outputting opcodes increment the update flag to indicate the string has changed.
- String consuming opcodes check the flag to see if anything needs to be done.

That way all string-consuming opcodes are set to thread 3 but they might be non-op if nothing is needed to be done.

This is similar to fsigs, except that it will also run at i-time.

**Comment by vlazzarini** [comment]
I have added an experimental update count to `STRINGDAT`, and tested it with 

- strcpy (https://github.com/csound/csound/blob/d10536279b85b986389f22c9504be786d2ff3c3f/Engine/csound_standard_types.c#L93)
- string_copy_value (https://github.com/csound/csound/blob/d10536279b85b986389f22c9504be786d2ff3c3f/Engine/csound_standard_types.c#L93)

It appears to work as planned. If it looks the right thing to do, we can then roll it to all other relevant string opcodes.

Basic principles are:

- opcodes always run at i-time and set the string output update count (if any)to 1 and their internal update counter to 0.
- at perf-time, opcodes check if their internal counter is less than the input string counter and if so they run and at the end update the output string counter to reflect the update using the input string count (if more than one, the greatest).

**Comment by mesca** [comment]
Commit [081f86b](https://github.com/csound/csound/commit/081f86bcb600975e2f8226057c6a4cfcce675b52) (the change in `Engine/csound_standard_types.c`) breaks this test:

```
S_arr[] init 2
S_arr[0] = "foo"
S_arr[1] = "bar"
k_index = 0
until (k_index == 2) do
    S_txt = S_arr[k_index]
    k_index += 1
od
printks("%s\n", 0, S_txt)
```

It should print `bar`, but instead, `foo` is printed.

**Comment by vlazzarini** [comment]
fixed.

**Comment by mesca** [comment]
Cool, now all my test pass.

**Comment by vlazzarini** [comment]
I had to redesign this, but I think now it works better:

1. STRINGDAT has a timestamp field now
2. At perf-time, the timestamp of input strings is checked and if it matches the current time, then the input is processed.
3. Opcodes producing strings at perf-time will update the timestamp to the current time if a new string is produced.
4. STRINGDAT variable copy (at perf time) is only done if the source timestamp matches the current time.
4. Opcodes reading strings but producing other outputs may use the timestamp to decide on whether to do any processing.

At i-time, the timestamp is understood to be zero.

**Comment by mesca** [comment]
This fails:

```
S_cmp = "foobar"
S_arr[] init 1
S_arr[0] = S_cmp
k_index = 0
printks("* strcmp with i index: [%d]\n", 0, strcmp(S_cmp, S_arr[0]))       ; OK
printks("* strcmp with k index: [%d]\n", 0, strcmp(S_cmp, S_arr[k_index])) ; KO
printks("* value at k-rate: [%s]\n", 0, S_arr[k_index])
```

But I guess the error is consistent with:

> Opcodes reading strings but producing other outputs may use the timestamp to decide on whether to do any processing.

**Comment by vlazzarini** [comment]
yes, but strcmp should return the previous result without needing to compute it again. That's the idea but there's something that needs fixing.

**Comment by vlazzarini** [comment]
the problem with the code above is unrelated to the changes. The issue is that`strcmp` is i-time and so the result is not computed at the correct time. You need

```
printks("* strcmp with k index: [%d]\n", 0, strcmpk(S_cmp, S_arr[k_index])) ; KO
```

The code is similar to having

```
kvar = k(strcmp(S_cmp, S_arr[k_index]))
```

While looking at this, I noticed there was a very old bug in the entry for `strcmpk` that was leading to crash with  the updated code.

**Comment by mesca** [comment]
Consider the following:

```csound-document
<CsoundSynthesizer>
<CsOptions>
-n
</CsOptions>
<CsInstruments>

gS_arr[] init 3

instr write
    gS_arr[p4] = p5
endin

instr read
    i_index = 0
    until (i_index = 3) do
        prints("%s\n", gS_arr[i_index])
        i_index += 1
    od
endin

</CsInstruments>
<CsScore>

i "write" 0 0 0 "a"
i "write" 0 0 1 "b"
i "write" 1 0 2 "c"
i "read"  2 0

</CsScore>
</CsoundSynthesizer>
```

It should print `abc`, but since [d687f1b](https://github.com/csound/csound/commit/d687f1b4e354eefb45abc7fb569f8ace4867509b), the output is `abb`.

**Comment by vlazzarini** [comment]
yep, I didn't think of global variables. I made an adjustment and your test is passing now in the latest commit.

**Comment by mesca** [comment]
> I didn't think of global variables.

Nor of UDOs ;)

```csound-document
<CsoundSynthesizer>
<CsOptions>
-n
</CsOptions>
<CsInstruments>

gS_arr[] init 5

opcode array_set, 0, iS
    i_key, S_val xin
    gS_arr[i_key] = S_val
endop

instr write
    i_key = p4
    S_val = p5
    array_set(i_key, S_val)
endin

instr read
    i_index = 0
    until (strcmp(gS_arr[i_index], "") == 0) do
        prints("%s\n", gS_arr[i_index])
        i_index += 1
    od
endin

</CsInstruments>
<CsScore>

i "write" 0 0 0 "a"
i "write" 0 0 1 "b"
i "write" 1 0 2 "c"
i "read"  2 0

</CsScore>
</CsoundSynthesizer>
```

**Comment by vlazzarini** [comment]
Not a problem with UDO but one with the use of global variables

**Comment by vlazzarini** [comment]
Looks like there is no practical way to avoid spurious copies from arrays at k-time, the pathological case of global variables does not permit it. At least I have a means to avoid further copies. Anyway, this is fixed.

**Comment by mesca** [comment]
Another test that fails since [d687f1b](https://github.com/csound/csound/commit/d687f1b4e354eefb45abc7fb569f8ace4867509b):

```csound-document
<CsoundSynthesizer>
<CsOptions>
-n
</CsOptions>
<CsInstruments>

gS_arr[] init 1

instr setS
    gS_arr[0] = "a"
endin

instr getS
    k_idx = 0
    S_txt = gS_arr[k_idx]
    printks("[%s%s]\n", 0, gS_arr[k_idx], S_txt)
    if timeinstk() == 1 then
        turnoff
    endif
endin

</CsInstruments>
<CsScore>

i "setS" 1 0 ; works if p2=0
i "getS" 1 1 ; prints [a], should be [aa]

</CsScore>
</CsoundSynthesizer>
```

**Comment by vlazzarini** [comment]
I've dealt with this one, but I think I have a better rule to implement now. I'll look into it later.

**Comment by mesca** [comment]
Thanks. That fixed the previous test case, but created another issue. Hard to debug because of this [line](https://github.com/csound/csound/blob/63dbb05932a4594c1c7f3c559b0aff17b0e8c68a/OOps/str_ops.c#L229). Can you remove it?

**Comment by mesca** [comment]
There are still some problems, but I will wait until you can implement your new idea.

**Comment by vlazzarini** [comment]
Now it looks better, the main issue before was that the array copy operation could not distinguish between i-time and perf-time, but now it does so the timestamp updates are consistent between that and the str opcodes that output S-vars.

**Comment by mesca** [comment]
No error, but my CSD does not render properly. I will investigate tomorrow.

**Comment by mesca** [comment]
S-vars are updated only during the first k-pass:

```csound-document
<CsoundSynthesizer>
<CsOptions>
-n
</CsOptions>
<CsInstruments>

instr getS
    S_arr[] init 2
    S_arr[0] = "a"
    S_arr[1] = "b"
    k_idx = 0
    until (k_idx == 2) do
        S_txt = S_arr[k_idx]
        printsk("%d: %s %s\n", k_idx, S_arr[k_idx], S_txt)
        k_idx += 1
    od
    if timeinstk() == 2 then
        turnoff
    endif
endin

</CsInstruments>
<CsScore>

i "getS" 0 1

</CsScore>
</CsoundSynthesizer>
```

Output:
```
0: a a
1: b b
0: b b
1: b b
```

Expected:
```
0: a a
1: b b
0: a a
1: b b
```

**Comment by vlazzarini** [comment]
yes, the design is exactly like this, one copy and none if the string is not changed, and it is the case here that the strings do not change. 

The whole point is to avoid copying data if it has not changed. The problem here is exactly what I am trying to solve, all this unnecessary copying, which is exacerbated by the new parser adding one extra synthetic variable. This also confuses things because the array printing is wrong because the code is not reading from the array but from the synthetic var.

It may in the end be the case that it is not possible to achieve it. So if the user writes code that requires a lot of unneeded copying at perf time, they'll just need to pay the penalty for it.

I'll have to think about it.

**Comment by vlazzarini** [comment]
the solution it appears can only be partial, excluding array access. So that's what's implemented now.

**Comment by mesca** [comment]
Ternary expressions such as: `S_txt = 0 == 0 ? "a" : "b"` now fail with `csound command: Illegal instruction`.
Everything else looks good.

**Comment by mesca** [comment]
> the solution it appears can only be partial, excluding array access

Just to be clear: does that mean that a copy is created every time a string is accessed from an array?

**Comment by vlazzarini** [comment]
yes, the string is copied from the array every time it is accessed, whether the string has changed or not. If the access is i-rate (using an i-rate index), then it should only be at i-time but if there's a k-rate index it will happen at every k-cycle, even if the index does not change.

**Comment by vlazzarini** [comment]
> S_txt = 0 == 0 ? "a" : "b"

this has been sorted. I think the parser is generating more assignments than needed, 

```
=.S args:	#S1	"a"
=.S args:	#S1	#S1
=.S args:	S_txt	#S1
```

That second line needed to be protected against.

**Comment by vlazzarini** [comment]
I'll close this now and move on. If there are further issues, feel free to reopen.
