### ISSUE TITLE
scanmap does not change scanned sound itself

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#1592]
please check for an example that shows this behavior here:
https://github.com/csound/manual/issues/615

**Comment by jpffitch** [comment]
Scansmap reads the internal state so I would not expect it to chane the sound.  What have I missed?

⁣Get TypeApp for Android ​

**Comment by tjingboem** [comment]
Nothing. 
Everything is absolutely clear now- thanks!

scansmap should change the sound, scanmap is only providing information.
