### ISSUE TITLE
Unregister callbacks in Csound API

### ISSUE THREAD

**Issue by giovannibedetti** [csound/csound#1595]
hi!
I'm implementing the API methods csoundSetInputChannelCallback (https://csound.com/docs/api/group__CONTROLEVENTS.html#ga156b528f5d32544874a929a6c109b343) and csoundSetOutputChannelCallback in C# in CsoundUnity. 
All is working great, but I was wondering if there is some way to unregister those callbacks without the need to call csoundCleanup (https://csound.com/docs/api/group__PERFORMANCE.html#ga81289d7daf033349d8b36aa03c528ea4), that would force me to end the performance.
Right now I am adding and removing the callbacks when Csound is already started using C# EventHandlerList, so after removing it I'm simply not executing the callback once received, but it's still invoked. 
If I add the callback again, my host application (Unity) starts throwing null refs, but also hangs, and it's impossible to stop it without closing it from the Task Manager.
Any advice?
Is it possible to implement a method to unregister the callbacks in the API? For example like the csoundRemoveKeyboardCallback method
(https://csound.com/docs/api/group__CONTROLEVENTS.html#gaf76c15ea689f203251fc379c5c73486b) 
It would be needed also for the other callbacks, csoundRegisterSenseEventCallback (https://csound.com/docs/api/group__CONTROLEVENTS.html#ga28e0e3e048d265218f343a1b34741986) and csoundSetYieldCallback (https://csound.com/docs/api/group__THREADING.html#ga55b35afa169c48e68d6b13674d616295)

current implementation in this branch:
https://github.com/rorywalsh/CsoundUnity/tree/channelCallbacks
latest commit: https://github.com/rorywalsh/CsoundUnity/commit/a42f659bd473d4d453da8ba9d9e210c87f209f9a

**Comment by vlazzarini** [comment]
why can't you set the callbacks to NULL? Would that not work?

**Comment by giovannibedetti** [comment]
Thanks for the explanation, I will try following your suggestions. 
This leads me to think that I could have implemented it in a dangerous way (basically I can add more than one callback of the same type to the same Csound instance).
Does it makes any sense to call csoundSetInputChannelCallback/csoundSetOutputChannelCallback more than once? Does the second overwrite the previous one?

Also thank you for pointing out that those will be removed, maybe it's not worth it having them in the CsoundUnity repo, so users won't start using them at all.

**Comment by mesca** [comment]
> 7.x will have a different API and much of these things will change, including input and output message callbacks (which will be removed since they duplicate channel bus functionality).

Sorry to hijack this thread, but does that mean that channel callbacks will completely disappear?
I was hoping that we would get callbacks for `chnset` (that I intensely use) in addition to `outvalue`.

**Comment by vlazzarini** [comment]
We will making invalue/outvalue use the chnget/chnset bus and the callbacks for those will disappear. We have discussed it in the list. Since Csound manages the list of channels, it is much safer to keep it that way. Also having two systems side by side is confusing. But here is not the place for further discussion, the dev list is. We're a bit way of working on the API still.

**Comment by vlazzarini** [comment]
> Thanks for the explanation, I will try following your suggestions. This leads me to think that I could have implemented them in a dangerous way (basically I can add more than one callback of the same type to the same Csound instance). Does it makes any sense to call csoundSetInputChannelCallback/csoundSetOutputChannelCallback more than once? Does the second overwrite the previous one?
> 
> Also thank you for pointing out that those will be removed, maybe it's not worth it having them in the CsoundUnity repo, so users won't start using them at all.

You only set it when you need a new callback to run.Csound only uses 1 input and 1 output message callback at a time in each Csound object.

**Comment by giovannibedetti** [comment]
Hi @vlazzarini, will the [SetYieldCallback](https://csound.com/docs/api/group__THREADING.html#ga55b35afa169c48e68d6b13674d616295) be removed too? 
And is it the right callback to use if I want to do something as soon as a ksmps block is computed? For example grabbing an audio channel with [GetAudioChannel](https://csound.com/docs/api/group__CONTROLEVENTS.html#gaa425270e455d6ebe0b1cd0ed7582bed3)?

**Comment by rorywalsh** [comment]
You really shouldn't need this callback if your are calling performKsmps()
directly?

**Comment by rorywalsh** [comment]
Yes, but in the case you discuss there you're already calling `GetAudioChannel()` on each k-boundary, so setting up an additional k-boundary callback makes no sense?

**Comment by vlazzarini** [comment]
We'll keep the yield callback because it's useful if we are not implementing a loop but calling csoundPerform().

**Comment by kunstmusik** [comment]
Closing this issue as it went off track and also sounds like there is a known solution or workaround for the original issue here. If there are remaining questions or problems please file new issues.
