### ISSUE TITLE
Distribute Csound for MacOS as a .bundle

### ISSUE THREAD

**Issue by giovannibedetti** [csound/csound#1598]
Hi,

To be able to import Csound in Unity correctly for the MacOS platform, I need it in the form of a ".bundle", instead of a ".framework".

Could it be added to the build pipeline maybe?

Here is a bash script with the steps to convert a ".framework" into a ".bundle":

[convert_Csound_Framework_To_Bundle.sh.zip](https://github.com/csound/csound/files/8188472/convert_Csound_Framework_To_Bundle.sh.zip)

Thanks!

**Comment by vlazzarini** [comment]
Can't you just rename the framework as a .bundle, create a MacOS dir inside it and put a symlink to CsoundLib64 there?

Then put in the info.plist and nothing else.

@rorywalsh do you know anything about this? I thought you used Csound in unity before.

**Comment by giovannibedetti** [comment]
Yes sure that is what the bash script is doing ;)
The issue with Unity is that when building from Unity the .framework is not copied in the exported build, instead the .bundle is, so with the .bundle we have working MacOS builds.

**Comment by vlazzarini** [comment]
The script does a lot of copying and changing links. You may not need all that, just a symlink.

**Comment by giovannibedetti** [comment]
Thanks, I will try to use a symlink!
Btw the script is from the Unity support team, I asked them for help for the build issues we had on MacOs with the .framework.

**Comment by rorywalsh** [comment]
@giovannibedetti and I have been doing it in a more brute force fashion. If having it as a .bundle means better integration into Unity, that's the way to go. @giovannibedetti , let me know how you get on. I will try to test the iOS stuff this week 👍

**Comment by giovannibedetti** [comment]
Have a look here, this is the whole conversation about the issue:

https://fogbugz.unity3d.com/default.asp?1311509_ukb6c3vemh2mq1d4

**Comment by kunstmusik** [comment]
Scheduling this for 7.0.0. It seems like it should not take too much work to add this to our build scripts as well as to github actions so that we're deriving a second artifact from our standard build.

**Comment by vlazzarini** [comment]
@giovannibedetti 
I am incorporating your script into our release building scripts. Just a question about this line:

```
cp CsoundLib64.framework.meta CsoundLib64.bundle.meta
```

what is `CsoundLib64.framework.meta`?

**Comment by vlazzarini** [comment]
A PR has been created to address this request.

**Comment by giovannibedetti** [comment]
Thanks for this Victor!

The meta files should be generated by Unity (a .meta file exists for every
file and folder in the Unity project), so I think that line can be removed
from the script

Il Mar 11 Giu 2024, 19:36 vlazzarini ***@***.***> ha scritto:

**Comment by vlazzarini** [comment]
ok this is done now. The bundle is created alongside the installer and packaged into the dmg.
