### ISSUE TITLE
Is csound suddenly breaking because I installed new binaries recently? Is my OS supported?

### ISSUE THREAD

**Issue by csound1734** [csound/csound#1600]
it's macOS High Sierra 10.13.6

I had to go download a new installer from the Downloads page at csound.com - and I noticed the version number is now 6.17

After downloading all of a sudden csound crashes when it starts playing any sound, realtime or non. And the csound command line prints this error message which I've never seen:

```
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Library/Frameworks/CsoundLib64.framework/Versions/6.0/../../libs/libsndfile.1.dylib (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Library/Frameworks/CsoundLib64.framework/Versions/6.0/../../libs/libsndfile.1.dylib (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib


csound command: Abort trap
inactive allocs returned to freespace
end of score.		   overall amps:  0.00000
```

**Comment by stekyne** [comment]
```(which was built for Mac OS X 11.0)```

I imagine this is the issue seeing as you're on 10. I'm not sure what's the solution outside of upgrading OS.

**Comment by rorywalsh** [comment]
The version of libsndfile that ships with Csound needs to be compiled with support for an earlier MacOS. That should resolve the issue.

**Comment by janjacobhofmann** [comment]
I can confirm this issue on Mac OSX 12.6 and Csound 6.17: Same output on commandline-rendering and on addition to that blue crashes right away on rendering, both realtime and defered time.

**Comment by janjacobhofmann** [comment]
Here is a solution that worked for me:
1. Do install Csound 6.16.2 again on your Mac OS-System
2. Go to  /Library/Frameworks/CsoundLib64.framework/libs/ and copy the file "libsndfile.1.dylib" to e.g. your dektop
3. Re-install Csound 6.17
4. Go to  /Library/Frameworks/CsoundLib64.framework/libs/ and replace the file "libsndfile.1.dylib" with your copy from version 6.16.2 
5. That should do - enjoy!
