### ISSUE TITLE
Parser Problem in Csound 6.17.0

### ISSUE THREAD

**Issue by markusdichtl** [csound/csound#1601]
Dear Csound Developers,
I think I found a severe bug in Csound 6.17.0. When trying to run the example file FluidEngine.csd which comes with the manual, I get the following error message:

rtaudio: PortAudio module enabled ...
using callback interface
error: syntax error, unexpected T_IDENT  (token "fluidEngine") from file C:/Users/marku/AppData/Local/Temp/csound-tmppjpIccfH.csd (1), line 17:
 >>> gienginenum1	fluidEngine <<<
Unexpected untyped word gienginenum1 when expecting a variable
Parsing failed due to invalid input!
Stopping on parser failure
cannot compile orchestra

The operating system is Windows 10, and I tried both CsoundQT and invokung Csound from the command line. Both failed.

When I tried the previous version, 6.16, there was no problem.

Yours sincerely,
    Markus Dichtl

**Comment by vlazzarini** [comment]
you need to install these opcodes. They are part of plugin libraries and have not been part of the main csound repository since version 6.17. They are part of csound-plugins

**Comment by rorywalsh** [comment]
This isn't a bug, those opcodes no longer come with Csound. Release packages for these opcodes can now be found here:
https://github.com/csound/plugins
Any issues should probably be reported to that repo instead of the main Csound repo. It is confusing that they are still listed in the manual. They should be marked as 3rd party I think.

**Comment by tjingboem** [comment]
This is already mentioned in the manual, in the Description:
"Plugin opcode in fluidOpcodes. This opcode is part of the plugin repository and has to be installed separately. The plugin repository can be found here: https://github.com/csound/plugins"

But i will make a note of this and check again if this is mentioned in the Description for _all_ the plugins- there might be new ones that escaped me.

**Comment by markusdichtl** [comment]
Apology, Thanks, and Doubts

Dear Csound Developers,
my sincere apologies for having molested you with an incorrect bug alarm.
RTFM!
And many thanks for the incredibly quick reaction by several of you! 

However, I feel quite frustrated about the new approach for these plugins. When I look at https://github.com/csound/plugins, there are build instructions for Linux and MacOs, but not for Windows, where I want to use it. I have succesfully built csound from the sources in the (distant) past, but I wonder whether it is really necessary to dive into build processes for opcodes which used to be part of the standard distribution.

Yours sincerely
   Markus Dichtl

**Comment by markusdichtl** [comment]
Dear rorywalsh,
thanks again for your quick response!
Unfortunately, it does not work as you described it. Indeed there is an installer for the windows in Release 1.0, but this does not include fluidOpcodes. Whereas in Version 1.02, which indeed contains fluidOpcodes, only source code is provided.

Yours sincerely,
   Markus Dichtl

**Comment by rorywalsh** [comment]
In that case I'm afraid you will need to build them yourself. Or you could reach out to the author of the plugins and ask them to prepare a build for you. It's frustrating, but it's also not fair to ask the core Csound developers to spend considerable time and effort maintaining plugins they didn't write.
