### ISSUE TITLE
fluidEngine not recognized

### ISSUE THREAD

**Issue by jvonachen** [csound/csound#1605]
I used the installer for csound on windows 10. While trying to generate an audio file by using a midi file as input and using a soundfont I used a sample file:

`<CsoundSynthesizer>
    <CsOptions>
        ;'-F' flag reads in a midi file
        -F test.mid
        -o test.wav -W
    </CsOptions>
    <CsInstruments>
        sr = 44100
        ksmps = 32
        nchnls = 2
        0dbfs = 1

        giEngine     fluidEngine; start fluidsynth engine
        ; load a soundfont
        iSfNum1      fluidLoad          "Yamaha C5 Grand-v2.4.sf2", giEngine, 1
        ; load a different soundfont
        iSfNum2      fluidLoad          "Best of Guitars-4U-v1.0.sf2", giEngine, 1
        ; direct each midi channels to a particular soundfonts
                     fluidProgramSelect giEngine, 1, iSfNum1, 0, 0
                     fluidProgramSelect giEngine, 3, iSfNum1, 0, 0
                     fluidProgramSelect giEngine, 5, iSfNum1, 0, 0
                     fluidProgramSelect giEngine, 7, iSfNum1, 0, 0`

I get an error:

`UnifiedCSD:  test.csd
rtaudio: PortAudio module enabled ...
using callback interface
rtmidi: PortMIDI module enabled

error: syntax error, unexpected T_IDENT  (token "fluidEngine")
 from file test.csd (1), line 13:
 >>> giEngine     fluidEngine  <<<
Unexpected untyped word giEngine when expecting a variable
Parsing failed due to invalid input!
Stopping on parser failure
cannot compile orchestra
end of score.              overall amps:      0.0
           overall samples out of range:        0
1 errors in performance
Elapsed time at end of performance: real: 0.015s, CPU: 0.015s`

I suspect it's because of a missing DLL.
My environment variable for OPCODE6DIR64 is correctly set to C:\Program Files\csound\plugins64
Here is a list of my DLLs in that directory:

02/02/2022  09:05 AM            11,264 ampmidid.dll
02/02/2022  09:05 AM            39,424 arrayops.dll
02/02/2022  09:06 AM            15,872 deprecated.dll
02/02/2022  09:06 AM            17,408 doppler.dll
02/02/2022  09:06 AM            16,896 fractalnoise.dll
02/02/2022  09:06 AM            37,888 ftsamplebank.dll
02/02/2022  09:06 AM            12,800 ipmidi.dll
02/02/2022  09:06 AM            23,552 mixer.dll
02/02/2022  09:06 AM            22,016 osc.dll
02/02/2022  09:06 AM            17,920 padsynth.dll
02/02/2022  09:06 AM            17,408 pmidi.dll
02/02/2022  09:06 AM            27,136 pvsops.dll
02/02/2022  09:06 AM            19,968 rtpa.dll
02/02/2022  09:06 AM            23,040 rtwinmm.dll
02/02/2022  09:06 AM            33,792 scansyn.dll
02/02/2022  09:06 AM            52,736 signalflowgraph.dll
02/02/2022  09:06 AM         2,225,664 stdutil.dll

Shouldn't there be a fluidOpcodes.dll or something like that?

**Comment by vlazzarini** [comment]
This is a plugin and not part of the Csound binaries. The code is kept in the csound/plugins repository. However there is no maintainer for that repository so it needs to be built from sources.

**Comment by jvonachen** [comment]
Based on this I’m moving on to use a tool called timidity++ combined with
ffmpeg.  I’m sure csound is awesome but I really just wanted to take a midi
file and a soundfont and produce an audio file.  Washing my hands of it.
Thanks for your timely response.

**Comment by vlazzarini** [comment]
you can use the original soundfont opcodes instead. These are part of Csound and don't depend on an outside library. 

https://csound.com/manual/SiggenSample.html#SiggenSampleSF

But if you only want to use Fluidsynth, then Csound is really not needed, you can use Fluidsynth directly. The only advantage with Csound is that you can use the rest of it to process sound, make applications, plugins etc.

**Comment by jvonachen** [comment]
Thanks
