### ISSUE TITLE
ftloadk bug

### ISSUE THREAD

**Issue by ReinerZorn** [csound/csound#1611]
I have problems converting a Csound instrument from using ftload to ftloadk and I think it is a bug in ftloadk. A minimal example is here: [ftload_test – Google Drive](https://drive.google.com/drive/folders/1AAQsXdLlLh3UKONcS1yFL8WuVVCtKc4y?usp=sharing)

If I run ftload-test.csd it works as expected rewriting table 1 which was initially length 2048 from file BWV_639.taps. The new length is 287 taken from what is in the file header. The value is printed 10 times at k-time:

    i 1 time 0.00000: 287.00000
    i 1 time 1.00000: 287.00000
    i 1 time 2.00000: 287.00000
    i 1 time 3.00000: 287.00000
    i 1 time 4.00000: 287.00000
    i 1 time 5.00000: 287.00000
    i 1 time 6.00000: 287.00000
    i 1 time 7.00000: 287.00000
    i 1 time 8.00000: 287.00000
    i 1 time 9.00000: 287.00000

In ftloadk-test.csd I just replaced ftload by ftloadk (with the additional argument ktrig set to 1). I would expect that it now reads the file ten times and outputs 10 times 287 again. But the output is

    i 1 time 0.00000: 2048.00000
    Deferred-size ftable 1.000000 load not available at perf time.

So in the first k-cycle it (maybe) read the file but did not change the length of the table. And in the second k-cycle it even crashes (with the above message which I could not find in the documentation). @joachimheintz tested it and found that the crash is due to a segfault.

**Comment by vlazzarini** [comment]
I have fixed this in two parts:

1) the error message is now gone, it is spurious
2) the segfault is addressed (bug in code allocation).

Note that ftlen(x) is i-time only, so when you do `k1 = ftlen(1)` this is not updated at k-rate.
It's fixed in the csound6 branch, but I will apply the fix to develop too now.
