### ISSUE TITLE
Most basic example on website does not work

### ISSUE THREAD

**Issue by joshkopecek** [csound/csound#1612]
I'm just getting started with csound. I have experience programming in other languages, and thought it would be an easy start, but the most simple example on the ['getting started' - your first synthesiser](https://csound.com/get-started.html#your-first-synthesiser) page on the website does not make any sound. I am running a MacBook Pro with macOS Monterey …

1. Installed the latest csound installer from the website
2. Copied and pasted the first example from the getting started page, saved as `test.csd` (no information about file types on that page)
3. Ran `csound test.csd`
4. Nothing played

This is the example I copied in. I tried with and without the `<CsOptions />` section.

``` csound
<CsoundSynthesizer>
<CsOptions>
-odac
</CsOptions>
<CsInstruments>

instr 1
aOut vco2 1, p4
out aOut
endin

</CsInstruments>
<CsScore>
i1 0 1 440
i1 1 1 500
i1 2 1 800
</CsScore>
</CsoundSynthesizer>

```

However, copying in the much more complex example I found after [digging through the manual](https://csound.com/docs/manual/vco2.html) worked fine: 

<details>
  <summary>Expand to show the complex example…</summary>

``` csound
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
; Audio out   Audio in    No messages
-odac ;;;RT audio I/O
; For Non-realtime ouput leave only the line below:
; -o vco2.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr      =  44100
ksmps   =  10
nchnls  =  1

; user defined waveform -1: trapezoid wave with default parameters (can be
; accessed at ftables starting from 10000)
itmp    ftgen 1, 0, 16384, 7, 0, 2048, 1, 4096, 1, 4096, -1, 4096, -1, 2048, 0
ift     vco2init -1, 10000, 0, 0, 0, 1
; user defined waveform -2: fixed table size (4096), number of partials
; multiplier is 1.02 (~238 tables)
itmp    ftgen 2, 0, 16384, 7, 1, 4095, 1, 1, -1, 4095, -1, 1, 0, 8192, 0
ift     vco2init -2, ift, 1.02, 4096, 4096, 2

        instr 1
kcps    expon p4, p3, p5                ; instr 1: basic vco2 example
a1      vco2 12000, kcps                ; (sawtooth wave with default
        out a1                          ; parameters)
        endin

        instr 2
kcps    expon p4, p3, p5                        ; instr 2:
kpw     linseg 0.1, p3/2, 0.9, p3/2, 0.1        ; PWM example
a1      vco2 10000, kcps, 2, kpw
        out a1
        endin

        instr 3
kcps    expon p4, p3, p5                ; instr 3: vco2 with user
a1      vco2 14000, kcps, 14            ; defined waveform (-1)
aenv    linseg 1, p3 - 0.1, 1, 0.1, 0   ; de-click envelope
        out a1 * aenv
        endin

        instr 4
kcps    expon p4, p3, p5                ; instr 4: vco2ft example,
kfn     vco2ft kcps, -2, 0.25           ; with user defined waveform
a1      oscilikt 12000, kcps, kfn       ; (-2), and sr/4 bandwidth
        out a1
        endin


</CsInstruments>
<CsScore>

i 1  0 3 20 2000
i 2  4 2 200 400
i 3  7 3 400 20
i 4 11 2 100 200

f 0 14

e


</CsScore>
</CsoundSynthesizer>
```
</details>

Is there something I'm missing? Should the simple example work?

**Comment by giovannibedetti** [comment]
what you miss should be this line:

`0dbfs = 1`

the first example has audio scaled 0-1, the second one is in the 0-32767 scale, that's why you don't hear sound in the first, it's too low.

See [0dbfs](https://csound.com/docs/manual/Zerodbfs.html)

"The default is 32767, so all existing orcs should work."

**Comment by jpffitch** [comment]
Did you get any output?  If you ad a -v ption is it the sae?

**Comment by vlazzarini** [comment]
the examples are missing 0dbfs=1.
This is bug at the website, not Csound. I'm closing this and filing a ticket there

**Comment by joshkopecek** [comment]
If I export the initial examples to file instead of to the dac, I get this:

![aif file](https://www.dropbox.com/s/cckzopbg0mu886u/test%20aif.png?raw=1)

There are some impulses there, but they're obviously 1 bit amplitude.

I can confirm that setting `0dbfs = 1` does indeed work. It make sense to either add that line to the example, or set the amplitude of each instrument to `32767`, so we know that the default is the number of bits.

I'm sure you've had a discussion about this before, but having the default as 32767 is not exactly intuitive, nor useful. Does this change depending on the bit depth of the output?

It would also be great to add a direction at the top that you can save each example as a *.csd file, since I really had to dig to find out what the default file extension should be.

You could also put simple links to the working examples on https://ide.csound.com/ in 'getting started'.

**Comment by vlazzarini** [comment]
We can't change the default because it breaks backwards compatibility. If there are other bugs relating to the website, please use the csound.github.io ticket tracker.

**Comment by joshkopecek** [comment]
Thank you all for the super prompt response! This has been instrumental in my learning.

Could I suggest that scaling 0dbfs to 1 becomes default in the next major version?

In the meantime I'll suggest this on the website thread.

**Comment by jpffitch** [comment]
Cannot without breaking backwards compatibility rule.

⁣Get TypeApp for Android ​

**Comment by joshkopecek** [comment]
I know csound is a very old platform, but most software nowadays has the opportunity to make breaking changes through a major version bump.

**Comment by vlazzarini** [comment]
We don't break code as a rule, even on major version changes.

**Comment by vlazzarini** [comment]
I am not sure what is the point you are trying to make, but whatever is posted on the Web IDE is not representative of all the code that has been using Csound. The 0dbfs constant was introduced many years after Csound was first released with the normalisation fixed to 32768 and a lot of code/music was written without any reference to 0dbfs.
