### ISSUE TITLE
AuHAL module not working properly for -odac (8 channels)

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#1613]
i start the attached auhal_test.csd with
csound -b256 -B1024 -+rtaudio=auhal -iadc -odac /Users/fmsbw19/Desktop/auhal_test.csd

what i hear is a dignal which scatters for one second between channel 1 and 2, then for the next second between channel 2 and 3, and so on.

please note that this ONLY occurs for -odac.  the render-to-file output is ok.
[auhal_test.zip](https://github.com/csound/csound/files/9033470/auhal_test.zip)

**Comment by vlazzarini** [comment]
Unfortunately, I can't test it as I only have stereo. I presume portaudio is ok?

**Comment by joachimheintz** [comment]
yes portaudio is ok.
we discussed in the csoundqt team whether it would be good to have auhal 
as default for mac, so i tested it.  perhaps you have any chance to get 
to a 8-channel sound card?

**Comment by vlazzarini** [comment]
I recall someone reporting trouble with specific hardware. What soundcard have you used?

**Comment by joachimheintz** [comment]
i use RME Fireface.  there is no similar issue with any other software, 
or with any other RT module (i use eitehr portaudio or jackosx) in the 
configuration.  the console output was:

...
orch now loaded
audio buffered in 256 sample-frame blocks
==========================================================
AuHAL Module: found 1 input device(s):
1: Fireface 802 (23932260) (30 channels)
selected input device: Fireface 802 (23932260)
***** AuHAL module: input device open with 256 buffer frames
reading 4096-byte blks of shorts from adc (RAW)
AuHAL Module: found 2 output device(s):
1: Built-in Output (2 channels)
2: Fireface 802 (23932260) (30 channels)
selected output device: Fireface 802 (23932260)
***** AuHAL module: output device open with 256 buffer frames
==========================================================
writing 2048 sample blks of 64-bit floats to dac
...

**Comment by vlazzarini** [comment]
I did not imply there would be problems with other applications, just that there was a report about the auhal module not working with a specific hardware.

**Comment by vlazzarini** [comment]
I did not imply there would be problems with other applications, just that there was a report about the auhal module not working with a specific hardware.

**Comment by vlazzarini** [comment]
Could you test all 8 channels at the same time, instead of switching? What happens then?

**Comment by joachimheintz** [comment]
yes will do.

**Comment by joachimheintz** [comment]
this is the result:
1. sending noise to all 8 channels also gives a scattered sound.  (it 
sounds like dropouts, but i think the reason is the same channel jump 
which i reported.)
2. setting nchnls=2 is ok.
in other words: it is really a multichannel issue.

**Comment by vlazzarini** [comment]
thanks. Noise is not always that useful, could you try sines instead and see if changing the ksmps makes any difference?

**Comment by vlazzarini** [comment]
I spotted something in the code that may be relevant to multichannel, as I was assuming a certain behaviour that may not be true always. I've tried to modify the code to remove that assumption; I tested it with stereo and it still works. Now the question is whether it fixed it for multichannel. I've pushed the changes to the csound6 branch, so if you could try from there, not sure whether you can build your own. Otherwise I'll try it when I get to a multichannel setup.

**Comment by joachimheintz** [comment]
thanks victor.  i build on linux, but have no setup to build on mac.  so 
let's wait until you have a chance to test yourself on a multichannel card.

**Comment by vlazzarini** [comment]
I was able to test here with a fireface UC. My new code doesn't work, but the old code works fine. I still suspect it's something related to my assumptions of how devices should work but not all do in that way. So I need to fix my new code so it can work here and hopefully will work there too.

**Comment by vlazzarini** [comment]
Ok, it was something else stopping from working, I got this fixed and the new code works just as well as the old in my Fireface UC (tested 8 channels). This new code does not have the same assumptions as the old and so I am now presuming it will work on your device too.

**Comment by joachimheintz** [comment]
i checked today with a macbook pro and two different interfaces: rme 
fireface uc and tascam us 1608.  the result is always as i described: 
"jumping channels".

are you sure you checked with -odac?!?  as i described: the strange 
thing is that it renders correctly; only the real time audio output is 
messed up.

this is the .csd which i ran from command line:

<CsoundSynthesizer>
<CsOptions>
-b256 -B1024 -+rtaudio=auhal -iadc -odac
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 8
0dbfs = 1

instr 1
  aNoise rand .1
  kChnl init 0
  if metro(1) == 1 then
   kChnl = kChnl % 8 + 1
  endif
  outch kChnl, aNoise
endin


</CsInstruments>
<CsScore>
i 1 0 17
</CsScore>
</CsoundSynthesizer>

**Comment by vlazzarini** [comment]
did you build from the latest csound6 git?

**Comment by joachimheintz** [comment]
no i used the module which is part of the csound installer.

i understood that you could not reproduce this behaviour when you tested?

**Comment by vlazzarini** [comment]
yes, I couldn't. However I found something in the code that could lead to channel hopping as you described. So I changed the code and it is still working in my fireface UC. So I have reasons to believe now it's correct and will work on all hardware.

**Comment by vlazzarini** [comment]
what I can do is give you my compiled rtauhal dylib and you can test it. I am on the mobile phone now, but I'll post it here later

**Comment by joachimheintz** [comment]
yes i would be able to test the next days.  i suppose it is possible to 
substitute it in the application bundle?

**Comment by vlazzarini** [comment]
it may be possible. Let's test it and see if it works as it should first.

**Comment by vlazzarini** [comment]
Here's the dylib. Just replace the installed librtauhal with this one to test it.

[librtuahal.zip](https://github.com/csound/csound/files/9125953/librtuahal.zip)

**Comment by joachimheintz** [comment]
BINGO!!! =)
yes now it is all good, and as expected.  i also tested live audio 
input.  it is clean and without any additional latency.

there is only one minor point which is irritating: the CPU time as 
reported by csound is always a bit higher than the real time, for instance:
elapsed time ...: real: 17.053  CPU: 17.352

this cannot be true.  i don't know how csound calculates this CPU time, 
but there must be something wrong with the value it gets from auhal.

**Comment by vlazzarini** [comment]
I think the "real time" may exclude the time auhal uses in processing the buffers.

Prof. Victor Lazzarini
Maynooth University
Ireland

On 17 Jul 2022, at 15:27, joachimheintz ***@***.***> wrote:

﻿
*Warning*

This email originated from outside of Maynooth University's Mail System. Do not reply, click links or open attachments unless you recognise the sender and know the content is safe.

BINGO!!! =)
yes now it is all good, and as expected. i also tested live audio
input. it is clean and without any additional latency.

there is only one minor point which is irritating: the CPU time as
reported by csound is always a bit higher than the real time, for instance:
elapsed time ...: real: 17.053 CPU: 17.352

this cannot be true. i don't know how csound calculates this CPU time,
but there must be something wrong with the value it gets from auhal.

**Comment by vlazzarini** [comment]
release package is now updated with this fixed code.

**Comment by joachimheintz** [comment]
so when you run my example csd there are no jumps with the original code ...
that's strange, as i used RME, too.
i can test in my university in different setups:
different laptops with different interfaces (RME and Tascam)

i will try to do this the next days, and report here.

**Comment by vlazzarini** [comment]
Is there a problem still?
