### ISSUE TITLE
Resolving argumnts to outch broken in cs7; ok in cs6

### ISSUE THREAD

**Issue by jpffitch** [csound/csound#1615]
Runing te mnual example outch-3.csd gives an error

UnifiedCSD:  manual6-git/examples/outch-3.csd
error:  error: opcode 'int' for expression with arg types iaia not found, line 26

 from file manual6-git/examples/outch-3.csd (1)
error:  Unable to find opcode entry for 'outch' with matching argument types:

Found:
  (null) outch @

Candidates:
   outch Z

Line: 26
 from file manual6-git/examples/outch-3.csd (1)
Parsing failed due to syntax errors
Stopping on parser failure
cannot compile orchestra
end of score.              overall amps:      0.0
           overall samples out of range:        0
1 errors in performance
Elapsed time at end of performance: real: 0.001s, CPU: 0.001s

It seems to work with only one output channel but` so far attempts tohave two channels in out outch call ave faied

**Comment by hlolli** [comment]
I've compared the code, and I don't see any smoking gun, it seems in most parts to be the exact same code. But what I do notice on develop, is that the tree seems to be incorrectly ordered, with the int opcall being incorrectly in place of the parent, which is outch.

```xml
 <treeright addresses="(0x600001498870 : 0x0)" type="284" name="T_OPCALL" varname="int" loc="16:./bug.csd">
  <treeleft addresses="(0x600001498410 : 0x600001c997e0)" type="284" name="T_OPCALL" varname="outch" loc="15:./bug.csd">
   <treeleft addresses="(0x6000014983a0 : 0x600001c99790)" type="294" name="T_IDENT" varname="outch" loc="15:./bug.csd">
   </treeleft>
   <treeright addresses="(0x600001498480 : 0x600001c99830)" type="297" name="INTEGER_TOKEN" value="1" loc="15:./bug.csd">
   </treeright>
   <treenext addresses="(0x6000014984f0 : 0x600001c99880)" type="285" name="T_FUNCTION" fname="poscil" loc="15:./bug.csd">
    <treeright addresses="(0x600001498560 : 0x600001c998d0)" type="298" name="NUMBER_TOKEN" value="0.100000" loc="15:./bug.csd">
    </treeright>
    <treenext addresses="(0x6000014985d0 : 0x600001c99920)" type="297" name="INTEGER_TOKEN" value="440" loc="15:./bug.csd">
    </treenext>
   </treenext>
   <treenext addresses="(0x600001498640 : 0x600001c99970)" type="285" name="T_FUNCTION" fname="int" loc="15:./bug.csd">
    <treeright addresses="(0x6000014986b0 : 0x600001c999c0)" type="297" name="INTEGER_TOKEN" value="2" loc="15:./bug.csd">
    </treeright>
   </treenext>
   <treenext addresses="(0x600001498720 : 0x600001c99a10)" type="285" name="T_FUNCTION" fname="poscil" loc="15:./bug.csd">
    <treeright addresses="(0x600001498790 : 0x600001c99a60)" type="298" name="NUMBER_TOKEN" value="0.100000" loc="15:./bug.csd">
    </treeright>
    <treenext addresses="(0x600001498800 : 0x600001c99ab0)" type="297" name="INTEGER_TOKEN" value="440" loc="15:./bug.csd">
    </treenext>
   </treenext>
  </treeleft>
 </treeright>
 ```
 
 this is a debug log when I ran this snippet
 
 ```csound
 instr 1
  outch int(1), poscil:a(0.1, 440), int(2), poscil:a(0.1, 440)
endin
```

**Comment by hlolli** [comment]
it seems it comes out initially incorrect like that after `csound_orcparse`

```xml
AST - AFTER csound_orcparse()
<ast>
....
 <treeright addresses="(0x60000264c870 : 0x0)" type="284" name="T_OPCALL" varname="int" loc="17:./bug.csd">
  <treeleft addresses="(0x60000264c410 : 0x600002e4d7e0)" type="284" name="T_OPCALL" varname="outch" loc="16:./bug.csd">
   <treeleft addresses="(0x60000264c3a0 : 0x600002e4d790)" type="294" name="T_IDENT" varname="outch" loc="16:./bug.csd">
   </treeleft>
   <treeright addresses="(0x60000264c480 : 0x600002e4d830)" type="297" name="INTEGER_TOKEN" value="1" loc="16:./bug.csd">
   </treeright>
   <treenext addresses="(0x60000264c4f0 : 0x600002e4d880)" type="285" name="T_FUNCTION" fname="poscil" loc="16:./bug.csd">
    <treeright addresses="(0x60000264c560 : 0x600002e4d8d0)" type="298" name="NUMBER_TOKEN" value="0.100000" loc="16:./bug.csd">
    </treeright>
    <treenext addresses="(0x60000264c5d0 : 0x600002e4d920)" type="297" name="INTEGER_TOKEN" value="440" loc="16:./bug.csd">
    </treenext>
   </treenext>
   <treenext addresses="(0x60000264c640 : 0x600002e4d970)" type="285" name="T_FUNCTION" fname="int" loc="16:./bug.csd">
    <treeright addresses="(0x60000264c6b0 : 0x600002e4d9c0)" type="297" name="INTEGER_TOKEN" value="2" loc="16:./bug.csd">
    </treeright>
   </treenext>
   <treenext addresses="(0x60000264c720 : 0x600002e4da10)" type="285" name="T_FUNCTION" fname="poscil" loc="16:./bug.csd">
    <treeright addresses="(0x60000264c790 : 0x600002e4da60)" type="298" name="NUMBER_TOKEN" value="0.100000" loc="16:./bug.csd">
    </treeright>
    <treenext addresses="(0x60000264c800 : 0x600002e4dab0)" type="297" name="INTEGER_TOKEN" value="440" loc="16:./bug.csd">
    </treenext>
   </treenext>
  </treeleft>
 </treeright>
 ...
 ```

**Comment by jpffitch** [comment]
Are you saying that the tree is created incorrectly by the parser?  I do not know what is expected

**Comment by hlolli** [comment]
@jpffitch it's actually not incorrect, this output is expected based on the grammar rules, it's just that the grammar of csound is inherently ambiguous, which is fine, but the way Steven has solved it, is to test for trees that are out of order, and re-arrange the tree nodes based on disambiguation of the identifiers.
This is fixed in my PR if you have time to test and review it https://github.com/csound/csound/pull/1674

**Comment by jpffitch** [comment]
Loking again the meanual example is in error.  outch has arguments og type Z which is alternating k- and a- rate objects.  Removing the ind() calls allows  thei rate to be recognised as k rate.

I have changed the example.

**Comment by jpffitch** [comment]
Closing as it is solved

**Comment by joachimheintz** [comment]
are you saying that this call to outch is wrong:
outch     int(ichn1), a1, int(ichn2), a2
(from https://csound.com/docs/manual/examples/outch-3.csd)

what is your change to the manual example?

**Comment by jpffitch** [comment]
On Sat, 27 Jan 2024, joachimheintz wrote:

> 
> are you saying that this call to outch is wrong:
> outch int(ichn1), a1, int(ichn2), a2
> (from https://csound.com/docs/manual/examples/outch-3.csd)



Exactly

> 
> what is your change to the manual example?
> 
>

outch ichn1, a1, ichn2, a2

**Comment by joachimheintz** [comment]
i can not follow you:
the first argument to outch is supposed to be an integer.
the ichn1 variable in the example will be a float.
what is wrong in converting this float to an integer?

**Comment by vlazzarini** [comment]
The discussion on the manual example can be taken elsewhere. The issue has been fixed.
