### ISSUE TITLE
rndseed not working

### ISSUE THREAD

**Issue by ST-Music** [csound/csound#1625]
it doesn't turn orange in the included editor and has no effect, for me anyways.

Csound for Android
version code: 30
library version: 6160
Android version 7.0
--

**Comment by vlazzarini** [comment]
I tested the manual example on MacOSX, using the latest version of Csound and it worked as expected. The problem of highlighting is nothing to do with Csound. I suggest you open a ticket with the Csound for Android developer at his github project

https://github.com/gogins/csound-android

**Comment by ST-Music** [comment]
Thank you for the prompt reply. I opened a ticket as suggested.

Scott Daughtrey
SToons Music
https://soundcloud.com/stoons-1

https://youtube.com/channel/UCGhwmkS1uWmX6mhTIQ0IDsg
