### ISSUE TITLE
delete sf_GMbank.sf2 from /csound/samples

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#1626]
the soundfont sf_GMbank.sf2 is at present part of /csound/samples, toghether with the hrtf data and its README.
But they are also present in the examples folder of the manual. Which i think is the better place as this soundfont is used in examples of the manual.
Therefor the sf2 can be deleted from /csound/samples?

**Comment by vlazzarini** [comment]
I would keep them there. Its purpose is different, for testing.

**Comment by tjingboem** [comment]
if they serve a purpose they should be available for sure!
I'll close the issue, thanks.
