### ISSUE TITLE
Segmentation fault  Bol Processor

### ISSUE THREAD

**Issue by Aman1531** [csound/csound#1632]
I have Csound 6.17 installed on Arch linux
It is not working with Bol Processor .
The issue occurs whenever php executes csound through Apache 
Exit status is 139 
Issue persists when I downgraded to csound 6.16

**Comment by vlazzarini** [comment]
We don't have much to go on here. Unless you can give us an example of the Csound code that is causing the segfault, we can't diagnose it.

**Comment by Aman1531** [comment]
Segfault happens whenever I call the following script through Apache & Lighttpd servers :
There is no problem with exec as other bash commands are working
<?php
$output=null;
$retval=null;
exec('csound --version', $output, $retval);
echo "Returned with status $retval and output:\n";
print_r($output);
?>

**Comment by vlazzarini** [comment]
Well, try that command line outside of the server, in the terminal. If it crashes, then it's to do with Csound, if not, it isn't really.

It certainly doesn't crash here so I have no clue as to what your problem is.

**Comment by Aman1531** [comment]
It only crashes when called through server . I tested with Apache & lighttpd

**Comment by vlazzarini** [comment]
ok, so there is nothing we can do, you need to open a ticket with Bol Processor. It could be a memory issue within their configuration. I'm closing this ticket. If there is a bug with instructions on how to reproduce it using Csound only, we can look at it again.
