### ISSUE TITLE
Bug in sum-opcode?

### ISSUE THREAD

**Issue by janjacobhofmann** [csound/csound#1636]
There seems to be a bug that clears the audio of an a-rate variable if the name of the variable is the same for input and output. The result is a different behavior of the sum-opcode to simple addition using a "+"-sign.

It occurs (at least) at these Csound-versions:

6.18 (double samples) May 30 2022 (which I compiled from git-sources on Ubuntu 20.4)
6.18 (double samples) Sep 26 2022 [commit: 0202b14ac91c4e297e99462333116a537cb4790b]
(which I compiled from git-sources on Ubuntu 20.4)

Here is a .csd to test it:
instr. 1 does sound different to instr. 2
The only thing I changed is to use "+" instead of "sum" in instr. 2.
in my setup the 683hz-tone gets trough only in the second instrument where "+" is unsed instead of "sum". In instr 1 there is only the 440hz tone audible, the 683hz sound is missing...actually there should be no difference between the output of both instruments.

<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>
sr = 44100
ksmps = 128
nchnls = 2
0dbfs = 1.0

instr 1

aout = 0
aout0 oscil .2, 683
aout sum aout, aout0
aout1 oscil .2, 440
aout sum aout, aout1
outs aout, aout
endin

instr 2
aout = 0
aout0 oscil .2, 683
aout = aout + aout0
aout1 oscil .2, 440
aout = aout + aout1
outs aout, aout
endin

</CsInstruments>
<CsScore>

i1 0 1
i2 1.2 1

</CsScore>
</CsoundSynthesizer>

Reply and fix by Eduardo Moguillansky ath the Csound-list on September 26th 2022 at 23:32:25 MESZ:

"The problem relies on the fact that the output variable is used as the accumulator for the sum and is cleared at the beginning of each cycle.

Here is a fix: https://github.com/csound/csound/pull/1634

Eduardo"

See also fix sum #1634

**Comment by vlazzarini** [comment]
this has already been merged, is there anything outstanding?

**Comment by vlazzarini** [comment]
https://github.com/csound/csound/commit/a7adfccf4971817f6a71c26c095b2ad80ab4f768
