### ISSUE TITLE
windows installer - wrong location..

### ISSUE THREAD

**Issue by rorywalsh** [csound/csound#1637]
I just noticed that the windows installer for 6.17 now installs to `C:/Program Files/csound/` whereas it should install to `C:/Program Files/Csound6_x64` @stekyne can you update this? It happened before and broke a lot of existing things. It also breaks the FindCsound.cmake script that is used across a number of Csound projects.

**Comment by stekyne** [comment]
It seems like this was changed back a year ago: https://github.com/csound/csound/commit/f0e1af34bbd180fccb45054b6372a0a465cf3620

Do you want this fixed in the version 6 branch or just 'develop'? The former can be done but I think for version 7 and going forward, maybe it should be different. I think either going with `csound/v7` or something to avoid having `csound6` + `csound7` alongside is better.

**Comment by rorywalsh** [comment]
Oh, so long ago? I use my own Csound installer with Cabbage which is why I never noticed. I think it should be like this for all version 6.n releases. Going forward I have no issues with two different install locations for version 6 and 7. `Csound6_x64` and `Csound7_x64` seem fine to me. Otherwise we will have to retrofit the version 6 installers to install into `csound/v6/`, and we will also need to update any previous build scripts to point to the new `v6` location?

**Comment by stekyne** [comment]
https://github.com/csound/csound/commit/cc42b318df45f782daf286304b05ee79d2d91857 This is commited now but I guess you might need to create a release or else use the build artifact.

**Comment by rorywalsh** [comment]
Thanks @stekyne I will wait for 6.18, that should be out soon I hope 👍

**Comment by vlazzarini** [comment]
Hi @stekyne I noticed this morning that the Windows build on csound6 branch is failing. Csould you take a look? Thx.

**Comment by stekyne** [comment]
@vlazzarini thanks. I see that the ci file needed to be updated as well. It's working now

**Comment by vlazzarini** [comment]
great, thanks!
