### ISSUE TITLE
rifft segfaults for non n^2+1 arrays

### ISSUE THREAD

**Issue by hlolli** [csound/csound#1638]
it came to my attention that the following code segfaults

```csound
instr 1
  iTabSize = 1024
  kFreqAmp[] init iTabSize
  kFreqPhase[] init iTabSize
  kSpectralSignal[] pol2rect kFreqAmp,kFreqPhase
  kRow[] rifft kSpectralSignal
endin
```

and this one doesn't

```csound
instr 1
  iTabSize = 1025
  kFreqAmp[] init iTabSize
  kFreqPhase[] init iTabSize
  kSpectralSignal[] pol2rect kFreqAmp,kFreqPhase
  kRow[] rifft kSpectralSignal
endin
```

so it's just a matter of giving a better error message to the user in this case

**Comment by vlazzarini** [comment]
well, it only works for pow of 2, but it should not segfault either. I will check it.

**Comment by hlolli** [comment]
thanks @vlazzarini !

**Comment by vlazzarini** [comment]
also note some additions to the manual to clarify the behaviour: https://github.com/csound/manual/commit/32fa22b32500961688ed8573fe59cb7d3c594755
