### ISSUE TITLE
OSCsend error when send without arguments

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#1639]
instr 1
OSCsend(1,"",7770,"/foo/bar")
endin
schedule(1,0,1)

error:  Unable to find opcode entry for 'OSCsend' with matching argument types:
Found: (null) OSCsend cScS

it should work, according to the manual.  and some software require receiving only the OSC address, returning an error if anything else is being sent in addition.

--Csound version 6.17 (double samples) Oct  8 2022
[commit: 95007834d8afc68b9ae465a6f65b93b23ae41709]

**Comment by vlazzarini** [comment]
I think the manual may be wrong, as the opcode intypes require another string, with the types. 

This is the case both with OSCsend and OSCsend_lo, so I am guessing that was always the intention.

'''
   { "OSCsend", S(OSCSEND2), 0, 3, "", "kSkSS*", (SUBR)osc_send2_init,
     (SUBR)osc_send2 },
'''


'''
  { "OSCsend_lo", S(OSCSEND), 0, 3, "", "kSkSS*",
    (SUBR)osc_send_set, (SUBR)osc_send, NULL,NULL },
'''


 They never worked without the types. I think the OSC message can carry no data (as per the spec) but then the types need to be an empty string.

@jpffitch wrote this originally, so maybe he can say how it should be.

**Comment by joachimheintz** [comment]
can this limitation be suspended?
otherwise it would not be possible to send the "/oscVideo/setVideoPlay" 
message to pyoscvideo: https://pypi.org/project/pyoscvideo/
this was the reason i cam across this issue. there may be other similar 
cases.

**Comment by vlazzarini** [comment]
I thought that adding "" would do the job. Does it not?

OSCsend ktime, Sdest, iport, "/foo/bar", ""

**Comment by joachimheintz** [comment]
no, unfortunately not:

OSCsend(1,"",12000,"/test","")
returns this error:
error:  insufficient required arguments for opcode OSCsend on line 13:

**Comment by vlazzarini** [comment]
Ok, then it's all broken. Try the latest commit. I've changed it so that it can run without the types (or with an empty string for types).

**Comment by vlazzarini** [comment]
It's passing my tests here. I have also set OSCsend_lo and OSClisten to work with zero-data messages (OSClisten needs empty types though as per the manual, where types are not optional)

**Comment by joachimheintz** [comment]
yes it works now =)
thanks so much!!

**Comment by kunstmusik** [comment]
Closing this as the discussion mentions it is fixed.
