### ISSUE TITLE
trim error 

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#1642]
according to the manual, the trim opcode can both, shorten or lengthen an array:
"Makes the array the desired length, either truncating or padding with zero/Null values."

shorten works, but lengthen returns an error:

instr 1
 kArr[] fillarray 1,2,3,4,5
 trim kArr, 10
endin

PERF ERROR in instr 1 (opcode trim.k) line 13: Array too small (allocated 40 < needed 80), but cannot allocate during performance pass. Allocate a bigger array at init time

**Comment by hlolli** [comment]
I can add that this isn't a problem on the develop branch (csound7). Is this still happening in csound6?

**Comment by kunstmusik** [comment]
Tested with latest from develop and got the same error as mentioned by @joachimheintz. Will schedule this for 7.0.0 as a bug to fix.

**Comment by vlazzarini** [comment]
I know this is marked as a bug, but should we allow memory allocation at perf time?

**Comment by jpffitch** [comment]
The manua is just wrong.  The code does no allocation,  so suggestion that it might,  and can only change 
the size to within the original allocation.
And yes, it should not do any memory allocation at perf-time.

I think it should be "will not fix" or "documentation error" sand the issue closed

**Comment by kunstmusik** [comment]
Thanks @jpffitch and @vlazzarini for chiming in. I've marked as won't fix.

@joachimheintz and @csound/documentation: We'll need an update to trim manual to reflect this information. I've filed https://github.com/csound/manual/issues/692 with a reference to this issue.
