### ISSUE TITLE
--limiter=.95 not relaxed

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#1643]
as a default, i use the limiter command flag in the output as a protection mechanism.
The flag and value i set is  **--limiter=.95**

When i set this flag to 
**--limiter= .95**
or
**--limiter =.95**
i get an error.
Can the use be more relaxed, so that **--limiter = .95** would work also?

**Comment by jpffitch** [comment]
Can you tell me the error you ge?  I am not seeing any errors or problemd

==John ff

**Comment by tjingboem** [comment]
I am working from Blue.
The command Blue produces:
```
Render Command ( csound -+rtaudio=JACK -o dac:system:playback_ -d -m1 --limiter= .95 /media/menno/datae/onderzoek/BLUEinstruments/partikkel/tempCsd16740495160099940326.csd --env:SFDIR=/media/menno/datae/onderzoek/BLUEinstruments/partikkel )
orchname:  .95
main: failed to open input file - .95
```

it seems to see it as part of an input file?

**Comment by vlazzarini** [comment]
there's a space before .95 so it's read as a different option

**Comment by tjingboem** [comment]
yes that is it.
Is that normal behavior? Or can this be changed so that a space here and there is allowed?

**Comment by vlazzarini** [comment]
normal behaviour. Afaik, spaces in this case make the argdecode parse options into different tokens. John might know more

**Comment by tjingboem** [comment]
> I will bear it in mind but i am not hopeful
> of seeing how to skip to the next option string. 

thanks for the explanation. I understand it is a lot of work but will keep this issue open for now.
Perhaps i can add a Note to the manual about not using spaces or else an error will be given.

**Comment by rorywalsh** [comment]
For now could we print a warning if the first character detected after the = is a whitespace?

**Comment by tjingboem** [comment]
It is not only after but also before.
For example **--format=alaw**
is correct but
**--format =alaw**
and
**--format= alaw**
is not
And **--format = alaw** etc.

I make an error like this easily because many programs that i run from the Terminal know how to deal with these spaces.
It took me quite some time to figure out why the csd was not working....

Perhaps the error report could be more clear? Like: "error due to unrecognized format in the flag"
This would prevent me for looking for the error in the instrument or score, and point to the right direction.

**Comment by DaveSeidel** [comment]
This really is standard behavior for command line processing. I don't think
we should consider it an error. If blue is generating command lines with
spaces before or after "=" in some circumstances then that should be fixed.
But IMO this is working the way it is supposed to work.

**Comment by tjingboem** [comment]
Okay, thanks. 
Then it is user error as i did put in that extra space. Blue does not generate this space, i did :-)

I will close the issue, thanks all for the information!
