### ISSUE TITLE
iOS libs in v6.18 are exactly the same as the ones in v6.17

### ISSUE THREAD

**Issue by giovannibedetti** [csound/csound#1645]
I'm trying to update the iOS libs in CsoundUnity, but the new ones look exactly the same as the 6.17 ones, and git is detecting no change at all.
![Csound ios libs](https://user-images.githubusercontent.com/1912983/198844250-4e24e4c4-2616-4ac7-97c7-70c061d79b4e.png)

**Comment by vlazzarini** [comment]
what version does it say when it runs?

**Comment by giovannibedetti** [comment]
Unfortunately I cannot test them because I have no iOS device, so my observation is purely based on their size, and the fact that git is not detecting any change from the 6.17 ones

**Comment by vlazzarini** [comment]
uploaded a new installer fixing this.
