### ISSUE TITLE
printks prints only once in loop

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#1654]
Is this expected behavior?
A question for adapting the manual was made, but i wonder if there is something not correct about the printing in printks?

Please check the issue here:
https://github.com/csound/manual/issues/660

**Comment by hlolli** [comment]
there's printks2, I feel there should be a deprecation warning

**Comment by vlazzarini** [comment]
they're different, one has a time count, the other prints on change of value. None is supposed to be deprecated.

**Comment by hlolli** [comment]
correct, big difference :)

It seems then it's a misunderstanding on the side of the manual. Given that printks with 0 time count will never behave the same way as printks2. But maybe I'm misunderstanding something. But let's close the ticket if this is a non issue?

**Comment by tjingboem** [comment]
i still think it is confusing.
_itime -- time in seconds between printings._
so i would expect that each time a new value is printed, the phrase "hello loop" would be printed with it immediately (time 0).
But it is not.
 
It might be good to have some remark in the manual on this imo? 
Don't know what though.

**Comment by hlolli** [comment]
Correct me if I'm wrong here. But it seems this is exactly the same situation as we have with printk vs printk2, where if you place 0 to printk, it will print on every ksmps, in a manner that k-rate signals behave, there's to say, on every ksmps, even if it's under if-else or while/until blocks (behaving like a signal).

**Comment by vlazzarini** [comment]
why we don't close this ticket and move this as doc issue to the manual?

**Comment by tjingboem** [comment]
yes it is a documentation issue.
I will close the issue.
