### ISSUE TITLE
Windows Visual Studio Project Build Issue

### ISSUE THREAD

**Issue by composingcap** [csound/csound#1655]
When building Csound 7 using VS and cmake on Windows

Doxygen causes VS project to fail. I have tried uninstalling and re-installing doxygen, but it does not seem to solve the issue.   There are also a number of libraries not being found, but I think that is on my end...  When remove the doxygen bits from cmake list, cmake create the VS solution.

[CMakeError.log](https://github.com/csound/csound/files/9998336/CMakeError.log)
[CMakeOutput.log](https://github.com/csound/csound/files/9998337/CMakeOutput.log)

**Comment by vlazzarini** [comment]
If you remove doxygen from the system, CMake will not use it. You will need to clear your CMake build cache though before trying again. 

Which branch are you trying to build? I have added an option to switch off docs build (set to OFF by default) to the develop branch.

**Comment by composingcap** [comment]
I was using the develop branch- though getting csound through the vs packages will make this a non-issue correct?

**Comment by vlazzarini** [comment]
Not sure, but the build should succeed anyway. I have just added that switch, so that would remove doxygen build by default.
