### ISSUE TITLE
'_m4eof'  _m4eof added the csound_orchparse.h on VS compile

### ISSUE THREAD

**Issue by composingcap** [csound/csound#1656]
When I configured my cs7 solution using cmake for VS "'_m4eof'  _m4eof " was added to the end of the csound_orcparse.h file. [Doing some searching](https://stackoverflow.com/questions/58250278/win-bison-inserting-m4eof-to-the-end-of-the-generated-parser), it seems winflexbison may be adding this to the end of the file due to a configuration issue, but is really just a few forum posts. 

When I manually remove the lines it will compile. (have not gotten it to run just yet...)

**Comment by vlazzarini** [comment]
csound_orchparse is going to be recreated every time you build, so editing it by hand will not work.

Note that Csound is built on Windows by the github actions CI, so you can always get the latest build from there.

If you want to build your own, you can check the build scripts used by the CI to get your build done correctly.

Look at .github in the repository.

**Comment by vlazzarini** [comment]
I'm closing this issue, because there is nothing to do. I suggest getting support for builds from the mailing lists (see csound.com for info).
