### ISSUE TITLE
csound wasm docs?

### ISSUE THREAD

**Issue by felixroos** [csound/csound#1658]
First of all thanks for the amazing work with this project! I am really interested in how to use the wasm build of csound (ideally through npm), but I cannot find any docs on how to use it . Google still thinks there should be a page under https://csound.com/wasm/ (search "csound wasm").. Similarly, https://csound.com/docs/web/ is also a dead link. Other things I've found:

- https://www.npmjs.com/package/csound-wasm looks outdated, also with an empty readme
- https://www.npmjs.com/package/libcsound also seems outdated + empty readme. found in the current csound flossmanual
- https://github.com/gogins/csound-wasm is the only thing with instructions that also worked, though it's not the official thing
- https://github.com/csound/csound/tree/master/wasm/browser seems like the active thing, also has an API doc, but no info on how to integrate the package

Is there anything I've missed? Am I expected to read the source of the web the Web IDE to know how to use this stuff?

**Comment by vlazzarini** [comment]
The two sites given by Google contained older versions and so they were removed by me to avoid more confusion. The site hosted by Mike Gogins also appears to hold an older version, but we have no control over that. 

The official NPM package can be got through

```
npm install @csound/browser
```

and the API reference is placed here https://github.com/csound/csound/tree/master/wasm/browser 

The authors @hlolli and @kunstmusik have made a tutorial, which they presented at the ICSC 2022,
hosted at https://kunstmusik.github.io/icsc2022-csound-web, showing how to get started with it in a web 
app development environment (npm, vide, etc).

I am preparing a vanilla guide, [the Absolute Vanilla Guide to Webaudio Csound](https://vlazzarini.github.io/vanilla/), hosted
at https://github.com/vlazzarini/vanilla.

I agree that a more central portal to Webaudio Csound (aka Csound on the Web, Csound WASM) would be a great addition, however we don't even have a maintainer for http://csound.com, so this looks unlikely as the developers do not have time to do this (a distraction from much needed work on the 7.0 version).

**Comment by joachimheintz** [comment]
wouldn't it be useful to put this all on csound.com/wasm?
i can volunteer for it, at least after december 10.

**Comment by kunstmusik** [comment]
Agreed, I'd like to see either:

1. icsc site be cloned and move to csound/wasm so it is served up as csound.com/wasm. Documentation for Vanilla be added as a tutorial to the site so that all relevant information is together.  
2. csound.com be migrated to docusaurus and the contents of the tutorial added to it. I find docusaurus a nice system that is easy to use and works with markdown pretty similarly to the jekyll-based site that we have been using the past years. 

Could also migrate csound.com to docusaurus as well as keep wasm as a separate docusaurus site.

**Comment by joachimheintz** [comment]
sounds great.  i have no idea how to do this migration, but once it is 
there, i can put in some work to update contents.

**Comment by vlazzarini** [comment]
That could work. As far as the vanilla guide is concerned, it's built as a repository, so I am not quite sure yet how to adapt it. The text is in the readme.md files and the example in the index.html files.

If there is some simple means of displaying the contents of the md files as formatted html, that's solved. We can just have a link from csounds.com or even serve the pages directly from there. That would allow me a simple way to maintain it too.

**Comment by felixroos** [comment]
> The Csound WASM authors @hlolli and @kunstmusik have made a tutorial, which they presented at the ICSC 2022. This is hosted at https://kunstmusik.github.io/icsc2022-csound-web, showing how to get started with it in a web app development environment (npm, vide, etc).
> 
> I am preparing a vanilla guide, [the Absolute Vanilla Guide to Webaudio Csound](https://vlazzarini.github.io/vanilla/), hosted at https://github.com/vlazzarini/vanilla.

Thank you, those resources look helpful! Should also be handy if they were linked in the readme somewhere. 
Anyways I  will now go play with csound a little bit, hoping to find a way to use it as an audio backend for [strudel](https://strudel.tidalcycles.org/).

**Comment by gogins** [comment]
I have implemented a Csound back end for Strudel in my fork of strudel:
https://github.com/gogins/strudel.

This contains some things that need to be changed, notably I do not know
how to create a package, so for now, the `csnd` function for Patterns that
sends notes to Csound has been stuck into the midi package. I also added an
extended embedded IFrame for the REPL that has a few methods that the
hosting code can call, e.g. to synchronise starting and stopping Csound and
the REPL at the same time.

However, it works. I have an example working in my cloud-music repository
here:
https://github.com/gogins/cloud-music/blob/strudel-integration/docs/cloud_music_no_5.html
.

You can get this working locally by cloning branches of Strudel and
cloud-music, running npm run setup and npm run build in strudel, and copy
the strudel/out directory's contents to the cloud-music/docs directory,
then any Web server can serve this piece.

I will have this live in my cloud-music Web server in the next day or so.

Best,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by kunstmusik** [comment]
I have forked the tutorial website that @hlolli and I put together for ICSC 2022 to https://github.com/csound/wasm and updated the documentation URLs to point to the new hosting site:

https://csound.com/wasm/

Closing this issue as completed and will announce on the csound user list.
