### ISSUE TITLE
csoundGetSpoutSample returns 0 on iOS

### ISSUE THREAD

**Issue by giovannibedetti** [csound/csound#1659]
We're facing an issue on CsoundUnity for iOS, we have no output from Csound using the API.
We're running the same exact code that runs great for Windows, macOS and Android.
Everything happens in the [ProcessBlock](https://github.com/rorywalsh/CsoundUnity/blob/a6928348993669f12787da49f124d0bef1430611/Runtime/CsoundUnity.cs#L2528) method in CsoundUnity.
Printing the values coming from Csound results in a <s>NaN</s> 0 -> edit, see below comment.
Testing branch is here: `https://github.com/rorywalsh/CsoundUnity.git#fix/ios_builds`
It can be imported in the Unity Package Manager pressing +, then _Add package from git URL_, and pasting the above url
Import the BasicTest sample.
Under BuildSettings select iOS and then click Switch Platform, then build.
Be sure to set a teamID under the PlayerSettings or set it in the created XCode project.

**Comment by giovannibedetti** [comment]
The issue was caused by zerdbfs not being set correctly on start, and so the division by 0 was causing NaNs.
Sorry for the false alarm!
But still, the native method always returns 0.

**Comment by vlazzarini** [comment]
I can only think that if getSpoutSample is producing zero can be for a couple of reasons: 

- the spout buffer has nothing in it, which my could be because no instrument is notrunning or the opcodes out/outs/outch etc are not used, or because the performKsmps() function has not been called.

- trying to read beyond the ksmps frames position may give funny results too.

So I think the first check is to see whether there is something in the spout buffer. You can do that by verifying that an instrument is actually running (eg print something at krate to the console) and that it's writing to the output. Or you can look at spout directly by getting its address from csoundGetSpout(). 

I think this may be a symptom of another underlying condition (like csoundPerformKsmps()) not running.

**Comment by giovannibedetti** [comment]
Hi Victor, thanks for your answer.
I made some tests. 
PerformKsmps runs correctly and returns 0 so the performance should be running.
But there is some other issue I noticed, it looks like I'm not able to set values using SetControlChannel.
Attached the logs of the first second of execution, where I'm setting a frequency of 220 and an amp of 0 from C#.
As you can see, the frequency doesn't change:

```
setting freq: 220 amp: 0
aout: 0.000000 kfreq: 0.000000, kamp: 0.000000, ktime: 0.000023
setting freq: 220 amp: 0
aout: 0.000000 kfreq: 0.000000, kamp: 0.000000, ktime: 0.100023
setting freq: 220 amp: 0
aout: 0.000000 kfreq: 0.000000, kamp: 0.000000, ktime: 0.200023
setting freq: 220 amp: 0
Csound.TableMorph.Theremin.Theremin:Update()
aout: 0.000000 kfreq: 0.000000, kamp: 0.000000, ktime: 0.300023
```
First line is C# output, second line is Csound output and so on.
ktime is the value returned by the opcode _times_

full log of first second of execution: [first_second.txt](https://github.com/csound/csound/files/10145309/first_second.txt)

Some seconds later:

```
setting freq: 353.3528 amp: 0.8046875
aout: 0.000000 kfreq: 2.000000, kamp: 0.000000, ktime: 9.000023

setting freq: 353.3528 amp: 0.8046875
aout: 0.000000 kfreq: 2.000000, kamp: 0.000000, ktime: 9.100022

setting freq: 353.3528 amp: 0.8046875
aout: 0.000000 kfreq: 2.000000, kamp: 0.000000, ktime: 9.200023

setting freq: 353.3528 amp: 0.8046875
aout: 0.000000 kfreq: 2.000000, kamp: 0.000000, ktime: 9.300022
```

Filtering only the Csound logs that prints the audio output, the freq, the amp and the performance time, I noticed some strange values, that make me think about some wrong Marshalling could be happening:

```
aout: 0.000000 kfreq: 2.000000, kamp: 0.000000, ktime: 11.500023
aout: 0.000000 kfreq: -2.000000, kamp: 0.000000, ktime: 11.600022
aout: 0.000000 kfreq: 0.000000, kamp: 0.000000, ktime: 11.700023
aout: 0.000000 kfreq: 36893488147419103232.000000, kamp: 0.000000, ktime: 11.800022
aout: 0.000000 kfreq: -36893488147419103232.000000, kamp: 0.000000, ktime: 11.900023

```

20 seconds of Csound logs: [aout.txt](https://github.com/csound/csound/files/10145317/aout.txt)

But also the simplest possible csd is not producing any output on device (and 0dbfs is 0 if retrieved using the API), even if printing the output in Csound returns correct values:

```
<Cabbage>
form caption (“Basic Test”), size(300, 100)
</Cabbage>
<CsoundSynthesizer>
<CsOptions>
-n
</CsOptions>
<CsInstruments>
sr = 24000
ksmps = 32
nchnls = 2
0dbfs = 1

instr 1
a1 oscil .2, 440, 1
printks “a1: %f”, 0.05, a1
outs a1, a1
endin
</CsInstruments>
<CsScore>
f0 3600
f1 0 4096 10 1
i1 0 50
</CsScore>
</CsoundSynthesizer>
```

C#
`var output = (float)GetOutputSample((int)ksmpsIndex, (int)outputSampleChannel) / (float)csound.Get0dbfs();
Debug.Log($"Csound output: {output}, 0dbfs: {(float)csound.Get0dbfs()}");`

and the output is:

```
a1: 0.177102
Csound output: NaN, 0dbfs: 0
```

If I remove the division by 0dbfs (which I will need at some point) this is the log:

`Csound output: 0, 0dbfs: 0`

What do you think?

I will investigate more into the Marshalling / Native calls in the next days ([CsoundCsharp](https://github.com/rorywalsh/CsoundUnity/blob/master/Runtime/CsoundCsharp.cs)).

**Comment by vlazzarini** [comment]
yes, I think it looks like the API calls are not passing the data back correctly, because of the discrepancy between what you get Csound to print and what comes out from the calls.

I would not think there is a reason for the API to fail like that, so maybe it is the Csharp interfacing with it.

**Comment by vlazzarini** [comment]
Great you found it. You may want to check for the USE_DOUBLE token, this is defined (or not, depending on the version) in float-version.h

**Comment by giovannibedetti** [comment]
Thanks, I wasn't aware of the existence of that file!
I suppose I would have to change the -DUSE_DOUBLE to 1 here in the iOS build.sh also, right?
https://github.com/csound/csound/blob/a1580f9cdf331c35dceb486f4231871ce0b00266/iOS/build.sh#L6

**Comment by vlazzarini** [comment]
No, unless you want to build your own version of Csound for iOS using doubles. This CMake option controls whether it is a floats or double version you are building. We distribute a floats version for iOS (I suppose we could review this, but that is what the 6.18 iOS package is). Once the library is built and installed, you can use float-version.h to determine what version is  being used.

**Comment by giovannibedetti** [comment]
Ok perfect, thanks.
Floats are perfectly fine for now, but maybe some users could want double support for their iOS apps. It's nice to know that we could support this easily with a few changes.

**Comment by vlazzarini** [comment]
We can also do a separate doubles release if requested.

**Comment by giovannibedetti** [comment]
Great, let's wait for the request then, for now I think floats are enough. 
On the Unity side it would mean having both the libcsound.a files (floats and doubles), with some PostProcessingBuild script that copies one or the other in the generated XCode project.
I can work on such a solution if there's interest. 
Thanks again for now!

**Comment by vlazzarini** [comment]
Btw, we would call it libcsound64.a in case of doubles.

**Comment by giovannibedetti** [comment]
Agree.
Btw I can only specify the CPU in the plugin import settings, so I 'd still have to rely on a post build script or on some Compile flag:
![image](https://user-images.githubusercontent.com/1912983/205679347-9f2ba20a-4eba-448c-9333-204d6651fe2a.png)

**Comment by vlazzarini** [comment]
Not sure why CPU would come into this. We built it as a universal wether it's floats or doubles (armv7, arm64, x86_64).

**Comment by giovannibedetti** [comment]
Yeah this is a generic settings that Unity applies to an iOS plugin, since it doesn't know the CPU for it when importing it on the Editor.
So I would have to specify if the plugin library is for a specific CPU. But not in this case since libcsound.a is Universal right?
Then I leave the  *Any CPU* setting.
But I think this is more like a backwards compatibility setting, since all the new iOS devices will be ARM64 based.
Btw there I could also specify the dependency from the Accelerate framework (under Rarely Used Frameworks).

**Comment by vlazzarini** [comment]
yes, libcsound.a is armv7, arm64, and x86_64.

**Comment by giovannibedetti** [comment]
yes it's there!
https://github.com/rorywalsh/CsoundUnity/tree/master/Runtime/iOS
