### ISSUE TITLE
Using b type (bool) variable in until statement segfaults

### ISSUE THREAD

**Issue by hlolli** [csound/csound#1669]
The following code segfaults on develop branch. It seems until statements only handle expressions and not identifier for boolean types.

```csound
<CsoundSynthesizer>
<CsInstruments>
sr=44100
ksmps=1
nchnls=1


instr 1
  ix = 0
  bi = ix == 10
  until bi do
   ix += 1
  od
endin


</CsInstruments>
<CsScore>
i1 0 0
e
</CsScore>
</CsoundSynthesizer>
```

**Comment by vlazzarini** [comment]
Looking at this example, I don't understand its semantics.

The expression `bi = ix == 10` would evaluate to False and the loop would repeat forever, since bi never changes. This is what I would have expected.

```
  until bi do
   ix += 1
   bi = ix == 10
  od
```

Anyway, it fails in create_bool_expression() at the moment.

**Comment by vlazzarini** [comment]
I have a PR fixing the crash. It would be good to have the value of a boolean in place of an expression, but at the moment we don't. Maybe we can open a separate ticket on that?
