### ISSUE TITLE
Csound for apple silicon?

### ISSUE THREAD

**Issue by porres** [csound/csound#1685]
Howdy, is Csound available for appl silicon yet? If not, what is on the way?

thanks

**Comment by gogins** [comment]
brew install csound

**Comment by porres** [comment]
cool, why not available from here? https://csound.com/download.html

**Comment by gogins** [comment]
Homebrew packages Csound in its own way. But it's pretty up to date. I use
the brew install because it's a universal binary which I need.

**Comment by kunstmusik** [comment]
Brew shouldn't be a universal but specific to your cpu. The last release
by @vlazzarini should be a universal binary.

**Comment by porres** [comment]
thanks

**Comment by gogins** [comment]
Steven is correct, my brew install csound is arm64 only.

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by rorywalsh** [comment]
The latest canonical installer for Csound on MacOS contains universal
binaries. No need to build yourself unless you want to.
