### ISSUE TITLE
k-rate versions of triglinseg and trigexpseg calculating increments from sr, not kr

### ISSUE THREAD

**Issue by iainmccurdy** [csound/csound#1687]
The k-rate versions of `triglinseg` and `trigexpseg` do not produce the correct output (they produce segments of inadequate slope). They only behave correctly when `kr = sr`, suggesting that increments are calculated using `sr` and not `kr`.
Csound ver. 6.18 (no front-end) on MacOS 12.6.

**Comment by rorywalsh** [comment]
I'll take a look Iain. Thanks.

**Comment by rorywalsh** [comment]
I have a fix for this Iain. I'm just waiting to see how to proceed, given that we now have a cs7 and csound6 branch on the go..

**Comment by iainmccurdy** [comment]
Thanks, Rory. they're very useful opcodes. Would it be difficult to add `trigtranseg` and `trigcosseg`?

**Comment by rorywalsh** [comment]
Shouldn't be that tricky, but I'm not sure I have the time to do it right now. I just pushed a fix to the main csound repos for this. I'm going to close this issue now :+1:
