### ISSUE TITLE
[feature request] - implementing a csound object using cuda and c++

### ISSUE THREAD

**Issue by ghost** [csound/csound#1688]
what if this would be the beggining for a new csound object created with cuda and c++:
- https://gist.github.com/tiagomoraismorgado2022/ea81ca8277a3e04b3e37866f98f4b471
this could be interesting for instance for an intelligent counterpoint based harmonizer, or some cv crazy thing emulation

**Comment by kunstmusik** [comment]
Closing as OP looks to be deleted from Github and cannot follow up on this.
