### ISSUE TITLE
event opcode with "e" statement ignores time as p1

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#1689]
this works in the score to finish the performance after ten seconds:
e 10

so i expected this to do the same:
instr 1
  event_i("e", 10)
endin
schedule(1,0,2)

but it **immediately** terminates.

this works instead:
instr 1
  event_i("e", 0, 10)
endin
schedule(1,0,2)

but it seems not consistent to me. (why having 0 as p1 if this is not the case for a score statement?)

can we leave the current behaviour for backwards compatibility, but add the `event_i("e",10)` possibility?

it would mean: if there is only one parameter following "e", read it as time until to terminate csound.

**Comment by vlazzarini** [comment]
That's how it works and is documented. We can't change it now

https://csound.com/manual/e.html

**Comment by joachimheintz** [comment]
i think it is how it is documented, but not how it works.

the example on this manual page has "e10", not "e 0 10"

when i have an empty score, and put "e 10" as statement, it will 
terminate after ten seconds.

when i put in what is written as "syntax" on the manual page:
     e 0 10
then it terminates immediately.

so i think the manual page is wrong.

**Comment by vlazzarini** [comment]
it terminates immediately as it is. So that's wrong too.

**Comment by vlazzarini** [comment]
This is now fixed in PR#1858.
