### ISSUE TITLE
@csound/browser no output since 6.18.4

### ISSUE THREAD

**Issue by felixroos** [csound/csound#1690]
When updating from `6.18.3` to `6.18.5` or `6.18.4`, the same code that worked before now produces no sound. I have made a minimal reproduction:

- working with 6.18.3 https://codesandbox.io/s/keen-blackwell-vhwvxq?file=/src/index.js
- non working with 6.18.5 https://codesandbox.io/s/gallant-thunder-2kb7w0?file=/src/index.js

I also noticed `{isRequestingRealtimeOutput: false}` is logged now..

I tried to dig in the code but the master branch only contains `6.18.2`

**Comment by felixroos** [comment]
ref https://github.com/tidalcycles/strudel/issues/402

**Comment by kunstmusik** [comment]
I think @hlolli made a change where it doesn't assume -odac anymore. If you add this code:

    await _csound.setOption("-odac");

to your example it plays audio here.

**Comment by felixroos** [comment]
that fixes it, thanks!
