### ISSUE TITLE
arduinoRead joystick example allows only a single data stream

### ISSUE THREAD

**Issue by hanstranslinear** [csound/csound#1699]
Hello, 
While compiling the arduinoRead.csd example from the 6.17.0 manual I ran into some weird problems.
System info: Csound 6.18, compiled for double precision, running Archlinux 6.2.6 and Arduino 1.8.19
After compiling the arduino sketch, I monitored the serial flow from the arduino board with putty, verifying
that the two continuous variables as well as the switch did inject their respective streams into USB.
After firing up csound I noticed that of the three input streams only the `Y' variable proved active; pushing
the switch or shifting the X-axis fader did not have any results; the printks line showed both variables and their
derivatives stuck at 0. 

Tried everything imaginable; swapped cables, chips, arduino boards, re-assigned pin numbers, pin definitions, 
reduced both csd as well as the sketch to a bare bones version, altered the execution order inside loop(), nothing had 
any effect; never more than one active variable stream at any time. Managed  to swap the three variables inside .csd and 
could then individually control frequency, or modulation index, or loudness, but never the three of them at once.

I noticed an operator `giport' that proved essential for the assignment of arduinoRead and arduinoReadF;
unfortunately, this operator could not be found in the 6.17.0 manual. A web search unearthed an ancient exchange 
 --2005-- between the usual suspects ffitch, Lazzarini, Gogins et al. that connected giport to OSC operators, but 
since this .csd does not apply OSC OPs, at least not overtly, I did not think it applied.

As you can see, I am stomped. Very curious what might be causing this. The manual definitely needs to be extended
to include giport, I think.

Many thanks in advance -- linking csound  with the outside world through multiple variables is absolutely vital to me.

Yours,

Hans Pelleboer

**Comment by jpffitch** [comment]
I do not know what you mean about giport which is just a standard csound global i-rate variable

**Comment by hanstranslinear** [comment]
Hello John,

I ploughed through the manual, sources even and couldn't find it anywhere but mentioned in both lemmata arduinoRead and arduinoReadF; evidently an initiator, but nowhere specified as such.
Besides; the problem stands. I deduced that in the example ksmps=441 coincides with the 10 ms delay in the sketch; 
could it be that at 9600 baud the window in time is simply too short to allow all three variables to be read ?

**Comment by hanstranslinear** [comment]
Nope; cranked the connection up to 115200baud, increased ksmps to 4410; made no difference whatsoever.

**Comment by jpffitch** [comment]
giport is just a variable.  The critical part is arduinoStart
Is that missing Inthe manual?

**Comment by jpffitch** [comment]
If X is not changing then the problem would seem to be the Arduino hardware

Still struggling to understand the isue

**Comment by hanstranslinear** [comment]
The issue is that only :

kX arduinoRead giport , 2 

yields an active, working kX variable, whereas, for example,

kX arduinoRead giport , 1   
or
kX arduinoRead giport , 3

yield _none_.

Clearly, arduinoStart managed to establish at least a _partially_
working serial link.
A serial monitor shows activity for all three variables
X, Y and Sw when both pots and switch are activated, so we
must assume that things are working on the hardware side.

This behaviour proved robust for any variation in parameters I could think of,
everything remained the same:
[1] tested the entire setup on three computers, all three running Cs 6.18;
same results
[2] baudrate could be varied between 1200 - 115200 baud ; in all cases
a working connection was established, but no improvement
a USB hub or direct line to the motherboard didn't make any difference
[3] swapped analog and digital inputs on the arduino; e.g. pin 2 is sometimes
troublesome, because it also functions as interrupt port on the Uno board
[4] replaced microcontrollers and boards
[5] drove ksmps between 10 and 4410 @ sr =44100, 88200

So I sigh with Catweazle ; Nothing Works!

**Comment by hanstranslinear** [comment]
Wrote a bare-bones sketch with 16 analog variables; works correctly, when monitored serially.
The corresponding csd showed much weirdness; as you suggested, analog input channel 1 does map onto arduinoRead 2,
2 onto 4 etc. but there is also something else; the scaling of channel 7  is off by a factor 4 ; quarter
fader position did not yield 256 as expected, but only 64. Pushing the fader higher than halfway created a 
simultaneous `spillover' in csound channels 2,4,6,8,10 and 12, yielding low integer values. Odd numbered channels remained
stuck at 0 at all times. Analog arduino input channels 8-16 did not yield any output at all.
BTW;  in serial.c you set N MAXSENSORS at value 30. Does this constant represent a hard limit ?
Hint -- I wouldn't mind having 200 sensor inputs or even more. Received eighty channels worth of ADCs
this very afternoon and there is plenty room for growth.

**Comment by hanstranslinear** [comment]
When I give the set of arduinoReads even numbers, the system operates nearly flawlessly; Arduino 
inputs above An14 exhibit a peculiar print-through phenomenon; values of An15 generate
identical copies in arduinoRead 26, 28 and 30.
But there is definite progress.

**Comment by jpffitch** [comment]
lual exale ( I hate web browsers; it just threw away a longish message nd a seconfd attempt...) 

Correted cde is in manual examle for arduinoRead in definitionof put_val
void put_val(int senChan, int senVal)
        // Set the Csound receive channel "senChan", and read from
        // the sensor data stream "senVal"
{       // The packing of the data is sssssvvv 0vvvvvvv where s is a
        // senChan bit, v a senVal bit and 0 is zero` bit
  int   low = senVal&0x7f;
  int hi = ((senVal>>7)&0x07) | ((senChan&0x1f)<<3);hoewhow to extend tisto 128
  Serial.write(low); Serial.write(hi);
}



Te version was confsed y an earlier version I think



and I tinki I c see ow to extend to 127bor possily255 chnneks ut It needs some thougtto ge it right

Sorry about typs here ut see rearlier commeny ofn rowsers

**Comment by hanstranslinear** [comment]
Well,

The bitmasks in your previous post definitely did the trick.
I am eagerly awaiting the future extensions of arduinoRead.
Would it be possible to extend the domain for kval to [0,4095] ?
-- 10 bit ADC resolution is already pretty much old hat,
most current microcontrollers have 12 bit ADCs on board.
Thanks for all your efforts.
P.S. this text was pasted in straight from emacs; would that
be of any help, given your hassle with web browsers ?

**Comment by jpffitch** [comment]
I will close this issue now, but you mg wan to create a wish-issue for 12 bit data and 128 channels  or what you think sane
