### ISSUE TITLE
Issue using the python interface: libcspt not found

### ISSUE THREAD

**Issue by julienbeisel** [csound/csound#1704]
Hi,

I'm using a custom folder structure (because I don't want to add the ctcsound.py files elsewhere, I decided to manually copy it in my project). When I try to run `ctcsound.py` to make sure it works, I get this error:

```
  File "/Users/julienbeisel/Documents/git-repos/transient_shaper_algo/ctcsound/ctcsound.py", line 2744, in <module>
    libcspt.NewCsoundPT.restype = ct.c_void_p
  File "/Users/julienbeisel/.pyenv/versions/3.10.4/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/Users/julienbeisel/.pyenv/versions/3.10.4/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, NewCsoundPT): symbol not found
```

**Versions:**
MacOS Ventura 13.1 / Python 3.10.4 / Csound 6.18.0 installed with the latest Cabbage beta version

**Solution?**
I understood the following lines were the root cause:

``` python
elif sys.platform.startswith('darwin'):
    libcspt = ct.CDLL(ctypes.util.find_library('csnd6.6.0'))
```

I can run the file smoothly by using:

``` python
elif sys.platform.startswith('darwin'):
    libcspt = ct.CDLL("/Library/Frameworks/CsoundLib64.framework/Versions/6.0/libcsnd6.6.0.dylib")
```

I'm not sure it would work on everyone device though... Do you know what causes the error?

Here is the installation folder structure:
![Capture d’écran 2023-04-05 à 10 21 27](https://user-images.githubusercontent.com/26651960/230023964-edbe6f4c-9d3a-43ea-a181-a8689313ff0f.png)

Thanks,

Julien

**Comment by vlazzarini** [comment]
It’s a known Python issue, reported here

https://bugs.python.org/issue43964

probably rearing its head again.
========================
Prof. Victor Lazzarini
Maynooth University
Ireland

**Comment by julienbeisel** [comment]
Hi Victor,

Thanks for your help. I didn't think the issue would be that deep!
The workaround is working though, so if someone has the same he can replace the `find_library()` call with the absolute path.

**Comment by vlazzarini** [comment]
yes, thanks for this.
I myself have no issues here with Python 3.9.6. I think it starts with Python 3.10.
========================
Prof. Victor Lazzarini
Maynooth University
Ireland
