### ISSUE TITLE
karray = iarray no longer works

### ISSUE THREAD

**Issue by ErrorThink** [csound/csound#1712]
karray assignment from an i array used to work
For example: The following code works in Windows Csound version 6.18 (double samples) Nov 23 2022 
However raises an error in the Web version 6.18.7 (as found at [https://cdn.jsdelivr.net/npm/@csound/browser@6.18.7/+esm](https://cdn.jsdelivr.net/npm/@csound/browser@6.18.7/+esm)).

```
instr 1
  iArr[] fillarray 1,2,3,4,5
  kArr[] = iArr
  printarray kArr
  turnoff
endin
```

schedule 1,0,1

Error message is:
InitError in wrong mode 0
INIT ERROR in instr 1 (opcode =._) line nnn: array-variable types do not match

**Comment by vlazzarini** [comment]
This is working now on latest develop

```
instr 1
  iArr[] fillarray 1,2,3,4,5
  kArr[] = iArr
  printarray kArr
  turnoff
endin
```

```
SECTION 1:
new alloc for instr 1:
 1.0000 2.0000 3.0000 4.0000 5.0000 
B  0.000 ..  1.000 T  1.000 TT  1.000 M:  0.00000
```
