### ISSUE TITLE
cs7 is broken wrt Bookean expressions

### ISSUE THREAD

**Issue by jpffitch** [csound/csound#1717]

**Comment by jpffitch** [comment]
error:  error: boolean expression '&&' with arg types cB not found, line 266

 from file tt.csd (1)
error:  Unable to verify arg types for boolean expression '=='
Line 266

 from file tt.csd (1)
Parsing failed due to syntax errors
Stopping on parser failure
cannot compile orchestra
end of score.              overall amps:      0.0
           overall samples out of range:        0
1 errors in performance

lines near 266 are

if gksstate[ki]=1 && gkstate[ki] = 2 then
event "i", 31+ki, 0, -1, 48+ki
gksstate[ki] = 2
endif

Used to work last week

**Comment by kunstmusik** [comment]
I wonder if this was something that was fixed in @hlolli 's branch?
(Hlodver could you comment?)

**Comment by jpffitch** [comment]
Sorry I lost my simple example. csd program  It a be on the other computer ; will check asap. 
⁣​

**Comment by jpffitch** [comment]
Example
```
<CsoundSynthesizer>

<CsInstruments>
gkbeat init 0
gkstate[] init 8
gksstate[] init 8
instr 3 ;; On beat actions
if gkbeat == 0 goto ee
ki = 0
;; printarray gkstate
;; printarray gksstate
loop:
;; printk2 ki, 0, 1
if gkstate[ki]=1 then
event "i", 21+ki, 0, -1, ki+1
gkstate[ki] = 2
endif
if gksstate[ki]=1 && gkstate[ki] = 2 then
event "i", 31+ki, 0, -1, 48+ki
gksstate[kample
``i] = 2
endif
ki += 1
if ki<=7 goto loop
ee:
endin

</CsInstruments>

<CsScore>

</CsScore>

</CsoundSynthesizer>
`

**Comment by jpffitch** [comment]
Tgis aseems to be fixed now.  Thanks
