### ISSUE TITLE
Csound 6 API docs are incorrect or out of date

### ISSUE THREAD

**Issue by bmitc** [csound/csound#1719]
The [Csound 6 API docs (current version 6.16)](https://csound.com/docs/api/index.html) are either incorrect or out of date.

I am implementing new .NET bindings for the API, and the first incorrect example I came across is for the `CS_AUDIODEVICE` struct. In the API docs, both the [struct reference](https://csound.com/docs/api/structCS__AUDIODEVICE.html) and the [`csound.h` header file](https://csound.com/docs/api/csound_8h_source.html) list the `char` array length as 64.

```c
typedef struct {
     char device_name[64];
     char device_id[64];
     char rt_module[64];
     int max_nchnls;
     int isOutput;
   } CS_AUDIODEVICE;
```

However, in the Csound repository, both in `ctcsound.py`:

https://github.com/csound/csound/blob/a1580f9cdf331c35dceb486f4231871ce0b00266/interfaces/ctcsound.py#L92-L97

and `csound.h`:

https://github.com/csound/csound/blob/a1580f9cdf331c35dceb486f4231871ce0b00266/include/csound.h#L527-L533

the `char` array is of length 128.

This seems to also apply to other structs, but I am not sure of how much total is incorrect.

**Comment by giovannibedetti** [comment]
I had a look in the Csound6Net source code, and indeed it was implemented with a length of 64:

```/**
     * Audio Device information for a given audio module
     */
    [StructLayout(LayoutKind.Sequential, CharSet=CharSet.Ansi)]
    public class CS_AUDIODEVICE
    {
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst=64)]
        public string device_name;

        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)]
        public string device_id;

        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)]
        public string rt_module;

        public int max_nchnls;

        [MarshalAs(UnmanagedType.Bool)]
        public bool isOutput;
    }```
    
    Not sure when the fields were updated to a length of 128 though.

**Comment by giovannibedetti** [comment]
You mean the 6.18.1 release? Are you using the csound64.dll from the Windows zip?
Btw I think I downloaded the Csound6Net repository before the Codeplex went down, and yes, it is referring to Csound 6.01, last update is dated 2013, so probably the version I have is the same you retrieved using Wayback Machine. 
Here it is:
[csound6net.zip](https://github.com/csound/csound/files/11930080/csound6net.zip)

**Comment by vlazzarini** [comment]
Docs were generated from 6.16 sources, hence they could be out of date. Just check the headers that come with your distribution and version.

**Comment by vlazzarini** [comment]
not hard, it's just doxygen. But we don't have anyone taking care of that part. As with many parts of the project, we're short of people helping out.
