### ISSUE TITLE
skip initialization for phaser2

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#1723]
phaser1 has this skip option for tied notes
_ares phaser1 asig, kfreq, kord, kfeedback [, iskip]_
phaser2 does not
_ares phaser2 asig, kfreq, kq, kord, kmode, ksep, kfeedback_

**Comment by jpffitch** [comment]
I have written code adding a skip of initialisation but it needs testing.

**Comment by tjingboem** [comment]
this example is a variation of the _phaser1_ opcode example 

```
<CsoundSynthesizer>
<CsOptions>
-odac     
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 10
nchnls = 1

instr 1
  ; Input mixed with output of phaser1 to generate notches.
  ; Shows the effects of different iorder values on the sound
  idur   = p3 
  iamp   = p4 * .05
  iorder = 16        ; number of 1st-order stages in phaser1 network.
                     ; Divide iorder by 2 to get the number of notches.
  ifreq  = .2        ; frequency of modulation of phaser1
  ifeed  = .9        ; amount of feedback for phaser1

  kamp   linseg 0, .2, iamp, idur - .2, iamp, .2, 0

  iharms = (sr*.4) / 100

  asig   gbuzz 1, 100, iharms, 1, .95, 2, -1  ; "Sawtooth" waveform modulation oscillator for phaser1 ugen.
  kfreq  oscili 3300, ifreq, 1
  kmod   = kfreq + 5600

 ; aphs   phaser2 asig, kmod, iorder, ifeed, 1
  aphs   phaser2 asig, 2000, .5, iorder, 1, 1, ifeed
  out    (asig + aphs) * iamp
endin


</CsInstruments>
<CsScore>

; inverted half-sine, used for modulating phaser1 frequency
f1 0  16384 9 .5 -1 0
; cosine wave for gbuzz
f2 0  8192 9 1 1 .25

; phaser1
i1 0  -5 7000  
i1 6  -5 7000 
i1 12 -5 7000 
i1 18 -5 7000 
i1 24 -5 7000 
i1 30 5 7000 
e


</CsScore>
</CsoundSynthesizer>
```

You do hear the clicks when going from note to note. imo there should be no clicks when _phaser2_ is not reset.
gbuzz does have the skip initialization set here.

**Comment by jpffitch** [comment]
I hear no clicks

**Comment by tjingboem** [comment]
i will do some testing this week

**Comment by tjingboem** [comment]
i found i do not have your new code that includes this skipping of initialization.
phaser2     a           akkkkkk

The list with all Csound opcodes missing the skipping of initialization https://github.com/csound/csound/issues/1736 i posted a while ago, already mentions the phaser2 opcode.

Is the new code for phaser2 already committed somewhere? Or can i test it?

**Comment by vlazzarini** [comment]
This is already implemented in the current develop code.
