### ISSUE TITLE
-Mm flag & ctrl7 midi channels - out of range errors

### ISSUE THREAD

**Issue by boonier** [csound/csound#1734]
Observed on Csound version 6.18 (double samples) Oct 20 2022

So when I was testing out the `-Mm` flag to enable access to multiple ports it looks like the ctrlN family of opcodes won't accept a midi channel greater than 1-16. This would also affect other midi input opcodes I think.

Can confirm that the error is being sent in here: https://github.com/csound/csound/blob/a1580f9cdf331c35dceb486f4231871ce0b00266/Opcodes/midiops2.c#L326-L329

More background info here: 
https://forum.csound.com/t/how-to-make-use-of-mm-flag-for-multiple-input-ports/1281?u=boonier
https://discord.com/channels/784849854270537790/786239959342121021/1133325632982499378

Cheers

**Comment by vlazzarini** [comment]
Fixed in PR #1966
