### ISSUE TITLE
printarray does not work in init-time

### ISSUE THREAD

**Issue by berntisak** [csound/csound#1757]
printarray doesn't work in i-time on string-arrays, which I believe used to be the case since Joachim is using it to print in init time in his example 03E04 from the Floss manual under arrays (https://flossmanual.csound.com/csound-language/arrays). 

```
<CsoundSynthesizer>
<CsOptions>
-odac -d
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs = 1

instr Files
 S_array[] directory "."
 iNumFiles lenarray S_array
 prints "Number of files in %s = %d\n", pwd(), iNumFiles
 printarray S_array
endin

</CsInstruments>
<CsScore>
i "Files" 0 0
</CsScore>
</CsoundSynthesizer>
;example by joachim heintz
```

**Comment by kunstmusik** [comment]
I'm not sure printarray with string arrays ever printed at init-time; the code shows it printing at perf-time with some controls on whether it's done at triggered time or every k-cycle.  

Requesting @gesellkammer for clarification and advice to evaluate this issue.

**Comment by gesellkammer** [comment]
In csound there is an ambiguity between data and rate. i- and k- arrays are scalar arrays with different rate, an audio array has audio vectors as data and control as rate and analogous to that, string arrays could be interpreted as having strings as data and control as rate. I would like to stress that there is no difference between doing an operation at init-time or at the first cycle. In this case the example should be modified to:

```csound

instr Files
 S_array[] directory "."
 iNumFiles lenarray S_array
 prints "Number of files in %s = %d\n", pwd(), iNumFiles
 printarray S_array
 turnoff
endin

schedule "Files", 0, 1/kr

```

In particular I would like to avoid a new opcode "printarray_i" or something similar

**Comment by kunstmusik** [comment]
Init-rate opcode could print a different result if someone does something like:

```
S_array[] directory "."
printarray S_array
...mutateArrayAtInitTime...
printarray S_array
```

(Hypothetical example thinking of someone using this for debugging code.)

I think there's no way around adding an init-time version of print_array for the above.

**Comment by vlazzarini** [comment]
thinking aloud, can't this be resolved with an overload?

**Comment by kunstmusik** [comment]
@vlazzarini no, as @gesellkammer mentioned Strings don't have a rate associated with them (nothing does except i,k,a really), so the opcode can't determine to do an init-only operation or init + perf operation. (I also wrote about this in my thesis what feels like multiple lifetimes ago ;) ).

**Comment by vlazzarini** [comment]
oh I only spotted now this is about string arrays not numeric arrays.

**Comment by gesellkammer** [comment]
What I could do is change the behaviour of the trigger in printarray. At the moment by default it prints only at the first k-cycle. I could change it to print at init by default (for string arrays only)

**Comment by joachimheintz** [comment]
i think this is a good solution.

**Comment by kunstmusik** [comment]
One concern I have is that this is specific to the String type. I think for future-proofing, we may need to do like in other systems and add a to_string opcode that could be overloaded by type. This would allow users to also define their own to_string for structs, for example. If this convention exists, a to_string for arrays that calls to_string with the data type it holds could make this generic. 

Thoughts?

**Comment by gesellkammer** [comment]
The only change is to assume that the default rate for strings is the init
rate. This follows multiple opcodes and as such is probably a better
default that it was before.

**Comment by gesellkammer** [comment]
There is a PR to fix this: https://github.com/csound/csound/pull/1803

**Comment by vlazzarini** [comment]
merged
