### ISSUE TITLE
Modify mp3in and mp3len to use libsndfile

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#1785]
Regarding https://github.com/csound/csound/issues/1553, this is a story for removing custom mp3 code and replacing with libsndfile now that it has mp3 support.

**Comment by jpffitch** [comment]
Diskin2 includes mp3 input files.  I have just built with the latest libsndfile and it runs the manual diskin2.csd with minimal modification to read the mp3 version of the drums.  As it can do pitch shifting on reading the mp3 file it is better than mp3in.

Need to check mp3len

**Comment by vlazzarini** [comment]
Thinking about this, I'd like to keep the specialist mp3 opcodes as it gives us a self-contained means of reading files without the need for dependencies.

Now that libsndfile can be taken out of the build, it seems a good idea to keep these.

**Comment by jpffitch** [comment]
This can be closed.   ?Only action needed is to consider optional inclusion of mp3in and kp3len.

**Comment by jpffitch** [comment]
U a, cponfused hre.

Are you suggesing a plugik wiith jusr mp3in and its support code?#

**Comment by vlazzarini** [comment]
mp3in is now a plugin so I am closing this, we can move the code out of the library if it is required in the future.
