### ISSUE TITLE
multiple assignments not working in CS7

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#1801]
this works in CS6 but not in CS7 (develop):
`iMin,iMax = 5,10`

not sure it is already expected to work but want to mention it for compatibility.

**Comment by kunstmusik** [comment]
I was not aware of this syntax in CS6. Is this commonly used? I'm wondering about the long-term language design implications of this and whether it'll cause issues in the future. 

Would love to hear @jpffitch and @vlazzarini 's thoughts on this.

**Comment by vlazzarini** [comment]
I wasn't aware either. Looks like tuples to me but I never knew we supported them in the old parser.

**Comment by joachimheintz** [comment]
just to note that it is documented in the manual:
https://csound.com/docs/manual/assign.html

**Comment by vlazzarini** [comment]
well then, looks like we need to keep this in the new parser. This goes back to 2010.

**Comment by joachimheintz** [comment]
i just checked whether multiple assignments work for init rather than 
for equal.
good news that it already works also in CS7, for instance:

instr 1
   ia,ib init 1,2
   print(ia,ib)
endin

not sure if this helps to implement it for `ia,ib = 1,2`, too.

**Comment by jpffitch** [comment]
I looked more carefilly and multiole assinment iin cs6 is just the usual call of an opcode.  There is no fuss about diskin2 have multiple outputs and more than 1 input. so there is issue in =or init,. The syntax is just like elsewhere
-  { "=.i",    S(ASSIGNM),0, 1,      "IIIIIIIIIIIIIIIIIIIIIIII", "m",
    minit, NULL, NULL, NULL  },
  { "=.k",    S(ASSIGNM),0, 2,      "zzzzzzzzzzzzzzzzzzzzzzzz", "z",
    NULL, minit, NULL, NULL },
In the parser3 however = is treated specially and so needs a rewrite to match the simplicity of cs6

**Comment by vlazzarini** [comment]
This is now fixed in PR #1944
