### ISSUE TITLE
add CI build for iOS libraries

### ISSUE THREAD

**Issue by rorywalsh** [csound/csound#1807]
XCode has moved to using multiplatform binary frameworks for iOS development. There should be a CI build for this. 

@kunstmusik Should we build an xcframework for libSndfile at the same time? I guess we might as well considering it will also be needed for iOS development.

**Comment by kunstmusik** [comment]
@rorywalsh I'm a bit out of date with iOS development so can not comment really on best path forward for this. Might also be useful to poll the csound users list for iOS devs to see what they might want/expect.

**Comment by rorywalsh** [comment]
Sure. All I know is it that in 99% of cases a user will also need libSndfile, as Csound will have been built against it. So it's probably best to include it.

**Comment by kunstmusik** [comment]
I think it hasn't been an issue so far for iOS as we linked it
into libcsound.a (if I remember correctly). Either way, yeah no questions
the user will need libsndfile, just a matter of what's the way to get it to
them.

**Comment by vlazzarini** [comment]
I see this is now in place, closing the issue.
