### ISSUE TITLE
not possible to skip audio output in UDO?

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#1808]
when i have a csound instrument, i can skip a certain number of k-cycles by a loop like this:
```
  kCount init 0
  skip:
  (do something)
  kCount += 1
  if (kCount < iTimeToSkip*kr) kgoto skip
```

this works inside an instrument, but not inside a UDO:
```
opcode Play,a,Si
  Sfile,iTimeToSkip xin
  kCount init 0
  skip:
  aOut = poscil:a(0.2,expon:k(400,2,1600))
  kCount += 1
  if (kCount < iTimeToSkip*kr) kgoto skip
  xout(aOut)  
endop

instr 1 // works
  iTimeToSkip = p4
  kCount init 0
  skip:
  aOut = poscil:a(0.2,expon:k(400,2,1600))
  kCount += 1
  if (kCount < iTimeToSkip*kr) kgoto skip
  outall(aOut)
endin
schedule(1,0,1,0)
schedule(1,2,1,1) ;skips the first second 

instr 2 // does not work
  iTimeToSkip = p4
  aOut = poscil:a(0.2,expon:k(400,2,1600))
  outall(aOut)
endin
schedule(2,4,1,0)
schedule(2,6,1,1) ;does NOT skip the first second
```

is this expected behaviour?  or is it a bug?

**Comment by vlazzarini** [comment]
maybe I am getting some wires crossed but I can't seen in instr 2 any code to skip anything (ie. the UDO is not called?)

**Comment by joachimheintz** [comment]
of course your wires are straight and mine were very crossed this 
morning ...
(i was at first using diskin and then saw that it is not related to it 
but can also demonstrated on a simple oscillator.)

thanks for looking into it; here is the correct code:

opcode Play,a,i
   iTimeToSkip xin
   kCount init 0
   skip:
   aOut = poscil:a(0.2,expon:k(400,2,1600))
   kCount += 1
   if (kCount < iTimeToSkip*kr) kgoto skip
   xout(aOut)
endop

instr 1 // works
   iTimeToSkip = p4
   kCount init 0
   skip:
   aOut = poscil:a(0.2,expon:k(400,2,1600))
   kCount += 1
   if (kCount < iTimeToSkip*kr) kgoto skip
   outall(aOut)
endin
schedule(1,0,1,0)
schedule(1,2,1,1) ;skips the first second

instr 2 // does not work
   iTimeToSkip = p4
   aOut = Play(iTimeToSkip)
   outall(aOut)
endin
schedule(2,4,1,0)
schedule(2,6,1,1) ;does NOT skip the first second

**Comment by vlazzarini** [comment]
There s a problem somewhere and I think I have seen it before. If you make the small change

```
opcode Play,a,Si
  Sfile,iTimeToSkip xin
  kCount init 0
  kgoto nxt
  skip:
  nxt:
  aOut = poscil:a(0.2,expon:k(400,2,1600))
  kCount += 1
  if (kCount < iTimeToSkip*kr) kgoto skip
  xout(aOut)  
endop
```
you get the expected result. If I remember it properly, the problem was that the label was not found inside the UDO and the code jump did not work. Adding another label seems to force it to be found. I thought we had fixed this. @jpffitch do you remember this issue from another time? I can't recall what we did with it,

**Comment by vlazzarini** [comment]
This is fixed in the current develop code, I checked your example and both instruments are now skipping the first second. I think this was fixed when I did some work on labels in udos etc, there was some wrong jumping going on that I worked on and it seems to solve your problem here.
