### ISSUE TITLE
problems in rtpulse

### ISSUE THREAD

**Issue by jpffitch** [csound/csound#1816]
In cs7 devel branch

WARNING: could not open library '/home/jpff/cs7/cs77/librtpulse.so' (/home/jpff/cs7/cs77/librtpulse.so: undefined symbol: pa_simple_write)

I have the libpulse-devel package installed on openSuSE 15.5 Linux

Could be portaudio version?

**Comment by jpffitch** [comment]
185.249.200.24aring with cs6
nm librtpulse.so:
 ....
0000000000000738 t _init
                 w _ITM_deregisterTMCloneTable
                 w _ITM_registerTMCloneTable
                 U pa_sample_spec_valid@PULSE_0
                 U pa_simple_drain@PULSE_0
                 U pa_simple_free@PULSE_0
                 U pa_simple_new@PULSE_0
                 U pa_simple_read@PULSE_0
                 U pa_simple_write@PULSE_0
                 U pa_strerror@PULSE_0
0000000000000f93 t pulse_clos....

cs7 has
0000000000000718 t _init
                 w _ITM_deregisterTMCloneTable
                 w _ITM_registerTMCloneTable
                 U pa_sample_spec_valid@PULSE_0
                 U pa_simple_drain
                 U pa_simple_free
                 U pa_simple_new
                 U pa_simple_read
                 U pa_simple_write
                 U pa_strerror@PULSE_0
0000000000000f73 t pulse_close

so it is not getting the relationshoip wit portaudio right

**Comment by vlazzarini** [comment]
but librtpulse should be completely independent from portaudio? Isn't that the code to connect to pulseaudio directly?

I think pa_*** are the pulse audio functions not portaudio.

**Comment by jpffitch** [comment]
Yes. I was wrong.  Trying to find a reason why it works for Steven but not me 


-------- Original Message --------

**Comment by kunstmusik** [comment]
I did a fresh build using an interactive shell with Dockerfile.opensuse and
using ldd I got the following with links to libpulse and libpulse-simple.
Do you get the same with ldd?

sh-4.4# ldd librtpulse.so

libpulse.so.0 => /usr/lib64/libpulse.so.0 (0x00007ffffff73000)

libpulse-simple.so.0 => /usr/lib64/libpulse-simple.so.0 (0x00007ffffff6e000)

libc.so.6 => /lib64/libc.so.6 (0x00007fffffd77000)

libpulsecommon-15.0.so => /usr/lib64/pulseaudio/libpulsecommon-15.0.so
(0x00007fffffcee000)

libm.so.6 => /lib64/libm.so.6 (0x00007fffffba2000)

libdbus-1.so.3 => /usr/lib64/libdbus-1.so.3 (0x00007fffffb4f000)

libdl.so.2 => /lib64/libdl.so.2 (0x00007fffffb48000)

libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fffffb24000)

/lib64/ld-linux-x86-64.so.2 (0x00007ffffffd2000)

librt.so.1 => /lib64/librt.so.1 (0x00007fffffb1a000)

libsndfile.so.1 => /usr/lib64/libsndfile.so.1 (0x00007fffffa9d000)

libxcb.so.1 => /usr/lib64/libxcb.so.1 (0x00007fffff800000)

libsystemd.so.0 => /usr/lib64/libsystemd.so.0 (0x00007fffff71d000)

libFLAC.so.8 => /usr/lib64/libFLAC.so.8 (0x00007fffff400000)

libogg.so.0 => /usr/lib64/libogg.so.0 (0x00007fffff000000)

libvorbis.so.0 => /usr/lib64/libvorbis.so.0 (0x00007ffffec00000)

libvorbisenc.so.2 => /usr/lib64/libvorbisenc.so.2 (0x00007ffffe800000)

libspeex.so.1 => /usr/lib64/libspeex.so.1 (0x00007ffffe400000)

libXau.so.6 => /usr/lib64/libXau.so.6 (0x00007ffffe000000)

liblzma.so.5 => /usr/lib64/liblzma.so.5 (0x00007ffffdc00000)

libzstd.so.1 => /usr/lib64/libzstd.so.1 (0x00007fffff2cf000)

liblz4.so.1 => /usr/lib64/liblz4.so.1 (0x00007ffffd800000)

libcap.so.2 => /usr/lib64/libcap.so.2 (0x00007fffffa8e000)

libgcrypt.so.20 => /usr/lib64/libgcrypt.so.20 (0x00007ffffeec2000)

libgpg-error.so.0 => /usr/lib64/libgpg-error.so.0 (0x00007ffffd400000)

**Comment by jpffitch** [comment]
Can you confirm he ldd is for cs7  develop?
Also could you check (with rpm -qf  ...)  the version numbers of the libpulse-develop and libpiulse0 packages?

**Comment by jpffitch** [comment]
Another datapoint.  The librtpulse I built in my cs7 tree is not the same as the /usr/lib64/csound/plugins64-6.0/librtpulse.so wrt the pa_simple* names.  The plugin is dated 16 jan and I do not know from whence it came

**Comment by kunstmusik** [comment]
Just did another fresh build and it was from develop. I got:

sh-4.4# git status
On branch develop
Your branch is up to date with 'origin/develop'.

nothing to commit, working tree clean
sh-4.4# ldd librtpulse.so
libpulse.so.0 => /usr/lib64/libpulse.so.0 (0x00007ffffff73000)
libc.so.6 => /lib64/libc.so.6 (0x00007fffffd7c000)
libpulsecommon-15.0.so => /usr/lib64/pulseaudio/libpulsecommon-15.0.so
(0x00007fffffcf3000)
libm.so.6 => /lib64/libm.so.6 (0x00007fffffba7000)
libdbus-1.so.3 => /usr/lib64/libdbus-1.so.3 (0x00007fffffb54000)
libdl.so.2 => /lib64/libdl.so.2 (0x00007fffffb4f000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fffffb29000)
/lib64/ld-linux-x86-64.so.2 (0x00007ffffffd2000)
librt.so.1 => /lib64/librt.so.1 (0x00007fffffb1f000)
libsndfile.so.1 => /usr/lib64/libsndfile.so.1 (0x00007fffffaa2000)
libxcb.so.1 => /usr/lib64/libxcb.so.1 (0x00007fffff800000)
libsystemd.so.0 => /usr/lib64/libsystemd.so.0 (0x00007fffff71d000)
libFLAC.so.8 => /usr/lib64/libFLAC.so.8 (0x00007fffff400000)
libogg.so.0 => /usr/lib64/libogg.so.0 (0x00007fffff000000)
libvorbis.so.0 => /usr/lib64/libvorbis.so.0 (0x00007ffffec00000)
libvorbisenc.so.2 => /usr/lib64/libvorbisenc.so.2 (0x00007ffffe800000)
libspeex.so.1 => /usr/lib64/libspeex.so.1 (0x00007ffffe400000)
libXau.so.6 => /usr/lib64/libXau.so.6 (0x00007ffffe000000)
liblzma.so.5 => /usr/lib64/liblzma.so.5 (0x00007ffffdc00000)
libzstd.so.1 => /usr/lib64/libzstd.so.1 (0x00007fffff2cf000)
liblz4.so.1 => /usr/lib64/liblz4.so.1 (0x00007ffffd800000)
libcap.so.2 => /usr/lib64/libcap.so.2 (0x00007fffffa93000)
libgcrypt.so.20 => /usr/lib64/libgcrypt.so.20 (0x00007ffffeec2000)
libgpg-error.so.0 => /usr/lib64/libgpg-error.so.0 (0x00007ffffd400000)

and:

sh-4.4# rpm -q libpulse-devel
libpulse-devel-15.0-150400.4.4.1.x86_64
sh-4.4# rpm -q libpulse0
libpulse0-15.0-150400.4.4.1.x86_64

**Comment by jpffitch** [comment]
You provide no information that the rtpulse library is working.  The definitive test seems to be 

nm librtpulse.so | grep pa_simple_write

if you get 
U pa_simple_write
then it is broken.  To work it should say
U pa_simple_write@PULSE_0

So the problem lies in the linking to the library in a manner 
beyond my knowledge, but it must be in the building of the sharable library.

If I could see the build command I would be happier.  It creates the Makefile as a quiet version and so far attempts to make it echo the commands has failed.

**Comment by kunstmusik** [comment]
Ahhhh apologies. I think I have not been testing correctly. I tried again
now with:

OPCODE7DIR64=$PWD ./csound -+rtaudio=pulse --daemon

in the build directory and I am now reproducing your issue:

WARNING: could not open library '/csound/build/librtpulse.so'
(/csound/build/librtpulse.so: undefined symbol: pa_simple_write)

I also get:

sh-4.4# nm librtpulse.so | grep pa_simple_write
                 U pa_simple_write

Now that we're on the same page I should be able to help diagnose better.
Looks to me that libpulse-simple.so needs to be linked in. Taking a look
now.

**Comment by kunstmusik** [comment]
I replaced FindPulseAudio.cmake with the one from xbmc (
https://github.com/xbmc/xbmc/blob/master/cmake/modules/FindPulseAudio.cmake)
which searches for pulseaudio-simple. That was enough to get librtpulse.so
to build and run for me here. Let me know if that fixes things up for you
John.

**Comment by bramtayl** [comment]
My bad from #1799. I got the findpulseaudio.cmake file from https://github.com/KDE/extra-cmake-modules/blob/master/find-modules/FindPulseAudio.cmake which looked like a reputable enough source

**Comment by jpffitch** [comment]
You restored this to working
