### ISSUE TITLE
stack smashing detected

### ISSUE THREAD

**Issue by William-Purvis** [csound/csound#1823]
I have a csound script which produce the error message :
   *** stack smashing detected ***: terminated
THis was with the current Debian Bookworm release. Browsing through issues I found a reference to a similar problem
with the Debian build, so I cloned the current source from github and built and installed that.
It still produced this error message, so I guess it is different to that previously reported.

I append:
[organ_mixer.csd.txt](https://github.com/csound/csound/files/14229541/organ_mixer.csd.txt)
I am attempting to construct a headless mixer for an organ. 
I'm happy to provide any further info if asked.

**Comment by William-Purvis** [comment]
I should add that although the script refers to Jack, I am actually running pipewire with pipewire-jack.

**Comment by William-Purvis** [comment]
Further info: I had not run the 'sudo ldconfig'. Now I have done that, it now falls over with sementation violation!

**Comment by vlazzarini** [comment]
That issue may be related to trying to use plugins of different versions. What is the version you are building?

To note: develop branch is 7.0 beta and that is not compatible with 6.x

If you want to build 6.19 beta, use csound6 branch. 

However as far as we know the Debian package is correct. Maybe you should ask @umlauete who maintains it.

**Comment by vlazzarini** [comment]
Do we have any further updates on this?

**Comment by vlazzarini** [comment]
closing for now. Without any further details, we can't move. Also 6.x is EOL.
