### ISSUE TITLE
scanu2 and GEN44 issue

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#1824]
I have made a Matrix of the string using the GEN44 format, played this and compared the result to the 'old' string-128 Matrix.

This is what the old Matrix (the binary one) looks like:
![CsoundString](https://github.com/csound/csound/assets/6670911/73a9d90a-4164-4acc-9e38-9c42d372790d)
This is my Matrix, created with the format of GEN44:
![MyString](https://github.com/csound/csound/assets/6670911/d9f83c2a-81b7-4e7f-983b-ce70e9a93990)

But, when played, there is a difference in sound.
This is a screenshot of how the old Matrix moves:
![string-128](https://github.com/csound/csound/assets/6670911/d65e5e5f-1541-4ab0-ba00-845d7e025f54)
compared to my Matrix:
![string_128matrxT](https://github.com/csound/csound/assets/6670911/88fea9db-aeee-49a3-97cc-2236db5bf53e)

Something is going on at the start; there is some distortion.
It may be that scanu2 is interpreting the GEN44 Matrix incorrectly OR i am doing something wrong...

Here is the csd and Matrices: 
[Matrices.zip](https://github.com/csound/csound/files/14323048/Matrices.zip)

**Comment by tjingboem** [comment]
i was hoping this issue could be solved before the release Csound7?

**Comment by vlazzarini** [comment]
@jpffitch do you know anything about this?

**Comment by vlazzarini** [comment]
The code example supplied does not use GEN44, only GEN23. Can you provide an example showing the issue with GEN44?

**Comment by vlazzarini** [comment]
I am closing this as I am not convinced GEN44 was tested at all. I noticed that ftgen could not run GEN44 with a string filename and I fixed that, but otherwise I see nothing to indicate there is a bug. If one is found, we'll be happy to look at it, given enough information.

**Comment by tjingboem** [comment]
i´d like to rebuild Csound6 again to check if the fix of GEN44 with a string filename makes any difference.
Can you add this fix in Csound6 as well? 

![Screenshot from 2024-08-27 15-17-52](https://github.com/user-attachments/assets/17143f79-622e-474f-8ce0-3c7a4782feb1)

(There are so many versions now...i have no idea where this fix went)

The string_128.matrxT file looks good when i look at the produced text and when i display it in my Python display program, (as you see above),  but let us first rule this ´GEN44 with a string filename fix´ out.

**Comment by vlazzarini** [comment]
the code in your example does not use GEN44 though.

**Comment by tjingboem** [comment]
True.

i just checked what i really meant at the time with filing this issue, and it has to do with me not understanding why the 'old' matrix string-128 (=Binary) sounds different from my generated matrix string_128.matrxT (=text as produced in the GEN44 format). This (undesirable) difference can be heard in scanu3.csd. 
I believe both files should produce the same sounding result.

The format of the matrix GEN44 is a more transparent one, one that provokes exploring. But a Utility, such as for ATSA, HETRO, CVANAL etc., is missing. And nobody wants to write thousands of numbers when wanting to create a matrix or a trajectory of 10, 100 or 1000 points.

So i created my own Utility (Csound code and made in Blue) to generate GEN44 matrices. It is called Scanned Matrix Pattern Generator https://github.com/tjingboem/Scanned-Matrix-Pattern-Generator

![Screenshot from 2024-08-28 12-45-16](https://github.com/user-attachments/assets/f21f7b12-1b18-48f4-89b4-cc9f3770391d)

and the trajectory generator called Scanned Trajectory Generator.

![Screenshot from 2024-08-28 12-46-29](https://github.com/user-attachments/assets/1466bfac-dc69-4d90-9c40-225287bdae10)


Still a work in progress, but i am able to reproduce all 'old' matrices like string, grid, torus etc. but in the GEN44 format. Two Python Matlabplot can show the produced matrix and the trajectory. The white matrix (at the top of this issue) shows such a plot. Although the visualization method is a bit different; the binary one from Steven Yi works its way down, my GEN44 format works its way up. But they both have the same direction and number of points. 

With the GEN44 format, it is optional to add a weight to a point. The manual says: "If this third number is omitted it is taken as value 1." So my matrix all have weight 1. I believe this is the neutral state, so both the old matrix string-128 and the new matrix string_128.matrxT should produce the same sounding result.

But it does not, the new matrix has distortion. And i don't know why.

My concern is, that if i am right and something somwehere in the code (perhaps Scanu2 does not interpret the new matrix correctly?) is not correct, people will start using the GEN44 format and later turns out not to be correct or Scanu2 does not read it correctly, then it needs to be changed. And cause backwards incompatibility. 
This is why i asked to give this more priority.

Another concern is that is stops me from developing the Generators further and getting the right examples for the manual.

**Comment by vlazzarini** [comment]
If there is a bug, then we can look at it, but we need a code example demonstrating this. In your example there was no GEN44 in the code. 

The text string_128.matrxT was not accepted by GEN44, I got an error straight away running it through GEN44. With

```
f 1 0 128 -44  "string_128.matrxT"
```

I get

```
ftable 1: GEN44: Out of range

f  1     0.00   128.00   -44.00  "string_128.matrxT" ...
```

Also in the code you have

```
ifnmatrixB   ftgen   33, 0, $SIZE*$SIZE, -23, "string_128.matrxT"
```
that is using gen 23 not gen 44. So it won't work either.

**Comment by tjingboem** [comment]
Thanks for your patience.

The issue is solved. It was my error.

```
<CsoundSynthesizer>
<CsOptions>
  --displays --limiter=.95
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 128
nchnls = 2
0dbfs = 1

instr 1

a0 init 0
irate = .01
      
;scanu2 init, irate, ifndisplace, ifnmass, imatrix, ifncentr, ifndamp, kmass, kmtrxstiff, kcentr, kdamp, ileft, iright, kpos, kdisplace, ain, idisp, id
scanu2   1,   irate,     2,          3,       p4,       4,       5,      20,      9,       0.1,    .9,     .5,    .1,     0,      0,     a0,     1,  2
;ar scans kamp, kfreq, ifntraj, id
a1 scans    1,   200,    6,     2
a1  dcblock2  a1
outs a1, a1
endin

</CsInstruments>
<CsScore>
f1 0 128 10  1 .3 .1; sine 
f2 0 128 -7 .01 128 .01   ; displace
f3 0 128 -7  5  128  5    ; Masses
f4 0 128 -7  1  128  1    ; centering
f5 0 128 -7 -.1 128  -.1  ; damping
f6 0 128 -7  0  128  127  ; trajectory

f50 0 16384 -23  "/home/tjingboem/string-128"
f100 0  0   -44  "/home/tjingboem/string_128.matrxT"

i1 0 10     50
i1 12 10    100
e
</CsScore>
</CsoundSynthesizer>
```

First of all, my generated matrix size was incorrect. Hence the GEN44: out of range error.
Also, number of points started at 0, must be starting at 1 or higher, as long as it does not exceed 128 in this case.

And yes, i am using GEN44 now instead of 23.

The 'old' matrix and the newly generated one now sound exactly the same. A good basis for continue building the Utility.

Again, thanks for the feedback! 
(Next time, i'd better use the mailing list for this.)

I think the example above would be good to have as a comparison between the 2 systems on the Scanned Synthesis page.

**Comment by vlazzarini** [comment]
No problem! Happy your issue is solved.
