### ISSUE TITLE
Csound unable to defined GENquadbezier 

### ISSUE THREAD

**Issue by lukenzoner1** [csound/csound#1833]
Hello there,  
I tried to use GENquadbezier through the example in the manual. 
Csound returns :   
SECTION 1: 
ftable 2: Named gen "quadbezier" not defined 
ftable 3: Named gen "quadbezier" not defined
 ftable 4: Named gen "quadbezier" not defined 
new alloc for instr 1: INIT ERROR in instr 1 (opcode tablei.k) line 18: 
table: could not find ftable 2  from file C:\Users\lbasd\Music\ma_musique\Licence_1\csound\bezier_1.csd (1),
 - note deleted.  i1 had 1 init errors 
INIT ERROR in instr 1 (opcode tablei.k) line 18: table: could not find ftable 3  from file C:\Users\lbasd\Music\ma_musique\Licence_1\csound\bezier_1.csd (1), 
- note deleted.  i1 had 1 init errors INIT ERROR in instr 1 (opcode tablei.k) line 18: table: could not find ftable 4  from file C:\Users\lbasd\Music\ma_musique\Licence_1\csound\bezier_1.csd (1),
 - note deleted.  i1 had 1 init errors 
 -end of score.		  
 overall amps: 	   overall samples out of range:        0 

 Do you have any idea on how to fix this issue ?  
Regards, Lucien

**Comment by vlazzarini** [comment]
I checked and then gen was not being added to Csound. I fixed this in both csound6 and develop (7.0) branches.
