### ISSUE TITLE
KillGraph callback

### ISSUE THREAD

**Issue by fggp** [csound/csound#1841]
It seems that the callback function set by csoundSetKillGraphCallback is never called.

**Comment by vlazzarini** [comment]
what should we do with this? Remove the callback setting?

**Comment by fggp** [comment]
Should ask to Rory and Tarmo because it seems they're using the graph functions in Cabbage and CsoundQt...

**Comment by rorywalsh** [comment]
I was using them in Cabbage, but will not be using them in newer versions.

**Comment by vlazzarini** [comment]
I guess the best thing is to fix it so it gets called.

**Comment by kunstmusik** [comment]
FWIW I went back to 6.02 and 5.05 and did not see the kill graph callback being called anywhere. I suspect it's long been unused.

**Comment by vlazzarini** [comment]
ok removal then seems best. I'll prepare a PR
