### ISSUE TITLE
CMake and Csound on Android

### ISSUE THREAD

**Issue by rorywalsh** [csound/csound#1843]
It would be nice if we could have CMake manage the Android library. I know that projects built with Android Studio generate their own CMakeFiles.txt file which can cause issues with existing CMake builds, but in this instance the build is done with `ndk-build`, so it might be manageable?

**Comment by kunstmusik** [comment]
Was this done?

**Comment by DaveSeidel** [comment]
Well, I can say that I have not had any trouble building Csound 7 on
Android for a while now. So I guess it was fixed (probably by accepting a
lower CMake version number).

FYI, I also wrote up a bug for the CMake team on this issue, which they
accepted, but I don't believe that it's been addressed yet.

**Comment by kunstmusik** [comment]
I don't see CMake being used in the Android build.

**Comment by DaveSeidel** [comment]
I don't know what happens on Github, but I have (since cs6) used CMake to
build, and I'm still doing so.

**Comment by kunstmusik** [comment]
Interesting, what command are you using for this to pickup the Android NDK
toolchain and libs? If CMake works we should remove the older custom NDK
build files and migrate to that for the release build.

**Comment by DaveSeidel** [comment]
Oh gosh, very sorry -- I was confusing this with the Raspberry Pi CMake
build issue. Please ignore me, and sorry for the distraction!

**Comment by vlazzarini** [comment]
There's a CI build, merged. So yes, it was done. I see cmake commands in the PR.

**Comment by vlazzarini** [comment]
> I don't see CMake being used in the Android build.  n

What's this line doing then?
https://github.com/csound/csound/blob/e36ebaa59ffcd7ece2d14b2e1de2843a73e1bc51/.github/workflows/csound_builds.yml#L532

**Comment by kunstmusik** [comment]
That's new to me. If we're good to go with this, we should remove the older
build files and update build instructions.

**Comment by vlazzarini** [comment]
We're definitely good, the build works.
@nonameentername could you do what @kunstmusik is asking?

**Comment by nonameentername** [comment]
@vlazzarini @kunstmusik I can update the documentation and remove the old build files.

In the folder structure, there is an `Android` folder that I believe contains the old build files and instructions. Should the `CsoundAndroid` and `CsoundForAndroid` folders be updated to use the CMake Android artifacts, or should they be removed?
