### ISSUE TITLE
Update docs for Linux Mint/some buttons not functional

### ISSUE THREAD

**Issue by presentformyfriends** [csound/csound#1845]
I posted this issue due to confusion for those on [Linux](https://forums.linuxmint.com/viewtopic.php?t=362060) [Mint](https://forum.cabbageaudio.com/t/install-csound-on-linux-mint-20/2970) having trouble installing csound v6. 

I currently have ToneZ and csound v6 working on Mint 21.3 in LMMS but with a few caveats regarding button functionality.

Step 1 from the ToneZ README instructions:

> 1) Make sure to have csound v6 installed on your computer

I built csound from source following the instructions [here](https://github.com/csound/csound/blob/develop/BUILD.md#debian) for Ubuntu/Debian. Step 1 of the build instructions reads:

> Edit, as root, /etc/apt/sources.list and ensure that each line
> beginning with deb has another line below it that is identical except
> that deb is replaced with deb-src. Then run sudo apt-get update.

However my `sources.list` in Mint is empty. I figured out you have to edit `/etc/apt/sources.list.d/official-package-repositories.list` instead. Then follow the rest of the instructions to build csound v6.

Now back to the ToneZ README instructions:

> 2) Copy the "Retornz" folder inside your $HOME directory

Easy enough.

> 3) Finally copy the .so and/or .vst3 plugin where your host can find
> it

For myself on Mint, I had to copy the `ToneZ_V2.vst3` directory to my `/lib/vst3/` directory and then copy the `ToneZ_V2.so` file to `/lib/lxvst/` directory.

Now everything sounds great but for some reason, the "Open", "Folder", and "Save" buttons seem to do nothing for me, so I have to cycle through the presets manually. If anyone knows how to fix that, feel free to let me know.

**Comment by rorywalsh** [comment]
This relates to a software that was written with Csound, I don't think it's an issue for the Csound devs. It's probably best to file an issue on the ToneZ github tracker, or visit the ToneZ discord page and query the issue there 👍
