### ISSUE TITLE
Regression: Fix issue with argdecode

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#1878]
argdecode was modified to fix an issue in https://github.com/csound/csound/pull/1859 with setOption failures calling longjmp. This however caused issues with commandline csound not exiting early as it should on a failed argument. Diagnosing this, argdecode should be rewritten to use return values and calling code updated to use the return values. (See comment in https://github.com/csound/csound/pull/1859/files#r1596198649).

**Comment by vlazzarini** [comment]
Fixed in https://github.com/csound/csound/pull/1885.
