### ISSUE TITLE
Regression: fix issue with loops in UDOs

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#1879]
A regression was created in the deinit PR due to a complication regarding updating OPDS struct definition and has an impact related to loops in UDOs that was previously fixed. The issue is a little complex and requires some larger refactoring, but since we have a queue of PRs to get through we're taking on the regression and noting it here to fix.

The background to the issue is here: https://github.com/csound/csound/pull/1859#discussion_r1596201351

The comments there have links to the relevant mailing list thread that discusses the UDO looping issue.

**Comment by vlazzarini** [comment]
This has now been fixed in #1883
