### ISSUE TITLE
modulo is not actually modulo

### ISSUE THREAD

**Issue by henlo-birb** [csound/csound#1884]
The % operator in csound is a remainder operator, not modulo, despite what the docs say.

i.e. in csound, ```-1 % 3``` is ```-1```, not ```2```

At the very least someone should update the docs to reflect this, and ideally add actual opcodes to do real modulo.

In the meantime, here's a simple custom opcode that should work at i-time to do the same thing.

```
opcode mod, i, ii
    ia, ib xin
    irem = ia % ib
    xout irem < 0 ? irem + ib : irem
endop
```

**Comment by vlazzarini** [comment]
This has always been the case. It should be filled for the manual, under github.com/csound/manual. We certainly can't change behaviour.

**Comment by kunstmusik** [comment]
Checked and `-1 % 3`  returns `-1` in C++, Java, and Javascript, returns `2` in Python and Lua. Documentation for Java language spec and MDN docs clarify % as a remainder operator. 

MDN's description of difference between the two is good:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Remainder#description

Agree this should be filed as an issue for the manual repo.

**Comment by henlo-birb** [comment]
😥 sorry I didn't realize the manual was in a different repo

I do still think a real modulo opcode(s) should be added separate from the % remainder, just for completeness, I wasn't suggesting changing behavior
