### ISSUE TITLE
Parser error in cs7; worked for cs6 i think

### ISSUE THREAD

**Issue by jpffitch** [csound/csound#1904]

**Comment by jpffitch** [comment]
cs7 generates at $end of parsing the orchestra swwhick does nort occur in my orc
Sp at present I have no working csound, 6 oR 7

{{{
<CsoundSynthesizer>

<CsInstruments>
	sr	=	48000
	kr	= 	 4800
	ksmps	=	   10
	nchnls	=	    2

gasnd  init 0

instr 1
print p3
gaenv   transeg  1, p3-15, 0, 1, 15, -1, 0
endin

instr 2
      a1,a2     diskin2 p4,1
      al, ar    hrtfstat a1, p5, 0, "h48-l.dat","h48-r.dat", 9, 48000
                outs     al,ar
endin

instr 3
      a1,a2     diskin2 p4,1
      a3,a4     reverbsc        a1, a2, 0.85, 12000, sr, 1
      al, ar    hrtfstat a1*0.75+a3*0.25, p5, 0, "h48-l.dat","h48-r.dat", 9, 48000
                outs     al,ar
endin

instr 4
;Start  dur     baseamp ampinc  Noise/cps       Timbre   Loc
;p2     p3      p4      p5      p6              p7       p8

        i2 = cpspch(p7)         ; 11; 12.5
        i1 = 1/p3               ; once per duration - for envelopes
        ip6  = cpspch(p6%13)
        i3 = 2*(p4+p5)/2        ; these three assignments balance the three
        i4 = 2*(p4+p5)/6        ; branches of the drum instrument
        i5 = (p4+p5)/2.1        ;

                                ; branch 1 - NOISE
a1      oscili  i3,i1,2         ; generate steep exponential envelope
a1      randi   a1,ip6/2         ; generate band of noise with freq. given by p5
a1      oscili  a1,500,4        ; use noise band for amp input - ring mod.

                                ; branch 2 - INHARM
a2      oscili  i4,i1,2         ; steep envelope with lower amplitude than a1
a2      oscili  a2,i2*.1,3      ; generate inharmonic partials - 1,1.6,2.2,2.3

                                ; branch 3 - FUND
a3      oscili  i5,i1,1         ; decay of f1 is less steep than f2
a3      oscili  a3,i2,4         ; generates fundamental tone

                                ; global envelope to prevent clicking
a4      linseg  1,p3-.05,1,.05,0,.01,0
a5  =   2.5*a4*(a1+a2+a3)
        ;; Delay these signals to provide a little of the effect
a8      delay1  a5
al, ar  hrtfstat a5+a8, p8, 0, "h48-l.dat","h48-r.dat", 9, 48000
        out     gaenv*al,gaenv*ar
endin

instr 7         ;finger cymbals when high F, lower pitches interesting too
                ;p4=pch p5=amp p6=chnl1amp

i1      =       cpsoct(p4)
k1      expseg  .0001,.05,ampdbfs(p5),p3-.05,.0001       ;env
k2      linseg  1.69,.1,1.75,p3-.1,1.69         ;power to partials
a1      foscil  k1,i1,1,2.01,k2,1
ga1     =       a1
        out     a1
        endin

instr 10       ;simple marimba with modifications
               ;p4=pch p5=amp p6=bias p7=loc

i1      =       cpsoct(p4)
iamp    =       ampdbfs(p5-7)
k1      expseg  .0001,.03,iamp,p3-.03,.001      ;env
k25     linseg  1,.03,1,p3-.03,3
k1      =       k25*k1
k10     linseg  2.25,.03,3,p3-.03,2     ;power to partials
a1      gbuzz   k1,i1,k10,0,35,4
a2      reson   a1,500,50,1     ;filt
a3      reson   a2,1500,100,1   ;filt
a4      reson   a3,2500,150,1   ;filt
a5      reson   a4,3500,150,1   ;filt
a6      balance a5,a1
a7      reverb2 a6, 2, 1
;;a8      dam  a7, k(ampdbfs(-6)), 0.8, 0.2, 0.01, 0.5  ;;; ifreq = cpsoct(p4)
;;  al, ar  hrtfstat a8, p7, 0, "h48-l.dat","h48-r.dat", 9, 48000
  ;;; ihrd = 0.1
  ;;; ipos = 0.561
  ;;; imp = 1
  ;;; kvibf = 6.0
  ;;; kvamp = 0.08
  ;;; ivibfn = -1
  ;;; idec = 0

  ;;; a6 marimba ampdbfs(p5), ifreq, ihrd, ipos, imp, kvibf, kvamp, ivibfn, idec, 20, 10
  ;;; a7      reverb2 a6, 2, 1
  ;;; a8      dam  a7, k(ampdbfs(-0.3)), 0.8, 0.2, 0.01, 0.5
  ;;;al, ar  hrtfstat a7/10, p7, 0, "h48-l.dat","h48-r.dat", 9, 48000
  al, ar  hrtfstat a7, p7, 0, "h48-l.dat","h48-r.dat", 9, 48000
  out     al,ar
        endin

instr 11
kamp = ampdbfs(p5)
kfreq = cpsoct(p4)
kc1 = 5
kc2 = p6
kvdepth = 0.005
kvrate = 6

aenv  transeg   0, 0.5, 0, 0, 1.5, 1, 1, p3, 1, 0       ;; remove attack
asig fmbell kamp, kfreq, kc1, kc2, kvdepth, kvrate, -1, -1, -1, -1, -1, 16
al, ar  hrtfstat aenv*asig, p7, 0, "h48-l.dat","h48-r.dat", 9, 48000
        out     al,ar
endin

</CsInstruments>
 <CsScore>
 ; amptitudes
#include "score1"
;;f 5 0 256 1 "marmstk1.wav" 0 0 0
#include "score2"
#include "score3"
</CsScore>
}}}

**Comment by vlazzarini** [comment]
I don't understand the issue: why is csound 6 not working for you?

**Comment by vlazzarini** [comment]
Just picking up on this issue. I ran your code on Csound 7 and found a few lines that seemed to contain typos:

```
al, ar hrtfstat a10.75+a30.25, p5, 0, "h48-l.dat","h48-r.dat", 9, 48000
```

Maybe it is `a1*0.75 + a3*0.25` ?

```
a5 = 2.5a4(a1+a2+a3)
```

Maybe `2.5*Aa4*(a1+a2+a3)` ?

```
out gaenval,gaenvar
```

Maybe `gaenv, gaenv`?

With these resolved, the code compiles. I am closing this but if there are further problems, please re-open.
