### ISSUE TITLE
invalid escape sequence in commandline test

### ISSUE THREAD

**Issue by umlaeute** [csound/csound#1906]
The commandline test contains the following lines:
https://github.com/csound/csound/blob/b4e8bc58d864d9ec3ed391fcb38bd9d909444ab1/tests/commandline/test.py#L227-L228 where the string `"..\csound.exe"` contains the invalid escape sequence `"\c"`.

Obviously this is just a typo, and what is meant here is the literal backslash, rather than an escape sequence.

As of Python3.12, this is an error.

You could either use a raw-string (`r"..\csound.exe"`), escape the backslash (`"..\\csound.exe"`) or construct the path on the fly (`os.path.join("..", "csound.exe")`)

**Comment by vlazzarini** [comment]
Thanks, would it be possible for you to put through a PR for us?

**Comment by umlaeute** [comment]
sure. just a sec.
