### ISSUE TITLE
for loop [sf feature-requests #24]

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#192]
**Originally reported by Sourceforge User: joachimheintz**

i suggest to have a c-like for loop (i- and k-rate), with this syntax (here i-rate as example):
for iIndx=0, iIndx<iMax, iIndx++
...
endfor

thanks for considering!

**Comment by hlolli** [comment]
for-each in csound7?

**Comment by hlolli** [comment]
I'm going to attempt to make for-of and for-in as they appear in javascript, which would be similar to @vlazzarini's suggestion

for-of

```csound
for k1 of karray do
  printk2 k1
od

for i1 of iarray do
  print i1
od

for iarr of itwodimensional do
  for i1 of iarr do
    print i1
  od
od
```

and for-in

```csound
for Smember in mytype do
  prints "member-name of struct %s\n", Smember
od
```

**Comment by kunstmusik** [comment]
Closing as completed in https://github.com/csound/csound/pull/1670
