### ISSUE TITLE
Overload the linear algebra opcodes for the new vector data type. [sf feature-requests #26]

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#193]
**Originally reported by Sourceforge User: gogins**

The existing linear algebra opcodes (which nobody seems to be using) should be extended to handle the new vector data type (which can also do matrices) as well as the opcodes' own native data type and the table data type.

In addition, it may be desirable to port the opcodes to Eigen to reduce the number of dependencies in Csound.

**Comment by gogins** [comment]
Actually this should be: overload for Csound arrays.

**Comment by kunstmusik** [comment]
@gogins seems like a ticket for you.  Is this something that you will work on?  I haven't seen any votes from anyone else, so I suppose if you're not working on it we can just close the ticket and it can get re-filed at a later time if someone wants.

**Comment by gogins** [comment]
I am unassigning myself from this to free up more time for composing.

**Comment by kunstmusik** [comment]
Closing this issue as out of date.
