### ISSUE TITLE
mp3in duration issue

### ISSUE THREAD

**Issue by gleb812** [csound/csound#1968]
If duration of the instrument with mp3in opcode is longer than the length of mp3 file, it causes a segmentation fault.

 ; Orc
instr 1
a1 mp3in "test.mp3"  ; test.mp3 is shorter than p3  
out a1
endin

; Sco
i1 0 10

**Comment by vlazzarini** [comment]
libsndfile supports mp3 files now, so those opcodes are candidates to be moved out of the codebase. The segfaults need to be fixed though.

**Comment by vlazzarini** [comment]
I can't reproduce this here using csound 7.

**Comment by vlazzarini** [comment]
Fixed in PR #1971
