### ISSUE TITLE
mp3len string input issue

### ISSUE THREAD

**Issue by gleb812** [csound/csound#1969]
If ifilcod of mp3len is not a p-field but a string, it always returns length of 0.

In this sample ... 
iLen mp3len "test.mp3"
print iLen
... iLen always 0.

Probably it was coded to act properly only with p-fields and string codes, but its closest analog filelen supports strings, so I guess we expect this one support string input as well.

**Comment by gleb812** [comment]
filelen can now calculate the length of mp3

**Comment by vlazzarini** [comment]
I'm still working on this. The length seems to be always 0 no matter what. Even mp3in is reporting it wrong.
