### ISSUE TITLE
mp3len length calculation issue

### ISSUE THREAD

**Issue by gleb812** [csound/csound#1970]
It seems that mp3len returns only rounded values i.e. 2 sec, 5 sec etc
For a mp3 file of length 1.785 sec I got 2.000 sec.

**Comment by vlazzarini** [comment]
libsndfile supports mp3 files now, so those opcodes are candidates to be moved out of the codebase. The segfaults need to be fixed though.

**Comment by gleb812** [comment]
filelen can calculate length of mp3 file instead of mp3len

**Comment by vlazzarini** [comment]
I'm still looking to fix this in the mp3len opcode

**Comment by vlazzarini** [comment]
Length calculation is back (it was always 0 with the files I tested). However the mpadec code can only return lengths quantised to the second.

**Comment by gleb812** [comment]
OK, thanks! I tried diskin2 and filelen with mp3. it works for me, so I guess there is the universal solution

**Comment by vlazzarini** [comment]
but it depends on a version of libsndfile supporting mp3s, which may not be universal.
