### ISSUE TITLE
Scanned error unclear

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#1972]
i get an error because the matrix table is not found
but i think it is a confusing report.

I get this:

```
INIT ERROR in instr 1 (opcode scanu2) line 46: scanu: Could not find ifndisplace table
 from file /home/tjingboem/Music/tempCsd11536535125116168206.csd (1),	scanu2	1	.003	2	3	100	4	5	10	6	0.1	.9	.5	.1	0	0	a0	0	-1	
	  B  0.000 - note deleted.  i1 had 1 init errors
```

The error is about not finding the matrix, not ifndisplace
Should this error report be changed to ifnmatrix?

**Comment by vlazzarini** [comment]
addressed in #1973
