### ISSUE TITLE
ctrlselect bug

### ISSUE THREAD

**Issue by PvonN** [csound/csound#1990]
i guess, i found a bug in the 'ctrlselect' opcode.
i track the midi values with ctrlsave,
create a preset with ctrlpreset,
save them to a .txt file with ctrlprintpreset.
after this i call the presets with ctrlselect.

to describe it:
let’s assume i have cc 1 - 4.
i save a preset-1 with
cc1: 127
cc2: 0
cc3: 0
cc4: 0

i save preset-2 with
cc1: 0
cc2: 127
cc3: 0
cc4: 0

now i recall preset-1 and everything is like expected.
now i change e.g. cc4 manually to 127.
so the setting is
cc1: 127
cc2: 0
cc3: 0
cc4: 127

now i want to recall preset-2
and i get
cc1: 0
cc2: 127
cc3: 0
cc4: stays 127!!! but should be 0, like i the preset i saved.

this is the most basic .csd i can think of for this. it's quite a lot. sorry for this:

```
<CsoundSynthesizer>
<CsOptions>
-d -oadc -W -3
-+rtmidi=portmidi -M1 -Q1
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs = 1.0


instr initToZero
  outic 1, 0, 0, 0, 127
  outic 1, 1, 0, 0, 127
  outic 1, 2, 0, 0, 127
  outic 1, 3, 0, 0, 127
  turnoff
endin
schedule("initToZero", 0, 1)

instr presets
  #include "presets.txt"
  gkMidiData[] ctrlsave 1,\
    0,1,2,3
  
  // selecting preset mode, saving oder calling presets
  ;; 's' = 115 for save mode
  ;; 'c' = 99 for call mode
  iSave = 115
  iCall = 99

  kChar,kDown sensekey
  ;;  printks2 "kChar: %d\n", kChar
  // save trig
  kSaveTrig init 0  
  if kChar == iSave && kDown == 1 then
    kSaveTrig = 1
  else
    kSaveTrig = 0
  endif
  
  // call trig
  kCallTrig init 0
  if kChar == iCall && kDown == 1 then
    kCallTrig = 1
  else
    kCallTrig = 0
  endif

  if kSaveTrig == 1 then
    event "i", "print_save", 0, 1
  endif
  if kCallTrig == 1 then
    event "i", "print_call", 0, 1
  endif

  // save or call mode
  kModeSelect init iCall
  if kChar != -1 && kDown == 1 then
    kMode = kChar
  else
    kMode = kModeSelect
  endif
  kModeSelect = (kMode == iSave) ? iSave : kModeSelect
  kModeSelect = (kMode == iCall) ? iCall : kModeSelect

  // choosing preset number
  kPresetNum init 0
  kPresetNum = (kChar >= 49 && kChar <= 57 ? (kChar - 48) : kPresetNum)
  kPresetNum = (kChar == 48 ? 0 : kPresetNum)
  printks2 "Preset Number: %d\n",kPresetNum
  
  // Save preset
  kChanged changed kPresetNum
  printks2 "kChanged: %d\n", kChanged
  if (kModeSelect == iSave) && (kChanged == 1) then
    event "i", "savePreset_faderfoxec4", 0, 1, kPresetNum
  endif
    
  // call preset
  if (kModeSelect == iCall) && (kChanged == 1) then
    event "i", "callPreset_faderfoxec4", 0, 1, kPresetNum
  endif
endin
schedule("presets", 0, 6000000)

instr print_save
  printf "\nPRESET-SAVE-MODE\n",1
  turnoff
endin

instr print_call
  printf "\nPRESET-CALL-MODE\n",1
  turnoff
endin

instr savePreset_faderfoxec4
  printf "\nIS-SAVING PRESET: %d\n",1, p4
  kPreset ctrlpreset p4, gkMidiData
  ctrlprintpresets "presets.txt"
  turnoff
endin

instr callPreset_faderfoxec4
  printf "\nIS-CALLING PRESET: %d\n",1, p4
  ctrlselect p4
  event "i", "updateCC", 0, 1
  turnoff
endin

instr updateCC
  iCC0 chanctrl 1, 0, 0, 127
  outic 1, 0, iCC10, 0, 127

  iCC1 chanctrl 1, 1, 0, 127
  outic 1, 1, iCC1, 0, 127

  iCC2 chanctrl 1, 2, 0, 127
  outic 1, 2, iCC2, 0, 127

  iCC3 chanctrl 1, 3, 0, 127
  outic 1, 3, iCC3, 0, 127

  turnoff 
endin

</CsInstruments>
<CsScore>
i1 0 1
</CsScore>
</CsoundSynthesizer>

```

**Comment by vlazzarini** [comment]
What is in presets.txt included in one of the instruments?

**Comment by PvonN** [comment]
at init time it's empty. but it is necessary to call the presets from later on.
when a preset is save its saved like this to the .txt file via ctrlprintpresets:

kpre1  ctrlpreset  1, 1, 0, 127, 1, 0, 2, 0, 3, 0

**Comment by vlazzarini** [comment]
Why are you including it? It will copy its contents to that place in the CSD. Not sure why you want to do that.

I was looking at the documentation and it says nothing about saving presets. I don't think there is a way to do that. 

ctrlselect only selects the presets you created with ctrlpreset.

ctrlprintpresent only prints the values.

ctrlsave gets the values from controllers

**Comment by PvonN** [comment]
Why are you including it? It will copy its contents to that place in the CSD. Not sure why you want to do that.

if i don't do that, the presets are gone when i load the csound session the next time. ctrlselect needs it included somewhere to find then, when i saved the preset in another csound session.

I was looking at the documentation and it says nothing about saving presets. I don't think there is a way to do that.

the example in the manual says this and it works at my place also like this, but only with the bug i described:
 kk ctrlpreset 0,kc                           ; adding and numbering the current state as a preset to the list
 ctrlprintpresets                             ; prints Controller Presets (CC Presets) to the console
 ctrlprintpresets "./my_ctrlpresets.txt"      ; appends Controller Presets (CC Presets) to a file

**Comment by vlazzarini** [comment]
> Why are you including it? It will copy its contents to that place in the CSD. Not sure why you want to do that.
> 
> if i don't do that, the presets are gone when i load the csound session the next time. ctrlselect needs it included somewhere to find then, when i saved the preset in another csound session.

I am not sure about that. All ```#include ``` does is copy the contents (empty) of the text file where it is included. I don't think it is doing what you think.

> I was looking at the documentation and it says nothing about saving presets. I don't think there is a way to do that.
> 
> the example in the manual says this and it works at my place also like this, but only with the bug i described: 

```
kk ctrlpreset 0,kc ; adding and numbering the current state as a preset to the list ctrlprintpresets ; 
prints Controller Presets (CC Presets) to the console 
ctrlprintpresets "./my_ctrlpresets.txt" ; appends Controller Presets (CC Presets) to a file
```
Yes,  `ctrlprintpresets`  prints the content to a file, but nowhere I see mentioned that `ctrlpreset` can recall these contents.

**Comment by PvonN** [comment]
> I am not sure about that. All `#include ` does is copy the contents (empty) of the text file where it is included. I don't think it is doing what you think.

yes, i know what #include is doing. but in this way it makes the presets available for the next csound session and `ctrlselect` can call theses presets via the tag variable.

> Yes, `ctrlprintpresets` prints the content to a file, but nowhere I see mentioned that `ctrlpreset` can recall these contents.

`ctrlpreset` is in some kind of way preparing the presets and can put a tag variable to it, via the `ctrlselect` is calling this preset.

it is working. i can save and reload presets like i mentioned in this way.
all i do, what is different to the example in the manual is, that i #include the file with the presets printed with 'ctrlprintpresets'.

when i replace the #include file with  e.g.
```
 kpre2 ctrlpreset	2 , 1, 0, 0, 1, 127, 2, 0, 3, 0, 4, 0, 5, 127, 6, 0, 7, 0, 8, 0, 9, 0, 10, 0, 11, 0, 12, 0, 13, 0, 14, 0, 15, 0
 kpre3 ctrlpreset	3 , 1, 0, 0, 1, 0, 2, 127, 3, 0, 4, 0, 5, 0, 6, 0, 7, 0, 8, 0, 9, 0, 10, 0, 11, 0, 12, 0, 13, 0, 14, 0, 15, 0
 kpre4 ctrlpreset	4 , 1, 0, 0, 1, 0, 2, 0, 3, 127, 4, 0, 5, 0, 6, 0, 7, 0, 8, 0, 9, 0, 10, 0, 11, 0, 12, 0, 13, 0, 14, 0, 15, 0
```
this, btw. is the output of the `ctrlprintpresets`opcode.
i also get the same buggy behaviour. so it has nothing to do with the #include.

**Comment by vlazzarini** [comment]
Include only works before at the time of compilation, when you first run the code, so it would only run when you first start Csound. So what you would expect is that the presets will be set by those values once you start. 

I do not think there is a mechanism to save and recall, unless you recompile the code.

**Comment by PvonN** [comment]
> Include only works before at the time of compilation, when you first run the code, so it would only run when you first start Csound. So what you would expect is that the presets will be set by those values once you start.

yes, i know this. this .csd is designed for loading these presets in several sessions over time. and it's working! all the time! there is no problem at all with this and this is not what i describe as the bug.
i also wrote that i deleted the #include and instead i wrote the 'ctrlpresets'  by hand and i get the buggy behaviour as well.

**Comment by vlazzarini** [comment]
Ok, your example is complex, so I tried to reduce the issue to changing a preset and accessing it.

```
instr 1
k1 ctrlpreset 0,1,1,64
ctrlselect k1
km ctrl7 1,1,0, 127
printk2 km
k1 ctrlpreset k1,1,1,127
ctrlselect k1
km ctrl7 1,1,0, 127
printk2 km
endin
```
and this behaves as I expected.

**Comment by PvonN** [comment]
While trying to create a short and concise example, which describe my problem more precise, i noticed, that it is more complex and the interplay between opcodes are not like i thought. i will close this for know, because the preset opcodes are working well, but it has something to do with `outic` and maybe order of execution of things. i will try to solve this via the csound list.

thank you victor for your time!

**Comment by PvonN** [comment]
While trying to create a short and concise example, which describe my problem more precise, i noticed, that it is more complex and the interplay between opcodes are not like i thought. i will close this for know, because the preset opcodes are working well, but it has something to do with `outic` and maybe order of execution of things. i will try to solve this via the csound list.
