### ISSUE TITLE
Proposal: Enhance maxalloc with Instance Replacement Mode

### ISSUE THREAD

**Issue by nonameentername** [csound/csound#1995]
### Problem:
The current maxalloc behavior in Csound limits the number of active instances of an instrument. When using maxalloc in conjunction with MIDI, reaching the limit can result in unresponsiveness, as no new instrument instances are allocated when the limit is reached. This can hinder live performance or real-time interaction, especially in scenarios where new notes need to replace older or less relevant ones.

### Solution:
To address this, I propose adding an optional parameter to maxalloc that allows automatic termination of older or newer instrument instances once the allocation limit is reached. This ensures that new instances can continue to be allocated, providing a more responsive performance experience.

### New Syntax:
```
maxalloc insnum, icount, iturnoffmode
```

- insnum: Instrument number.
- icount: Maximum number of instances that can be allocated.
- iturnoffmode (optional): Specifies the behavior when the icount limit is reached. This parameter can take the following values:
  - 0: Default behavior. When the number of instances equals icount, no new instances are allocated.
  - 1: When the number of instances equals icount, the oldest active instrument instance is automatically turned off, and a new instance is created.
  - 2: When the number of instances equals icount, the newest active instrument instance is automatically turned off, and a new instance is created.
  
### Behavior:

- 0 (Default Behavior): This retains the current behavior of maxalloc. No new instances are created once the allocation limit (icount) is reached. Existing instances continue to play until they finish or are manually turned off.
- 1 (Replace Oldest): When the allocation limit is reached, the oldest playing instance of the instrument is automatically turned off to make room for a new instance. This is useful when older, less relevant notes should be discarded to maintain the flow of new notes. 
- 2 (Replace Newest): When the allocation limit is reached, the newest playing instance is automatically turned off, allowing older instances to continue playing. This behavior is beneficial in scenarios where the oldest notes should be preserved for musical or compositional reasons.

### Backward Compatibility:
By default, iturnoffmode is set to 0, ensuring that this change does not affect existing scores or scripts that do not make use of the new feature. This preserves backward compatibility while offering the new functionality for users who opt in.

**Comment by vlazzarini** [comment]
sounds good to me.

**Comment by kunstmusik** [comment]
Looks good, my only comment would be that iturnoff might be better renamed in documentation to something like imode or iturnoffmode or istrategy.

**Comment by nonameentername** [comment]
I named it iturnoffmode in the implementation.  I'll update the description to use that name instead.
