### ISSUE TITLE
Global variables using explicit types 

### ISSUE THREAD

**Issue by vlazzarini** [csound/csound#2003]
As far as I can see, global variables cannot be created using explicit types. This is a problem because it limits global variables to implicit type variable declaration. New standard types and UDTs do not use implicit types.

Ideal scenario
-------
In my view, the ideal scenario is this

```
var:type init ...   // variable in instr 0 pool

instr 1
import var         // variable from instr 0 pool added to local pool
export var2:type, ...    // variable exported to instr 0 pool  (optional arguments can be used to initalise it)
...
endin

instr 2
import var2    // importing var2 created in instr 1
...
endin
```

The export case will need to make sure the variable does not already exist in the  pools etc. and treat these cases accordingly. 

I think that importing and exporting go well with explicit types

For a scheme like this to work we will need changes to semantic analysis and to the parser. While we can implement `import` and `export` now without problems, any code using these will fail semantic analysis.
The left-hand side will be checked and the global variables used in instr 1 and instr 2 will not be found at  all! Currently the semantic analysis looks *only* for reserved names or names starting with `g` in the global pool and so the variables given to import and export are not going to be found. 

Alternatives
----------

If we want to avoid the complications of changing the parser, there is an alternative.
For export we could  simply implement it as

```
var:type export [...]   // create variable in the global pool and optionally initialise it
```

which does not seem problematic.

For import, while we could do 

```
var:type import
```

we have an issue: the compiler will have created the variable already in the local pool. The import opcode could look for the variable in the global pool but what should we do with the local variable? If it is used elsewhere in the instrument, it is all tied up in the code (instead of the global var)

We could shadow it with the global variable, which as far as I know can be done by

- pointing the local var CS_VAR_MEM to the global CS_VAR_MEM so they share memory. We need to make sure when the instance allocation is cleared (eg by orcompact()) that the global var memory is not washed away (I don't think it is, but needs checking). 

Unless there is a better way to achieve this, that's it. The local variable memory is left unused (and this is wasteful but possibly can be tolerated). 

From my perspective, while `export` looks good and perhaps that's the best way of implementing it anyway, `import` looks wrong.

Thoughts?

**Comment by rorywalsh** [comment]
I think it would cleaner if we could avoid using import. `export` seems ok, but I wonder if it might lead to confusion for people coming from other languages. Anything to be said for:

`var:type globalinit [...]   // create variable in the global pool and optionally initialise it`

**Comment by vlazzarini** [comment]
I had originally thought of that name for export, but in any case, creating a global variable like that is fine. The trouble is how to make it pass the semantic analysis and compile into args where it is used. We rely on the "g" letter for that.

I still think we need to explicitly bring into the local context so we can check for name clashes etc and it seems good practice, I don't see that global vars magically appearing in an instrument necessarily cleaner.

**Comment by vlazzarini** [comment]
But it may be possible for the compiler to check if the right hand arg of an opcode is in the global pool and not create a var in this case. We could then have a means of accessing the global var *and* passing the semantic analysis check.

Say

var:type globalinit ...

instr 1
var:type global

...
endin

that may be possible if we patch the compiler arg build.

**Comment by kunstmusik** [comment]
Reading from the global pool should be straightforward I think. Similar
scoping as Javascript, so we'd read from local and if not found read from
global.

**Comment by vlazzarini** [comment]
The only thing is that semantic analysis and compilation happen before we run any opcodes. So we need to either find a way to mark global variables or we have them in the rhs of opcodes.

**Comment by vlazzarini** [comment]
I did a test and it's possible to add an extra annotation to the type, like `var:type_global`  to make a global variable. I can then parse and compile it without anything else and it can be used anywhere, no special importing, etc, just like a global var. 

Would that be an acceptable solution?

Sample code

```
myvar:i_global init 1

instr 1
print myvar
endin
```

**Comment by rorywalsh** [comment]
I think so. It follows the current convention of marking a var as global, and not having to do anything special to access it within an instrument block. 👍

**Comment by vlazzarini** [comment]
what about `@global`? I prefer to have a special marker. 
The only downside I see with the scheme is that the type annotation becomes `type@global` and so for arrays we have `type@global[]` unless we change the bison code (which I want to avoid).

**Comment by vlazzarini** [comment]
This proposal is now implemented in the branch fix-global-var-explicit. 
I've also taken the chance to clean up some of the compiler code to make it more readable.

**Comment by vlazzarini** [comment]
On reflection the semantics seemed wrong. The variable is global not the type, so now I have this form instead `var@global:type`, which I am much happier with.  

This is the test code

```
myvar@global:i init 0
myarr@global:i[] fillarray 1,2,3

instr 1
print myvar
print myarr[0]
myarr[1] = 0
endin
```

**Comment by DaveSeidel** [comment]
Nice! What happens if you create a local variable with the same name as a
global?

**Comment by vlazzarini** [comment]
> Nice! What happens if you create a local variable with the same name as a global?
> […](#)


~~the local name hides the global name, as for instance in C.~~

EDIT: Once the global variable is created, any mentions of the name will refer to that global variable.

**Comment by DaveSeidel** [comment]
Sounds good.

**Comment by vlazzarini** [comment]
example:

```
<CsoundSynthesizer>
<CsOptions>
-n
</CsOptions>
<CsInstruments>

myvar@global:i init 2
instr 1
print myvar
myvar:i init 1
print myvar
endin

instr 2
print myvar
endin

</CsInstruments>
<CsScore>
i1 0 1
i2 1 1
</CsScore>
</CsoundSynthesizer>
```
prints

```
new alloc for instr 1:
instr 1:  myvar = 2.000
instr 1:  myvar = 1.000
B  0.000 ..  1.000 T  1.000 TT  1.000 M:      0.0
new alloc for instr 2:
instr 2:  myvar = 1.000
```

**Comment by vlazzarini** [comment]
and if you try to use the same name with a different type, you'll get a syntax error.
