### ISSUE TITLE
Old-style UDO support for explicit types

### ISSUE THREAD

**Issue by vlazzarini** [csound/csound#2006]
Currently it is not possible to use explicit types with old-style UDOs. As we promote the use of explicit typing and with the introduction of new standard types and UDTs, we have a choice:

1) Do not support old-style UDOs for these - which will mean adopting pass-by-reference as the only way forward for these
types (I don't think currently there is a way to ask for pass-by-copy besides setting a different local ksmps but I might be wrong)

2) Support old-style UDOs - provide an alternative to pass-by-reference.

**Comment by kunstmusik** [comment]
I don't think it's worth supporting old-style UDOs for pass-by-ref. We could add a means to do pass-by-value for new-style UDOs, but I'd argue that pass-by-ref with new-style UDOs gives it the same processing expectations as using native opcodes, which are all pass-by-ref.
