### ISSUE TITLE
Unable to compile with USE_DOUBLE=OFF when MSVC is used

### ISSUE THREAD

**Issue by lukaspirkl** [csound/csound#2009]
I am using the latest code from the `develop` branch and following [the build instructions](https://github.com/csound/csound/blob/develop/BUILD.md#windows-visual-studio--vcpkg). The only difference is that I switched the USE_DOUBLE to OFF as I want to embed the Csound into the different application and it is expecting the 32-bit samples. 

Everything in CMake is set correctly because I can see the `Building with 32-bit floats` message in the console during the build. Also, the output files are without the 64 postfixes. However, the binaries are still compiled with double as MYFLT because when I call the `csoundGetSizeOfMYFLT()`, it returns `8`.

I was investigating what is overriding the USE_DOUBLE and I found that this change causes it: https://github.com/csound/csound/commit/9fd826b74a986a8951b39df139228cf56927e3cc

This dirty hack makes it work for me:
```
diff --git a/include/sysdep.h b/include/sysdep.h
index 6a4a255df..e4f39861f 100644
--- a/include/sysdep.h
+++ b/include/sysdep.h
@@ -100,14 +100,6 @@ typedef uint_least16_t uint16;
 #include <AvailabilityMacros.h>
 #endif
 
-#if !defined(USE_DOUBLE)
-#if !defined(_MSC_VER)
-#include "float-version.h"
-#else
-#define USE_DOUBLE
-#endif
-#endif
-
 #ifdef USE_DOUBLE
 /* Defined here as Android does not have log2 functions */
 #define MYRECIPLN2  1.442695040888963407359924681001892137426 /* 1.0/log(2) */
```

This fix is obviously completely wrong but my understanding of Csound (and C in general) is not good enough to create a proper fix.

**Comment by vlazzarini** [comment]
Thanks! It looks like 32bit floats on Windows hasn't been working for a long time!
@rorywalsh @stekyne could you have a look?

NB: @lukaspirkl did you try just including float-version.h ? This is where we define the float type used.

**Comment by lukaspirkl** [comment]
Where should I include it? If I understand it right the code I removed is the place where it is included.
https://github.com/csound/csound/blob/develop/include/sysdep.h#L103
```
#if !defined(USE_DOUBLE)
#  if !defined(_MSC_VER)
#    include "float-version.h"
#  else
#    define USE_DOUBLE
#  endif
#endif
```
In my case `USE_DOUBLE` **is not** defined and `_MSC_VER` **is** defined. So it ends in the branch where it defines `USE_DOUBLE`. The result is that `USE_DOUBLE` is defined no matter what and double is used as MYFLT instead of float.

**Comment by vlazzarini** [comment]
Try just leaving #include “float-version.h” from what you removed.

========================
Prof. Victor Lazzarini
Maynooth University
Ireland

**Comment by lukaspirkl** [comment]
I can confirm that removing only the MSVC-related part fixes the problem. This feels more like a proper fix so I create a pull request. https://github.com/csound/csound/pull/2010

**Comment by vlazzarini** [comment]
Thanks @lukaspirkl @stekyne
