### ISSUE TITLE
Changes in the API: FindOpcode

### ISSUE THREAD

**Issue by gesellkammer** [csound/csound#2031]
In Csound6, a call to `csound->FindOpcode` (in csound6 this is called "find_opcode_new") with an opcode with signature
`opcode "test", a, ak` would be resolved correctly even if called with an init arg instead of a k arg. In csound7 this is no longer the case, nothing is found. (The opcode is only resolved if the variable is explicitly a k variable)

Example: given an opcode with an OENTRY defined as 

```c
    { "testopc", S(TESTOPC), 0, "a", "ak", (SUBR)testopc_init, (SUBR)testopc_perf, NULL, NULL}
```
I would assume that calling `csound->FindOpcode(csound, "testopc", "a", "ai")` would find the opcode since a call within csound in the form of "aout testopc ain, 0.5" would be valid, but this is not the case, null is returned instead. The opcode is correctly found when called as `csound->FindOpcode(csound, "testopc", "a", "ak")`. The former call using "ai" as input signature is successful in csound6 with  `csound->find_opcode_new(csound, "testopc", "a", "ai")`.

Any hints as to what was changed here?

**Comment by vlazzarini** [comment]
That is because the function used is `find_opcode_exact()`. If it is more useful to have `find_opcode_new()`, it's an easy replacement.

**Comment by gesellkammer** [comment]
Oh, that's good to know, thanks for looking into it. Would it be possible to have both, maybe in the form of a flag argument to FindOpcode?

**Comment by vlazzarini** [comment]
Flag is a good idea. I want to avoid the multiplication of similar functions. I'll make a PR.

**Comment by vlazzarini** [comment]
PR submitted.
