### ISSUE TITLE
pconvolve not looking at --env:SSDIR in CsOptions

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#2037]
in csound6 i could use `--env:SSDIR+=..` also for the impulse response file used in the pconvolve opcode.  
this is not any more working in csound7 as the attached example shows:
`INIT ERROR in instr 1 (opcode SimpConv) line 27: pconvolve: error while impulse file`

diskin is working as expected as the example shows once you cd in the csd directory.
[pconvolve.zip](https://github.com/user-attachments/files/17812029/pconvolve.zip)

**Comment by vlazzarini** [comment]
Fixed in #2038
