### ISSUE TITLE
Fix precedence so that SetOption() will always override .csound7rc

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#2042]
While reviewing PR #2035 I found that the tests failed due to having a .csound7rc file that contained `-odac -+rtaudio=pa_bl`. This ended up showing that API apps that call SetOption() but do not use CSD files will have values overridden by anything in .csound7rc. There is a call to checkOptions() in main.c:csoundStart() that is triggered in this scenario that causes the issue. 

The expected behavior is that .csound7rc has lower precedence than either CsOptions, commandline flags, or SetOption values (preferably in that order).

**Comment by vlazzarini** [comment]
Here's a possible solution:

- in csoundSetOption() we call checkOptions() if csound->csd is zero , and set it so it is not called again (as csoundSetOption() may be called more than once)
- then we proceed to set the arguments so the precedence is the same as in csoundCompileArgs().

**Comment by vlazzarini** [comment]
PR open so closing this.
