### ISSUE TITLE
Using EventString with named instruments uses the incorrect string argument

### ISSUE THREAD

**Issue by nonameentername** [csound/csound#2055]
Example csd:

```csound
instr buzz_instrument

  iChan = p4
  SNote = p5
  prints SNote
  iFreq = ntof:i(SNote)
  iAmp = p6 / 127
  iFn  = 1

  kSeg linsegr iAmp, .5, iAmp / 2, 1, 0

  asig buzz 1, iFreq, kSeg * iAmp, iFn
  outs asig, asig

endin
```

Executing the following event `i "buzz_instrument" 0 -1 3 "3A" 64` in the host api with `EventString` uses the instrument name (`buzz_instrument`) for p5 instead of the string parameter (`3A`).

**Comment by vlazzarini** [comment]
Thanks for the report and attempted fix. It looks like a very old bug because it was missing code for doubles. We have had doubles Csound for over 20 years, I reckon. Fixed in #2057
