### ISSUE TITLE
Crash on macOS with `recursive_mutex lock failed: Invalid argument`

### ISSUE THREAD

**Issue by chenrui333** [csound/csound#2072]
seeing some regression build/test failure with 6.18.1 release recently as 

```
libc++abi: terminating due to uncaught exception of type std::__1::system_error: recursive_mutex lock failed: Invalid argument
```

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/12549207814/job/34989865152

**Comment by vlazzarini** [comment]
Csound 6 is EOL. I'd suggest moving to Csound 7 (develop branch).

**Comment by chenrui333** [comment]
@vlazzarini that makes sense, any timeline for the csound 7 release?

**Comment by vlazzarini** [comment]
No timeline, but betas are available already (in binary or sources)
