### ISSUE TITLE
Explorer new parser design (Parser3)

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#321]
Explore using a new parser design where there is less semantic information in the Flex generated parser, making parsing just structural.  This would move more work into the semantic analyzer.  The goal would be to clean up current parsing issues, such as "opcode()" and "opcode ()" issues, as well as pave the way for future work (type inference, user-defined data types).

**Comment by hlolli** [comment]
this one seems done?

**Comment by kunstmusik** [comment]
Closing as this work has been merged into develop.
