### ISSUE TITLE
Use Emscripten with the Csound Manual to playback examples

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#327]
Explore modifying the Csound Manual to use Emscripten to render manual example entries within the browser.

**Comment by eddyc** [comment]
I was just thinking about this today, personally I find the way the manual is at the moment a bit inconvenient to write documentation for as it is non-trivial to figure out what tags to wrap your text in and you need to run scripts on csd files to embed them and so on, then you have to compile the manual which takes a little while.

The way the manual is at the moment is reminiscent of a wiki and I think it would be great if the whole thing could be just moved over to a wiki and hosted online. The pages could have embedded in them the ace editor and emscripten/pnacl for running examples, and pages could be added or edited online with a lot less friction than they are now.

This could tie into the learning csound work as the pages could just be a part of a larger wiki, it could also possibly host udos as well.

There are some nice wiki software packages out at the moment for instance https://github.com/gollum/gollum that github uses and http://daux.io/. These allow you to write documents using markdown which is very easy to learn.

**Comment by vlazzarini** [comment]
I am not sure I'd like to see the manual be moved into a wiki. 

Victor Lazzarini
Dean of Arts, Celtic Studies, and Philosophy
Maynooth University
Ireland

**Comment by eddyc** [comment]
Perhaps it is not fitting to be a wiki, but I still think there would be a great benefit to making documentation easier to create for csound, and doing so in a way that incorporates having working examples. I think it would be useful outside of the scope of just the manual, like with the learn csound site.

**Comment by vlazzarini** [comment]
I agree that it should be easier to create new pages. 

Victor Lazzarini
Dean of Arts, Celtic Studies, and Philosophy
Maynooth University
Ireland

**Comment by mantaraya36** [comment]
I've been thinking about this recently too, as I have had to do some work
with sphinx. Would it be worth the trouble to move to sphinx?

A

**Comment by fsateler** [comment]
+1 to ditching docbook ;)

Markdown would be great, although sphinx looks more sophisticated than most markdown tools and rst looks simple enough as well.

Given that github supports rst as well, it should make it easy to provide patches via the in-browser editor.

**Comment by gogins** [comment]
I have complained about docbook before. I am looking at Sphinx. If it does
what the front page says, great.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by vlazzarini** [comment]
Moving this discussion to the developer’s list…

I don’t link docbook either, however since we have god knows how many pages and words in that format, any
move away from it has to include an automatic means of conversion that works and only requires very little
hand editing.

I also want to stress that I am against making any type of public wiki or web etc-based manual. I don’t think there is
much longevity in this. I think we treat the manual as we do source code, then it will be maintained properly.

Regards
========================
Dr Victor Lazzarini
Dean of Arts, Celtic Studies and Philosophy,
Maynooth University,
Maynooth, Co Kildare, Ireland
Tel: 00 353 7086936
Fax: 00 353 1 7086952

**Comment by gogins** [comment]
I may close this and move it to the NaCl build of Csound. Or I may try to get the Emscripten audio up to snuff.

**Comment by gogins** [comment]
I am closing this issue and re-opening it with the target being PNaCl for now and WebAssembly in the future.
