### ISSUE TITLE
Unify the two Web Csound API's (Emscripten, PNaCl) into one that can choose one version or the other

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#328]
We should unify the two web csound API's into a single API that can choose to use PNaCl if it is available, or Emscripten if not.

**Comment by gogins** [comment]
I am not sure about the need for callbacks. I am just getting started looking at the requirements. One thing that seems reasonable is for the JavaScript interface to enable connection to WebAudio nodes for both input and output, as is done on Emscripten.

I also want to use this interface in Android so that users of the <CsHtml5> element do not have to work only on one platform or rely on conditional code. It should work the same on all platforms.

I also want the API to be as simple and intuitive as possible. I will post a proposed design here and ask for comments.

**Comment by gogins** [comment]
I have implemented a cut-down version of the API in a "csound" object in the HTML context on the desktop, in a test application. I may move this into CsoundQt. The functions that I have implemented are few because in this context, so far, there has not been a need to instantiate Csound or load a CSD file or start the performance, though these functions will be useful. Here is what I have done so far (described here as Java, but actually implemented as JavaScript):

 * int getVersion ()
 * void compileOrc (String orchestracode)
 * double evalCode (String orchestracode)
 * void inputMessage (String scorelines)
 * void readScore (String scorelines)
 * void setControlChannel (String channelName, double value)
 * double getControlChannel (String channelName)
 * void message (String text)
 * int getSr ()
 * int getKsmps ()
 * int getNchnls ()

**Comment by gogins** [comment]
I need input regarding the JavaScript interfaces to Csound. My goal is to unify the signatures of the most important JavaScript functions across all of the interfaces, and also make sure that the Csound object is named "csound" in all the interfaces. This will enable a piece developed for one JavaScript interface to run the same way in all the other JavaScript interfaces.

I have compiled a spreadsheet comparing the Csound API in C (csound.h) with various JavaScript interfaces (CsoundQt, NW.js, Android, Emscripten, PNaCl). You can view this spreadsheet at  https://docs.google.com/spreadsheets/d/1C9RqnV5Tlxag5xnMNP1VXO_W-_XirB5BIidASWvhJ9E/edit?usp=sharing. The "C" column consists of all "csound*" functions exported from the csound shared library. The "Objective" column names all functions that I would like to see exposed in the JavaScript interfaces. The remaining columns indicate what functions currently ARE exposed in the indicated JavaScript interfaces.

I am aware that different interfaces may do somewhat different things using the same names, or use different names for doing the same things, or that callbacks are used in some interfaces but not in others. Again, my objective here is to ensure that all the interfaces support the functions in the "Objective" column (without removing code that already exists), and the contents of this column are open to change. These functions should all be synchronous and should all use only elementary data types.

(1) Currently, the "csound" object is instantiated by the host and injected into the user's JavaScript context. In other words, "csound" is a static singleton, as far as the JavaScript context is concerned. Is it important to be able to create a new instance of Csound FROM JavaScript? 

(2) In the Csound C++ API we have the naming convention that all functions start with an initial capital letter, e.g. ReadScore. In most of the JavaScript interfaces, most functions start with an initial lower-case letter, e.g. readScore. What is your preference: (a) lower case, (b) upper case, (c) both lower and upper case?

(3) I am assuming that any audio streams and/or MIDI messages communicated between the JavaScript context and Csound itself will be accomplished via Web Audio as in Emscripten and/or Web MIDI, not by use of lower level Csound APIs. Is this reasonable? Of course Csound itself may still be able to directly access audio and MIDI ports on the computer.

(4) Please let me know what functions you would like to add to or remove from the list in the "Objective" column, i.e. from the common JavaScript interface.

(5) The "Perform" function in the JavaScript interfaces runs in a separate thread, similar to CsoundPerformanceThread. This function is called after the orchestra is compiled to actually perform the score and/or handle real-time events. No code whatsoever in this thread communicates directly with the JavaScript context, all such communication is via thread-safe FIFOs.

As background for your thoughts, please consider that in some but not all HTML/JavaScript environments (e.g. the Chromium Embedded Framework used in CsoundQt), the browser runs in one process ("browser"), and the actual user interface and JavaScript virtual machine run in another process ("renderer"); these processes must communicate using an IPC channel and this contributes overhead to Csound API function calls. Also consider that JavaScript is single-threaded, and can simulate multi-threading only with Web Workers or libuv threads that also need IPC to communicate. Of course, Csound itself, isolated from the JavaScript VM, can run multiple threads.

**Comment by kunstmusik** [comment]
My preference in all of this is that we have CsoundObj API that matches in features and design to the CsoundObj implementations on Android and iOS.  This would make porting of applications between CsoundObj implementation easier.  

Otherwise, for method names, I prefer camel case with first letter lower-case. That's the norm in Java at least, and at least for the projects I've used in JavaScript that are object-oriented (though, I've seen upper-case there too, just not as often).

**Comment by gogins** [comment]
iOS is not a JavaScript platform, or is it?

The main issues that I see are (a) callbacks and (b) the use of composite
types. I would prefer to avoid both in this common API. That does not mean
that I want to remove them anywhere.

Best,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by kunstmusik** [comment]
iOS is not JS, yes.  However, I do think CsoundObj as an API can be a good
fit on JS platforms.  Maybe what we need to try first is a prototype of
CsoundObj on top of Emscripten and PNaCl and see where we are from there.

**Comment by gogins** [comment]
I agree that camel case should be used, I have changed my spreadsheet
accordingly.

I see the following issues with using CsoundObj in iOS as a prototype.

(1) What I have already done (see the spreadsheet) includes a number of
functions that are not in CsoundObj.

(2) CsoundObj makes use of callbacks, I do not want to use callbacks. They
are good for your original use case but I do not think they are good for
users without a lot of programming experience trying to write pieces.

Best,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by kunstmusik** [comment]
What you have in your Csound class may be orthogonal to what is provided in
CsoundObj.  CsoundObj always exposes the underlying Csound implementation,
whether that's the Java Csound class on Android, or CSOUND* on iOS.  The
same could be done for JS versions.

As for callbacks or not, CsoundObj's offering of the CsoundBinding system
is optional.  Users can always elect to grab a Csound channel pointer and
asynchronous read/write as they wish.  I don't think having the option for
CsoundBinding's conflict with other styles of communication, and would
argue having a clear-cut way to do synchronous communication that follows
the same architecture as on Android and iOS would be useful.

**Comment by gogins** [comment]
How does CsoundObj expose the underlying implementation? If it is by
inheritance that is useful in this case. Or does it expose the underlying
implementation as another object?

I agree that have the CsoundBindings is useful and I will consider that for
a later stage of implementation.

Best,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by kunstmusik** [comment]
In CsoundObj, there is a getCsound() method.  This allows users to fallback
to the standard Csound API.

**Comment by gogins** [comment]
I have created a C++ class that encapsulates threading and other operations defined for the base level of the HTML interfaces. I will now change this to a subclass of the existing Csound class defined in the header-file-only csound.hpp class, and I will bring my threading stuff into this subclass. It will then in turn become the base class for various JavaScript interfaces. I figured out how to do the callbacks, at least for NW.js, so I will look again at the CsoundBindings.

**Comment by gogins** [comment]
The advent of WebAssembly appears to mean that PNaCl will fade and Emscripten will merge with WebAssembly (perhaps as a toolchain front end). I am considering closing this issue with a recommendation that the Emscripten build of Csound be improved and maintained with the goal of becoming the WebAssembly build of Csound. I am not however closing this issue yet, pending comments or suggestions.

**Comment by gogins** [comment]
I am now closing this issue and opening an issue to implement a WebAssembly build of Csound.
