### ISSUE TITLE
csound~ 1.1.2 on Max 6.1.7 32 bit Windows does not load

### ISSUE THREAD

**Issue by alfonso73** [csound/csound#345]
Hi all,
1. if i install csound~ in the Package directory of Max the external is not recognized

2. if i install csound~ in the externals' directory of Max the external is recognized but does not load 'cause the system complains about a missing "pthreadGC2.dll" file.

3. If i place a "pthreadGC2.dll" file in the Csound directory the warni9ng about the missing file disappear but the Max window says " Error 193 loading external csound~"

thanks and all the best

**Comment by rorywalsh** [comment]
I can get this working on my Win8 machine if I:

1) use '-static-libgcc -static' when building any dll that csound64.dll loads on startup
2) add -+rtaudio=null to any .csd file that is to be used in max as it will disable the loading of rtpa.dll

**Comment by kunstmusik** [comment]
@rorywalsh Could you do a pull request with the changes?  As for rtaudio=null, that could probably be done automatically by csound~, no?

**Comment by rorywalsh** [comment]
Will do, but note that my changes will cause plugin opcodes on all platform to be built with static linking. I'm not sure that something you wish to do. Anyway, I'll put in a pull request later and you can review it. And yes, it would be better to add -+rtaudio in csound~.

**Comment by vlazzarini** [comment]
Any movement in this one? Can we finalise it and close it (appears to be a cmake issue now)

**Comment by rorywalsh** [comment]
Hi Victor. I've absolutely zero Cmake chops so I'll have to leave this with someone who knows how to make these changes.

**Comment by vlazzarini** [comment]
Steven is our go-to man for CMake. Do you have all the info you need to make these changes @kunstmusik?

**Comment by kunstmusik** [comment]
I looked into this.  We already had --static-libgcc for C artifacts set in the main CMakeLists.txt.  I added a flag for --static-libstdc++ for C++ artifacts.  I'm able to build most things but it fails on libcsnd6 as it complains about not having a reference to pthreads, but I seem to remember this being a problem before and am not sure if it's just me or due to the change I made.

@gogins and @rorywalsh : Could you test the latest in develop to make sure things are still compiling for you?  Also, @rorywalsh  could you test if change does what is needed for csound~?

**Comment by rorywalsh** [comment]
Hi Steven. I'm afraid I'm only getting a chance to look into this now. It seems that Mike had no problems preparing the Windows installer for the last release, so I'm assuming that everything compiles Ok. I'm going to check now myself. If there are any issues I will report back to you.

**Comment by rorywalsh** [comment]
It looks like csound~ is working now. But I'm getting a hang on exit. The problem, windows informs me, is to do with the libgcc dll. But if that's the case then it would seem that the -static-libgcc is not making any difference when building?

**Comment by alfonso73** [comment]
Hi all guys,
i'm thinkin' about trying another compile of csound~.mxe and csound~.mxe64.
Has some progress on csound~ being made recently?
Maybe i need some special csound.dll version to try compiling for 64 bit
architecture?
Many thanks and all the best!
a.

www.elgallorojorecords.com
soundcloud.com/alfonsosantimone
www.facebook.com/alfonsosantimone

**Comment by rorywalsh** [comment]
csound~ for 32bit Max is fine, but until Cycling74 supports building of
64bit objects with MiinGW you will need to use MSVC. It'll be quite a bit
of work I'd say. In fact, I think it might be a good idea to just port
Victor's csoundapi~ object in Pd to Max. It would be far simpler to
maintain in the long term.

**Comment by vlazzarini** [comment]
Why would it be simpler?

**Comment by alfonso73** [comment]
I guess is just a matter of workin on things to let the code be compatible
with MSVC compiler.


www.elgallorojorecords.com
soundcloud.com/alfonsosantimone
www.facebook.com/alfonsosantimone

**Comment by rorywalsh** [comment]
It's far more lightweight than the Max object from what I can tell. Plus, I
can follow your code, just about!

**Comment by vlazzarini** [comment]
I am not sure about it. The source is OK as far as I can see, and it is being maintained. The trouble is to do with building and linking in Windows. I thought this was solved by your contribution as discussed above. Shouldn't we close this ticket?

**Comment by rorywalsh** [comment]
32bit version is fine. Alfonso is talking about a 64bit version. 64bit
objects can't be built with MinGW.

**Comment by rorywalsh** [comment]
When I say can't I mean I failed in my attempts and the cycling74
developers can't manage it either. I'm sure however that it could be done,
if in the hands of the right person!

**Comment by vlazzarini** [comment]
I built a 64bit Csound with mingwn64 here, so it is possible. I can't however commit to maintain this build.

**Comment by vlazzarini** [comment]
It seems that we should close this ticket, since the 64bit windows is a separate issue.

**Comment by alfonso73** [comment]
Would you mind victor making a short tutorial on how to compile Csound on
mingw64?
Anyway the thing is that Max SDK seems to compile only with Visual Studio
and not on mingw.
Yes 64 bit is a separate issue. Should we open another ticket and close
this one?


www.elgallorojorecords.com
soundcloud.com/alfonsosantimone
www.facebook.com/alfonsosantimone

**Comment by vlazzarini** [comment]
It's been a while, but I don't think I did anything terribly different. I downloaded mingw64, msys, cmake, etc (as for any ordinary build), build libsndfile with it, and placed it where cmake would see. Then I ran cmake and make. You can have a go, and ask questions in the list as you go along. I am closing this ticket, because it is done.

**Comment by alfonso73** [comment]
ok thanks.
a.

www.elgallorojorecords.com
soundcloud.com/alfonsosantimone
www.facebook.com/alfonsosantimone
