### ISSUE TITLE
Update Csound Android to match changes to CsoundObj API in iOS/OSX

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#353]
CsoundObj in iOS has been updated with renamed methods and new classes that better encapsulates features (GUI, Motion, etc.). These changes need to be updated in Android so that the API's are in line with each other.

**Comment by gogins** [comment]
1146 is 8687
311ULd8a NJI(mko0 %RDX6tfc &YGV8uhb *UHB9ijn %T^Y7u8i
6341
4Esz5rdx
9xBdF~j3
Act Blue Bright Launch Internals 48
AdaptivTrak michael.gogins XXAYMYOIRY
Aetna 01michaelgogins Jamboree98
Amazon perforate allocation
ASCAP MichaelGogins 1qaz2wsx
away.emea.sungard.com 1qaz2wsx concatenate
away.sungard.com
AXA Isaac Castle 4
bago1279 8i9o0p
Benefits Online heidigogins !QAZ2wsx confirmation 2303589
Benefits heidigogins 1qaz2wsx
borage simpson thunder
Clothing sizes American XLT Chest/Jacket 44 (Barbour C46/117) Neck 17.5
Waist 38 Arms 37.5 Leg 32
Computer Music Journal 8872775 1qaz2wsx
CGMS24ever
Citrix Engine8
Dropbox blastoff maven
f93kdlf9
facebook amber anticipating
FAST 10.254.66.24
FERC ID #F269572 1qaz2wsx
fpml.org gogins Q141DB
GitCentric QQM5UyjeqTJv
Github bubblegum 14 forty / passcode yorker chop sting
Google code Jg5jn3fc3EV7
heidirogersmusic.tumblr.com oleo1951
Intercall PIN 9223 Code 618 3454
HD 345Ertdfg
Hedge360 internal\michael.gogins *UHB9ijn
iPay Sungard-US-SG1 MGogins@Sungard-US 1Qaz2wsx3edc
IPCROUTE NYCp2PS1
Kobo borgandiodematter
LinkedIn ZSE4xdr5
Meetup carrot brain rug
Merrill Edge h 0200 593716 suzanne 51
MS braggageDoor
Microsoft account 1qaz2wsx
Monis ^YHN7ujm
Monis client site *UHB9ijn
MSDN MVLFF70AB652 BrightNutshell MSVS key BBJ4B-WBV7Q-DFHJG-G97DD-GXXKR
2010 key YCFHQ-9DWCY-DKV88-T2TMH-G7BHP
Netflix bishop 48 sand
NVFUV8G7EN
NYCEMF webring spazz primal
NY Times 065841744 heidi195 password
Outlook Web access for SunGard:https://na.owa.sungard.com/owa/
Overnight Prints blargorb multipurpose snoose
padi1234
PayPal urbane72brass
Phone 1235789
Pianoteq serial number 26N0U-MDZPK-C8GXG-Y904E
Pianoteq user area password mmeZXByC
Remote access:https://na.owa.sungard.com
*Rhapsody lake uzbekistan
Salamander brontosaur reverse
SGD8104 21247-180-32
Showroom78
Social security porridgebank hRf7fd%*edde
sourceforge yorker chop sting dir is /home/pfs/project/csound
starsnyvm26-23 panadmin panorama
Steinberg developer gogins 1qaz2wsx
SunGard remote access https://away.sungard.com then domainless username,
1Qaz2wsx and key
Trepp 10.255.22.31
tumblr njal burrow everywhere
Vanguard gogins 1qaz2wsx
WebEx michael.gogins ONi:<=827
WEP 5A97421321
xD0Gwar7
boring corvette squabbles

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com
