### ISSUE TITLE
Use stdout for data output

### ISSUE THREAD

**Issue by gesellkammer** [csound/csound#372]
Csound uses stderr to output all logging (version, warnings, help and other information). When parameters like "--get-system-sr" or "--devices" are passed, which ask specific information from the csound executable and then exit, this information is written to the same stream, making it difficult for the invoking program to parse the data. In the cases being mentioned, since this is the output the user has asked for, these should be sent to stdout, or maybe another strategy could be used to make this data easily parsable without using stdout (a file?)

## Use case

1) I need to call csound with the sample-rate of the default audio device, so that I can rely on the operating system's already provided mechanisms to select device and sample-rate. I call csound with `csound -odac --get-system-sr > output.txt`. output.txt contains the text "48000" and this information is then used to call csound with `csound -odac --sample-rate=48000 myfile.csd`
2) What would happen if multiple arguments asking for information are passed, like `--get-system-sr` and `--devices`? As output format something like json could be adopted, then the resulting file would be

```
{
    "sample-rate": 48000,
    "input-devices" : ["adc0 (...)", "ard1 (...)"],
    "output-devices" : ["dac0 (...)", "dac1 (...)"]
}
```

**Comment by vlazzarini** [comment]
I thought about this and the best way is to provide another message printout function (csound->Message2()) which could be used to direct output elsewhere. As a rule, libraries should avoid using printf etc directly, but provide an interface. We can deal with this when we review the API for 7.0

**Comment by vlazzarini** [comment]
I have done three things to address this request:

- added the CSOUNDMSG_STDOUT  attribute type to csound messages.
- change the default message callback to respond to this by placing messages with such attribute in the stdout.
- modified the informational messages for devices and sr to print using this attribute. So these should go to STDOUT now.

More generally, any message can be directed to stdout by using csoundMessageS with this attribute.
