### ISSUE TITLE
global no-carry behavior in score

### ISSUE THREAD

**Issue by tgrey1** [csound/csound#374]
It would be helpful to be able to "turn off" the default carry behavior, so that the no-carry symbol "!" doesn't have to be explicitly stated in each note statement.

For example, if the behavior were enabled the following note statements would parse the same:
i 1 1 1 1 2
i 1 2 1 !

versus:

i 1 1 1 1 2
i 1 2 1

**Comment by jpffitch** [comment]
Do you want this for all the score (globally) or do you want it switchable by a score opcode?

**Comment by tgrey1** [comment]
For the use case I had intended, globally for the score would be sufficient... but I can see where switchable behavior might be useful to others in the future.  Up to you guys, either will work great for me.

**Comment by jpffitch** [comment]
I have a version working switchable.  Currently has a bug when omitting 
p1, p2 or p3 but I tink I understand a way of fixing -- later today I hope

**Comment by jpffitch** [comment]
Committed to git and seems to work

in score 
C 0
switches automatic carry off for p4 onwards.  It canbe restored with
C 1

So closng issue
