### ISSUE TITLE
Add a command-line flag to set ksmps 

### ISSUE THREAD

**Issue by gesellkammer** [csound/csound#379]
Csound already has --sample-rate and --control-rate. It would be good if ksmps could also be set via the command-line, so that control rate can be inferred from the sample-rate.

```
$ csound -odac --ksmps=64 mycsd.csd
```

In this case, csound would use the default audio-device, and since no sample-rate has been specified, it would use the default sample-rate of this device, if not otherwise indicated in the .csd file. 

The .csd file would not need to have any indication of `sr` or `ksmps`. `sr` would contain the sample-rate being used. There would be no default sample-rate, the default would then be the system sample-rate.

**Comment by vlazzarini** [comment]
I've added --ksmps=N, also allowing now -r and -k to be used independently and in combination with --ksmps.
