### ISSUE TITLE
Command line flag to get midi devices as easily parseable output

### ISSUE THREAD

**Issue by gesellkammer** [csound/csound#383]
To my knowledge, there is no way to get information about midi devices available to csound from the command-line. A flag similar to --devices=in and --devices=out but for midi would help using csound as audio/midi tool, without having to rely on current workarounds, like sending -M999. Of capital importance is that the output can be easily parsed and that multiple information requests are possible in one call. For example

```
$ csound --devices=in --midi-devices=out --get-system-sr
```

### USE CASE

I use csound embedded in instruments, interacting with very specific hardware, and often used by musicians who could not care less about what is running inside. I need a reliable way to start csound in a headless environment. Particularly for midi devices, which cannot be set by name (-M and -Q accept only an index) this enhancement would make working with csound in such "hostile" environments much easier

**Comment by vlazzarini** [comment]
done.

**Comment by jpffitch** [comment]
Not finished unti documented

**Comment by vlazzarini** [comment]
documented now
