### ISSUE TITLE
Multithread problem

### ISSUE THREAD

**Issue by Oeyvind** [csound/csound#390]
This occurs in a Python program using Csound via the API. It
is CPU heavy, so we use multiprocessing in python via zmq.

After running for (some random amount of) time, our Python program simply halts.
We've investigated the cause and found that it stops on the call to
PerformKsmps.

In the C source code, we've inserted some print statements, allowing
us to see that the lock is acquired but not released in
function csoundPerformKsmps in csound.c
here:
csoundLockMutex(csound->API_lock)

And further, we see that it halts on csound->spinrecv in kperf_nodebug

**Comment by vlazzarini** [comment]
Added a timeout to the jack input lock.
