### ISSUE TITLE
plltrack cpu usage

### ISSUE THREAD

**Issue by Oeyvind** [csound/csound#401]
It seems that plltrack can increase CPU usage at very low input signal levels.
This would appear to be denormals related, but it does not disappear
if I denorm the signal before plltrack. However, if I lower the
tracking signal level threshold (kthresh) to e.g. 10^-20 and manually
denorm the input signal by adding noise at a level of 10^-19, then I
can prevent it from increased CPU usage.

I haven't been able to reproduce the behaviour in a scaled-down csd,
but I am quite sure I'm looking in the right place for the bug, since
- the problem does not appear if I comment out plltrack and replace it
with a static cps value,
- the problem also re-appears if I keep plltrack in there but replace
its output with a static value (meaning that the rest of the
instrument gets the static value for cps, and plltrack is just
processing a cps value that is never used for anything
- I can make the problem go away by fiddling with the kthresh value in
relationg to the noise floor set by a manual denorm
- The problem still appears if I set kthresh to 0.0, The kthresh value
needs to be a value larger than 10^-24, and I need to add noise at a
level above this threshold, then it behaves nicely.

**Comment by vlazzarini** [comment]
I have looked at this, and did a simple test CSD that demonstrated that the CPU use would climb if the input was muted. So I fixed this by checking for a muted input and bypassing the processing in this case. So now if you mute the input (by making it 0 or constant), there is no processing and CPU is saved.
