### ISSUE TITLE
latest pull of csound segfaults with ftable creation

### ISSUE THREAD

**Issue by PaulBatchelor** [csound/csound#418]
I am running Csound 6.03.2 with doubles. This bug was tested on a Debian x86_64 machine and a Slackware x86 machine. 

given this test file:

<CsoundSynthesizer>
<CsOptions>
-o test.wav
</CsOptions>
<CsInstruments>
sr	=	44100
ksmps	=	1
nchnls	=	2
0dbfs	=	1
gisine ftgen 0, 0, 4096, 10, 1
instr 1	
endin
</CsInstruments>
</CsoundSynthesizer>

Csound exits with a segfault. 

When I remove the ftable creation, Csound compiles this CSD with no issue. This also seems to happen with ftable creation in the score, and the use of the ftgentmp opcode.

**Comment by jpffitch** [comment]
Segfaults for me on 64bit Debian and OpenSuSE currebnt git version.

Will look furter.

(for developers....0
==6356== Invalid write of size 8
==6356==    at 0x4C2DD23: memcpy@@GLIBC_2.14 (in 
/usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==6356==    by 0x4E7FDA8: hfgens (fgens.c:274)
==6356==    by 0x4FB8302: ftgen_ (ftgen.c:154)
==6356==    by 0x4FB8302: ftgen (ftgen.c:164)

Line of program comments with "is this right"  !!

==John ff

**Comment by jpffitch** [comment]
Fixed in git -- it was te wrong fix for another bug no one has seen yet....

**Comment by vlazzarini** [comment]
6.03.2? We are beyond 6.04. What's going on?

**Comment by PaulBatchelor** [comment]
Ignore that bit about the version number. I was looking at the wrong build.
