### ISSUE TITLE
csoundReadScore does not release memory

### ISSUE THREAD

**Issue by aure** [csound/csound#419]
I am using the CsoundObj for iOS and I am programmatically sending thousands of lines to Csound, one at a time and when I do so the memory usage skyrockets and never gets released.  

I even changed the sendScore method to just send csound a blank string:

- (void)sendScore:(NSString *)score
{
    if (mCsData.cs != NULL) {
        csoundReadScore(mCsData.cs, "");
    }
}

and it still hangs on to memory, so I don't believe it is a problem in the CsoundObj itself.

**Comment by vlazzarini** [comment]
If you don't need the extra score processing, it is a waste to use csoundReadScore. Replace it for csoundInputMessage, which is much more lightweight

Victor Lazzarini
Dean of Arts, Celtic Studies, and Philosophy
Maynooth University
Ireland

**Comment by aure** [comment]
Fantastic!  I'll take it.

**Comment by aure** [comment]
P.S. Victor, you rock!  Thank you.
