### ISSUE TITLE
Release segments not initialized from i-Statements

### ISSUE THREAD

**Issue by aure** [csound/csound#420]
Using feedback from Victor on the csound mailing list, I attempted to create a release for a note by sending a negative p3 for a held note and then a negative p1 for a note-off event, which should trigger the release but just stops the note.  I did this on this xadsr example from the manual.  But, the stop note i-Statement just stops the note and does not start the release.  Can you see what I am doing wrong or if it is something wrong with csound.  Here's the csd file showing the issue.

<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac     ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if RT audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o xadsr.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs = 1

instr 1

iatt  = p5
idec  = p6
islev = p7
irel  = p8

kenv  xadsr iatt, idec, islev, irel
kcps =  cpspch(p4)    ;frequency

asig  vco2  kenv * 0.8, kcps
  outs  asig, asig

endin

</CsInstruments>
<CsScore>
f 0 10

i 1  0  -100  6.09  .0001  1 .1  .7     ; start a held note with a defined long release
i -1  2 ; should start the release but instead just stops the instrument cold

;i 1  0  1  7.00  .0001  1  .01  .001 ; short attack
;i 1  2  1  7.02  1  .5  .01  .001    ; long attack
;i 1  4  2  6.09  .0001  1 .1  .7     ; long release

e
</CsScore>
</CsoundSynthesizer>

**Comment by kunstmusik** [comment]
I this is not necessarily a bug.  adsr and xadsr are noted in the manual as not being appropriate for MIDI notes, but really they should note that the release segment is calculated as part of a note's total duration.  madsr and mxadsr should be used if you want the release to occur after a note is turned off.  Note: madsr and mxadsr can be used without MIDI.  You can also use transegr, expsegr, and linsegr if you want the behavior where the release segment is done upon note turnoff. 

Closing out issue.

**Comment by aure** [comment]
aha!  Thanks Steven!
