### ISSUE TITLE
CSound for UBUNTU Studio

### ISSUE THREAD

**Issue by michaelrempel** [csound/csound#421]
I tried the instructions for compiling CSound on UBUNTU Studio 14.02.

It has an unmeetable dependency on Jack. As far as I can tell (which isnt far) it requires jack 2 because jack 1 cannot co-exist with jack2 and that version of UBUNTU has version 2.

Since that UBUNTU deployment is designed for multi-media artists it is a shame if CS6 does not port to it or compile on it.

**Comment by gogins** [comment]
Thanks for the information. I glanced at the CMakeLists.txt files. I think
if you define USE_JACK as false in the CMake configuration step, it might
be OK. Or do you really need to have Jack for Ubuntu Studio?

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by vlazzarini** [comment]
I am sure it can be built against jack 2 as well. Without more details we cannot help.

Victor Lazzarini
Dean of Arts, Celtic Studies, and Philosophy
Maynooth University
Ireland

**Comment by fsateler** [comment]
If I'm guessing correctly, you have problems with the `apt-get build-dep csound` step ? If so, try installing libjack-jackd2-dev before running build-dep again.

**Comment by michaelrempel** [comment]
Yup that is it. Thanks very much.

**Comment by michaelrempel** [comment]
Not sure Mike, I have little experience with Ubuntu. Jack is probably a bit
of a ways down the pipe for me to play with but I wanted to do the compile
with it in.

 

Felipe Sateler sent me the note below which worked. It seems to me that you
could automate this variant. I have always encouraged automation as much as
possible so that intrepid hackers have a simple base line to jump off from.
A numbered list of options for cross-compiling against all supported devices
would be asking a bit, but perhaps not a lot from the team. The script could
be part of the build to keep it synced for releases.

 

If I'm guessing correctly, you have problems with the apt-get build-dep
csound step ? If so, try installing libjack-jackd2-dev before running
build-dep again.

**Comment by kunstmusik** [comment]
This looks like it was resolved. Closing this issue.
