### ISSUE TITLE
Environment variables for Csound in OS X Yosemite

### ISSUE THREAD

**Issue by sr-murthy** [csound/csound#422]
Hi

I've recently installed Csound 6.04 on a Mac running OS X Yosemite 10.10.1.

I do have the manual, but am completely new to Csound.  Trying to play the file `oscil.csd` I had the following error message:

    virtual_keyboard real time MIDI plugin for Csound
    Error: define environment variable RAWWAVE_PATH
    (points to rawwaves directory) to use STK opcodes.
    0dBFS level = 32768.0
    Csound version 6.04 (double samples) Dec  7 2014
    libsndfile-1.0.25
    WARNING: could not open library '/Library/Frameworks/CsoundLib64.framework/Versions/6.0/Resources/Opcodes64/libjacko.dylib' (-1)
    WARNING: could not open library '/Library/Frameworks/CsoundLib64.framework/Versions/6.0/Resources/Opcodes64/libjackTransport.dylib' (-1)
    WARNING: could not open library '/Library/Frameworks/CsoundLib64.framework/Versions/6.0/Resources/Opcodes64/librtjack.dylib' (-1)
    UnifiedCSD:  oscil.csd
    Failed to open csd file: No such file or directory
    Reading CSD failed ... stopping
    end of score.		   overall amps:      0.0
	   overall samples out of range:        0
    1 errors in performance
    Elapsed time at end of performance: real: 0.002s, CPU: 0.001s

If I specify the full path `/Library/Frameworks/CsoundLib64.framework/Versions/6.0/Resources/Manual/examples/oscil.csd` then the sound is played, but this error above still appears in the terminal output.

Would appreciate a simple explanation of which environment variables have to set for what resources, in my case.

Thanks

**Comment by vlazzarini** [comment]
This is not a Csound bug. It is also not a Csound error, but a STK one, and it will not affect you because you are not using the STK opcodes. If you set the RAWWAVE_PATH environment variable, the message will disappear.
Please refer any further questions to the csound e-mail list.
