### ISSUE TITLE
Is hrtfer working as expected?

### ISSUE THREAD

**Issue by aure** [csound/csound#423]
The example provided for hrtfer is highly distorted and even when I replace beats.wav with an oscil I am getting a mangled sound.   The example multiplies the output by 200 for some reason, which makes me think that the output of hrtfer is orders of magnitude too small which might be a clue that something strange is going on.  Looks like it would be a great opcode if it works though.  Thanks.

**Comment by vlazzarini** [comment]
Something wrong alright. But note that hrtfer has been superseded by hrtfmove & friends which is much better.

**Comment by aure** [comment]
Since I opened this and I agree that the hrtfermove and friends are better and the correct choice, I will close this.  I'll make a note to update the manual for hrtfer with links to the newer opcodes.
