### ISSUE TITLE
hrtfmove2 opcode

### ISSUE THREAD

**Issue by aure** [csound/csound#424]
How certain are we that hrtfmove2 is working correctly?  The reason I ask is that if you listen to the example CSD file from the manual, while there there is a panning effect, the sound source also sounds like it is being sent through a tremolo volume gate.   Changing the elevation parameter from zero in the example doesn't seem to  give me the sense of the sound source being elevated either, and yes, I am wearing headphones.

**Comment by vlazzarini** [comment]
From the author:
"Hi Victor, 

it works ok here on 
Csound version 6.03.2 (double samples) May 12 2014

It is quite a swift movement so maybe recommend slowing it down a little and highlight that elevation perception is secondary and individualised. "

**Comment by aure** [comment]
I didn't want to push this at the time, but I don't think this issue should have been closed based on his response.  It seems like he ran the example to make sure it makes a sound and that's all. He claims that it is "quite a swift movement" but is it really?  Two full rotations over 10 seconds is fast?  If he had taken two second to slow it down to one full rotation (360) or half a rotation (180) he would have heard that it is still doing a bizarre tremolo.

 If you replace the outs line with:

outs gasrc, gasrc

You will hear the arpeggio how it sounds normally.  No tremolo.  Why would moving the sound source create such a strong tremolo effect?  Can we please reopen this issue?

**Comment by vlazzarini** [comment]
I asked for advice from the author.

**Comment by aure** [comment]
Thanks!

**Comment by briancarty** [comment]
Hi Guys, 

there are some natural volume changes due to Interaural Intensity Differences inherent to the HRTFs (which will be more pronounced with swifter movements) but nothing that I would describe as a strong tremolo effect.

I'll mail you the file I get when I run the example Aure.

**Comment by aure** [comment]
Indeed the wav file that Brian sent me sounds good, but I do not know what the specifics of the implementation used to create that file were. What csound version and what OS are you on?  I am on OSX Yosemite: Csound version 6.04 (double samples) Dec  1 2014  and I sent you the tremolo sounding wav file

**Comment by aure** [comment]
Anyone else want to test this opcode with the example csd and see if they hear a tremolo sound or not?

**Comment by briancarty** [comment]
I have upgraded to Yosemite (10.10.3) and Csound version 6.04 (double samples) Dec  7 2014 since my previous comment in Feb. 
I have used the opcode successfully on various systems since Csound 5. 

I have emailed a suggestion, hopefully it helps to get to the the bottom of the issue!

**Comment by aure** [comment]
Brian discovered the issue!   My .dat files were out of date.  The problem is that are named exactly the same as the new files.  That is unfortunate.  I will edit the manual to provide a warning that the correct files are needed and provide a direct link to ones that work.  Thanks Brian!
