### ISSUE TITLE
schedkwhen crashes CsoundQt in Windows 8.1

### ISSUE THREAD

**Issue by midiguru** [csound/csound#425]
Consistent crash. Csound 6.04, CsoundQt 0.90. .csd file below (slightly modified from the Python article in Csound Journal #6; the long rows of semicolons mark the crucial section of code). This seems to be restricted to Windows 8.1 (64-bit) -- in Windows 7 (also 64-bit), the .csd plays normally with the same versions of Csound and CsoundQt.

```
<CsoundSynthesizer>
<CsInstruments>

sr=44100
ksmps=128
nchnls=2

pyinit

pyruni {{c = [0.1, 0.2, 0.05, 0.4, 0.25]
d = [0.4, 0.1, 0.1, 0.2, 0.2]
e = [0.2, 0.35, 0.05, 0.4, 0]
g = [0.7, 0.1, 0.2, 0, 0]
a = [0.1, 0.2, 0.05, 0.4, 0.25]

markov = [c, d, e, g, a]

import random

random.seed()

def get_new_note(previous_note):
    number = random.random()
    accum = 0
    i = 0
    while accum < number:
        accum = accum + markov[int(previous_note)] [int(i)]
        i = i + 1 
    return i - 1.0

}}

instr 1
ioct init p5
ilen = 1 / (ioct - 4)
klastnote init 0
ktrig metro p4
knewnote pycall1t ktrig, "get_new_note", klastnote

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; the schedkwhen line crashes Csound in Windows 8.1, but not in Windows 7:
schedkwhen ktrig, 0, 10, 2, 0, ilen, knewnote, ioct, p6

; using event for the same purpose works in Windows 8.1:

;if (ktrig == 1) then
;	event "i", 2, 0, ilen, knewnote, ioct, p6
;endif
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

klastnote = knewnote
endin


instr 2

ioct init p5

ipclass table p4, 2
ipclass = ioct + (ipclass / 100)
ifreq = cpspch(ipclass)
aenv linen 6000, 0.05, p3, 0.1
aout oscil  aenv, ifreq , 1
aL, aR	pan2	aout, p6
outs aL, aR
endin


</CsInstruments>
<CsScore>

f 1 0 2048 10 1 ;sine wave
f 2 0 8  -2  0  2  4  7 9  ;Pitch classes for pentatonic scale

;        frequency of       Octave of
;        note generation    melody		panning
i 1 0 30      3               8			0.5  
i 1 5 25      6               9			0.1
i 1 10 20     7.5             10		0.9
i 1 15 15     2.5               11		0.5

</CsScore>
</CsoundSynthesizer>
```

**Comment by vlazzarini** [comment]
Tested on OSX 10, no crashes here. I wonder if this is a Python problem masked as a schedkwhen issue. I am saying this for two reasons:
1) knewnote is generated from Python code. 
2) I am getting these messages 
pycall1t: python exception
with no crashes or anything, but it means the Python code is having issues. I wonder if a bad
value (say a NaN) is causing schedkwhen to go wrong.

**Comment by jpffitch** [comment]
Does this fail in csound without ccsoundQt?

**Comment by vlazzarini** [comment]
I went back to this and tested it again. I think I had a formatting error in the python, so that is why I had the errors. It runs perfectly on OSX. Not sure how to proceed with this. We need a Windows 8.1 user or developer involved.

**Comment by midiguru** [comment]
On 4/2/2015 2:04 AM, vlazzarini wrote:
>
> I went back to this and tested it again. I think I had a formatting 
> error in the python, so that is why I had the errors. It runs 
> perfectly on OSX. Not sure how to proceed with this. We need a Windows 
> 8.1 user or developer involved.
>

I believe I was the person who reported this. (It was a couple of months 
ago.) I have Windows 8.1 on my laptop. I can test a new version if you 
have one ... but I'm not able to build from source. (Not without 
extensive hand-holding, anyway. I'd like to learn to do it, but I'm not 
sure you want to commit a couple of hours to helping me learn.)

--Jim Aikin

**Comment by vlazzarini** [comment]
I am not sure about the state of toolsets for windows, so I am not the best person to help you. Also I think we might need a developer in case there is debugging needed (there probably is).

**Comment by kunstmusik** [comment]
@midiguru Could you double-check that the version of python you installed on your Windows 8.1 machine is a 32-bit (i386) version of Python?  Also, can you try eliminating the python code altogether so we can eliminate that as a variable? (or help determine if it is python)?

**Comment by midiguru** [comment]
On 4/3/2015 10:34 AM, Steven Yi wrote:
>
> @midiguru <https://github.com/midiguru> Could you double-check that 
> the version of python you installed on your Windows 8.1 machine is a 
> 32-bit (i386) version of Python? Also, can you try eliminating the 
> python code altogether so we can eliminate that as a variable? (or 
> help determine if it is python)?
>

Yes, the Python is definitely 32-bit, if Idle is to be believed. 
(Version 2.7.9)

If I eliminate the Python code and just test schedkwhen by itself, it 
works fine. So the problem would seem possibly to be somewhere in the 
Python implementation.

--Jim Aikin

**Comment by vlazzarini** [comment]
Ok, we're getting closer now. Could you print the value of knewnote? That seems to be the result of
the python code that gets passed to schedkwhen. 

As I understand it,  "event" in place of schedkwhen works, so we need to find out what is throwing schedkwhen off.

**Comment by midiguru** [comment]
On 4/4/2015 3:50 PM, vlazzarini wrote:
>
> Ok, we're getting closer now. Could you print the value of knewnote? 
> That seems to be the result of
> the python code that gets passed to schedkwhen.
>
> As I understand it, "event" in place of schedkwhen works, so we need 
> to find out what is throwing schedkwhen off.
>

Today, my python_markov.csd works without errors in Windows 8.1. This is 
the same file I uploaded to the list on Feb. 6.

I have no explanation, as I don't think my system has changed. I tried 
it again after commenting out my new printk2 line, just on the 
off-chance that using that line was fixing the problem -- but no, it 
works fine without that line as well.

Intermittent problems ... gotta love 'em.

--JA

**Comment by vlazzarini** [comment]
Ok, so I will close this for the moment. If it pops up again, we can look at it.

**Comment by AndreaCrespi** [comment]
Hello. Just to let you know, I am also having crash issues when running a csd containing schedkwhen in CsoundQt 0.8.2 on Windows 8.1 (64 bit). No python involved:

```
<CsoundSynthesizer>

<CsOptions>
</CsOptions>

<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs = 1

instr 1
  ktrig metro 1
  schedkwhen ktrig, 0, 4, 2, 0, 3
endin

instr 2
  ifreq random 220, 880
  asig vco2 .8, ifreq  
  outs asig, asig
endin

</CsInstruments>

<CsScore>
i 1 0 10
e

</CsScore>

</CsoundSynthesizer>

```


PS: I know there is a newer version of CsoundQt (maybe this bug was solved) but I am not able to find a pre-built binary. From the Csound download page (http://csound.github.io/download.html) I only get a .apk file, which I am not sure how to use. I think many newbies like me might be confused about this, as it is kind of unusual in a Windows scenario.

**Comment by rorywalsh** [comment]
Whoops, that download link is wrong. I've updated it. Can you hit refresh
on the download page and try again? The current version of Csound is if
6.07b.

**Comment by vlazzarini** [comment]
No crashes on OSX. Have you tried "Run in Term"?

**Comment by AndreaCrespi** [comment]
@rorywalsh Yes, I get a .exe now, thanks a lot.
@vlazzarini  Sorry, I always forget to try and run in terminal: when running in terminal it works fine indeed.
