### ISSUE TITLE
McCurdy FLTK examples are crashing Csound

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#428]
Csound is crashing using Iain McCurdy's FLTK examples.  Posted on the mailing list by a user on Linux, also crashing here on OSX 10.10.  Examples tried are wgbrass.csd (crashes but csound still alive, ctrl-c does not kill, requires "kill -9") and wgclar.csd (crashes but exits csound).

**Comment by jpffitch** [comment]
Works for me.  Need more imformation as to what you change on the sliders

**Comment by kunstmusik** [comment]
It crashes for me right when I press the on/off button.  I did not change
any slider values.

**Comment by jpffitch** [comment]
Revision: wgbrass works but wgclar freezes without updating ftlk windows

**Comment by jpffitch** [comment]
and more; removing all the MIDI stuff makes wgclar run mostly OK
Some sliders seem unconnected anf base freq was very odd

**Comment by jpffitch** [comment]
Looking at wgclar example; the hang is.....
(gdb) where
#0  0x00007ffff7712a9d in read () from /lib64/libpthread.so.0
#1  0x00007fffe76778d7 in ?? () from /usr/lib64/libfltk.so.1.3
#2  0x00007fffe767b8c3 in fl_wait(double) () from /usr/lib64/libfltk.so.1.3
#3  0x00007fffe7626461 in Fl::wait(double) () from /usr/lib64/libfltk.so.1.3
#4  0x00007fffe7d766f4 in Fl_wait (csound=0x6044a0, seconds=0)
    at /home/jpff/Sourceforge/csound/New/csound6/InOut/./winFLTK.h:93
#5  0x00007fffe7d7698f in ReadMidiWindow (csound=0x6044a0, keyWin=0x7959f0, 
    mbuf=0x6f9d34 "", nbytes=4096)
    at /home/jpff/Sourceforge/csound/New/csound6/InOut/virtual_keyboard/virtual_keyboard.cpp:101
#6  0x00007fffe7d77561 in ReadMidiData_ (csound=0x6044a0, userData=0x7959f0, 
    mbuf=0x6f9d34 "", nbytes=4096)
    at /home/jpff/Sourceforge/csound/New/csound6/InOut/virtual_keyboard/virtual_keyboard.cpp:359
#7  0x00007ffff798fa68 in sensMidi (csound=csound@entry=0x6044a0)
    at /home/jpff/Sourceforge/csound/New/csound6/InOut/midirecv.c:490
#8  0x00007ffff797c25a in sensevents (csound=csound@entry=0x6044a0)
    at /home/jpff/Sourceforge/csound/New/csound6/Engine/musmon.c:1102
#9  0x00007ffff7a84b4e in csoundPerform (csound=csound@entry=0x6044a0)
    at /home/jpff/Sourceforge/csound/New/csound6/Top/csound.c:2019
#10 0x000000000040158c in main (argc=<optimized out>, argv=0x7fffffffdf98)
    at /home/jpff/Sourceforge/csound/New/csound6/frontends/csound/csound_main.c:318

so lookslike aMIDI/Virtual keyboard issue

**Comment by jpffitch** [comment]
or a fltk/threading issue

**Comment by vlazzarini** [comment]
More like a threading issue. The crash is inside FLTK is it not? So isn't this a FLTK bug?

**Comment by gogins** [comment]
Not necessarily, Csound may possibly be setting up FLTK with an
inappropriate threading model.

If I had the time, I would replace FLTK with Qt for the "FLTK" widgets. But
I don't have the time.

Regards,
Mikd


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by vlazzarini** [comment]
do we have a CSD?

**Comment by jpffitch** [comment]
Yes; the Mccurdy examples PhysicalModels/wgclar.csd and wgbrass.csd

**Comment by vlazzarini** [comment]
yes, but where can I get these?

**Comment by kunstmusik** [comment]
This is no longer crashing for me.  I had done a separate bug fix in commit https://github.com/csound/csound/commit/072b944e44a732663e5ac19df61871d356bb466f that I think  fixed this issue with crashing.  

So it looks like this is now a linux-only issue?

**Comment by jpffitch** [comment]
More information.  I added some tracinf in Fl_wait and gotK but in different place. That suggests a memory problem or threading

(gdb) where
#0  0x00007ffff77127bc in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007ffff770e489 in _L_lock_909 () from /lib64/libpthread.so.0
#2  0x00007ffff770e2b0 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x00007fffe724673d in ?? () from /usr/lib64/libfltk.so.1.3
#4  0x00007fffe724699a in Fl::lock() () from /usr/lib64/libfltk.so.1.3
#5  0x00007fffe79456a3 in Fl_lock (csound=0x6044a0)
    at /home/jpff/Sourceforge/csound/New/csound6/InOut/./winFLTK.h:63
#6  0x00007fffe79459e2 in ReadMidiWindow (csound=0x6044a0, keyWin=0x79da00, 
    mbuf=0x6fa694 "", nbytes=4096)
    at /home/jpff/Sourceforge/csound/New/csound6/InOut/virtual_keyboard/virtual_keyboard.cpp:99

**Comment by vlazzarini** [comment]
wasn't there a switch to run FLTK in a separate thread, or is that gone now? I seem to remember something like that.

**Comment by kunstmusik** [comment]
It used to be we required FLTK be built with --enable-threads.  I also
don't know what the situation is now. To note, on OSX, the dependencies
script does *not* use --enable-threads when building FLTK. Maybe that's the
source of differences, if FLTK is built with threads on Linux?

**Comment by jpffitch** [comment]
The macro NO_FLTK_THREADS is not set on linux; is it on OSX and Windows?

**Comment by jpffitch** [comment]
Building linux cs with -DNO_FLTK_THREADS makes it run OK.  What are the down-sides?

**Comment by vlazzarini** [comment]
Maybe that is the difference, it could be that libfltk is build with --enable-threads in Linux.

**Comment by jpffitch** [comment]
So we could build csoud with -DNO_FLTK_THREADS  on all platforms; but I repeat, what is the down-side of that?

Also does it work on Windows?

**Comment by vlazzarini** [comment]
I think we should leave OSX & Windows as before, whichever way it was.

**Comment by kunstmusik** [comment]
@gogins Michael could you comment on Windows and FLTK?

**Comment by gogins** [comment]
I will check this when I get a chance.

Best,
Mike

**Comment by jpffitch** [comment]
I have committed what seems like a Linux fix

**Comment by vlazzarini** [comment]
I am closing this now, as it looks fixed.
