### ISSUE TITLE
macro expansion

### ISSUE THREAD

**Issue by cvrn** [csound/csound#429]
Hi,

I tested this under Linux (Ubuntu 14.04 LTS) and WIN7
(64-Bit, 8 GB RAM), Csound 6.04
The soundfile is a monofile (44.1 kHz) named test_1.wav

Under Linux it runs fine.
Under WIN7 it produces this error message:

INIT ERROR in instr 2: diskin2: 1READING__INFILE1.1READING__HEADER_INFILE: failed to open file
aSig diskin2 "1READING__INFILE1.1READING__HEADER_INFILE" 1 0 0 0 0 0 0 0
B 2.000 - note deleted. i2 had 1 init errors

```
<CsoundSynthesizer>
<CsInstruments>
sr		= 44100
ksmps	= 64
nchnls = 1
0dbfs = 1

;SOUNDFILE READ-IN SETTINGS
#define INFILE #test_#			
#define HEADER_INFILE #wav#	

#define FILE #test_1.wav#		

instr 1
#define	#READING#							
aSig   diskin2	"$FILE", 1
	   out aSig
#

$READING					
endin

instr 2
#define	#READING(T)#							
aSig   diskin2	"$INFILE$T..$HEADER_INFILE", 1
	   out aSig
#

$READING(1)					
endin

</CsInstruments>
<CsScore>
i1 0 2
i2 2 2
</CsScore>
</CsoundSynthesizer>
```

**Comment by jpffitch** [comment]
Looks like te fixed bug relating to macros.  Does it run on develop brach in windows?

**Comment by kunstmusik** [comment]
@gogins Could you may try this on Windows to see if it is still a bug?  I'm not sure OP is building csound themself.

**Comment by gogins** [comment]
I will try this and let you know.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by kunstmusik** [comment]
I just built on Windows 2012 and the example ran here, properly replacing macros. I think this will be okay for 6.05.0.
