### ISSUE TITLE
Problem with MIDI controller

### ISSUE THREAD

**Issue by zdenekdvoracek** [csound/csound#430]
Hi,

I´m working on midi controller. But I´m beginner and I work on it according tutorials. I found this on page 364, 365 http://en.flossmanuals.net/csound/_booki/csound/csound.pdf 
But Arduino software found a few problems. ![arduino problem](https://cloud.githubusercontent.com/assets/11014674/6202762/c3fd6fce-b4fb-11e4-9db2-4256776833c8.jpg)

Thanks for your help,

Zdeněk

**Comment by vlazzarini** [comment]
I do not think this is a bug report, but a user question, please use the csound users list to ask these questions. If it is a bug, you can open another issue, but we will need mire details of the bug and how we can reproduce it.
