### ISSUE TITLE
score macros lacks features of orchestra macros

### ISSUE THREAD

**Issue by DaveSeidel** [csound/csound#434]
For example, score macros lack #ifdef/#indef/#endif. Is there any good reason why score macros can't have all the capabilities of orchestra macros?

**Comment by jpffitch** [comment]
On Tue, 10 Mar 2015, Dave Seidel wrote:

> 
> For example, score macros lack #ifdef/#indef/#endif. Is there any good reason
> why score macros can't have all the capabilities of orchestra macros?
>

Time.  Actually harder than it sounds.  If I ever get the newsciore parser 
wiorking they will be the same
==John

**Comment by jpffitch** [comment]
If compiled with SCORE_PARSER true then you will get these and also bug fixes. I have been running thus for some time and seems OK.  Would appreciate more testing though
