### ISSUE TITLE
array init leads to memory allocation failure 

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#436]
this statement in instr0 leads to "memory allocate failure for 4294967256":
gkArr[] init 5, -1

it is obviously because of the negative default value; this works:
gkArrArr[] init 5, 1

(csound from today's git, ubuntu studio 12.04)

**Comment by kunstmusik** [comment]
I can confirm the error. I've got a fix and will push it shortly. Thanks!

**Comment by joachimheintz** [comment]
i can confirm that the memory allocation failure has been fixed.

but i am still confused, because i expected another behaviour.

the manual states for *init*:
tab init isize[, ival]
"The t-variable form was introduced in 5.14 and allocated space for a 
vector or the given size, initialised to the given value (default value 
is zero)."

so, for
gkArr[] init 5, 1
i expected to get [1, 1, 1, 1, 1]
but i get [0, 0, 0, 0, 0]

and for
gkArr[] init 5, -1
i expected to get [-1, -1, -1, -1, -1]
but i get the error message:
"Error: sizes must be > 0 for array initialization"

and this message i actually do not understand at all:
i thought i declared a one-dim array by "gkArr[]" (one bracket).
why is the second argument for init interpreted as size, instead of 
default value?



Am 11.03.2015 um 19:34 schrieb Steven Yi:

**Comment by kunstmusik** [comment]
I think the design changed when arrays were added as array can have
multiple dimensions.  So the expectation with the init is:

gkArr[][] init 5, 1

which in C-like languages would be equivalent to:

int gkArray[5][1]

However, we could modify init to check the number of dimensions on the
left-hand side, and allow up to one additional value for init value.  There
is a caveat though, in that I'm not sure how this will interact with arrays
of other types:

adefault init 0
gaSignals[] init 2, adefault

default:MyCustomType init 45, "SomeString", gkval
myArray:MyCustomType[] init 5, default

I guess it will work out alright, if type checks are used for the input
arguments.

I'll close this issue now as the original task is done. If you'd like the
init behavior, please file a new issue and you can add a mention to this
issue number.
