### ISSUE TITLE
csound6.04-OSX-universal installation cannot open libraries in Opcodes64

### ISSUE THREAD

**Issue by evanlooij** [csound/csound#437]
I have used the csound6.04-OSX-universal.dmg installer to install csound. Running csound from the Terminal appears to work fine, but for the warning that libjacko.dylib, libjackTransport.dylib and librtjack.dylib cannot be opened. 

The complete message is:
csound HelloWorld.csd 
virtual_keyboard real time MIDI plugin for Csound
Error: define environment variable RAWWAVE_PATH
(points to rawwaves directory) to use STK opcodes.
0dBFS level = 32768.0
Csound version 6.04 (double samples) Dec  7 2014
libsndfile-1.0.25
WARNING: could not open library '/Library/Frameworks/CsoundLib64.framework/Versions/6.0/Resources/Opcodes64/libjacko.dylib' (-1)
WARNING: could not open library '/Library/Frameworks/CsoundLib64.framework/Versions/6.0/Resources/Opcodes64/libjackTransport.dylib' (-1)
WARNING: could not open library '/Library/Frameworks/CsoundLib64.framework/Versions/6.0/Resources/Opcodes64/librtjack.dylib' (-1)
UnifiedCSD:  /Users/elisevanlooij/Documents/Project_Plug-ins/Csound files/HelloWorld.csd
STARTING FILE
Creating options
Creating orchestra
Creating score
Error: define environment variable RAWWAVE_PATH
(points to rawwaves directory) to use STK opcodes.
rtaudio: PortAudio module enabled ... 
using callback interface
rtmidi: PortMIDI module enabled
Elapsed time at end of orchestra compile: real: 0.002s, CPU: 0.002s
sorting score ...
	... done
Elapsed time at end of score sort: real: 0.002s, CPU: 0.002s
--Csound version 6.04 (double samples) Dec  7 2014
graphics suppressed, ascii substituted
0dBFS level = 1.0
orch now loaded
audio buffered in 1024 sample-frame blocks
PortAudio V19-devel (built Sep  4 2014 22:30:30)
   0: dac0 (Built-in Output)
   1: dac1 (EPSON Projector UD Audio)
PortAudio: selected output device 'Built-in Output'
writing 2048 sample blks of 64-bit floats to dac 
SECTION 1:
new alloc for instr 1:
B  0.000 ..  1.000 T  0.998 TT  0.998 M:  0.25000  0.00000
Score finished in csoundPerform().
inactive allocs returned to freespace
end of score.		   overall amps:  0.25000  0.00000
	   overall samples out of range:        0        0
0 errors in performance
Elapsed time at end of performance: real: 1.069s, CPU: 0.024s
closing device
43 2048 sample blks of 64-bit floats written to dac

**Comment by vlazzarini** [comment]
These are just warnings because you do not have JackOSX installed

Victor Lazzarini
Dean of Arts, Celtic Studies, and Philosophy
Maynooth University
Ireland
