### ISSUE TITLE
3d array bug

### ISSUE THREAD

**Issue by vncntmchlk** [csound/csound#439]
The following Instrument prints out 1 2 3 4 3 4 5 6 instead of 1-8. (csound 6.04 on windows 7)

instr 1
karr[][][] init 2,2,2
karr fillarray 1,2,3,4,5,6,7,8
printk 0,karr[0][0][0]
printk 0,karr[0][0][1]
printk 0,karr[0][1][0]
printk 0,karr[0][1][1]
printk 0,karr[1][0][0]
printk 0,karr[1][0][1]
printk 0,karr[1][1][0]
printk 0,karr[1][1][1]
turnoff
endin

**Comment by kunstmusik** [comment]
I'm not sure fillarray was designed to work with multi-dimensional arrays.
I think we may need to clear up the rules for working with multiple
dimensions as a whole.

**Comment by vlazzarini** [comment]
should we limit fillarray to one dim?

**Comment by vlazzarini** [comment]
Ok, since multidimensional arrays are not defined for fillarray, I have restricted it to 1-d, for the moment.

**Comment by joachimheintz** [comment]
i think this is not a lucky solution.

using fillarray for two dimensions started from a question on the list. 
  john ffitch replied that it could work with fillarray, like:

iArr[][] init   2,3
iArr     array  1,2,3,7,6,5

this worked indeed, so i included the feature in my chapter in the 
csound floss manual (http://en.flossmanuals.net/csound/arrays/ — see 
example 03E07).

if we limit now fillarray to one dimension, we would break existing csd 
files, and get less than we have now.

instead, i suggest:
- let us keep the current state.
- let us explain in the fillarray manual page that fillarray is not 
supposed to work for more than one dimensions.  it will probably work 
for two dimensions, but not for more than two dimensions.
- i will change the flossmanuals explication to be in consensus with it.


Am 02.04.2015 um 00:18 schrieb vlazzarini:

**Comment by vlazzarini** [comment]
limited to <= 2 dim now.
