### ISSUE TITLE
Reinitializing OSCsend crashes CsoundQT on exit

### ISSUE THREAD

**Issue by rpinkston** [csound/csound#440]
There seems to be a problem with reinitializing OSCsend. Since the IP address and Port arguments are i-time variables, the only way to change where you are sending something is to reinitialize OSCsend. This seems to work fine, as long as the orchestra is running in CsoundQT. Messages get send to the correct IP and port. However, if you stop the orchestra, it crashes CsoundQT. I have tested this on a Mac with both Csound5.19 (CsoundQT 0.7) and Csound6.04 (CsoundQT 0.9). If I don't reinitialize OSCsend, but just hardwire the IP and port, then it doesn't crash CsoundQT on stopping the program, so it's clearly the re-initialization that causes the problem.

**Comment by vlazzarini** [comment]
I checked and you do not need to reinit OSCsend. The manual is probably out of date as the opcode allows you to change the port and address during performance (iport is kport, and the address is a string
that can be modified).
I will check why the reinit is causing a crash.

**Comment by vlazzarini** [comment]
Fixed the deinit crash in git.
