### ISSUE TITLE
built-in example

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#442]
it would be good to have a built-in example which can be run out of the box, after having installed the csound android apk.

**Comment by gogins** [comment]
I will try to create one or more example pieces, visible in the app menu, built into the app as string resources. When selected, the menu item will save the string resource as a csd file, obtain the complete path to the csd file, and open the csd so that it can be viewed, edited, or performed.

**Comment by gogins** [comment]
This is finished. I built a number of examples into the Csound6.apk as files in the assets directory, and added their titles and composers to the menu of the app. When an example is selected, its file or files are copied from the assets of the app into the external file storage area of the app, and loaded into the app for performance or editing. The user guide has been modified to document this.

**Comment by joachimheintz** [comment]
this is great, mike - thanks for it!

Am 09.04.2015 um 14:42 schrieb gogins:
