### ISSUE TITLE
Channels and CS_VAR_MEM

### ISSUE THREAD

**Issue by mantaraya36** [csound/csound#444]
It would be ideal to have channels use CS_VAR_MEM instead of passing string pointers via STRINGDAT. This would allow API hosts to be able to resize data as needed (or eventually interpret user defined types).

From Steven's original email:
I double checked, as I thought I might have modified the channels
system to use CS_VAR_MEM, so that you can access the type pointer.
However, that's not the case unfortunately.

Andres: could you file an issue and assign it to me for reworking the
channel db for CS_VAR_MEM?  We also may want to modify the system to
use CS_TYPE's when creating channels, rather than have a separate set
of type information like we do now.

For things like STRINGDAT, I think we need to have that be public.
It's sort of a primitive data type and there's not much one can do for
introspection.  For CS7 structs, the data type for that should also be
exposed.  For structs, one can use the CS_TYPE, which has information
about the fields of the structure, to interrogate values in a struct
variable.

**Comment by kunstmusik** [comment]
From discussion on IRC, this issue could be addressed in CS6, with the exception of aggregate data structures (i.e., user-defined types, see #408). 

The current design is to create new API functions for getting channel variables as CS_VAR_MEM.  Additional functions will be added for primitive data types, such as:

* csoundVarGetMYFLT()
* csoundVarSetMYFLT()
* csoundVarGetString()
* csoundVarSetString()
* csoundVarSetArrayMYFLT(indx, MYFLT)
* csoundVarGetArrayString(indx, char*)

We would need a set of accessors that match each type we want to expose.  This should prevent internal details, such as STRINGDAT, from being exposed to hosts.  Additional functions for aggregate data should be added for Csound 7.

**Comment by kunstmusik** [comment]
(Moved to 6.x as I'm unable to have this ready in time for 6.08)

**Comment by kunstmusik** [comment]
Moving this to milestone 7.0.0 as I think we should finally get the channels reworked for initial CS7 release.

**Comment by vlazzarini** [comment]
closing this as duplicate to #318
