### ISSUE TITLE
STRINGDAT made public

### ISSUE THREAD

**Issue by mantaraya36** [csound/csound#445]
Should STRINGDAT struct and related functions be made public for API users? This would be useful in the context of data channel handling (and general string processing) in the host.

(Or should STRINGDAT be completely deprecated and everything moved to the new type system?)

**Comment by kunstmusik** [comment]
With the design of CS_TYPE today, I think STRINGDAT should be made public.
It's somewhat of a primitive type to Csound and the only way to interrogate
it's value would be to know it's structure. This would also go for PVSDAT
and SPECDAT.  Also, we may want to look at creating typedefs for all of the
primitive types, something like:

typedef MYFLT CS_I_TYPE
typedef MYFLT CS_K_TYPE
typedef MYFLT* CS_A_TYPE

The new type system wouldn't really help in the situation of primitive
types.  If you get a data pointer and CS_TYPE, the CS_TYPE can't tell you
enough about the data pointer without having something to refer to (the
primitives).  However, for  structures and arrays, the information in
CS_TYPE would be enough to understand how to get the data out of the data
pointer, assuming one has access to all of the primitive types.

The only situation where we may have a problem is if a user creates their
own opcode library that uses its own C-defined CS_TYPE and data structure.
The host application would have to know somehow what that data structure
is. I guess we'd have to weigh how likely that might even happen.

An alternative would be to further change CS_TYPE and CS_VARIABLE to add
information. CS_TYPE could then have function pointers like getValue() and
getFields().  If getValue(), returns a data pointer.  If getFields(),
returns a list of field descriptors. We might then have something like
CS_FIELD, which would have properties like field name, field size,
dimensions, fieldType, getValue(), and other things. It would add more
necessary properties to CS_TYPE, but would offer the tools necessary for
full host introspection into any variable.

My own preference right now is that we expose the primitive data types, and
encourage using structures in Csound 7.  From there, we could spend time
trying to optimize efficiency of structures use.  Ideally, it would be
possible for users to express whatever they want in Csound ORC code alone,
using structures and UDO's.  That way, the only reason a user would use C
code is for performance.

I'm not really sure I have a complete understanding of all the uses of this
yet, so perhaps we'll need to augment CS_TYPE in the end.  Hopefully at
least the above adds some notes about this topic.

**Comment by kunstmusik** [comment]
Closing out this ticket.  This modifications to the API will be worked in #444 , which will be split between csound6 and csound7.
