### ISSUE TITLE
rtjack.c segfaults when used by csoundqt

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#450]
the last changes to InOut/rtjack.c lead to a segfault when jack is used on linux (ubuntu studio 12.04) by csoundqt.

in other words: running a csd which uses jack from the terminal works, but running the same csd from inside csoundqt (even if it does not use sound at all) segfaults. (when using csoundqt's "run in terminal" option, the message is: "csound command: segmentation fault".)

i went back in git. when i go back to victor's commit march 27, csound is not segfaulting any more, but the jack module is not recognized any more:
git checkout ffd87c7fc9ca8a9e0c1ffcbee3d008637bb13a4f InOut/rtjack.c
-> unknown rtaudio module: 'jack', using dummy module

going back to the commit before (03403ba3137eb305b9b628e34ea2688384f92b03) solves the problem.

is looks like one of these commit has introduced the issue (= API issue?):

commit d447a1333a7913f4b0cb74fbf1f01400cc424756
Author: jpff <jpff@codemist.co.uk>
Date:   Wed Apr 1 10:52:46 2015 +0100

    strings, tabs

commit e444f72babc2aabb0b7ff45cda977cb7795a04c0
Author: jlucas <jlucas@ash.106.net>
Date:   Sun Mar 29 04:46:10 2015 -0400

    Fix undefined symbol on Linux

commit ffd87c7fc9ca8a9e0c1ffcbee3d008637bb13a4f
Author: veplaini <victor.lazzarini@nuim.ie>
Date:   Fri Mar 27 14:37:01 2015 +0000

    dealt with issue 390 by giving jack input a timeout

**Comment by vlazzarini** [comment]
maybe the fix for linux was wrong. I will check, as it works on OSX

**Comment by vlazzarini** [comment]
yes, as expected, that fix was not right. I think it is OK now.

**Comment by joachimheintz** [comment]
yes, works now.  thanks for the quick fix.

**Comment by joachimheintz** [comment]
unfortunately, the fix seems to be not correct.  for checking, you can run for instance the manual example soundin.csd from inside csoundqt, using jack.  i get a distorted signal, the time proceeds much too fast.  when i checkout the old version (03403ba3137eb305b9b628e34ea2688384f92b03), it works ok.
as before, this does not happen when runnding the .csd from the terminal.  but nevertheless it is no csoundqt issue, i think.

**Comment by vlazzarini** [comment]
can you try now?

**Comment by joachimheintz** [comment]
yes works now.
