### ISSUE TITLE
Enhance PADSynth FGEN by accepting samples and FFTs.

### ISSUE THREAD

**Issue by gogins** [csound/csound#451]
Currently the PADSynth FGEN accepts more or less harmonic partials input by the user as pfields. Users have requested the ability to supply a function table in place of the series of partials. This could contain a sound sample or the spectrum of a sound sample. This function table would have to be reduced to something more or less like partials that would be treated to the existing "bandwidth spreading" algorithm. The easiest way to do this is probably as follows. If the function table contains a sample, its FFT is taken at the size of the PADSynth spectrum. If the function table contains an FFT, its coefficients are copied to the corresponding frequencies in the PADSynth spectrum. The PADSynth spectrum would then be copied, and each nonzero sample in it would be spread using the "bandwidth spreading" algorithm. For this to work, the user would also have to enter the base frequency of the function table.

**Comment by gogins** [comment]
I'm clearly not getting around to do this...

**Comment by kunstmusik** [comment]
Closing as not going to be done.
