### ISSUE TITLE
GEN23 goes into an infinite loop on some input, reads a format other than what's documented

### ISSUE THREAD

**Issue by mskala** [csound/csound#455]
The documentation for GEN23 says:

>numeric values contained in "filename.txt" (which indicates the complete pathname of the character file to be read), can be separated by spaces, tabs, newline characters or commas. Also, words that contains [sic] non-numeric characters can be used as comments since they are ignored.

Later comments describe line-based commenting using the semicolon, hash, and less-than characters.

After reading a number, the code around line 1312 in Engine/fgens.c reads one more character and then goes into a loop looking for the next number.  If that one character is not a digit, upper or lowercase "e", plus, minus, period, whitespace, semicolon, hash mark, or less-than, then this loop _will never read another character_.  It will just keep testing the already-read character against those possibilities forever.  This can be triggered if, for instance, the sequence " , " (that is space, comma, space) is used to separate two numbers in the input.  Comma is legal as a separator, whitespace is legal as a separator, comma followed by whitespace works too, but there must not be any whitespace before the comma.  Any character not otherwise special (such as "$") works just like comma.

Even when it does not go into an infinite loop, it does not behave as documented.  Words that contain non-numeric characters are not ignored.  The non-numeric characters "e", "E", "+", "-", and "." are part of the numeric format and handled as such.  They probably should be, so that aspect is at most a documentation bug.  The characters ";" and "#" cause everything from there to the end of the line (not the "word" containing them) to be a comment; and other non-numeric characters apparently act either as word separators or trigger the infinite loop, in no case causing a word to be ignored.  The character "<" is documented as a line-comment character (WHY?), but only appears to function as such if it is preceded by whitespace, because the end-of-number check only looks for semicolon and hash.

I suggest:
* GEN23 should not infinite-loop on any input.
* At least one of the code and documentation should change so that they match each other.

I don't have strong feelings on exactly what the input format should really be except that it should be as versatile as possible.  In particular, I discovered these problems when I wanted to use input that would look like this:

     connection( 123 , 456 ). %789
     connection( 124 , 567 ). %790
     connection( 125 , 568 ). %791

That is valid EcLiPSe-CLP code that, based on the documentation for GEN23, I thought GEN23 could read also (with the last number on each line treated as a comment because _the word contains a non-numeric character_).  Based on the GEN23 documentation I thought that would be read as six values:  123, 456, 124, 567, 125, 568.  It'd be convenient for me to have the same files readable by Csound and EcLiPSe-CLP.  But in fact, this syntax causes GEN23 to go into an infinite loop, and it appears nothing similar enough to it to be valid EcLiPSe-CLP code will in fact be readable by GEN23.  I have to switch to something closer to just a file of numbers.  The specific point about reading my particular file is not so important, but at the very least, it shouldn't infinite-loop.

**Comment by vlazzarini** [comment]
looks like a bona-fide bug in the code. The documentation is less than optimal. Can you open an issue in the manual repository? Thanks

**Comment by jpffitch** [comment]
I see a bug relating to comma but cannot see the loop you describe.  The comment about other characters being ignored ir not the case and should be deleted,  but I cannot see the loop unless there is no \n terminating a comment

**Comment by mskala** [comment]
Try running GEN23 on a file that contains the sequence "123 , 456" (with a space both before and after the comma).  Csound's behaviour speaks for itself; but I think it should be visible in the code too.

Here's the code:
```
    c = getc(f);
 top:
    if (feof(f)) return NAN; /* Hope value is ignored */
    if (isdigit(c) || c=='e' || c=='E' || c=='+' || c=='-' || c=='.') {
      double d;                           /* A number starts */
      char buff[128];
      int j = 0;
      do {                                /* Fill buffer */
        buff[j++] = c;
        c = getc(f);
      } while (isdigit(c) || c=='e' || c=='E' || c=='+' || c=='-' || c=='.');
      buff[j]='\0';
      d = atof(buff);
      if (c==';' || c=='#') {             /* If exended with comment clear it now */
        while ((c = getc(f)) != '\n');
      }
      return (MYFLT)d;
    }
    while (isspace(c)) c = getc(f);       /* Whitespace */
    if (c==';' || c=='#' || c=='<') {     /* Comment and tag*/
      while ((c = getc(f)) != '\n');
    }
    goto top;
```

Suppose the next character to be read is a comma, and we are not at the end of the file.  We read that character and enter the loop.

```
    c = getc(f);
 top:
```

Now c contains a comma, and we check for end of file - but we're not there yet, so the body of this if has no effect.

```
    if (feof(f)) return NAN; /* Hope value is ignored */
```

Now we check for a digit, e, E, plus, minus, or period; but a comma is none of these, so this entire if statement has no effect, and in particular, does not read more characters from the file.

```
    if (isdigit(c) || c=='e' || c=='E' || c=='+' || c=='-' || c=='.') {
      double d;                           /* A number starts */
      char buff[128];
      int j = 0;
      do {                                /* Fill buffer */
        buff[j++] = c;
        c = getc(f);
      } while (isdigit(c) || c=='e' || c=='E' || c=='+' || c=='-' || c=='.');
      buff[j]='\0';
      d = atof(buff);
      if (c==';' || c=='#') {             /* If exended with comment clear it now */
        while ((c = getc(f)) != '\n');
      }
      return (MYFLT)d;
    }
```

Now we skip over whitespace, but because c contains a comma, which is not whitespace, the body of this while executes zero times, and no additional characters are read from the file.

```
    while (isspace(c)) c = getc(f);       /* Whitespace */
```

Now we check for semicolon, hash, and less-than, but since a comma is none of these, this if body also has no effect and reads no more characters.

```
    if (c==';' || c=='#' || c=='<') {     /* Comment and tag*/
      while ((c = getc(f)) != '\n');
    }
```

Now we branch unconditionally.  Note that because no more characters have been read from the file, c still contains a comma, and feof is still false.

```
    goto top;
```

With the false conditionals deleted, the code looks like this:

```
top:
    goto top;
```

Is the problem simply that someone intended the "top:" label to be above, not below, the "c = getc(f);"?  Switching them would guarantee termination by reading at least one character on every pass through the loop, but it's not clear to me whether it might not introduce other issues.

**Comment by jpffitch** [comment]
Switching the label higher is my solution, plus dealing wit comma which 
was missing.  Committed but not tested

**Comment by jpffitch** [comment]
Passes my tests and documentation adjusted.
I think it might do with better checking, or filling unused part of the table with zero?
