### ISSUE TITLE
Inconsistent Guiro-opcode behavior

### ISSUE THREAD

**Issue by narner** [csound/csound#457]
In the .csd example below, there are two instruments, both using the guiro opcode. It plays instrument one for four times, then plays instrument two once, then plays instrument one's sound again. Why would that be happening? 

```
<CsoundSynthesizer>

<CsOptions>
-o dac   
</CsOptions>

<CsInstruments>

nchnls = 2 
sr     = 44100 
0dbfs  = 1 
ksmps  = 64 

instr 1
aGuiro1 guiro 1, 1, 128, 0, 0, 2500, 4000
outs aGuiro1, aGuiro1

endin


instr 2
aGuiro2 guiro 1, 1, 800, 0, 0, 9000, 4000
outs aGuiro2, aGuiro2
endin
</CsInstruments>
<CsScore>
i 1 0 1
i 1 + .
i 1 + .
i 1 + .
i 2 5 1
i 2 + .
i 2 + .
i 2 + .



</CsScore>

</CsoundSynthesizer>
```

**Comment by kunstmusik** [comment]
@narner I ran this here with the latest from the develop branch and I heard four instances of each instrument. What version of Csound are you using?

**Comment by narner** [comment]
@kunstmusik Ahh, I'm running 6.03.4 on CsoundQt 0.8.2. 

Here's a link to the recorded output on SoundCloud: https://soundcloud.com/narner/phisemguirotestcsd-001

**Comment by kunstmusik** [comment]
@narner I'd try upgrading to Csound 6.04 and CsoundQT 0.9.0, considering I
have not heard any problems. Also, the log for Opcodes/phisem.c has:

```
commit f0558082ad5b0e0e30e89ea2241d971735a949db
Author: John ffitch <jpff@codemist.co.uk>
Date:   Tue Aug 26 19:03:25 2014 +0100

    fix to second guiro note
```

Which is after 6.03.2 (which was on May 14, 2014).

**Comment by jpffitch** [comment]
This bug was fixed some time ago I think

**Comment by narner** [comment]
I can confirm that this was fixed when running the test project on the latest version of Csound using CsoundQt 0.9.0 on my system.
