### ISSUE TITLE
Migrate Csound for Android SDK to Android Studio

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#460]
We should migrate the Csound for Android SDK to work with Android Studio.

**Comment by mantaraya36** [comment]
I don't know enough, but thought I'd ask, would this move preclude building
from the command line, or would it just be an addition to make it easy to
integrate Android Csound apps with the IDE?

**Comment by vlazzarini** [comment]
My impression is that we just propose to replace Eclipse for ADS, keeping the current workflow.

**Comment by digithree** [comment]
This would be great. I attempted to import a project which depends on Csound form Eclipse to Android Studio and got build errors. It would be ideal if it could function as a Gradle dependency on JCenter, this seems to be the most common remote for Android libraries.

This tutorial seems good: https://www.virag.si/2015/01/publishing-gradle-android-library-to-jcenter/

**Comment by kunstmusik** [comment]
@digithree Great idea! It would be great to be have the Csound library as a dependency in a repository. We'll have to document workflow details but it shouldn't be too bad.  We'll also have to figure out how this might work with Csound opcode libraries.

**Comment by digithree** [comment]
Excellent! Count me in.

**Comment by kunstmusik** [comment]
I have updated Csound for Android to be released as an Android Studio project.  This will be available in Csound 6.06.0.  A separate AAR release via JCenter will be tracked in #508.
