### ISSUE TITLE
CSound QT fails to launch

### ISSUE THREAD

**Issue by michaelrempel** [csound/csound#461]
Csound-d-cs6.exe has stopped working

on attempted launch. Debugger says

Unhandled exception at 0x53E2A0F3 (Qt5Widgets.dll) in CsoundQt-d-cs6.exe: 0xC0000005: Access violation reading location 0xFF000004.

AMD Phenom II X6 1090T 3.2GHZ, 16 gigs Windows 7 pro SP1

Install from installer unchanged. Problem showed up before reboot, tried a reboot and then ran my debugger.

Best,

Michael

**Comment by kunstmusik** [comment]
Is this Csound 6.05.0?

**Comment by gogins** [comment]
I will try uninstalling Csound from my work computer completely and
reinstalling 6.05.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by michaelrempel** [comment]
Yes, I just downloaded it.

**Comment by vlazzarini** [comment]
looks like a QT library issue, not a Csound one. Maybe two clashing DLL versions?

**Comment by gogins** [comment]
That's possible. Before 6.05 the CsoundQt that comes with Csound in the
Windows installer was built with MinGW,.  in 6.05 CsoundQt is buiilt with
Microsoft Visual C++. So a version conflict with CsoundQt on Windows could
well be a DLL problem.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by expressfinn** [comment]
After installing the latest CSound6.05 I will get this message

CsoundQt-d-cs6.exe has stopped working

My Computer
Operating System: Windows 7 Home Premium 64-bit SP1
CPU:      Intel Core i7 2630QM @ 2.00GHz

**Comment by jpffitch** [comment]
Sounds lke a csoundQT problem, not csound

**Comment by gogins** [comment]
I have just now completely removed Csound from my computer and work and
re-installed Csound 6.05 from SourceForge with all options (including
Python features) enabled. CsoundQt runs without any problems on this
computer now.

It is possible that the problem relates to code generation. You have an AMD
Phenom II X6 1090T 3.2GHZ CPU, just possibly the compiler flags used to
build Csound and/or CsoundQt are not compatible with this processor.

But first, could you please make sure that all prior versions of both
Csound and CsoundQt do not exist in your environment? As I said before,
there is a potential Qt DLL incompatibility problem. If you have
MinGW-built Qt DLLs in your PATH ahead of your MSVS-built Qt DLLs from the
Csound installer, there would definitely be a problem. Such MinGW- built Qt
DLLs could come from an earlier installation of Csound/CsoundQt, or even
from some other piece of software on your computer.

You don't need to uninstall anything to fix your environment, just make
sure that your Windows PATH environment variable puts the Csound bin
directory ahead of any other directory that might contain Qt DLLs. Also
check your Windows system32 directory to make sure that it does not contain
any Qt DLLs.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by michaelrempel** [comment]
I ran MS Debugger and checked that the QT DLL pointed to was the one in the
Csound6 application folder. It is a call to the dll that fails. Path
management in my system is explicit for each application, I have far too
many programs installed. The only reachable csound is also in that same
folder set. I have Visual Studio 2012 Premium.

 

I have been running CSound for years on this box. I looked for other DLLs
and did not find any. I have been using CSEdit and Blue for years, I thought
QT failed in prior versions as well, but I am not sure. 

 

Michael Rempel.

**Comment by gogins** [comment]
Thanks for your response. I will check your CPU capabilities against the
build compiler flags. However, a quick Google shows that this is a high-end
processor so I would not anticipate such incompatibilities.

Have you tried profiling CsoundQt with depends.exe (free download)?

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by michaelrempel** [comment]
CSoundQT Shows a bunch of run-time load dependency errors as suspected. This
is the list.

 

API-MS-WIN-APPMODEL-RUNTIME-L1-1-0.DLL

API-MS-WIN-CORE-WINRT-ERROR-L1-1-0.DLL

API-MS-WIN-CORE-WINRT-L1-1-0.DLL

API-MS-WIN-CORE-WINRT-ROBUFFER-L1-1-0.DLL

API-MS-WIN-CORE-WINRT-STRING-L1-1-0.DLL

API-MS-WIN-SHCORE-SCALING-L1-1-1.DLL

DCOMP.DLL

IESHIMS.DLL

 

And the console output

Error: At least one module has an unresolved import due to a missing export
function in an implicitly dependent module.

Error: Modules with different CPU types were found.

Warning: At least one delay-load dependency module was not found.

Warning: At least one module has an unresolved import due to a missing
export function in a delay-load dependent module.

**Comment by gogins** [comment]
The runtime dependency errors listed are not actually going to cause any
crashes (I see these on my system which runs).

The unresolved dependency error may or may not cause a crash. If you see it
in the depends log some time before the crash, most likely it is not the
cause.

"Modules with different CPU types" may be a problem. I thought I had made
CsoundQt's compiler flags consistent with Csound's but this may have
reverted. I will let you know this evening. Can you tell me which are the
modules that have CPU types not consistent with the Csound library?

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by michaelrempel** [comment]
A Quick debugger dump. I may have time to poke around further later.

 

CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\bin\CsoundQt-d-cs6.exe'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ntdll.dll'. Cannot
find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\kernel32.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\KernelBase.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ole32.dll'. Cannot
find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcrt.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\gdi32.dll'. Cannot
find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\user32.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\advapi32.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\sechost.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\rpcrt4.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\sspicli.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\cryptbase.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\lpk.dll'. Cannot
find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\usp10.dll'. Cannot
find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\bin\csound64.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\bin\libsndfile-1.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\bin\intl.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ws2_32.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\nsi.dll'. Cannot
find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\bin\libwinpthread-1.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\bin\pthreadVC2.dll'. Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcr100.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\bin\Qt5PrintSupport.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\bin\Qt5Widgets.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\bin\Qt5Gui.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\bin\Qt5Core.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\shell32.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\shlwapi.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\mpr.dll'. Cannot
find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\bin\icuin53.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\bin\icuuc53.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\bin\icudt53.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcr120.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcp120.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\winspool.drv'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\comdlg32.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded
'C:\Windows\winsxs\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.
0.7601.17514_none_41e6975e2bd6f2b2\comctl32.dll'. Cannot find or open the
PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\bin\Qt5QuickWidgets.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\bin\Qt5Quick.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\bin\Qt5Qml.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\bin\Qt5Network.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\dnsapi.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\crypt32.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msasn1.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\bin\Qt5Xml.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\imm32.dll'. Cannot
find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msctf.dll'. Cannot
find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\AVG\AVG2015\avghookx.dll'. Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\bin\platforms\qwindows.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\winmm.dll'. Cannot
find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\oleaut32.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\uxtheme.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\Wintab32.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\wtsapi32.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\Pen_Tablet.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\opengl32.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\glu32.dll'. Cannot
find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ddraw.dll'. Cannot
find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\dciman32.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\setupapi.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\cfgmgr32.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\devobj.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\dwmapi.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\nvoglv32.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\version.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\wintrust.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ntmarta.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\Wldap32.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\winsta.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\plugins64\ampmidid.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\bin\libgcc_s_dw2-1.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\plugins64\buchla.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\plugins64\cellular.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\plugins64\chua.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\bin\libstdc++-6.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\plugins64\cs_date.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\plugins64\doppler.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\plugins64\exciter.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\plugins64\fareygen.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\plugins64\fluidOpcodes.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\bin\libfluidsynth.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\dsound.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\powrprof.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\bin\libglib-2.0-0.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\bin\libgthread-2.0-0.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\bin\libgomp-1.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\plugins64\fractalnoise.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\plugins64\image.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\bin\libpng16-16.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\plugins64\ipmidi.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\plugins64\linear_algebra.dll'. Module was built without
symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\plugins64\LuaCsound.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\bin\lua51.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\plugins64\mixer.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\plugins64\osc.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\wsock32.dll'.
Cannot find or open the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\plugins64\padsynth.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\plugins64\platerev.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\plugins64\pmidi.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\bin\libportmidi.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\plugins64\py.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files (x86)\MySQL\MySQL
Fabric 1.5.3 & MySQL Utilities 1.5.3 1.5\python27.dll'. Cannot find or open
the PDB file.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\plugins64\rtpa.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\plugins64\rtwinmm.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\plugins64\scansyn.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\plugins64\serial.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\plugins64\signalflowgraph.dll'. Module was built without
symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\plugins64\stdutil.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\plugins64\stk.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\plugins64\system_call.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\plugins64\virtual.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\bin\mgwfltknox-1.3.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Program Files
(x86)\Csound6\plugins64\widgets.dll'. Module was built without symbols.

'CsoundQt-d-cs6.exe' (Win32): Loaded 'C:\Windows\SysWOW64\apphelp.dll'.
Cannot find or open the PDB file.

The thread 0x31e8 has exited with code 0 (0x0).

Unhandled exception at 0x649EA0F3 (Qt5Widgets.dll) in CsoundQt-d-cs6.exe:
0xC0000005: Access violation reading location 0xFF000004.

**Comment by gogins** [comment]
Modules built without symbols will not cause a crash as long as they were
linked with via import libraries, as all of these were as far as I know.

Modules missing PDB files also will not cause a crash. It just means that
if you step into such modules you will see assembler not source code.

I am guessing it is one of these:


   1. Wrong compiler flags to build Csound or CsoundQt (or the Qt DLLs, for
   that matter) as compared with your CPU.
   2. Some DLL required is not found on your system or is the wrong version.

Either way we can fix it, either by fixing the compiler flags or by adding
a library to the Csound bin dir. But we have to figure out what it is.

According to the GCC manual the AMD XP CPU uses this instruction set:

‘athlon-4’
‘athlon-xp’
‘athlon-mp’
Improved AMD Athlon CPU with MMX, 3DNow!, enhanced 3DNow! and full SSE
instruction set support.

I will check on flags used for Csound and CsoundQt when I build them for
the Windows installer. However, off the top of my head, I don't think there
would be a conflict. But I will check the details.

I'm leaning to the idea of a missing or incompatible DLL.

Thanks,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by vlazzarini** [comment]
Can you run Csound in the terminal at all?

Victor Lazzarini
Dean of Arts, Celtic Studies, and Philosophy
Maynooth University
Ireland

**Comment by gogins** [comment]
I certainly can.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by vlazzarini** [comment]
I meant Michael Rempel.

Victor Lazzarini
Dean of Arts, Celtic Studies, and Philosophy
Maynooth University
Ireland

**Comment by michaelrempel** [comment]
Command line CSound runs fine.

**Comment by gogins** [comment]
The compiler flags for CsoundQt are generic so should not be a problem. If
your Csound runs fine than the compiler flags for Csound also are not a
problem.

So i think the problem is a missing or incompatible DLL. You can email me
the log from depends.exe and I will compare it with mine.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by hsn10** [comment]
i have same problem with csound 6.0.5, i downloaded recently uploaded 6.05.1.beta from sf.net and it fixed problem.

**Comment by expressfinn** [comment]
Hi. 
Tnx hsn10 for the info.
For me at least the version 6.05.1.beta solved the problem of CsoundQt-d-cs6.exe stopping.

**Comment by endolith** [comment]
I have the same problem with CSound 6.05.0 in Windows 7 Pro 64-bit on an Intel i5 CPU, csoundqt crashes immediately and won't launch.

**Comment by michaelrempel** [comment]
The Beta fixed it for me. Thanks.

 

Michael Rempel

**Comment by gogins** [comment]
I do see a problem that I will immediately fix. The Windows installer does not contain all of the Microsoft runtime libraries for C and C++ that are identified by Qt as required for the version of Qt used to build the current CsoundQt.

I will add all required DLLs to the Windows installer and post a new version of it to SourceForge. I will also remove the existing installers based on Microsoft DLLs from public view.

I don't think the manifest is responsible, as I think it is embedded in the CsoundQt executable, but I will verify that as well.
