### ISSUE TITLE
Implement Continuous Build for Windows using Appveyor

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#464]
As mentioned by @fsateler on the dev list, appveyor.com provides continuous builds for Windows and is free for open-source projects.  It is similarly setup to Travis.  I imagine if we can automate the build using appveyor, we should also get a simple reproducible build for Windows as a whole.

**Comment by jpffitch** [comment]
This seems a good idea; tried reading the "getting started" but could not understand how to start(!)

Anyone know about this?  Seems similar to travis but probably needs a widows background

**Comment by kunstmusik** [comment]
I've only taken a brief look but yes, it's pretty much Travis for Windows
in a nutshell. We're close to getting the Visual Studio build working and I
think we should setup Appveyor once that is complete.

**Comment by rorywalsh** [comment]
Great idea.

**Comment by stekyne** [comment]
Delivered in #793. Closing the issue.
