### ISSUE TITLE
VCOscillator - triangle waveform not working

### ISSUE THREAD

**Issue by narner** [csound/csound#468]
I'm using VCOscillator in a project, and am attempting to use the 'triangle with ramp' waveform. However, I don't hear any audio output when I try to use that waveform (all of the other waveforms work fine). 

I've attached a .CSD file for demonstrating this...I'm running the latest version of Csound. 

<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 128
nchnls = 2
0dbfs = 1.0

instr 1
aVCO vco2 0.5, 440, p4, 0, 0, 0.5
outs aVCO, aVCO
endin

</CsInstruments>

<CsScore>
i1 0 1 0 ; Sawtooth
i1 + 1 4 ; Triangle that doesn't work
i1 + 1 12 ; Triangle that works

</CsScore>
</CsoundSynthesizer>
![screen shot 2015-05-17 at 8 48 59 pm](https://cloud.githubusercontent.com/assets/2131591/7672977/32475892-fcd6-11e4-82ae-31535656b8d2.png)

**Comment by vlazzarini** [comment]
The manual says that for mode 4, kpw cannot be 0 or 1.

Victor Lazzarini
Dean of Arts, Celtic Studies, and Philosophy
Maynooth University
Ireland

**Comment by narner** [comment]
My mistake Victor; didn't catch that before.

**Comment by vlazzarini** [comment]
not a problem, best to report than to have a possible bug go undetected
