### ISSUE TITLE
OSClisten Issue

### ISSUE THREAD

**Issue by abhunkin** [csound/csound#470]
Steven Yi responded:
Seems reasonable to me at least, maybe go ahead and file an issue in
the tracker and someone can look into it further.

On Thu, May 21, 2015 at 1:17 PM, Art Hunkins <abhunkin@uncg.edu> wrote:
> Steven -
>
> Your explanation makes sense, and is no doubt what is happening.
>
> I doubt that in the case we are discussing, anyone actually expects the
> result that occurs - in this example, kamp increases to infinite amplitude
> with many thousands of samples out of range (according to Console output).
> In addition, I feel sure noone has ever used OSClisten this way.
>
> A simple change in OSClisten to (re-)set the value of kamp to its
> *unchanged* value each k-cycle (if indeed unchanged) would rectify the
> situation. To my knowledge, this is what occurs with other input values in
> opcodes including MIDI and chnget. There would be no change to OSClisten's
> format or behavior other than to cover this case.
>
> Does anyone see a problem with this proposal?
>
> It would certainly simplify porting .csd's designed for MIDI or chngets, to
> OSC control. The several "workaround" alternatives, such as the one Russell
> suggests, require additional coding changes.
>
> Art Hunkins
>
> ----- Original Message -----
> From: "Steven Yi" <stevenyi@gmail.com>
> To: "csound users' discussions" <csound-users@lists.sourceforge.net>
> Sent: Tuesday, May 19, 2015 7:38 PM
> Subject: Re: [Csnd] OSClisten Issue
>
>
>> Hi Art,
>>
>> I looked a little into this and I think what is happening is that with
>> OSClisten, it sets the value to kamp only when a change is found (so
>> kans will be 1 in those cases). In the cases where no changes were
>> found, it does not set the value to kamp, and the previous value will
>> be there.  In that case, when you get to the:
>>
>> kamp = kamp * 12000
>>
>> line, it will multiply the previous value of kamp there, instead of
>> the last value received from OSClisten.  That would explain why the
>> other two versions work.
>>
>> I don't really use OSC much myself, so don't have much of an opinion
>> on any changes, but thought the above worth mentioning.
>>
>> steven
>>
>> On Tue, May 19, 2015 at 7:10 PM, Art Hunkins <abhunkin@uncg.edu> wrote:
>>> I've been working intensively on Android with OSClisten, receiving OSC
>>> data
>>> from TouchOSC GUIs (Layouts). I've no idea whether or not this issue
>>> pertains to other situations or platforms, though I suspect it does.
>>>
>>> It is this:
>>>
>>> The following code works:
>>> kamp   init     0
>>> kans    OSClisten gichan, "/1/slider1", "f", kamp
>>> aout    lfo      kamp * 12000, 440, 1
>>>         outs     aout, aout
>>>
>>> So does this:
>>> kamp   init     0
>>> kans    OSClisten gichan, "/1/slider1", "f", kamp
>>> kamp2 = kamp * 12000
>>> aout    lfo      kamp2, 440, 1
>>>         outs     aout, aout
>>>
>>> But this (which I use all the time, and which works fine in the context
>>> of
>>> chnget and MIDI input) does not:
>>> kamp   init     0
>>> kans    OSClisten gichan, "/1/slider1", "f", kamp
>>> kamp = kamp * 12000
>>> aout    lfo      kamp, 440, 1
>>>         outs     aout, aout
>>>
>>> The problem seems to be that an OSC k-time variable (here kamp) cannot be
>>> redefined. I feel sure this has something to do with the special way that
>>> OSC data are stored/handled that is different from how MIDI and chnget
>>> variables are treated.

**Comment by kunstmusik** [comment]
From the discussion on the mailing list, modifying the existing OSClisten seems the wrong way to go. There are also work arounds mentioned on the list.  I'll close this.  If a new opcode is desired, then let's go with a new issue.
