### ISSUE TITLE
Missing include in nacl/csound/csound.cpp 

### ISSUE THREAD

**Issue by fcahoon** [csound/csound#472]
This patch is needed to build csound.pexe from source:

diff --git a/nacl/csound/csound.cpp b/nacl/csound/csound.cpp
index 895a2bf..efeefb1 100644
--- a/nacl/csound/csound.cpp
+++ b/nacl/csound/csound.cpp
@@ -35,6 +35,7 @@
 #include "ppapi/utility/completion_callback_factory.h"
 #include "ppapi/cpp/module.h"
 #include "ppapi/cpp/var.h"
+#include "ppapi/cpp/var_dictionary.h"
 #include <sys/mount.h>
 #include <errno.h>
 #include "nacl_io/nacl_io.h"

**Comment by vlazzarini** [comment]
Thanks, I will investigate this before iincorporating

**Comment by fcahoon** [comment]
Looks like GitHub ate the angle brackets in that patch -- let me try that again with a Markdown code block:

```
diff --git a/nacl/csound/csound.cpp b/nacl/csound/csound.cpp
index 895a2bf..efeefb1 100644
--- a/nacl/csound/csound.cpp
+++ b/nacl/csound/csound.cpp
@@ -35,6 +35,7 @@
 #include "ppapi/utility/completion_callback_factory.h"
 #include "ppapi/cpp/module.h"
 #include "ppapi/cpp/var.h"
+#include "ppapi/cpp/var_dictionary.h"
 #include <sys/mount.h>
 #include <errno.h>
 #include "nacl_io/nacl_io.h"
```

The point is, var_dictionary.h is now a required include, at least as of pepper_42 (the current stable according to the naclsdk command-line tool of the NaCl SDK distribution).
