### ISSUE TITLE
Unexepected behavior using PNaCl csound.PlayCsd() with sr=48000

### ISSUE THREAD

**Issue by fcahoon** [csound/csound#474]
When csound.PlayCsd() is used to play a csd file which has sr=48000 specified, the pitches are lower than the same file with sr=44100 ; I suspect the samples are being calculated for 48000 but being played at 44100.

Other sr values generate the error "CompiledCsound error: unsupported SR" and does not play. A minimal fix would be to have this also occur for sr=48000.

For my use case, a better behavior (assuming PNaCl Csound must be hardcoded to sr=44100) would be to override any other sr value with a warning and proceed to play the csd file.

**Comment by vlazzarini** [comment]
48000 is not supported at the moment by Pepper.

**Comment by fcahoon** [comment]
Right, which is why it should generate an error instead of playing at the wrong frequency.

**Comment by vlazzarini** [comment]
done.
