### ISSUE TITLE
Migration away from SourceForge

### ISSUE THREAD

**Issue by ainola** [csound/csound#475]
Considering the [sorry state](https://helb.github.io/goodbye-sourceforge/) that Sourceforge is in, I'd imagine the current scandal of Hijacking GIMP's projects proves a decent time to bring up a request to move away from SF.

I imagine the only feature that SF might have would be the mailing list, but code hosting/binary downloads seem to already be set up in Github. Duplication of efforts seems a little silly, anyway.

**Comment by vlazzarini** [comment]
We do not duplicate; we use SF solely for releases and lists. If we decide to move away from SF, we should do it completely, lists and releases, and also old packages. We should close the Csound project completely so that we are not exposed to any misuse.

**Comment by ainola** [comment]
Are the releases posted on Github not advised? I am in the process of repackaging Archlinux's csound to depend on github's files rather than sourceforge.

**Comment by vlazzarini** [comment]
We do not currently release on Github, it's the source repo only at the moment.

**Comment by PaulBatchelor** [comment]
It makes a great deal of sense to break away completely from SF, though this will take some time and planning to do adequately. 

A list of things I see that need to be done:

- Download existing files on SF to temporary holding place
- Decide alternative mail service for mailing list (options here?)
- Migrate mailing list to said new mailing list service 
- Set up release page on github
- Upload archive of old releases on github (is this possible?)
- Update download links accordingly
- Delete Account and content on Sourceforge

Feel free to add things that I missed.

**Comment by narner** [comment]
This may have been mentioned in the mailing list thread on the topic, but here is GitHub's guide to setting up software releases: [Release Your Software] (https://github.com/blog/1547-release-your-software).

**Comment by jpffitch** [comment]
We have migrated -- should we close this?

**Comment by PaulBatchelor** [comment]
I think this can be closed.
