### ISSUE TITLE
port at a-rate 

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#477]
i'm looking for an a-rate version of the port opcode. When using this a-rate port within the tied notes system of Csound, it would help to prevent  audible clicks and smoothen the abrupt changes  in amplitude and/or pitch with ksmps>1.

**Comment by vlazzarini** [comment]
tone should work in the same way as port, but instead o setting a half-time, you set a freq (lower freqs  mean longer half-times).

**Comment by tjingboem** [comment]
tone and port ( even together with interp) still produces little clicks, that can be heard when you use sine waves as a sound source. 
Best solution is to make a UDO for port and setkspms=1. Tied notes, even when using sine waves, are clean this way.

This works for me, so you can close this issue.
