### ISSUE TITLE
Feature request: write BWF-data

### ISSUE THREAD

**Issue by cvrn** [csound/csound#480]
It is already possible to read bwf-data via sndinfo. It would be helpful to write bwf-data as well when creating audiofiles.

**Comment by jpffitch** [comment]
I think this depends on libsndfile providing support.  I would rather not 
do this ad-hoc.  Therehas been discussion on libsndfie-devel about this 
recently.
==John ff

**Comment by jpffitch** [comment]
Closing as theis really relates to libsndfile
