### ISSUE TITLE
transeg first note

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#481]
the first note of the csd, using transeg, shows that channel 1 begins all right, while channel 2 kicks in at a later time.
![screenshot from 2015-06-07 13 42 36](https://cloud.githubusercontent.com/assets/6670911/8023820/8d121ed2-0d1c-11e5-8264-a77bf67eb8cc.png)
The second note is like it should.
![screenshot from 2015-06-07 13 43 00](https://cloud.githubusercontent.com/assets/6670911/8023824/9fa0e9de-0d1c-11e5-84ba-1c8b2adfb1fd.png)

I can hear the sound kicking in on channel 2.

A similar csd but using adsr instead of transeg does not show such behaviour. 
Here is the first note with adsr:
![screenshot from 2015-06-07 13 48 42](https://cloud.githubusercontent.com/assets/6670911/8023831/e829ffe2-0d1c-11e5-81af-124a3a05822b.png)

Here is the csd:
<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
; Audio out   Audio in
-odac           -iadc    ;;;RT audio I/O
; For Non-realtime ouput leave only the line below:
; -o transeg.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 48000
ksmps = 32
nchnls = 2

0dbfs = 1

instr 1
;p4 and p5 determine the type of curve for each
;section of the envelope
kenv transeg 0, p3*0.0001, p4, 1, p3-0.0001, p5, 0
;kenv adsr 0.00001, .6, 0, 0
aenv interp kenv
a1 poscil aenv, 440, 1
outs a1, a1
endin

</CsInstruments>
<CsScore>
; Table #1, a sine wave.
f 1 0 16384 10 1

i 1 0 2 0 -20
i 1 3 2 0 -20
i 1 6 2 0 -20
e
</CsScore>
</CsoundSynthesizer>

**Comment by fggp** [comment]
Hello Menno,

on my system, Csound version 6.05 (double samples) May 30 2015, compiled 
from sources on Ubuntu 14.04, channel 1 and channel 2 are totally 
synchronized from the first note included.

Regards

Francois

**Comment by tjingboem** [comment]
That is interesting, Francois. I have the same system as you do...

**Comment by tjingboem** [comment]
except that iam using Jack.
And Jack and Csound apparently needs some time to kick in - hence the missing beginning on channel 2.
So it's solved.
Can you please close this issue?
