### ISSUE TITLE
check if Loris opcodes still work

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#484]
- download and build Loris with Csound support and check if they works as expected in Csound6.

If not and the Loris support has been lost forever, the Loris opcodes in the Csound manual can be regarded as deprecated

**Comment by vlazzarini** [comment]
csound 5 opcodes will not compile for Csound 6, that is a given. The Loris authors should be notified of this. There is only a small change needed to make them compile.

**Comment by tjingboem** [comment]
i've made the support request at the Loris SourceForge site -

**Comment by tjingboem** [comment]
...and got an answer from Kelly Fitz from the CERL Sound Group:

"I am not a Csound user, and I don't have a lot of bandwidth to dedicate to that kind of maintenance. I would be glad to work with someone more familiar with the Csound API who wanted to take charge of that update, but if it has to wait for my availability, it isn't going to happen soon, I'm afraid.

Michael Gogins helped me quite a lot to get everything updated to Csound 5, when that was fresh, and I remember that it was messy and that the API was not that well documented or thoroughly maintained. I believe that only someone pretty familiar with that API can make that upgrade efficiently. "

**Comment by vlazzarini** [comment]
Well, we could help him; I would not want to
bring it back into the Csound sources, as they would very quckly diverge from the upstream sources.

**Comment by vlazzarini** [comment]
This is not Csound, I suggest asking the third party developers.

**Comment by gogins** [comment]
The developer is not interested. A compromise would be to fork Loris into
its own repository and maintain the Csound plugin there.

Regards,
Mike
