### ISSUE TITLE
Csound~ crashes when receiving strings

### ISSUE THREAD

**Issue by unriginal** [csound/csound#486]
If I send multiple strings in relatively quick sucession to Csound~, Max crashes. An example of this would be in the "chn string channels" subpatcher in the helpfile for Csound~. Clicking between the message boxes that contain c my_string will cause max to crash. I am using Csound version 6.05, Csound~ version 1.1.3, and Max version 7.0.3, in 64bit.

**Comment by kunstmusik** [comment]
I'm able to get crashes but with different methods.  There seems to be code in csound~ that wasn't updated when Csound moved to using STRINGDAT internally rather than raw char* data.  There also may be an issue with Csound's string channels.  This requires a little more investigation.

**Comment by kunstmusik** [comment]
Just to follow up, the Csound string channel code I was looking at turned out to be alright.  I'll continue looking at the csound~ String channel code.

**Comment by kunstmusik** [comment]
String handling code updated to work with Csound 6 conventions.
