### ISSUE TITLE
--get-system-sr fails when using jack as backend

### ISSUE THREAD

**Issue by gesellkammer** [csound/csound#490]
Tested in Linux (Ubuntu 15.04)
* Jack is running with a samplerate of 48000

$> csound -odac -+rtaudio=jack --get-system-sr
...
Csound version 6.05 (double samples) May 14 2015
libsndfile-1.0.25
rtmidi: ALSA Raw MIDI module enabled
rtaudio: JACK module enabled
Error: define environment variable RAWWAVE_PATH
(points to rawwaves directory) to use STK opcodes.
 *** rtjack: sample rate 44100 does not match JACK sample rate 48000

With "pa_cb" as rtaudio backend, the correct samplerate is given.

**Comment by vlazzarini** [comment]
Ok, it looks like Csound does not have a chance to report the sr because the error message kills it
off first. Thanks for the report, we'll get to it.

**Comment by vlazzarini** [comment]
Now Jack will report it before issuing an error. This last bit needs to still take place, because it is true.
