### ISSUE TITLE
Csound~ crashes when using fluid opcodes

### ISSUE THREAD

**Issue by unriginal** [csound/csound#494]
When loading a .csd that uses the fluid opcodes, such as the fluidnote.csd from the manual, Csound~ will crash on start.

**Comment by kunstmusik** [comment]
@unriginal  Do fluidsynth examples work on your system using commandline csound?

**Comment by unriginal** [comment]
Yes- I was using the fluidnote.csd from the manual, and it worked in
commandline, but crashed max while compiling in csound~

**Comment by kunstmusik** [comment]
@unriginal  I just tried this using my local build of csound~ and csound.  What version of Csound are you using? Also, is this on OSX?

**Comment by unriginal** [comment]
Yes- I'm using 6.0.5 in OSX 10.10.4, with Max 7.0.4 and Live 9.2, and I'm still encountering this issue. I was using Max 7.0.3, Csound 6.0.4, and OSX 10.10.3 when I filed it. It still works in the command line for me.

**Comment by kunstmusik** [comment]
I have removed myself as asignee as Csound~ is now maintained by Mark Jordankamholz.

**Comment by jpffitch** [comment]
Is this still an issue or has it been resolved?  Almost a year since last response.

**Comment by vlazzarini** [comment]
Who maintains this?

**Comment by vlazzarini** [comment]
can we close this?

**Comment by jpffitch** [comment]
I think it shoud be closed as no response and old
