### ISSUE TITLE
csound installer and java wrapper on osx

### ISSUE THREAD

**Issue by peimankhosravi** [csound/csound#498]
On os x. the java library does not seem to be installed in the correct place. I need to manualy copy csnd6.jar and lib_jcsound6.jnilib from /Library/Frameworks/CsoundLib64.framework/Versions/6.0/Resources/Java/ to /Library/Java/Extensions

Even then, I get an error when calling the csound class. (Please see my other reported issue.)

**Comment by vlazzarini** [comment]
lib_jcsound6.jnilib is installed in /Library/Java/Extensions (as a link) by a postinstall/postupgrade script in the installer

```
/bin/ln -sF /Library/Frameworks/CsoundLib64.framework/Resources/Java/lib_jcsound6.jnilib /Library/Java/Extensions/lib_jcsound6.jnilib
```

Not sure where the jar should go (extensions is for jnilibs as far as I know).

**Comment by vlazzarini** [comment]
A link was added to the installer script to link csnd6.jar
