### ISSUE TITLE
csound~ 1.1.3 not installed in correct location

### ISSUE THREAD

**Issue by alfonso73** [csound/csound#499]
Hi for an external to be seen in the Package dir on Windows 7 the path must be,

C:\Users\$USER_NAME$\Documents\Max 7\Packages\csound~_v1.1.3

the externals must be in

C:\Users\$USER_NAME$\Documents\Max 7\Packages\csound~_v1.1.3\externals

and the help patches in

C:\Users\$USER_NAME$\Documents\Max 7\Packages\csound~_v1.1.3\help

otherwise the externals are not seen in Max 7 unless the user specify an explicit search path in the Max 7 Directories Properties.

**Comment by peimankhosravi** [comment]
I think the best solution is what Steven suggeted, which is to have the externals and exmaples distributed in a zip file.

**Comment by jpffitch** [comment]
This is very old, over 4 years!  Has it been fixed yet?

**Comment by kunstmusik** [comment]
No idea, but I'm closing out this issue as csound~ has its own repo and tracker now at https://github.com/csound/csound_tilde/issues.
