### ISSUE TITLE
Request : Csound and all its frontends for Windows 64bit

### ISSUE THREAD

**Issue by alfonso73** [csound/csound#501]
Hi guys,
there is and experimental Cabbage 64 bit version.
I think it's about time to think about  a full Csound distribution for Windows 64bit.
thanks and bests!!
a.

**Comment by gogins** [comment]
I think the best solution here may be to turn the Cabbage 64 bit build into the full Windows release, but I will look at the build system and see if I can adapt it for Windows 64 bits general release. So far, it looks pretty specific to a particular system and uses scripts and not makefiles. I will communicate with Rory Walsh about this.

**Comment by gogins** [comment]
Steven Yi began and I have completed a system for building all Csound programs, loadable modules and plugins, frontends, and interface libraries on Windows for 64 bit CPU architecture, including an Inno Setup installer. I am now testing the build but this issue, itself, will now be closed.

**Comment by alfonso73** [comment]
well done! thanks
Il 25/mar/2016 12:46, "Michael Gogins" <notifications@github.com> ha
scritto:
