### ISSUE TITLE
alsaseq reading Midi device error reported

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#503]
On every run an error is reported when using alsaseq but alsaseq seems to be working like it should:
................
ALSASEQ: opened MIDI output sequencer
ALSASEQ: created output port 'Csound' 130:0
ALSASEQ: connected to 16:0
--Csound version 6.05 (double samples) Jun  2 2015
..................
.................
ALSASEQ: opened MIDI input sequencer
ALSASEQ: created input port 'Csound' 131:0
ALSASEQ: connected from 16:0
................
...............
 *** error reading MIDI device: -2 (Unknown MIDI error)
WARNING: rtjack: xrun in real time audio
 *** error reading MIDI device: -2 (Unknown MIDI error)
................

As far as i am concerned, i have been using alsaseq for a while now and did not have any problems with either reading or writing to the ports.
I think this message can be removed?

I'm using Linux Mint, KXStudio and Jack

**Comment by vlazzarini** [comment]
This actually is a real read error, and not a bug. It means:

The sequencer event does not correspond to one or more MIDI messages.

 For some reason, the event received is not quite right. But we cannot silence this message, because it is genuine.
