### ISSUE TITLE
Bad code crashing compiler. No error message.

### ISSUE THREAD

**Issue by Underwaterbob** [csound/csound#504]
I had an error in my code:
...
f5   0    8192    -18    4 1 0 2047 3 1 2048 4095 2 1 4096 6143 1 1 6144 8192
...
The last number exceeds the table length. Instead of informing me of the error, the compiler gets to "new alloc for instr 1:" before Windows notifies me that "csound.exe has stopped working".

If I change the last number to 8191 as it should be, everything compiles fine.

I'm using command line CSound 6.05 in Windows 8.1.

**Comment by jpffitch** [comment]
fixed in git; gives error message
