### ISSUE TITLE
handling large strings - iOS uses very long file paths

### ISSUE THREAD

**Issue by boulangerlabs** [csound/csound#505]
With Csound 5, I used an Obj-C API function to send a score message to csound.  The scoreline includes a very large file path (string) as one of its p-fields.  

With Csound 6, a mangled version of the string is fed to my instrument.

I believe Steven Yi has already successfully located the bug - 
changing SSTRSIZE did seem to fix things.  Currently it is set to 200 in size. I modified to 256 and I'm getting the string that is passed in consistently printed out.  

SSTRSIZE is used in a few places, particularly in reading line events.

He also raised a good question:
Is quite long as it's in a generated path.  I'm wondering what we should use, to take into account possible very long paths.  Would 512 be a good compromise between accommodating large strings passed in, and memory requirements? 

Michael Gogins gave great input:
I think it should simply be the maximum of the maximum path lengths on different operating systems.

Steven built a version of Csound for iOS with SSTRSIZE set to 1024 (MAX_PATH on iOS), and I have verified that csound is now properly handling my file path strings on iOS.

**Comment by vlazzarini** [comment]
This issue seems to have been dealt with in the sources.
