### ISSUE TITLE
Vibrato with a phase causes a segmentation fault

### ISSUE THREAD

**Issue by aure** [csound/csound#507]
My apologies if this a known bug, but in the example from the manual page on vibrato, if I add an iphs parameter at the end of the vibrato, I get a segmentation fault:

kvib vibrato kaverageamp, kaveragefreq, krandamountamp, krandamountfreq, kampminrate, kampmaxrate, kcpsminrate, kcpsmaxrate, 1, 0.25

Only the values of 0 or 1 seem to work.

**Comment by vlazzarini** [comment]
No, it is not known as far as I can tell. We'll look into it

**Comment by vlazzarini** [comment]
Fixed in git.
