### ISSUE TITLE
INCDIR parse error

### ISSUE THREAD

**Issue by ssaue** [csound/csound#510]
It looks like the parser removes the drive letter from the INCDIR path, at least on Windows. Using INCDIR="C:\Program Files (x86)\Hadron" as include path the Csound console verbose output prints:

Creating search path cache for 'INCDIR':
    1: "\Program Files (x86)\Hadron\"
    2: "C\"

The drive letter and the remaining path has been separated in two. This works OK as long as my working directory is on the C:-drive, but fails if it is on another drive.

**Comment by jpffitch** [comment]
I think someone years ago introduced : as a separator.  So we are kinda stuck with that.  We could change the separator on Windows to ; I suppose but not sure if that gives problems.  Any advice/suggestions?

**Comment by jpffitch** [comment]
It is a bug in csoundGetSearchPathFromEnv (Engine/envvar.c)
Yeak!  what a function.  I have found where it is wrong but so far my patch is wrong.  Could do with a test program
cannot find a test program

**Comment by jpffitch** [comment]
My newer patch passed my simple tests; can you try git version?

**Comment by ssaue** [comment]
Works fine on Windows now. Thank you
