### ISSUE TITLE
pvstanal no output if kwrap = 0

### ISSUE THREAD

**Issue by arsalanabedian** [csound/csound#512]
when using the opcode pvstanal with a soundfile in ftgen, if the input "kwrap" = 0 then no sounds would be play. 
fSig pvstanal p4, giamp, gipitch, giFile, gidet, giwrap, gioffset, gifftsize, gioverlap, githresh
giwrap = 0 ;no sounds!
giwrap = 1 ;it works

**Comment by vlazzarini** [comment]
I need an example demonstrating the problem. If giwrap = 0 the sound will stop playing when it reaches the end of the table, so this can be normal behaviour.

**Comment by arsalanabedian** [comment]
Hi,

actually the sound does not begin at all when giwrap = 0.

**Comment by vlazzarini** [comment]
Ok, fixed in GIT sources. Thanks for the report.
For now, if you do not build your own Csound, the work-around is to give it a small offset
of hopsize/sr (default hopsize is 512).

**Comment by arsalanabedian** [comment]
Perfect! Thank you
