### ISSUE TITLE
Extract feature does not work any longer

### ISSUE THREAD

**Issue by nicb** [csound/csound#514]
For a very long time I have been using in my didactical slides some examples in which I separate voicings using the extract feature of csound. Very recently (e.g. yesterday) I realized that this feature, that used to work on very old csound scripts, does not work any longer.Here is a [gist](https://gist.github.com/nicb/b44861cc0243b838d482#file-test_extract-csd) to exemplify the problem. If you simply compile this file (which has a score with two voices corresponding to two instruments, namely 1 and 2) - everything works as a charm. However, as soon as you try to isolate one of the two instruments with an extract file that just says 

i 1 

(or i 2 for that matter), no output is produced. 

I am using Csound version 6.03.2 (double samples) Jun  6 2014 with libsndfile-1.0.25 on Debian GNU/Linux 8.

**Comment by vlazzarini** [comment]
I think I've fixed this on the GIT sources. I can extract the voices now from your file.

**Comment by nicb** [comment]
Ah! Yes actually I just compiled from the git sources and it works fine! Thank you Victor!

**Comment by cscomposer** [comment]
Dear Csounders,
I tested (and i need) the extract feature –xfile.txt  (that dr. Lazzarini fixed on GIT sources on 6.03) on 6.06 and 6.09 (OSX) and it crashes always CsoundQt! 
I need this  old feature for an important goal: to hear single sounds and voices from an long score articulated in more sections: for this purpose don’t seem valid the other features avalaibles:
-the advance feature (a 0 0 xsec)
-the skip section “x”
-	the setscore position opcode, valid apparently without sections
-	- the Evaluate selection, avalaible in CsoundQt, interesting but not so practice and general I I find this extract feature valid to control each voice/instrument and time point (or attack point) of score!
-	Greetings and gratulations for ICSC!
-	Giovanni Damiani
