### ISSUE TITLE
Add array output to monitor opcode

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#515]
it would be nice to have an array output as option for the monitor opcode. it is often cumbersome to change the code depending on the nchnls.  with an array output, we could do:
  aOutChnls[] init nchnls
and then use any of them for display or something else.

**Comment by jpffitch** [comment]
Partially working -- lost a channel

**Comment by jpffitch** [comment]
OK now and in manual

**Comment by joachimheintz** [comment]
i just checked but get no output for the example below.  can you test?
thanks -
	joachim


<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 8
0dbfs = 1

vbaplsinit 3, 5, -45, 0, 45, 0, 135, 0, -135, 0, 0, 90

instr Test

  aSig poscil 1, 400
  ;aSig soundin "fox.wav"
  kAzim linseg 0, p3, 360
  a1, a2, a3, a4, a5 vbap aSig, kAzim, 0
  outch 1, a1, 2, a2, 3, a3, 4, a4, 5, a5

endin

instr Monitor

  aOut[] monitor
  kTrig metro 10
  kPrevMax init 0
  kMax max_k aOut[0], kTrig, 1
  printk2 kMax

endin


</CsInstruments>
<CsScore>
i "Test" 0 10
i "Monitor" 0 10
</CsScore>
</CsoundSynthesizer>

**Comment by jpffitch** [comment]
Apologies-- fencepost problem fixed (I think)

**Comment by joachimheintz** [comment]
yes, works now perfectly!
thanks — so useful to have!!
	joachim
