### ISSUE TITLE
clicks using 'segr' opcodes, --realtime and --sample-accurate

### ISSUE THREAD

**Issue by ErrorThink** [csound/csound#519]
With both --realtime and --sample-accurate in the command line flags, Using 'segr' opcodes (e.g. linsegr, expsegr, transegr) introduces a click in the audio when rendered to dac. The click seems to be at the time p3 expires. Removing either flag fixes the issue, as does rendering to disk. 
Csound version 6.05 (double samples) May  1 2015, on linux mint 14
Example:
```
<CsoundSynthesizer>
<CsOptions>
-odac 
--realtime 
--sample-accurate
</CsOptions>

<CsInstruments>
nchnls=2
0dbfs=1


instr 1

; clicks with both --realtime and --sample-accurate in the command line flags.
; removing either flag fixes the issue, as does rendering to disk.

aenv linsegr 0, 0.08, 1, 0, 1, 1.5, 0

ares oscili p4, p5

aresult = ares * aenv

outs aresult, aresult

endin

</CsInstruments>

<CsScore>
i1 0 0.5 0.3 440
i1 0 0.75 0.3 400
i1 0 1 0.3 340
e

</CsScore>
</CsoundSynthesizer>
```

**Comment by vlazzarini** [comment]
it does click. I will have to check why. Thanks for reporting

**Comment by vlazzarini** [comment]
fixed in git develop
