### ISSUE TITLE
tablexkt sinc interpolation bug

### ISSUE THREAD

**Issue by awelex** [csound/csound#521]
Using sinc interpolation with tablexkt causes significant artifacts, distortion, and high frequency ringing. All other interpolation methods work fine.

**Comment by vlazzarini** [comment]
I have been looking at this and I can't yet locate the bug. The code for diskin2 & tablexkt is very similar.

**Comment by vlazzarini** [comment]
fixed in git. It was subtle error in one expression (parenthesis location) that it took a while to find.
Also on the bright side, I've changed it so that it can take tables of any size.
