### ISSUE TITLE
plltrack with ksmps=1

### ISSUE THREAD

**Issue by Oeyvind** [csound/csound#523]
plltrack outputs zero as the cps value if ksmps = 1

example csd attached, works fine if ksmps is 2 or higher, but produce silence in the right channel when ksmps = 1

Tested with 
Csound version 6.05 (double samples) Apr 24 2015
on windows 7

<CsoundSynthesizer>
<CsOptions>
-opll_test.wav
</CsOptions>
<CsInstruments>

	sr = 48000
	ksmps = 1
	nchnls = 2	
	0dbfs = 1

	giSine		ftgen	0, 0, 65536, 10, 1

	instr 1
        iamp    = ampdbfs(-9)
        kfreq   line 200, p3, 400
	a1	oscili iamp, kfreq, giSine
        acps, alock plltrack a1, 0.2 
	a2	oscili iamp, acps, giSine
		outs a1, a2
	endin

</CsInstruments>
<CsScore>
i1	0	2
e
</CsScore>
</CsoundSynthesizer>

**Comment by vlazzarini** [comment]
That was an easy one. Fixed on git. Thanks for the report
