### ISSUE TITLE
Csound for Android Documentation: Update Required

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#525]
Sections 8 and 9 are currently marked as referring to older versions of Csound for Android. Section 8 is marked as written for Eclipse, and section 9 is marked as referring to an older version of the Csound6 Application.  These sections needs updating for Android Studio and the latest version of the Csound6 application.

**Comment by gogins** [comment]
Not sure what the documentation being referred to is.

**Comment by kunstmusik** [comment]
This issue is for the manual that comes with Csound for Android SDK release.  The source is a latex file found in csound/android/docs/csound_android_manual.tex.

**Comment by kunstmusik** [comment]
The manual requires further updates for images, but the text is at least updated to refer to steps necessary for Android Studio.  I have filed issue #711 to continue looking at the manual at a future date.
