### ISSUE TITLE
Cannot compile 6.05.0 on Arch/glibc 2.22

### ISSUE THREAD

**Issue by ainola** [csound/csound#526]
Forgive me if I'm wrong in creating a ticket in csound, but it appears that the latest glibc seems to have issues with compiling csound. At compile time I'm presented with the following:
```
/usr/bin/ld: CMakeFiles/csound-bin.dir/csound/csound_main.c.o: undefined reference to symbol '_ZGVcN4vv_pow@@GLIBC_2.22'
/usr/lib/libmvec.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
frontends/CMakeFiles/csound-bin.dir/build.make:121: recipe for target 'csound' failed
make[2]: *** [csound] Error 1
CMakeFiles/Makefile2:2086: recipe for target 'frontends/CMakeFiles/csound-bin.dir/all' failed
make[1]: *** [frontends/CMakeFiles/csound-bin.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```
This is using the same PKGBUILD for 6.05 that I am certain worked since 6.05 first came out.

**Comment by vlazzarini** [comment]
looks like some sort of version mismatch in your development environment. Did you do a fresh build?

**Comment by ainola** [comment]
Yes, completely clean.

**Comment by vlazzarini** [comment]
you can try adding -lmvec to the custom.cmake build settings to see if it fixes the second line

**Comment by jpffitch** [comment]
That munged name suggests use of a C++ compiler for a C program

  '_ZGVcN4vv_pow@@GLIBC_2.22'

Just an idea...

**Comment by ainola** [comment]
Thanks for the responses. I tried adding `-lmvec` and `-lm` to set CMAKE_C_FLAGS in Custom.cmake.ex, neither of which gave me any different output.

I should have given a little more information, apologies. here is a more verbose output of the error(s)

```
[ 79%] Building C object util/CMakeFiles/atsa.dir/atsa_main.c.o
[ 79%] Building C object frontends/CMakeFiles/csound-bin.dir/csound/sched.c.o
[ 79%] Linking C executable ../atsa
/usr/bin/ld: CMakeFiles/atsa.dir/atsa_main.c.o: undefined reference to symbol '_ZGVcN4vv_pow@@GLIBC_2.22'
/usr/lib/libmvec.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
util/CMakeFiles/atsa.dir/build.make:95: recipe for target 'atsa' failed
make[2]: *** [atsa] Error 1
CMakeFiles/Makefile2:2392: recipe for target 'util/CMakeFiles/atsa.dir/all' failed
make[1]: *** [util/CMakeFiles/atsa.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 79%] Linking C executable ../csound
[ 80%] Building CXX object interfaces/CMakeFiles/libcsnd6.dir/CsoundFile.cpp.o
[ 80%] Linking C shared module "../csound6~.pd_linux"
/usr/bin/ld: CMakeFiles/csound-bin.dir/csound/csound_main.c.o: undefined reference to symbol '_ZGVcN4vv_pow@@GLIBC_2.22'
/usr/lib/libmvec.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
frontends/CMakeFiles/csound-bin.dir/build.make:121: recipe for target 'csound' failed
make[2]: *** [csound] Error 1
CMakeFiles/Makefile2:2086: recipe for target 'frontends/CMakeFiles/csound-bin.dir/all' failed
make[1]: *** [frontends/CMakeFiles/csound-bin.dir/all] Error 2
[ 80%] Building CXX object interfaces/CMakeFiles/libcsnd6.dir/Soundfile.cpp.o
[ 80%] Built target csound6~.pd_linux
[ 80%] Building CXX object interfaces/CMakeFiles/libcsnd6.dir/csPerfThread.cpp.o
[ 80%] Linking CXX shared module ../csladspa.so
[ 80%] Linking CXX executable ../csdebugger
[ 80%] Building CXX object interfaces/CMakeFiles/libcsnd6.dir/cs_glue.cpp.o
[ 80%] Built target csladspa
[ 80%] Building CXX object interfaces/CMakeFiles/libcsnd6.dir/filebuilding.cpp.o
[ 80%] Built target csdebugger
[ 81%] Linking CXX shared library ../libcsnd6.so
[ 81%] Built target libcsnd6
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

I have tried using the following PKGBUILD: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=csound

(Another user brought it to my attention that it somehow broke despite my not updating it since July).

I've also tried a very vanilla build as per https://github.com/csound/csound/blob/develop/BUILD.md without success as well. It works on Debian Sid, but they're still on glibc 2.21 on the experimental branch (Arch is on the latest 2.22).

**Comment by vlazzarini** [comment]
I think CFLAGS are only for compilation, the error is in linking.

**Comment by ainola** [comment]
Thanks for pointing that out. I've tried both `set (CMAKE_SHARED_LINKER_FLAGS "-lmvec")` and `set (CMAKE_MODULE_LINKER_FLAGS "-lmvec"`followed by a `rm -R * ; cmake ../csound-6.05.0/ && make -j6` to no success. Is this the correct method of passing flags to cmake?

**Comment by kunstmusik** [comment]
@ainola Are you just editing the Custom.cmake.ex or are you copying it to Custom.cmake first?  Also, you can pass flags directly to cmake on the commandline, so you can use ```rm -R * ; cmake ../csound-6.05.0/ -DCMAKE_SHARED_LINKER_FLAGS=-lmvec && make -j6```

**Comment by kunstmusik** [comment]
BTW: release notes for glibc 2.22 state:

```* Added vector math library named libmvec with the following vectorized x86_64
  implementations: cos, cosf, sin, sinf, sincos, sincosf, log, logf, exp, expf,
  pow, powf.
  The library can be disabled with --disable-mathvec. Use of the functions is
  enabled with -fopenmp -ffast-math starting from -O1 for GCC version >= 4.9.0.
  Shared library libmvec.so is linked in as needed when using -lm (no need to
  specify -lmvec explicitly for not static builds).
  Visit <https://sourceware.org/glibc/wiki/libmvec> for detailed information.```

from https://www.sourceware.org/ml/libc-alpha/2015-08/msg00609.html

**Comment by ainola** [comment]
I'm sorry, I did indeed mean Custom.cmake that I copied from the .ex. I will update the comment. I get a much more verbose output but it's still the same error: Passing the flags in results in nothing different :(

**Comment by kunstmusik** [comment]
It looks like libm has come up before in the CMake build, but for lpc_export.  I would try modifying csound/util/CMakeLists.txt, and add:

```
    target_link_libraries(atsa m)
```

after the call to make_utility(atsa  atsa_main.c).  If that works, let us know and we can update it for the 6.06.0 release.

**Comment by fsateler** [comment]
Another Arch user had the same problem on irc  few days ago. He said he would file an issue, I guess he didn't :(

In any case, the problem is solved by linking several utils with -lm: atsa, csanalyze, cvanal and mixer where mentioned.

My guess is that the transitive -lm via libcsound is no longer sufficient to satisfy the math.h requirements (possibly libcsound does not use the vectorized variants?), so they need to be explicit.

I was not able to reproduce on a debian system.

**Comment by ainola** [comment]
That seems to fix it. Adding target_link_libraries($TARGET m) after the offending errors gets rid of it. That would be atsa, csanalyze, cvanal, lpc_export, and mixer-bin. It does get past those errors, but I'm stuck with another one that I can't locate: 

```
make[2]: *** [csound] Error 1
make[2]: Leaving directory '/home/ainola/Downloads/csound/cs6make'
CMakeFiles/Makefile2:2089: recipe for target 'frontends/CMakeFiles/csound-bin.dir/all' failed
make[1]: *** [frontends/CMakeFiles/csound-bin.dir/all] Error 2
```
I apologize for needing the hand-holding at this point: I'm not very well versed in c/makefiles.

@fsateler, was the user named pankid? Also, Debian with 2.22? I also couldn't reproduce on sid with 2.21 (experimental). It's my suspicion that the Arch PKGBUILD broke after the upgrade to 2.22 last month.

Once I figure exactly which lines are needed, I'll carry a patch until 6.06 is issued. Thanks for the help, everyone.

**Comment by kunstmusik** [comment]
@ainola could you build with just "make" instead of "make -j6" to see if
there is more information there about the build failure?  Usually that info
gets lost in the messages when running parallel builds.

**Comment by ainola** [comment]
```
[ 76%] Building C object frontends/CMakeFiles/csound-bin.dir/csound/sched.c.o
cd /home/ainola/Downloads/csound/cs6make/frontends && /usr/bin/cc  -DCS_DEFAULT_PLUGINDIR=\"/usr/local/lib/csound/plugins-6.0\" -DHAVE_SOCKETS -DHAVE_STRTOD_L -DHAVE_STRTOK_R -DLINUX -DNO_FLTK_THREADS -DPIPES -DUSE_LRINT -D_CSOUND_RELEASE_ -D_GNU_SOURCE -ffast-math -mfpmath=sse -msse2 -fomit-frame-pointer -W -Wall -mtune=core2 -fvisibility=hidden -DHAVE_ATOMIC_BUILTIN -DHAVE_CURL -fopenmp -I/home/ainola/Downloads/csound/csound-6.05.0/./H -I/home/ainola/Downloads/csound/csound-6.05.0/./include -I/home/ainola/Downloads/csound/csound-6.05.0/./Engine -I/home/ainola/Downloads/csound/csound-6.05.0/. -I/home/ainola/Downloads/csound/cs6make -I/home/ainola/Downloads/csound/cs6make/include -I/home/ainola/Downloads/csound/cs6make/frontends -I/home/ainola/Downloads/csound/csound-6.05.0/frontends/beats    -Wno-format -o CMakeFiles/csound-bin.dir/csound/sched.c.o   -c /home/ainola/Downloads/csound/csound-6.05.0/frontends/csound/sched.c
[ 76%] Linking C executable ../csound
cd /home/ainola/Downloads/csound/cs6make/frontends && /usr/bin/cmake -E cmake_link_script CMakeFiles/csound-bin.dir/link.txt --verbose=1
/usr/bin/cc   -ffast-math -mfpmath=sse -msse2 -fomit-frame-pointer -W -Wall -mtune=core2 -fvisibility=hidden -DHAVE_ATOMIC_BUILTIN -DHAVE_CURL -fopenmp   CMakeFiles/csound-bin.dir/csound/csound_main.c.o CMakeFiles/csound-bin.dir/csound/sched.c.o  -o ../csound -rdynamic ../libcsound64.so.6.0 -lpthread -Wl,-rpath,/home/ainola/Downloads/csound/cs6make: 
/usr/bin/ld: CMakeFiles/csound-bin.dir/csound/csound_main.c.o: undefined reference to symbol '_ZGVcN4vv_pow@@GLIBC_2.22'
/usr/lib/libmvec.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
frontends/CMakeFiles/csound-bin.dir/build.make:124: recipe for target 'csound' failed
make[2]: *** [csound] Error 1
make[2]: Leaving directory '/home/ainola/Downloads/csound/cs6make'
CMakeFiles/Makefile2:2089: recipe for target 'frontends/CMakeFiles/csound-bin.dir/all' failed
make[1]: *** [frontends/CMakeFiles/csound-bin.dir/all] Error 2
make[1]: Leaving directory '/home/ainola/Downloads/csound/cs6make'
Makefile:163: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by fsateler** [comment]
@ainola no, it was a user named rdvonz. BTW, are you the maintainer of the
pkgbuild? If so, you may want to change the prepare() sed magic with a
Custom.cmake that should be less brittle.

On 22 September 2015 at 16:58, ainola <notifications@github.com> wrote:

> That seems to fix it. Adding target_link_libraries($TARGET m) after the
> offending errors gets rid of it. That would be atsa, csanalyze, cvanal,
> lpc_export, and mixer-bin. It does get past those errors, but I'm stuck
> with another one that I can't locate:
>
> make[2]: *** [csound] Error 1
> make[2]: Leaving directory '/home/ainola/Downloads/csound/cs6make'
> CMakeFiles/Makefile2:2089: recipe for target 'frontends/CMakeFiles/csound-bin.dir/all' failed
> make[1]: *** [frontends/CMakeFiles/csound-bin.dir/all] Error 2
>
> I apologize for needing the hand-holding at this point: I'm not very well
> versed in c/makefiles.
>
> @fsateler <https://github.com/fsateler>, was the user named pankid? Also,
> Debian with 2.22? I also couldn't reproduce on sid with 2.21
> (experimental). It's my suspicion that the Arch PKGBUILD broke after the
> upgrade to 2.22 last month.
>
> Once I figure exactly which lines are needed, I'll carry a patch until
> 6.06 is issued. Thanks for the help, everyone.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/csound/csound/issues/526#issuecomment-142401620>.
>



-- 

Saludos,
Felipe Sateler

**Comment by fsateler** [comment]
https://github.com/csound/csound/blob/develop/include/sysdep.h#L133
https://github.com/csound/csound/blob/develop/include/sysdep.h#L159

These are in a public header. Would these macros be instantiated under some
conditions?


On 22 September 2015 at 17:12, ainola <notifications@github.com> wrote:

> [ 76%] Building C object frontends/CMakeFiles/csound-bin.dir/csound/sched.c.o
> cd /home/ainola/Downloads/csound/cs6make/frontends && /usr/bin/cc  -DCS_DEFAULT_PLUGINDIR=\"/usr/local/lib/csound/plugins-6.0\" -DHAVE_SOCKETS -DHAVE_STRTOD_L -DHAVE_STRTOK_R -DLINUX -DNO_FLTK_THREADS -DPIPES -DUSE_LRINT -D_CSOUND_RELEASE_ -D_GNU_SOURCE -ffast-math -mfpmath=sse -msse2 -fomit-frame-pointer -W -Wall -mtune=core2 -fvisibility=hidden -DHAVE_ATOMIC_BUILTIN -DHAVE_CURL -fopenmp -I/home/ainola/Downloads/csound/csound-6.05.0/./H -I/home/ainola/Downloads/csound/csound-6.05.0/./include -I/home/ainola/Downloads/csound/csound-6.05.0/./Engine -I/home/ainola/Downloads/csound/csound-6.05.0/. -I/home/ainola/Downloads/csound/cs6make -I/home/ainola/Downloads/csound/cs6make/include -I/home/ainola/Downloads/csound/cs6make/frontends -I/home/ainola/Downloads/csound/csound-6.05.0/frontends/beats    -Wno-format -o CMakeFiles/csound-bin.dir/csound/sched.c.o   -c /home/ainola/Downloads/csound/csound-6.05.0/frontends/csound/sched.c
> [ 76%] Linking C executable ../csound
> cd /home/ainola/Downloads/csound/cs6make/frontends && /usr/bin/cmake -E cmake_link_script CMakeFiles/csound-bin.dir/link.txt --verbose=1
> /usr/bin/cc   -ffast-math -mfpmath=sse -msse2 -fomit-frame-pointer -W -Wall -mtune=core2 -fvisibility=hidden -DHAVE_ATOMIC_BUILTIN -DHAVE_CURL -fopenmp   CMakeFiles/csound-bin.dir/csound/csound_main.c.o CMakeFiles/csound-bin.dir/csound/sched.c.o  -o ../csound -rdynamic ../libcsound64.so.6.0 -lpthread -Wl,-rpath,/home/ainola/Downloads/csound/cs6make:
> /usr/bin/ld: CMakeFiles/csound-bin.dir/csound/csound_main.c.o: undefined reference to symbol '_ZGVcN4vv_pow@@GLIBC_2.22'
> /usr/lib/libmvec.so.1: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status
> frontends/CMakeFiles/csound-bin.dir/build.make:124: recipe for target 'csound' failed
> make[2]: *** [csound] Error 1
> make[2]: Leaving directory '/home/ainola/Downloads/csound/cs6make'
> CMakeFiles/Makefile2:2089: recipe for target 'frontends/CMakeFiles/csound-bin.dir/all' failed
> make[1]: *** [frontends/CMakeFiles/csound-bin.dir/all] Error 2
> make[1]: Leaving directory '/home/ainola/Downloads/csound/cs6make'
> Makefile:163: recipe for target 'all' failed
> make: *** [all] Error 2
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/csound/csound/issues/526#issuecomment-142405325>.
>



-- 

Saludos,
Felipe Sateler

**Comment by ainola** [comment]
@fsateler, you're completely right, and it's something I meant to do long ago.

The module install dirs are easy enough to set in Cmake.custom, but unless there's some other magic you can recommend, sed is the only way to remove the execute_process that wants to install system files in ~/.local/lib/python3.4/site-packages47. I'd love a better solution to get rid of it as I realize the sed command is not particularly reliable long-term.

**Comment by fsateler** [comment]
@ainola you should be able to set it in Custom.cmake, because the execute_process is run before including that file, so whatever value you set there, should override the previous value. As a matter of fact, that is what I do in the debian package (this file is preprocessed before using):

http://sources.debian.net/src/csound/1:6.05~dfsg1-5/debian/Custom.cmake/

**Comment by kunstmusik** [comment]
@ainola Could you try adding:

target_link_libraries(csound-bin m)

after the definition of the csound-bin target in csound/frontends/CMakeLists.txt?

**Comment by kunstmusik** [comment]
@ainola Sorry to ping about this, but we're getting ready to setup a release branch for 6.06.0, but we want to make sure have changes to fix this issue before we release.  Could you check the target_link_libraries(csound-bin m) ?

**Comment by ainola** [comment]
@kunstmusik, apologies, the last two days have been long at work. I just got home. Had I known there was a rush to get 6.06 out, I would have replied sooner: Yes, it gets me yet further along to link csound-bin to m, but I was figuring out this next one:

```
Scanning dependencies of target dnoise
[ 86%] Building C object util/CMakeFiles/dnoise.dir/dnoise_main.c.o
[ 86%] Linking C executable ../dnoise
/usr/bin/ld: CMakeFiles/dnoise.dir/dnoise_main.c.o: undefined reference to symbol '_ZGVcN4vv_pow@@GLIBC_2.22'
/usr/lib/libmvec.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
util/CMakeFiles/dnoise.dir/build.make:95: recipe for target 'dnoise' failed
make[2]: *** [dnoise] Error 1
CMakeFiles/Makefile2:2503: recipe for target 'util/CMakeFiles/dnoise.dir/all' failed
make[1]: *** [util/CMakeFiles/dnoise.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by kunstmusik** [comment]
@ainola all good!  I seems like more libm issues.  Could you try adding
more target_link_libraries calls in util/CmakeLists.txt ? (in this case for
dnoise)

**Comment by ainola** [comment]
Yeah, now that I sat down and looked at it, I see how obvious the solution is. I played a little whack-a-mole but it's compiled now. I had to link every single target except het_import in util/CMakeLists.txt.

`scsort` and `extract` also needed to be linked in util1/CMakeLists.txt

And I also had to add `target_link_libraries(csound-bin m)` to csound/frontends/CMakeLists.txt, as noted above

**Comment by kunstmusik** [comment]
@ainola I managed to get an Arch system setup in Virtualbox and was able to reproduce your build problem. I ended up using a different approach by modifying to add libm to the make_utility function, csound-bin, and mixer-bin.  That worked for building for me on Arch, OSX, and Ubuntu 14.04.
