### ISSUE TITLE
Usage of csoundEvalCode

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#528]
Advance apologies if I’m doing something bone-headed. I’m trying to include a binding for [`csoundEvalCode`](https://github.com/csound/csound/blob/develop/include/csound.h#L641) in a [Node.js Addon](https://github.com/nwhetsell/csound-api), and I can’t seem to use it without causing a segmentation fault. A [search of uses in the Csound repository](https://github.com/csound/csound/search?q=csoundEvalCode) didn’t turn up many examples of usage.

I made a test Xcode project based on the [example code](https://github.com/csound/csound/blob/develop/include/csound.h#L637) in csound.h that consists almost entirely of:

```c
#include <csound.h>

int main(int argc, const char *argv[]) {
    CSOUND *csound = csoundCreate(NULL);
    char *code = "i1 = 2 + 2 \n return i1 \n";
    MYFLT retval = csoundEvalCode(csound, code);
    printf("%f", retval);
    return 0;
}
```

Running this also produces a segmentation fault at the call to `csoundEvalCode`. I don’t know if it’s helpful, but I put a ZIP archive of this Xcode project at https://dl.dropboxusercontent.com/u/21723817/csoundTest.zip.

How should one use `csoundEvalCode`?

**Comment by vlazzarini** [comment]
You have not started csound. Call csoundStart() before trying to evaluate the code. 
Here's a Python example:
```
>>> import csnd6
>>> cs = csnd6.Csound()
time resolution is 1000.000 ns
virtual_keyboard real time MIDI plugin for Csound
0dBFS level = 32768.0
Csound version 6.05 beta (double samples) Sep 21 2015
libsndfile-1.0.25
>>> code = "i1 = 2 + 2 \n return i1 \n"
>>> cs.Start()
rtaudio: PortAudio module enabled ... 
using callback interface
rtmidi: PortMIDI module enabled
--Csound version 6.05 beta (double samples) Sep 21 2015
graphics suppressed, ascii substituted
0dBFS level = 32768.0
orch now loaded
audio buffered in 1024 sample-frame blocks
writing 2048-byte blks of shorts to test.aif (AIFF)
SECTION 1:
0
>>> cs.EvalCode(code)
4.0
>>> 
```
