### ISSUE TITLE
Error: define environment variable RAWWAVE_PATH

### ISSUE THREAD

**Issue by rorywalsh** [csound/csound#530]
I think this 'error' is rather misleading:

Error: define environment variable RAWWAVE_PATH

Should it not be a warning considering it doesn't prevent Csound from running?

**Comment by vlazzarini** [comment]
it's a warning in Csound 6.06

**Comment by rorywalsh** [comment]
Pardon me. I thought I was using the latest code base.

**Comment by jpffitch** [comment]
It is a warning in 6.06 and develop
==John

**Comment by vlazzarini** [comment]
```
$ csound
virtual_keyboard real time MIDI plugin for Csound
WARNING: STK opodes not available: define environment variable RAWWAVE_PATH
(points to rawwaves directory) to use STK opcodes.
0dBFS level = 32768.0
Csound version 6.06 (double samples) Sep 29 2015
```

**Comment by rorywalsh** [comment]
I believe you ;)
