### ISSUE TITLE
Topics at the round table ICSC 2015

### ISSUE THREAD

**Issue by anton-k** [csound/csound#533]
## Topics at the round table ICSC 2015

The main theme for the round table was the attraction of newcomers.
The Csound is magic and we know it but how can we explain it to others.

There is confusion in learning resources, no showcases, links to video tutorials.
The thing that can capture the attention is portability. Lots of systems
can interact with Csound. we can catch the eye of newcomer with it. 

terms: the site - is official Csound's github site

---
- Csound strong points: Portability
  
  I think that to attract the novices we need to advertise the things
  that nobody can do better than Csound. My impression of the conference
  is that right now the killer feature of Csound is the Portability. 
  Csound can run anywhere and used with anything. 
  iOS, Android, any desktop, web-browser, ipython spread sheets, Haskell, Clojure, 
  RPi, custom effect processors, creating distributed audio systems
  or environments for collaborative composition -- csound can create sound
  for them all. We need to explain it to newcommers and catch their attention with it.
  I think it would be nice to have Carusel widget on the web site that higlights
  this point. Smth like:
  
  http://audiokit.io/
  
  http://snapframework.com/
- Challenge for non-programmer users to update the info on the official Csound site.
  We need a guide for non-programmers to submit github pull requests.
  
  Steven said that the site is hosted on github
  and everyone can update it (add news, articles, learning resources).
  But nobody seems to do it. 
  
  Tarmo replied that the procedure is unclear to him. 
  
  The site is updated with pull requests the procedure
  is pretty obvious for the programmer since the
  git is a modern standard for collaborative coding.
  
  So we need to explain to non-programmers how to use the Github
  pull requests process. DrB mentions that he wants to learn
  by watching the video of it.
- Confusion with two sites
  
  We've got `csounds.com` and also github site which is official one.
  Students that learn Csound are often confused with the two sites.
  Where should I learn the Csound? 
  
  DrB says that he wants to keep the csounds.com alive since
  he can loose so many information on Csound (17 Gb of Csound resouces, maybe I'm wrong with the figure).
  But we can host it on github and make redirects. It's no that hard
  and eliminates the confusion.
- The official site is not so pretty. it has this yet another open-source trash feel to it
  
  Can we create a better design for the site? Any web-designers out there?
  Can we reuse by any chance the ICSC 20015 website design
  to make the official site more attractive.
- Confusion with Csound releases
  
  It's not clear for the users where and how to install the Csound.
- Showcases of Csound on the site. Csound in Action approach
  
  There were so many cool  projects going with Csound
  that I'm unaware of. It would be nice to be able to
  see what people are doing with Csound at the site.
  
  That's how we can attract the newcomers. That's how
  they can appreciate the powers of csound.
- Learning resources.
  
  For newcomer it's hard to guess where should (s)he learn 
  the Csound. I think it's better to promote the FLOSS manual
  as the best place to learn (we need to have a link at the official site)
  and also we can provide links to the books or online materials and examples. 
- Learn by video
  
  Is it possible to create screencasts of what can be done with Csound.
  Actually there is online video tutorial on Csound 
  
  http://www.youtube.com/watch?v=KxyBTr0eamQ
  
  Maybe we should link to it on the site or even better to 
  integrate to the site. So that users are not distracted by other things 
  that they can see on youtube. So that they can see only 
  original 12 or more video posts. 
- We need more musical examples
  
  Sine waves are great but it's hard to convince the novice with them.
  We need a book or a learning material that can explain the user
  how to create drums, pads, bases, leads with Csound.  Smth like
  manuals for Circle and Thor synths
  
  http://www.futureaudioworkshop.com/circle/tutorials/tutorial1
  
  https://www.propellerheads.se/substance/discovering-reason/index.cfm?article=part19&fuseaction=get_article
  
  like csound demystified
- Learn by interaction
  
  It would be nice to have the Csound playground.
  Some web-page where users can edit and listen to Csound without 
  the need to install compiler. 
  
  Steven says that there is such a site. He has created 
  a first example and wanted people to collaborate but nobody
  seems to did a thing. 
  
  Anton says that's the thing doesn't works for him
  I need to install or activate pNaCl which he couldn't 
  figure out how to do it.
  
  The Rory says that there is JavaScript csound without
  any dependencies. Maybe it's better to move the 
  learning material to pure JS solution.
- Learn by listening
  
  It would be nice if learning resources could be played online.
  There is a text of the example and near the text we can see the
  play/stop button trigger the playing. 
  
  Often users have not so much time to copy things
  into editor, download possible dependent audio files
  to execute the csound example.
  
  It's nice to supply FLOSS manual and the Reference manual with 
  this facility.
  
  It can be done with rendered audio files or it can be done 
  with pure JS. The rendered audio requires a lot of routine work (and space on the server)
  the pure JS can be done with creating a Csound example widget
  and adding global css info. Maybe it's better to do it with JS.
  
  Here is an example:
  
  http://www.futureaudioworkshop.com/circle/tutorials/tutorial1
  
  It's really helps to see the reason (or to see no reason) 
  in diving deeper into the thing that is explained.
- Taking responsibilities 
  
  Joachim has mentioned that it's good to talk but to change things
  we need to do smth concrete. We need to take the responsibility
  to support ideas with actions. 
- Online forums with categories.
  
  It's hard to use the mailing list because the questions on
  different topics are mixed up. 
  
  If I'm novice it's hard to ask for me when I see all the
  stuff about implementing a new feature or parallel execution
  performance. My question seems to be unrelated to the thing.
  But it is related and John Ff sends the reminder on it.
  
  It would be nice to have categories for discussion
  
  Csound for developers
  
  Csound for Newcomers
  
  Csound's showcases (music, installations, performances)
  
  Csound for DSP engineers 
  
  Csound for musicians/performers
  
  Csound and other tech stuff (Mobiles, Game engines, other languages)
  
  Possible solution is Goolge groups.
  But there can be reaction from the users (also Victor L, John F) that like to
  use the mailing list (no need to go to a separate site, and check it out).
  But we can explain that google-groups can also be used that way
- Stackoverflow tag for Csound
  
  Every language has it so why do we need to ignore this opportunity to help people.
- Make Cabbage built in UI for Csound. Switching the FLTK with Cabbage
  
  Cabbage is much nicer than FLTK. Can we ship the csound with cabbage support?
  Steven says that he wants to separate the csound as audio engine from
  front ends. There is no best front end and we should let the users 
  choose the right front end.
  
  Also front ends can ship with Csound not other ways.
- CsoundQt built-in editor problem
  
  CsoundQt is such a great thing to use. But there is one thing that
  annoys many users. The CsoundQt forces the musicians to use it's own editor.
  But there are much better ways to edit the text (Sublime text, Vim, Emacs, Idea IntelliJ).
  Can we separate the concepts? Use CsoundQt for it's great widgets and 
  let the musician to use his own favorite editor.
  
  Right now there is no other way than to copy and paste the text
  to CsoundQt. But it becomes harder to edit it. 
- Issue tracker
  
  There are better ways than Github to do it. Can we use them?
  Do we need it?  
  
  trac (http://trac.edgewall.org/) or
  
  Attlassian Confluence JIRA
- OSC based Csound API
  
  Can we make explicit support for OSC in the Csound API. 
  With support for livecoding.  So that we can use OSC to send the 
  new instruments to Csound object (not just messages).
- Opcodes with named parameters
  
  It would be nice to be able to use named parameters. 
  The python things like:
  
  filter(q = 0.5, centerFrequency = 1500, asig)
- Namespaces/modules for Csound
  
  The namespaces can help the user safely share their code.
  With modules we can import someone elses instruments.
  There is a Macro solution with include. But it can break the
  code by exposing the global names/tables. So it would be
  great to have the local instrmnets or UDOs that can be safely
  imported to the Csound code.
  
  With modules people can create and distribute they instruments/UDOs.
- Csound packages distribution standard
  
  The next question is to define Csound distribution standard (Csound packages).
  It's very complicated question I guess.
  There is a collection of UDOs on the Csound site. It would be nice to be able
  to install the Csound functionality in the way Node packages are distributed.
  If we have the namespaces and modules in Csound. Is it poossible to create
  a tool like `npm` in the node or `sbt` in scala or leiningen in Clojure. 
  That gives the user ability to reuse Csound code. 
- Creating opcodes out of Csd files. Emulating PD-abstractions in Csound
  
  The primary tool of abstraction for Csound is UDO. With UDO's we can
  create a musical algorithm. It's like defining a function in the Python with `def`.
  But UDO are restricted. We can use only opcodes in the UDOs. 
  We can put into UDO only things that can be put into an instrument definition.
  
  But what if we could create a UDO out of complete Csound file. 
  Just like we can do it in the PD or Max. Then the UDO can contain
  an Orchestra and the Score. it becomes very powerful audio generator.
  Imagine that you want to use the existing Csound composition in your own.
  Then tyou can use it as an opcode and trigger it in your code.
  
  The Csound already has the proper interface for it. 
  We can treat the `ins` as input and `outs` as outputs for the UDO. 
  That way we don't need to change anything in the existent Csound code (csd).
  we can use old csd's. But this limits us with using only signals.
  What if we want to have CSD that takes in ftable as parameter or a string.
- Welcome to Montevideo  for the next Csound Conference 2017

**Comment by nwhetsell** [comment]
This may touch on the fourth bullet (improving the official website) and learning resources: I wrote a Csound lexer for the [Pygments](http://pygments.org) syntax highlighter, and it was merged into Pygments’ main branch recently. [Here](https://dl.dropboxusercontent.com/u/21723817/csound.html) is a sample output from the lexer.

The lexer isn’t yet part of a Pygments release, so if you want to try the lexer, you’ll need to clone the [Pygments repository](https://bitbucket.org/birkenfeld/pygments-main), using either [SourceTree](https://www.sourcetreeapp.com) or Mercurial from the command line:
```sh
hg clone http://bitbucket.org/birkenfeld/pygments-main pygments
```
To try the lexer, `cd` to `pygments-main` and run
```sh
./pygmentize -O full -f html -o csound.html tests/examplefiles/test.orc
```
to create an HTML file from `tests/examplefiles/test.orc`.

Note that, very unfortunately, while I wrote a lexer to handle CSD files, it was causing a Pygments test to fail, so it’s commented out. If you want to try lexing CSD files, you’ll have to edit a bit of Python:

1. Open the Csound lexer at `pygments-main/pygments/lexers/csound.py`
2. Edit the assignment to `__all__` near the top of the file to say

    ```python
    __all__ = ['CsoundScoreLexer', 'CsoundOrchestraLexer', 'CsoundDocumentLexer']
    ```

3. Uncomment `CsoundDocumentLexer` (and the `import` statements above it) near the bottom of the file.

4. `cd` to `pygments-main` and run

    ```sh
    make mapfiles
    ```

5. Lex your CSD file using, for example,

    ```sh
    ./pygmentize -O full -f html -o csd.html my.csd
    ```

[Here](https://dl.dropboxusercontent.com/u/21723817/csd.html) is a sample output made from the example at http://www.csounds.com/manual/html/lua.html.

**Comment by kunstmusik** [comment]
Closing as stale issue. Lots of great ideas here and some still relevant. If anyone comes to this issue and sees something that hasn't been addressed since this issue was written, I'd encourage filing new individual issues to track work for those.
