### ISSUE TITLE
jacko opcodes segfault

### ISSUE THREAD

**Issue by genell** [csound/csound#534]
Running the jacko.csd example file from the csound manual causes a segfault, on at least Linux and OSX.

**Comment by jpffitch** [comment]
Any chance of an example of the crash that does not require so many external systems?

**Comment by gogins** [comment]
I could reproduce the error, but it is not a bug. The example requires careful configuration.

When I took care to configure my system as follows, Csound ran jacko.csd without crashing and produced the correct soundfile.

System:
mkg@Sun-Yukong:~$ uname -a
Linux Sun-Yukong 3.16.0-73-generic #95~14.04.1-Ubuntu SMP Thu Jun 9 08:00:04 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Compiler:
mkg@Sun-Yukong:~$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.3' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 

Execute "sudo apt-get update"
Execute "sudo apt-get install jackd"
Execute "sudo apt-get install aeolus"
Execute "sudo dpkg-reconfigure -p high jackd2" to configure jackd2 for RT audio.
In the Csound source directory execute "git pull"
In the Csound build directory execute "cmake ../csound; make clean; make -j6"
Run qjackctl and configure for 128 frame buffer and 48 KHz sample rate for real-time audio.
Execute "aeolus". When its window opens, pull some stops and assign them to MIDI channel 1.
Execute "csound jacko.csd".
In the QJackCtl patchbay, you may need to manually connect Csound's audio output to the system audio input. 

The soundfile should be written with a reasonable audio level.
