### ISSUE TITLE
readfi segfaults on printf

### ISSUE THREAD

**Issue by Oeyvind** [csound/csound#535]
The manual example on readfi segfaults when trying to read a line with printf
(tested on windows 7, csound 6.05 Apr 24 2015).

It works fine until the line 
printf_i  "Line %d: %s", iLineNum, iLineNum, Sline

If I try to read another file (not containing printf), it will complete without error.
(make a copy of the readfi.csd file, delete the printf line, and read that file with readfi)

The example from the manual:
<CsoundSynthesizer>
<CsOptions>
-n
</CsOptions>
<CsInstruments>
instr 1
    Swd pwd
        printf_i "Working directory is '%s'\n", 1, Swd
        prints "Reading myself =):\n"
read:
Sline, iLineNum readfi "readfi.csd"
        printf_i  "Line %d: %s", iLineNum, iLineNum, Sline
        if iLineNum != -1 igoto read
endin
</CsInstruments>
<CsScore>
i1 0 0.1
e
</CsScore>
</CsoundSynthesizer>

**Comment by kunstmusik** [comment]
The example seems off, as only two %'s are used in the format string, but
three arguments are given.  However, this scenario should give an error and
not segfault.

**Comment by vlazzarini** [comment]
The code is correct, first argument is a trigger.

**Comment by vlazzarini** [comment]
It looks like printf might be getting confused as the formatting string is not escaped.

**Comment by jpffitch** [comment]
Victor is correct  The code prints the line with a printf family that interprets %d and %s so this is a programmer error.  I guess we could attempt better checking of arguments etc to printf

**Comment by Oeyvind** [comment]
Ok. But the csd is from the manual...
14. okt. 2015 17.22 skrev "John ffitch" <notifications@github.com>:

**Comment by jpffitch** [comment]
I tried to delete tat message -- I ws wrong.  I am deep in gdb at present 
but I tink the error is in printf with %s which should not interpret the % 
recursively.
==John

**Comment by vlazzarini** [comment]
that is what I meant. The recursion is tripping printf

**Comment by jpffitch** [comment]
Fixed in git

**Comment by Oeyvind** [comment]
Excellent, thanks so much!

2015-10-14 20:39 GMT+02:00 John ffitch <notifications@github.com>:
