### ISSUE TITLE
OSC operations

### ISSUE THREAD

**Issue by jpffitch** [csound/csound#537]
Need to allow OSClisten to accept tables and for both OSClisten and OSCsend to deal with arrays.
And the use of code T for tables if not compatible with other OSC codes; needs to change to an unused code.

**Comment by jpffitch** [comment]
OSCsend of arrays written, not tested, using code A
Code for tables changed to G (from Gen)

**Comment by joachimheintz** [comment]
let me know when you want me to test.
regards -
	joachim

**Comment by jpffitch** [comment]
Code to send and receive arrays seems to work using code A; only tested with 1d arrays but should work for others.  Sorry for delay but it turned out to be rather delicate.  

examples
Write:
#define IPADDRESS       # "localhost" #
#define PORT            # 47120 #
instr       1
  ka[]      fillarray  1,2,3,4,5
  OSCsend   0, $IPADDRESS, $PORT, "/test", "A", ka
endin

Read
#define IPADDRESS       # "localhost" #
#define PORT            # 47120 #
  gilisten  OSCinit   $PORT
 instr       1
  ka[]      fillarray  100,200
  kk        OSClisten   gilisten, "/test", "A", ka
  printks2  "here%d", kk
  printk2   ka[1]
endin


Will do tables next

**Comment by jpffitch** [comment]
Sending and receuiving tables now seems to run (type G)
Still to do is string arrays

Do you also need sending/receiving audio?

**Comment by rpinkston** [comment]
Sending and receiving audio would be very useful! And for debugging purposes, in particular, having a pair of basic updsend and udpreceive opcodes (i.e., not tied to OSC) that could send and receive strings would be invaluable.

Thanks for working on this, John!

RP

________________________________

**Comment by jpffitch** [comment]
Audio added in OSC (in git) with code a.  Not tested and very little 
checking.  Will improve soon I hope

**Comment by jpffitch** [comment]
Russell, i thought socksend would transmit a string (code looks that way) and strecv receives strings (silly name -- should be sockrecv).  Do they not work?

**Comment by rpinkston** [comment]
Nice. I haven't tried them, but I will. Agree that strecv should be named
sockrecv. RP

 

  _____
