### ISSUE TITLE
What’s the correct way to get messages about orchestra compilation using Csound’s API?

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#540]
I’m using Csound’s API on OS&nbsp;X to repeatedly compile orchestras (to do, for example, linting). When I do this, the line numbers where syntax errors occur are sometimes unexpected. They’re either very large, negative, or off by one. Below is a short command-line program with an example of what I’m doing. Is this the right way to do this?

```c
#include <csound.h>

int main(int argc, const char *argv[]) {
    for (int i = 0; i < 100; i++) {
        CSOUND *Csound = csoundCreate(NULL);
        csoundCreateMessageBuffer(Csound, 0);
        csoundCompileOrc(Csound, "x\n");
        csoundCleanup(Csound);
        
        while (csoundGetMessageCnt(Csound) > 0) {
            if (strncmp(csoundGetFirstMessage(Csound), "\nerror:", 7) == 0) {
                csoundPopFirstMessage(Csound);
                int line;
                sscanf(csoundGetFirstMessage(Csound), " line %d", &line);
                if (line != 2)
                    printf("\n***\nline = %d, expected 2\n***\n\n", line);
            }
            csoundPopFirstMessage(Csound);
        }
        
        csoundDestroyMessageBuffer(Csound);
        csoundDestroy(Csound);
    }
    
    return 0;
}
```

**Comment by vlazzarini** [comment]
No: you should check for the return value of cdoundCompile, csoundPerform etc . Zero means no errors, and you can proceed then.

**Comment by nwhetsell** [comment]
I’m trying to show were compilation errors occur in a text editor, which requires getting messages off of a message buffer even (indeed especially) when `csoundCompileOrc` doesn’t return `CSOUND_SUCCESS`. Does this mean Csound’s API can’t be used for this?

**Comment by vlazzarini** [comment]
AFAIK, CsoundQT does that. The reason for my comment is that in your code example you don't check for the return value of csoundCompileOrc(). Also calling csoundCleanup() after the compilation will probably interfere with what you want to do. This function should only be called after the end of performance.

**Comment by nwhetsell** [comment]
If you can point me to CsoundQt’s source code, I’m happy to take a look. The link to the source code at http://qutecsound.sourceforge.net/pages/develop.html (to https://sourceforge.net/p/qutecsound/code/ci/master/tree/) appears to be dead. http://sourceforge.net/p/csoundqt/code/ci/master/tree/ doesn’t work either.

Sorry, I’m not sure why it’s necessary to check the return value of `csoundCompileOrc` in this particular case. The code example repeatedly attempts to compile `"x\n"`, and `csoundCompileOrc` returns `CSOUND_ERROR` every time because `"x\n"` isn’t a valid orchestra. The purpose of attempting to compile `"x\n"` is to put messages about syntax errors on the message buffer.

The call to `csoundCleanup` seems to be suggested in the [Csound API documentation of `csoundCreateMessageBuffer`](https://csound.github.io/docs/api/group__MESSAGES.html#ga01f4b4e4baabcd74c36500a4d27f776b):

> You will generally want to call [csoundCleanup()](https://csound.github.io/docs/api/group__PERFORMANCE.html#ga81289d7daf033349d8b36aa03c528ea4) to make sure the last messages are flushed to the message buffer before destroying Csound.

Flushing the last messages seemed like a good idea. At any rate, I still see unexpected line numbers in messages from the message buffer after removing the call to `csoundCleanup`.

**Comment by vlazzarini** [comment]
CsoundQt is in github now afaik.

**Comment by vlazzarini** [comment]
I had a look at your problem, and I see that Csound reports line 1 most times, but at certain
times, it prints out garbage. If there is only one or a few iterations, it seems to be OK, as
line 1 is the correct number (x is in line 1), but I am suspecting some
memory issue now that is generating the garbage. 
I will need to look into this.

**Comment by nwhetsell** [comment]
Okay, thanks.

I could be wrong about this, but line 2 may be correct, if unintuitive. When an unexpected token is a `NEWLINE`, Csound seems to report the line after the newline as having the issue. If you instead compile `"x y\n"`, Csound reports line 1 most of the time, but sometimes 0, and sometimes garbage.

**Comment by mantaraya36** [comment]
Here:

https://github.com/mantaraya36/CsoundQt/blob/master/src/csoundengine.cpp#L832

https://github.com/mantaraya36/CsoundQt/blob/master/src/csoundengine.cpp#L124

https://github.com/mantaraya36/CsoundQt/blob/master/src/csoundengine.cpp#L1145

You can see that I use the new message buffer method when Csound 6 is used
and the old message callback method for Csound 5.
