### ISSUE TITLE
Compiling orchestra with unterminated string and function macro definition causes crash

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#541]
When using Csound’s API, compiling an orchestra that contains an unterminated string followed by a function-like macro definition appears to cause a crash on OS&nbsp;X. Here is a code example illustrating the issue:

```c
#include <csound.h>

int main(int argc, const char *argv[]) {
    CSOUND *Csound = csoundCreate(NULL);
    csoundCompileOrc(Csound, "prints \"\n"
                             "#define MACRO(ARGUMENT) #$ARGUMENT#\n");
    return 0;
}
```

I’m only able to produce this using `csoundCompileOrc`. Compiling, from the command line, an orchestra file containing

```
prints "
#define MACRO(ARGUMENT) #$ARGUMENT#
```

doesn’t appear to produce a crash. The crash seems to occur whether or not `prints` is included.

**Comment by jpffitch** [comment]
Surethis is dsame as 542 so closing
