### ISSUE TITLE
Parser increments line number when reporting syntax error followed by newline

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#544]
First, note that Csound appears to report errors in orchestras using 0-based line numbering.

If I syntax-check

```csound
if 1 == 1 then + -
endif
```

by running in a Terminal

```sh
csound --syntax-check-only --orc PlusMinus.orc
```

then Csound reports the error in line&nbsp;0:

```
error: syntax error, unexpected '+', expecting NEWLINE  (token "+ ") from file PlusMinus.orc (1)
 line 0:
>>>if 1 == 1 then +  <<<
Parsing failed due to invalid input!
```

If I instead syntax-check

```csound
if 1 == 1 then +
endif
```

(note the absence of the minus sign following the plus sign) then Csound reports the error in line&nbsp;1:

```
error: syntax error, unexpected '+', expecting NEWLINE  (token "+
") from file Plus.orc (1)
 line 1:
>>>if 1 == 1 then + <<<
Parsing failed due to invalid input!
```

I’d expect the line number to be 0 in both cases.

**Comment by jpffitch** [comment]
Line numbers are 1-based and the code is lagely rewritten.  Please test again
But the error is not detected until the \n so line number is incremented

**Comment by nwhetsell** [comment]
I’m no longer able to devote time to this issue. If this is indeed a bug, Csound’s contributors might be better off creating a [CTest](https://cmake.org/Wiki/CMake/Testing_With_CTest) test case for it.

**Comment by jpffitch** [comment]
I can reproduce but at present cannot see any explanation.  I suspect it is just reading ahead
