### ISSUE TITLE
Strings not allowed in subinstr opcode

### ISSUE THREAD

**Issue by berntisak** [csound/csound#547]
Strings doesn't seem to be allowed in the subinstr opcode like they are in normal score lines.

This works:
        
        i "Reverb" 0 10 "ReverbOne" 0.5 0.9 6000

This doesn't work:

        aOutL, aOutR subinstr "Reverb", "ReverbOne", 0.5, 0.9, 6000

I get this error:
 
*        error:  Unable to find opcode entry for 'subinstr' with matching argument types:
         Found: aa subinstr SSccc
         Line: 36
          from file Main.csd (1)
         Parsing failed to syntax errors

Whole files supplied below:

**Reverb.csd**

```
instr Reverb

	kRev_Mix init 0.5
	kRev_Decay init 0.85
	kRev_Cutoff init 7000

	kRev_Mix = p5
	kRev_Decay = p6 
	kRev_Cutoff = p7

	SchnName strget p4
	Sleft sprintf "%s_L", SchnName
	Sright sprintf "%s_R", SchnName

	aL chnget Sleft
	aR chnget Sright

	aReverbL, aReverbR reverbsc aL, aR, kRev_Decay, kRev_Cutoff

	aOutL = (aL * (1-kRev_Mix)) + (aReverbL * kRev_Mix) 
	aOutR = (aR * (1-kRev_Mix)) + (aReverbR * kRev_Mix) 

        a0 = 0
	chnset a0, Sleft
	chnset a0, Sright

	outs aOutL, aOutR

endin
```

**Main.csd**
```
<CsoundSynthesizer>
<CsOptions>
-odac 
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 16
nchnls = 2

#include "Reverb.csd"


instr 1

	aL, aR ins

	aOutL, aOutR subinstr "Reverb", "ReverbOne", 0.5, 0.9, 6000

	outs aOutL, aOutR


endin

</CsInstruments>

<CsScore>
i1 0 86400
i "Reverb" 0 10 "ReverbOne" 0.5 0.9 6000
</CsScore>

</CsoundSynthesizer>
```

**Comment by vlazzarini** [comment]
I've got this working, but need just to check the generality of the approach.

**Comment by vlazzarini** [comment]
fixed in git.
