### ISSUE TITLE
Create csoundCompileCsdText function.

### ISSUE THREAD

**Issue by gogins** [csound/csound#549]
Provide a function in the Csound API to compile a CSD from a string of text in memory, rather than from a file, similar to the csoundCompileOrc function. The signature of this function should be int csoundCompileCsdText(CSOUND *csound, const char *csdText) and it should appear in all API wrappers including JavaScript. The parameters section of the CSD file should be parsed and applied. To actually perform the compiled CSD, csoundPerform() must then be called.

**Comment by nwhetsell** [comment]
I second this, for what it’s worth. For consistency with `csoundCompileOrc` (which compiles an orchestra stored in a `char *`), it might be worth using `csoundCompileCsd` for compiling CSD strings and adding a `csoundCompileCsdAtPath` function. (This will break code that currently uses `csoundCompileCsd`, though.) It may also be possible to have `csoundCompileCsd` do both—if its `char *` argument is a path, try to compile a CSD file at that path. If not, try to compile the `char *` itself.

**Comment by gogins** [comment]
I implemented this in the "C" API and in csound.hpp and csound.cpp. I tested it on WIndows with the MinGW build and the LuaJIT wrapper. It needs to be exposed in the JavaScript interfaces now.

**Comment by gogins** [comment]
I did expose this in the Android for Csound JavaScript interface, but it doesn't do much good as I don't find a way to call this at the right time to actually get a performance.
