### ISSUE TITLE
Calling csoundCompileCsd shows window created by FLpanel

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#555]
Running

```c
#include <csound.h>

int main(int argc, const char *argv[]) {
    CSOUND *Csound = csoundCreate(NULL);
    csoundCompileCsd(Csound, "path/to/FLxyin.csd");
    return 0;
}
```

where FLxyin.csd (which is based on the example [here](http://www.csounds.com/manual/html/FLxyin.html#idp44444976)) contains

```
<CsoundSynthesizer>
<CsInstruments>
// This is based on
// http://www.csounds.com/manual/html/FLxyin.html#idp44444976
// by Andrés Cabrera.
FLpanel "FLxyin", 200, 100, -1, -1, 3
FLpanelEnd
FLrun
</CsInstruments>
<CsScore>
e
</CsScore>
</CsoundSynthesizer>
```

briefly shows the window created by [`FLpanel`](http://www.csounds.com/manual/html/FLpanel.html). Here’s a screenshot showing this:

<img width="1440" alt="screen shot 2015-11-13 at 9 04 30 am" src="https://cloud.githubusercontent.com/assets/14102861/11147667/a4b2c730-89e5-11e5-9303-3a4557c193c5.png">

This seems unexpected. Compiling the orchestra part of the same CSD file using

```c
#include <csound.h>

int main(int argc, const char *argv[]) {
    CSOUND *Csound = csoundCreate(NULL);
    csoundCompileOrc(Csound,
        "FLpanel \"FLxyin\", 200, 100, -1, -1, 3\n"
        "FLpanelEnd\n"
        "FLrun\n"
    );
    return 0;
}
```

does not show the window  created by `FLpanel`.

**Comment by jpffitch** [comment]
Not my area bt the first example runs for minimal timr while the secong 
has no per call

**Comment by vlazzarini** [comment]
That's expected, because they behave differently. csoundCompileCSD() will call csoundCompile() if this is the first CSD to be compiled and if csoundStart() has not yet being called. This behaves differently to csoundCompileOrc() which just compiles but doesn't start the engine. Not a bug.

**Comment by nwhetsell** [comment]
Okay, thanks for the clarification.
