### ISSUE TITLE
Remove usages of __DATE__ macro

### ISSUE THREAD

**Issue by fsateler** [csound/csound#561]
Hi,

There is an effort going on to ensure that packages can be built reproducibly ([more info](https://wiki.debian.org/ReproducibleBuilds)). This means that a rebuild using the same build-dependency versions should be bit-for-bit identical. Usage of the timestamp macros evidently makes this impossible. Would there be a problem with simply dropping the __DATE__ macro? It is used only when reporting the version. Alternatively, a new macro could be used, that defaults to __DATE__ but could be specified externally (in our case, the debian changelog date).

I can do either option, but didn't know which one to implement so I decided to ask here. Do people consider the date in the version string valuable? I personally don't, and dropping the __DATE__ would be the easiest, but I can see that others would think differently. In that case one could add a PACKAGE_DATE option, which if defined would be used instead of __DATE__.

**Comment by vlazzarini** [comment]
In my case, it is often useful to have a build date, as it can tell me exactly whether I am running the one I've just built or some other version I have in my system (there is always at least three versions around, the one I'm working on, the latest devel installed, and the latest released). 

I would prefer if the macro was replaced for one that could be specified externally, but that default to __DATE__,  if that's OK with you.

**Comment by jpffitch** [comment]
+1

**Comment by fsateler** [comment]
I pushed a CS_PACKAGE_DATE macro in version.h, and replaced all uses of __DATE__ with it.

**Comment by fsateler** [comment]
In a related note, I have pushed 55833bad91335adb6c6a3bded3fa0ab95d675fe1 . I hope nobody misses the timestamps in the doxygen output footer. If you do, please revert, I can carry this  patch downstream.
