### ISSUE TITLE
Problem with the r score statement

### ISSUE THREAD

**Issue by fggp** [csound/csound#562]
When I run the manual r.csd example, I get this error:

sorting score ...
score error:  r: invalid repeat count
  section 1:  at position 3
    ... done

Csound version 6.07 (double samples)  on a linux 64bit platform, compiled from sources.

I get the error either if Csound was compiled with the SCORE_PARSER option ON or OFF.

Francois

**Comment by jpffitch** [comment]
Probably my fault; I simplified the code in this area to use isblank and 
isspace.  Initial reading looks OK to me but I will look closer
==John ff

**Comment by jpffitch** [comment]
Fixed in git -- apologies

**Comment by fggp** [comment]
Thanks John. It's working now.
