### ISSUE TITLE
CsoundQT Crash Trying to Run Files

### ISSUE THREAD

**Issue by Chocowayne** [csound/csound#566]
So I'm using Csound 6.06 and running CsoundQT 0.9.1 on Windows. When I try to run a file, even just the example music files, I get an immediate crash. Upon running in term, I get an error "This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information." and then the command window crashes. Any ideas or suggestions would be greatly appreciated.

**Comment by vlazzarini** [comment]
Please open an issue in the CsoundQt tracker, as that is not part of Csound.
