### ISSUE TITLE
python pip package for csnd6

### ISSUE THREAD

**Issue by anton-k** [csound/csound#569]
The python community has the [pip repository](https://pypi.python.org/pypi/pip) of packages. It makes it easy to install python libraries and programs. Moreover we can include the pip packages as dependency for our packages. It's as easy as:

```
> easy_install  wonderful_lib
```

It would be nice to have csound to python bindings as a package on pip. With package like this we can create and distribute python apps and libs that use csound as audio engine.

**Comment by dodiku** [comment]
how can you install csnd6 at the moment?
I seems like I don't have it on my machine.

**Comment by rorywalsh** [comment]
It should come with the installer. What OS are you on?

**Comment by dodiku** [comment]
Actually, I just discovered that it was deprecated on Csound 6.08.

The new standard for the Python API should be ``ctcsound.py``.
For some reason, I think that this package was also not included as well (but I might be wrong on that).

I added all the details to - http://stackoverflow.com/questions/41053461/cant-import-csnd6-for-csounds-python-api/

**Comment by vlazzarini** [comment]
csnd6 is not yet deprecated, it is still there in the release.

**Comment by dodiku** [comment]
@vlazzarini -- sounds good. do you know why I fail to import it?

**Comment by kunstmusik** [comment]
From the StackOverflow message, it mentions the OSX as 10.12.  Maybe that's
the issue @vlazzarini?

**Comment by kunstmusik** [comment]
@anton-k I think we might have discussed something related in another issue or on the mailing list.  I think it'd be rather nice to have "pip install csound" or something like it.  I suppose having that for ctcsound might be the ideal way?  The issue I see is what to do about requiring Csound itself to be installed.  Would it be enough to have "pip install ctcsound" with the assumption that the user would also installed Csound (libcsound64.so, etc.) separately?

**Comment by anton-k** [comment]
@kunstmusik I don't know how python folks do it but in general you don't need to install third party libs for python lib to work. I can recall that when I installed wxPython with pip it didn't required wx-widgets to be installed. though I don't know how it works across various systems. 

Maybe requirement to install csound separatley is better way to do it with regards t o modularity.

**Comment by kunstmusik** [comment]
@anton-k I think that's a good example of one way, the other might be something like MySQL-python, which can be installed from PIP but I believe assumes the user will have MySQL installed on their own.  Something like wxPython might be the easier option from a python user's perspective, but I think it would then require compilation of Csound on the end user's computer during the PIP installation, bringing in a lot of dependencies and so on.

**Comment by vlazzarini** [comment]
csnd6 is going to be discontinued, so I am closing this.
