### ISSUE TITLE
Github website issues (error in sample code, and contributes page is down)

### ISSUE THREAD

**Issue by waimanus** [csound/csound#571]
I realize this is probably not the right place to report this kind of problem, but I have no choice since the following link is broken:

https://csound.github.io/contribute.html

(i.e., can we tell the github site maintainers that the contributions page is down?)

The first block of sample code on the "Get started" page has an error: the "<CsOptions>" should not be commented on the fourth line.

Again, I would have sent this to the maintainers via https://csound.github.io/contribute.html, but the page does not exist/the link is broken.

Thank you for Csound!

W

**Comment by waimanus** [comment]
Sorry: I see that the text I quoted was interpreted as markup and it disappeared from my message.  What I meant is that the opening tag for the CsOptions flag should not be commented in the first block of sample source code.

In fact, it looks like there are quite a few things on this "Getting Started" page that could be improved / fixed /edited.  Someday, I would be happy to make some edits.

Again, more urgently: the contributions page is unreachable.

Thank you again for CSound!

W

**Comment by kunstmusik** [comment]
I have added a skeleton page and added an issue on the Csound.github.io project:

https://github.com/csound/csound.github.io/issues/42

For future issues with the site, please file issues with the Csound.github.io site issue tracker at:

https://github.com/csound/csound.github.io/issues

Thanks for filing this issue; we will have to add the above information to the site soon to clarify where to go to do these things.
