### ISSUE TITLE
6.06 github version release

### ISSUE THREAD

**Issue by ainola** [csound/csound#572]
Please supply a github release download for 6.06.0: currently, 6.05.0 is the latest source code release.

Thanks for all of your work!

**Comment by vlazzarini** [comment]
6.06 has been released at sourceforge

http://sourceforge.net/projects/csound/files/csound6/Csound6.06/

**Comment by ainola** [comment]
I'm aware of that, but it would be nice to have the files available on Github as well. As previous releases have been pushed to Github one would expect the files here to be up-to-date as well. I would recommend keeping the releases page current or removing them entirely as I have been using the Github releases page for release notifications and package sourcing. Switching back and forth between github and sourceforge means renaming of version numbers or changing the build scripts since github versions are X.XX.X and sourceforge is X.XX.

This goes back to #475 and what your plans are as a project regarding code hosting and dev environments. It's a bit odd that both Sourceforge and Github are being used: Surely maintaining only one environment would be easier in the long run?

**Comment by vlazzarini** [comment]
We have a draft release for 6.06 which we never published, we will try to do that soon (I tried but have not managed to make it public).

**Comment by kunstmusik** [comment]
The tag for 6.06.0 was not pushed from my computer; that is fixed and the
release should be live now.

**Comment by ainola** [comment]
Thanks!
