### ISSUE TITLE
diskin array not resized when reused

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#573]
when i create an array with diskin, first for a mono file, and then for a stereo file, the latter is refused with the error "output array too small", if the second call is done after the first instance is finished. it works if the second instance of instr 1 is called while the first instance still runs, so it looks like something is wrong with re-using the previous instance.  this is the basic code ("fox.wav" is mono, "SpracheStereo.aiff" is stereo):

nchnls = 2
instr 1
 arr[] diskin p4
 out arr
endin
schedule(1,0,3,"fox.wav")
schedule(1,3,1,"SpracheStereo.aiff")

this is the output:
new alloc for instr 1:
diskin2: opened '/home/jh/src/csoundmanual/examples/fox.wav':
         44100 Hz, 1 channel(s), 121569 sample frames
  rtevent:	   T  3.000 TT  3.000 M:  32768.0      0.0
INIT ERROR in instr 1: diskin2: output array too small
arr	diskin.i	p4	1	0	0	0	0	0	0	0	
		   T  3.000 - note deleted.  i1 had 1 init errors

**Comment by jpffitch** [comment]
Code written to resize array; not tested yet but committed.

I seems that it was designed that way to allow stereo and then mono but not the other way

**Comment by joachimheintz** [comment]
thanks, john: i have tested it and it works perfectly (also for more 
than stereo).
if you are fine with the change, please close.

	joachim
