### ISSUE TITLE
multiple copya2ftab statements with missing tables crash csound

### ISSUE THREAD

**Issue by tgrey1** [csound/csound#574]
If my instrument contains one copya2ftab statement that is attempting to copy into a non-existent table, it errors gracefully... however adding a second statement copying into a non-existent table causes csound to lock up, requiring a force close.

This was actually only tested in cabbage, since my console csound broke and we haven't figured out why yet.  Tried both with large 2d arrays, and with tiny one dimensional arrays.

; just this line works ok
    copya2ftab gkarr1, 11
; adding this line breaks everything
    copya2ftab gkarr2, 12

**Comment by jpffitch** [comment]
Can we have a complete test csd please?

**Comment by vlazzarini** [comment]
Fixed in GIT. PerfError() being called at i-time, which is not possible.
