### ISSUE TITLE
support for arrays in changed opcode...

### ISSUE THREAD

**Issue by rorywalsh** [csound/csound#575]
Can the changed opcode be updated to support arrays?

**Comment by jpffitch** [comment]
Do you want just a single array, or multiple arrays, or mixtures or....
The first is not too hard; do not fancy the others.

**Comment by jpffitch** [comment]
Code written but not tested.  Can you construct a simple example?  One array, any size and dimension

**Comment by jpffitch** [comment]
Passes my simple trst -- committed code.

**Comment by rorywalsh** [comment]
Thanks John. It works fine in the following test:
```
<CsInstruments>

gkArray[] fillarray 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

instr 1; set all channels to 0 
k1 changed gkArray
if k1==1 then
	printks "An element in the array changed", 0
endif
endin

instr 2; change value of channel 'step1'
	gkArray[3] = 3
endin


</CsInstruments>
<CsScore>
i1 0 100
i2 4 .1
</CsScore>
```
But if I change my array to a 2d array, changed is trigger once when the instrument starts, and again when an element changes. In other word, it doesn't behave the same way as with the previous example. 
```
<CsInstruments>
gkArray[][] init   2,3
gkArray     array  1,2,3,7,6,5

instr 1
k1 changed gkArray
if k1==1 then
	printks "An element in the array changed", 0
endif
endin

instr 2; change value of channel 'step1'
	gkArray[1][0] = 3
endin

</CsInstruments>
<CsScore>
i1 0 100
i2 4 .1
</CsScore>
```

**Comment by jpffitch** [comment]
That ios not a 2D effect but the initialisatuon of the "previous" values 
to zero.  To overcone this I should initialise to NaN rather than 0.  Not 
a total fix but very likely to work.

**Comment by jpffitch** [comment]
Actually changed initialises to zero so I followed that.  I also have a version that randomises the "previous" initial value so with high probability it will report the first event as a change.  What do you (or everyone) want?

**Comment by jpffitch** [comment]
Implemented as changed2 with reasonable stating case
