### ISSUE TITLE
opcode "rand" - bug?

### ISSUE THREAD

**Issue by jieunnueij** [csound/csound#576]
<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs = 1

instr 1

aSig rand 0.1, 0, 1 
out aSig, aSig
endin

</CsInstruments>
<CsScore>
i 1 0 100
</CsScore>
</CsoundSynthesizer>
-----------------------------------------------------------------------------------------

if I gave here 0 for isel and 1(or non-zero) for ioffset by opcode "rand": I did not see errors(when I played it) but I can not hear any sound! Could be a bug?

**Comment by vlazzarini** [comment]
You are not doing what you intended. Parameters are:

ar rand  xamp,iseed,isel,ioffset

so you are giving a 0 seed, using 31 bit algorithm. The zero seed seems to be the problem here. I don't know the algorithm.

**Comment by vlazzarini** [comment]
The recursive 31-bit algorithm cannot cope with seed 0, it gets stuck on -1 output. Maybe this needs to be documented.

**Comment by jpffitch** [comment]
Better to map a seed of zero to simeting  else -- 1 or a random start; and 
document

**Comment by joachimheintz** [comment]
+1

**Comment by jpffitch** [comment]
Done in git
