### ISSUE TITLE
apparent problems with some Ambisonic FLOSS examples in CsoundQt

### ISSUE THREAD

**Issue by MarieCurie13** [csound/csound#577]
when trying to run some Ambisonic examples in CsoundQt I get the following error message:

error:  invalid xout statement for UDO: defined 'k', found 'c'
Parsing failed to syntax errors

which is due to statements in the UDO of the kind

xout 0

where the zero is not taken as k-type variable

I found this (easy to correct) problem in 
05B12_udo_ambisonics2D_3.csd, 
05B13_udo_ambisonics2D_4.csd 

and also in 

ambisonics2D_udos.txt

I did not test the other examples yet

Cheers,

Karin

**Comment by MarieCurie13** [comment]
In 05B13 also the normalisation of the HO gain is wrong. It should be 
kgainHO = (1-exp(-kdist))* kgainW

currently it is
 kgainHO = (1-exp(-kdist)) ;* kgainW
that means the factor kgainW is missing, not only in the file & book but also on the web page

There is another bug in ambisonics2D_udos.txt

when fixing the first  issue reported yesterday you get the error message:

error:  invalid xout statement for UDO: defined 'k', found '(null)'
Parsing failed to syntax errors

which is due to ambi2D_write_B

**Comment by joachimheintz** [comment]
sorry steven i didn't see that you self-aasigned this issue, and added the "bug" label.
why?  i thought i'd look at it, because it is about the floss manual.
of course i am happy if you contribute!! — it's just a question.

**Comment by kunstmusik** [comment]
@joachimheintz I'm concerned with the xout validation failing on the constant given rather than any issues with the FLOSS manual examples.  Perhaps you could work with those while I look at the Csound compiler side?

**Comment by joachimheintz** [comment]
@kunstmusik yes, excellent, i will do.

**Comment by joachimheintz** [comment]
@MarieCurie13 : thanks for the report!

1) xout 0 issue: i found this, too, when i ran my tests for the recent floss release (last summer). at http://floss.booktype.pro/csound/b-panning-and-spatialization/ the code is ok, i think. 
i had a look at the csoundqt sources and found the correct code also here, e.g. https://github.com/mantaraya36/CsoundQt/blob/master/src/Examples/FLOSS%20Manual%20Examples/05%20Sound%20Modification/05B12_udo_ambisonics2D_3.csd
so most probably the correct code will be there in the next release.

2) kGainW: yes, obviously a typo. i fixed this on the web site and will soon in the csoundqt sources.

the problem in  ambisonics2D_udos.txt is related to 1), and i think i fixed this, too, but the zhdk page has still the old version.

**Comment by MarieCurie13** [comment]
there have been 2 issues with ambisonics2D_udos.txt. The first was of the same kind than in the examples 05B12 and 05B13 and then there was another issue with the ambisonics2D_write_B opcodes at the end of the txt file. Have they also been solved. Since I just started with Csound and are currently especially looking at the multichannel panning methods, would you please send me the corrected txt file by mail or will I find it on GitHub?

cheers,

Karin

**Comment by joachimheintz** [comment]
can you try these versions and let me know whether they are ok or not?
http://files.csound-tutorial.net/floss_manual/Release06/csd_and_audio_rl6.zip

i had a chat with johannes schuett from zhdk; he will upload the fixed files once we know it works.

**Comment by gogins** [comment]
Earlier I said I would post my spatialization system, an adaptation of the
work of Jan Jacob Hofmann. Here is an archive containing this with some
documentation. Warning: Not tested for a year or so, but should work, if
not, fixes should be obvious.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by kunstmusik** [comment]
@gogins I'm not sure your message was meant for this GitHub issue?  (Issues don't take attachments)

**Comment by MarieCurie13** [comment]
there is no file attached. would you please send it directly to my mail address: karin.dam@desy.de

regards,

karin

**Comment by gogins** [comment]
Right, I was confusing this thread with another. I've sent the stuff
directly.

Best,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by gogins** [comment]
This address does not appear to be valid.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by MarieCurie13** [comment]
sorry a typo: karin.daum@desy.de

**Comment by kunstmusik** [comment]
This ticket has gotten cluttered.  It looks like the FLOSS manual issues are sorted.  I have started #579 for the xout validation issue and added a reference to this ticket.  I will close this ticket now.
