### ISSUE TITLE
Escaping % sign in a string

### ISSUE THREAD

**Issue by hlolli** [csound/csound#580]
Continuing from my question from the mailing list.

Escaping the percentage sign in strings is not possible, at least not with \ ~ or %

Return segfault on all of these

prints "Text %%"
prints "Text \%"
prints "Text ~%"

Just because I love guessing, then my guess is that it needs to be added as switch case in ugrw1.c

https://www.refheap.com/113537

I may be very wrong :)

**Comment by vlazzarini** [comment]
The source for this is in fout.c not ugrw1.c . I had a look and saw the broken bit but did not come up with a solution yet.

**Comment by hlolli** [comment]
Since
Smodulo sprintf "%c", 37
  puts Smodulo, 1

prints out the % sign. So the sprintf works fine in fout.c

again suspecting printsset in ugrw1.c

I can continue with what Im doing without prints being able to print %, and use puts instead.

**Comment by vlazzarini** [comment]
I have worked on this yesterday, and I think I will need to rewrite some of the code.

**Comment by vlazzarini** [comment]
prints uses code from fout.c btw and that is what needs to be rewritten to get the escapong right.

**Comment by vlazzarini** [comment]
prints is fixed, it can escape a constant % with a %, and the character % passed to %c is also escaped.
sprintf does not seem to be able to cope with constants. So I will try to fix that too.

**Comment by joachimheintz** [comment]
if you are on this run, and it's not too difficult, could you perhaps 
include %s as format option in prints/printks?  would be great for many 
use cases.

**Comment by vlazzarini** [comment]
That'll be a big a change. It needs a separate ticket. But why duplicate printf_i?

**Comment by vlazzarini** [comment]
fixed prints now to work with sprintf also.

**Comment by hlolli** [comment]
I did sometimes get weird bugs with sprintf and constants. I'll see if this change fixed it. Sometimes I got scrambled letters � quite unpredictably. I will then make a reproduceable issue.

Thanks for this fix!

**Comment by vlazzarini** [comment]
probably not fixed these, because the issues were in prints.

**Comment by joachimheintz** [comment]
yes if it's a big change, then it makes no sense.  in general, print(k)s 
are a bit more handy to use, but they cannot take strings.  of course 
it's possible to switch to printf for these cases.
