### ISSUE TITLE
crashes on start

### ISSUE THREAD

**Issue by markireland** [csound/csound#581]

**Comment by markireland** [comment]
Android 4.4.2

**Comment by vlazzarini** [comment]
Isn't 5.0 the lowest version?

**Comment by jpffitch** [comment]
From were did you install csound?  Version on playstore seems to need 5.1 but tere are versions fr android 4 on sourceforge.  More detail please

**Comment by jpffitch** [comment]
Do details added for nearly a month.  I will close this as invalid without answers in a week or so
