### ISSUE TITLE
active to uncompiled instrument to send warning instead of error?

### ISSUE THREAD

**Issue by hlolli** [csound/csound#582]
If the active opcode would send a warning instead of an error for instruments that don't exist, would be a major improvement and actually make all my tedious work last days applicable and the possibility of live-coding much easier. 
Let me give an example:

1. I have an UDO that takes 2 strings I call SInstrName and SCompileThisString
2. I assign active to k-rate (kActive active SInstrName)
3. I make a if test if the aforementioned instrument is active
4. If it's not active then I initialize a string I call State-old to "" (State-old init "")
   and endif
5. I make a comparison test if SCompileThisString is equal to State-old (kCompare strcmpk SCompileThisString, State-old
6. I make an if statement that says if this string comparison is false, then it will proceed to compile the string. And endif.
7.  I will make another if statement afterwards that asks the same question as earlier, if SInstrName is active. (SInstrName was indeed the name of the compiled instrument in the SCompareThisString). Since it has not been given event, I will send it an event (schedkwhen 1, 0, 1, SInstrName, 0, -1). And endif.
8. At the bottom I assign State-old = SCompileThisString
9. In the next control-cycle the UDO will see aha, this instrument (SInstrName) is active, therefore not reinitializing State-old and it will therefore (given that no change has been made) will also show successful comparison in the strcmpk and therefore not recompile the SCompileThisString, and in the end not send another event.

But this is only possible if active doesn't send me an error. Any arguments against it? If so, active2 possible?

**Comment by jpffitch** [comment]
Can you give more detail?  I cannot see any error message from te active 
opcode.  If the instrr does not exist it returns zero as far as I can 
tell.

For instance is this with named or numbered instruments?
==John ff

**Comment by hlolli** [comment]
Looks like I was wrong, something magical happened and it doesn't complain about this anymore. Bit shocked. But this still brings me to an old issue I posted on the mailing list. That the active seems to not see re-evaluated instruments. I post the code here, take a look at the opcode live_loop and instr 1, the number of active for the instrument "hommi" (and please dont translate this word from Icelandic :) ) seems to go to 0 after first repeat round.
https://www.refheap.com/113612
Hopefully you can make sense of all this string madness.

**Comment by jpffitch** [comment]
I see a wy in which an error message cound be generated.  Will need some 
work to investigate or fix

**Comment by hlolli** [comment]
Since you are looking at this you could try to see that when changin this string:

"sweet 0.1 -40 500"
to
"sweet [0.1 0.2] -30 [100 200 300 400 500]" for example, that it could do it wrong in the first try, with scrambled letters, but do it compleatly correct the second or third time, despite it working on i-rate. Not such a big problem since this just thorws a warning and continues. I would suspect the memory allocation of char in the c code is too small, but have no idea if that is related.

**Comment by jpffitch** [comment]
I may have fixed the error->warning in active in git now

**Comment by hlolli** [comment]
Yes I indeed don't get an error anymore (but it did come before in an undeterministic manner, as so it seemed). As of now active does just send me off with an warning, and continues without warning when the instrument in question is found.

So my bug is bit unrelated, instead of opening a new ticket, my description above of the udo is this udo live_loop, you could maybe look at the part of this code https://www.refheap.com/113612 where it says ```kActive active "hommi" ```
 ```if kActive > 0 then```
Even tough the instrument "hommi" is said to be running forever so kActive should return 1 or greater number, it still returns 0, except the the first time the event ```i 1 0 4``` is sent.

This warning could apply as well for turnoff2 (it returns error if it doesn't find the instrument being asked to turn off), Im not sure if I need turnoff2 to for what Im trying to achieve. So in sum as of now, active opcode is sending false information to the opcode live_loop as of how many instuments of given instrument name is active.

**Comment by vlazzarini** [comment]
I checked with this code:

```
instr 1
endin

instr 2
print active(1)
endin
```
and

```
i1 0 -1
i2 1.1 0
i2 1.3 0
```

active works correctly. How can you tell that active is not working in your case? The prints statement is i-time and will not run at perf-time, when you do the check.

**Comment by hlolli** [comment]
Ok, my energy for csound is drained for this die. Rest to fight another day.

But I would have thought that the opcode gets reinitilized every time the instrument calling it gets reinitialized, therefore no need for k-rates, at least in the live_loop UDO. And I am printing the active output on k-rate, but never from inside the instrument. Well, let me write a better description tomorrow, thanks for now.

**Comment by vlazzarini** [comment]
But the check is k-rate, it has no effect on i-time (i-time gets run unchanged)

**Comment by hlolli** [comment]
Ok this is then based on my misunderstanding on the k-rate behavious, would just expected it would say 1 on the kratate e.g. 44100/64 times a second (since in my view active is a state). But this works all now what should work. This has been a huge lesson for me, and my eyes are still burning after realizing that compilestr creates new event that replaces the old one, but will keep the old one running. So as of now the events just stack up. I am going to bump my head against the wall today to see where I can go from now on.
