### ISSUE TITLE
Macros with arguments don't work anymore

### ISSUE THREAD

**Issue by hlolli** [csound/csound#585]
After updating csound, suddenly few of my opcodes relying on macro with argument don't work. And I receive the same error when running the manual example define_args.csd, what I recieve:

define macro unexpected character )(0x29) awaiting #

Both in my opcode and the example.

**Comment by jpffitch** [comment]
Example please, and which platform?
==John

**Comment by hlolli** [comment]
I was refering to the manual example define_args.csd

<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
; Audio out   Audio in    No messages
-odac           -iadc     -d     ;;;RT audio I/O
; For Non-realtime ouput leave only the line below:
; -o define_args.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

; Initialize the global variables.
sr = 44100
kr = 4410
ksmps = 10
nchnls = 1

; Define the oscillator macro.
#define OSCMACRO(VOLUME'FREQ'TABLE) #oscil $VOLUME, $FREQ, $TABLE#

; Instrument #1
instr 1
  ; Use the oscillator macro.
  ; This will be expanded to "a1 oscil 5000, 440, 1".
  a1 $OSCMACRO(5000'440'1)

  ; Send it to the output.
  out a1
endin


</CsInstruments>
<CsScore>

; Define Table #1 with an ordinary sine wave.
f 1 0 32768 10 1 
         
; Play Instrument #1 for two seconds.
i 1 0 2
e


</CsScore>
</CsoundSynthesizer> 

csound 6.07 compiled from develop yesterday.

**Comment by hlolli** [comment]
ok markdown clearly hates xml tags, but I hope you understand.

**Comment by jpffitch** [comment]
OK I can reproduce.  Will look latertoday

**Comment by jpffitch** [comment]
Think it is fixed in git; please try

**Comment by hlolli** [comment]
Yes this works now, that was quick!
