### ISSUE TITLE
new #define method to expand in both orc and sco

### ISSUE THREAD

**Issue by tgrey1** [csound/csound#586]
For people using .csd files there is no way to have a singular #define statement that expands in both the orchestra and the score.  Users of individual files can work around this with an included file, but this won't be possible in many cases such as using frontends like blue or cabbage.

**Comment by vlazzarini** [comment]
I am not on favour of this. The score is separate from the orchestra and mixing up the two is not a good idea in my view.

**Comment by tgrey1** [comment]
Victor:  how about the use case where a group of pfields are defined to be used in i statements both in the static score and dynamically from the orc vie scoreline statements?  This seemed to me like another example when it would be very beneficial.

I know very little to nothing about what happens behind the curtain with csound.  Is there a reason I don't understand that having macros available in both contexts would be bad?

**Comment by vlazzarini** [comment]
In that case, you don't need the score. Just use scoreline_i or readscore outside instruments with your static score.

**Comment by tgrey1** [comment]
From my point of view, having an instrument solely to process the score is more mixing up the two more than having a definition that expands in both... but again, I don't know what's going on behind the scenes.  If you guys determine it's a bad idea, I'll trust your judgement on it.

**Comment by vlazzarini** [comment]
you don't need an instrument. You can put scoreline_i and readscore outside instruments. No need for sny score at all. All in Csound code.

I am not trying to have an argument. I am expressing my opinion that I am not happy with mixing score and orchestra features.

**Comment by tgrey1** [comment]
I'm not trying to have an argument either, I genuinely meant that I'll trust the dev's decision in this.  Was just expressing a different point of view.

**Comment by jpffitch** [comment]
An alternative to #include and to new code is to have in <CsOptions> the line
--omacro:FOO=1024 --smacro:FOO=1024
A little more work to maintain but will work

**Comment by kunstmusik** [comment]
Closing out this issue as it seems like it may solve one problem but the cost would be high for implementation, maintenance, and compatibility.
