### ISSUE TITLE
Compiling strings bug

### ISSUE THREAD

**Issue by hlolli** [csound/csound#587]
Ok, first of all I have no idea where the root of this bug is located at. I am just very exhausted trying to figure this out, this used to work before but then suddenly I am getting these bugs that just wont leave me alone. This is based on the idea of compilestring opcode, it looks as if this opcode is not recieveng the same string as that one which is printed, I think it has to do with the fact that garbage collection is somewhere broken, maybe by my long chain of strcat or in the csound code. 

these are examples of what the string is printing at the end:
```
ì×ÝÎ@¶
```
Whatever these characters mean, I have no idea. One idea would be to add an end of line character option in csound strings \0 maybe that will work.

If you play this https://www.refheap.com/113973 in csound

you will see that in the first score event, everything is successful, the string compiles any everyone is happy, in second or third score event, I start to get these weird error messages, despite the fact that prints opcode prints the string just the way I want to see it (from prints in opcode live_loop), but stringcompile will tell me this:
```
error:  Unable to find opcode entry for 'fillarray' with matching argument types:
Found: ][][] fillarray c
Line: 9
```

Which makes no sense to me, because at no point does the string exist in this form ][][] but I want to remind that this was not a bug some days ago and compilestring was able to recompile infinitely, dont know what I did to change this behaviour. Im just exhausted.

**Comment by vlazzarini** [comment]
I put your code in a constant string, and I got similar errors, so I think strcat etc are not to blame. I then changed "fillarray" for "init" and it stopped giving me errors. So it's something with fillarray. Not sure what yet.

**Comment by vlazzarini** [comment]
The problem seems to be that you are using global variables for your arrays. Not quite sure exactly what is going on, but I made a small diagnostics instrument, and I can reproduce the problem with it:

```
instr 1
Scor = {{
instr 2
gi1[] fillarray 20.1
endin
}}
i1 compilestr Scor
endin
```
if  gi1 becomes i1, then the problem goes away.

**Comment by hlolli** [comment]
ok... I can actually use the string arrays instead of csound array datatypes. Good to know the root of the problem, I can work with it from here. But these garbage letters at the end are then nothing to worry about, they make no difference? After currywurst and coffee I will see if using other datatypes than arrays will solve my problem. If so, I change from coffee to a beer :)

**Comment by vlazzarini** [comment]
We'll try to fix this. In the meantime, you can just add the global variables initialisation at the top of
your current code, and it will fix it. Add these lines right at the top before your UDOS

```
giphommi3[] init 1
giphommi4[] init 1
giphommi5[] init 2
```

This makes the code work as is (here).

**Comment by hlolli** [comment]
ok, that shouldn't be diffucult to add. Lets keep this issue open then, let you know if this works.

**Comment by hlolli** [comment]
This https://www.refheap.com/113976 at least doesn't work, but then again I may be misunderstanding what you mean by before the udos. Maybe before the instrument definition?

**Comment by vlazzarini** [comment]
I meant this:

```
sr = 44100
ksmps = 64
nchnls = 2
0dbfs = 1.0


giphommi3[] init 1
giphommi4[] init 1
giphommi5[] init 2

 opcode StrNumP, i, S
[the rest of your code...]
```

It doesn't have problems compiling here.

**Comment by hlolli** [comment]
Ok, I believe that will work, but this predetermination goes against the idea of dynamic power that I am looking for in live evaluation. So I will give stringarray a chance here.

**Comment by vlazzarini** [comment]
Well, it does not need to be static like that, the other solution is not to use fillarray, before we fix it. This will work instead.

```
giphommi3[] init 1
giphommi[0] = 20
```

you can write a UDO replacing fillarray.

**Comment by vlazzarini** [comment]
I got to the bottom of this. The problem is in csound_orc_semantics.c:502 . I have worked on this before, and placed a comment there. Obviously my fix was not complete. @kunstmusik could you have a look?
The problem is this: global variables are being stored in two places, typeTable->globalPool which is used by the parser and csound->engineState.varPool, which is used by the compiler and engine. 

In order to keep references to existing variables, we need to check in  csound->engineState.varPool, if
the variable exists first. But if it does not, we create it here, and somehow it gets re-created elsewhere too, because it is not the same one seen by the compiler when merging. Then, on the second compilation, we get wrong variable attributes.

I will see if I can find a solution.

**Comment by vlazzarini** [comment]
Never mind, I think I fixed this. It was a bug on merge, where the array init was not being done properly.

**Comment by vlazzarini** [comment]
tested your original code and it works. The fix is now in git.

**Comment by hlolli** [comment]
amazing, I think this was the last bottleneck. Happy that all this string madness was not made for nothing. Just add one beer to my tap!

**Comment by vlazzarini** [comment]
beer on me, I am thankful for having these bugs found out. One wrong line of code, that's all it was
