### ISSUE TITLE
Initialize array member data when array is initialised

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#588]
From the mailing list, it looks like arrays do not initialise member data to the array's sub-type, instead starting off with calloc'd memory. We may need to initialise data so that things like STRINGDAT and PVSDAT have some sort of default value setup.  To do this, we may need to split up what happens in createVariable() for each CS_TYPE, which does allocation and initialisation, and have them be separate so that the array initialiser can call init for each member. 

Also, we will have to ensure that when an array is re-sized that initialisation occurs for any new members added. (i.e. add code to tabensure in arrays.c)

**Comment by vlazzarini** [comment]
I've added the var initialisation code for S types, initialising them to empty strings. fsigs might be a bit trickier, no sure what they need to be initialised to.

**Comment by vlazzarini** [comment]
added initialisation for fsigs.
