### ISSUE TITLE
Global arrays length calculation

### ISSUE THREAD

**Issue by hlolli** [csound/csound#589]
```
<CsInstruments>
instr 1
giArray[] fillarray 1
iLen lenarray giArray
print iLen
endin

instr 2
giArray[] fillarray 1, 2
iLen lenarray giArray
print iLen
endin

instr 3
giArray[] fillarray 1
iLen lenarray giArray
print iLen
endin
</CsInstruments>
<CsScore>
i1 0 1
i2 1 1
i3 2 1
</CsScore>
```

returns
```
SECTION 1:
new alloc for instr 1:
instr 1:  iLen = 1.000
B  0.000 ..  1.000 T  1.001 TT  1.001 M:  0.00000  0.00000
new alloc for instr 2:
instr 2:  iLen = 2.000
B  1.000 ..  2.000 T  2.000 TT  2.000 M:  0.00000  0.00000
new alloc for instr 3:
instr 3:  iLen = 2.000
B  2.000 ..  3.000 T  3.001 TT  3.001 M:  0.00000  0.00000
```

Which is bit inconsistent with local scoped arrays. Because relying on array length for iterating trough array via indices becomes extra work. It's just my opinion that fillarrays should (re)initialize the array and assignin to specific array index should be what comes after, if this is supposed to behave this way, then I will find a way around this.

**Comment by vlazzarini** [comment]
Fillarray will check the size, and grow it if needed. It won't shrink it back. Since it is i-time, this will most likely become evident in global variables, but the behaviour is exactly the same for local variables.

**Comment by hlolli** [comment]
Well I checked it and this is excacly the same, but when I evaluate the code section and reinitialize then it will show "correct" array length. About shrinking it back, so many times I see good use for a dynamic case like this:
ivalue opcode iArray[indx % lenarray(iArray)]
but if it never shrinks (or just replaces old values with nil), then a case like that is not possible. But maybe that's just my opinion.
In general no problem, I can find a workaround.

**Comment by vlazzarini** [comment]
When you re-evaluate it's new code, starting from zero again, so yes. It is not that arrays are not dynamic per se, but that there is no opcode to manipulate array sizes. Even if we found that it was better to make fillarray shrink arrays, we could not change its behaviour as it would break existing code. But it should be possible to create other opcodes to resize etc arrays.
