### ISSUE TITLE
Short circuit evaluation for logic operators

### ISSUE THREAD

**Issue by anton-k** [csound/csound#591]
This feature exists in many languages. It would be nice to have it in Csound. So that code below doesn't produce a Warning:

~~~
if (1 == 1 ||  1/0 == 0) then
endif
~~~

This is a contrived example. But it's often useful to have a conditional statement that relies on previous conditional statements in  the chain of OR's.

**Comment by kunstmusik** [comment]
Just adding a note, I was thinking whether this would be backwards compatible to implement and I think it is.  We don't currently expose the boolean types (b and B) to users to define variables and I'm almost certain that all opcodes that process booleans are all stateless.  I think the code generation would change from something like:

```
#b0 equals 1, 1
#i0  div 1, 0
#b1 equals #i0, 0
#b2 and #b0, #b1
cggoto #b2, #label0 
...code
#label0 
```
to:

```
#b0 equals 1, 1
cngoto #b0, #label0
#i0  div 1, 0
#b1 equals #i0, 0
cngoto #b1, #label0 
...code
#label0 
```
(Pseudo code above, I'm not recalling the exact opcodes at the moment.)

**Comment by vlazzarini** [comment]
Do you mean 

```
#b2 or #b0, #b1
```

So you're not doing an explicit OR in this case?

**Comment by kunstmusik** [comment]
Yes sorry, should have been an or instead of and.  I've modified the example code to show the real opcodes as reported from using --verbose when compiling:

```
if (1 == 0 || 1 == 1) then
...
endif
```

**Comment by jpffitch** [comment]
Just to note that this is not a compatible change.  In te proposed short 
cut the valus of
if (k=0 || (k1 == fn())
where fn as internal state. If short cut then that state will not change.

I suspect this is unlikely to occur but it is not without cange.

==John

**Comment by kunstmusik** [comment]
Thanks @jpffitch  for that pointing that out, I was too quick in my analysis regarding stateful opcodes. I'm struggling to imagine a scenario where one would use this kind of code, but it's certainly possible.  Regardless of what we do, we should probably update documentation with the exact behavior.

**Comment by kunstmusik** [comment]
@jpffitch , @vlazzarini , @anton-k : I'm going through issues and wondering if this is a "won't fix" since it's not backwards compatible.  Thoughts?  (Assigning to 6.08 for the timebeing.)

**Comment by jpffitch** [comment]
I think it is too much of a change
==John ffitch

**Comment by kunstmusik** [comment]
Closing as backwards compatibility would be broken.
