### ISSUE TITLE
Windows Installer ENV setting

### ISSUE THREAD

**Issue by Lamprecht** [csound/csound#593]
I just installed Csound for the first time.
I downloaded Setup_Csound6_6.07.0beta2.exe from http://sourceforge.net/projects/csound/files/csound6/Csound6.06/
and installed on a Windows10 Machine.
There seems to be a bug in the installer: The installation requires admin rights, which is fine. However, Env variables OPCODE6DIR64 , PYTHONPATH, and RAMWAVE_PATH are being set for the admin user only instead of setting them system wide.
When trying to use csound from a different user account, this leads to error messages like:
...
\<CsOptions>
-odac
\</CsOptions>
...
 unknown rtaudio module: 'PortAudio', using dummy module
...

Moving the Env variables to the System settings solves this problem.

Cheers, Christoph Lamprecht

**Comment by gogins** [comment]
Fixed in Git.
