### ISSUE TITLE
New to Linux: trying to install csound, but failing

### ISSUE THREAD

**Issue by 4471** [csound/csound#594]
Hi. I have been trying to install csound in ubuntu studio 14.04.03 but I am failing to accomplish it.
I did this:
sudo apt-get build-dep csound

And receive a message on the terminal (I am translating from Portuguese): 
E: It was not possible to get lock /var/lib/dpkg/lock - open (11: resource temporarily unavailable) 
E: Not possible to get exclusive access to the administration directory (/var/lib/dpkg/), is another process using it?
What can I do?
Thank you

**Comment by rorywalsh** [comment]
This usually happens when you have another instance of apt-get running.
Perhaps the software centre is open at the same time? Or a background
update process was running?

**Comment by vlazzarini** [comment]
yes, please check with the Ubuntu help sites etc., as this is not a Csound issue. You can also join the Csound list and ask users there. I am closing this as it is not to do with Csound development.
