### ISSUE TITLE
Audio glitches with UDO

### ISSUE THREAD

**Issue by vncntmchlk** [csound/csound#595]
The following UDO to send audio to a channel is creating a many glitches, which change depending on the ksmps value of the orchestra.

```
opcode sendAudio,0,a
ain xin
chnmix ain,"audio1"
endop

instr play
a1 poscil 0.5,440
sendAudio a1
endin

instr Out
a1 chnget "audio1"
outs a1,a1
chnclear "audio1"
endin
```

However if all happens inside one instrument the glitches don't occur. This is fine:

```
opcode sendAudio,0,a
ain xin
chnmix ain,"audio1"
endop

instr play 
a1 poscil 0.5,440
sendAudio a1
a2 chnget "audio1"
outs a2,a2 
endin

```

Csound 6.07 on Ubuntu 15.10

**Comment by vlazzarini** [comment]
Sorry, I can't reproduce it on OSX. Is that your own build? Did you build with the Release or Debug configuration? The Debug is not normally optimised and its performance can be affected (when you say glitch, you probably mean 'dropout').

**Comment by kunstmusik** [comment]
I also can not reproduce here on Windows with latest from Git. 

@vncntmchlk is this a 32-bit or 64-bit Ubuntu system?

**Comment by vncntmchlk** [comment]
Last week i cloned the csound repository and build it according to these instructions: https://github.com/csound/csound/blob/develop/BUILD.md#debian
So i suppose it's the release configuration. I can send you an audiofile later if it is helpful.
Ubuntu version is 64 bit

**Comment by vlazzarini** [comment]
Try rebuilding with

$ cmake -DCMAKE_BUILD_TYPE="Release" ..

and see if the problem persists.

**Comment by rorywalsh** [comment]
Just tested here on Ubuntu64 and have no problems. I'm using a Release build..

**Comment by jpffitch** [comment]
Just to say it runs OK on OpenSuSE (Linux) 64bit

**Comment by vncntmchlk** [comment]
Ok i just realized it only happens when i use csoundqt, so it must be some configuration problem there. Sorry about the noise.

**Comment by joachimheintz** [comment]
just to note, for me it runs also in csoundqt without any problems 
(debian 8.3, 64 bit, csoundqt from today's git).
