### ISSUE TITLE
Line numbers for errors in UDOs

### ISSUE THREAD

**Issue by rorywalsh** [csound/csound#596]
Is this something that ever worked? Right now Csound will print the error, but doesn't give any line numbers?

**Comment by jpffitch** [comment]
Quite possible never worked.  Could you provie a simple example?

**Comment by jpffitch** [comment]
We NEEDan example -- or this will get marked as will not fix......

**Comment by rorywalsh** [comment]
Hi John. This looks like it is Ok now. In fact, my original post should have said line numbers when dealing with included files. But I just checked that it seems to work fine with the current tip.
