### ISSUE TITLE
new option to report *ALL* possible opcodes

### ISSUE THREAD

**Issue by tgrey1** [csound/csound#597]
-z1 only shows installed opcodes and deprecated opcodes.  It would be useful in certain situations (most notably creating and updating syntax highlighting schemas) if csound could report *ALL* possible opcodes it would accept, even if the required libraries for the opcodes aren't installed.  I jokingly suggested it be added as the -z2 option, but really it doesn't matter where it exists.

For example, -z1 doesn't display the FL or STK opcodes on all systems.

**Comment by kunstmusik** [comment]
I don't think this feature makes sense.  Csound can not report what it
doesn't not know. The Csound manual can be used to parse information
for syntax highlighting and is already used for this purpose by
various systems (e.g., CsoundQT, Blue).

**Comment by vlazzarini** [comment]
I agree, there is no way Csound is able to predict that an opcode exists in a plugin library that it hasn't loaded.

**Comment by jpffitch** [comment]
This makes zero sense.  If you want the union of centrally supported opcodes that is in the manual.
It is not possible to give a complete list

**Comment by tgrey1** [comment]
I concede, sorry for the bad request.  I didn't realize that was how the external libraries work.
