### ISSUE TITLE
Windows MSYS2 dist/install

### ISSUE THREAD

**Issue by Oeyvind** [csound/csound#598]
Building according to the instructions on https://github.com/csound/csound/blob/develop/mingw64/README.md,
the csound64.dll is left in the build directory, while the other binaries are moved to 
csound\mingw64\csound-mingw64\dist
It would be convenient if also the csound64.dll is moved to the bin dir

**Comment by gogins** [comment]
For CMake, csound64.dll is a RUNTIME not a LIBRARY.

**Comment by Oeyvind** [comment]
Yes, which is why I thought it would make sense to put it in the /bin directory ....
