### ISSUE TITLE
Windows MSYS2 build instructions

### ISSUE THREAD

**Issue by Oeyvind** [csound/csound#599]
Add 'make' to the dev tools to be installed with pacman (bullet point 2).

Bullet point 4 could be more clear. 
' The formulas are included in the packages folder.' 
can be changed to
'  The formulas are included in the mingw64/packages folder of the Csound source code' (alternatively ' ... of this repo)

and here:
'Use 'pacman -U name-of-package.pkg.tar.xz' to install the package.'
add sentence:
'Install the devel packages too, if any'

The notes:
'Building the python interface for 64-bit python requires some hacking to build with mingw64. Information is available at this site.' 
add sentence:
'Go to the paragraph "Setup Python for compilation of extensions" and follow the instructions.'

**Comment by gogins** [comment]
Addressed these issues, and explained changes that I have made for building the MSYS2/mingw64 environment.

**Comment by gogins** [comment]
Further expanded MSYS2/mingw64 instructions, which now cover all targets up to and including the Windows installer.

**Comment by rorywalsh** [comment]
Thanks Mike for adding to these build instructions, but I wonder if we couldn't split these steps into 'building core Csound', and 'building auxilary tools'? For example, the first 8 steps outlined in your guide are completely unnecessary for people who just want to build Csound. People not in the know, wishing to build Csound themselves, will assume they need MSVC, QT, Node.js and a host of other developer tools.

**Comment by gogins** [comment]
That is a good suggestion, I will clarify this somehow.

Regards,
Mike

**Comment by rorywalsh** [comment]
Thanks Mike.
