### ISSUE TITLE
PYTHONPATH on Windows

### ISSUE THREAD

**Issue by Oeyvind** [csound/csound#600]
The system variable PYTHONPATH on Windows must be set to C:\Python27\Lib.
Earlier, this was set to Csound6/bin, but this no longer works.

The problem can be seen with the 6.07 binary release on Windows 10 (seems ok on Windows 7).
It also shows on Windows 7 when Csound is built from source using MSYS2.

The error shows as 
ImportError: No module named site
triggered by pyinit

**Comment by gogins** [comment]
This is not a problem for me. There was an issue with PYTHONPATH being set only for "admin" and not for SYSTEM. This is now fixed in Git.
