### ISSUE TITLE
Problems in pvsdemix 

### ISSUE THREAD

**Issue by jpffitch** [csound/csound#602]
Reported in mailing list and transferred here.....originally from Jimmy Manone <jimmanone@GMAIL.COM>

I have implemented the pvsdemix opcode, and it works well but once the azimuth crosses zero in either direction, the output gets a 'doubled' sound.

I've tried this in Linux and Windows with the same result. Also, not only with sliders, but I tried it as well with linseg going up/down through the azimuth values.

I think it is down to how the range is represented in the original code, but I wanted to see if anybody else who is a bit more knowledgeable in all things csound could provide some insight.

**Comment by jpffitch** [comment]
pvsdemix seems to be missing from the manual/examples

**Comment by jpffitch** [comment]
Example code
```
<CsoundSynthesizer>
<CsOptions>
-i adc -o dac
</CsOptions>
<CsInstruments>
sr = 44100
ksmps = 441
kr = 100
nchnls = 2
gifftsiz  =         1024
giwintyp  =         1

instr 1
kexpr  linseg 1,5,.5,5,0.25,5,0,5,-.25,5,-.5,5,-1,5,-.5,5,-.25,5,0,5,.25,5,.5,5,1,5,0 
;Move panning position between positive and negative values
          prints    "LIVE INPUT NOW!%n"
ain, ain2 soundin "fox.wav"
fsig      pvsanal   ain, gifftsiz, gifftsiz/2, gifftsiz*2, giwintyp
fsig2     pvsanal   ain2, gifftsiz, gifftsiz/2, gifftsiz*2, giwintyp
fdm       pvsdemix  fsig, fsig2, kexpr, 15, 15
alisten1   pvsynth   fdm
          outs      alisten1, alisten1
endin

</CsInstruments>
<CsScore>
i 1 0 100
e
</CsScore>
</CsoundSynthesizer>
```

...

**Comment by vlazzarini** [comment]
Two questions
1) fox.wav in the repo is mono
2) overlap 1/2 fftsize is not sufficient for full reconstruction with Von Hann windows. 1/4 is the min.

Also it is a very big ksmps size, which is not good either. I will test with a proper stereo file and better parameters

**Comment by vlazzarini** [comment]
I can't see anything particularly wrong when using a stereo file.

**Comment by jpffitch** [comment]
Can you suggest a corrected set of parameters/  I am getting SDFT not implemented for pvsdemix

**Comment by vlazzarini** [comment]
ksmps=64

fftsize and windowsize 1024
hopsize 256

**Comment by jpffitch** [comment]
Thanks; I cannot hear any problem using xanadu as the input.  Perhaps we close this.
