### ISSUE TITLE
GEN34 only working with pow-of-two source tables

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#603]
these two lines 
  giPartials	ftgen	0, 0, 6, -2, 1,1,0, .7,2,0
  giWave ftgen 0, 0, 1024, 34, giPartials, 2, 1
are failing as:
  INIT ERROR in instr 0: illegal table length
  giWave	ftgen	0	0	1024	34	giPartials	2	1

but if i am not wrong, the manual only requires the *resulting* table (here giWave) to be a power of two size, not the *source* table (which contains triples of strength, partial number and phase):
"Table length (not including the guard point) should be at least 3 * nh. If the table is too short, the number of partials (nh) is reduced to (table length) / 3, rounded towards zero."

and i am pretty sure, the code worked in csound5.

but now, it only works if i set it to a power of two:
giPartials	ftgen	0, 0, 8, -2, 1,1,0, .7,2,0

thanks for having a look -
  joachim

**Comment by vlazzarini** [comment]
Fixed in GIT. Can you confirm it works?

**Comment by joachimheintz** [comment]
yes it does. thanks for the quick fix!
