### ISSUE TITLE
ftgen doesn't work with GEN49

### ISSUE THREAD

**Issue by anton-k** [csound/csound#604]
Ftgen says that it can not take in string as an argument for gen 49.
As we can see in the source code, the 49 is missing in the list of string opcodes for `ftgen.c`:

~~~c
       switch (n) {                      /*   must be Gen01, 23, 28, or 43 */
        case 1:
        case 23:
        case 28:
        case 43:
          ftevt->strarg = ((STRINGDAT *) p->p5)->data;
          break;
~~~

**Comment by jpffitch** [comment]
y you give a line number anf fuction for that ode?  I cannot finf it in 
fgens.c

**Comment by jpffitch** [comment]
Sirry foud it -- must get new lasses

**Comment by jpffitch** [comment]
Can you pull and test?  Or provide a test program?

**Comment by anton-k** [comment]
I can not try it out due to another issue. But I\ve tried the commit like you have done and it worked fine with one of the previous versions of csound (where I don't get the segfault). I guess it should work.
Here is a little sample. I don't know why it doesn't plays the ftable back but it reads it without any complains: 

[ftgen49.csd.zip](https://github.com/csound/csound/files/155218/ftgen49.csd.zip)

You need to replace an mp3 file at the line 16 with your own.
