### ISSUE TITLE
pvsfwrite and 0dbfs

### ISSUE THREAD

**Issue by iainmccurdy** [csound/csound#606]
pvsfwrite seems not to respond correctly to changes made to 0dbfs away from a value of 1.

The appended csd analyses fox.wav and writes a file fox.pvx using pvsfwrite in instr 1. It then reads and resynthesises the audio in instr 2. If 0dbfs=1 this performs as desired but if 0bdfs is removed - so it defaults to 32768 - the resynthesised playback in instr 2 is hugely distorted. Obviously an amps mismatch. pvsfread and pvsdiskin give the same results. 

<CsoundSynthesizer>

<CsOptions>
-odac -dm0
</CsOptions>

<CsInstruments>

sr              =       44100
ksmps           =       64
nchnls          =       1
0dbfs           =       1

#define SoundName #fox#

instr   1
 p3     filelen "$SoundName..wav"
 asig   diskin  "$SoundName..wav"
 fsig   pvsanal asig, 1024, 256, 1024, 0
        pvsfwrite fsig, "$SoundName..pvx"
        out     asig
        event_i "i",2,p3+0.5,p3
endin

instr   2
 p3     filelen         "$SoundName..pvx"
 kptr   linseg          0,p3,p3
 ;fsig  pvsdiskin       "$SoundName..pvx",1,1
 fsig   pvsfread        kptr, "$SoundName..pvx"
 asig   pvsynth         fsig
        out             asig
endin

</CsInstruments>

<CsScore>
i 1 0 0.1 ; read file and write analyse
;i 2 5 0.1 ; read analysis and resynthesise
f 0 20
</CsScore>

**Comment by vlazzarini** [comment]
fixed in git
