### ISSUE TITLE
Linux Macro Substitution issue

### ISSUE THREAD

**Issue by ssj71** [csound/csound#609]
HI all:

I'm a total csound Noob, but I've been trying to use the hadron particle synth on linux. As noted in this thread from the ML:
https://sourceforge.net/p/csound/mailman/message/34531673/

There is some substitution error going on. If I go and change any place with a macro argument in the middle of a string so the '$' is escaped then it at least is getting past the defining macros. You can see the diff of what I've done here: https://github.com/ssj71/hadron-particle-synth/commit/e7233e7ec571629711ad3fb71a3c9ff6680cd362

but now I'm hitting the error:
"Cannot open #include'd file inc/setModFuncTable.inc"
I haven't a clue how to proceed.

Regardless of that, I don't think these $args in macros should need to be escaped, so there's a bug in the parser somewhere.

**Comment by fsateler** [comment]
Looks like the faulty commit is 424ec418da1ce0d1ab2710e8baa8532b54d4f4ef , a git bisect has led me there. (I get a segmentation fault even when the macro passes though...)

**Comment by Oeyvind** [comment]
Hi,
The Csound code for Hadron was written under Csound5, and the parser was a
little more forgiving as to macro termination back then. We are in the
process of updating the Hadron engine to use Csound 6, and subsequently
also the code should run in standalone under Csound 6. I did a preliminary
version for another user that asked, it is here:
http://oeyvind.teks.no/ftp/Hadron/hadron_standalone_cs6.zip
I hope that this might solve it also for you. Do let me know.
Oeyvind

2016-03-10 0:23 GMT+01:00 ssj71 <notifications@github.com>:

> HI all:
>
> I'm a total csound Noob, but I've been trying to use the hadron particle
> synth on linux. As noted in this thread from the ML:
> https://sourceforge.net/p/csound/mailman/message/34531673/
>
> There is some substitution error going on. If I go and change any place
> with a macro argument in the middle of a string so the '$' is escaped then
> it at least is getting past the defining macros. You can see the diff of
> what I've done here: ssj71/hadron-particle-synth@e7233e7
> <https://github.com/ssj71/hadron-particle-synth/commit/e7233e7ec571629711ad3fb71a3c9ff6680cd362>
>
> but now I'm hitting the error:
> "Cannot open #include'd file inc/setModFuncTable.inc"
> I haven't a clue how to proceed.
>
> Regardless of that, I don't think these $args in macros should need to be
> escaped, so there's a bug in the parser somewhere.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/csound/csound/issues/609>.
>



-- 

Oeyvind Brandtsegg
Professor of Music Technology
NTNU
7491 Trondheim
Norway
Cell: +47 92 203 205

http://www.partikkelaudio.com/
http://soundcloud.com/brandtsegg
http://flyndresang.no/
http://soundcloud.com/t-emp

**Comment by ssj71** [comment]
Thanks very much Oeyvind!
I'm excited to use this. I'm now getting some error with the alsa midi/rtmidi module. 
'''
ALSA lib rawmidi.c:286:(snd_rawmidi_open_noupdate) Unknown RawMidi 4
ALSA: error opening MIDI input device: '4'
 *** error opening MIDI in device: -1 (Unknown MIDI error)
'''
I'm also working a bit with Dave Phillips, he's got lots of linux and Csound experience so I think he'll be able to get me going. For the curious see: https://linuxmusicians.com/viewtopic.php?f=48&t=15466

So is there a bug in Csound or just by definition macro arguments mid-string must be terminated with a .?

**Comment by hlolli** [comment]
The included midi driver from csound is often unstable, I recommend checking out rt_midi with CsoundQt for midi. But you may check to see what alsa_seq does instead of alsa_raw.

**Comment by Oeyvind** [comment]
Hlöðver, in what way do you mean Csound's midi driver is unstable? it
sounds like somoething we would want to fix.

and *ssj71* (did not get your name, sorry?), the macros work as they
should in Csound 6, so a macro argument must be terminated by a dot
(or whitespace). Previous versions of Csound did allow non-terminated
macro arguments, but this could lead to ambiguities.

**Comment by hlolli** [comment]
Well... I must admit that I've never tried really hard to get csound midi to work, but I've failed so far with it and jackplugins from gogins. But the unstable part I'm mostly quoting CsoundQt editor where a button exists that says: [ ] Use Csound MIDI modules (unstable). But this is also a thing that is hard to reproduce for an issue, because this can always be driver related issue.

**Comment by Oeyvind** [comment]
ok,
so it means the Csound midi driver is unstable from within Qt (Andres?
Tarmo?),
but we have no info saying it is unstable when run from the terminal it
seems (?).

I seem to recall having used midi under Linux with no problems, but I
haven't done it much and not in a while.
Dave Phillips may perhaps help us with a report on his experience?

2016-03-11 9:20 GMT+01:00 Hlöðver Sigurðsson <notifications@github.com>:

**Comment by joachimheintz** [comment]
yes i think andrés chose these words as there were a lot of problems 
with midi inside csoundqt when using the csound midi modules.

so, as oeyvind says, it is not a judgement about csound's midi modules 
but of their usage inside csoundqt.

**Comment by ssj71** [comment]
Ok. Thanks all. I'll close this issue as it was just a bug in the csd (which Oeyvind's update resolves) not a bug in Csound. I think the midi issue is just user error/lack of knowledge I found some documentation at http://www.csounds.com/manual/html/RealTimeLinux.html which I'll try.

Thanks again,
_Spencer
