### ISSUE TITLE
Better integration with Lisp algorithmic composition environments

### ISSUE THREAD

**Issue by gogins** [csound/csound#610]
Provide an init file or other facility to load Lisp and/or Scheme systems for algorithmic composition for use with Csound. Also provide some examples of integrating such code with Csound. Systems to integrate could include Common Music, OpenMusic, and Drew Kraus' code.

**Comment by gogins** [comment]
The init file needs to work at least on Linux and Windows. I will investigate Steel Bank Common Lisp as the Lisp system. I need to find out if I can just use ffi to access the Csound API.

**Comment by gogins** [comment]
SBCL has its own FFI. In addition, SBCL is supposed to be able to use CFFI. Because /csound/interfaces contains a SWIG-generated CFFI interface, I will first see if this actually works with SBCL. So yes, I will be able to use FFI to access the Csound API.

Our CFFI binding is out of date, so I will try to regenerate it, and I will also make it a part of the default build.

**Comment by kunstmusik** [comment]
Let me know when this is ready and I'll be happy to help testing (should be
able to test on Linux, OSX, and Windows).

**Comment by gogins** [comment]
Thanks for helping. I'll keep you posted. Now that we have
"csoundCompileCsdText" the "filebuilding.lisp" thing should not be required.

Best,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by gogins** [comment]
Got "test.lisp" to run on Linux with SBCL using raw CFFI and embedded CSD.
Now to try using the generated wrapper for the same CSD.

**Comment by gogins** [comment]
I am pasting as many defcfn calls into csound.lisp as possible from the SWIG generated wrapper. So far it works to restrict the interface to pointers, strings, and elementary types.

**Comment by gogins** [comment]
I have pushed the following updated files to GitHub:

csound/interfaces/lisp-swig.sh -- Generates an "lcsound" package wrapping
everything in csound.h, but it doesn't actually work.
csound/interfaces/csound.lisp -- Handwritten "csound" package for Lisp
based on output from SWiG, but not actually generated by SWIG; works but
adding new functions seems difficult.
csound/examples/test.lisp -- Runs "Xanadu" using low-level cffi calls.
csound/examples/test-wrapper.lisp -- Runs "Xanadu" using the csound wrapper
package. Run like this from the csound source dir:

    mkg@Sun-Yukong:~/csound/csound$ sbcl --load
examples/lisp/test-wrapper.lisp

See if you can get that to run for you, and better yet, see if you can find
out why adding some of the commented functions in csound.lisp seems to
break it.

Best,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by kunstmusik** [comment]
@gogins I am going through the README.md for setup and am not sure how to interpret this step:

"Install Csound's cffi wrapper. The interfaces/csound.lisp file defines a Lisp  cffi  wrapper for many of the most useful functions in the Csound API defined in include/csound.h, and documented here. If you do not find  interfaces/csound.lisp  in your installation of Csound, download it directly from GitHub here."

I am testing with clisp as sbcl reports being only somewhat maintained for Windows.  clisp with quicklisp doesn't seem to load cffi correctly, so I may just move on to other platforms for now.

**Comment by gogins** [comment]
OpenMusic's Web site says OpenMusic on Linux is only for 32 bit CPU architecture. I will check that. In addition, OM is said to depend on stuff from the proprietary LispWorks compiler. This probably means that loading OM from sbcl is out of the question. If that is the case I will drop OM from my page except for referencing it.

Drew Krause no longer hosts his Lisp code but I hope to be able to host it. He has switched to Haskell so I am going to perform this exercise for Haskell as well.

**Comment by gogins** [comment]
OpenMusic depends on and only runs in LispWorks. But LispWorks supports cffi.

**Comment by gogins** [comment]
When I get back to the city next week where my Windows machine lives I will
try again with clisp. As I recall clisp for Windows is only available for
32 bit CPU architecture and that is why I switched to SBCL. Which at least
runs on Windows.

Best,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by gogins** [comment]
It seems that I cannot easily use sbcl with Common Music. I am now trying cmucl from https://common-lisp.net/project/cmucl/downloads/release/21a/.

**Comment by kunstmusik** [comment]
@gogins I tried testing with sbcl on Debian.  I got to this step again which I still do not understand:

"Install Csound's cffi wrapper. The interfaces/csound.lisp file defines a Lisp cffi wrapper for many of the most useful functions in the Csound API defined in include/csound.h, and documented here. If you do not find interfaces/csound.lisp in your installation of Csound, download it directly from GitHub here."

Could you explain this step?  I tried using quicklisp and asdf but there is no .asd file.  Should the .lisp file be placed somewhere?

**Comment by gogins** [comment]
I have not created an asd file for csound.lisp but I can see that I should
so I will.

Best,
Mike

**Comment by gogins** [comment]
I have created a csound.asd file and also a separate wrapper for Steel Bank Common Lisp. The sb-csound wrapper is starting to work with Common Music.

**Comment by gogins** [comment]
Cut this back to Lisp only and with sb-alien FFI only. But it works.

**Comment by gogins** [comment]
Reopening to provide a working example with Drew Krause's code.

**Comment by gogins** [comment]
Reopening to provide a working example with Drew Krause's code.

There are many uses of Scheme "define" in Drew's Lisp code, see http://stackoverflow.com/questions/28938940/simulate-scheme-define-in-common-lisp for what to do about them.

**Comment by gogins** [comment]
Can't really get Common Music, Lisp version, to work on Windows. The cm2.asd files I tried bail on translating loop.scm to iter.lisp.

**Comment by gogins** [comment]
I have got tonnetz.lisp to work with MIDI. I will create an example from this that works with Csound. I will also create a nudruz.asd if I can. I also will attempt to integrate Common Music Notation.

**Comment by gogins** [comment]
I have created a `nudruz.asd` system definition file, and tested a few examples. So this is complete enough for now.

**Comment by gogins** [comment]
Reopening this with respect to OpenMusic, which now truly does appear to be open source, and to install and run without obvious problems on Linux.
