### ISSUE TITLE
mvclpf4 segfaults

### ISSUE THREAD

**Issue by anton-k** [csound/csound#611]
Here is an example of segfault with mvclpf4
The instrument is pure sine filtered with LFO on center frequency.

[mvclpf4-segfault.csd.zip](https://github.com/csound/csound/files/178655/mvclpf4-segfault.csd.zip)

Also when I use the filter with constant values for center frequency and resonance I get an error:

~~~
error:  Unable to find opcode entry for 'mvclpf4' with matching argument types:
Found: a mvclpf4 aii
~~~

**Comment by vlazzarini** [comment]
There are 4 outputs in this filter, 6, 12, 18, 24 db / octave. 

Victor Lazzarini
Dean of Arts, Celtic Studies, and Philosophy
Maynooth University
Ireland

**Comment by vlazzarini** [comment]
fixed in git. Just to remind that this filter has 4 audio outputs. The CSD now fails with a syntax error
