### ISSUE TITLE
Optimization of moogladder filter

### ISSUE THREAD

**Issue by anton-k** [csound/csound#612]
The filter produces audio of the great quality. But unfortunately it's expensive to use.
On the list @jpffitch has mentioned a way to optimize it. There are calls to tanh in the loop. Maybe it's possible to substitute them with table look up.

**Comment by jpffitch** [comment]
I have a version that approximates tanh for small and large args which seems to speed up moogladder by  about 4 times.  Needs more testing tat I can give

**Comment by anton-k** [comment]
Great news! I've made a comparison of filters and moogladder produces one of the best outputs to my ears if not the best.

**Comment by anton-k** [comment]
Maybe I can help you with testing somehow?

**Comment by jpffitch** [comment]
There have been objections to the lack of accuracy.  I think they are very small but the test must be aural.
At preset the faster version is in te sources but not compiled in normal builds

**Comment by jpffitch** [comment]
moogladder2 is now in sources with faster less accurate code
