### ISSUE TITLE
ATS tme pointer not totally right

### ISSUE THREAD

**Issue by jpffitch** [csound/csound#614]
Try running the manual example ATSsinnoi; it reports time pointer out of range.   Adding tracing shows that the pointer is generated by line opcode from 0 to 2 and when reported is at 1.95265 which is below 2 which is length of beats.wav from which beats.ats is derived.  FrMax is 41 and frIndx is 41.0057 so the warning is correct, but should not be a problem.  Suspet error is in atsa utility but not checked.  

WARNING: ATSSINNOI: time pointer out of range, fr=41.0057 max=41 ktimpnt=1.95265 timefrmInc=21 truncating to last frame

**Comment by jpffitch** [comment]
Further investigation shows it complains for values between 1.95265 and 1.99909 which correspond to frIndex from 41.0057 to 41.981.  Assuming these are truncated the test for end of data is wrong, or te frame count is wrong in atsa.
Anyone know anything about this code?

**Comment by jpffitch** [comment]
changing thetrst from frIndx>frMax to frIndx>=frMax+1 seems to fix it and valgrind does not complain.
But is it right?

**Comment by jpffitch** [comment]
Closing this for now as the fix seems Ok

**Comment by joachimheintz** [comment]
i have asked one of the ats authors.   once he answered, i will reply here.
