### ISSUE TITLE
Windows building problem

### ISSUE THREAD

**Issue by C2K16** [csound/csound#615]
Problem building on Windows (mingw32).
Following Build instructions inside the downloaded source code folder

"Now type sndfile into the search field and you should see a few cmake entries concerned with libsndfile"

cmake does not display anything.

**Comment by rorywalsh** [comment]
The 2 libsndfile specific CMAKE flags are LIBSNDFILE_LIBRARY and SNDFILE_H_PATH. However,  building on Windows has changed in recent months. It's now recommended to use MSYS2. You canfind instructions here:
https://github.com/csound/csound/tree/develop/mingw64
