### ISSUE TITLE
MSYS2 build issue with mingw-w64-x86_64-luajit-git

### ISSUE THREAD

**Issue by merlinusambrosius** [csound/csound#616]
Just wanted to make aware a problem I found following these instructions:
https://github.com/csound/csound/tree/develop/mingw64
When attempting to install mingw-w64-x86_64-luajit-git, the following error occurs:

`$ pacman -S mingw-w64-x86_64-luajit-git
resolving dependencies...
warning: cannot resolve "winpty-git", a dependency of "mingw-w64-x86_64-luajit-git"
:: The following package cannot be upgraded due to unresolvable dependencies:
      mingw-w64-x86_64-luajit-git`

Apparently there's an issue with a name change from winpty-git to winpty.

https://github.com/Alexpux/MINGW-packages/issues/1242

Not sure what they are doing to fix it.

**Comment by gogins** [comment]
I can't reproduce this. In any event if it remains a problem, we can't fix it, MINGW-packages has to fix it.

**Comment by kunstmusik** [comment]
It's a problem for me here. You should experience the same thing I'd you
try to remove then reinstall Linksys luajit-git. However, I agree with
Michael that there is little we can do.

**Comment by mati865** [comment]
Not sure why it is not in msys2 repo yet. However you can build it yourself since fixed pkgbuild is already merged to git repo (https://github.com/Alexpux/MINGW-packages).
