### ISSUE TITLE
problem with pvsbandp 

### ISSUE THREAD

**Issue by MarieCurie13** [csound/csound#617]
Hi,

I've encountered a problem with pvsbandp. As soon as it is used at different non-overlapping time intervals CsoundQt gets stuck and when I'm running Csound on the terminal I get the following error massage:

Score finished in csoundPerform().
Csound(59047,0x7fff7c504300) malloc: *** error for object 0x7f83c28df808: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug

csound command: Abort trap

and the output file is not closed properly. Using afinfo I get:

File:           pvsbandp_bug.wav
File type ID:   WAVE
Num Tracks:     1
----
Data format:     2 ch,  44100 Hz, 'lpcm' (0x0000000C) 16-bit little-endian signed integer
               no channel layout.
estimated duration: 0.000000 sec
audio bytes: 0
audio packets: 0
bit rate: 1411200 bits per second
packet size upper bound: 4
maximum packet size: 4
audio data file offset: 44
optimized
source bit depth: I16
----

Im using the latest Csound/CsoundQt versions available for MAC. A small program for verifying the bug can be found below:

<CsoundSynthesizer>
<CsOptions>
-opvsbandp_bug.wav -W
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs = 1.0
gisine	ftgen 0,0,2^12,10,1
instr 1
asnd	poscil 0.5,440,gisine
fsig	pvsanal asnd,1024,256,1024,1
fsigl	pvsbandp fsig,10,50,800,1250
fsigh	pvsbandp fsig,800,1250,15000,18000
fsig1 pvscale fsigl,p4
asig1	pvsynth fsig1
asig2	pvsynth fsigh
asig 	sum asig1,asig2
     outs asig, asig

endin

</CsInstruments>
<CsScore>
i 1 0 2 1.
i 1 3 2 1.5
</CsScore>
</CsoundSynthesizer>

Cheers,

Karin

**Comment by vlazzarini** [comment]
Simple bug in opcode initialisation (MYFLT used instead of float). Fixed in git.
