### ISSUE TITLE
Csound 6.0.7 beta (MAC) prints bug

### ISSUE THREAD

**Issue by MarieCurie13** [csound/csound#620]
Hi,

a statement like:

	prints " mean pitch original   %7.1f sigma %5.2f centroid %7.1f samples %d\n",imean,isig,icent,i(gkcnt[0])

produces the following output:

%7.1f sigma %5.2f centroid %7.1f samples %d

%5.2f centroid %7.1f samples %d

%7.1f samples %d

 mean pitch original     212.8 sigma  4.43 centroid   180.2 samples 1416

**Comment by jpffitch** [comment]
Any chance if a full csd to test?  Preferable a sort one but anything helps.

**Comment by MarieCurie13** [comment]
here it comes, it shows both problems I’ve posted

<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 128
nchnls = 2
0dbfs = 1.0
instr 1
iv1	init 10.5
iv2	init 5.3
iv3	init 200
prints " using pvscale for LF only - split with butlp/buthp before pvsanal %f %f %d\n",iv1,iv2,iv3
prints " using sndwarp \n"
endin

</CsInstruments>
<CsScore>
i 1 0 1
</CsScore>
</CsoundSynthesizer>

**Comment by jpffitch** [comment]
How does this differ from #621?

**Comment by jpffitch** [comment]
Fixed in git

**Comment by MarieCurie13** [comment]
printing out these formatting lines (the example csd)

%f %f %d

%f %d

happens only with 6.0.7. I did not have this problem with 6.0.6 and it does not appear on the latest CsoundQt (which is based 6.0.6)

the printing of the left-over from the previous string if it is longer happens also on CsoundQt

**Comment by vlazzarini** [comment]
This has been fixed as reported elsewhere.
