### ISSUE TITLE
prints bug in Csound

### ISSUE THREAD

**Issue by MarieCurie13** [csound/csound#621]
Hi,

there is a problem with printing strings in CsoundQt. If after a long string a short string should be printed also the remainder of the long string will be printed.

The example below:

<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 128
nchnls = 2
0dbfs = 1.0
instr 1
prints " using pvscale for LF only  - split with butlp/buthp before pvsanal \n"
prints " using sndwarp \n"
endin

</CsInstruments>
<CsScore>
i 1 0 1
</CsScore>
</CsoundSynthesizer>

prints:

 using pvscale for LF only  - split with butlp/buthp before pvsanal 
 using sndwarp 
or LF only  - split with butlp/buthp before pvsanal 

could this be related to the fact that I have updated to Csound 6.0.7 beta that means an issue with libraries?

**Comment by rorywalsh** [comment]
This is not just an issue with CsoundQT, it's a problem Csound itself, and it's present on all platforms. Therefore I'm changing the title of this issue to reflect this.

**Comment by vlazzarini** [comment]
fixed in GIT.
