### ISSUE TITLE
more i/o problems with Csound 6.0.7-beta (readfi)

### ISSUE THREAD

**Issue by MarieCurie13** [csound/csound#622]
Hi,

the last problem I encountered with 6.0.7 before going back to 6.0.6 is related to the readfi opcode (I could not run the code I've used before changing to 6.0.7)
I verified it with a small csd below:
`<CsoundSynthesizer>`
`<CsOptions>`
`</CsOptions>`
`<CsInstruments>`

sr = 48000
ksmps = 128
nchnls = 6
0dbfs = 1.0
instr 1
indx		init	0
	prints "start reading \n"
  Sfile,indx	readfi "test.txt"
	prints " index in test.list %d \n",indx
	prints Sfile
endin

`</CsInstruments>`
`<CsScore>`
i 1 0 1
`</CsScore>`
`</CsoundSynthesizer>`

and test.list is attached. 
[test.txt](https://github.com/csound/csound/files/206493/test.txt)
The error message I get is:

new alloc for instr 1:
start reading 
PERF ERROR in instr 1: readf: read failure
   note aborted
 index in test.list 0 

independently of giving the full path or only the file name as above. Now I'm back to 6.0.6 and there it works as expected:

new alloc for instr 1:
start reading 
 index in test.list 1 
test.wav

I also verified that the  two prints bugs I reported today  are absent on 6.0.6 

cheers,

Karin

**Comment by vlazzarini** [comment]
The prints issue has been fixed. I will look at this one now

**Comment by vlazzarini** [comment]
fixed in git
