### ISSUE TITLE
FLTK crashes Csound in Windows 6.07 rc1 (Gogins build April 3 2016)

### ISSUE THREAD

**Issue by Oeyvind** [csound/csound#623]
The following example csd is taken from the manual for FLslider.
It crashes Csound on startup.
Using Csound 6.07 rc1 downloaded from:
https://sourceforge.net/projects/csound/files/csound6/Csound6.07/Setup_Csound6_x64_6.07.0rc1.exe/download
This is on windows 7.

<CsoundSynthesizer>
<CsOptions>
-odac           -iadc     -d     ;;;RT audio I/O
</CsOptions>
<CsInstruments>

; A sine with oscillator with flslider controlled frequency
sr = 44100
kr = 441
ksmps = 100
nchnls = 1

FLpanel "Frequency Slider", 900, 400, 50, 50
    ; Minimum value output by the slider
    imin = 200
    ; Maximum value output by the slider
    imax = 5000
    ; Logarithmic type slider selected
    iexp = -1
    ; Slider graphic type (5='nice' slider)
    itype = 5 
    ; Display handle (-1=not used)
    idisp = -1
    ; Width of the slider in pixels
    iwidth = 750
    ; Height of the slider in pixels
    iheight = 30
    ; Distance of the left edge of the slider
    ; from the left edge of the panel
    ix = 125
    ; Distance of the top edge of the slider 
    ; from the top edge of the panel
    iy = 50

    gkfreq, ihandle FLslider "Frequency", imin, imax, iexp, itype, idisp, iwidth, iheight, ix, iy
; End of panel contents
FLpanelEnd
; Run the widget thread!
FLrun

;Set the widget's initial value
FLsetVal_i 300, ihandle

instr 1
    iamp = 15000
    ifn = 1
    kfreq portk gkfreq, 0.005  ;Smooth gkfreq to avoid zipper noise
    asig oscili iamp, kfreq, ifn
    out asig
endin

</CsInstruments>
<CsScore>

; Function table that defines a single cycle
; of a sine wave.
f 1 0 1024 10 1

; Instrument 1 will play a note for 1 hour.
i 1 0 3600
e

</CsScore>
</CsoundSynthesizer>

**Comment by jpffitch** [comment]
Works for me on Linux

**Comment by rorywalsh** [comment]
Which is why Oeyvind wrote Windows in his issue subject ;) I just tried
here and using the virtual MIDI keyboard also causes a segfault. Must also
be fltk related. Here is a simple test:

<CsoundSynthesizer>
<CsOptions>
-odac  -+rtmidi=virtual -M0
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 256
nchnls = 2
0dbfs = 1

instr 1
print p1
endin

</CsInstruments>
<CsScore>
i1 0 100
</CsScore>
</CsoundSynthesizer>

**Comment by Oeyvind** [comment]
I did a test just now with a Csound version I built myself (from develop branch) on March 7, using the mingw64 build script. The crash does not occur with that Csound version.

**Comment by gogins** [comment]
This is probably related to CsoundVST crashing. I tried to debug this but
the segfault happens in FLTK code when a text buffer is set into an edit
widget, which crashes in its resize callback.

**Comment by Oeyvind** [comment]
In case it matters, the following example also crashes (containing no FLTK
widgets, only an empty FLpanel).

<CsoundSynthesizer>
<CsOptions>
-odac3
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2

FLpanel         "Controllers",280,260,100,100
        FLpanel_end
    FLrun

;*********************************************************************
instr 1

a1 oscil 2000, 440, 93
outs a1, a1

endin
;*********************************************************************

</CsInstruments>
<CsScore>
i1 0 60000
f93 0 65536 10   1     ; sine
e
</CsScore>
</CsoundSynthesizer>


2016-04-06 23:09 GMT+02:00 Michael Gogins <notifications@github.com>:

> This is probably related to CsoundVST crashing. I tried to debug this but
> the segfault happens in FLTK code when a text buffer is set into an edit
> widget, which crashes in its resize callback.
>

**Comment by Oeyvind** [comment]
I wonder if this is related to some changes done between March 8 and March 10. There seems to be other issues with static libraries introduced at that time.

**Comment by gogins** [comment]
csoundvstmain.exe and the fltk_test.csd are no longer crashing after changes to the build system and updating my msys2/mingw64 toolchain.
