### ISSUE TITLE
Issue: Version and Macros

### ISSUE THREAD

**Issue by nogothenogo** [csound/csound#624]
I tried a macro and it did not work.
I think it is a bug in the version check module
At other places it works.

```
#define CsoundVersion #6.07#
<CsVersion>
  Before [$CsoundVersion +1]
  After [$CsoundVersion -1]
</CsVersion>	
```

**Comment by jpffitch** [comment]
In your example the define is not in an orc or score; it also has no effect in a CsVersion section.  You have misunderstood csoudf macros

**Comment by nogothenogo** [comment]
Maybe the misunderstanding comes because the compiler directive ifdef works any where.
I use this to place large comment blocks into the code at any place and CSound seems to accept it as a comment if the condition is not defined.
