### ISSUE TITLE
Issue: system_i on windows does only one command in {{}} brackets

### ISSUE THREAD

**Issue by nogothenogo** [csound/csound#625]
On windows system_i can execute system commands, but not as stated in the manual, line by line enclosed in brackets. It just executes one command at a time even with the brackets.

As a workaround you can call system_i for each line of a *.bat script or put the commands into a *.bat script and call this one.

`ires system_i 1, {{ pause }}, 0`
works
`ires system_i 1, {{ pause`
`pause }}, 0`
works not.

**Comment by jpffitch** [comment]
I do not have a windows system but I suspect the Microsoft implementation of <i>system</i> is such

**Comment by nogothenogo** [comment]
Maybe a hint about this windows issue in the manual would be nice and save some time to people who try it as given in the manual? ;)
