### ISSUE TITLE
Issue; Labels do only understand english

### ISSUE THREAD

**Issue by nogothenogo** [csound/csound#626]
Labels do only understand english, if non-english characters appear in the label-name Csound fails.

`Channels:`
valid
`Kanäle:`
invalid

maybe this is a bug or enhancement request, i dont know, thanks any way :D

**Comment by jpffitch** [comment]
Csound is ASCII based and non-ASCII characters are not valid in variables or labels.

Personally I have no plans to change this; it will take strong arguments for a mind change.
