### ISSUE TITLE
tablewa kstart reset (bug in csound 6, worked in csound 5.19)

### ISSUE THREAD

**Issue by Oeyvind** [csound/csound#627]
The tablewa opcode behaviour has changed from csound 5 to csound 6.
The change is in the behaviour of the kstart parameter. 

In csound 5, the kstart value was not reinitialized between instrument calls.
In csound 6 kstart always starts at zero.
The csound 5 behaviour allowed continuous writing to a table, with each call to the table writing instrument continuing where the previous instrument instance left off. This is preferable.

The following csd demonstrates the change.
Tested with Csound 6.07, csound 6.03 (both behaving the same, kstart starting at zero with each instrument instance), 
and with csound 5.19 (giving the desired behaviour, kstart continues from where the previous instrument instance left off)

<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

	sr	=	44100
	kr	=	441
	ksmps	=	100
	nchnls	=	2

	giSine		ftgen	0, 0, 65537, 10, 1					; sine wave
        giAudioTable    ftgen   0, 0, 8388608, 2, 0 ; empty table, size 8388608 equals 190 seconds at 44.1kHz sr

;********************************************
	instr 1
        a1	oscil	0.5, 440, giSine
	gkstart tablewa giAudioTable, a1/0dbfs, 0        ;write audio a1 to table 
	printk2 gkstart
	outs	a1, a1
	endin
;********************************************
</CsInstruments>

<CsScore>

e
</CsScore>
</CsoundSynthesizer>

**Comment by Oeyvind** [comment]
... moreover, the koff parameter is incrementally added to the write index (as opposed to being a constant offset). The following example has a ksmps of 100, and an offset of 10. I would expect it to print the numbers 110, 210, 310, ... however, it prints 110, 220, 330, ...

<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

	sr	=	44100
	kr	=	441
	ksmps	=	100
	nchnls	=	2

	giSine		ftgen	0, 0, 65537, 10, 1					
        giAudioTable    ftgen   0, 0, 8388608, 2, 0 ; empty table, size 8388608 equals 190 seconds at 44.1kHz sr
        
	instr 1
        a1	oscil	0.5, 440, giSine
	gkstart tablewa giAudioTable, a1/0dbfs, 10        ;write audio a1 to table 
	printk2 gkstart
	outs	a1, a1
	endin

</CsInstruments>


<CsScore>
i1 0 .01
i1 2 .01

e
</CsScore>
</CsoundSynthesizer>

**Comment by vlazzarini** [comment]
Fixed in GIT. Do you have a means to try it?

**Comment by Oeyvind** [comment]
I did try to build, but the windows mingw64 build has become unmanageable
for me after all the recent additions of all bells and whistles.
(would it be possible to wish for a minimal build alternative, like we had
in the beginning of March? that one was a godsend really!)
Even if the build can not fully complete, I do get new versions of
csound64.dll and all plugin dlls, so I tried to copy these into my
excisting install.
It complains about missing lua51.dll and libwinpthread-1.dll, but otherwise
seems to run ok.
With this version, the tablewa behaviour is not changed, it still resets
kstart each time the instrument is called.
I did pull from develop btw.


2016-04-08 19:18 GMT+02:00 vlazzarini <notifications@github.com>:

**Comment by rorywalsh** [comment]
pthread should be linking statically? If this has been disabled it means we
may once again have issue with Csound loading in different VST hosts. Btw,
are you using your own build script. Here is the one I use. It disables
most of the features that I don't need. Try deleting the csound-mingw64
dir, then copy and paste this text into a custombuild.sh file and use that
to build instead.

#!/bin/bash

mkdir csound-mingw64
cd csound-mingw64
cmake ../.. -DCMAKE_TOOLCHAIN_FILE=../Toolchain-mingw64.cmake
 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=dist
-DCUSTOM_CMAKE=../Custom-mingw64.cmake -DUSE_GETTEXT=0
-DSWIG_DIR=C:\msys2\mingw64\share\swig\3.0.6 -G "MSYS Makefiles"
 -DUSE_CURL=0 -DBUILD_FLUID_OPCODES=1 -DBUILD_LUA_OPCODES=0
-DBUILD_LUA_INTERFACE=0 -DBUILD_CSOUND_AC_LUA_INTERFACE=0
-DBUILD_OSC_OPCODES=1 -DBUILD_CSOUND_AC_PYTHON_INTERFACE=0
-DBUILD_PYTHON_INTERFACE=0 -DBUILD_PYTHON_OPCODES=1 -DBUILD_CSOUND_AC=0
make -j4 install.

**Comment by Oeyvind** [comment]
Thanks for the custom build script Rory, but it seems it will use MSVC, and
then a whole lot of other errors follows:

Administrator@HF-31335 MINGW64 /c/Source/csound/mingw64
$ ./custombuild.sh
-- Building for: Visual Studio 10 2010
-- The C compiler identification is MSVC 16.0.40219.1
...

Maybe I'll just try to pull the build script from early March and see if
that still works.
Any reason why it should not?


2016-04-08 23:50 GMT+02:00 Rory Walsh <notifications@github.com>:

> pthread should be linking statically? If this has been disabled it means we
> may once again have issue with Csound loading in different VST hosts. Btw,
> are you using your own build script. Here is the one I use. It disables
> most of the features that I don't need. Try deleting the csound-mingw64
> dir, then copy and paste this text into a custombuild.sh file and use that
> to build instead.
>
> #!/bin/bash
>
> mkdir csound-mingw64
> cd csound-mingw64
> cmake ../.. -DCMAKE_TOOLCHAIN_FILE=../Toolchain-mingw64.cmake
> -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=dist
> -DCUSTOM_CMAKE=../Custom-mingw64.cmake -DUSE_GETTEXT=0
> -DSWIG_DIR=C:\msys2\mingw64\share\swig\3.0.6 -G "MSYS Makefiles"
> -DUSE_CURL=0 -DBUILD_FLUID_OPCODES=1 -DBUILD_LUA_OPCODES=0
> -DBUILD_LUA_INTERFACE=0 -DBUILD_CSOUND_AC_LUA_INTERFACE=0
> -DBUILD_OSC_OPCODES=1 -DBUILD_CSOUND_AC_PYTHON_INTERFACE=0
> -DBUILD_PYTHON_INTERFACE=0 -DBUILD_PYTHON_OPCODES=1 -DBUILD_CSOUND_AC=0
> make -j4 install.
>

**Comment by Oeyvind** [comment]
Worked nicely

2016-04-09 1:04 GMT+02:00 Oeyvind Brandtsegg <obrandts@gmail.com>:

> Thanks for the custom build script Rory, but it seems it will use MSVC,
> and then a whole lot of other errors follows:
>
> Administrator@HF-31335 MINGW64 /c/Source/csound/mingw64
> $ ./custombuild.sh
> -- Building for: Visual Studio 10 2010
> -- The C compiler identification is MSVC 16.0.40219.1
> ...
>
> Maybe I'll just try to pull the build script from early March and see if
> that still works.
> Any reason why it should not?
>
>
> 2016-04-08 23:50 GMT+02:00 Rory Walsh <notifications@github.com>:
>
>> pthread should be linking statically? If this has been disabled it means
>> we
>> may once again have issue with Csound loading in different VST hosts. Btw,
>> are you using your own build script. Here is the one I use. It disables
>> most of the features that I don't need. Try deleting the csound-mingw64
>> dir, then copy and paste this text into a custombuild.sh file and use that
>> to build instead.
>>
>> #!/bin/bash
>>
>> mkdir csound-mingw64
>> cd csound-mingw64
>> cmake ../.. -DCMAKE_TOOLCHAIN_FILE=../Toolchain-mingw64.cmake
>> -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=dist
>> -DCUSTOM_CMAKE=../Custom-mingw64.cmake -DUSE_GETTEXT=0
>> -DSWIG_DIR=C:\msys2\mingw64\share\swig\3.0.6 -G "MSYS Makefiles"
>> -DUSE_CURL=0 -DBUILD_FLUID_OPCODES=1 -DBUILD_LUA_OPCODES=0
>> -DBUILD_LUA_INTERFACE=0 -DBUILD_CSOUND_AC_LUA_INTERFACE=0
>> -DBUILD_OSC_OPCODES=1 -DBUILD_CSOUND_AC_PYTHON_INTERFACE=0
>> -DBUILD_PYTHON_INTERFACE=0 -DBUILD_PYTHON_OPCODES=1 -DBUILD_CSOUND_AC=0
>> make -j4 install.
>>

**Comment by Oeyvind** [comment]
All compiled without error with  build.sh and Custom-mingw64.cmake taken
from commit 6d3124c8a52cc4479f9f30c7a220faf3fcc1d461 (Feb 27th).
It will still complain about missing libwinpthread-1.dll when Csound starts
(!).

But the bug in tablewa still remains with this build.


2016-04-09 1:18 GMT+02:00 Oeyvind Brandtsegg <obrandts@gmail.com>:

> Worked nicely
>
> 2016-04-09 1:04 GMT+02:00 Oeyvind Brandtsegg <obrandts@gmail.com>:
>
>> Thanks for the custom build script Rory, but it seems it will use MSVC,
>> and then a whole lot of other errors follows:
>>
>> Administrator@HF-31335 MINGW64 /c/Source/csound/mingw64
>> $ ./custombuild.sh
>> -- Building for: Visual Studio 10 2010
>> -- The C compiler identification is MSVC 16.0.40219.1
>> ...
>>
>> Maybe I'll just try to pull the build script from early March and see if
>> that still works.
>> Any reason why it should not?
>>
>>
>> 2016-04-08 23:50 GMT+02:00 Rory Walsh <notifications@github.com>:
>>
>>> pthread should be linking statically? If this has been disabled it means
>>> we
>>> may once again have issue with Csound loading in different VST hosts.
>>> Btw,
>>> are you using your own build script. Here is the one I use. It disables
>>> most of the features that I don't need. Try deleting the csound-mingw64
>>> dir, then copy and paste this text into a custombuild.sh file and use
>>> that
>>> to build instead.
>>>
>>> #!/bin/bash
>>>
>>> mkdir csound-mingw64
>>> cd csound-mingw64
>>> cmake ../.. -DCMAKE_TOOLCHAIN_FILE=../Toolchain-mingw64.cmake
>>> -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=dist
>>> -DCUSTOM_CMAKE=../Custom-mingw64.cmake -DUSE_GETTEXT=0
>>> -DSWIG_DIR=C:\msys2\mingw64\share\swig\3.0.6 -G "MSYS Makefiles"
>>> -DUSE_CURL=0 -DBUILD_FLUID_OPCODES=1 -DBUILD_LUA_OPCODES=0
>>> -DBUILD_LUA_INTERFACE=0 -DBUILD_CSOUND_AC_LUA_INTERFACE=0
>>> -DBUILD_OSC_OPCODES=1 -DBUILD_CSOUND_AC_PYTHON_INTERFACE=0
>>> -DBUILD_PYTHON_INTERFACE=0 -DBUILD_PYTHON_OPCODES=1 -DBUILD_CSOUND_AC=0
>>> make -j4 install.
>>>

**Comment by Oeyvind** [comment]
I also tried resetting the repo to make sure it is clean to the latest
commit, then dropped in the build and make file from Feb 27 and rebuilt.
Same behaviour.
The make file says explicitly
set(BUILD_STATIC_LIBRARY ON)
So why does it need libwinpthread-1.dll? Is this hardcoded somewhere?

2016-04-09 1:46 GMT+02:00 Oeyvind Brandtsegg <obrandts@gmail.com>:

> All compiled without error with  build.sh and Custom-mingw64.cmake taken
> from commit 6d3124c8a52cc4479f9f30c7a220faf3fcc1d461 (Feb 27th).
> It will still complain about missing libwinpthread-1.dll when Csound
> starts (!).
>
> But the bug in tablewa still remains with this build.
>
>
> 2016-04-09 1:18 GMT+02:00 Oeyvind Brandtsegg <obrandts@gmail.com>:
>
>> Worked nicely
>>
>> 2016-04-09 1:04 GMT+02:00 Oeyvind Brandtsegg <obrandts@gmail.com>:
>>
>>> Thanks for the custom build script Rory, but it seems it will use MSVC,
>>> and then a whole lot of other errors follows:
>>>
>>> Administrator@HF-31335 MINGW64 /c/Source/csound/mingw64
>>> $ ./custombuild.sh
>>> -- Building for: Visual Studio 10 2010
>>> -- The C compiler identification is MSVC 16.0.40219.1
>>> ...
>>>
>>> Maybe I'll just try to pull the build script from early March and see if
>>> that still works.
>>> Any reason why it should not?
>>>
>>>
>>> 2016-04-08 23:50 GMT+02:00 Rory Walsh <notifications@github.com>:
>>>
>>>> pthread should be linking statically? If this has been disabled it
>>>> means we
>>>> may once again have issue with Csound loading in different VST hosts.
>>>> Btw,
>>>> are you using your own build script. Here is the one I use. It disables
>>>> most of the features that I don't need. Try deleting the csound-mingw64
>>>> dir, then copy and paste this text into a custombuild.sh file and use
>>>> that
>>>> to build instead.
>>>>
>>>> #!/bin/bash
>>>>
>>>> mkdir csound-mingw64
>>>> cd csound-mingw64
>>>> cmake ../.. -DCMAKE_TOOLCHAIN_FILE=../Toolchain-mingw64.cmake
>>>> -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=dist
>>>> -DCUSTOM_CMAKE=../Custom-mingw64.cmake -DUSE_GETTEXT=0
>>>> -DSWIG_DIR=C:\msys2\mingw64\share\swig\3.0.6 -G "MSYS Makefiles"
>>>> -DUSE_CURL=0 -DBUILD_FLUID_OPCODES=1 -DBUILD_LUA_OPCODES=0
>>>> -DBUILD_LUA_INTERFACE=0 -DBUILD_CSOUND_AC_LUA_INTERFACE=0
>>>> -DBUILD_OSC_OPCODES=1 -DBUILD_CSOUND_AC_PYTHON_INTERFACE=0
>>>> -DBUILD_PYTHON_INTERFACE=0 -DBUILD_PYTHON_OPCODES=1 -DBUILD_CSOUND_AC=0
>>>> make -j4 install.
>>>>

**Comment by vlazzarini** [comment]
Sorry, a typo in the fixed code... now it should be OK. Second example prints
```
 i1   110.00000
 i1   210.00000
 i1   310.00000
 i1   410.00000
B  0.000 ..  2.000 T  2.000 TT  2.000 M:      0.5      0.5
 i1   520.00000
 i1   620.00000
 i1   720.00000
 i1   820.00000
```

starts at 100 + offset and increments by 100 then continues from the next increment with an added 10 as offset.

**Comment by Oeyvind** [comment]
Thanks. Tested and works here too.

2016-04-09 8:13 GMT+02:00 vlazzarini <notifications@github.com>:

**Comment by rorywalsh** [comment]
I know this bug is fixed,(thanks Victor), but regarding the libpthread issue, I think it must have something to do with one of the plugin opcodes. I built here just now and do not have those problems, but I'm not building any of the CsoundAC, CsoundVST, or Lua libraries. Note that fltk works just fine for me too. No crash with my own build.
