### ISSUE TITLE
csound~ 1.1.3 and Csound6_x64_6.07.0rc2

### ISSUE THREAD

**Issue by merlinusambrosius** [csound/csound#628]
Using the new build Csound6_x64_6.07.0rc2
csound~ 1.1.3 
Max/MSP 7.2.1

getting an error:
newobj: csound~: No such object

I'm assuming this csound~ installer is not built against the new x64 Csound build for Windows?

**Comment by unriginal** [comment]
It isn't. I hadn't planned on building it until 6.07 was out of beta, but
my Windows environment needs updating so I'll give it a look.

**Comment by rorywalsh** [comment]
Good luck with this. It will involve a bit of work considering that Mingw64 is unsupported by Cycling74. My attempts to build even the simplest of examples that ship with Max SDK using Mingw64 have all failed in the past. I would start there before trying the Csound object. If you can get one of the included examples building as 64bit then you should be good to go.

**Comment by gogins** [comment]
If you build with Visual Studio, link with Csound using only the C API and
csound64.lib, and put all dependencies identified with depends.exe in your
bin dir, it should work fine. Both CsoundQt and csound.node for Windows x64
are built this way.

Regards,
Mike
On Apr 8, 2016 11:23 AM, "Rory Walsh" <notifications@github.com> wrote:

Good luck with this. It will involve a bit of work considering that Mingw64
is unsupported by Cycling74. My attempts to build even the simplest of
examples that ship with Max SDK using Mingw64 have all failed in the past.
I would start there before trying the Csound object. If you can get one of
the included examples building as 64bit then you should be good to go.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/csound/csound/issues/628#issuecomment-207307846>

**Comment by merlinusambrosius** [comment]
Trying my hand at it in Visual Studio Community 2015, getting:

Error C1083 Cannot open include file: 'MacTypes.h': No such file or
directory csound~
x64 e:\downloads\max-sdk-7.1.0\max-sdk-7.1.0\source\c74support\max-includes\ext_prefix.h
149

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-2200-b>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-2200-b>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by rorywalsh** [comment]
Sorry, I really can't help. The only times I've ever built csound~ on windows was using the cmake/mingw build system that is supported by Csound. You're in uncharted territory here. Hopefully Mike can help.

**Comment by unriginal** [comment]
I've built a version of csound~ with 6.0.7, and uploaded it here:
https://drive.google.com/open?id=0B1NeDv6k4ooXZTc4elNPTEh3SFU

You'll have to put it in a place where Max can find it. As far as getting an error where Max can't find the object, it seems like 64-bit Max won't recognize the external unless the extension is .mxe64 (as opposed to just .mxe).

If anyone would like my notes on building csound~ in Visual Studio (just csound~, not Csound as a whole), I'd be happy to consolidate my notes and share them.

**Comment by merlinusambrosius** [comment]
Thanks a lot, man; you're a lifesaver!  I sure wouldn't mind learning how to build it in VS.

**Comment by rorywalsh** [comment]
Great stuff! Yes please regarding the notes. We can as them to the existing
build instructions.

**Comment by gogins** [comment]
That's great, thank you for pursuing this.

Regards,
Mike

**Comment by merlinusambrosius** [comment]
It was working great for a bit, now I'm getting this:
Error 126 loading external csound~

**Comment by unriginal** [comment]
Ack, that's weird. I've uploaded a new version in the same place. Let me
know how that one works/ if the same thing happens. I haven't been using
csound~ that much lately, but I'll spend a few hours with it over the next
couple of days to see if I can reproduce this issue.

Link, for convenience:(
https://drive.google.com/open?id=0B1NeDv6k4ooXZTc4elNPTEh3SFU).

On Mon, May 2, 2016 at 11:53 PM, merlinusambrosius <notifications@github.com

**Comment by merlinusambrosius** [comment]
The new version works.  Reading over Davis' comments on the issue, I guess it doesn't find the csound *.dll file for some reason.  I'm a little out of practice with csound myself, owing to distractions from other projects.  Soon to be amended, however as I have some new ideas in my head that I want to try.  Thanks again.

**Comment by jpffitch** [comment]
Can this be closed now?

**Comment by merlinusambrosius** [comment]
Yes, the issue has been resolved.

**Comment by alfonso73** [comment]
Great! Finally we have csound~.mxe64!
Thanks everybody!
@unriginal can you share the VS project?
thanks

**Comment by vlazzarini** [comment]
Would you be able to provide this as a download for other people?
========================
Dr Victor Lazzarini
Dean of Arts, Celtic Studies and Philosophy,
Maynooth University,
Maynooth, Co Kildare, Ireland
Tel: 00 353 7086936
Fax: 00 353 1 7086952

**Comment by rorywalsh** [comment]
The download link is in the issues page I referenced earlier..

**Comment by vlazzarini** [comment]
Ok, thanks, can this go in csounds.github.io?
========================
Dr Victor Lazzarini
Dean of Arts, Celtic Studies and Philosophy,
Maynooth University,
Maynooth, Co Kildare, Ireland
Tel: 00 353 7086936
Fax: 00 353 1 7086952

**Comment by rorywalsh** [comment]
As a new news item? Or in the download list?

**Comment by vlazzarini** [comment]
I suppose it should go in the download list.

Victor Lazzarini
Dean of Arts, Celtic Studies, and Philosophy
Maynooth University
Ireland

**Comment by rorywalsh** [comment]
Can we upload the package to releases? We have no idea how long that link
will be live for. @unriginal has not communicated with us much since he
generously contributed the package. Would be great to have clear
instructions on how to do this.

**Comment by vlazzarini** [comment]
Not quite sure we can add anything after the release is finished, but I’ll check.
========================
Dr Victor Lazzarini
Dean of Arts, Celtic Studies and Philosophy,
Maynooth University,
Maynooth, Co Kildare, Ireland
Tel: 00 353 7086936
Fax: 00 353 1 7086952

**Comment by vlazzarini** [comment]
Updated the release with these packages.
========================
Dr Victor Lazzarini
Dean of Arts, Celtic Studies and Philosophy,
Maynooth University,
Maynooth, Co Kildare, Ireland
Tel: 00 353 7086936
Fax: 00 353 1 7086952

**Comment by alfonso73** [comment]
Hi guys,
i think the right way to distribute csound~ is to do a package wich is downloadable by the Max 7 Package Manager.
I can take care of prepare it.
We need a 500*500 px .png file as a image for the csound~ package.
As it is now csound~.mxe64 linked here by @unriginal works perfectly in Max7 64bit.
But the older csound~.mxe does not load in Max7 32bit and gives me the "old" error of not loading pthreadGC2.dll.
I guess we should ask @unriginal instruction on how to compile csound~ correctly.

To prepare a package i need the following things.

1. Working csound~.mxe64 (we have it! thanks @unriginal! )
2. Working csound~.mxe (missing)
3. Working csound~.mxo (for OSX...sadly i don't own a Mac)
4. A 500*500 .png image
5. A quick description of csound~

I can work on 4. and 5. if the community wants me to do it (i'm a poor designer and not a native english speaker but i can try).
On point 2. and 3. i need your help.

best

**Comment by rorywalsh** [comment]
I've updated the downloads section on at csound.github.io

**Comment by rorywalsh** [comment]
Do we really need a 32bit target? We are moving away from 32bit support on
Windows.

**Comment by alfonso73** [comment]
From the Max perspective the typical multiplatform policy recently is Win
32/64 and OSX.
I'm on a 64bit machine and work with 64bit DAW, plugins etc.
But i don't know if there is still some significant demand for Win 32 stuff.

www.elgallorojorecords.com
soundcloud.com/alfonsosantimone
www.facebook.com/alfonsosantimone
