### ISSUE TITLE
Raspbian Python API Bug

### ISSUE THREAD

**Issue by epalaima** [csound/csound#630]
Tried installing Csound on an 8GB SD card set up with Raspbian Jessie. First installed python-dev and swig, after which I installed Csound via the github instrucitons: ([https://github.com/csound/csound/blob/develop/BUILD.md#raspian])
I get the following error, when running a really basic test file I put together: 

ImportError: /home/pi/.local/lib/python2.7/site-packages/_csnd6.so: undefined symbol: PyBytes_As_StringAndSize

No idea why. Seems like I did everything right.

**Comment by rorywalsh** [comment]
You've been on the Csound list where others there have confirmed that they
have had no issues in installing and running Csound on a RPI. If there was
a bug it wouldn't work for them either.

**Comment by jpffitch** [comment]
Can this be closed?  Lacks information

**Comment by rorywalsh** [comment]
I think so. Answers were given on the mailing list.

**Comment by jpffitch** [comment]
Closing as dealt with elsewhere
