### ISSUE TITLE
Python module installers use 2.7 hardcoded path

### ISSUE THREAD

**Issue by mantaraya36** [csound/csound#631]
Although cmake finds python 3.4 and links to it, the python csound module is installed in ~/.local/lib/python2.7

**Comment by nogothenogo** [comment]
i have similar problems on windows i have python 3.x and csoundqt asks for python2.7, i had to rename the py.dll in the csound_64/plugin64 folder. now the popup is gone and i guess the functionality too.

**Comment by fggp** [comment]
Csound is built with Python 2.7 and so the PYTHONPATH used in the install
is for Python2.7. If you put a copy of ctcsound.py in the site-packages
directory of Python 3.x, it should work. ctcsound can be imported in Python
2.7 and in Python 3.x as well, provided it's in their PYTHONPATH.

2016-04-14 23:24 GMT+02:00 nogothenogo <notifications@github.com>:

**Comment by mantaraya36** [comment]
Yes, but I think we are referring to the csnd6 module. Since it depends on
specific version of python, then the installation is performed incorrectly.
My guess is that the path for python 2.7 is hardcoded instead of using the
path detected by cmake for building the module.

**Comment by kunstmusik** [comment]
(I'm not sure how to resolve this, but I think it should be resolved for 6.08 and have assigned the milestone accordingly.)

**Comment by kunstmusik** [comment]
removing from 6.08 for interim, we should consider committing to ctcsound.py for cs7, if so, maybe this issue is moot for the time being

**Comment by fsateler** [comment]
Maybe instead of invoking python [directly](https://github.com/csound/csound/blob/6.07.0/CMakeLists.txt#L50), we could use [FindPythonInterp](https://cmake.org/cmake/help/v3.0/module/FindPythonInterp.html) cmake module and use `${PYTHON_EXECUTABLE}`.

**Comment by dvzrv** [comment]
Given the fact, that [python2 will be EOL in less than 9 months](https://pythonclock.org/), it would be great, if this could be added to a very close milestone again!

**Comment by jpffitch** [comment]
Is this issue now redundant?  I thought we had moved to python3.

**Comment by fggp** [comment]
I created a plugins repository (https://github.com/csound/plugins) to test
the possibility of building plugins separately. Among these plugins,
there's a port of the py opcodes to Python 3. The build have only been
tested on linux, because I don't have a Windows or an OsX machine. If the
py opcodes plugin builds on Windows and OsX as well, it can be integrated
in Csound right now and then, we wouldn't need anymore a hard coded path to
Python 2.7. Nota bene: this would mean that we don't build anymore the
Python wrapper for Python 2.7. This is a backward compatibility break; so
maybe should we wait for Csound 7 before doing this?

François

Le dim. 15 déc. 2019 à 22:33, John ffitch <notifications@github.com> a
écrit :

**Comment by dvzrv** [comment]
Do you have a roadmap for the release of csound 7?
It would of course be great, to have a python3 ready plugin available also for the current release (i.e. >= 6.13.0), as I will now remove the plugin from the package on Arch Linux for the time being to allow the distribution to remove python2 from the repos in the near future.

**Comment by fggp** [comment]
No definitive roadmap for now. However, you can build some plugins cloning
this repo: https://github.com/csound/plugins. The py (libpy.so) opcodes in
this repo are built for Python3. This way, you can already get rid of
Python2.7 for your package on ArchLinux.

François

Le mer. 25 déc. 2019 à 12:08, David Runge <notifications@github.com> a
écrit :

**Comment by kunstmusik** [comment]
Closing as stale, seems we've moved on to Python3
