### ISSUE TITLE
fast_tanh not found error on ubuntu 15.10 with g++ 5.2.1

### ISSUE THREAD

**Issue by obbayazit** [csound/csound#633]
When csound is compiled in Ubuntu 15.10, it gives fast_tanh undefined error for all the executables  linking libcsound. 

 If the inline command is removed from ../Opcodes/newfils.c, the program compiles fine. This may be a related to g++ C99 support where inline function requires an external definition.  See

- http://stackoverflow.com/questions/19068705/undefined-reference-when-calling-inline-function
- http://stackoverflow.com/questions/16245521/c99-inline-function-in-c-file/16245669#16245669
- https://gcc.gnu.org/onlinedocs/gcc/Inline.html#Inline

**Comment by jpffitch** [comment]
It should be defined in newfils.c

Can you check line 33?
==John

**Comment by vlazzarini** [comment]
The problem is the inline definition. I've added a 'static' which fixes it for me. In git now.

**Comment by jpffitch** [comment]
And comment out the tracing
