### ISSUE TITLE
float builds?

### ISSUE THREAD

**Issue by rorywalsh** [csound/csound#638]
With USE_DOUBLE set to 0 in my cmake settings, Csound is still printing:

Csound version 6.07 (double samples) May  8 2016

Is there something else I need to do to build for floats, or is this just a misprint?

**Comment by jpffitch** [comment]
Do not set USE_DOUBLE -- it needs to be unset

**Comment by vlazzarini** [comment]
It's not a misprint. Make sure -DUSE_DOUBLE=0 when you run cmake, because it's on by default. I've added a message to the cmake config step telling what build it is. On git now.

**Comment by rorywalsh** [comment]
Something is still not right. When I run cmake with the latest cmakelists.txt file I get your new message:

>Building with 32-bit floats", yet when I run my newly created Csound

Yet when I run my newly built Csound it still prints:

>Csound version 6.07 (double samples) May  8 2016 

For what it's worth I'm building on Windows. And I'm cleaning before each new attempt.

**Comment by rorywalsh** [comment]
It turns out my float-version.h was the issue. USE_DOUBLE was defined in there. Removing that definition enables me to build for floats. Thanks for the help.
