### ISSUE TITLE
Get Started Documentation about Opcodes Wrong

### ISSUE THREAD

**Issue by InvncibiltyCloak** [csound/csound#639]
In the [Csound syntax section of the Get Started page](http://csound.github.io/documentation.html#syntax), under the Opcodes subsection, there is an error. In the second paragraph:

> Outputs always appear to the left of an opcode name, while inputs always appear to the right of the opcode name.

In the fourth paragraph:

> Remember that the result of each opcode’s calculations are passed to its output parameter, which is located to the right of the opcode.

I believe the first is correct while the second is wrong, although I have never used Csound. If they are both correct, then there needs to be clarification why this is the case.

**Comment by rorywalsh** [comment]
My bad! You are right, it was a typo. Fixed now.
