### ISSUE TITLE
CsoundQt-d-cs6.2015-11-05.exe has stopped working

### ISSUE THREAD

**Issue by GETBUB** [csound/csound#642]
Hi again!

 Not the end of the world, however, I wanted to inform you that every time I close CsoundQt, I get that error message/crash...

This happens both with the 32 and 64bit versions of CSound 6.07

ASUS F550l Intel Core i7 4500u 1.8 GHZ Windows 8

edit: maybe with the 64bit version of Csound 6.07 it is a different CsoundQt, in any event it was the Qt which came with the respective installation..

**Comment by olenyk** [comment]
Hello,

I would like to verify a similar crash on my x64 machine when closing the current version of CsoundQt.

I ran the process through the debugger and extracted the following information:

Unhandled exception at 0x000000013FDDD17D in CsoundQt-d-cs6.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

The address referenced: 000000013FDDD17D  mov         rax,qword ptr [rbx]

Perhaps this is a null pointer reference? I hope this information proves to be useful.

Thank You,
Ryan Olenyk

**Comment by jpffitch** [comment]
Is this a csound error or csoundQt?

**Comment by rorywalsh** [comment]
CsoundQT as far as I know.

**Comment by olenyk** [comment]
It is specific to CsoundQT, scores compile fine without error from command line. The crash is specific to when you exit the program, scores compile and widgets are fully functional otherwise.

**Comment by jpffitch** [comment]
As this is not a csound issue I am closing it -- csoundQt sould pick it up
