### ISSUE TITLE
Using function-like macro resets line count

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#643]
When attempting, on OS&nbsp;X, to compile

```csound
//
#define MACRO(string) #prints $string#
instr 1
  $MACRO("hello, world")
  error
endin
```

using
```
csound --orc Test.orc --syntax-check-only
```

Csound 6.07 (May 16, 2016) reports the error at line&nbsp;1:

```
error: syntax error, unexpected NEWLINE  (token "
") from file Test.orc (1)
 line 1:
>>>  error <<<
Unexpected untyped word error when expecting a variable
```

I’d expect the error to be reported at line&nbsp;5.

**Comment by jpffitch** [comment]
What it should say is line 1 from line 5.  I will check why it does not 
give the wider context

**Comment by nwhetsell** [comment]
> What it should say is line 1…

Why line&nbsp;1, which contains only a comment?

Deleting `error` from the orchestra lets Csound compile it.

**Comment by jpffitch** [comment]
I misread the original error.  What is (apparently) happening is that 
expaning the macro is treated like a new file (thik #include) so the line 
is 1 in the expansion.  It should get restored to revious value at te ed 
of the expansion but seems not to be; or there is a cached value 
somewhere.   I have had an initial unsuccessful look and was hoping to get 
time today too try again.
  The 1 is in the macro not the main orc

**Comment by jpffitch** [comment]
Fixed in git -- as I tought te estoration was wrong
