### ISSUE TITLE
centroid and pvscent

### ISSUE THREAD

**Issue by Oeyvind** [csound/csound#646]
It seems there is something odd with the centroid opcode. It produces intermittent spikes, both positive and negative. I think this is relatively recent. As an extra comment, centroid and pvscent produce different results. It seems like pvscent is correct. 
[centroid_test.zip](https://github.com/csound/csound/files/286566/centroid_test.zip)

**Comment by vlazzarini** [comment]
Code looks ok. Can we have a CSD showing the problem?

**Comment by Oeyvind** [comment]
Yes, there was a zip attachment to the issue.  Did it get lost? There was a
wave file to use with it too.
27. mai 2016 17.13 skrev "vlazzarini" <notifications@github.com>:

**Comment by vlazzarini** [comment]
Sorry I missed that.

**Comment by vlazzarini** [comment]
Ok, I had a look at this. A couple of things

1) the processes are not identical. pvscent is taking the centroid from the windowed/overlapped analyses, and centroid takes the last 1024 samples, windows and transforms them, calculating the centroid. 

2) having said that, negative numbers are wrong, and I fixed that. 

Now the values are close but not identical. Could you test it? In GIT now.

**Comment by vlazzarini** [comment]
By the way, the pvscent analysis has a 1 hopsize delay in relation to centroid, so if you add

asig delay asig,ioverlap/sr

before centroid, the values will be aligned and you will see that they are quite close.

**Comment by Oeyvind** [comment]
Super. Yes, it works fine here now. And thanks for the info about the
differences between the two methods!

2016-05-27 19:41 GMT+02:00 vlazzarini <notifications@github.com>:

**Comment by vlazzarini** [comment]
I've also written an array version. It takes N/2+1 magnitudes (N is the DFT size) and calculates the centroid. Might come in handy.
