### ISSUE TITLE
Attempting to compile while loop with invalid condition causes segfault

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#647]
When attempting, on OS&nbsp;X, to compile

```csound
iIndex = 0
while iIndex < /* count */ do
  /* statements */
  iIndex += 1
od
```

using
```
csound --orc Test.orc --syntax-check-only
```

Csound 6.07 (May 16, 2016) segfaults:

```
error: syntax error, unexpected DO_TOKEN  (token "do") from file Test.orc (1)
 line 1:
>>>while iIndex < do <<<

csound command: Segmentation fault
```

Although the Csound example is clearly not valid, I use it as a snippet in a [Csound language package for Atom](https://atom.io/packages/language-csound), and inserting the snippet while [linting Csound](https://atom.io/packages/linter-csound) crashes Atom.

**Comment by jpffitch** [comment]
I fixed this some days ago, and the until loop the same
