### ISSUE TITLE
Strange k cycle behaviour

### ISSUE THREAD

**Issue by jmmp2013** [csound/csound#648]
Hello All,
I am working my way through the excellent Csound FLOSS Manual.
In Joachim Heintz's FLOSS 03E04 example, pg.148,  I encountered strange behaviour, not game-stopping, but  perhaps points to a lower-level inconsistency?  In the 03E04_Anagram.csd viewable on this page: http://write.flossmanuals.net/csound/e-arrays/
If I have ksmps = 32, printks seems to omit output when timeinstk == 3,  but not when ksmps == 31.  Indeed different ksmps cause different omissions in the output.
My system is Ubuntu 14.04 LTS, on a 64-bit Intel Core i7.   
( Joachim's system didn't seem to get the problem judging by his exemplar output. )

Another trivial bug:  in print statements using %d - if it has an attached punctuation mark '%d,' or '%d!'  that will result in substitution of numbers in the eight thousands, e.g. 8155, rather than the expected, correct, digit.  However,   '%d ' (with a space), works fine. 

Thanks for all you work on the excellent Csound, and the above mentioned manual.  ( I am currently studying it in order to produce my final assignment in August for a Masters degree:  MMus: Sonic Arts  ) 

John Montgomery, Glassel, Scotland.

**Comment by joachimheintz** [comment]
hi john -

thanks for the feedback!

i ran this example again, and get a similar output to what is printed in 
the floss manual.

do you use CsoundQt?  if so, can you try "Run in Term" instead of "Run"?

if the issue is not related to this, could you pass here two or three 
printouts with different ksmps?

cheers -
	joachim

**Comment by jmmp2013** [comment]
Hello Joachim,

Thanks for your response.
I use emacs 24 and run csound in the standard GNOME Terminal 3.6.2
So I have attached a text file showing outputs from a range of different
ksmps values.
I'm not a very mathematical thinker so you may prefer I try other, more
significant, ksmps values?


:-)
*John Montgomery*
Smiddy Cottage,
Campfield, Glassel,
Banchory.
AB31 4DL

On Sun, May 29, 2016 at 6:34 PM, joachimheintz <notifications@github.com>
wrote:

> hi john -
>
> thanks for the feedback!
>
> i ran this example again, and get a similar output to what is printed in
> the floss manual.
>
> do you use CsoundQt? if so, can you try "Run in Term" instead of "Run"?
>
> if the issue is not related to this, could you pass here two or three
> printouts with different ksmps?
>
> cheers -
> joachim
>
>
> On 29/05/16 02:36, jmmp2013 wrote:
> > Hello All,
> > I am working my way through the excellent Csound FLOSS Manual.
> > In Joachim Heintz's FLOSS 03E04 example, pg.148, I encountered strange
> > behaviour, not game-stopping, but perhaps points to a lower-level
> > inconsistency? In the 03E04_Anagram.csd viewable on this page:
> > http://write.flossmanuals.net/csound/e-arrays/
> > If I have ksmps = 32, printks seems to omit output when timeinstk == 3,
> > but not when ksmps == 31. Indeed different ksmps cause different
> > omissions in the output.
> > My system is Ubuntu 14.04 LTS, on a 64-bit Intel Core i7.
> >
> > ( Joachim's system didn't seem to get the problem judging by his
> > exemplar output. )
> >
> > Another trivial bug: in print statements using %d - if it has an
> > attached punctuation mark '%d,' or '%d!' that will result in
> > substitution of numbers in the eight thousands, e.g. 8155, rather than
> > the expected, correct, digit. However, '%d ' (with a space), works fine.
> >
> > Thanks for all you work on the excellent Csound, and the above mentioned
> > manual. ( I am currently studying it in order to produce my final
> > assignment in August for a Masters degree: MMus: Sonic Arts )
> >
> > John Montgomery, Glassel, Scotland.
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/csound/csound/issues/648>, or mute the thread
> > <
> https://github.com/notifications/unsubscribe/ACGDqh2CP1NMPZAsPic6WUsycfJSp69sks5qGN-IgaJpZM4IpL5f
> >.
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/csound/csound/issues/648#issuecomment-222372551>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AEs3rdsJbqo6Vyd92MQYatB3To8Ys_T6ks5qGc4PgaJpZM4IpL5f>
> .
>



WITH KSMPS == 32 --------------------------------------------------
> csound 03E04_Anagram.csd
virtual_keyboard real time MIDI plugin for Csound
0dBFS level = 32768.0
Csound version 6.07 (double samples) May 20 2016
libsndfile-1.0.25
WARNING: could not open library '/usr/local/lib/csound/plugins64-6.0/libstkops.so' (/usr/lib/x86_64-linux-gnu/libstk.so.0: undefined symbol: _ZN7RtAudio10openStreamEPNS_16StreamParametersES1_mjPjPFiPvS3_jdjS3_ES3_PNS_13StreamOptionsEPFvN7RtError4TypeERKSsE)
UnifiedCSD:  03E04_Anagram.csd
STARTING FILE
Creating options
Creating orchestra
Creating score
rtaudio: ALSA module enabled
rtmidi: ALSA Raw MIDI module enabled
sorting score ...
	... done
--Csound version 6.07 (double samples) May 20 2016
displays suppressed
0dBFS level = 32768.0
orch now loaded
audio buffered in 256 sample-frame blocks
not writing to sound disk
SECTION 1:
Filling giArr[] in instr 1 at init time
Printing gSArr[] in instr 2 at init time 
[ sdnocu sducno ndscuo onsdcu ucndos  ]
Printing gSArr[] from instr 3 at perf-time (k): 
[ sdnocu sducno ndscuo onsdcu ucndos  ]
Modifying gSArr[] in instr 4  at init-time
Printing gSArr[] in instr 5 at init time 
[ dnsuco dnuosc usdocn dounsc cosdnu  ]
Modifying gSArr[] in instr 6 at k-cycle 1 .
Printing gSArr[] in instr 7 at k-Cycle 1 
 [s < x + ! ]
Modifying gSArr[] in instr 6 at k-cycle 2 .
Printing gSArr[] in instr 7 at k-Cycle 2 
 [P Z r u U ]
b K c " h Modifying gSArr[] in instr 6 at k-cycle 4 .
Printing gSArr[] in instr 7 at k-Cycle 4 
 [h 9 = # U ]
Score finished in csoundPerform().
inactive allocs returned to freespace
end of score.		   overall amps:      0.0
	   overall samples out of range:        0
0 errors in performance
no sound written to disk

WITH KSMPS == 31 --------------------------------------------------
[[-- cut, same as before-- ]]
not writing to sound disk
SECTION 1:
Filling giArr[] in instr 1 at init time
Printing gSArr[] in instr 2 at init time 
[ scondu cosdun osdcnu sndcuo odscnu  ]
Printing gSArr[] from instr 3 at perf-time (k): 
[ scondu cosdun osdcnu sndcuo odscnu  ]
Modifying gSArr[] in instr 4  at init-time
Printing gSArr[] in instr 5 at init time 
[ nudosc csdnou ncduso csnuod suocnd  ]
Modifying gSArr[] in instr 6 at k-cycle 1 .
Printing gSArr[] in instr 7 at k-Cycle 1 
 [s < x + ! ]
Modifying gSArr[] in instr 6 at k-cycle 2 .
Printing gSArr[] in instr 7 at k-Cycle 2 
 [P Z r u U ]
Modifying gSArr[] in instr 6 at k-cycle 3 .
Printing gSArr[] in instr 7 at k-Cycle 3 
 [b K c " h ]
Modifying gSArr[] in instr 6 at k-cycle 4 .
Printing gSArr[] in instr 7 at k-Cycle 4 
 [h 9 = # U ]
Score finished in csoundPerform().


WITH KSMPS == 29 --------------------------------------------------
[[-- cut, same as before-- ]]
not writing to sound disk
SECTION 1:
Filling giArr[] in instr 1 at init time
Printing gSArr[] in instr 2 at init time 
[ dnusoc scnoud odscnu nosdcu scnuod  ]
Printing gSArr[] from instr 3 at perf-time (k): 
[ dnusoc scnoud odscnu nosdcu scnuod  ]
Modifying gSArr[] in instr 4  at init-time
Printing gSArr[] in instr 5 at init time 
[ dousnc odsunc cnsdou douscn ousncd  ]
Modifying gSArr[] in instr 6 at k-cycle 1 .
Printing gSArr[] in instr 7 at k-Cycle 1 
 [s < x + ! ]
Modifying gSArr[] in instr 6 at k-cycle 2 .
Printing gSArr[] in instr 7 at k-Cycle 2 
 [P Z r u U ]
Modifying gSArr[] in instr 6 at k-cycle 3 .
Printing gSArr[] in instr 7 at k-Cycle 3 
 [b K c " h ]
Modifying gSArr[] in instr 6 at k-cycle 4 .
Printing gSArr[] in instr 7 at k-Cycle 4 
 [h 9 = # U ]
Score finished in csoundPerform().


WITH KSMPS == 28 --------------------------------------------------
[[-- cut, same as before-- ]]
not writing to sound disk
SECTION 1:
Filling giArr[] in instr 1 at init time
Printing gSArr[] in instr 2 at init time 
[ nscudo cundso sdocnu dsucon oucdsn  ]
Printing gSArr[] from instr 3 at perf-time (k): 
[ nscudo cundso sdocnu dsucon oucdsn  ]
Modifying gSArr[] in instr 4  at init-time
Printing gSArr[] in instr 5 at init time 
[ scound dcsnou ncusod cosndu odusnc  ]
Modifying gSArr[] in instr 6 at k-cycle 1 .
Printing gSArr[] in instr 7 at k-Cycle 1 
 [s < x + ! ]
Modifying gSArr[] in instr 6 at k-cycle 2 .
Printing gSArr[] in instr 7 at k-Cycle 2 
 [P Z r u U ]
b K c " h Modifying gSArr[] in instr 6 at k-cycle 4 .
Printing gSArr[] in instr 7 at k-Cycle 4 
 [h 9 = # U ]
Score finished in csoundPerform().


WITH KSMPS == 27 --------------------------------------------------
[[-- cut, same as before-- ]]
not writing to sound disk
SECTION 1:
Filling giArr[] in instr 1 at init time
Printing gSArr[] in instr 2 at init time 
[ ucnsdo uconsd nusocd oucnsd snoduc  ]
Printing gSArr[] from instr 3 at perf-time (k): 
[ ucnsdo uconsd nusocd oucnsd snoduc  ]
Modifying gSArr[] in instr 4  at init-time
Printing gSArr[] in instr 5 at init time 
[ duscon noudsc ucnsdo nsucdo dcsnou  ]
Modifying gSArr[] in instr 6 at k-cycle 1 .
Printing gSArr[] in instr 7 at k-Cycle 1 
 [s < x + ! ]
Modifying gSArr[] in instr 6 at k-cycle 2 .
Printing gSArr[] in instr 7 at k-Cycle 2 
 [P Z r u U ]
b K c " h Modifying gSArr[] in instr 6 at k-cycle 4 .
Printing gSArr[] in instr 7 at k-Cycle 4 
 [h 9 = # U ]
Score finished in csoundPerform().


WITH KSMPS == 26 --------------------------------------------------
[[-- cut, same as before-- ]]
not writing to sound disk
SECTION 1:
Filling giArr[] in instr 1 at init time
Printing gSArr[] in instr 2 at init time 
[ onscud usdocn ocdnsu snoduc dosucn  ]
Printing gSArr[] from instr 3 at perf-time (k): 
[ onscud usdocn ocdnsu snoduc dosucn  ]
Modifying gSArr[] in instr 4  at init-time
Printing gSArr[] in instr 5 at init time 
[ ouscdn soncdu duocns cusodn ouscdn  ]
Modifying gSArr[] in instr 6 at k-cycle 1 .
Printing gSArr[] in instr 7 at k-Cycle 1 
 [s < x + ! ]
Modifying gSArr[] in instr 6 at k-cycle 2 .
Printing gSArr[] in instr 7 at k-Cycle 2 
 [P Z r u U ]
Modifying gSArr[] in instr 6 at k-cycle 3 .
Printing gSArr[] in instr 7 at k-Cycle 3 
 [b K c " h ]
Modifying gSArr[] in instr 6 at k-cycle 4 .
Printing gSArr[] in instr 7 at k-Cycle 4 
 [h 9 = # U ]
Score finished in csoundPerform().


WITH HSMP == 33 --------------------------------------------------
not writing to sound disk
SECTION 1:
Filling giArr[] in instr 1 at init time
Printing gSArr[] in instr 2 at init time 
[ uosdcn sodncu nsduco cosund donsuc  ]
Printing gSArr[] from instr 3 at perf-time (k): 
[ uosdcn sodncu nsduco cosund donsuc  ]
Modifying gSArr[] in instr 4  at init-time
Printing gSArr[] in instr 5 at init time 
[ codsun cuonds nsdcou usncdo usocdn  ]
Modifying gSArr[] in instr 6 at k-cycle 1 .
Printing gSArr[] in instr 7 at k-Cycle 1 
 [s < x + ! ]
Modifying gSArr[] in instr 6 at k-cycle 2 .
Printing gSArr[] in instr 7 at k-Cycle 2 
 [P Z r u U ]
Modifying gSArr[] in instr 6 at k-cycle 3 .
Printing gSArr[] in instr 7 at k-Cycle 3 
 [b K c " h ]
Modifying gSArr[] in instr 6 at k-cycle 4 .
Printing gSArr[] in instr 7 at k-Cycle 4 
 [h 9 = # U ]
Score finished in csoundPerform().

WITH KSMPS == 34 --------------------------------------------------
not writing to sound disk
SECTION 1:
Filling giArr[] in instr 1 at init time
Printing gSArr[] in instr 2 at init time 
[ ocsndu nducos condus cdusno nusodc  ]
Printing gSArr[] from instr 3 at perf-time (k): 
[ ocsndu nducos condus cdusno nusodc  ]
Modifying gSArr[] in instr 4  at init-time
Printing gSArr[] in instr 5 at init time 
[ ucosdn ocdusn soucdn ocndus cnduos  ]
Modifying gSArr[] in instr 6 at k-cycle 1 .
Printing gSArr[] in instr 7 at k-Cycle 1 
 [s < x + ! ]
Modifying gSArr[] in instr 6 at k-cycle 2 .
Printing gSArr[] in instr 7 at k-Cycle 2 
 [P Z r u U ]
Modifying gSArr[] in instr 6 at k-cycle 3 .
Printing gSArr[] in instr 7 at k-Cycle 3 
 [b K c " h ]
Modifying gSArr[] in instr 6 at k-cycle 4 .
Printing gSArr[] in instr 7 at k-Cycle 4 
 [h 9 = # U ]
Score finished in csoundPerform().

WITH KSMPS == 35 --------------------------------------------------
not writing to sound disk
SECTION 1:
Filling giArr[] in instr 1 at init time
Printing gSArr[] in instr 2 at init time 
[ dsncou sodcnu nosucd sduocn noudsc  ]
Printing gSArr[] from instr 3 at perf-time (k): 
[ dsncou sodcnu nosucd sduocn noudsc  ]
Modifying gSArr[] in instr 4  at init-time
Printing gSArr[] in instr 5 at init time 
[ docsnu ndsuoc ducosn dsuocn dcuosn  ]
Modifying gSArr[] in instr 6 at k-cycle 1 .
Printing gSArr[] in instr 7 at k-Cycle 1 
 [s < x + ! ]
Modifying gSArr[] in instr 6 at k-cycle 2 .
Printing gSArr[] in instr 7 at k-Cycle 2 
 [P Z r u U ]
Modifying gSArr[] in instr 6 at k-cycle 3 .
Printing gSArr[] in instr 7 at k-Cycle 3 
 [b K c " h ]
Modifying gSArr[] in instr 6 at k-cycle 4 .
Printing gSArr[] in instr 7 at k-Cycle 4 
 [h 9 = # U ]
Score finished in csoundPerform().


WITH KSMPS == 40 --------------------------------------------------
not writing to sound disk
SECTION 1:
Filling giArr[] in instr 1 at init time
Printing gSArr[] in instr 2 at init time 
[ uocnds sodncu soncdu ndocus csodnu  ]
Printing gSArr[] from instr 3 at perf-time (k): 
[ uocnds sodncu soncdu ndocus csodnu  ]
Modifying gSArr[] in instr 4  at init-time
Printing gSArr[] in instr 5 at init time 
[ ucsnod suoncd cdnosu csonud onudsc  ]
Modifying gSArr[] in instr 6 at k-cycle 1 .
Printing gSArr[] in instr 7 at k-Cycle 1 
 [s < x + ! ]
Modifying gSArr[] in instr 6 at k-cycle 2 .
Printing gSArr[] in instr 7 at k-Cycle 2 
 [P Z r u U ]
b K c " h Modifying gSArr[] in instr 6 at k-cycle 4 .
Printing gSArr[] in instr 7 at k-Cycle 4 
 [h 9 = # U ]
Score finished in csoundPerform().

WITH KSMPS == 48 --------------------------------------------------
not writing to sound disk
SECTION 1:
Filling giArr[] in instr 1 at init time
Printing gSArr[] in instr 2 at init time 
[ usncdo cdunso oucsdn sdonuc cdouns  ]
Printing gSArr[] from instr 3 at perf-time (k): 
[ usncdo cdunso oucsdn sdonuc cdouns  ]
Modifying gSArr[] in instr 4  at init-time
Printing gSArr[] in instr 5 at init time 
[ odnucs dcsuno nouscd dscnuo snuodc  ]
Modifying gSArr[] in instr 6 at k-cycle 1 .
Printing gSArr[] in instr 7 at k-Cycle 1 
 [s < x + ! ]
Modifying gSArr[] in instr 6 at k-cycle 2 .
Printing gSArr[] in instr 7 at k-Cycle 2 
 [P Z r u U ]
Modifying gSArr[] in instr 6 at k-cycle 3 .
Printing gSArr[] in instr 7 at k-Cycle 3 
 [b K c " h ]
h 9 = # U Score finished in csoundPerform().

WITH KSMPS == 47 --------------------------------------------------
not writing to sound disk
SECTION 1:
Filling giArr[] in instr 1 at init time
Printing gSArr[] in instr 2 at init time 
[ conusd cnouds dsonuc nudocs ucdons  ]
Printing gSArr[] from instr 3 at perf-time (k): 
[ conusd cnouds dsonuc nudocs ucdons  ]
Modifying gSArr[] in instr 4  at init-time
Printing gSArr[] in instr 5 at init time 
[ dnoscu sunodc cnsduo nscudo undocs  ]
Modifying gSArr[] in instr 6 at k-cycle 1 .
Printing gSArr[] in instr 7 at k-Cycle 1 
 [s < x + ! ]
P Z r u U Modifying gSArr[] in instr 6 at k-cycle 3 .
Printing gSArr[] in instr 7 at k-Cycle 3 
 [b K c " h ]
Modifying gSArr[] in instr 6 at k-cycle 4 .
Printing gSArr[] in instr 7 at k-Cycle 4 
 [h 9 = # U ]
Score finished in csoundPerform().


with KSMPS == 44 --------------------------------------------------
not writing to sound disk
SECTION 1:
Filling giArr[] in instr 1 at init time
Printing gSArr[] in instr 2 at init time 
[ udscno scudno consdu ucndso sdoncu  ]
Printing gSArr[] from instr 3 at perf-time (k): 
[ udscno scudno consdu ucndso sdoncu  ]
Modifying gSArr[] in instr 4  at init-time
Printing gSArr[] in instr 5 at init time 
[ scnduo usoncd snoudc doscun snoudc  ]
Modifying gSArr[] in instr 6 at k-cycle 1 .
Printing gSArr[] in instr 7 at k-Cycle 1 
 [s < x + ! ]
Modifying gSArr[] in instr 6 at k-cycle 2 .
Printing gSArr[] in instr 7 at k-Cycle 2 
 [P Z r u U ]
Modifying gSArr[] in instr 6 at k-cycle 3 .
Printing gSArr[] in instr 7 at k-Cycle 3 
 [b K c " h ]
Modifying gSArr[] in instr 6 at k-cycle 4 .
Printing gSArr[] in instr 7 at k-Cycle 4 
 [h 9 = # U ]
Score finished in csoundPerform().

------------------------------------------------------------
My actual code, ( my unconventional layout )
------------------------------------------------------------
<CsoundSynthesizer>
<CsOptions>
-dnm0
</CsOptions>
<CsInstruments>
sr        = 44100
ksmps     = 31

giArrlen     = 5
gSArr[]      init giArrlen

opcode StrAngrm,  S, Sj
  ;; Changes the elements of Sin randomly
  Sin, iLen     xin
  if iLen == -1 then
    iLen  strlen Sin
  endif
  Sout = ""
  iCount     = 0
  iRange     = iLen
  loop:
    iRnd    rnd31 iRange-.0001, 0
    iRnd    = int(abs(iRnd))
    Sel     strsub  Sin, iRnd, iRnd+1
    Sout    strcat Sout, Sel
    ;; Remove it from Sin
    Ssub1   strsub  Sin, 0, iRnd
    Ssub2   strsub  Sin, iRnd+1
    Sin     strcat Ssub1,Ssub2
    ;; Cchange range to new length
    iRange  -= 1
  loop_lt iCount, 1, iLen, loop
  xout    Sout
endop


instr 1
  prints "Filling giArr[] in instr %d at init time\n", p1
  iCounter   = 0
  until iCounter == giArrlen do
    S_new        StrAngrm  "csound"
    gSArr[iCounter] = S_new
    iCounter += 1
  od
endin

instr 2
  prints "Printing gSArr[] in instr %d at init time \n[ ", p1
  iCounter     = 0
  until iCounter == giArrlen do
    printf_i "%s ", iCounter+1, gSArr[iCounter]
    iCounter += 1
  od
  prints " ]\n"
endin

instr 3
  printks "Printing gSArr[] from instr %d at perf-time (k): \n[ ",0 , p1
  kCounter     = 0
  until kCounter == giArrlen do
    printf "%s ", kCounter+1, gSArr[ kCounter ]
    kCounter +=1
  od
  printks " ]\n" , 0
  turnoff
endin


instr 4
  prints "Modifying gSArr[] in instr %d  at init-time\n", p1
  iCounter    = 0
  until iCounter == giArrlen do
    S_new   StrAngrm "csound"
    gSArr[iCounter] = S_new
    iCounter += 1
  od
endin

instr 5
  prints "Printing gSArr[] in instr %d at init time \n[ ", p1
  iCounter     = 0
  until iCounter == giArrlen do
    printf_i "%s ", iCounter+1, gSArr[iCounter]
    iCounter += 1
  od
  prints " ]\n"
endin

instr 6
  kCycle    timeinstk
  printks   "Modifying gSArr[] in instr %d at k-cycle %d .\n", 0, p1, kCycle
  kCounter    = 0
  until (kCounter == giArrlen) do
     kChar    random 33, 127
     S_new    sprintfk "%c", int(kChar)
     gSArr[kCounter] strcpyk S_new  ;;  =  S_new  doesn't work.
     kCounter += 1
  od
  if (kCycle > 3) then
    turnoff
  endif
endin


instr 7
  kCycle    timeinstk
  printks   "Printing gSArr[] in instr %d at k-Cycle %d \n [", 0, p1, kCycle
  kCounter  = 0
  until kCounter == giArrlen do
    printf    "%s ", kCounter+1, gSArr[ kCounter ]
    kCounter  += 1
  od
  printks "]\n", 0
  if (kCycle > 3) then
    turnoff
  endif
endin

</CsInstruments>
<CsScore>
i 1 0 1
i 2 0 1
i 3 0 1
i 4 1 1
i 5 1 1
i 6 1 1
i 7 1 1
</CsScore>
</CsoundSynthesizer>

------------------------------------------------------------

**Comment by jpffitch** [comment]
Totally odd!  kCycle gets set to 3 in both instr 6 and 7 but the printks produces no output with ksmps=32.  Time to look closer.  Seems remotely familiar......

**Comment by jpffitch** [comment]
I can get the "correct" answer but I do not understand why!  Need to discuss with others.

**Comment by jpffitch** [comment]
Better fix made and committed

**Comment by jmmp2013** [comment]
Thanks
:-)
John Montgomery, Glassel, Scotland.
