### ISSUE TITLE
Orchestra grammar uses default Flex rule

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#649]
The orchestra grammar [csound_orc.l](https://github.com/csound/csound/blob/develop/Engine/csound_orc.l) seems to use Flex’s default rule, which matches one character and prints it to standard output. This means that syntax-checking

```csound
instr 1
  prints "hello, world\n"
  `@.\$•🎹
endin
scoreline_i {{
  i 1 0 0
  e
}}
```

using

```
csound --orc Test.orc --syntax-check-only
```

shows that the orchestra is correct and prints the characters in line&nbsp;3 to standard output:

```
Syntax check completed.
end of score.		   overall amps:      0.0
	   overall samples out of range:        0
0 errors in performance
Elapsed time at end of performance: real: 0.002s, CPU: 0.002s
`@.\$•🎹
```

Running the orchestra using

```
csound --nosound --orc Test.orc
```

produces

```
--Csound version 6.07 (double samples) May 16 2016
graphics suppressed, ascii substituted
0dBFS level = 32768.0
orch now loaded
audio buffered in 1024 sample-frame blocks
not writing to sound disk
SECTION 1:
new alloc for instr 1:
hello, world
Score finished in csoundPerform().
inactive allocs returned to freespace
end of score.		   overall amps:      0.0
	   overall samples out of range:        0
0 errors in performance
Elapsed time at end of performance: real: 0.001s, CPU: 0.001s
no sound written to disk
`@.\$•🎹
```

**Comment by jpffitch** [comment]
Patced in git -- but there may e a better solution.  Should one ignore 
tese caraxter or give a syntax error?

**Comment by nwhetsell** [comment]
> Should one ignore tese caraxter or give a syntax error?

My personal expectation would be that those characters produce syntax errors (especially since `@.` is not expandable to a power of 2 and `$•🎹` is not a valid use of a macro), but given that backwards compatibility is a main principle in Csound development, I can’t really answer this.

**Comment by jpffitch** [comment]
I have made it a syntax error -- bt gets te line wrong!  Off my one again

**Comment by vlazzarini** [comment]
I'd say syntax error, it trumps any possiblr backwards compatibility in this case

**Comment by nwhetsell** [comment]
This may be a related issue. Running

```csound
instr 1
  print ¬0
endin
scoreline_i {{
  i 1 0 0
  e
}}
```

using

```
csound --nosound --orc Test.orc
```

results in

```
--Csound version 6.07 (double samples) May 16 2016
graphics suppressed, ascii substituted
0dBFS level = 32768.0
orch now loaded
audio buffered in 1024 sample-frame blocks
not writing to sound disk
SECTION 1:
new alloc for instr 1:
instr 1:  #i0 = -1.000
Score finished in csoundPerform().
inactive allocs returned to freespace
end of score.		   overall amps:      0.0
	   overall samples out of range:        0
0 errors in performance
Elapsed time at end of performance: real: 0.002s, CPU: 0.002s
no sound written to disk
?
```

Note the question mark appended to the output. Changing the `¬` to a `~` eliminates the question mark from the output.

**Comment by jpffitch** [comment]
I do not see a ?
Are you using the version from git?

**Comment by nwhetsell** [comment]
> Are you using the version from git?

The version information in the output is “Csound version 6.07 (double samples) May 16 2016”.

**Comment by jpffitch** [comment]
Today is 6 June

**Comment by nwhetsell** [comment]
Where I am it’s 7&nbsp;June. I wasn’t aware the date stamps in the output were updated on each build. I suppose this means this means that no, I am not using the version from git.

**Comment by vlazzarini** [comment]
Works here. I get a syntax error:
```
error: syntax error, unexpected ERROR_TOKEN, expecting NEWLINE or ','  (token "?") from file syntax.csd (1)
 line 7:
>>>  print ? <<<
```

**Comment by nwhetsell** [comment]
When using a `¬`, I get the exact same error as @vlazzarini in the most recent build of Csound:

```
Csound version 6.07 (double samples) Jun 12 2016
libsndfile-1.0.26
orchname:  Test.orc

error: syntax error, unexpected ERROR_TOKEN, expecting NEWLINE or ','  (token "?") from file Test.orc (1)
 line 1:
>>>  print ? <<<
Parsing failed due to invalid input!
Stopping on parser failure
cannot compile orchestra
end of score.		   overall amps:      0.0
	   overall samples out of range:        0
1 errors in performance
Elapsed time at end of performance: real: 0.001s, CPU: 0.001s
no sound written to disk
```

**Comment by jpffitch** [comment]
Te problem I see is rgat the character ¬ comes as two characters 0xc2 and 
0xac in the input file (according to od)


0000000   i   n   s   t   r       1  \n           p   r   i   n   t
            6e69    7473    2072    0a31    2020    7270    6e69    2074
0000020 302 254   0  \n   e   n   d   i   n  \n   s   c   o   r   e   l
            acc2    0a30    6e65    6964    0a6e    6373    726f    6c65


Bt thelexer expects one character (I tink)  The lexer looks orrect to me 
but is nt triggered
   I need advice from a character code expert

**Comment by nwhetsell** [comment]
It looks like [csound_orc.l](https://github.com/csound/csound/blob/9f53f3c810e6c8d523fc79d0f8f51a46f08c3016/Engine/csound_orc.l) is encoded using [ISO/IEC 8859-1](https://en.wikipedia.org/wiki/ISO/IEC_8859-1) (also called ISO Latin&nbsp;1). In this encoding, the ¬ character is represented by a single byte with hexadecimal value AC, octal value 254. These days, most text editors encode files using UTF-8 by default. In UTF-8, the ¬ character is represented by a 2-byte sequence: hexadecimal C2&nbsp;AC, octal 302&nbsp;254 (which is in line&nbsp;3 of od’s output).

I believe one way to ensure backward compatibility with ISO/IEC 8859-1–encoded orchestras and let UTF-8–encoded orchestras use ¬ characters is to replace [line&nbsp;266 of csound_orc.l](https://github.com/csound/csound/blob/9f53f3c810e6c8d523fc79d0f8f51a46f08c3016/Engine/csound_orc.l#L266) with

```
\xC2?\xAC{OPTWHITE}"\n"? {
```

The regex pattern `\xC2?\xAC` checks for an optional C2 byte followed by an AC byte, which should match both UTF-8 and ISO/IEC 8859-1 encoded ¬ characters.

**Comment by jpffitch** [comment]
I had already tried a variant of that but must have had a typo as that works; thanks
