### ISSUE TITLE
Add csound64.lib import library to the Windows installer

### ISSUE THREAD

**Issue by gogins** [csound/csound#651]
Add the "csound64.lib" import library for the "csound64.dll" shared library to the Windows installer, to enable the use of the Csound API with other compilers than mingw.

**Comment by gogins** [comment]
Done for the next release. At some point I will post a beta installer containing this.

**Comment by rorywalsh** [comment]
Thanks Mike. That would be very useful.

**Comment by gogins** [comment]
Make sure this is really happening for 6.08...

**Comment by gogins** [comment]
Done for next release.
