### ISSUE TITLE
Escape sequences in strings

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#652]
I’m trying to understand exactly how escape sequences in Csound strings work. Csound has two kinds of string literals: quoted strings enclosed in `"`, and braced strings beginning with `{{` and ending with `}}`. I believe the general idea is that braced strings can contain newlines, and quoted strings can’t.

After some experimentation, I’ve found that the [C escape sequences](https://en.wikipedia.org/wiki/Escape_sequences_in_C#Table_of_escape_sequences) `\a`, `\b`, `\t`, `\f`, `\n`, `\v`, and `\r` work the same in [`puts`](http://csound.github.io/docs/manual/puts.html) and [`prints`](http://csound.github.io/docs/manual/prints.html), using either quoted or braced strings. Octal sequences of the form `\nnn` do not necessarily work the same way in these opcodes (which makes some sense, since `prints` does its own string processing). Csound does not appear to support hexadecimal sequences.

I also found some other behavior:
* When `\b` ends a string, the character preceding the `\b` is not deleted when printed by either `puts` or `prints`.
* When `\r` ends a string, `prints` overwrites this string until a newline appears.
* Quoted strings containing newlines and line continuations compile, but appear with unexpected characters when printed.
* Braced strings cannot end with an escaped right brace (`\}`). This may be because of an issue with the Csound orchestra lexer, and it’s possible that attempting to compile an orchestra with a braced string like `{{\}}}` will produce a syntax error in the most recent version of Csound.
* The behavior of non-C escape sequences varies in `puts` and `prints`. I believe that `\"` and `\$` work the same in both opcodes, though.
* The behavior of an escaped backslash `\\` varies in `puts` and `prints`, and it does not appear to be possible for a quoted string to end with an escaped backslash.

As far as it goes, is this treatment of escape sequences correct? Is there any documentation (apart from [this](https://csound.github.io/docs/manual/StringsTop.html)) about escape sequences in Csound strings? Even some guidance on where in the Csound source code escape sequences are handled would be very helpful.

Here is the orchestra I used to experiment with escape sequences, and its output.

```csound
instr 1
  puts "\n# Quoted strings with puts", 1
  puts "BELL (U+0007)\a", 1
  puts "BACKSPACE (U+0008) (there should be 1 x) x\bx", 1
  puts "CHARACTER TABULATION (U+0009)\tx", 1
  puts "LINE FEED (U+000A)\n", 1
  puts "LINE TABULATION (U+000B)\v", 1
  puts "FORM FEED (U+000C)\f", 1
  puts "CARRIAGE RETURN (U+000D)\r", 1
  puts "Octal sequences \134\042", 1
  puts "Hex sequences \x5C\x22", 1

  puts "\n# Braced strings with puts", 1
  puts {{BELL (U+0007)\a}}, 1
  puts {{BACKSPACE (U+0008) (there should be 1 x) x\bx}}, 1
  puts {{CHARACTER TABULATION (U+0009)\tx}}, 1
  puts {{LINE FEED (U+000A)\n}}, 1
  puts {{LINE TABULATION (U+000B)\v}}, 1
  puts {{FORM FEED (U+000C)\f}}, 1
  puts {{CARRIAGE RETURN (U+000D)\r}}, 1
  puts {{Octal sequences \134\042}}, 1
  puts {{Hex sequences \x5C\x22}}, 1

  puts "\n# Quoted strings with prints", 1
  prints "BELL (U+0007)\a\n"
  prints "BACKSPACE (U+0008) (there should be 1 x) x\bx\n"
  prints "CHARACTER TABULATION (U+0009)\tx\n"
  prints "LINE FEED (U+000A)\n\n"
  prints "LINE TABULATION (U+000B)\v\n"
  prints "FORM FEED (U+000C)\f\n"
  prints "CARRIAGE RETURN (U+000D)\r\n"
  prints "Octal sequences \134\042\n"
  prints "Hex sequences \x5C\x22\n"

  puts "\n# Braced strings with prints", 1
  prints {{BELL (U+0007)\a\n}}
  prints {{BACKSPACE (U+0008) (there should be 1 x) x\bx\n}}
  prints {{CHARACTER TABULATION (U+0009)\tx\n}}
  prints {{LINE FEED (U+000A)\n\n}}
  prints {{LINE TABULATION (U+000B)\v\n}}
  prints {{FORM FEED (U+000C)\f\n}}
  prints {{CARRIAGE RETURN (U+000D)\r\n}}
  prints {{Octal sequences \134\042\n}}
  prints {{Hex sequences \x5C\x22\n}}

  puts "\n# When \134b ends a string, the preceding character is not deleted", 1
  puts "BACKSPACE (U+0008) (there should be no x) x\b", 1
  puts {{BACKSPACE (U+0008) (there should be no x) x\b}}, 1
  prints "BACKSPACE (U+0008) (there should be no x) x\b\n"
  prints {{BACKSPACE (U+0008) (there should be no x) x\b\n}}

  puts "\n# When \134r ends a string, prints overwrites it until a newline appears", 1
  prints "CARRIAGE RETURN (U+000D)\r"
  prints "overwrite \n"

  puts "\n# Quoted strings with newlines and line continuations compile", 1
  puts "hello,
world\
", 1

  puts "\n# Braced strings cannot end with an escaped right brace", 1
  puts {{\}x}}, 1
  puts {{\}}}, 1
  
  puts "\n# The behavior of other escaped characters varies", 1
  puts "\c\d\e\'\"\?", 1
  prints "\c\d\e\'\"\?\n"
  
  puts "\n# The behavior of an escaped backslash (\134\134) varies", 1
  puts "\\\\x", 1
  prints "\\\\x\n"
  // This should probably print a backslash, but results in a syntax error.
  //puts "\\", 1

  puts "", 1
endin

scoreline_i {{
  i 1 0 0
  e
}}
```

```
--Csound version 6.07 (double samples) May 16 2016
graphics suppressed, ascii substituted
0dBFS level = 32768.0
orch now loaded
audio buffered in 1024 sample-frame blocks
writing 2048-byte blks of shorts to test.aif (AIFF)
SECTION 1:
new alloc for instr 1:

# Quoted strings with puts
BELL (U+0007)
BACKSPACE (U+0008) (there should be 1 x) x
CHARACTER TABULATION (U+0009)	x
LINE FEED (U+000A)

LINE TABULATION (U+000B)

FORM FEED (U+000C)

CARRIAGE RETURN (U+000D)
Octal sequences \"
Hex sequences \x5C\x22

# Braced strings with puts
BELL (U+0007)
BACKSPACE (U+0008) (there should be 1 x) x
CHARACTER TABULATION (U+0009)	x
LINE FEED (U+000A)

LINE TABULATION (U+000B)

FORM FEED (U+000C)

CARRIAGE RETURN (U+000D)
Octal sequences \"
Hex sequences \x5C\x22

# Quoted strings with prints
BELL (U+0007)
BACKSPACE (U+0008) (there should be 1 x) x
CHARACTER TABULATION (U+0009)	x
LINE FEED (U+000A)

LINE TABULATION (U+000B)

FORM FEED (U+000C)

CARRIAGE RETURN (U+000D)
Octal sequences "
Hex sequences x5Cx22

# Braced strings with prints
BELL (U+0007)
BACKSPACE (U+0008) (there should be 1 x) x
CHARACTER TABULATION (U+0009)	x
LINE FEED (U+000A)

LINE TABULATION (U+000B)

FORM FEED (U+000C)

CARRIAGE RETURN (U+000D)
Octal sequences "
Hex sequences x5Cx22

# When \b ends a string, the preceding character is not deleted
BACKSPACE (U+0008) (there should be no x) x
BACKSPACE (U+0008) (there should be no x) x
BACKSPACE (U+0008) (there should be no x) x
BACKSPACE (U+0008) (there should be no x) x

# When \r ends a string, prints overwrites it until a newline appears
overwrite ETURN (U+000D)

# Quoted strings with newlines and line continuations compile
hello,
#line 57
world#sline 58 

# Braced strings cannot end with an escaped right brace
\}x
"

# The behavior of other escaped characters varies
\c\d\e\'"\?
cde'"?

# The behavior of an escaped backslash (\\) varies
\\x
\x

Score finished in csoundPerform().
inactive allocs returned to freespace
end of score.		   overall amps:      0.0
	   overall samples out of range:        0
0 errors in performance
Elapsed time at end of performance: real: 0.004s, CPU: 0.003s
1024 2048 sample blks of shorts written to test.aif (AIFF)
}
```

The final `}` is unexpected—it is similar to the behavior in #649—and is what makes me think the orchestra will produce a syntax error in the latest version of Csound on GitHub.

**Comment by jpffitch** [comment]
Documemted in Strings (Part II. Opcodes Overview)

I think the \b implementatin is correct.  Afaik octal and hex were never considered, but tis s not my code

**Comment by nwhetsell** [comment]
> Documemted in Strings (Part II. Opcodes Overview)

Yes, I’ve read that section of the manual; I included a link to it with my question. Is there any documentation of escape sequences in Csound strings _in addition_ to that section?

> Afaik octal and hex were never considered

Octal sequences seem to be supported by Csound, and they are mentioned in “Strings (Part II. Opcodes Overview)”.

> tis s not my code

If anyone else knows, I’m still very curious about where Csound handles escape sequences.

**Comment by jpffitch** [comment]
I would look at OOps/str_ops.c and OOps/ugrw1.c for a start if I had time.

**Comment by nwhetsell** [comment]
Found it—[`unquote_string`](https://github.com/csound/csound/blob/5e9cccc7c7d45cdde705263735d5c275092f86ad/Engine/csound_orc_compile.c#L119) in [Engine/csound_orc_compile.c](https://github.com/csound/csound/blob/5e9cccc7c7d45cdde705263735d5c275092f86ad/Engine/csound_orc_compile.c).
