### ISSUE TITLE
option for PADsynth GEN

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#655]
is it possible to have an option to disable the printing in GENpadsynth?

**Comment by jpffitch** [comment]
Can you give some examples of the printing you do not want?  Would help to locate

**Comment by tjingboem** [comment]
i am talking about this kind of output:
samplerate:                         48000
p1_function_table_number:             103.0000
p2_score_time:                          0.0000
p3_ftable_size                     131072
p4_gen_id:                             66
p5_fundamental_frequency:             500.0000
p6_partial_bandwidth:                  30.3600
p7_partial_bandwidth_scale_factor:      2.6900
p8_harmonic_stretch:                    2.9900
...................etc

as you can see in context below.
I do think this relevant information, but because i use different harmonic settings etc. in a piece, this text production causes unneede output and slow the system down. 

This is a part of the output:
Render Command ( csound -+msg_color=false -+rtaudio=JACK -o dac:system:playback_ -m135 -j4 --sample-accurate /home/menno/onderzoek/padsynth_onderzoek/tempCsd3944324589655543086.csd --env:SFDIR=/home/menno/onderzoek/padsynth_onderzoek )
UnifiedCSD:  /home/menno/onderzoek/padsynth_onderzoek/tempCsd3944324589655543086.csd
STARTING FILE
Creating orchestra
Creating score
rtmidi: ALSA Raw MIDI module enabled
rtaudio: JACK module enabled
Elapsed time at end of orchestra compile: real: 0.136s, CPU: 0.207s
sorting score ...
	... done
Elapsed time at end of score sort: real: 0.137s, CPU: 0.208s
--Csound version 6.08 (double samples) Sep  8 2016
Multithread performance: insno:  -1  thread 0 of 4 starting.
Multithread performance: insno:  -1  thread 2 of 4 starting.
Multithread performance: insno:  -1  thread 1 of 4 starting.
graphics suppressed, ascii substituted
0dBFS level = 1.0
orch now loaded
audio buffered in 256 sample-frame blocks
system sr: 48000.000000
 0: dac:system:playback_ (system:playback_)
 1: dac:PulseAudio JACK Source:front-left (PulseAudio JACK Source:front-left)
 2: dac:PulseAudio JACK Source:front-right (PulseAudio JACK Source:front-right)
 3: dac:PulseAudio JACK Source:rear-left (PulseAudio JACK Source:rear-left)
 4: dac:PulseAudio JACK Source:rear-right (PulseAudio JACK Source:rear-right)
 5: dac:PulseAudio JACK Source:front-center (PulseAudio JACK Source:front-center)
 6: dac:PulseAudio JACK Source:lfe (PulseAudio JACK Source:lfe)
 7: dac:PulseAudio JACK Source:side-left (PulseAudio JACK Source:side-left)
 8: dac:PulseAudio JACK Source:side-right (PulseAudio JACK Source:side-right)
 9: dac:PulseAudio JACK Source:aux (PulseAudio JACK Source:aux)
writing 512 sample blks of 64-bit floats to dac:system:playback_ 
SECTION 1:
new alloc for instr 3:
new alloc for instr 4:
ftable 101:
ftable 101:	16384 points, scalemax 1.000
               _--'''''--_
            _-'           '-_
          _-                 -_
         .                     .
       _'                       '_
      -                           -
    _'                             '_
   .                                 .
  -                                   -
_'_____________________________________'________________________________________
                                        '_                                     .
                                          .                                   .
                                           -                                 -
                                            '_                             _'
                                              .                           -
                                               -_                       _'
                                                 .                     -
                                                  '.                 .'
                                                    '._           _-'
                                                       -.._____.-'
ftable 102:
ftable 102:	16384 points, scalemax 1.000
                                _'
                              _-  _
                             .
                           .'
                         _-        .
                       _.
                    _.-
                 _.-                .
              _.-
____...---''''__________________________________________________________________
WARNING: rtjack: xrun in real time audio
WARNING: rtjack: xrun in real time audio
B  0.000 ..  0.648 T  0.645 TT  0.645 M:  0.00000  0.00000
new alloc for instr 1:
ftable 103:
samplerate:                         48000
p1_function_table_number:             103.0000
p2_score_time:                          0.0000
p3_ftable_size                     131072
p4_gen_id:                             66
p5_fundamental_frequency:             500.0000
p6_partial_bandwidth:                  30.3600
p7_partial_bandwidth_scale_factor:      2.6900
p8_harmonic_stretch:                    2.9900
p9_profile_shape:                       1
p10_profile_parameter:                  1.0000
partial[  1]:                           0.9100
  partial_Hz:                        1495.0000
  frequency_sample_index_normalized:    0.0311
  partial_frequency_index:           4082
  bandwidth_Hz:                       168.3779
  bandwidth_samples:                    0.0018
partial[  2]:                           0.0000
  partial_Hz:                        2990.0000
  frequency_sample_index_normalized:    0.0623
  partial_frequency_index:           8164
  bandwidth_Hz:                      1086.5652
  bandwidth_samples:                    0.0113
partial[  3]:                           0.4100
  partial_Hz:                        4485.0000
  frequency_sample_index_normalized:    0.0934
  partial_frequency_index:          12247
  bandwidth_Hz:                      3234.0095
  bandwidth_samples:                    0.0337
partial[  4]:                           0.0000
  partial_Hz:                        5980.0000
  frequency_sample_index_normalized:    0.1246
  partial_frequency_index:          16329
  bandwidth_Hz:                      7011.7513
  bandwidth_samples:                    0.0730
partial[  5]:                           0.0000
  partial_Hz:                        7475.0000
  frequency_sample_index_normalized:    0.1557
  partial_frequency_index:          20411
  bandwidth_Hz:                      12779.5170
  bandwidth_samples:                    0.1331
partial[  6]:                           0.7900
  partial_Hz:                        8970.0000
  frequency_sample_index_normalized:    0.1869
  partial_frequency_index:          24494
  bandwidth_Hz:                      20869.4978
  bandwidth_samples:                    0.2174
partial[  7]:                           0.0000
  partial_Hz:                        10465.0000
  frequency_sample_index_normalized:    0.2180
  partial_frequency_index:          28576
  bandwidth_Hz:                      31593.5818
  bandwidth_samples:                    0.3291
partial[  8]:                           1.0000
  partial_Hz:                        11960.0000
  frequency_sample_index_normalized:    0.2492
  partial_frequency_index:          32658
  bandwidth_Hz:                      45247.7727
  bandwidth_samples:                    0.4713
partial[  9]:                           0.0000
  partial_Hz:                        13455.0000
  frequency_sample_index_normalized:    0.2803
  partial_frequency_index:          36741
  bandwidth_Hz:                      62115.1438
  bandwidth_samples:                    0.6470
partial[ 10]:                           0.4800
  partial_Hz:                        14950.0000
  frequency_sample_index_normalized:    0.3115
  partial_frequency_index:          40823
  bandwidth_Hz:                      82467.9401
  bandwidth_samples:                    0.8590
ftable 103:	131072 points, scalemax 1.000
                                                          _
    '
        '     .       '    - .  '_           '                              .
      .             .-                                      _              -
  -             '                             -_                    ' -       .
_'_________.'_____'____.___________.'_-____________.___-_____________-_'_'______
         '-  _          .   _           . '                    . .           '
   -               .           '  .                  .   _ _
       '                                 - _     -  '        .  _ -       _    -
'    -           .        .            '    -         .
                              _                 -             _
                                                  '                '
               .
                                                                        -

**Comment by jpffitch** [comment]
Quietr version in git now  -- untested -- but only prints in -m4 set
==John

**Comment by jpffitch** [comment]
Tested and works as intended -- set -m3 to suppress output

**Comment by gogins** [comment]
Thanks,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com
