### ISSUE TITLE
Quoted strings cannot end with an escaped backslash

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#661]
On OS&nbsp;X, attempting to run

```csound
instr 1
  puts "x\\", 1
endin
scoreline_i {{
  i 1 0 0
  e
}}
```

results in a syntax error:

```
Csound version 6.07 (double samples) Jun 13 2016
libsndfile-1.0.26
orchname:  /Users/nathanwhetsell/Downloads/Test.orc
unterminated string found on line 1 >>"x\\", 1
#line   2
endin
#line   3
scoreline_i {{
  i 1 0 0
  e
}}
#line   7

#line   8<<

error: syntax error, unexpected $end  (token "") from file /Users/nathanwhetsell/Downloads/Test.orc (1)
 line 1:
>>>8 <<<
Parsing failed due to invalid input!
Stopping on parser failure
cannot compile orchestra
end of score.		   overall amps:      0.0
	   overall samples out of range:        0
1 errors in performance
Elapsed time at end of performance: real: 0.001s, CPU: 0.001s
no sound written to disk
```

I’d expect the orchestra to print `x\` to the console. Changing the string to `"x\\y"` lets Csound print `x\y` to the console.

**Comment by jpffitch** [comment]
This is a side effect of trying to catch unterminated strings.  I have remoed tat ceck ad this example works.

Perhaps you can suggest a better fix in flex.  Was
 STRCONST        \"(\\.|[^\"\n])*\"
 STRCONSTe       \"(\\.|[^\"])*$
 
second is error case now removed

**Comment by nwhetsell** [comment]
Just to make sure I understand, in [csound_orc.l](https://github.com/csound/csound/blob/develop/Engine/csound_orc.l), this pattern and its associated action were deleted:

```
STRCONSTe       \"(\\.|[^\"])*$
```

I would do string lexing using an exclusive start condition for quoted strings:

```
%x quoted_string
```

The rules and actions might look like this (not tested)—

```
\"
%{
  BEGIN(quoted_string);
  // Add the quote to the orchestra, and save its location to use in error
  // messages.
%}
<quoted_string>"\\".|[^$"\n\r] // Add this text to the orchestra.
<quoted_string>\"
%{
  BEGIN(INITIAL); // Or yy_pop_state() with the %option stack directive.
  // Add the quote to the orchestra.
%}
<quoted_string>{newline}|<<EOF>>
%{
  // Report an error that this string is missing its terminating ".
%}

<INITIAL,quoted_string>{line_continuation}
%{
  // Handle line continuations.
%}

<INITIAL,quoted_string>\${macro_name}\.?\(
%{
  // Expand function-like macros.
%}

<INITIAL,quoted_string>\${macro_name}\.?
%{
  // Expand object-like macros.
%}
```

—where the `newline`, `line_continuation`, and `macro_name` patterns are defined appropriately. I’m assuming this is in [csound_pre.lex](https://github.com/csound/csound/blob/develop/Engine/csound_pre.lex), of course, but because the preprocessor handles quoted strings by setting `PARM->isString` to `true`, this would probably require significant changes to the preprocessor.

**Comment by jpffitch** [comment]
i have redesigned the string lexing in csound_orc.lex so I understand it and it appears to fix the known issues, but no doubt I have introduced new bugs.

**Comment by nwhetsell** [comment]
After commit 58d4abf, Csound hangs when compiling

```csound
Sstring = "
```

Note that I _must_ end the orchestra with a newline to produce this; the orchestra is two lines, and line&nbsp;2 is empty. Running

```
echo 'Sstring = "' > Test.orc
```

should produce the right orchestra.

**Comment by jpffitch** [comment]
I think this report is wrong.  The string does end in backspace but this  does not delete the previous character but is in the string

**Comment by nwhetsell** [comment]
I’m not sure what you mean about a string ending with a backspace, but I was indeed mistaken about this.
