### ISSUE TITLE
Function-like macros can have 0-length parameter names

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#663]
Compiling

```csound
#define MACRO(arg') #$arg $#
prints "==> $MACRO(1'2)\n"
scoreline_i "e"
```

using

```
csound --nosound --orc Test.orc
```

produces this output

```
Csound version 6.07 (double samples) Jun 20 2016
libsndfile-1.0.26
orchname:  Test.orc
defining argument _MACRO__arg as...#1#
defining argument _MACRO__ as...#2#
Elapsed time at end of orchestra compile: real: 0.001s, CPU: 0.001s
sorting score ...
	... done
Elapsed time at end of score sort: real: 0.001s, CPU: 0.001s
--Csound version 6.07 (double samples) Jun 20 2016
graphics suppressed, ascii substituted
0dBFS level = 32768.0
==> 1 2
orch now loaded
audio buffered in 1024 sample-frame blocks
not writing to sound disk
SECTION 1:
Score finished in csoundPerform().
inactive allocs returned to freespace
end of score.		   overall amps:      0.0
	   overall samples out of range:        0
0 errors in performance
Elapsed time at end of performance: real: 0.001s, CPU: 0.001s
no sound written to disk
```

I would expect compiling the orchestra to fail.

**Comment by jpffitch** [comment]
Looks correct to me.  you declare a macro with two argument, the secnd 
having an empty name, so then it binds 1 to frst arg and 2 to second asnd 
outputs them both.

it may look odd but it is correct and defensible

**Comment by nwhetsell** [comment]
I can’t think of a reason to have a 0-length name, but if it’s generally agreed that this is useful syntax, feel free to close this issue.

**Comment by jpffitch** [comment]
I too cannot thik of a reason but being liberal in semantics seems a good 
idea.  There ae other unpoliced issues like using the same name for two 
macro args which is deterministic but could cause problems

I pefer using my time to fix macros in scores which are iffy in places; I 
have most of the code written now.
