### ISSUE TITLE
table: index type inconsistent with output

### ISSUE THREAD

**Issue by irelefpiz** [csound/csound#665]
I'm using the old DX7-Emulation Instrument by Russel Pinkston in conjuction with the Csound6~ pureData-Object in realtime (under OSX). This works for me without any problems for several years up to Csound version 6.06. Under the new Csound 6.07 I get the following sporadic error (I'm reading 
from pd console):

```
INIT ERROR in instr 1: 
table: index type inconsistent with outpu 
 
a3sig 
tablei.a 
#a130 
1 
1 
0 
1 
 
INIT ERROR in instr 1: 
table: index type inconsistent with outpu 
 
a1sig 
tablei.a 
#a136 
1 
1 
0 
1 
 
		   T 11.73 
 - note deleted.  i1 had 2 init error 
```

This occurs approximately on one about ten realtime events and belongs only to the carrier statements in the instrument code. Non realtime usage of the instrument code seems to work well.

**Comment by irelefpiz** [comment]
Maybe it is a problem with the csound6~ object and Csound 6.07 ?

**Comment by irelefpiz** [comment]
The attached example causes error on my machine (OSX 10.10.5 with Csound 6.07). Open the file "cspd_test1.pd" with pd  (requires the attached file "cspd_test1.csd") and hit the "event" message several times. There are no errors with the same example under Csound 6.06. 

[cspd_test1.zip](https://github.com/csound/csound/files/328563/cspd_test1.zip)

**Comment by jpffitch** [comment]
Can you reproduce in csiund witout PD?

**Comment by irelefpiz** [comment]
No, there is no error with plain Csound. The zip file contain the same example "wihoutPd.csd". This example works well with Csound 6.07 and with Csound 6.06.

**Comment by irelefpiz** [comment]
And no error occurs with "ptablei" in the csd code instead of "tablei".

**Comment by vlazzarini** [comment]
I identified where the problem is, but I am not sure of the reason. The check for asig type is failing
on OOps/ugtabs.c:66. The problem is that I can't reproduce it outside PD, so it might be a memory 
error of some kind. Here are some other diagnostics:

(a) It only happens if we try to reuse an instance: new instances are OK.
(b) the check gets it wrong: ie. it's clearly an asig and if we remove the check, it works OK.
(c) there is a similar check on ptablei, which is reported to pass.
I'll keep at it, but if @jpffitch has any ideas, I'd like to hear them.

**Comment by vlazzarini** [comment]
It's definitely a memory problem. By adding another code line (any, just before tablei), the error goes away. Maybe a run with valgrind would show up something.

**Comment by vlazzarini** [comment]
Valgrind does not show any errors in Csound. So these could be in PD or csound6~, but csound6~ has not changed from 6.06 to 6.07.

Since valgrind is not that great on OSX, I'd appreaciate if it can be run on linux.

**Comment by vlazzarini** [comment]
I've fixed the check so that it is performed on first instantiation only. The possible underlying mem problem has not been addressed but it seems all OK in the Csound part of the code.

**Comment by irelefpiz** [comment]
Many thanks for your work, you are great!
