### ISSUE TITLE
prints bug

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#666]
the line
  prints "%d.\n", 1
returns
  8192.

without the dot after %d it is ok.

csound from recent develop branch on debian.

**Comment by jpffitch** [comment]
Why me?  Never worked on printing.

**Comment by joachimheintz** [comment]
okay, sorry — i thought you had done some works on printing issues recently.  i removed the assignment and leave it to anyone.

**Comment by jpffitch** [comment]
As far as I can see there is no attempt to convert the float 1 to an integer but this is not my code

**Comment by vlazzarini** [comment]
it does not seem to handle floats, just integers anyway. I have hacked a fix for this, but the code is not great to start with. Needs to be rewritten,

**Comment by vlazzarini** [comment]
fixed in GIT.

**Comment by joachimheintz** [comment]
thanks — works for me now, too.

it worked some time before, by the way; i saw the issue at one example i 
did (perhaps two years ago).
