### ISSUE TITLE
Implement a WebAssembly build of Csound

### ISSUE THREAD

**Issue by gogins** [csound/csound#668]
Implement a WebAssembly build of Csound.

[WebAssembly](https://webassembly.github.io/) is a portable executable platform designed to run in Web browsers on various operating systems, and in browser-like execution environments. The WebAssembly spec is under development. When WebAssembly supports pthreads, but not before, i.e. at the post MVP stage, Csound should be ported. It should provide roughly the same JavaScript Csound API as CsoundObj and csound.node (see this [comparison chart](https://drive.google.com/open?id=1C9RqnV5Tlxag5xnMNP1VXO_W-_XirB5BIidASWvhJ9E)) with all the [HTML5 features](https://html5test.com/) of the browser. Ideally, it should be possible to run the same piece on csound.node, Android, and WebAssembly.

**Comment by gogins** [comment]
WASM is at the Browser Preview milestone. That should be completed Q1 2017, then the WASM specification will be finalized and browsers will turn it on. When this happens, Csound for WASM should be ready, and should replace Csound for Emscripten, Csound for PNaCl, csound.node, and probably the CsoundAndroid library.

**Comment by gogins** [comment]
I noticed today that WebAssembly has [completed the browser preview](https://lists.w3.org/Archives/Public/public-webassembly/2017Feb/0002.html) stage and will be "on by default" in browsers from now on (presumably this means upcoming releases).

I would like to see pthreads support before really trying to build Csound for WebAssembly, but it may make sense to get started anyway.

**Comment by gogins** [comment]
I am installing the WebAssembly toolchain on my Windows computer. I installed Microsoft Visual Studio 2017, which is not supposed to work on Windows 8.1 which is what I am running, but it does seem to work and the Clang toolchain is building with MSVCPP right now. 

However, to debug, it is necessary to copy ucrtbased.dll to the PATH. There may be other issues.

**Comment by gogins** [comment]
Installed the WebAssembly toolchain but I still find gaps. In addition to no pthreads:

1. No dynamic linking. This alone prevents me from proceeding and becomes a gating issue.
2. 32-bit address space.

Once again I am holding off on this.

**Comment by kunstmusik** [comment]
All of this has been addressed in the Emscripten build.  The toolchain/build files should be reused for wasm.  I think @eddyc might already be looking int o it.

**Comment by gogins** [comment]
I presume the WebAssembly interface with the JavaScript context is quite
different, see
https://developer.mozilla.org/en-US/docs/WebAssembly/C_to_wasm.

Best,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by gogins** [comment]
More on interfacing native code with the JavaScript context in browsers: http://webassembly.org/docs/gc/.

**Comment by gogins** [comment]
Just to summarize: I am holding off on implementing either Csound or just CsoundAC in WebAssembly until WebAssembly has, in decreasing order of importance:

1. pthreads.
2. Interface generator to produce JavaScript classes or objects from C++ classes or objects.
3. 64 bit address space.

**Comment by eddyc** [comment]
I have just tried to build using emscripten's ASM=1 flag, but unfortunately it is failing at the moment.

**Comment by gogins** [comment]
Others are working on this. I am unassigning myself for now, I may come back to this.

**Comment by gogins** [comment]
I am closing this issue as @hfmanson has implemented at least some of it. I will try to work in the existing code base.
