### ISSUE TITLE
Example orchestra statement in manual does not compile

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#670]
Commit 01928e8, which I believe was intended to address [an issue raised on the Csound mailing list](https://listserv.heanet.ie/cgi-bin/wa?A2=ind1606&L=CSOUND&P=124943), seems to prevent compiling the example statement in [the manual’s section on “Syntax of the Orchestra”](https://csound.github.io/docs/manual/OrchTop.html). For example, compiling

```csound
label: prints "==> labeled statement\n"
scoreline_i "e"
```

fails in Csound 6.07 (Jun 26 2016) and succeeds in Csound 6.07 (May 16 2016).

I think this can be fixed by requiring labels to be followed by one or more whitespace character. Changing [line&nbsp;74 of csound_orc.lex](https://github.com/csound/csound/blob/7923c1f18b4b80f2394e53a9b425fdc476e99506/Engine/csound_orc.lex#L74) from

```
LABEL           ^[ \t]*[a-zA-Z0-9_][a-zA-Z0-9_]*:[ \t]*$  /* VL: added extra checks for after the colon */
```

to 

```
LABEL           ^[ \t]*[a-zA-Z0-9_][a-zA-Z0-9_]*:([ \t\n]+|$)
```

should accomplish this.

This change would fix orchestras that have spaces and tabs between a label and a statement; orchestras with nothing at all between a label and statement would still be broken. Also, this change would require that opcode type annotations not contain whitespace. After this change, this should compile:

```csound-document
<CsoundSynthesizer>
<CsInstruments>
instr 1
label: outs oscil:a(0.5 * 0dbfs,
                    linseg:a(220, p3, 440))
endin
</CsInstruments>
<CsScore>
i 1 0 0.5
e
</CsScore>
</CsoundSynthesizer>
```

This shouldn’t compile:

```csound-document
<CsoundSynthesizer>
<CsInstruments>
instr 1
label: outs oscil:a(0.5 * 0dbfs,
                    linseg: a(220, p3, 440))
endin
</CsInstruments>
<CsScore>
i 1 0 0.5
e
</CsScore>
</CsoundSynthesizer>
```

Note the space between the `linseg:` and the `a`.

**Comment by vlazzarini** [comment]
Thanks; fix pushed to git. Do you want to contribute directly? If so, you can consider joining the project.

**Comment by nwhetsell** [comment]
I don’t mind contributing by making pull requests, and I can’t promise many pushes, but sure.
