### ISSUE TITLE
Mac OS X install of github package claiming to be version 6.07 appears to be 6.06

### ISSUE THREAD

**Issue by crc9** [csound/csound#672]
I deleted /usr/local/bin/csound and reinstalled the package csound6.07-OSX-universal.dmg, freshly downloaded from http://csound.github.io/download.html moments ago. Here is what it says the version is when run:

Cecils-MacBook-Air:csound robert$ csound
0dBFS level = 32768.0
Csound version 6.06 (double samples) Mar 10 2016
libsndfile-1.0.26

Please let me know if I'm doing something wrong in the installation process, i.e., not deleting enough components, etc.

**Comment by kunstmusik** [comment]
Do you have a local copy of the CsoundLib64.framework in
~/Library/Frameworks? If so, try deleting it.

**Comment by vlazzarini** [comment]
I have just downloaded and installed the package again to check:

'''
lh-pac-3g9:csound.github.io victor$ csound 
0dBFS level = 32768.0
Csound version 6.07 (double samples) May 16 2016
'''

I am satisfied that the package installs the correct version

**Comment by crc9** [comment]
That was indeed the problem. I now am running version 6.07!

Thanks,
Robert
