### ISSUE TITLE
Midi file to score freeze

### ISSUE THREAD

**Issue by hlolli** [csound/csound#673]
A colleague of mine is trying to export the data from midi into a text file, what happens is that csound either stops before reading trough the whole midi file or gets stuck in a loop (TT does not incement and writes the same note events over and over). He's using macosx on csound 6.07 from 18th May. I'm not sure if this is connected to the audio driver (in fact we would like to do this non-realtime) but nill and portaudio with no audio output produce the same error. This error also appears on other midi files, but sometimes with luck csound is able to read trough the whole midi file before the end. So the process freezes on various points unpredictably.

Midi file in this example can be found here:
http://www.jsbach.net/midi/bwv988/988-v23.mid

```
<CsoundSynthesizer>

<CsOptions>
; enter name of input midi file
-Fbmw_988.mid
</CsOptions>

<CsInstruments>
; Example by Iain McCurdy

;ksmps needs to be 10 to ensure accurate rendering of timings
ksmps = 10

massign 0,1

  instr 1
iChan       midichn
iCps        notnum            ; read pitch in frequency from midi notes
iVel        veloc    0, 127 ; read in velocity from midi notes
kDur        timeinsts          ; running total of duration of this note
kRelease    release            ; sense when note is ending
 if kRelease=1 then            ; if note is about to end
;           p1  p2  p3    p4     p5    p6
event "i",  2,  0, kDur, iChan, iCps, iVel ; send full note data to instr 2
 endif
  endin

  instr 2
iDur        =        p3
iChan       =        p4
iCps        =        p5
iVel        =        p6
iStartTime  times   
fprints  "my.sco", "\\t%.2f\\t%.2f\\t%d\\n",iStartTime-iDur,iDur,iCps
 endin

</CsInstruments>

<CsScore>
f 0 480 ; ensure this duration is as long or longer that duration of midi file
e
</CsScore>

</CsoundSynthesizer>
```

**Comment by vlazzarini** [comment]
works here on OSX with a midi file I had in my disk in realtime and offline. Is this a bug? Maybe this type of thing should be discussed at the list before a ticket is open.

**Comment by hlolli** [comment]
Good point. This is not a crash, but only a complete hault after usually a
60-90 secs (TT). We tried various midi files, short ones flew trough,
longer ones haulted (but could somrtimes run trough). He is feeding this
data to a machine learning network so we are getting midi data from many
midi files. I will see if compiling from develop makes any difference (he
installled from .dmg originally) otherwise on my linux. So I close it
tomorrow if this does not persist, or post more condence failing example.

**Comment by vlazzarini** [comment]
Another thing is that the file writing is blocking, so that does not go well with realtime.

I'd suggest using Python and collecting the data using bus channels. Or even sending the data over OSC to another file writing program.

**Comment by hlolli** [comment]
Ok thanks, that shouldn't be a problem.
