### ISSUE TITLE
Better integration with Haskell composition environments

### ISSUE THREAD

**Issue by gogins** [csound/csound#675]
This will be similar to issue #610 but for Haskell instead of Lisp/Scheme. If it is feasible I will provide an FFI wrapper to csound.h and some examples.

**Comment by gogins** [comment]
It may be possible to use this: https://github.com/haskell/c2hs

**Comment by kunstmusik** [comment]
John Lato wrote hCsound but it does not look to have been updated recently. https://wiki.haskell.org/CSound has the link to hCsound.

**Comment by gogins** [comment]
Thanks. I am trying to get this to work now.

Best,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by gogins** [comment]
The story is not so good so far. Requests by software packages to use specific versions of the Haskell Platform are an indication of a steep curve ahead. Also there are not very many maintainers of the music packages. I am putting this on hold for now although Kulitta is damn impressive.

**Comment by gogins** [comment]
I have been trying to get Euterpea, HSoM, and Kulitta to work, also a bit for haskore.

My impression is that I can proceed, but I have to patch the code as I go. This surely indicates that these packages are not kept up to date with the toolchain. Also there are package incompatibility issues with haskore.

It is Donya Quick who is keeping this stuff going. She does not provide much information on how to actually run things, and there are things in her code that are Windows-specific. What she has done is impressive, but this has been exhausting. I got as far as generating some chorales for MIDI and now I am going to put this on hold and work on some other things.

**Comment by gogins** [comment]
One thing that happened several times is that using cabal to install a package failed, whereas getting up to date code with git and building locally with cabal succeeded.

**Comment by gogins** [comment]
I am unassigning myself from this to free up time for composing.

**Comment by gogins** [comment]
I am closing this for now because I am not aware of ongoing composition using Donya Quick's packages. Her GitHub commits are to private repositories.
