### ISSUE TITLE
shift parameter in pvswarp

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#680]
i have two problems with the kshift parameter in pvswarp:

1) it seems to have no effect whatever value i try. i attach an example which modifies the manual example to change kshift.
2) i think the manual description has a typo: "kshift -- spectral envelope shift, values > 0 shift the envelope linearly upwards and values < 1 shift it downwards."
this should probably read: "values > 1 ..."

cheers -
  joachim

<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac  ;;;realtime audio out
;-iadc    ;;;uncomment -iadc if realtime audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o pvswarp.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1

instr 1

asig  soundin "fox.wav"			; get the signal in
fsig  pvsanal asig, 1024, 256, 1024, 1	; analyse it
ftps  pvswarp fsig, 1, p4		; warp it
atps  pvsynth ftps			; synthesise it                      
      outs atps, atps

endin
</CsInstruments>
<CsScore>

i 1 0 3 1
i 1 + 3 1.5
i 1 + 3 3
i 1 + 3 .25
e
</CsScore>
</CsoundSynthesizer>

**Comment by vlazzarini** [comment]
The shift values are too small. This offsets the spectral envelope. An offset of 1.5 Hz is likely not to be heard. Try 150 instead

**Comment by joachimheintz** [comment]
yes this works. it was not clear for me that it is in hertz, so i added this to the manual, if you don't mind.
also i extended the example to see the effect of the shifting.
i saw that the typo in the manual (< 1 instead of < 0) was already fixed.
