### ISSUE TITLE
Deeply nested #include can segfault

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#681]
One way to reproduce this (on macOS) is to compile a 1-line orchestra named Test.orc consisting of

```csound
#include "Test.orc"
```

using

```
csound --nosound --orc Test.orc
```

For avoidance of doubt, there must not be a newline after the `"` following `Test.orc` in the orchestra.

**Comment by jpffitch** [comment]
Believed fixed in orchestra-- score to follow
