### ISSUE TITLE
Recursively expanding macros can segfault

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#682]
I can reproduce this (on macOS) by compiling an orchestra consisting of

```csound
#define FOO #$BAR##define BAR #$FOO#$FOO
```

using

```
csound --nosound --orc Test.orc
```

This orchestra can also reproduce the issue:

```csound
#define FOO #$FOO#$FOO
```

**Comment by jpffitch** [comment]
User infinite loop.  I guess one could check memory use, but I thought it did.

**Comment by nwhetsell** [comment]
> User infinite loop.

The two code snippets are reduced test cases.

I can easily imagine an orchestra `#include`-ing multiple 3rd-party files that `#define` several macros that happen to have naming collisions, thus producing this issue, with no indication of what the real problem is because Csound reports only that a segmentation fault occurred.

**Comment by jpffitch** [comment]
Believed fixed for orchestra -- score to follow
