### ISSUE TITLE
--sample-accurate issue

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#683]
a click is produced when using --sample-accurate

The file looks a bit crazy, but is created by Blue and works from the terminal: 
[click.csd.txt](https://github.com/csound/csound/files/386366/click.csd.txt)

a screenshot from Audacity shows the click caused by --sample-accurate (top) and a render without the --sample-accurate flag (bottom)
Clearly you can see the click at 3.0 second, where the second note starts.
![screenshot from 2016-07-27 16 50 53](https://cloud.githubusercontent.com/assets/6670911/17179926/329a7a98-541b-11e6-94f5-205cf203d0c0.png)

**Comment by jpffitch** [comment]
Te problem is that it only needsone opcode to get sample-accurate wrong, 
or not at all for this to hape.   3secods does not fall on a ksmps 
boundary in your code which is why I suspect a missing opcode,; but tere 
are so many, so many user opcodes and I have no clue whee to start.  Must 
be at start of instr1 so that migt allow some simplification.
==J

**Comment by jpffitch** [comment]
This is indeed related to --sample-accurate and nothing  to do with oscbnk.

I have a fix, now in git, for this example but the global fix is harder.  The question is in an incomplete k-cycle (start late or finish early or both) what should assignment via = do?  If entirely a local signal then it does not matter but if a global variable it will be seen outside this instance, so usually it should only copy the active section and ignore the rest (think +=) but that might not be right either (eg when global is carrying data between instances with same start/finish).
  i have changed to only copying the active part as that seems most likely, and keeps blue happy.

I seek inspiration.....

**Comment by jpffitch** [comment]
Code changed so think is now correct.  Will close issue for now but will need monitoring.
Problems my arise with using global variable with --sample-accurate

**Comment by tjingboem** [comment]
does this mean that --sample-accurate will not work for global variables?
Or are other problems to be expected?

**Comment by jpffitch** [comment]
It is hard to explain but wit --sample-accurate  consider an instrument 
starting in the midde of a cycle; saya1 oscil 1,440
tn the variable a1 will hae zeros at the start until thetruetime

Now think what happens to
gaa = gaa + a1
you want the initial part of gaa to remain, but for local a-vars it is 
different, and especially for the last cycle.  What we have done is make 
assignment to global preserve the start/end but assignments to  locals to 
zero them   This seems to be correct in most casesbutt we have not prooved 
tis to be correct.  it fixes your blue) example though.

Hope that isa little clearer; just take care and for most cases it will 
work
