### ISSUE TITLE
README refers to nonexistent directories and files

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#684]
The [“Getting Started” section of the README](https://github.com/csound/csound/tree/8996a80c2db8a1815fde13ceba9a80bcd95de1fc#getting-started) refers to

* [examples/Boulanger_Examples](https://github.com/csound/csound/blame/8996a80c2db8a1815fde13ceba9a80bcd95de1fc/README.md#L36)
* [doc/manual/html/indexframes.html](https://github.com/csound/csound/blame/8996a80c2db8a1815fde13ceba9a80bcd95de1fc/README.md#L39)
* [doc/manual/api/index.html](https://github.com/csound/csound/blame/8996a80c2db8a1815fde13ceba9a80bcd95de1fc/README.md#L45)

It seems that these do not exist.

**Comment by gogins** [comment]
These directories refer to directories that are created in a Csound installation. They may vary by operating system.

I have changed the README.md to refer to the git examples directory and to the online documentation.
