### ISSUE TITLE
Questions about types and type characters

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#685]
I have a few questions about types and type characters:

* Does `.` permit `i`, `k`, `a`, or `S`; or should this list be longer (or shorter)?
* Is `b` the same as `B`? This seems to be used only by [`&&`, `||`, and the opcode that handles conditional expressions](https://github.com/csound/csound/blob/8996a80c2db8a1815fde13ceba9a80bcd95de1fc/Engine/entry1.c#L189).
* Is the `I` _input_ type the same as `S`? This seems to be used only by [FLslidBnk2](https://csound.github.io/docs/manual/FLslidBnk2.html).
* Is the `s` _input_ type the same as `x`? This seems to be used only by [spectrum](https://csound.github.io/docs/manual/spectrum.html).
* What does an input type of `*[]` mean? This seems to be used only by [changed2](https://csound.github.io/docs/manual/changed2.html). (For the sake of comparison, [lenarray](https://csound.github.io/docs/manual/lenarray.html) and [slicearray](https://csound.github.io/docs/manual/slicearray.html) both use `.[]`, which I think means a required array of i‑time scalars, k‑rate scalars, a‑rate vectors, or strings.)

**Comment by jpffitch** [comment]
B and b are not the same.  One is rate the other k

**Comment by nwhetsell** [comment]
> One is rate the other k

Which one is k‑rate?

And what’s the rate of the one that’s not k‑rate?

**Comment by kunstmusik** [comment]
* Does `.` permit `i`, `k`, `a`, or `S`; or should this list be longer (or shorter)?

**'.' represents a required argument of any scalar type (could be f-, w-, anything)**

* Is `b` the same as `B`? This seems to be used only by [`&&`, `||`, and the opcode that handles conditional expressions](https://github.com/csound/csound/blob/8996a80c2db8a1815fde13ceba9a80bcd95de1fc/Engine/entry1.c#L189).

**'b' is an i-rate boolean, 'B' is a k-rate boolean**

* Is the `I` _input_ type the same as `S`? This seems to be used only by [FLslidBnk2](https://csound.github.io/docs/manual/FLslidBnk2.html).

**I don't see an 'l' type for that opcode.**

* Is the `s` _input_ type the same as `x`? This seems to be used only by [spectrum](https://csound.github.io/docs/manual/spectrum.html).

**I don't see an s type for spectrum (and I don't even see it in my set of opcodes using 'csound -z1'**

* What does an input type of `*[]` mean? This seems to be used only by [changed2](https://csound.github.io/docs/manual/changed2.html). (For the sake of comparison, [lenarray](https://csound.github.io/docs/manual/lenarray.html) and [slicearray](https://csound.github.io/docs/manual/slicearray.html) both use `.[]`, which I think means a required array of i‑time scalars, k‑rate scalars, a‑rate vectors, or strings.)

**That OENTRY should probably be .[]. I think * means var-arg of any type, but need to revisit code**

BTW: the types have traditionally been documented in:

https://github.com/csound/csound/blob/develop/Engine/entry1.c

**Comment by nwhetsell** [comment]
@kunstmusik Many thanks!

> '.' represents a required argument of any scalar type (could be f-, w-, anything)

Just to make sure I understand, `.` can mean `i`, `k`, `a`, `S`, `f`, `w`, `b`, `B`, or `l`? Or are `b`, `B`, and `l` excluded?

> I don't see an 'l' type for [FLslidBnk2].

Odd; when I run `csound --list-opcodes1` using Csound 6.07 (May 16 2016), I see this for FLslidBnk2:

```
FLslidBnk2  (null)      Iiiiooooo
FLslidBnk2  (null)      Siiiooooo
```

> I don't see an s type for spectrum (and I don't even see it in my set of opcodes using 'csound -z1'

Try using `csound -z3` to [include deprecated opcodes](https://csound.github.io/docs/manual/CommandFlags.html#FlagsMinusLowerZ). When I run `csound --list-opcodes3`, I see this for spectrum:

```
spectrum    w           siiiqoooo
```

> I think * means var-arg of any type, but need to revisit code

The only place I’m aware of `*` being documented is in the [release notes of Csound 6.06](https://github.com/csound/manual/blob/56f0313d67f34265932305a439f94933a221ea75/preface/whatsnew.xml#L2755) (which indeed say it’s “a var-arg list of any-type”).

**Comment by jpffitch** [comment]
b is irate, B krate == ust read te sources in Engine/insert.c

**Comment by kunstmusik** [comment]
@nwhetsell I think that s is a polymorphic type that can match k- or a-.  However, the current code in Engine/csound_standard_types.c only matches s- on the out-types and there is no entry for the in-types, which may be a bug. 

For '.', the type checker basically sees the '.' and accepts whatever is the type found for the input, so yes, it will match one-argument of any type.  'b', 'B', and 'l' probably are non-sensical for opcodes using '.'.  I believe any opcode using '.' will use run-time type checking, and some opcodes may have their own restrictions on allowed types that are not reflected at compile-time.

For FlslidBnk2, I suspect the "I" entry is a typo, since FlslidBnk uses "S" and "i".

**Comment by nwhetsell** [comment]
@jpffitch `B` is [documented in entry1.c as a Boolean](https://github.com/csound/csound/blob/8996a80c2db8a1815fde13ceba9a80bcd95de1fc/Engine/entry1.c#L47), but there is no mention of rate. `b` is not documented as far as I can see — it just appears in the types for the [`&&`, `||`, and the opcode that handles conditional expressions in entry1.c](https://github.com/csound/csound/blob/8996a80c2db8a1815fde13ceba9a80bcd95de1fc/Engine/entry1.c#L189), to which I linked in my original question.

**Comment by jpffitch** [comment]
On Sun, 31 Jul 2016, Steven Yi wrote:

> 
> @nwhetsell I think that s is a polymorphic type that can match k- or a-.
> However, the current code in Engine/csound_standard_types.c only matches s- on
> the out-types and there is no entry for the in-types, which may be a bug.
>

ityope x is k- or a- much used

**Comment by jpffitch** [comment]
Yes it is generated nternally so does not apear in opcodes.

The list in entry1.c may be out of date by now, as we move from ad-hoc 
code to signature-based decisions.

**Comment by jpffitch** [comment]
Can this be closed now?

**Comment by nwhetsell** [comment]
The above discussion seems to indicate 3 issues:

1. The `Iiiiooooo` input entry for FLslidBnk2 should be `iiiiooooo`.
2. The `*[]` input type of changed2 should be `.[]`.
3. Either the `s` input type used by spectrum should be changed to `x`, or [Engine/csound_standard_types.c](https://github.com/csound/csound/blob/develop/Engine/csound_standard_types.c) should be updated so that `s` can be used as an input type.

If there are plans to address these issues, it may be better to leave this issue open in the meantime. If not, I leave closing this issue up to you.

**Comment by jpffitch** [comment]
>  1. The Iiiiooooo input entry for FLslidBnk2 should be iiiiooooo.

    Not sure that is right. Manual says first argument is a string.  The 
code does something I do not follow with GetStrsets and GetStrsetsMax
Needs manual change

>  2. The *[] input type of changed2 should be .[].

    Done

>  3. Either the s input type used by spectrum should be changed to x, or
>     Engine/csound_standard_types.c should be updated so that s can be used as
>     an input type.


    I did this but the opcode is deprecatedanyway

**Comment by nwhetsell** [comment]
> > 1. The `Iiiiooooo` input entry for FLslidBnk2 should be `iiiiooooo`.

> Not sure that is right. Manual says first argument is a string. The
code does something I do not follow with GetStrsets and GetStrsetsMax
Needs manual change

FLslidBnk2 also has an input entry of  `Siiiooooo`. There does not seem to be another opcode that uses an `I` input type, and `"I"` is not currently in the `POLY_IN_TYPES`, `OPTIONAL_IN_TYPES`, or `VAR_ARG_IN_TYPES` in [Engine/csound_standard_types.c](https://github.com/csound/csound/blob/acba87ec6f2f14862503f0feb90e7e4b6ced01ee/Engine/csound_standard_types.c).

**Comment by jpffitch** [comment]
I fixed the manual so closing issue
