### ISSUE TITLE
Inconsistent definition of phase vocoder default window type

### ISSUE THREAD

**Issue by gogins** [csound/csound#686]
As the Csound Reference Manual states, the default window type for pvanal is von Hanning. However, when running pvlook on a .pvx file, the Hamming window is reported as "Default", and von Hanning is  reported as "von Hann".

This is because in pvanal the code sets the window type to Hanning and only sets it to Hamming if you pass -H. But pvlook looks at the definition of the window type enum and reports the value of the window type flag according to pvfileio.h:

typedef enum pvoc_windowtype {
    PVOC_DEFAULT = 0,
    PVOC_HAMMING = 0,
    PVOC_HANN,
    PVOC_KAISER,
    PVOC_RECT,
    PVOC_CUSTOM
} pv_wtype;

I dumped some .pvx files and they appear to be correct. The window type flag is correct. Moreover the analysis data is somewhat different.

So I think the behavior of pvanal, pvoc, and pvadd is actually correct. But if you don't know that pvanal and pvlook have a different idea about what is the "default" you will be confused.

**Comment by vlazzarini** [comment]
I am not quite sure what needs to be done here? Documentation? Change pvanal to default to Hamming? Pvlook reporting?

**Comment by gogins** [comment]
I would have fixed this myself but was not sure why the default in pvfileio.h is Hamming.

The default for pvanal should be "standard" whatever that is (least artifacts, most generally useful).

The least intrusive solution is to simply change pvlook to report the actual window name and not "Default."

**Comment by jpffitch** [comment]
Richard Dobson may have a view -- largely his codee i think

**Comment by vlazzarini** [comment]
Von Hann is better than Hamming in my opinion.

**Comment by gogins** [comment]
In that case, unless you object, I will leave the enum alone and just
change the name of the window reported by pvlook. That way, I can't
possibly break something that depends on the value of the enum.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by vlazzarini** [comment]
I think that's a good solution
