### ISSUE TITLE
P-fields are ignored if not used directly in an instrument

### ISSUE THREAD

**Issue by glocq** [csound/csound#689]
I don't know if this is intended behaviour, but in case it is, [this page](http://www.csounds.com/manual/html/opcode.html) of the manual should probably reflect it.

I want to define an instrument that uses a UDO. The page above says "all p-fields are automatically copied at initialization". So I make my UDO use the value of p4. However, since the instrument doesn't directly use the value of any p-field above p3, I get the warning `WARNING: instr 1 uses 3 p-fields but is given 4`, which I could live with, if the instrument didn't choose to ignore p4 altogether, whose value my UDO needs.

So I have to add a line to define a dummy variable to be able to say "Hey, this instrument does use p4!"

Here is an example of code that works, but that doesn't as soon as the line `iuseless = p4` is commented out:

```
<CsoundSynthesizer>
<CsOptions>
-odac
</CsOptions>
<CsInstruments>


opcode Celesta, a, 0
aenv    transeg     0, 0.007, -4, 1, p3-0.007, -4, 0
asig    oscils      0dbfs, p4, 0
        xout        aenv*asig
endop


instr 1
// If I comment the following line, it doesn't work anymore :(
iuseless = p4
asig    Celesta
        outs        asig, asig
endin


</CsInstruments>
<CsScore>
i1 0 2 440
</CsScore>
</CsoundSynthesizer>
```

**Comment by vlazzarini** [comment]
That's the behaviour. If there is a documentation issue, then a ticket needs to be filed for the manual.
