### ISSUE TITLE
Loris opcodes on csound 6.07

### ISSUE THREAD

**Issue by RobertoPalazzolo** [csound/csound#690]
Hi all ! 
I'm trying Loris opcodes on csound 6.07 and windows 7 ultimate 64 bit. I get an syntax error but it should not be: 

------- Compiler Start ------- 
virtual_keyboard real time MIDI plugin for Csound 
0dBFS level = 32768.0 
Csound version 6.07 (double samples) May  3 2016 
libsndfile-1.0.26-exp 
UnifiedCSD:  D:\STUDIO 1\CSOUNDELAB\lorismorphing.csd 
STARTING FILE 
Creating options 
Creating orchestra 
Creating score 
rtaudio: PortAudio module enabled ... 
using callback interface 
rtmidi: PortMIDI module enabled 

error: syntax error, unexpected T_IDENT  (token "ktimpnt") from file D:\STUDIO 1\CSOUNDELAB\lorismorphing.csd (1) 
 line 24: 
>>>             lorisread   ktimpnt <<< 
Unexpected untyped word lorisread when expecting a variable 
Parsing failed due to invalid input! 
end of score.	  overall amps:      0.0 
           overall samples out of range:        0 
1 errors in performance 
Elapsed time at end of performance: real: 0.005s, CPU: 0.005s 
------- Compiler End ------- 

Compiler Info/Warnings/Errors: 
csound->FileOpen2 failed: No such file or directory 
Stopping on parser failure 
cannot compile orchestra 

best regard 
robertopalazzolo

**Comment by vlazzarini** [comment]
You do not have them in your system. 
Loris opcodes are supplied by a third-party and we do not package them in the release.
