### ISSUE TITLE
Csound6 Android app crashes on CSD syntax errors

### ISSUE THREAD

**Issue by DaveSeidel** [csound/csound#693]
If I load a CSD into the Android app and the CSD contains any fatal syntax errors (i.e., errors that would cause the command-line version of csound to exit with an error message), the app crashes when I click the Start button.

**Comment by gogins** [comment]
I will debug this and try to fix it soon.

Thanks,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by gogins** [comment]
Updating the Android for Csound build for Linux, where I expect to work on this from now on.  Gradle sync takes waaaaaaaay to long, so try this:

http://stackoverflow.com/questions/36529301/android-build-gradle-is-too-slow-dependency-resolution

**Comment by gogins** [comment]
I have now completely rebuilt Csound for Android. I will post a beta APK to the repository soon.

However, now I cannot reproduce this error. Can you post here a simplified CSD that causes the crash?

**Comment by DaveSeidel** [comment]
Here is a simple example that crashes the app on my system:

```
<CsoundSynthesizer>

<CsOptions>
</CsOptions>

<CsInstruments>

sr = 48000
ksmps = 10
nchnls = 2
0dbfs = 1.0

gifoo = fillarray(1, 2, 3, 4)

instr 1
	printf "yo\n", 1
endin

</CsInstruments>

<CsScore>

i 1 0 1
e

</CsScore>

</CsoundSynthesizer>
```

**Comment by gogins** [comment]
I ran this on my latest build of the Android app and it did not crash. Behavior was identical to command line Csound on linux.

**Comment by gogins** [comment]
Thanks, I tested this on my new android build and it ran without crashing
with the same message as on my pc. So I have closed the issue and the next
release should be OK.

Best, Mike

**Comment by DaveSeidel** [comment]
Thanks, Mike. Looking forward to the new release.
