### ISSUE TITLE
Can't Find lib_jcsound6.jnilib

### ISSUE THREAD

**Issue by softpunch** [csound/csound#699]
I'm using OSX 10.11 on a MacBook Pro.

I've tried installing the most recent CSound binaries and I've tried installing CSound via Homebrew.
I've tried (and failed) to run the .sh files that mention lib_jcsound6.jnilib.
I've searched in /usr/lib and /usr/lib/java (and the rest of my system).
For the life of me, I can't find lib_jcsound6.jnilib.

I'm trying to run CSoundo in Processing, 
but that library depends on **lib_jcsound6.jnilib** from the **main** CSound install.
(Hence, I'm filing this issue here, rather than in the CSoundo repo.)

I appreciate any suggestions!

**Comment by kunstmusik** [comment]
The jnilib should be installed in ~/Library/Java/Extensions or
/Library/Java/Extensions

**Comment by softpunch** [comment]
Thanks! Not sure why I had such trouble finding it!
