### ISSUE TITLE
What’s the correct way to use csoundSetOutput?

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#700]
I’m probably misunderstanding something, but based on the [documentation of `csoundSetOutput`](https://csound.github.io/docs/api/group__FILEIO.html#ga974ac937c9cac9330420e56f53cc965c), Csound can write 25 file types and 10 encoding formats supported by [libsndfile](https://github.com/erikd/libsndfile). The 25 file types, by string accepted by `csoundSetOutput`, are

String    | File type
----------|----------
`"wav"`   | [Microsoft WAV](https://en.wikipedia.org/wiki/WAV)
`"aiff"`  | [Apple AIFF/AIFC](https://en.wikipedia.org/wiki/Audio_Interchange_File_Format)
`"au"`    | [Sun Au](https://en.wikipedia.org/wiki/Au_file_format)
`"raw"`   | Audio in any format
`"paf"`   | [Ensoniq PARIS](https://en.wikipedia.org/wiki/Ensoniq_PARIS) Audio Format
`"svx"`   | [Amiga 8SVX](https://en.wikipedia.org/wiki/8SVX)
`"nist"`  | [NIST Speech File Manipulation Software (SPHERE)](https://www.nist.gov/itl/iad/mig/tools)
`"voc"`   | [Creative Labs](https://en.wikipedia.org/wiki/Creative_Technology_Limited) Voice
`"ircam"` | [Berkeley](https://en.wikipedia.org/wiki/Berkeley_Software_Distribution)/[IRCAM](https://en.wikipedia.org/wiki/IRCAM)/[CARL](http://musicweb.ucsd.edu) Sound Format
`"w64"`   | [Sound Forge](https://en.wikipedia.org/wiki/Sound_Forge) Wave 64
`"mat4"`  | [MATLAB](https://en.wikipedia.org/wiki/MATLAB) MAT-File Level 4
`"mat5"`  | [MATLAB](https://en.wikipedia.org/wiki/MATLAB) MAT-File Level 5
`"pvf"`   | [Nullsoft](https://en.wikipedia.org/wiki/Nullsoft) Portable Voice Format
`"xi"`    | [FastTracker 2](https://en.wikipedia.org/wiki/FastTracker_2) Extended Instrument
`"htk"`   | [Hidden Markov Model Toolkit](http://htk.eng.cam.ac.uk)
`"sds"`   | MIDI Sample Dump Standard
`"avr"`   | Audio Visual Research
`"wavex"` | Microsoft WAV Extensible
`"sd2"`   | [Sound Designer II](https://en.wikipedia.org/wiki/Avid_Audio#Sound_Designer_file_formats)
`"flac"`  | [Free Lossless Audio Codec](https://en.wikipedia.org/wiki/FLAC)
`"caf"`   | [Apple Core Audio Format](https://en.wikipedia.org/wiki/Core_Audio_Format)
`"wve"`   | [Psion](https://en.wikipedia.org/wiki/Psion_(company)) waveform
`"ogg"`   | [Ogg](https://en.wikipedia.org/wiki/Ogg) container
`"mpc2k"` | [Akai MPC2000](https://en.wikipedia.org/wiki/Music_Production_Controller#MPC2000)
`"rf64"`  | [European Broadcasting Union RF64](https://en.wikipedia.org/wiki/RF64)

The 10 encoding formats are

String     | Encoding format
-----------|----------------
`"uchar"`  | Unsigned 8‑bit integer
`"schar"`  | Signed 8‑bit integer
`"short"`  | Signed 16‑bit integer
`"24bit"`  | Signed 24‑bit integer
`"long"`   | Signed 32‑bit integer
`"float"`  | 32‑bit floating-point number
`"double"` | 64‑bit floating-point number
`"ulaw"`   | [_µ_‑law](https://en.wikipedia.org/wiki/Μ-law_algorithm)
`"alaw"`   | [A‑law](https://en.wikipedia.org/wiki/A-law_algorithm)
`"vorbis"` | [Vorbis](https://en.wikipedia.org/wiki/Vorbis)

(I’m aware that the file types don’t necessarily support all the encoding formats. How types support formats is summarized in the table at [http://www.mega-nerd.com/libsndfile/](http://www.mega-nerd.com/libsndfile/).)

When I run

```c
#include <assert.h>
#include <csound/csound.h>
#include <libsndfile/sndfile.h>

#define FILE_NAME "test.aif"

int main(int argc, const char *argv[]) {
  char *types[] = {
    "wav", "aiff", "au", "raw", "paf", "svx", "nist", "voc", "ircam", "w64",
    "mat4", "mat5", "pvf", /*"xi",*/ "htk", "sds", "avr", "wavex", "sd2", /*"flac",*/
    "caf", /*"wve",*/ /*"ogg",*/ "mpc2k", "rf64"
  };
  int typeCount = sizeof(types) / sizeof(types[0]);
  char *formats[] = {
    "uchar", "schar", "short", "24bit", "long", "float", "double", "ulaw",
    "alaw", "vorbis"
  };
  int formatCount = sizeof(formats) / sizeof(formats[0]);
  
  int status = csoundSetGlobalEnv("SFDIR", "/usr/local");
  assert(status == CSOUND_SUCCESS);
  
  CSOUND *Csound = csoundCreate(NULL);
  assert(Csound != NULL);
  
  FILE *file = fopen("/usr/local/output-test.txt", "w");
  
  for (int typeIndex = 0; typeIndex < typeCount; typeIndex++) {
    char *type = types[typeIndex];
    for (int formatIndex = 0; formatIndex < formatCount; formatIndex++) {
      char *format = formats[formatIndex];
      csoundSetOutput(Csound, FILE_NAME, type, format);
      status = csoundCompileOrc(Csound,
        "0dbfs = 1\n"
        "giFunctionTableID ftgen 0, 0, 16384, 10, 1\n"
        "instr A440\n"
          "outc oscili(0.5 * 0dbfs, 440, giFunctionTableID)\n"
        "endin\n"
      );
      assert(status == CSOUND_SUCCESS);
      status = csoundReadScore(Csound,
        "i \"A440\" 0 1\n"
        "e\n"
      );
      assert(status == CSOUND_SUCCESS);
      
      status = csoundStart(Csound);
      assert(status == CSOUND_SUCCESS);
      
      csoundPerform(Csound);
      
      SF_INFO soundFileInfo;
      SNDFILE *soundFile = sf_open("/usr/local/" FILE_NAME, SFM_READ, &soundFileInfo);
      if (sf_error(soundFile) == SF_ERR_NO_ERROR) {
        fprintf(file, "%x\t", soundFileInfo.format & SF_FORMAT_SUBMASK);
        sf_close(soundFile);
      } else {
        fprintf(file, "x\t");
      }
      
      csoundReset(Csound);
    }
    
    fprintf(file, "\n");
  }
  
  fclose(file);
  
  return 0;
}
```

I attempt to output each file type (except for `"xi"`, `"flac"`, `"wve"`, and `"ogg"`) and each encoding format. I then read these files using libsndfile and write the encoding format to /usr/local/output-test.txt. Despite attempting to write each type and format, output-test.txt contains a 21 row by 10 column matrix of the number 2, the value of libsndfile’s `SF_FORMAT_PCM_16` subtype. This would seem to indicate that Csound is writing signed 16‑bit integers (corresponding to the `"short"` format) no matter what format is passed to `csoundSetOutput`.

This strikes me as unexpected. Am I missing something with `csoundSetOutput`?

Also, I’m skipping `"xi"`, `"flac"`, `"wve"`, and `"ogg"` because, if I attempt to write those types, the `assert(status == CSOUND_SUCCESS)` after starting Csound fails.

It’s probably also worth mentioning that while Csound outputs the type to the console — for example

```
writing 2048-byte blks of shorts to /usr/local/test.aif (WAV)
```

for `"wav"` — Csound outputs `(unknown)` for `"avr"` and `"wavex"`.

**Comment by vlazzarini** [comment]
you need to set the flag for output data format. It defaults to 16bit.

**Comment by vlazzarini** [comment]
but it looks like there is some overwriting of options going on.

**Comment by vlazzarini** [comment]
fixed in git

**Comment by nwhetsell** [comment]
It looks like a fix was pushed in commit 67b10a9b4c441b97a6e447f097b28f2c409f9baa. Can you recommend a workaround to make `csoundSetOutput` work in Csound 6.07 and earlier? (The nature of the change and the commit message make me think the answer is no, but I figure I should ask.)

Here are the results of running (slightly updated, included below) code to reproduce the table at http://www.mega-nerd.com/libsndfile/ (I added column headers with the values of libsndfile’s format types):

```
 1   2   3   4   5   6   7   A   8   B   C   D   E   F  10  18  16  17
------------------------------------------------------------------------
 5   5   -   2   -   -   -   -   x   5   -   5   -   -   -   -   -   -  
 -   1   1   2   1   1   1   -   -   -   -   -   1   -   -   1   1   -  
 2   2   2   2   2   2   2   2   2   2   2   2   2   -   2   2   2   -  
 3   3   3   2   3   -   3   -   -   3   -   -   -   -   -   3   3   -  
 4   4   4   2   -   -   4   4   -   4   4   4   4   -   -   4   4   -  
 6   6   6   2   -   -   -   6   -   6   6   6   -   -   -   6   -   -  
 7   7   7   2   -   -   -   -   -   7   7   7   -   -   -   7   -   -  
10  10  10   2   -   -  10  10  10  10   -   -   -   -   -  10   -   -  
11  11  11   2   -   -  11  11  11  11   -   -   -   -   -  11   -   -  
 -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -  
```

Here are some things to note about this table:

1. `"raw"` files (column 4) appear to still be written using signed 16‑bit integers regardless of the format passed to `csoundSetOutput`.

2. `"ircam"` files (column A) can’t seem to use the `"24bit"` format despite what’s in the libsndfile table.

3. Unsigned 8‑bit integers can be written to `"voc"` files (column 8), but not subsequently read by libsndfile (the `x` in the first row).

4. Although the [documentation of `csoundSetOutput`](https://csound.github.io/docs/api/group__FILEIO.html#ga974ac937c9cac9330420e56f53cc965c) says that `"xi"` files (column F) can be written, none of Csound’s formats can be used with that type.

5. `"sd2"` files (column 16) can use signed 32‑bit integers (format 4), although the table at libsndfile indicates the opposite.

6. There may be a problem with the `"flac"` type (column 17).

I’m guessing I should report items 2, 3, and 5 at the libsndfile repository.

I should also note that Csound still outputs `(unknown)` for `"avr"` and `"wavex"`.

Here is the code I used to generate the table:

```c
#include <assert.h>
#include <csound/csound.h>
#include <libsndfile/sndfile.h>

#define FILE_NAME "test.aif"

int main(int argc, const char *argv[]) {
  char *formats[] = {
    "uchar", "schar", "short", "24bit", "long", "float", "double", "ulaw",
    "alaw", "vorbis"
  };
  int formatCount = sizeof(formats) / sizeof(formats[0]);
  // Types in the order of the major format constants at
  // http://www.mega-nerd.com/libsndfile/api.html
  /*
  char *types[] = {
    "wav", "aiff", "au", "raw", "paf", "svx", "nist", "voc", "ircam", "w64",
    "mat4", "mat5", "pvf", "xi", "htk", "sds", "avr", "wavex", "sd2", "flac",
    "caf", "wve", "ogg", "mpc2k", "rf64"
  };
  */
  // Types in the order of the table at http://www.mega-nerd.com/libsndfile/
  char *types[] = {
    "wav", "aiff", "au", "raw", "paf", "svx", "nist", "ircam", "voc", "w64",
    "mat4", "mat5", "pvf", "xi", "htk", "caf", "sd2", "flac"
  };
  int typeCount = sizeof(types) / sizeof(types[0]);
  
  int status = csoundSetGlobalEnv("SFDIR", "/usr/local");
  assert(status == CSOUND_SUCCESS);
  
  CSOUND *Csound = csoundCreate(NULL);
  assert(Csound != NULL);
  
  FILE *file = fopen("/usr/local/output-test.txt", "w");
  
  for (int formatIndex = 0; formatIndex < formatCount; formatIndex++) {
    char *format = formats[formatIndex];
    for (int typeIndex = 0; typeIndex < typeCount; typeIndex++) {
      char *type = types[typeIndex];
      csoundSetOutput(Csound, FILE_NAME, type, format);
      status = csoundCompileOrc(Csound,
        "0dbfs = 1\n"
        "giFunctionTableID ftgen 0, 0, 16384, 10, 1\n"
        "instr A440\n"
          "outc oscili(0.5 * 0dbfs, 440, giFunctionTableID)\n"
        "endin\n"
      );
      assert(status == CSOUND_SUCCESS);
      status = csoundReadScore(Csound,
        "i \"A440\" 0 1\n"
        "e\n"
      );
      assert(status == CSOUND_SUCCESS);
      
      status = csoundStart(Csound);
      if (status == CSOUND_SUCCESS) {
        csoundPerform(Csound);
        
        SF_INFO soundFileInfo;
        SNDFILE *soundFile = sf_open("/usr/local/" FILE_NAME, SFM_READ, &soundFileInfo);
        if (sf_error(soundFile) == SF_ERR_NO_ERROR) {
          fprintf(file, "%2x  ", soundFileInfo.format & SF_FORMAT_SUBMASK);
          sf_close(soundFile);
        } else {
          fprintf(file, " x  ");
        }
      } else {
        fprintf(file, " -  ");
      }
      
      csoundReset(Csound);
    }
    
    fprintf(file, "\n");
  }
  
  fclose(file);
  
  return 0;
}
```

**Comment by vlazzarini** [comment]
Ultimately, the limits of precision/encoding are set by libsndfile, we just use what is available. So some combinations might not be possible. 
A work-around to the bug I fixed in csoundSetOutput() is not to use this function, and use instead
csoundSetOption() or csoundSetParams(). These should work as expected. For instance
csoundSetOption(csound, "--format=wav:float"); will write a RIFF-Wave containing floats.

**Comment by vlazzarini** [comment]
Looks like the libsndfile that goes with the Csound installation on OSX is lacking flac and ogg support. I will investigate

**Comment by nwhetsell** [comment]
> the limits of precision/encoding are set by libsndfile, we just use what is available.

This should enable Csound to write raw audio files using all the same formats as AIFFs, not just signed 16‑bit integers.

It may also be a good idea to remove FastTracker 2 Extended Instruments (`"xi"`) from the list of supported types to avoid confusion.

> Looks like the libsndfile that goes with the Csound installation on OSX is lacking flac and ogg support.

I’m compiling Csound from source with libsndfile 1.0.26, the latest I can get with [Homebrew](http://brew.sh). I can use Csound to write Ogg Vorbis, but not FLAC.

**Comment by vlazzarini** [comment]
I have tested FLAC here with a new build of libsndfile and I found no problems. Likewise, raw soundfiles with float output are not a problem either.  I was able to generate them and open in audacity to check.

**Comment by nwhetsell** [comment]
Are you using the code in [my comment above](https://github.com/csound/csound/issues/700#issuecomment-248275005) or different code?

What version of libsndfile are using?

**Comment by vlazzarini** [comment]
I am using a similar code and libsndfile 1.0.25 linked to flac and ogg.

**Comment by vlazzarini** [comment]
I ran your code here
'''
lh-pac-57t:debug victor$ more output-test.txt
 5   5   -   3   -   -   -   -   x   5   -   5   -   -   -   -   -   -  
 -   1   1   3   1   1   1   -   -   -   -   -   1   -   -   1   1   1  
 2   2   2   1   2   2   2   2   2   2   2   2   2   -   1   2   2   2  
 3   3   3   2   3   -   3   -   -   3   -   -   -   -   -   3   3   3  
 4   4   4   3   -   -   4   4   -   4   4   4   4   -   -   4   -   -  
 6   6   6   3   -   -   -   6   -   6   6   6   -   -   -   6   -   -  
 7   7   7   3   -   -   -   -   -   7   7   7   -   -   -   7   -   -  
10  10  10   3   -   -  10  10  10  10   -   -   -   -   -  10   -   -  
11  11  11   3   -   -  11  11  11  11   -   -   -   -   -  11   -   -  
 -   -   -   -   -   -   -  
'''

**Comment by nwhetsell** [comment]
With headers and without the last row, your table is

```
 1   2   3   4   5   6   7   A   8   B   C   D   E   F  10  18  16  17
------------------------------------------------------------------------
 5   5   -   3   -   -   -   -   x   5   -   5   -   -   -   -   -   -  
 -   1   1   3   1   1   1   -   -   -   -   -   1   -   -   1   1   1  
 2   2   2   1   2   2   2   2   2   2   2   2   2   -   1   2   2   2  
 3   3   3   2   3   -   3   -   -   3   -   -   -   -   -   3   3   3  
 4   4   4   3   -   -   4   4   -   4   4   4   4   -   -   4   -   -  
 6   6   6   3   -   -   -   6   -   6   6   6   -   -   -   6   -   -  
 7   7   7   3   -   -   -   -   -   7   7   7   -   -   -   7   -   -  
10  10  10   3   -   -  10  10  10  10   -   -   -   -   -  10   -   -  
11  11  11   3   -   -  11  11  11  11   -   -   -   -   -  11   -   - 
```

I’m going to chalk up the format libsndfile reads for `"raw"` files (column 4) to libsndfile having difficulty determining the format of raw audio files (which have no header, after all).

Aside from libsndfile reading signed 8‑bit integers instead of signed 16‑bit integers from `"htk"` files (column 10), and a missing format from `"sd2"` files (column 16), the only difference appears to be FLAC support.

How are you building libsndfile? I’m using Homebrew, and [libsndfile’s Homebrew formula currently lists the FLAC library as a dependency](https://github.com/Homebrew/homebrew-core/blob/edcce811a9f71fbac3a5f38d6327a7df75f08072/Formula/libsndfile.rb#L21) (I have [version 1.3.1 of the FLAC library](https://github.com/Homebrew/homebrew-core/blob/b1df2675043cabb0bf363196e544926dfc4fada9/Formula/flac.rb)). It seems a bit strange that I can use Csound to write Ogg Vorbis, but not FLAC, so I’m wondering if I’m missing a compilation step.

**Comment by vlazzarini** [comment]
I never used homebrew. Since I do the Csound releases,  I need to have all dependencies built on their own.

The Csound sources have a dependencies directory with a script that downloads and build each one.  You will need to have pkgconfig.

**Comment by nwhetsell** [comment]
For avoidance of doubt, is that directory [csound/dependencies](https://github.com/csound/csound/tree/develop/dependencies)?

**Comment by nwhetsell** [comment]
Sorry to keep harping on this…

> A work-around to the bug I fixed in csoundSetOutput() is not to use this function, and use instead
csoundSetOption() _or csoundSetParams()_.

(emphasis added)

I’m looking at the `CSOUND_PARAMS` struct (defined in [csound.h](https://github.com/csound/csound/blob/develop/include/csound.h), documented at https://csound.github.io/docs/api/structCSOUND__PARAMS.html), and none of its members jump out as being a file type and format. Indeed, none of the members of `CSOUND_PARAMS` are of type `char *`. Am I missing something?

In a similar vein, after one uses `csoundSetOption` (or `csoundSetOutput` in Csound 6.08 and later), how might one check Csound’s output type and format? If the file type and format are not members of `CSOUND_PARAMS `, then it does not appear that [`csoundGetParams`](https://csound.github.io/docs/api/group__ATTRIBUTES.html) can be used to do this.

**Comment by jpffitch** [comment]
Look at field outformt in OPARM structure. It has the bitwidth in it
From Top/argdecode.c

    case 'a':
       O->outformat = AE_ALAW;    /* a-law soundfile */
       break;

     case 'c':
       O->outformat = AE_CHAR;    /* signed 8-bit soundfile */
       break;

     case '8':
       O->outformat = AE_UNCH;    /* unsigned 8-bit soundfile */
       break;

etc

Output type is in filetyp; again...

O->filetyp = TYP_WAV


TYP_* and AE_* defined in include/soundio.h

Or have I misunderstood again?

**Comment by nwhetsell** [comment]
I’m trying to test a wrapper of the Csound API function `csoundSetOutput` in JavaScript, and (currently) I only need to `#include` [csound.h](https://github.com/csound/csound/blob/develop/include/csound.h) (actually [cwindow.h](https://github.com/csound/csound/blob/develop/include/cwindow.h), which `#include`s csound.h) to build this wrapper. I’m not `#include`-ing [csdl.h](https://github.com/csound/csound/blob/develop/include/csdl.h) (since I’m not building a plug-in), so I don’t have access to the `OPARAMS` struct.

It’s starting to look like Csound’s API can be used to set Csound’s output type and format, but not subsequently get them. I suppose I could `#include` csdl.h and write a wrapper around the `OPARAMS` struct to bring it into JavaScript, but that seems a bit strong for just getting the file type and format.

**Comment by jpffitch** [comment]
So you want a new function csoundGetOutput?

**Comment by nwhetsell** [comment]
If there’s indeed no way to get Csound’s output type and format using its current API, I’m not sure of the best way to add that. (I was also looking at `csoundSetPlayopenCallback` and `csoundSetRecopenCallback`, but those don’t seem suited to simply getting a type and format, and I’d likely have to somehow use those with `csoundSetFileOpenCallback` since the [`csRtAudioParams`](https://csound.github.io/docs/api/structcsRtAudioParams.html) struct contains the format but not the type.)

Another option may be to add the output type and format to the `CSOUND_PARAMS` struct, and then one could get the output type and format using `csoundGetParams`. (Doing it that way might also allow deprecating `csoundSetOutput` — which seems to have never really worked — in favor of `csoundSetParams`.) The [audio file types defined in csound.h](https://github.com/csound/csound/blob/5d10796c6af8b9703d9f4ad27464d174a01194f8/include/csound.h#L278) might be used for this.

**Comment by vlazzarini** [comment]
csoundSetOutput() works afaik. If it doesn't, it needs to be fixed. It should not be deprecated. Give me some time to read all the comments before I can provide some reasonable response.

**Comment by vlazzarini** [comment]
I thought we had exposed the sf types, but we did not. I can do that, but I need time to think it through.
csoundSetOption() can be used, just pass the options as strings with no blank spaces: eg
"--format=wav" , one option per call.

**Comment by nwhetsell** [comment]
> csoundSetOption() can be used, just pass the options as strings with no blank spaces: eg
"--format=wav"

Yep, I understand that from [your earlier comment](https://github.com/csound/csound/issues/700#issuecomment-248276866).

If sound file _formats_ are added to `CSOUND_PARAMS ` in addition to types, that would permit getting the output type and format using `csoundGetParams`. As it stands now, I see no way to get Csound’s output type and format using the current API.

**Comment by vlazzarini** [comment]
I had a look at this. I could expose type and format. However, there are some
issues:
1) To set a format/type, we also need to call set_output_format() or set_stdout_assign() in the
case of stdout. A simple setting of the parameter will not work. So it can lead to confusion
in that a csoundSetParam() call will have no effect on this. I am not quite sure I should add
calls to set_output_format() etc. in csoundSetParam(), and whether that would have implications.
As it is we expose the parameters that are simply set, no extra calls to do anything are needed.
2) The formats are held using the sndfile constants, and to translate these a client to the API
would have to look them up in sndfile.h. Not a big deal, but maybe awkward.

Possibly we can add a csoundGetOutput() etc to retrieve this information in a more 
structured way through the API. I think this might be the preferred route and I will
investigate it.

**Comment by vlazzarini** [comment]
I have added a csoundGetOutputFormat() function to the API to retrieve the output type and
format used by Csound.
