### ISSUE TITLE
Audio input does not work

### ISSUE THREAD

**Issue by gogins** [csound/csound#702]
Passing the -iadc flag to Csound on Android produces the following error message:

OpenSL: input open error.
Failed to initialize real time audio input

**Comment by gogins** [comment]
Currently, in rtopensl.c, only mono audio input is supported.

**Comment by vlazzarini** [comment]
the code seems to support stereo in, but the hardware may not.

**Comment by vlazzarini** [comment]
it's done. If it does not work then the hardware does not support it, you can try setting nchnls_i=1 and nchnls=2.

**Comment by gogins** [comment]
I made a few more changes to enable nchnls and nchnls_i to differ. On my tablet:

nchnls=1 works.
nchnls=1 nchnls_i=1 works.
nchnls=2 nchnls_i=1 works.
nchnls=2 does not work.
nchnls=2 nchnls_i=2 does not work.

I think this means that it is working but the tablet only has a mono mic. The mic can be heard in the Csound performance, but latency is bad. I only did minimal experimentation,
