### ISSUE TITLE
Help Installing CSound in a Computer Lab

### ISSUE THREAD

**Issue by MDellelo** [csound/csound#705]
Hi,

I'm trying to get CSound installed in a computer lab for use by a music composition class.  We're in a multi-user environment, so I need to get it set up so that multiple users can login to our Macs and launch the CSound application.  But the application appears to be unable to load the framework upon launch and it crashes.  I have an error report from the crash.  Can anyone here help me debug this and figure out how to get this working in our lab?

Process:               CsoundQt-d-py-cs6 [14052]
Path:                  /Applications/CsoundQt-d-py-cs6.app/Contents/MacOS/CsoundQt-d-py-cs6
Identifier:            CsoundQt-d-py-cs6
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           CsoundQt-d-py-cs6 [14052]
User ID:               1365828959

Date/Time:             2016-10-28 17:03:22.893 -0400
OS Version:            Mac OS X 10.11.6 (15G31)
Report Version:        11
Anonymous UUID:        9C2EC47A-0A4D-4651-D5F1-7B01089E371D

Time Awake Since Boot: 28000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @executable_path/../Frameworks/libcsnd6.6.0.dylib
  Referenced from: /Applications/CsoundQt-d-py-cs6.app/Contents/MacOS/CsoundQt-d-py-cs6
  Reason: no suitable image found.  Did find:
    /usr/local/lib/libcsnd6.6.0.dylib: stat() failed with errno=13

Binary Images:
    0x7fff6e5ea000 -     0x7fff6e621a47  dyld (360.22) <DC81CC9D-651A-3A45-8809-928282052BD3> /usr/lib/dyld
    0x7fff9bd38000 -     0x7fff9bd89fff  com.apple.audio.CoreAudio (4.3.0 - 4.3.0) <EA7D4F3B-062B-3C81-A98C-C89264D00D48> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fffa0554000 -     0x7fffa09cafff  com.apple.CoreFoundation (6.9 - 1258.1) <943A1383-DA6A-3DC0-ABCD-D9AEB3D0D34D> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation

Model: iMac13,2, BootROM IM131.010A.B09, 4 processors, Intel Core i7, 3.4 GHz, 16 GB, SMC 2.11f16
Graphics: NVIDIA GeForce GTX 680MX, NVIDIA GeForce GTX 680MX, PCIe, 2048 MB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D5434314753364D465238432D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D5434314753364D465238432D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xF4), Broadcom BCM43xx 1.0 (7.21.95.175.1a6)
Bluetooth: Version 4.4.6f1 17910, 3 services, 27 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
PCI Card: pci1b21,612, AHCI Controller, Thunderbolt@195,0,0
Serial ATA Device: APPLE HDD ST1000DM003, 1 TB
Serial ATA Device: HGST HTS721010A9E630, 1 TB
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Keyboard Hub
USB Device: Apple Keyboard
USB Device: FaceTime HD Camera (Built-in)
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Hub
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 3.0 Bus
USB Device: USB Optical Mouse
USB Device: MT1806
Thunderbolt Bus: iMac, Apple Inc., 23.4
Thunderbolt Device: G-DRIVE mobile with Thunderbolt, G-Technology, 1, 7.8

**Comment by kunstmusik** [comment]
@MDellelo - Did you use the Csound installer from:

https://github.com/csound/csound/releases/download/6.07.0/csound6.07-OSX-universal.dmg

to install the latest version of Csound?  Also, is the version of CsoundQT you installed the one that came with this installer or one separately released?

**Comment by MDellelo** [comment]
@kunstmusik - That's the installer I used, yes, for the both the framework and the application.

**Comment by kunstmusik** [comment]
@MDellelo - It sounds like an issue with the installer then.  My guess is that previous versions of the installer may have made a symlink in /usr/local/lib that is not being made in the current installer, and the version of CsoundQT provided in the installer has the link hardcoded to the older location.

@vlazzarini - looking at the installer script, it seems it is okay for the install_name_tool calls and that this is a problem with the version of CsoundQT provided in the installer.  Could you verify?  If that is indeed the case, then we might consider providing a new release, as well as providing a command-line call here for install_name_tool to use on CsoundQT as a stop-gap.

**Comment by vlazzarini** [comment]
This is a permissions issue, I think. The file is there but it can't be opened (stat error 13). Make sure permissions for /usr /usr/local /usr/local/lib and the file itself are read for everyone.

We heard a similar issue reported to the list a while ago.

**Comment by kunstmusik** [comment]
@MDellelo could you check the permissions for the library in /usr/local/lib?

**Comment by MDellelo** [comment]
@kunstmusik and @vlazzarini - Thanks for the help, changing permissions on that folder worked.

**Comment by kunstmusik** [comment]
Glad that worked out!  Closing out this ticket now.
