### ISSUE TITLE
ntrpol exponential/linear

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#709]
can ntrpol get an option to not only be linear but exponential/logarithmic as well?

**Comment by jpffitch** [comment]
In principlei is k but would need an extra aruument to say which 
exponential or lg you wated

**Comment by tjingboem** [comment]
yes, that would need an extra optional argument (the 3rd). When not used, the default would be 0.

0 linear
1 exponential
2 logarithmic

i am fading in one sound with another, but in my case it fades to quickly into the second sound. I use it for mixing a dry/wet signal and would like the effect (=wet) to mix in more slowly when i use the kpoint argument.
I imagine an exponential/logarithmic option could solve this?

**Comment by joachimheintz** [comment]
maybe the better way to do this is to adjust the kpoint parameter in the 
way you like.  so instead
	kpoint linseg 1, p3, 0
you could use
	kpoint transeg 1, p3, -3, 0
or something like this?

	joachim

**Comment by tjingboem** [comment]
that's a nice idea, Joachim.
i will try it out and report my findings

**Comment by jpffitch** [comment]
Which exponential do you want?  e^(ax) varies significantly with a (consider 0, -1, 1, 100,..)

**Comment by tjingboem** [comment]
i reckon this should be a Blue request and not so much a Csound issue...

i'm working on an instrument in Blue and I have replaced kpoint with a slider:

![screenshot from 2016-11-13 21-15-32](https://cloud.githubusercontent.com/assets/6670911/20248742/b82e98e0-a9ea-11e6-875e-a5b96ba64b7a.png)

it is the horizontal slider that replaces kpoint.

Unfortunately Blue does not provide a choice between exp/lin as FLTK does. I have already asked Steven if it would be possible to provide this option in the new JavaFX system that he is implementing atm.

Still i think an lin/exp/log option in ntrpol would be "the fastest way" to try out how you want to mix 2 signals.

**Comment by tjingboem** [comment]
John, i can't tell you which exponential i want - i simply lack the knowledge in maths. Probably that is the very reason that i would like to have such a mixing option in ntrpol...

I just hear the sounding result and now, starting from sound 1, sound #2 takes over too fast when i change kpoint from 0...1. I would like to hear sound 1 a while longer in the mix.
sound 1 and sound 2 have equal amplitude, but i have only little room in the fade process so that sound 1 remains audible.

**Comment by jpffitch** [comment]
ave you tried
    kk nterpol ....
    kk = (exp(kk)-1)/(exp(1)-1)

?  I tink that iw wat you might want.  If it s too fast or slow it is 
easily adjusted

**Comment by tjingboem** [comment]
i used your code min a new instrument to see what is happening:

kmix    linseg 0, p3, 1
kmix = (exp(kmix)-1)/(exp(1)-1)
printk2 kmix

and it looks like this is a good solution.
