### ISSUE TITLE
Using csound with multitrack MusicSequence on iOS

### ISSUE THREAD

**Issue by Rexhits** [csound/csound#710]
I've been working on an iOS APP with csound4ios as the "audio engine". So far, I'm able to load a midi file into MusicSequence, set a virtual midi endpoint and send the midi events from MusicSequence to CsoundObj via the virtual midi endpoint. But I got stuck on multitrack midi routing, ideally what I want to do is sending each MusicTrack in the MusicSequence to one CsoundObj instance, that way I can have multiple csd loaded and make my APP act like a proper multitrack sequencer without MIDI's 16-channel limitation. 

Since I'm totally a newbie in csound4ios, coreAudio and coreMIDI, I believe there should be an easy way but I just can't figure it out... Here's what I tried and failed so far:

1. Setting up an AUGraph, calling "MusicTrackSetDestNode()" to route each track to an AUNode. I retrieved the csound AudioUnit by calling "getAudioUnit()", but soon I got lost on how to connect the AudioUnit to an AUNode...

2. Creating multiple MidiClients, Virtual Midi Endpoints and Midi sources, trying to route the the midi events via coreMIDI using "MusicTrackSetDestMIDIEndpoint()", but I didn't figure out how to connect the endpoints to the CsoundObjs...

This is basically it, any help would be appreciated! Let me know if you need anything else such as the code. Thanks!

**Comment by vlazzarini** [comment]
This is not an issue with the code. Please use the mailing lists for programming help.
