### ISSUE TITLE
eval logical expression

### ISSUE THREAD

**Issue by vlazzarini** [csound/csound#712]
It has been requested that csound allow the evaluation of predicates, return 0 or 1 e.g.:

k2 = k1 > 0;  k2 is 1 if k1 is gt 0 otherwise 0

this could be done by parsing the expression
into k1 > 0 ? 1 : 0

**Comment by jpffitch** [comment]
This looks like the wrong way to go.  The punning of Booleans to integers comes from BCPL which was typeless.  In the intended use an opcode is the best way.⁣

**Comment by kunstmusik** [comment]
I'm with John on this, I don't think this would be good.  We have a boolean type already (though it is not exposed to the user) and I think it'd be a step backwards to use ints/floats instead.  I think we'd open ourselves up to potential coding errors, without much benefit.

**Comment by vlazzarini** [comment]
Agreed
