### ISSUE TITLE
ftgentmp can't take string as parameter

### ISSUE THREAD

**Issue by hlolli** [csound/csound#714]
It seems to me that ftgenonce can take a string as parameter for GEN but not ftgentmp. Running on Csound 6.08 from 14th September.

this fails
```
ipadTable ftgentmp 0, 0,  1025, "padsynth", 40, 5,  10, 3, 3, 2000,  0.7600046992, 0.6199994683, 0.9399998784, 0.4400023818, 0.0600003302, 0.8499968648, 0.0899999291, 0.8199964762, 0.3199984133, 0.9400014281, 0.3000001907, 0.120003365, 0.1799997687, 0.5200006366, 0.9300042987`
```
but this won't
```
ipadTable ftgenonce 0, 0,  1025, "padsynth", 40, 5,  10, 3, 3, 2000,  0.7600046992, 0.6199994683, 0.9399998784, 0.4400023818, 0.0600003302, 0.8499968648, 0.0899999291, 0.8199964762, 0.3199984133, 0.9400014281, 0.3000001907, 0.120003365, 0.1799997687, 0.5200006366, 0.9300042987
```

**Comment by jpffitch** [comment]
This needs a little new code -- currently string only permitted as p5 but you are wanting p4.  Hooks exist just needs time

**Comment by jpffitch** [comment]
Easie that I tought for you case -- in git soon

**Comment by hlolli** [comment]
I made an attempt to solve this myself yesterday as I found it obvious that ftgen and ftgentmp were almost identical in structure with more i-rate/S-type variations of ftgen to ftgentmp. But I see that I may need some help with temp building debugging version of csound. But that for another time.
