### ISSUE TITLE
Installation on Mac

### ISSUE THREAD

**Issue by sameoldcaviar** [csound/csound#715]
Hi,

I am having a basic issue installing CSound on my Mac.  I had it previously however since updates it seems certain software doesn't load.  I have downloaded the latest dmg and gone through installation.  Once completed it is nowhere to be seen on my Mac.  My Mac is currently running with: OS X Yosemite 10.10.5.  I am not sure if this is just a problem with Yosemite and whether I need to update again as I had a similar problem with Puredata also.  

Thanks for your help.

**Comment by vlazzarini** [comment]
How do you know Csound was not installed? If you try running the '/usr/local/bin/csound' command on the terminal you will be able to check. Or look in your disk under /Library/Frameworks to see if the CsoundLib64.framework is there. Or finally, run the CsoundQT that comes in the installer to see if it opens up.

**Comment by jpffitch** [comment]
No response for weeks.  Should this be closed?
