### ISSUE TITLE
Update Build.md

### ISSUE THREAD

**Issue by berntisak** [csound/csound#717]
Build.md needs to be updated at least for OS X, which only has Homebrew instructions (that probably should be removed as long as it's not updated?)

**Comment by nwhetsell** [comment]
Seconded, and even better (perhaps) would be incorporating the build instructions into README.md.

**Comment by kunstmusik** [comment]
Assigning to 7.0.0 milestone so that we have visibility on this and ensure we take care of it before we release CS7.

**Comment by vlazzarini** [comment]
this is done now in #1940, a fresh set of instructions for the basic platforms. Further contributions are welcome, but I will close this ticket now.
