### ISSUE TITLE
Emscripten: modify to allow custom ksmps

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#718]
The current Emscripten build forces ksmps to be 256 to match the buffersize of the requested ScriptProcessorNode.  The code in CsoundObj.js and CsoundObj.c should be modified to:

1. Allow any ksmps
2. Run Csound (i.e., csoundPerfKsmps()) as many times as necessary to fill up the buffersize of the script processor node

**Comment by vlazzarini** [comment]
alternatively, we can use csoundPerformBuffer and align the Csound buffer size to the ScriptProcessorNode buffer size. Then write/read to/from the buffer, rather than spin/spout.
This would save JS calls and would possibly be more efficient.

**Comment by gogins** [comment]
I suggest that rather than investing in Emscripten and PNaCl, we should
proceed with WebAssembly. See https://github.com/csound/csound/issues/668
and http://webassembly.org/roadmap/.

Best,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by kunstmusik** [comment]
The Emscripten work would be relevant to WASM as WASM is currently using a
branch of Emscripten to compile code to .wasm.

**Comment by eddyc** [comment]
Has there been any mention of audio within the WASM spec so far? I agree
that it is definitely the future, I am afraid though as seems to be the
case with the Web Audio API currently, getting any sort of serious audio
programming interface for custom synthesis in the browser may take a while.
Ed

**Comment by kunstmusik** [comment]
I am not certain, but it looks to me that WASM is not going to offer a separate audio API and that WebAudio would still be what one gets. This is from looking at:

http://webassembly.org/docs/high-level-goals/
http://webassembly.org/docs/faq/

It's really based heavily around asm.js/Emscripten at this time, with pretty much the same design goals. I don't particularly think there's going to be a lot gained except for speed with WASM over Emscripten.

**Comment by kunstmusik** [comment]
Closing: WASM build is now released and ksmps was made aligned to ScriptProcessorNode.
