### ISSUE TITLE
readme.txt file in minimal Windows archives should be encoded using UTF-8

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#720]
This file is in Csound6.08_Win32_minimal.zip and Csound6.08_Win64_minimal.zip on the [releases page](https://github.com/csound/csound/releases), and it appears to be encoded using [Windows‑1252](https://en.wikipedia.org/wiki/Windows-1252). Many text editors will assume an encoding of UTF‑8 and display this file as

```
… you will need to add the ëbiní directory to your system path, and create an OPCODE6DIR64 system variable that points to this ëlibí folder. 
```

instead of the expected

```
… you will need to add the ‘bin’ directory to your system path, and create an OPCODE6DIR64 system variable that points to this ‘lib’ folder. 
```

As an alternative, if the left and right quotes are replaced with straight quotes (or omitted entirely), the file can be encoded using ASCII.

(As a side-note, it may be worth adding instructions to the readme.txt file describing how to “add the ‘bin’ directory to your system path, and create an OPCODE6DIR64 system variable that points to this ‘lib’ folder.”)

**Comment by rorywalsh** [comment]
That's a fair point about the encoding. Feel free to prepare a version of
that file with the appropriate instructions. I'll happily add it to future
zip files.

**Comment by nwhetsell** [comment]
Is the readme.txt file included in the Windows archives in the Csound repository?

**Comment by rorywalsh** [comment]
No, but if you write one we can add it somewhere.

**Comment by nwhetsell** [comment]
[Here’s a new README.txt](https://github.com/csound/csound/files/629223/README.txt), containing:

```
This folder contains a minimal build of Csound for 64-bit Windows. If you're
trying to install Csound along with its documentation,
[CsoundQt](https://csoundqt.github.io), and other extras, download and run one
of the setup executables at https://github.com/csound/csound/releases. The names
of the setup executables begin with Setup_Csound6_x64_.

It's a good idea, but not essential, to move the bin, include, and lib folders
to roughly where Csound's setup executables install them. To do this, open an
administrator Command Prompt in this folder and enter

    set CsoundPath=%ProgramFiles%\Csound6_x64
    if not exist "%CsoundPath%\NUL" mkdir "%CsoundPath%"
    move bin "%CsoundPath%"
    move include "%CsoundPath%"
    move lib "%CsoundPath%"

To easily run the executables in the bin folder, you must add the bin folder to
your Windows path and create an OPCODE6DIR64 environment variable. To do this on
Windows 10:

1. Right-click the Start button, and then select Run from the menu that appears.

2. Type

       sysdm.cpl ,3

   (note the space between sysdm.cpl and ,3) in the Open field and press Enter.
The System Properties window appears with the Advanced tab selected.

3. Click Environment Variables at the bottom of the window.

4. In system variables, select Path, and then click Edit. Click New, enter the
path to the bin folder, and then click OK. If you moved the bin folder to where
Csound's setup executables install it, the path of the bin folder is probably
C:\Program Files\Csound6_x64\bin.

5. In system variables, click New to create an environment variable named
OPCODE6DIR64 with a value of the path to the csound\plugins64-6.0 folder within
the lib folder, and then click OK. If you moved the lib folder to where Csound's
setup executables install it, this path is probably
C:\Program Files\Csound6_x64\lib\csound\plugins64-6.0.

If you want to use the minimal build of Csound with Visual Studio, you must
create a csound64.lib file. To do this, open an administrator Command Prompt in
the bin folder and enter

    set PATH=%PATH%;%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\bin
    echo LIBRARY csound64.dll > csound64.def && echo EXPORTS >> csound64.def
    for /F "skip=19 tokens=4" %G in ('dumpbin /exports csound64.dll') do @echo %G >> csound64.def
    if not exist ..\lib\NUL mkdir ..\lib
    lib /def:csound64.def /out:..\lib\csound64.lib /machine:x64
```

I kept everything as ASCII and tried to use a maximum line width of 80 characters. I tried to make it comprehensible as plain text, but it’s also Github-flavored Markdown if you want to change the extension from .txt to .md.

I wrote this for 64‑bit Windows, and hopefully it’s adaptable to 32‑bit Windows.

For what it’s worth, I’m using some of these scripts on [AppVeyor](https://ci.appveyor.com/project/nwhetsell/csound-api/build/1.0.76). Many, many thanks for putting together this minimal build. It has cut AppVeyor’s build time from [around 6 minutes](https://ci.appveyor.com/project/nwhetsell/csound-api/build/1.0.69) to around 2 minutes.

**Comment by vlazzarini** [comment]
looks good, thanks. Rory, consider adding this to the git repo under installers/windows. If you have a script that builds the zip, you could add it there too.

**Comment by rorywalsh** [comment]
I've added this now, but renamed it to minimalReadme.txt as github uses any
readme.txt files as that folder's info text, which in this case would be a
bit misleading. Thanks for this Nate.

**Comment by nwhetsell** [comment]
No problem!

It may be better to create a new folder (“minimal”, say) in [installer](https://github.com/csound/csound/tree/develop/installer) and move minimalReadme.txt to README.txt in that folder. Eventually, perhaps the scripts used to create the minimal build can go in that folder. (Better still might be to create a separate repository for Csound’s installers.)

**Comment by rorywalsh** [comment]
I've now including import libraries for Visual Studio in each of the minimal zip files. I modified the readme to take this into account, but left in your instructions on creating one from scratch as it's useful information for developers. The scripts used to create the build can be found [here](https://github.com/csound/csound/tree/develop/mingw64). It's basically the same script used to build the full version.

**Comment by nwhetsell** [comment]
If I were you, I’d omit the instructions for creating a csound64.lib file from README.txt. Pull request #738 is an attempt to partially address this, but there are now at least four csound64.lib creation scripts:

1. https://github.com/csound/csound/blob/develop/make_import_library.cmd
2. https://github.com/csound/csound/blob/develop/mingw64/make_import_library.cmd
3. https://github.com/csound/csound/blob/develop/mingw64/make_import_library_32.cmd
4. The one in the minimal Windows build’s README.txt

I think there should be only one csound64.lib creation script.
