### ISSUE TITLE
parenthesis in score macro arguments.

### ISSUE THREAD

**Issue by moongodjon** [csound/csound#721]
in Csound 5.08, using parentheses in a score macro argument makes Csound stop reading the arguments too early. e.g. 
`#define MACRO(a,b,c,d) # [ $a+$b+$c+$d ] #`
`i1 $MACRO(0' 1 ' (3/2)' 2) `
fails with the error:

> ... 
>defining argument __MACRO__c Too few arguments to macro
>...

Also, nested brackets no longer seem to be supported in csound 5.08, giving the error:
>score error: illegal character [(5b) in [] expression

which wasn't a problem in Csound 5.05

**Comment by jpffitch** [comment]
5.08 is rather old is unlikely to be modified.  That whole area has been rewritten anyway.  Does it Gail in 6.08⁣

**Comment by moongodjon** [comment]
Sorry, I meant 6.05, 6.08, and mistyped.

**Comment by vlazzarini** [comment]
which one? 6.05 or 6.08?

**Comment by jpffitch** [comment]
I get a different error; still looking

**Comment by jpffitch** [comment]
The closing bracket in arg3 is treated as closing the $MACRO(0' 1 ' (1/2)
As expansion happens before lexing not sure how to fix; seems of the essence

**Comment by jpffitch** [comment]
Suggestions
1:  insist on ') as arg terminator as $MACRO(0' 1 ' (1/2)  '4 ')

2: allow terminator to be flexible
#close ]
$MACRO(0' 1 ' (1/2) ' 4]

Tere must be more schemes

**Comment by nwhetsell** [comment]
I think option 1 would break every use of function-like macros currently in the wild, and also `$MACRO(1'2'3'4')` is currently a valid use of a 5-argument macro (the last argument is empty). Neither option seems user-friendly, and it looks like they still leave room for future breakage. For example, there’s a reasonable argument to be made that

```
$MACRO(0'1'(1 # 0)'4)
```

should pass `(1 # 0)` as `MACRO`’s third argument, but my guess is that will collide with `#` as a parameter value separator.

I think the way to address this so that macro parameter value lists “just work” is to use Flex’s `%option stack` directive with `yy_push_state` and `yy_pop_state`. To be honest, I haven’t worked out exactly what states would be needed myself yet, but I think it would look something like

* A `macro_parameter_value_list` state such that
    * if `['#]` is matched, finish the current macro parameter value and prepare for another one
    * if a literal `)` is matched, finish the current macro parameter value (if there is one – the macro may take 0 arguments) and pop this state
    * if any other character (including a literal `(`) is matched, `unput` the character, and push a `macro_parameter_value` state onto the stack
* A `macro_parameter_value` state such that
    * if a literal `(` is matched, append it to the value of the macro parameter, and push a `macro_parameter_parenthesized_expression` state onto the stack
    * if `['#)]` is matched, unput the character and pop this state
    * if any other character is matched, just append it to the value of the macro parameter
* A `macro_parameter_parenthesized_expression` state such that
    * if a literal `(` is matched, append it to the value of the macro parameter, and push another `macro_parameter_parenthesized_expression` state onto the stack
    * if a literal `)` is matched, append it to the value of the macro parameter and pop this state
    * if any other character is matched, just append it to the value of the macro parameter

**Comment by nwhetsell** [comment]
I have this working in the linter-csound preprocessor if it’s any help: https://github.com/nwhetsell/linter-csound/blob/e0d3a67ba863f2559998ce8ca8776a0600d92c59/lib/csound-parser/preprocessor.jison-lex#L201. I’m doing almost exactly what I outlined, except I renamed `macro_parameter_parenthesized_expression` to `macro_parameter_value_parenthetical`.

**Comment by jpffitch** [comment]
Ay cace f a path to te csounf lexing code?

**Comment by nwhetsell** [comment]
I think something got garbled in your question. What about lexing code?

**Comment by jpffitch** [comment]
The ) closes the macro arguments. If you want the ) to be treated as not the terminator it needs to be quoted as 
 `#define MACRO(a,b,c,d) # [ $a+$b+$c+$d ] # `
`i1 $MACRO(0' 1 ' (3/2\)' 2)
`

**Comment by nwhetsell** [comment]
Commit a42d90e24c450866fd699b655aeeb178c327ab50 doesn’t seem like a particularly good fix for this. Anyone who enclosed macro arguments in parentheses will now have to go back through their orchestras and escape closing parens.

Also, you can no longer pass strings with escaped characters as macro arguments. Running this

```csound
#define PRINT(STRING) #prints $STRING#
$PRINT("==> hello, world\n")
scoreline_i "e"
```

now shows

```
defining argument `PRINT``STRING as...#"==> hello, worldn"#
Elapsed time at end of orchestra compile: real: 0.001s, CPU: 0.001s
sorting score ...
	... done
Elapsed time at end of score sort: real: 0.002s, CPU: 0.002s
graphics suppressed, ascii substituted
0dBFS level = 32768.0
==> hello, worldnorch now loaded
```

**Comment by jpffitch** [comment]
Oh well it was an attempt to fix an impossible case

**Comment by nwhetsell** [comment]
I truly hope this can be of some help:

https://github.com/nwhetsell/linter-csound/blob/74126a33a201fa909cc0979b9fd30a9f2a47f9be/lib/csound-parser/preprocessor.jison-lex#L251-L276

**Comment by nwhetsell** [comment]
It might be worth mentioning that even after commit 3e0b441b55fd8e07d70b0908da8165b889feb883, running

```csound
#define PRINT(STRING) #prints $STRING#
$PRINT("==> (hello, world)")
scoreline_i "e"
```

results in

```
--Csound version 6.09 (double samples) Jan 17 2017 
[commit: f496ca0848fad3b02a344cca3831484c0d789444]
libsndfile-1.0.26
scoreless operation
orchname:  /Users/nathanwhetsell/Downloads/test.orc
defining argument `PRINT``STRING as...#"==> (hello, world#

error: syntax error, unexpected ')', expecting NEWLINE or ','  (token ")") from file … (1)
 line 1:
>>>) <<<
Parsing failed due to invalid input!
Stopping on parser failure
cannot compile orchestra
end of score.		   overall amps:      0.0
	   overall samples out of range:        0
1 errors in performance
```

**Comment by jpffitch** [comment]
That is because it is a syntax error.

Bracket needs escaping.⁣

**Comment by nwhetsell** [comment]
It seems a bit unexpected to have to escape closing parentheses in _strings_ passed to a macro, but maybe that’s just me.

**Comment by jpffitch** [comment]
Slight affect of expanding macros inside strings.  Possibly could change ) inside a string.⁣

**Comment by jpffitch** [comment]
Still not convinced but now brackets must match for argumets.  Tested a little but seems to work
