### ISSUE TITLE
Array variables should not be allowed to have types redefined

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#728]
From the Csound users mailing list discussion, there is a problem in that the parser allows variables to be defined as arrays a second time, ignoring the array definition and using the already registered type for the variable name.  The following CSD highlights the problem:

```csound-csd
<CsoundSynthesizer>
<CsOptions>
</CsOptions>
; ==============================================
<CsInstruments>
sr = 48000
ksmps = 1
;nchnls = 2
0dbfs = 1
instr 1
karr[] fillarray 1,2,3,4
karr[] = karr + 4
kindx = 0
while kindx < 4 do
  printk2 karr[kindx]
  kindx += 1
od

endin

instr 2
karr init 1
karr[] = karr + 4
printk2 karr

endin
</CsInstruments>
; ==============================================
<CsScore>
i1 0 0.001
i2 0.1 0.001
</CsScore>
</CsoundSynthesizer>
```

The above operates, but it probably shouldn't. In instr 2, the karr[]
in the second line functions as just karr, which is defined first in
the line above it as a k-rate scalar value.  The second line is
misleading in instr2, and I would imagine it *should* be considered a
bug to redeclare a variable's type a second time for arrays (and
explicitly-typed vars in CS7).  This would be in-line with errors that
would be reported in C-like languages, such as:

```
int x = 4;
int x = 5;  // ERROR
```

**Comment by nwhetsell** [comment]
@kunstmusik This is off-topic, but if you write

````markdown
```csound-document
<CsoundSynthesizer>…
```
````

or

````markdown
```csound-csd
<CsoundSynthesizer>…
```
````

instead of

````markdown
```
<CsoundSynthesizer>…
```
````

then [GitHub Linguist](https://github.com/github/linguist) will highlight it for you:

```csound-csd
<CsoundSynthesizer>
<CsOptions>
</CsOptions>
; ==============================================
<CsInstruments>
sr = 48000
ksmps = 1
;nchnls = 2
0dbfs = 1
instr 1
karr[] fillarray 1,2,3,4
karr[] = karr + 4
kindx = 0
while kindx < 4 do
  printk2 karr[kindx]
  kindx += 1
od

endin

instr 2
karr init 1
karr[] = karr + 4
printk2 karr

endin
</CsInstruments>
; ==============================================
<CsScore>
i1 0 0.001
i2 0.1 0.001
</CsScore>
</CsoundSynthesizer>
```

You can also use

````markdown
```csound
; Csound code
```
````

for orchestra-only snippets.

**Comment by kunstmusik** [comment]
@nwhetsell Wow, thanks for that Nate, I didn't realize this was supported.  Taking a look, thanks for contributing that to Github Linguist. ;)

**Comment by vlazzarini** [comment]
it's really nice. Thanks @nwhetsell

**Comment by rorywalsh** [comment]
Neat.

**Comment by nwhetsell** [comment]
:beers:

**Comment by vlazzarini** [comment]
Should we not fix this? It's a rather old bug.

**Comment by vlazzarini** [comment]
Bumping this again. Should it not be fixed? @jpff ?

**Comment by jpffitch** [comment]
Steven wrote the type resolution  code. I have not looked at it.

⁣Get TypeApp for Android ​

**Comment by jpffitch** [comment]
I think I have traced this down to the function csoundCreateVariable which does not check to see if the variable already exists before creating a variable in the pool. If the name matches but the the type does not there is a problem.

I am not up to sped on the variable creation so it may take a while to chase.

**Comment by kunstmusik** [comment]
I think it might be easier to just work on this in CS7 code since the
parser has changed a bit there, and leave the behavior as-is for CS6
since it's been stable for years like this.

**Comment by jpffitch** [comment]
I am happy to leae this to cs7.  Just was feeling guilty aout it.

**Comment by kunstmusik** [comment]
Assigning to 7.0.0, think this should be addressed before release.

**Comment by vlazzarini** [comment]
Here's the issue with the first instrument. The code is parsed as

```
fillarray.k args:	karr	1	2	3	4
##add.[i args:	#k0[]	karr	4
=.generic args:	karr	#k0[]
```
Since `##add.[i ` does not update the output at i-time but `=.generic` does, we have zeros copied into the `karr` array. Then at performance time the computation uses that zeroed array as the starting point.

So the problem in Csound 7 is not so much the type redefinition in this case, but a mismatch of init and perf opcodes. If `=.generic` was only copying at perf time, then the code would give the correct results.

In Engine/csound_type_system.c:339 we have

```
int copyVarGenericInit(CSOUND *csound, void *p) {
    ASSIGN* assign = (ASSIGN*)p;
    int flag = 0;
    CS_TYPE* type = csoundGetTypeForArg(assign->a);

    if(type == &CS_VAR_TYPE_ARRAY) {
      ARRAYDAT* adat = (ARRAYDAT*) assign->a;
      if(adat->arrayType == &CS_VAR_TYPE_I) flag = 1;
    } else if(type == &CS_VAR_TYPE_I) flag = 1;

    if (flag) {
      assign->h.perf = copyVarNoOp;
    }
    return copyVarGeneric(csound, p);
}

```

If I change this to:

```
int copyVarGenericInit(CSOUND *csound, void *p) {
    ASSIGN* assign = (ASSIGN*)p;
    int flag = 0;
    CS_TYPE* type = csoundGetTypeForArg(assign->a);

    if(type == &CS_VAR_TYPE_ARRAY) {
      ARRAYDAT* adat = (ARRAYDAT*) assign->a;
      if(adat->arrayType == &CS_VAR_TYPE_I) flag = 1;
    } else if(type == &CS_VAR_TYPE_I) flag = 1;

    if (flag) {
      assign->h.perf = copyVarNoOp;
      return copyVarGeneric(csound, p);
    }
    return OK;
}
```

The code  produces the expected results. However, this fails test 85

```
Test 85: test multiple operations on multiple array types (test_array_operations.csd)
	Return Code: 1	Expected: 0
```
-----------

In the second instrument, we have

```
init.k args:	karr	1
##add.kk args:	#k0	karr	4
=.k args:	karr	#k0
printk2 args:	karr	0	0
```

So in this case, there are no arrays at all, karr[] is just a plain kvar. That does seem a more straightforward parser issue where a syntax error should result (e.g. you can't assign a kvar to an array).

**Comment by vlazzarini** [comment]
The problem with test 85 is that the array subtraction, multiplication and division were not correctly implemented for k-vars (but addition was). So with that fixed, all tests passed with the suggested change in the copy generic code. Making a PR for this now

**Comment by vlazzarini** [comment]
Both issues are now taken care of in #1942
