### ISSUE TITLE
FLTK valuators crash csound in UDP server mode

### ISSUE THREAD

**Issue by extrasharp** [csound/csound#729]
Starting csound on Arch Linux with
`./server.csd`

where server.csd is
```
#!/usr/bin/csound

<CsoundSynthesizer>

<CsOptions>
--port=33333 -+rtaudio=jack -odac -b512 -B2048
</CsOptions>

<CsInstruments>

sr = 48000
ksmps = 32
nchnls = 2
0dbfs = 1

</CsInstruments>
</CsoundSynthesizer>
```

then sending the following to the daemon over UDP
```
FLpanel "heyo", 100, 100
gks1, ihs1 FLknob "knob", 440, 880, 0, 1, -1, 50, 10, 10
FLpanelEnd

FLrun
```

will open a window just fine, but will crash when moving the knob.
I also tried this with FLslider to the same effect.

the above csound code works fine when put into the server.csd file as part of the orchestra header.

I realize this might not be the intended way to use FLTK opcodes but I'm just experimenting around and perhaps it could be fixed?

**Comment by jpffitch** [comment]
I gtt a cras before te FLun

#0  0x00007ffff70d249a in __strcmp_sse2_unaligned () from /lib64/libc.so.6
#1  0x00007fffe42dd4cd in EndPanel (csound=0x6044a0, p=0x7fffdc103058)
    at /home/jpff/csound6/InOut/widgets.cpp:2682
#2  0x00007ffff7960b99 in init0 (csound=csound@entry=0x6044a0)
    at /home/jpff/csound6/Engine/insert.c:64
#3  0x00007ffff7b2d07b in csoundCompileTree (csound=csound@entry=0x6044a0, 
    root=root@entry=0x7fffdc101cc0)
    at /home/jpff/csound6/Engine/csound_orc_compile.c:1696
#4  0x00007ffff7b2da5b in csoundCompileOrc (csound=csound@entry=0x6044a0, 
    str=str@entry=0x7fffdc0008d0 "FLpanelEnd\n")
    at /home/jpff/csound6/Engine/csound_orc_compile.c:1796
#5  0x00007ffff7a7d9dc in udp_recv (pdata=0x7b3d30)
    at /home/jpff/csound6/Top/server.c:64

Actual crash is
2682          if (UNLIKELY(strcmp( adrstk.h->optext->t.opcod, "FLpanel")))
(gdb) print adrstk.h->optext->t.opcod
$1 = 0x0

I have added a ceck so it does not cras but tere is sme initialisation missing I guess

**Comment by vlazzarini** [comment]
which file is the crashing code in?

**Comment by vlazzarini** [comment]
Ok, this is what I figured out. When FLrun is going to open the display, it needs to be running on the main thread (or at least here on OSX). The server compiles and runs global code in a separate thread. So when it attempts to run FLrun, it can't. 

A solution that appears to run OK is to place the code in an instrument and then schedule it. This
will make the code run in the main thread. For example, this works here:

```
instr 1000
FLpanel "heyo", 100, 100
gks1, ihs1 FLknob "knob", 440, 880, 0, 1, -1, 50, 10, 10
FLpanelEnd
FLrun
endin
schedule(1000,0,0)
```

Now I realise Linux might be different and we might be looking at two different issues with FLTK. On OSX, your example crashes as soon as FLrun is called. One significant difference might be (I don't know) that on Linux FLTK is run with threads. On OSX, it is not.

**Comment by vlazzarini** [comment]
can we close this now? It's FLTK-related and cannot be helped.
