### ISSUE TITLE
Internal Error With Nested Parentheses

### ISSUE THREAD

**Issue by ldo** [csound/csound#733]
The enclosed file [macro-bug.csd.txt](https://github.com/csound/csound/files/659277/macro-bug.csd.txt) illustrates a problem with expanding macro arguments containing nested parentheses. I use parentheses around macro arguments to avoid the well-known precedence problems you can get with string substitutions. However, in this case it seems to trigger an “internal error” during the macro expansion.

Either of the last two lines in the score can trigger the problem; I have commented out one and uncommented the other, but you can also try it the other way round.

The clue in the diagnostic lines may indicate that the argument parsing is stopping when it gets to the second opening parenthesis, instead of continuing past nested parentheses to the corresponding closing parenthesis.

I am using Csound version 6.08 from the package that comes with Debian Unstable.

**Comment by jpffitch** [comment]
Same as #721
