### ISSUE TITLE
OSCsend: empty string for localhost segfaults

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#735]
for instance:
instr 1
 OSCsend  1,"", 7000, "/ITL/scene/text", "sss", "set", "txt", "Hello Csound!"
endin

the empty string for ihost should be allowed according to http://csound.github.io/docs/manual/OSCsend.html and worked in Csound5 (not sure i tested it later).

replacing "" by "localhost" works.

this is on debian unstable with csound 6.08 develop from november 18.

**Comment by jpffitch** [comment]
Consequence of change to caching host name.  Not fixed yet

**Comment by joachimheintz** [comment]
works for me =)
