### ISSUE TITLE
luajit-2.1 compatibility

### ISSUE THREAD

**Issue by jpgr87** [csound/csound#737]
Luajit has had 2.1 beta version out since august 2015, and Fedora updated to that version in the development branch this past august.  csound is currently set up to search for the luajit header files under the luajit-2.0 directory path.  Are there plans to support luajit-2.1 in the near future?

**Comment by gogins** [comment]
It should just work, just set the CMAKE configuration variables for LuaJIT
using cmake-gui or by passing them to the CMake command.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by ignatenkobrain** [comment]
@gogins would be nice if you would start using pkg-config file to locate luajit...

**Comment by gogins** [comment]
I will look into pkg-config. One issue is of course the need to build everything for Windows.

**Comment by gogins** [comment]
I have implemented the use of pkg-config in find_package for LuaJIT.

**Comment by gogins** [comment]
Closing this as I do not plain to maintain LuaJIT in Csound. If someone else wants it, feel free.
