### ISSUE TITLE
UDOs can silently change the local ksmps to the value of one of it's arguments

### ISSUE THREAD

**Issue by anton-k** [csound/csound#741]
Using UDOs can lead to strange errors with local ksmps values set to strange values. My guess is the memory somehow becomes shared between the memory cell for local ksmps and for arguments of UDOs. 

I don't know how to recreate the bug but when I find some UDO and inline the code the error disappears. The error says 

~~~
instr 31:  p1 = 31.008
INIT ERROR in instr 31: RunDirectMono: invalid local ksmps value: 7
aL	aR	RunDirectMono	iId	iChannel	
		   T 12.074 - note deleted.  i31 had 1 init errors
~~~

Where RunDirectMono is my UDO that I invoke within the instrument. The code for `RunDirectMono` is like this. We can see that there is  no setKsmps in it:

I'm using it to read mono-audio file from the table.

~~~
opcode RunDirectMono, aa, i
    iId xin
    iTab1 = giTab1s[iId]
    kRatio = gkSpeeds[iId] * gkPitches[iId]
    aSnd lposcil3 1, kRatio, 0, ftlen(iTab1), iTab1
    xout aSnd, aSnd    
endop 
~~~

The strange number 7 for local ksmps is set from another place in my code the 7 is the value for one 
of the p-fields of the instrument that invokes the UDO. It's p5 pfield. The meaning of thecode is to start playing audio loop on the 7's bus. But if I start to play on the 8's bus there is no  error (but I guess that local ksmps is changed to 8 though I haven't asked for it).

PS: It's second time I was bitten by the bug. I don't know how to create a minimal example
since it happens when the audio app is quite big.  

I can send my source code if you want. But it's not that easy to test since it relies on OSC. Maybe I'll wrap it in the Python to highlight the error scenario. 

My Csound version is:  Csound version 6.08 (double samples) Sep 28 2016
OS: Ubuntu 14.04

**Comment by vlazzarini** [comment]
Are you supplying an extra parameter? That will be taken as local ksmps. It is documented here
http://www.csounds.com/manual/html/opcode.html

**Comment by anton-k** [comment]
Yes you are right. I didn't know about this extra argument feature. It's kind of unusual behavior.. 
That means that the problem is in my code. I have four UDO's that behave in the same way (with slight variations) and I've added extra argument to all of them except that one. and this leads to error. Thanks for clarification

**Comment by vlazzarini** [comment]
I think this feature is slightly hidden in the documentation.
