### ISSUE TITLE
Is it possible to set different number of inputs and outputs when csound is used with jack?

### ISSUE THREAD

**Issue by anton-k** [csound/csound#742]
I'm trying to create a jack-based mixer.

The mixer has many inputs (up to 16 or more) and several 2 or 4 outputs. But the csound fails to launch my code when `nchnls_i` is not equal to `nchnls`.

**Comment by gogins** [comment]
You can do this with the Jacko opcodes, because you must code the Jack connections in the Csound orchestra, and the routing is arbitrary.

**Comment by anton-k** [comment]
That's workaround.  But in the case of jack nchnls_i doesn't work as it's expected

**Comment by jpffitch** [comment]
Can you produce an example .csd etc?

**Comment by anton-k** [comment]
Here is the minimal example. It's a mixer console with two strips. So we are mixing two stereo channels to a single stereo channels. I'd like it to be:

~~~
nchnls_i = 4
nchnls = 2
~~~

but this gives me error: 

~~~
*** rtjack: input and output parameters are not consistent
~~~

When I change the `nchnls` to 4 it works fine

[mini-mixer.csd.zip](https://github.com/csound/csound/files/857256/mini-mixer.csd.zip)

**Comment by vlazzarini** [comment]
Now jack IO allows separate numbers of channels.

**Comment by anton-k** [comment]
Thanks Victor! Good to know!
