### ISSUE TITLE
Enhance reliability of C++ opcodes

### ISSUE THREAD

**Issue by gogins** [csound/csound#743]
Enhance the reliability of C++ opcodes:

1. Enforce thread safety against data races by using mutexes created by Csound and stored as Csound gobal variables. Each opcode instance should individually retrieve, store, and use these mutexes.
2. Override global operators new and delete in C++ plugin opcodes to use CSOUND.Alloc and CSOUND.Free. This should be done if and only if different instances of CSOUND do not share access to the same C++ objects.

The files to be enhanced are:

ableton_link_opcodes.cpp
ampmidid.cpp
doppler.cpp
faustgen.cpp (not doing this one)
ftsamplebank.cpp
jacko.cpp
linear_algebra.cpp
LuaCsound.cpp
mixer.cpp
padsynth_gen.cpp
signalflowgraph.cpp
vst4cs.cpp

**Comment by gogins** [comment]
I am considering changing OpcodeBase.hpp to do these things.

**Comment by gogins** [comment]
This was too hasty. Opcodes that use static collections may crash if operator delete is called too soon. I am  reverting all of these overrides. The mutex code I have left.

**Comment by vlazzarini** [comment]
just to note that the most appropriate mechanism for opcodes is csound->AuxAlloc() (not Malloc() or Calloc) as it will take care of de-allocation when it's appropriate for the engine. The standard practice is to allocate only if the memory needs expanding.

**Comment by gogins** [comment]
As I noted in the issue, that doesn't help because the life cycle of the
objects does not necessarily correspond with the life cycle of Csound's
allocator, so there is e.g. a crash when it is called at the wrong time.
Some objects exist before the allocator because they are static. Some
objects are static because they need to be so state can be managed across
opcode instances.

Possibly this could be resolved if modules were loaded and unloaded only
within the lifetime of the allocator, which I was assuming is the case, but
perhaps it is not.

Regards,
Mike

**Comment by gogins** [comment]
However, I will try AuxAlloc to see what happens.

Regards,
Mike

**Comment by gogins** [comment]
I am going to instrument a build to identify the timing of:

module loading
static constructors in the module
availability of the Csound allocator
calling new and delete

This in the signal flow graph opcodes.

**Comment by gogins** [comment]
I have verified that static constructors in a module, even though initialized within a function body that is called by csoundModuleCreate, use the pre-overloaded operator new.

This means that either the Csound allocator must not be used in opcodes, or else that if the Csound allocator is used, global objects should be created by the Csound allocator and stored as Csound global variables which, however, can be cached in the opcode.

**Comment by gogins** [comment]
CSOUND.AuxAlloc is not suitable for use in overloading operator new and delete because it depends on the existence for each allocation of an AUXCH struct that persists in the AUXCH chain.

**Comment by gogins** [comment]
Lifecycle of a plugin opcode:

csoundModuleCreate
csoundModuleInit
csoundModuleInit (it's a drag that this happens twice...)
...performance...
csoundModuleDestroy

What happens if a program runs the same instance of Csound again? I will find out.

**Comment by gogins** [comment]
I don't see a problem here if the following guidelines are observed:
