### ISSUE TITLE
String formatting opcodes are inconsistent

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#747]
I should note at the outset that I’m familiar with [conversion specifiers (like the `d` in `%d`) in C](http://pubs.opengroup.org/onlinepubs/009695399/functions/printf.html); that’s not what this issue is about.

In thinking about [this question](https://listserv.heanet.ie/cgi-bin/wa?A2=ind1701&L=CSOUND-DEV&P=62151) on the CSOUND-DEV list, I took a closer look at opcodes that work with conversion specifiers. This is what I found.

* prints and fprints accept
    * `%d`, `%i`, `%u`, `%o`, `%x`, and `%X` for integers.
    * `%f`, `%F`, `%e`, `%E`, `%g`, `%G`, `%a`, and `%A` for floating-point numbers.
    * `%c` to print an integer as a character. The `%s` specifier can’t be used with prints or fprints because neither accepts string arguments.
    * `%p`, which prints a memory address.
    * `%D`, `%U`, and `%O`, which seem to print a random or garbage number.
    * `%C`, `%L`, `%S`, `%h`, `%j`, `%l`, `%q`, `%v`, and `%z`, which seem to print nothing in prints and garbage in fprints. All but `C`, `S`, `q`, and `v` are length modifiers. `%C` is equivalent to `%lc`, and `%S` is equivalent to `%ls`. Also, in [Opcodes/fout.c](https://github.com/csound/csound/blob/develop/Opcodes/fout.c), it seems like `%h` and `%l` have some meaning, or did at one point.
    * A percent sign followed by any other ASCII letter, which seems to print that ASCII letter.
    * `%%`, which prints _two_ percent signs, not one.
* sprintf accepts
    * `%d`, `%i`, `%u`, `%o`, `%x`, and `%X` for integers (just like prints and fprints).
    * `%f`, `%F`, `%e`, `%E`, `%g`, and `%G` for floating-point numbers (but not `%a` or `%A`).
    * `%c` to print an integer as a character and `%s` to print a string.
    * `%%`, which prints one percent sign.
    * Attempting to use any other conversion specifier (including `%a` or `%A`) results in an error.

I’m assuming printks, printks2, fprintks, and sprintfk handle conversion specifiers the same as their i‑time versions.

Here’s an orchestra I used to test this:

```csound
prints "\nprints:\n"
prints "  %d %i %u %o %x %X\n", -1, -1, -1, 8, 10, 10
prints "  %f %F %e %E %g %G %a %A\n", \
  3.14159, 3.14159, 3.14159, 3.14159, 3.14159, 3.14159, 3.14159, 3.14159
// The %s specifier can’t be used with prints because prints doesn’t accept
// string arguments.
prints "  %c\n", 0x63
// The %p specifier appears to print a memory address.
prints "  %p\n", 1
// These write a random number.
prints "  %D %D %D\n", -1, 0, 10
prints "  %U %U %U\n", -1, 0, 10
prints "  %O %O %O\n", -1, 0, 10
// These in a sense print the character after the percent sign.
prints "  %B %H %I %J %K %M %P %Q %V %W %Y %Z %b %k %m %w %y\n", \
          1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11,12,13,14,15,16,17
// %C, %L, %S, %h, %j, %l, %q, %v, and %z seem to print nothing. All but C, S,
// q, and v are length modifiers. %C is equivalent to %lc, and %S is equivalent
// to %ls
// <http://pubs.opengroup.org/onlinepubs/009695399/functions/printf.html>.
prints "  x%Cx%Lx%Sx%hx%jx%lx%qx%vx%zx\n", \
           1, 2, 3, 4, 5, 6, 7, 8, 9
prints "  %% ~31mred ~~ ^[32mgreen ^^ %! %%\n"

prints "\nfprints:\n"
puts "  Writing strings to temp.txt", 1
Sfilename = "temp.txt"
fprints Sfilename, "  %d %i %u %o %x %X\n", -1, -1, -1, 8, 10, 10
fprints Sfilename, "  %f %F %e %E %g %G %a %A\n", \
  3.14159, 3.14159, 3.14159, 3.14159, 3.14159, 3.14159, 3.14159, 3.14159
fprints Sfilename, "  %c\n", 0x63
fprints Sfilename, "  %p\n", 1
fprints Sfilename, "  %D %D %D\n", -1, 0, 10
fprints Sfilename, "  %U %U %U\n", -1, 0, 10
fprints Sfilename, "  %O %O %O\n", -1, 0, 10
fprints Sfilename, "  %B %H %I %J %K %M %P %Q %V %W %Y %Z %b %k %m %w %y\n", \
                      1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11,12,13,14,15,16,17
// These appear to write garbage.
fprints Sfilename, "  x%Cx%Lx%Sx%hx%jx%lx%qx%vx%zx\n", \
                       1, 2, 3, 4, 5, 6, 7, 8, 9
fprints Sfilename, "  %%\n"

prints "\nsprintf:\n"
Sstring sprintf "  %d %i %u %o %x %X", -1, -1, -1, 8, 10, 10
puts Sstring, 1
Sstring sprintf "  %f %F %e %E %g %G", \
  3.14159, 3.14159, 3.14159, 3.14159, 3.14159, 3.14159
puts Sstring, 1
Sstring sprintf "  %% %c %s %%", 0x63, "string"
puts Sstring, 1
// No other specifiers, including %a and %A, work with sprintf.

scoreline_i "e"
```

Here’s the output from Csound at commit f496ca0848fad3b02a344cca3831484c0d789444.

```
prints:
  -1 -1 4294967295 10 a A
  3.141590 3.141590 3.141590e+00 3.141590E+00 3.14159 3.14159 0x1.921f9f01b866ep+1 0X1.921F9F01B866EP+1
  c
  0x1006dfcd0
  4302191488 4302191488 4302191488
  4302207536 4302207536 4302207536
  40033534340 40033534340 40033534340
  B H I J K M P Q V W Y Z b k m w y
  xxxxxxxxxx
  %% red ~ green ^ ; %%

fprints:
  Writing strings to temp.txt

sprintf:
  -1 -1 4294967295 10 a A
  3.141590 3.141590 3.141590e+00 3.141590E+00 3.14159 3.14159
  % c string %
```

**Comment by vlazzarini** [comment]
That's right, but I am not quite sure we can do much about it, because we can't really change the behaviour, apart from fixing it to what the manual says they should do if they are broken. Unfortunately, these opcodes were added at a time when things like consistency were not given sufficient attention. One way forward is to deprecate one of the sets and keep the most consistent one. Or to deprecate them all and add a complete set that is consistent.

**Comment by jpffitch** [comment]
Surely the %% -> %% is a bug.  Not sure about te rest as I never use them

**Comment by jpffitch** [comment]
I think I have fixed the bug but needs more testing

**Comment by nwhetsell** [comment]
In case there’s a regression, the fix referred to in https://github.com/csound/csound/issues/747#issuecomment-284850204 is commit 53ca79c27e31922b85476e970836fca185ccd920.
