### ISSUE TITLE
Octal escape sequences in strings don’t work

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#748]
From https://csound.github.io/docs/manual/StringsTop.html, among the escape sequences available in strings is

> _\nnn_ the character of which the ASCII code (in octal) is nnn

Although [`unquote_string` in Engine/csound_orc_compile.c](https://github.com/csound/csound/search?q=unquote_string+path%3AEngine+filename%3Acsound_orc_compile.c) appears intended to handle octal escape sequences, octal escape sequences don’t seem to work. Running this orchestra

```csound
prints "\n"
printf_i "%s \103\163\157\165\156\144\n", 1, "==>"
printf_i "==> %s\n", 1, "\103\163\157\165\156\144"
prints "==> \103\163\157\165\156\144\n"
puts "==> \103\163\157\165\156\144\n", 1
scoreline_i "e"
```

prints

```
==> 103163157165156144
==> 103163157165156144
==> 103163157165156144
==> 103163157165156144
```

instead of four repetitions of `==> Csound` in Csound at commit f496ca0848fad3b02a344cca3831484c0d789444.

**Comment by vlazzarini** [comment]
I had a look and unquote is not doing its job properly. It looks as if \ is somehow removed before
it gets there. I was able to modify the function to work with \\ but there's clearly something wrong somewhere else.

**Comment by jpffitch** [comment]
Have you tried \\103 ?  Just guessig but the \ may be interpreted before 
it get to the opcode.

**Comment by nwhetsell** [comment]
Replacing `\103` with `\\103` prints

```
==> \103163157165156144
==> \103163157165156144
==> 103163157165156144
==> \103163157165156144
```

**Comment by vlazzarini** [comment]
From what I can gather, a \ gets removed before it gets to unquote_string(). Maybe the parser is doing that.

**Comment by vlazzarini** [comment]
A \103 turns into 103 before unquote_string(); a \\103 is passed as \\103 and unquote_string turns
it into \103 (as expected). The unquote_string() is designed to expect for a single \ but it never
gets passed one.

**Comment by vlazzarini** [comment]
I checked the parser and the lexeme does not have the \, so the lexer must be dropping it.

**Comment by vlazzarini** [comment]
Ok, found it and committed a fix. Could anyone check whether that's working? It appears to work here I get this using the example above:

```
==> Csound
==> Csound
==> Csound
==> Csound
```
