### ISSUE TITLE
What do w and z do in scores?

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#750]
I noticed that the score lexer seemingly contains a `w` statement at

https://github.com/csound/csound/blob/78051adf20ab8ba54e1f221fce1ff4136abb2923/Engine/csound_sco.lex#L106

and a `z` statement at

https://github.com/csound/csound/blob/78051adf20ab8ba54e1f221fce1ff4136abb2923/Engine/csound_sco.lex#L109

In addition, the [manual](https://csound.github.io/docs/manual/ScoreTop.html) says:

> The input token 'z' is read as a number with the value of approximately 25367 years.

Is `z` a numerical constant in Csound scores, and, if so, where in Csound’s code is `z` converted to approximately 25,367 years? Does `w` mean anything in Csound scores?

**Comment by jpffitch** [comment]
On Sun, 22 Jan 2017, Nate Whetsell wrote:

> 
> I noticed that the score lexer seemingly contains a w statement at
> 
> https://github.com/csound/csound/blob/78051adf20ab8ba54e1f221fce1ff4136abb292
> 3/Engine/csound_sco.lex#L106
> 
> and a z statement at
> 
> https://github.com/csound/csound/blob/78051adf20ab8ba54e1f221fce1ff4136abb292
> 3/Engine/csound_sco.lex#L109
> 
> In addition, the manual says:
>
>       The input token 'z' is read as a number with the value of
>       approximately 25367 years.
> 
> Is z a numerical constant in Csound scores, and, if so, where in Csound’s code
> is z converted to approximately 25,367 years? Does w mean anything in Csound
> scores?

z is tanslated in Engine/srea.c in function stof.   Easy to find -- look 
for 'z'

w is used by the score waroed so it does exists but do not use as it will 
give probles as it is auto generated

**Comment by nwhetsell** [comment]
> Easy to find -- look for 'z'

Once you know which file to look in, certainly. I think that should be [Engine/srea**d**.c](https://github.com/csound/csound/search?q=stof+path%3AEngine+filename%3Asread.c).

**Comment by jpffitch** [comment]
I did not know but guessed; sorry if te keyboard mistyped again
