### ISSUE TITLE
examples/par.csd cannot be performed

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#752]
Attempting to run [examples/par.csd](https://github.com/csound/csound/blob/cd4be5f71cb7b18ecb51e338f0b680676662b26f/examples/par.csd) results in

```
--Csound version 6.09 (double samples) Jan 24 2017 
[commit: cd4be5f71cb7b18ecb51e338f0b680676662b26f]
libsndfile-1.0.26
UnifiedCSD:  ../csound/examples/par.csd
STARTING FILE
Creating options
Creating orchestra
Creating score
Elapsed time at end of orchestra compile: real: 0.004s, CPU: 0.002s
sorting score ...
{: invalid repeat count
end of score.		   overall amps:      0.0
	   overall samples out of range:        0
1 errors in performance
Elapsed time at end of performance: real: 0.004s, CPU: 0.002s
```

**Comment by jpffitch** [comment]
The example is wrong as well; look at the maual example/leftbrace.csd

But it does rater depend on who/when the macro is expanded.  At present 
the cout is an explicit number as te {...} construct defines macros.
y

**Comment by nwhetsell** [comment]
[examples/par.csd](https://github.com/csound/csound/blob/2447348fce0479b5849f805e6a342f2565ba08b2/examples/par.csd) as updated in commit 2447348fce0479b5849f805e6a342f2565ba08b2 compiles and runs, but it probably shouldn’t. According to the [manual](http://csound.github.io/docs/manual/leftbrace.html), names of count macros in score `{` statements are not prefixed by `$`. Running examples/par.csd with the `--verbose` flag eventually shows

```
External LOOP=3 Level:1
/Users/victor/src/csound6/…/Engine/csound_prs.lex(688): repeat  zero 0x7fc76484da60
```

If I change the count macro from `$FOO` to `COUNT`, I get

```
External LOOP=3 Level:1
/Users/victor/src/csound6/…/Engine/csound_prs.lex(688): repeat COUNT zero 0x7fcdedd69f40
```

It seems that the name of the count macro in examples/par.csd is an empty string, probably because the `isNameChar` test [here](https://github.com/csound/csound/blob/2447348fce0479b5849f805e6a342f2565ba08b2/Engine/csound_prs.lex#L689) fails at the `$` character.

**Comment by vlazzarini** [comment]
Why is my directory structure quoted in these strings?

**Comment by nwhetsell** [comment]
Because that’s what Csound v6.08 (commit a1159a1e12a1095c4607f7162c44b196f5143959), installed from [csound6.08-OSX-universal.dmg](https://github.com/csound/csound/releases/download/6.08.0/csound6.08-OSX-universal.dmg), outputs in Terminal.

**Comment by vlazzarini** [comment]
That explains it, the strings are compiled into the code. Maybe it would be better to use  just the file name, not the full
path.

**Comment by jpffitch** [comment]
That tracing should be removed.  Agree that the new par.csd should check, but it is better than the old very broken version.

⁣Sent from TypeApp ​

**Comment by nwhetsell** [comment]
> That tracing should be removed.

I’m not sure why. Showing the state of score loops when the `--verbose` flag is used helped identify why examples/par.csd currently compiles.

**Comment by jpffitch** [comment]
It gives file names (__FILE__) whic only refer to the buid
