### ISSUE TITLE
Confusion with sr and ksmps when setting sr via command line

### ISSUE THREAD

**Issue by gesellkammer** [csound/csound#754]
Jack is running at 48000 Hz

    $ csound -+rtaudio=jack -odac --sample-rate=48000 sr-test.csd

sr-test.csd contains: 

~~~
<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

ksmps = 128
nchnls = 2
0dbfs = 1.0

instr 1
  ksr = sr
  printk2 ksr
  turnoff
endin

</CsInstruments>
<CsScore>
i 1 0 1

</CsScore>
</CsoundSynthesizer>
~~~

Csound sets the sr correctly to 48000 but gets confused about ksmps and then fails with this error:

> sr = 48000, kr = 344.5312, ksmps = 139.3197
> error: invalid ksmps value

This is on linux with csound compiled from latest git (br=develop)

**Comment by vlazzarini** [comment]
could you try removing the ksmps=128 to see if it makes any change? Just trying to check something about the order of calculations.

**Comment by gesellkammer** [comment]
This is the error without ksmps:

sr = 48000, kr = 4410, ksmps = 10.88435
error: invalid ksmps value

**Comment by vlazzarini** [comment]
ok, I see what is happening. If you don't supply overrides, Csound will use the defaults, and kr precedes ksmps, so it can make a non-integral ksmps value. 
I suppose we could change the precedence, but I'd like to hear opinions on this.

**Comment by vlazzarini** [comment]
btw, you can fix this by providing a ksmps override.

**Comment by vlazzarini** [comment]
oh, but I think there might be bug there as well

**Comment by jpffitch** [comment]
sr divided by kr must  be integer.  Try setting kr to 4800?⁣

**Comment by vlazzarini** [comment]
The bug in the first example is that we get a
kr from 44100/128 and then recalculate the
ksmps by 48000/kr and we're in a mess.

it's sbout the order of operations.

**Comment by vlazzarini** [comment]
I've committed a fix.

**Comment by gesellkammer** [comment]
It's working great, thanks. One last thing regarding the default sr: when using csound in realtime, it would make things easier if the default sr would be the system sr. If there is a need in the given csd to be running at a specific sr, then this would be set as we already do with sr=xxx (and for non-realtime the behaviour would stay untouched). But it would be helpful to have a way of specifying "run in realtime with xxx backend and at the sr used by that backend".

**Comment by vlazzarini** [comment]
ok; you know the drill, please open a new issue with a feature request describing it in as much detail as possible.
