### ISSUE TITLE
CS_UDO_DIR not working

### ISSUE THREAD

**Issue by gesellkammer** [csound/csound#757]
This is an experimental setting, but it is not working as advertised. Looking at the code, this seems to be the problem:

Engine/new_orc_parser.c, line 116
~~~
if (strlen(buff)>768) {
	corfile_preputs(buff, xx);
        buff[0] ='\0';
}
~~~

If I take the if away all files in the CS_UDO_DIR are translated as `#includes`, with the if file, for me it's only the last one.

I can do a PR, but I don't know enough about the context.

**Comment by jpffitch** [comment]
Example of what fails please.  I do not have enough information to reproduce

**Comment by gesellkammer** [comment]
1. define env var CS_UDO_DIR to point to a dir containing more than one file, each with the .udo extension
2. in a csd, use the udos defined in the included files. 
3. only the last of the files is included

Line 110 in Engine/new_org_parser.c seems to be the offending one, where the strcpy is overwriting the already included files

~~~c
if (n>4 && (strcmp(&fname[n-4], ".udo")==0)) {
    strcpy(buff, "#include \"");                // <----------------------- 
    strlcat(buff, dir, 1024);
    strlcat(buff, "/", 1024);
    strlcat(buff, fname, 1024);
    strlcat(buff, "\"\n", 1024);
    if (strlen(buff)>768) {
        corfile_preputs(buff, xx);
        buff[0] ='\0';
    }
}
~~~

**Comment by jpffitch** [comment]
Thanks; fixed in git now
