### ISSUE TITLE
Add privacy policy to Csound for Android app and Play Store

### ISSUE THREAD

**Issue by gogins** [csound/csound#759]
See https://mail.google.com/mail/u/0/#inbox/15a15b3785bf319f

**Comment by jpffitch** [comment]
Please amplify.

**Comment by gogins** [comment]
This is about the Csound for Android app for Android that I put on the
Google Play Store. The app's permissions are:

Device & app history
--read sensitive log data
Photos/Media/Files
--read the contents of your USB storage
--modify or delete the contents of your USB storage
Storage
--read the contents of your USB storage
--modify or delete the contents of your USB storage
Microphone
--record audio
Other
--full license to interact across users
--full network access
--change your audio settings

What we need to to is put up a statement that we don't collect private data
at all, which is true. This has to be on the Play Store page and also in
the app itself.

I will take care of this. I am reviewing the existing privacy policies of
related apps to see how to write it.

Here's the email from the Play Store:

Hello Google Play Developer,

Our records show that your app, Csound for Android, with package name
com.csounds.Csound6, currently violates our User Data
<https://play.google.com/about/privacy-security/personal-sensitive/> policy
regarding Personal and Sensitive Information.

*Policy issue*: Google Play requires developers to provide a valid privacy
policy when the app requests or handles sensitive user or device
information. Your app requests sensitive permissions (e.g. camera,
microphone, accounts, contacts, or phone) or user data, but does not
include a valid privacy policy.

*Action required:* Include a link to a valid privacy policy on your app's
Store Listing page and within your app. You can find more information in
our help center
<https://support.google.com/googleplay/android-developer/answer/113469#privacy>
.

Alternatively, you may opt-out of this requirement by removing any requests
for sensitive permissions or user data.

If you have additional apps in your catalog, please make sure they are
compliant with our Prominent Disclosure
<https://play.google.com/about/privacy-security/personal-sensitive/>
 requirements.

Please resolve this issue by *March 15, 2017*, or administrative action
will be taken to limit the visibility of your app, up to and including
removal from the Play Store. Thanks for helping us provide a clear and
transparent experience for Google Play users.

Regards,

The Google Play Team


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by gogins** [comment]
Resources:

https://s2imon.github.io/pp4pp/

**Comment by gogins** [comment]
Added policy .html file to csound.github.io, and linked to this from the Play Store. I only need to add the same link to the menu in the app.

**Comment by gogins** [comment]
I have added a link to the privacy policy to the Android for Csound app. It appears in the app menu, as recommended. I only need to update the .apk in the Play Store.

**Comment by gogins** [comment]
I have updated the .apk and uploaded it to the Play Store. This includes not only a menu item with a link to the privacy policy, but a bug fix enabling the Lua score generator example to run again.
