### ISSUE TITLE
pop.csdfom manual

### ISSUE THREAD

**Issue by jpffitch** [csound/csound#761]
fails after end of score (tested  on 64bit linux)

**Comment by jpffitch** [comment]
Little moe information; it is wen it tres to free the memory associated with the string variable S01.  The dat field is not correctly allocated -- the header is corrupted and the string data is rubbish.  Suggests push/pop on strings is bust
Oddly is works under valgrind

**Comment by vlazzarini** [comment]
who's the author?

**Comment by jpffitch** [comment]
Istvan

**Comment by jpffitch** [comment]
Patced in git -- rus simpletests -- also moved to plugi
