### ISSUE TITLE
Crashing in csound.node 

### ISSUE THREAD

**Issue by gogins** [csound/csound#763]
When running a Csound HTML file, csound.node on Windows now always crashes. Not tested on other platforms.

**Comment by gogins** [comment]
Theories:

1. Recent changes with sprintf opcodes.
2. Recent changes to parser regular expressions.
3. Recent changes to csound.node itself or to the C++ interface that csound.node uses.
4. Typos introduced into the HTML file (I know this has happened).

Debugging is difficult, I may need to do a binary search through the commits.

RIght now I am doing a complete rebuild. If that doesn't help, I will try debugging again to catch the complete orchestra parse error log. If that doesn't help, I will try paring down the orchestra in the HTML file.

It would be useful to print lines of context for Bison parse errors.

**Comment by gogins** [comment]
Debugging:

1. Pull develop branch. Done.
1. Completely uninstall Csound with removal of all leftovers. Done.
2. Kill all NW or Chrome related processes. Done.
1. Rebuild Csound (1st run). Done.
2. Rebuild MSVC 2013 import library. Done.
3. Rebuild csound.node. Done.
1. Rebuild Csound (2nd run). Done.
2. Pull CsoundQt. Done.
3. Completely rebuild CsoundQt.
4. Test CsoundQt.
5. Rebuild Csound (3rd run to get new installer).
6. Install Csound.
7. Retest HTML file.

**Comment by gogins** [comment]
Some progress, created a csd from my HTML orc and it crashes too, so I may have reproduced the problem in a form that I can debug.

**Comment by gogins** [comment]
That fixed it.

**Comment by jpffitch** [comment]
I guess we ned a different fix to the verity defect?
