### ISSUE TITLE
GEN18 off-by-one error

### ISSUE THREAD

**Issue by Oeyvind** [csound/csound#767]
It seems that GEN 18 is off by one in the writing of source tables to the destination table.
Writing seems to start at index 1, and end one index later than what is set in the finisha (finishb ...) argument.

The following csd shows the behaviour.

I would expect these values
i0 = 1.0 ; first value of the source table
i1 = 0.99... ; second value of the source table
i9 = 0.0; last value of the source table
i10 = 1.0; first value of the source table
i11 = 0.99...; second value of source table

But I get these values
i0 = 0.0
i1 = 1.0
i9 = 0.002
i10 = 0.001
i11 = 1.0
...

<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

giRampDown ftgen 0, 0, 1024, 7, 1, 1024, 0
giPanLaws ftgen 0, 0, 4096, 18, giRampDown, 1, 0, 1023, \
                                giRampDown, 1, 1024, 2047, \
                                giRampDown, 1, 2048, 3071, \
                                giRampDown, 1, 3072, 4095

instr 1
print giPanLaws
i0 table 0, giPanLaws
i1 table 1, giPanLaws
print i0, i1

i9 table 1023, giPanLaws
i10 table 1024, giPanLaws
i11 table 1025, giPanLaws
print i9, i10, i11
i19 table 2047, giPanLaws
i20 table 2048, giPanLaws
i21 table 2049, giPanLaws
print i19, i20, i21
		endin

</CsInstruments>
<CsScore>
i1  0 1
</CsScore>
</CsoundSynthesizer>

**Comment by jpffitch** [comment]
Stupd coding error (not mine), now fixed
==John
