### ISSUE TITLE
p-field accuracy

### ISSUE THREAD

**Issue by inkeye** [csound/csound#768]
First of all thank you very much for hosting the csound repository. :) Keep up the good work.

When checking for equality of 2 pfields which have 7 or more decimal places, csound does not recognize them as equal, if they are equal in fact.

orc:
`
sr = 44100
ksmps = 1
nchnls = 2
0dbfs = 1

instr floattest
  if p3 == p4 then
    print 1
  else
    print 0
  endif
endin
`

sco:
`
i "floattest" 0 0.1111111 0.1111111 
`

Thought about floating point precision but cannot figure out the reasons for this strange behaviour.

Thank you very much. Any help appreciated.

**Comment by jpffitch** [comment]
Not lookd yet bt p2 and p3 are modified by tempo.  That could introdue 
some errors.  btwsingles or doubles ad wich platform/OS?
==John

**Comment by jpffitch** [comment]
ps running under gdb the comparison between a anb b is
(gdb) print *p->a
$2 = 0.111111
(gdb) print *p->b
$3 = 0.1111111
(gdb)

So thhey are not equal,, p3 is being tuncated; certainly tat s wat the 
sorted and warped score ays

i "floattest" 0.000000 0.000000 0.111111 0.111111 0.1111111

p2 and p3 are printed twice, pefore and after warpig, so my original 
suggestion is wrong

**Comment by jpffitch** [comment]
Function stof is not reading correctly; string to MYFLT
****stof 0  -> 0
****stof 0.1111111  -> 0.111111

Only used ot p1, p2 and p3. Nowto find out why!

**Comment by jpffitch** [comment]
Found it; p2 and p3 were truncated to 6 decimal places.  I have increased this to 12 and am considering a better solution.
