### ISSUE TITLE
Bug in libpy.so

### ISSUE THREAD

**Issue by hlolli** [csound/csound#769]
This is a bug that I mentioned on the mailing list when I was trying to play Anton's piece and I believe Steven mentioned encountering the same problem. I've compiled the latest develop branch and it persists, here's the complaint (btw this file exists and seems healty on my machine).
```
WARNING: could not open library '/usr/local/lib/csound/plugins-6.0/libpy.so' (/usr/local/lib/csound/plugins-6.0/libpy.so: undefined symbol: PyFile_AsFile)
```

And here's the code I was running (from the new Csound book)
```csound
<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 1
0dbfs = 1.0

instr 1
  itie tival
  tigoto dur 
  env:
    ist = p2
    idur = abs(p3)
    k1 linen 1,0.2,idur,2 
  dur:
    if itie == 0 igoto osc
    iend = idur + ist - p2
    p3 = iend > 0 ? iend : 0
  osc:
    a1 vco2 p4*k1,cpspch(p5),0,itie
    a2 moogladder a1,1000+k1*3000,.7,itie
    out a1
endin
schedule(1,0,-6,0dbfs/2,8.00)
schedule(1,2,-1,0dbfs/2,8.07)
schedule(1,4,1,0dbfs/2,8.05)

</CsInstruments>
<CsScore>
</CsScore>
</CsoundSynthesizer>
```
I run with `csound -odac tiedvals.csd`
I'm on Fedora25 if that info helps.

**Comment by hlolli** [comment]
I don't know what I did, but not csound plays sound but this undefined symbol is still there. So this is not very important bug but I guess this is needs to be fixed anyway.

**Comment by vlazzarini** [comment]
Sounds like a problem with the Python, not Csound. Are you sure you are linking to Python 2.7? This
is a symbol in the Python API, so if it's not there it's a linking problem, not a bug in Csound.

Python 3 API does not appear to have that function

http://stackoverflow.com/questions/16130268/python-3-replacement-for-pyfile-asfile

and that error does not happen on OSX, btw, where libpy is safely linked to Python 2.7.

**Comment by hlolli** [comment]
Probably I need to do that on compilation time, from a quick check I see that
```
$ python --version
Python 2.7.13
```

**Comment by hlolli** [comment]
Ok csound seems to look for python 3+ on compilation, look into how I can prevent that.
```
/usr/include/python3.5m/pythonrun.h:160:23: note: in definition of macro ‘PyRun_File’
     PyRun_FileExFlags(fp, p, s, g, l, 0, NULL)
                       ^~
/usr/include/python3.5m/pythonrun.h:104:24: note: expected ‘FILE * {aka struct _IO_FILE *}’ but argument is of type ‘int’
 PyAPI_FUNC(PyObject *) PyRun_FileExFlags(
```

**Comment by vlazzarini** [comment]
It is probably cmake that is doing that.
