### ISSUE TITLE
Per-voice ramping

### ISSUE THREAD

**Issue by Excentertex** [csound/csound#773]
It would be really nice to have a feature in the standard score to "group by" voice.

Background: many music paradigms (i.e. polyphonic classical music) is organized in separate musical lines  playing concurrently. However, the ramping symbols (`<`, `(`) take effect _after_ score sorting.
So if we would have something like:

`
p 1
i 111    	0      	1		2000
i 111    	+      	1		<
i 111    	+      	1		<
i 111    	+      	1		2500

p 2
i 112    	0      	1		1000
i 112    	+      	1		.
i 112    	+      	1		.
i 112    	+      	1		.
`

, then voice 1 (I used 'p' for 'polyphonic' here) would correctly gain amplitude while voice 2's amplitude would stay the same.

**Comment by jpffitch** [comment]
i do not understand this request.  If I input
```
i 111 0 1 2000
i 111 + 1 <
i 111 + 1 <
i 111 + 1 2500
i 112 0 1 1000
i 112 + 1 .
i 112 + 1 .
i 112 + 1 .
```
then it gives values of p4 as
```
instr 111:  p4 = 2000.000
instr 112:  p4 = 1000.000
instr 111:  p4 = 2166.667
instr 112:  p4 = 1000.000
instr 111:  p4 = 2333.333
instr 112:  p4 = 1000.000
instr 111:  p4 = 2500.000
instr 112:  p4 = 1000.000
```
which is what you are requesting.  I see no issue.  Clarifcation please!

**Comment by Excentertex** [comment]
I believe I had an older version at the time. This can be closed.
