### ISSUE TITLE
Csound with rtmidi=jack does not creat jack client for Csound when -Q or -M is not set

### ISSUE THREAD

**Issue by tarmoj** [csound/csound#776]
With command
csound -odac -+rtaudio=jack  -+rtmidi=jack test.csd
no csound6 client is created in Jack MIDI section and it is not possible to connect manually.
If to add -M or -Q option with even nonexisting name like
csound -odac -+rtaudio=jack  -+rtmidi=jack -Qdummy test.csd
csound6 appears among jack clients.

expected behaviour: csound6 midi  client is created always for jack when -+rtmidi=jack is used.

**Comment by vlazzarini** [comment]
actually, no. you need the flags to load the midi functions, it's like that across the other backends.

**Comment by tarmoj** [comment]
Ok
all clear. Please close the issue.
Thanks

2017-04-07 13:42 GMT+03:00 vlazzarini <notifications@github.com>:
