### ISSUE TITLE
When csoundPerform is running in a background thread, SIGINT does not terminate immediately

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#778]
This C program—

```c
#include <csound/csound.h>
#include <assert.h>

uintptr_t perform(void *data)
{
    return csoundPerform((CSOUND *)data);
}

int main(int argc, char *argv[])
{
    CSOUND *Csound = csoundCreate(NULL);
    assert(csoundSetOption(Csound, "--output=dac") == CSOUND_SUCCESS);
    char *orchestra =
        "0dbfs = 1\n"
        "giFunctionTableID ftgen 0, 0, 16384, 10, 1\n"
        "instr A440\n"
        "    outc oscili(0.5 * 0dbfs, 440, giFunctionTableID)\n"
        "endin\n";
    assert(csoundCompileOrc(Csound, orchestra) == CSOUND_SUCCESS);
    assert(csoundReadScore(Csound, "i \"A440\" 0 10\n") == CSOUND_SUCCESS);
    assert(csoundStart(Csound) == CSOUND_SUCCESS);

    void *threadID = csoundCreateThread(perform, (void *)Csound);

    csoundSleep(10 * 1000);

    csoundStop(Csound);
    assert(csoundJoinThread(threadID) == 0);
    csoundDestroy(Csound);

    return 0;
}
```

—loads an orchestra and score to play a 440 Hz sine tone for 10 seconds, performs the sine tone on a thread created with `csoundCreateThread`, and then waits.

Compiling and executing this code on macOS plays the sine tone as expected. While the sine tone is playing, pressing <kbd>Ctrl</kbd>-<kbd>C</kbd> sends a `SIGINT`, stops the sine tone, and causes “Csound tidy up: Interrupt” to appear in the console. However, the program does not terminate. Unexpectedly, it’s necessary to press <kbd>Ctrl</kbd>-<kbd>C</kbd> one or two more times.

**Comment by DaveSeidel** [comment]
I see similar behavior when I run Csound from Python via ctcsound in the app I'm working on now, except that the first Ctrl+C has little apparent effect, and only with the second Ctrl+C does the sound stop and the program terminate.

**Comment by vlazzarini** [comment]
In this case, Csound is running in a separate thread and the SIGKILL might not be handled directly. You need to handle the interrupt yourself to stop the thread. For instance, this will do it (tested here on OSX):

```
#include <csound.h>
#include <assert.h>
#include <atomic>
#include <csignal>


// handle ctrl-c
static std::atomic_bool running(true);
void signal_handler(int signal) {
  running = false;
}

uintptr_t perform(void *data)
{
    csoundPerform((CSOUND *)data);
    running = false;
    return 0;
}


int main(int argc, char *argv[])
{
    CSOUND *Csound = csoundCreate(NULL);
    assert(csoundSetOption(Csound, "--output=dac") == CSOUND_SUCCESS);
    const char *orchestra =
        "0dbfs = 1\n"
        "giFunctionTableID ftgen 0, 0, 16384, 10, 1\n"
        "instr A440\n"
        "    outc oscili(0.5 * 0dbfs, 440, giFunctionTableID)\n"
        "endin\n";
    assert(csoundCompileOrc(Csound, orchestra) == CSOUND_SUCCESS);
    assert(csoundReadScore(Csound, "i \"A440\" 0 100000\n") == CSOUND_SUCCESS);
    assert(csoundStart(Csound) == CSOUND_SUCCESS);
    running = true;
    std::signal(SIGINT, signal_handler);
    
    void *threadID = csoundCreateThread(perform, (void *)Csound);

    while(running) {
      csoundSleep(1);
    }
    
    csoundStop(Csound);
    assert(csoundJoinThread(threadID) == 0);
    csoundDestroy(Csound);
    return 0;
}
```

There are other similar ways to do this, but the principle is the same. When Csound is running in the main thread it handles signals and deals with them, doing the necessary jumps. Because it is running inside csoundPeformanceThread(), you need to take care of stopping the thread yourself.

**Comment by nwhetsell** [comment]
I’m not sure I fully understand this.

The default behavior, and in general the expected behavior, when a process receives a `SIGINT` on macOS is to terminate. However many threads are running in a process, if the process receives a `SIGINT` and terminates, the threads stop executing, because their process has been terminated.

As you point out, this can be changed by defining a signal handler. The Csound API currently defines a signal handler [here](https://github.com/csound/csound/blob/e23e44eeb705a78e1b2374938b724bf0a6bfccf6/Top/csound.c#L1093). This signal handler doesn’t appear to terminate the process on `SIGINT` (or `SIGTERM`) signals, instead setting an `exitNow_` flag to a non-zero value (I assume so that [this if-branch](https://github.com/csound/csound/blob/e23e44eeb705a78e1b2374938b724bf0a6bfccf6/Top/csound.c#L3011) is taken eventually).

So, it seems to me that to get the expected behavior, the solution is to not use the Csound API signal handler. I believe that this can be done by passing `CSOUNDINIT_NO_SIGNAL_HANDLER` to `csoundInitialize` before any calls to `csoundCreate`:

```c
#include <csound/csound.h>
#include <assert.h>

uintptr_t perform(void *data)
{
    return csoundPerform((CSOUND *)data);
}

int main(int argc, char *argv[])
{
    // When using CSOUNDINIT_NO_ATEXIT or CSOUNDINIT_NO_SIGNAL_HANDLER,
    // csoundInitialize must be called before csoundCreate.
    assert(csoundInitialize(CSOUNDINIT_NO_SIGNAL_HANDLER) == 0);

    CSOUND *Csound = csoundCreate(NULL);
    assert(csoundSetOption(Csound, "--output=dac") == CSOUND_SUCCESS);
    char *orchestra =
        "0dbfs = 1\n"
        "giFunctionTableID ftgen 0, 0, 16384, 10, 1\n"
        "instr A440\n"
        "    outc oscili(0.5 * 0dbfs, 440, giFunctionTableID)\n"
        "endin\n";
    assert(csoundCompileOrc(Csound, orchestra) == CSOUND_SUCCESS);
    assert(csoundReadScore(Csound, "i \"A440\" 0 10\n") == CSOUND_SUCCESS);
    assert(csoundStart(Csound) == CSOUND_SUCCESS);

    void *threadID = csoundCreateThread(perform, (void *)Csound);

    csoundSleep(10 * 1000);

    csoundStop(Csound);
    assert(csoundJoinThread(threadID) == 0);
    csoundDestroy(Csound);

    return 0;
}
```

> Because it is running inside csoundPeformanceThread(), you need to take care of stopping the thread yourself.

I believe that should be <code>CsoundPe<b>r</b>formanceThread</code>. However, I am not using that [class](https://github.com/csound/csound/blob/e23e44eeb705a78e1b2374938b724bf0a6bfccf6/interfaces/csPerfThread.hpp#L119).

Am I missing something?

**Comment by vlazzarini** [comment]
If you switch off the Csound signal handler you will need to handle it yourself. If you don't the default handler will just jump out of the program. However, it is better to allow Csound to exit cleanly, by killing the thread and destroying Csound. This is what happens in my example. In fact, I don't even need to switch off Csound's SIGINT handling, because I am supplying one that will replace it. So the sequence is this: Csound is initialised, sets up a set of handlers, we replace the SIGINT one by a custom handler that switches off the sleeping loop and the proceeds to stop the csound performance, join the thread and cleanup. If the handler is not added, and the Csound one is switched off, the program exits at the sleep loop with no clean up.

I misread your code and I see you are using pthreads directly, but Dave's Python code probably uses it. It actually doesn't matter, because the underlying principle is the same.

**Comment by kunstmusik** [comment]
I've been half-following this, but I thought I'd mention I often have to
use ctrl-c twice using the normal csound command-line executable.

**Comment by nwhetsell** [comment]
> it is better to allow Csound to exit cleanly

What are the drawbacks of not immediately exiting in response to a `SIGINT`?

**Comment by vlazzarini** [comment]
> What are the drawbacks of not immediately exiting in response to a SIGINT?

You probably mean "immediately exiting" rather than "not".
If you have open files and devices, there might be issues with things that are left unclosed when
you jump out of the program directly without destroying or resetting or cleaning up the Csound object.

**Comment by vlazzarini** [comment]
@kunstmusik if there is more than one thread anywhere in Csound it might need a couple of ctl-c. Sometimes the second thread is run by the audio IO.

**Comment by nwhetsell** [comment]
> You probably mean "immediately exiting" rather than "not”.

Quite right.

> If you have open files and devices, there might be issues with things that are left unclosed

Sorry to ask so many questions, but can you give an example of an issue? My understanding is that the operating system closes files and other output streams on a `SIGINT`, although the operating system probably won’t flush them.

**Comment by vlazzarini** [comment]
You could be right that the OS will close files, but if there is any clean up that is needed in a Csound instrument (can't think of an example off the top of my head), it won't happen. I am not sure that all MIDI/Audio backends are closed properly/cleanly in automatic way by SIGINT in all platforms. For instance, it might be the case that in certain implementations of ALSA the device does not get closed and then we cannot connect again to it without some sort of hard reset.

One thing I have noticed as well as that the audio IO buffer might not be cleared up and when you start it again, it's not clean and we get a click on start up.

**Comment by nwhetsell** [comment]
Feel free to close this, but perhaps the possibility of needing to press <kbd>Ctrl</kbd>-<kbd>C</kbd> multiple times to terminate Csound is a sign that another approach is needed to address issues with certain implementations of ALSA, clearing audio buffers, etc.

**Comment by vlazzarini** [comment]
No, it is not. In this case, it is a sign that a multi-threading program using the API is not handling ctrl-c properly. The command-line frontend in most cases closes on ctrl-c if there is no extra threads in the background (that is my experience with OSX, for instance); if there is a blocking operation somewhere inside Csound preventing it, then this specific case needs to be looked at.

**Comment by nwhetsell** [comment]
> In this case, it is a sign that a multi-threading program using the API is not handling ctrl-c properly.

Perhaps, then, it would be worth mentioning in the [documentation of Csound’s threading API](https://csound.github.io/docs/api/group__THREADING.html) the need to write a custom signal handler, and not use the Csound API default.

**Comment by vlazzarini** [comment]
yes, but this is just a thin wrapper over pthreads/etc. Any programmer using threads of any kind should be careful with signals etc.

**Comment by nwhetsell** [comment]
I think a note in the documentation like, “You should not use the default Csound API signal handler if you use Csound on a background thread” would in general be more valuable than one like “Any programmer using threads of any kind should be careful with signals.”

**Comment by vlazzarini** [comment]
I did not mean this to go in the documentation, just as a remark that if someone is hoping to work at this level, there is quite a bit of know-how required, whether they are using the Csound API or not.
