### ISSUE TITLE
array operations

### ISSUE THREAD

**Issue by Oeyvind** [csound/csound#780]
More array operations would be very handy for massaging and analysing chunks of data.

1) Sort the values in an array. "sortarray"
2) Transform an array by using array values a function table lookup  "funcarray"
- e.g. if we have an array with values monotonically rising from 0.0 to 1.0, and apply this operation using a sine wave table, then we get an array with a sine wave as output. 
- this kind of shaping resembless waveshaping, and could be used for simple limiting or nonlinear shaping.

**Comment by vlazzarini** [comment]
Ok. I will have a look.

**Comment by vlazzarini** [comment]
Note that there is already a huge number of functions that can be applied to arrays: all basic trigonometric, modulus, and other basic one-arg functions are there. There are a whole list of two-argument functions that take two arrays also. This is all documented in the latest git manual and will be released in 6.09.

I'll implement the sorting operations. 

Mapping in general (your number 2) using csound-language code has all the caveats explained by @kunstmusik and I guess that needs a wider discussion.

**Comment by vlazzarini** [comment]
I have added two opcodes, sorta and sortd for sorting arrays in asceding and descending order, respectively.

**Comment by Oeyvind** [comment]
That was fast

2017-04-20 12:57 GMT-07:00 vlazzarini <notifications@github.com>:

**Comment by vlazzarini** [comment]
C++, it's all templated. Very little extra work.

**Comment by rorywalsh** [comment]
So long as they work better than sorta good everyone will be happy 😂

On 20 Apr 2017 22:07, "vlazzarini" <notifications@github.com> wrote:

C++, it's all templated. Very little extra work.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/csound/csound/issues/780#issuecomment-295885966>, or mute
the thread

**Comment by vlazzarini** [comment]
They sorta work. Sortd.

**Comment by jpffitch** [comment]
Do they sort strings in arrays?

**Comment by Oeyvind** [comment]
well sortd

2017-04-20 13:35 GMT-07:00 vlazzarini <notifications@github.com>:

**Comment by vlazzarini** [comment]
numeric arrays of scalars only, k- and i-

**Comment by Oeyvind** [comment]
Would it also be possible to sort bins of a pvs frame according to
amplitude?
That is, of course, keeping the amp-frequency pairs together.

2017-04-20 15:05 GMT-07:00 vlazzarini <notifications@github.com>:

**Comment by vlazzarini** [comment]
Hi Oeyvind. Not sure I understand the sorting you want. PVS bins cannot be moved around, because each one is linked to a frequency point. You can place them in array and sort them, but you won't be able to resynthesise them with an IFFT (only additive synthesis).

**Comment by jpffitch** [comment]
Can this be closed?

**Comment by vlazzarini** [comment]
yes.
