### ISSUE TITLE
Remove Boost dependency from Max Csound~

### ISSUE THREAD

**Issue by gogins** [csound/csound#785]

**Comment by stekyne** [comment]
Is this done now that we've removed Boost from the main library build?

**Comment by kunstmusik** [comment]
No; I did a grep for boost and it's all over the source. The cmake file
does not search for it in in frontends/max_csound_tilde. At this point no
one is known to be maintaining csound~ for Max and we should make a
decision on what to do with it (split it out into its own repository,
etc.).

**Comment by vlazzarini** [comment]
I’d be happy for it to go to its own repo. And for boost to go away too.

Victor Lazzarini
Dean of Arts, Celtic Studies, and Philosophy
Maynooth University
Ireland

On 27 Nov 2017, at 17:14, Steven Yi <notifications@github.com<mailto:notifications@github.com>> wrote:

No; I did a grep for boost and it's all over the source. The cmake file
does not search for it in in frontends/max_csound_tilde. At this point no
one is known to be maintaining csound~ for Max and we should make a
decision on what to do with it (split it out into its own repository,
etc.).

**Comment by gogins** [comment]
There is not any boost in the Csound build, that includes all components
included in the Windows installer.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com
