### ISSUE TITLE
Update Visual Studio to 2015 for CsoundQt and csound.node

### ISSUE THREAD

**Issue by gogins** [csound/csound#786]
There are problems installing Visual Studio 2015 Community Edition on Windows 8.1. These are the steps that I took to overcome these problems.

1. I uninstalled all instances of Visual Studio.
2. In the Visual Studio 2015 packages directory, I deleted all VC redistributable files.
3. I removed all temp and Windows temp files.
4. I rebooted my computer.
5. I ran the Visual Studio 2015 installer with the option for C++ compiler tools enabled.
6. I ran the Windows SDK 8.1 installer.
7. I ran the Windows SDK 10 installer.

**Comment by gogins** [comment]
Then there are problems with nw-gyp not working with Visual Studio 2015. These are the steps that I took to get it to work:

1. I updated NW.js to version 0.22.
2. In the npm shell, I updated everything with `xxx`.

I still got his error:

```
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 wa
s not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selectin
g "Retarget solution". [D:\msys64\home\restore\csound\frontends\nwjs\build\csound.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\restore\AppData\Roaming\npm\node_modules\nw-gyp\lib\build.js:294:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

**Comment by gogins** [comment]
I may have to revert to Visual Studio 2013 for csound.node. What a bite.

**Comment by rorywalsh** [comment]
I guess Visual Studio 2017 is also out of the running?

**Comment by gogins** [comment]
Yes. 2013 is the lowest common denominator and may be what I end up using.

This is down to what I, a big fan of C++, acknowledge as its major flaw:
lack of a standard ABI.

Best,
Mike

**Comment by gogins** [comment]
I am closing this issue as not currently being practical. Visual Studio 2013 is still being used to build NW.js and thus is the lowest (actually, greatest) common denominator of Microsoft development systems for csound.node and CsoundQt. It is unfortunate but perhaps there is no solution that Visual Studio 2017 is being used for the MSVS build of Csound.

Visual Studio 2013 and Windows SDK 8.1 will be used going forward for csound.node and CsoundQt on Windows.

**Comment by gogins** [comment]
I may also have to do something like this:

If above information couldn't solve your problem, I am proposing below steps from my VS2013 experiences:

Select Project Properties>Configuration>VC++ Directories>Include Directories and add that: c:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Include
Select Project Properties>Configuration>VC++ Directories>Library Directories and add that: c:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Lib
After that configuration I had problem about rc.exe link error. For this problem one more thing is needed:

copy RC.exe and RcDll.dll files from C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin and past them to C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin After all those configuration steps, you can build a simple "Hello World!" example and run if you are lucky.

**Comment by gogins** [comment]
Horrible hack that may work:

In C:\Program_Files_x86\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets, rename the v140 dir to v140.save and copy the v140_xp dir to v140.

**Comment by stekyne** [comment]
VS2015 is binary compatible with 2017. I guess if you could get it working somehow with 2015, it would work with the 2017 build. Still trying to read through this and see the problem though!

**Comment by gogins** [comment]
The problem is that Microsoft's configuration files and code that lines up the installed versions of Visual Studio with the appropriate installed versions of the Windows SDK are buggy. It works if one installs SDKs along with Visual Studios that lack it, and always install earlier versions before later versons. Otherwise it does not work. There are many reports of these problems along with not always successful workarounds on line.

**Comment by stekyne** [comment]
With VS2017 you have the option of installing multiple Windows SDK. I have 10.something and 8.1 installed right now. Does that help at all?

**Comment by gogins** [comment]
I do not know. I am concerned with two targets: CsoundQt and csound.node. Both projects assume that the Widows SDK and Visual Studio have been installed. However, csound.node runs in NW.js which is built using Visual Studio 2013. I think I will have to do the experiment to see if configuring nw-gyp to use msvs2015 will run in NW.js. As for CsoundQt, I think we are currently stuck with Visual Studio 2013 or Visual Studio 2015 because that is what the Qt SDK is built for. Right now, QTCreator with Qt for Visual Studio 2015 can't find Windows.h. Other people have similar problems.

**Comment by stekyne** [comment]
I can try and help out and see if we can build with the later versions. Would be a shame if it wasn't possible.

**Comment by stekyne** [comment]
Just wondering, for CsoundQT, is the RTMidi and Python support both required for the installer build?

**Comment by gogins** [comment]
I do the RTMidi but not the PythonQt.

Best,
Mike

**Comment by gogins** [comment]
There is yet another wrinkle here. Qt SDK 5.8.0 for Visual Studio 2013 no longer includes the WebEngine components because Chrome no longer is built with Visual Studio 2013.

I am going back to the idea of building everything with Visual Studio 2015.

**Comment by gogins** [comment]
There now is a problem with rc.exe not being found by qmake. I added the path to the build environment.

**Comment by gogins** [comment]
After ridiculous gymnastics of googling, analysis, and trial and error I have finally built and run both CsoundQt and csound.node using Visual Studio 2015. Tested with NW.js 0.22.0 and Qt SDK 5.8.0 for MSVS 2015 x64. Here is a summary of the steps that I think are required:

1. Uninstall all instances of Visual Studio.
2. In the Visual Studio 2015 packages directory, delete all VC redistributable files.
3. Remove all temp and Windows temp files.
4. Reboot the computer.
5. Run the Visual Studio 2015 installer with the option for C++ compiler tools enabled.
6. Run the Windows SDK 8.1 installer.
7. Run the Windows SDK 10 installer.
8. Run the Qt SDK 5.8.0 for MSVS 2015 x64 installer.
6. From the Visual Studio 2015 IDE Tools menu, open the Visual Studio Command Prompt.
7. Change to the `x86_amd64` directory.
8. Run `vcvarsx86_amd64.bat`.
9. Change to the `csound/mingw64' directory.
10. Run the `make_import_library.cmd` script to create an MSVC import library for Csound.
9. Install NW.js 0.22.0.
2. In the npm shell, change to the `csound\frontends\nwjs` directory.
3. Run `npm -g install npm@latest`.
3. Run `npm -g install nw-gyp@latest`.
4. Reset the target with `npm config set msvs_version 2015 --global`.
5. Configure the project with `npm configure --version=0.22.0`.
5. Build sound.node with `build_csound_node_windows_x64.cmd`.
6. If that didn't work, In `C:\Program_Files_x86\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets`, rename the `v140` directory to `v140.save` and copy the `v140_xp` directory to `v140`. Then try again.
5. Run QtCreator.
6. Load the qcs.pro project.
7. Configure the "Kit" for Qt SDK 5.8.0 for Visual Studio 2015 x64.
8. Configure the "Kit" for Visual Studio 2015. Ensure that the paths for the C compiler, the C++ compiler, and the `cdb` debuffer are really for Visual Studio 2015 amd64 and consistent with each other.
9. In the Projects tab, use the Build environment Details button to add the full path to the directory containing the 'rc.exe' resource compiler for SDK 10 to the `PATH` environment variable.
10. Add `CONFIG += html_webengine` to the project configuration QMake details.
11. Run qmake.
12. Rebuiild the qcs.pro project.

**Comment by gogins** [comment]
I think it would be worth trying the above with Visual Studio 2017.

**Comment by stekyne** [comment]
VS2017 can load a project as VS2015 toolset so I don't think there is much of an issue. You can install a few  different versioned frameworks side by side. I'd be very surprised if it didn't work.

**Comment by gogins** [comment]
VS2017 won't install on my computer even though it claims to be running Windows 8.1 which should do the job.

**Comment by stekyne** [comment]
What kind of error is it? Microsoft have got very trigger happy with pulling support from previous versions so maybe. They want everyone on their Windows 10 spyware platform I guess :)

**Comment by gogins** [comment]
This kind of error:

[image: Inline image 1]

I thought I had Windows 8.1, but it seems I do not, only 8.0.

Best,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com
