### ISSUE TITLE
Generate MP3 Output

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#791]
On the Csound user list, user requested MP3 generation from Csound. Csound depends upon libsndfile to generate output and would require MP3 support in libsndfile for this to happen.  An issue is filed in libsndfile at https://github.com/erikd/libsndfile/issues/258.  Adding this issue to track the overall status of things for Csound.

**Comment by jpffitch** [comment]
Two comments:

1: The opcode mp3out exists in github using the LAME library.

2: There have been significant developments libsndfile that incorporate mpeg input and output to the list of recognised file types.  Still needs a little tidying up but it looks hopeful.

**Comment by vlazzarini** [comment]
does libsndfile depend on an external lib for mp3?

**Comment by jpffitch** [comment]
Actually two libraries; mg123 to read and lame to write.
