### ISSUE TITLE
Make build process more modular

### ISSUE THREAD

**Issue by algorev** [csound/csound#796]
The build process should be made more modular and not force users to compile bindings.
Those should come as a build option.

**Comment by vlazzarini** [comment]
Not quite sure what the request is, cmake is pretty modular. If you set up a custom.cmake with the paths, build variables etc., you can customise the linking as needed. However, if you know exactly what you want, a pull request would be helpful.

**Comment by stekyne** [comment]
I think the only hard requirement is libsndfile. The other dependencies are optional. It might be an idea to create some preset scripts for a minimal build, installer (full) build, etc.

**Comment by algorev** [comment]
How do you set those flags? it would be useful to tell in the build
instructions, then.

**Comment by stekyne** [comment]
Well cmake-gui will show you the options available and you can select/deselect easily then. You can specify them on the command line also. 

If cmake can't detect the dependencies it will usually just remove those features from the build anyway. It shouldn't only really fail for a small number of dependencies (like libsndfile).

**Comment by algorev** [comment]
It failed with python.

**Comment by stekyne** [comment]
If you don't need it then add "-DBUILD_PYTHON_OPCODES=0" to your cmake command line. If you want to get it working then paste the log and I'll try and help.

**Comment by gogins** [comment]
Here's an example of a real-world cmake command line for building Csound:

cmake ../.. -G "MSYS Makefiles" \
-DABLETON_LINK_HOME:PATH="D:\msys64\home\restore\link" \
-DBUILD_ABLETON_LINK_OPCODES:BOOL=No \
-DBUILD_CSOUNDVST=1 \
-DBUILD_PD_CLASS=0 \
-DBUILD_STATIC_LIBRARY=1 \
-DBUILD_TESTS=0 \
-DBUILD_VST4CS_OPCODES=1 \
-DCMAKE_BUILD_TYPE=RelWithDebInfo \
-DCMAKE_VERBOSE_MAKEFILE=1 \
-DMUSICXML_LIBRARY:FILEPATH=/mingw64/bin/libmusicxml2.dll \
-DNEED_PORTTIME=0 \
-DPTHREAD_LIBRARY:FILEPATH=/mingw64/x86_64-w64-mingw32/lib/libpthread.a \
-DTCL_VERSION=8.5 \
-DUSE_CURL=0 \
-DUSE_GETTEXT=0 \
-DUSE_OPEN_MP=0 \
-D_WIN32=1 \
-DPYTHON_INCLUDE_DIRS:PATH="C:/Program Files/Anaconda2/include" \
-DPYTHON_LIBRARIES:FILEPATH="C:/Program Files/Anaconda2/libs/python27.a" \
-DSTK_LIBRARY:FILEPATH=/mingw64/lib/libstk.a \
-DLIBSNDFILE_LIBRARY:FILEPATH="C:\Program
Files\Mega-Nerd\libsndfile\bin\libsndfile-1.dll" \
-DSNDFILE_H_PATH:PATH="C:\Program Files\Mega-Nerd\libsndfile\include" \
-DBUILD_WEBSOCKET_OPCODE=0 \
-DMS_WIN64=1

In my experience doing this with the command line works but using a
custom-cmake file does not work. Don't know why.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by stekyne** [comment]
Setting the properties does work from the custom cmake files, it's working now for the MSVC build. However, you need to use absolute paths or else it get's messed up if relative paths are used. So if you're setting paths, it's probably best to do it on the command line.

**Comment by stekyne** [comment]
Closing as there doesn't seem to be any tangible request after discussing it.
