### ISSUE TITLE
Multithread error in 6.09 on Raspberry Pi

### ISSUE THREAD

**Issue by berntisak** [csound/csound#802]
Trying to run any file with the -j flag produces an error and seg fault. Compiled latest csound from master branch on Raspberry Pi running Wheezy. This worked fine on 6.08 earlier today.

Here is the error when I tried running with -j 2:

> Create barrier 2 => 0x1920428 (0)
> Create barrier 2 => 0x18efa98 (0)
> Multithread performance: insno:  -1  thread -1 of 2 starting.
> Bad ThreadId
> csound: malloc.c:4100: __libc_calloc: Assertion `!mem || ((((mchunkptr)((char*)(mem) - 2*(sizeof(size_t)))))->size & 0x2) || av == (((((mchunkptr)((char*)(mem) - 2*(sizeof(size_t)))))->size & 0x4) ? ((heap_info *)((unsigned long)(((mchunkptr)((char*)(mem) - 2*(sizeof(size_t))))) & ~((2 * (512 * 1024))-1)))->ar_ptr : &main_arena)' failed.
> Segmentation fault

Without -j 2 it runs fine

**Comment by vlazzarini** [comment]
it's already been addressed. There will be a bugfix release soon. Try building from develop.
