### ISSUE TITLE
Seg fault with Macro arguments

### ISSUE THREAD

**Issue by boonier** [csound/csound#806]
Hi

Just installed latest CSQT 0.9.4 and CS 6.09 on OSX 10.10.5 (from 6.08).

When running the define_args.csd example (from the Manual Manual > Syntax of the Orchestra > Macros > $NAME (2nd example - Example 20), in terminal from CsoundQT, otherwise it
crashes the ide) I'm getting a seg fault:

```
defining argument `OSCMACRO``VOLUME as...#5000#
defining argument `OSCMACRO``FREQ as...#440#
defining argument `OSCMACRO``TABLE
csound command: Segmentation fault
```

I first noticed this when my own macros didn't work, so I tried the example
and sure enough, it failed too. Confirmed here https://github.com/CsoundQt/CsoundQt/issues/235

Many thanks
S

**Comment by vlazzarini** [comment]
it has been fixed and a bugfix release will be prepared to address it.

**Comment by boonier** [comment]
oh great, thanks
