### ISSUE TITLE
allow i- and S-arrays for getrow/setrow

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#808]
as far as i see, the array methods getrow and setrow are currently only available for k-arrays.
it would be nice to have them also for i-arrays, and if possible for S-arrays, too.
thanks -
  joachim

**Comment by kunstmusik** [comment]
@jpffitch Is this something that you imagine could/should be done for 7.0.0?

**Comment by jpffitch** [comment]
setrow and getrow are now working for strings.

Not attacked set/get cols yet but will add it to the worklist
ut wil d it...

**Comment by jpffitch** [comment]
setcol/getcol fo string arrays  now works
