### ISSUE TITLE
Cmake regression on rtpa

### ISSUE THREAD

**Issue by hlolli** [csound/csound#810]
I build the develop branch on weekly basis, so I'm quick to catch regressions
```
[ 75%] Building CXX object InOut/CMakeFiles/rtpa.dir/rtpa.c.o
/home/hlolli/csound/csound/InOut/rtpa.c: In function ‘int csoundModuleInit(CSOUND*)’:
/home/hlolli/csound/csound/InOut/rtpa.c:842:53: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
     csound->module_list_add(csound, "pa_bl", "audio");
                                                     ^
/home/hlolli/csound/csound/InOut/rtpa.c:842:53: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
/home/hlolli/csound/csound/InOut/rtpa.c:843:53: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
     csound->module_list_add(csound, "pa_cb", "audio");
                                                     ^
/home/hlolli/csound/csound/InOut/rtpa.c:843:53: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
/home/hlolli/csound/csound/InOut/rtpa.c:878:47: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
     csound->module_list_add(csound, s, "audio");
                                               ^
[ 75%] Linking CXX shared module ../librtpa.so
/usr/bin/ld: cannot find -lwinmm
/usr/bin/ld: cannot find -ldsound
/usr/bin/ld: cannot find -lsetupapi
collect2: error: ld returned 1 exit status
make[2]: *** [InOut/CMakeFiles/rtpa.dir/build.make:96: librtpa.so] Error 1
```

```
git blame InOut/CMakeLists.txt -L 151,151
359b20a17c (Michael Gogins 2017-06-12 11:41:42 -0400 151)  target_link_libraries(rtpa winmm dsound setupapi ${PORTAUDIO_LIBRARY} ${CSOUND_WINDOWS_LIBRARIES})
```
@gogins 
I'm running on Fedora25
and I think cmake claims to find Portaudio, but I haven't been touching it nor using it. First time ever I get these messages, they smell a bit windowsy for a linux.
```
-- USE_PORTAUDIO is enabled.
-- Building rtpa module.
-- PORTMIDI_INCLUDE_PATH="PORTMIDI_INCLUDE_PATH-NOTFOUND", so disabling USE_PORTMIDI
-- PORTMIDI_LIBRARY="PORTMIDI_LIBRARY-NOTFOUND", so disabling USE_PORTMIDI
-- PORTTIME_LIBRARY="PORTTIME_LIBRARY-NOTFOUND", so disabling USE_PORTMIDI
-- USE_PORTMIDI is disabled.
```

added: For that its worth, commenting line 150-151  in InOut/CMakeLists.txt causes the installation to succeed.

**Comment by vlazzarini** [comment]
lwinmm etc is Windows not Linux.

**Comment by hlolli** [comment]
I did not say that lwinmm was Linux, on the contrary, I said that these errors are too windowsy for a linux. Obviously a os checks there are a bit off.

**Comment by vlazzarini** [comment]
That's what I am pointing out. Cmake is broken in the linux build because of windows libraries

**Comment by hlolli** [comment]
ah ok! Sorry, I misunderstood that :)

**Comment by stekyne** [comment]
I just tested this with the latest develop branch but couldn't reproduce. Has it been fixed?

**Comment by stekyne** [comment]
Tested on Ubuntu also and not seeing the error.

**Comment by hlolli** [comment]
Anton was also reporting this 2-3 days ago on the mailing list, I try
installing again after work to confirm that this is solved.

2017-06-19 13:06 GMT+02:00 Stephen Kyne <notifications@github.com>:

**Comment by stekyne** [comment]
I took at the look at the version of CMakeLists.txt for your broken build, as per the blame commit. 

It does look broken for that version, the non-static build for non-MSVC was including winmm dsound setupapi.

It seems to be fixed in the latest version now so you should be able to just do a clean build and it will work.

**Comment by hlolli** [comment]
Yup, it's fixed from latest commit.
