### ISSUE TITLE
Feature request: Fade out on sigkill or csound process terminate

### ISSUE THREAD

**Issue by anton-k** [csound/csound#811]
Hi!

I'm trying to use the Csound on stage. And I often use it with JACK.
I have several little csound synths that are organized in the graph.

And often I'd like to substitute one csound-jack unit with another one.
Think of it like instrument switch or effect switch.

But when I terminate the csound process if it's still produces the audio
I can hear the pop or click. It's understandable behavious but it would
be great if csound could shut down in more musical way.

It would be nice to have a release stage. And be able to control the length
of it in the command line argument.

Like it happens in Cubase for instance when we shut down the track
we can still hear the reverb tail going on and it doesn't disappears with
the click but goes to silence in musical way.

**Comment by vlazzarini** [comment]
You could do that yourself. If you set up a listener for a SIGINT, SIGKILL etc in your application then deal with it in the way you want it to do, that should work. Your program could apply the fade out, stop performing and then destroy the Csound object.

In my opinion, this kind of thing is better handled by the application, rather than the library, which should have a more general approach to handling signals (after all not all applications want the same thing).

**Comment by anton-k** [comment]
Thanks for response! Does Csound provide the opcodes for handling SIG*** listeners?

**Comment by vlazzarini** [comment]
It doesn't, this is probably better handled in the host code (if you are using the API). Not sure exactly what could be done in the command-line frontend if that is where you need a change, but it might be possible to introduce a change there.

**Comment by anton-k** [comment]
My simple scenario is like this:

I have a pile of csd-s. Every csd is a MIDI-synt. And I'd like to be able to switch quickly between them. Or it might be a csd that generates playback for a track. Right now I manually turn the volume to zero. and then switch them. Kill one and spawn the next one.

Your solution means that I need to wrap every csd with another app that uses Csound-API. 
This can be lot of boiler plate... and unfortunaately hard to use for non programmers.

Another solution might be to create sort of switcher.. But then it should rely on common functions inside the csd's... I can not control the volume with API as far as I understand it.

**Comment by jpffitch** [comment]
> Another solution might be to create sort of switcher.. But then it should rely
> on common functions inside the csd's... I can not control the volume with API
> as far as I understand it.

You can as you can change spout values on each k-perf and so fade it out 
before replacing the .csd; at least I thik that can be done;  or ave 
aglobal gainn yu cange via achanel wic is probably easier.

**Comment by anton-k** [comment]
But this creates rather specific solution. Those synths are actually JACK-units. 
And in case of MIDI they have 2 out channels. In case of playback there can be more outputs. That means that I have to write a specific app for each kind of audio producing units..

**Comment by vlazzarini** [comment]
@anton-k  there are two things that can be done off the top of my head. 
First solution:
1) on SIGKILL/INT your program starts an instrument (say instr 10000) that controls
a global volume variable for a given time.
2) performance goes into a new loop with a given count.
3) after this, the csound performance is wrapped up by destroying the Csound instance.
Second solution:
1) your application takes care of audio IO (say to Jack, or to alsa, or etc)
2) on SIGKILL/INT it applies a fade out gain and exits after a certain amount of
iterations.

**Comment by anton-k** [comment]
everything can be done with api. some while ago jack also wasn't the part of the csound. And someone could ask what if csound could establish the jack interface from the CLI. 

But why do we need the flags for jack interface it if it's actually can be done with API?

I don't mean to disturb you. You are doing wonderful job and merits of this feature probably not so much important and too specific. I can understand :) 

But wrapping it in the API it's not very practical solution.

**Comment by vlazzarini** [comment]
Not sure exactly what your question is, you can establish a connection to jack through the CLI alright. Not sure where the talk of flags came from.

All you need is one program that does option 1 or 2 above. With option 1, which is simpler to implement, you need the CSD to include a global master gain variable that you can apply to the outputs and fade out; plus a boilerplate instrument that does that. Option 2 would not need any specific CSD code. You definitely don't need a separate program for each CSD.

**Comment by anton-k** [comment]
I'd rather go for solution that doesn't requires the specific csound code. 
But can the second solution work for any number of outputs?

PS: Alas csound api is not working for me anymore but I guess it's the topic of another quistion...  I think it's something to do with update to 6.09 version and some changes in the api that i need to find out.

It segfaults for me, and I was thinking to use just system call to csound. since I was just starting and stopping csd.

**Comment by vlazzarini** [comment]
Can we close this? I think we have established that this is not a feature that should be implemented in the Csound library, as it is too case-specific (and may likely cause side issues).

**Comment by jpffitch** [comment]
Agreed; close it

⁣Sent from TypeApp ​
