### ISSUE TITLE
After installing Csound6.09 / Win7-64: QT5svg.dll is missing (CsoundQT)

### ISSUE THREAD

**Issue by kezb765** [csound/csound#812]
Hello all,

I just installed Csound (Setup_Csound6_x64_6.09.0.exe) on Win7/64bit Enterprise. "csound -v" runs fine, but trying to start CsoundQT gives an error dialog about missing "QT5svg.dll". This dll is not present on my system, so I think the PATH is set correctly. I searched the net but didn't find an answer, I hope I am here in the right corner with this kind of question.

Installing the whole QT5 package for windows requires 900MB space, so this is not really an option, or is it?

Btw. with Csound6.08 -> CsoundQT did run fine!

Cheers, Michael

**Comment by manfredosanchez** [comment]
Hi,

Same issue here when trying to execute CSoundQT.

**Installer:** Setup_Csound6_x64_6.09.0.exe
**OS:** Windows 10

![image](https://user-images.githubusercontent.com/4485480/27451076-eeb8e8a6-575b-11e7-82e7-ef4b05054fa0.png)

Regards,

Manfredo.

**Comment by joachimheintz** [comment]
i just read this thread:
https://github.com/CsoundQt/CsoundQt/issues/238

maybe the version turgut tried out can work for you, too.

	joachim

**Comment by manfredosanchez** [comment]
Hi,

I've installed that version. It is working properly.

Thanks!

Manfredo.

**Comment by kezb765** [comment]
Thanks to Joachim, I read the thread CsoundQT#238, installed the ZIP and now I am able to start CsoundQT.

Just one small comment for windows user: the menu under "Programs" still points to "CsoundQt-d-py-cs6.exe" from the first installation (which yields an error). With the mentioned update the correct program is called "CsoundQt-d-cs6.exe". So either change the menu entry or just copy "CsoundQt-d-cs6.exe" over the old one.
