### ISSUE TITLE
Implement AAudio backend for Android

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#817]
Android currently has a developer preview for a new low-latency audio backend called AAudio. Information and examples available at:

https://developer.android.com/ndk/guides/audio/index.html
https://developer.android.com/ndk/guides/audio/aaudio/aaudio.html
https://github.com/googlesamples/android-audio-high-performance/

We should look at developing a dynamic solution that could try to use AAudio to start, then fallback to OpenSL.

**Comment by gogins** [comment]
I think that's a really great idea.

By the way, is this backend accessible from WebAssembly? Or JavaScript? I
mean on Android of course, but in the JavaScript context there.

Best,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by kunstmusik** [comment]
I haven't looked into this deeply, but I had heard about AAudio from the Google bug tracker:

https://issuetracker.google.com/issues/36908622#comment492

The issue mentions these videos:

Google I/O 2017 talk
Optimising recording and playback latency:  https://youtu.be/C0BPXZIvG-Q?t=10m29s
Introduction to AAudio: https://youtu.be/C0BPXZIvG-Q?t=21m53s

And it's listed as just a preview and not production ready.  I would guess that if Chrome/Webview on Android used AAudio, we would not have anything but just the standard WebAudio APIs to use.

**Comment by vlazzarini** [comment]
yes. Do you have an idea of what device we would need to have to develop for this? I think we will need that in order to progress with this.

**Comment by kunstmusik** [comment]
Developer preview of Android O looks available here:

https://developer.android.com/preview/download.html#flashable-images

For these devices:

Nexus 5X	
Nexus 6P	
Nexus Player
Pixel C
Pixel	
Pixel XL	

I assume we could compile/test against simulator, but not certain.

**Comment by kunstmusik** [comment]
Closing as stale. Android moved on to Oboe and if we update the audio driver we should be using that.
