### ISSUE TITLE
fractalnoise RPI2

### ISSUE THREAD

**Issue by bezlikijshlejf** [csound/csound#818]
Hi, 
when i turn off instance (p3 > 0) during perfomance with [fractalnoise] in instr code this crashes the engine
Linux raspberrypi 4.9.24-v7+ #993 SMP Wed Apr 26 18:01:23 BST 2017 armv7l GNU/Linux
--Csound version 6.09 (double samples) Apr  3 2017
[commit: 00e3d45fc6690889a421b9b98ea29c3a0422c780]

sorry my extremely poor english, thanks

**Comment by jpffitch** [comment]
Do you have a csd example?  I would like more details as how you are turning it off

**Comment by bezlikijshlejf** [comment]
i write osc client and my 'server.csd'

> \<CsoundSynthesizer\>

> \<CsOptions\>

> \</CsOptions\>

> \<CsInstruments\>
> 
> sr     = 48000
> ksmps  = 32
> nchnls = 2
> 0dbfs  = 1.0
> 
> 
> giOSC  OSCinit 3000
> 
> turnon 1
> 
> instr 1
> 
>  Scode     init ""
>  kloadevnt OSClisten giOSC, "/load", "s", Scode
>  kevalevnt evalstr Scode, kloadevnt
> 
>  kinsn     init 2
>  konevnt   OSClisten giOSC, "/on",   "i", kinsn
>  koffevnt  OSClisten giOSC, "/off",  "i", kinsn
> 
>  if (konevnt = 1) then
>  schedkwhen 1, 0, 2, kinsn, 0, 604800
>  endif
> 
>  kres active kinsn
> 
>  if (kres = 2) then
>  turnoff2 kinsn, 1, 1
>  endif
> 
>  if (koffevnt = 1) then
>  turnoff2 kinsn, 0, 1
>  endif
> 
> endin
> 
> \</CsInstruments\>
> \<CsScore\>
> \</CsScore\>
> \</CsoundSynthesizer\>

**Comment by vlazzarini** [comment]
Not sure where your crash is coming. I used your code, with some changes and was able to run it here. I don't think it is to do with fractalnoise.
```
<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

sr = 48000
ksmps = 32
nchnls = 2
0dbfs = 1.0

giOSC OSCinit 3000

instr 1

Scode init ""
kloadevnt OSClisten giOSC, "/load", "s", Scode
kevalevnt evalstr Scode, kloadevnt

kinsn init 2
konevnt OSClisten giOSC, "/on", "i", kinsn
koffevnt OSClisten giOSC, "/off", "i", kinsn

if (konevnt = 1) then
 printk 0, kinsn
 event "i", kinsn, 0, -1
endif

kres active kinsn

if (kres = 2) then
turnoff2 kinsn, 1, 1
endif

if (koffevnt = 1) then
turnoff2 kinsn, 0, 1
endif

endin

instr 200
S1 = {{ 
instr 2
ka init 1000
kctrlevnt OSClisten giOSC, "/a", "d", ka

a2 fractalnoise ka, 2
a1 vco2 0.25, k(a2), 0
a0 = a1
out a0, a0
endin
}}

OSCsend 1, "localhost", 3000, "/load", "s", S1
turnoff
endin

instr 201
OSCsend_lo 1, "localhost", 3000, "/on", "i", p4
turnoff
endin



</CsInstruments>
<CsScore>
i1 0 10
i200 1 1 
i201 2 1  2
i201 4 1 -2
e
</CsScore>
</CsoundSynthesizer>
```

**Comment by bezlikijshlejf** [comment]
perhaps, I do not know if it helps or not (dont have с++ background ) build csound from source with:
-O3 -mcpu=cortex-a7 -mtune=cortex-a7 -mfloat-abi=hard -mfpu=neon-vfpv4 -ffast-math -ftree-vectorize -funroll-loops -fomit-frame-pointer
flags, current raspbian gcc

**Comment by vlazzarini** [comment]
I can't reproduce the crash. You will need to give us a complete example demonstrating.

**Comment by jpffitch** [comment]
No example supplied in 4 months -- should this be closed?
