### ISSUE TITLE
CSound 6.09.1 win64 py.dll warning

### ISSUE THREAD

**Issue by tzunix** [csound/csound#824]
I keep getting:

"WARNING: could not open library 'C:\Csound6_x64\plugins64\\\py.dll' (-1)"

The double backslash just before py.dll might be the cause, not sure.

Tried: installing in default directory (same issue), installing in custom directory (C:\CSound_X64) as seen above.

**Comment by kunstmusik** [comment]
@tzunix do you have Python 2.7 (64-bit) installed on your system?

**Comment by tzunix** [comment]
You were incredibly spot-on... had the 32 bit version installed. Silly me. My apologies for asking this easily correctable question, thank you for the reply :).
