### ISSUE TITLE
On macOS, SIGINT doesn’t terminate Csound running while loop outside of instrument

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#827]
Running

```csound
while 1 == 1 do
    prints "Csound\n"
od
scoreline_i "e"
```

using `csound --nosound --orc test.orc` results in Csound printing `Csound` forever, and sending SIGINT (<kbd>Control</kbd>-<kbd>C</kbd> on macOS) does not terminate Csound.

**Comment by vlazzarini** [comment]
It's stuck in an i-time loop after compilation. This code is not called in perfKsmps() so it might be that the handler is not set correctly.

**Comment by vlazzarini** [comment]
Note that this is the case for all loops, regardless of whether they are in or out of instruments or whether they are init or perf time. Not sure whether we can do anything about this. An infinite loop in a program is an infinite loop in a program.

**Comment by vlazzarini** [comment]
Just checked and it appears to be an issue with the csound CLI frontend (the csound command). A simple host such as
```
int main(int argc, const char *argv[]){

  CSOUND *csound = csoundCreate(NULL);
  csoundCompile(csound, argc, argv);
  csoundPerform(csound);
  csoundDestroy(csound);
  return 0;
}
```

allows the command to be interrupted. I think this is because the signal handler in csound_main.c does not pass on the signal to Csound. I vaguely remember someone complaining about this before.

**Comment by vlazzarini** [comment]
Ok found a solution. fixed in git develop

**Comment by nwhetsell** [comment]
I see that you edited your original [remark](#issuecomment-316023296). I’ll note for posterity that on macOS (and almost certainly other operating systems), all of the following can be stopped with a SIGINT:

* [Node.js](https://nodejs.org): `node --eval "while(1){console.log('node')}"`
* [PHP](http://php.net): `php -r 'while (true) echo "php\n";'`
* [Python 2.7](https://www.python.org): `python -c "while True: print 'python'"`
* [Ruby](https://www.ruby-lang.org): `ruby -e 'while true do puts "ruby" end'`

**Comment by vlazzarini** [comment]
yes, as you will see from above, the problem was not with Csound per se, which handles signals but in the CLI csound that did not do it properly.
