### ISSUE TITLE
6.09.1 does not honor PYTHON_MODULE_INSTALL_DIR

### ISSUE THREAD

**Issue by ainola** [csound/csound#828]
6.09.1 seems to be outputting some python modules in my home folder when attempting to build for installation to the system. 6.09.0 did not exhibit this behavior.

Here are my Cmake variables:

PYTHON_INCLUDE_DIR=/usr/include/python2.7 \
PYTHON_LIBRARY=/usr/lib/libpython2.7.so \
JAVA_MODULE_INSTALL_DIR=/usr/lib/csound/java \
PYTHON_MODULE_INSTALL_DIR=/usr/lib/python2.7/site-packages \
LUA_MODULE_INSTALL_DIR=/usr/lib/lua/5.1 \
DPD_MODULE_INSTALL_DIR=/usr/lib/pd/extra

The files that this package creates are:

/home/ainola/.local/lib/python3.6/site-packages/csnd6.py
/home/ainola/.local/lib/python3.6/site-packages/_csnd6.so
/home/ainola/.local/lib/python3.6/site-packages/CsoundAC.py
/home/ainola/.local/lib/python3.6/site-packages/_CsoundAC.so
/home/ainola/.local/lib/python3.6/site-packages/ctcsound.py
/home/ainola/.local/lib/python3.6/site-packages/icsound.py

I notice that this is Python 3: Is there a new Cmake flag that I should be setting? I've been unsuccessful in finding any new items.

Thanks for your time.

**Comment by fsateler** [comment]
I've seen this when updating the debian package. This fixes the issue for me:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index f97541b..3559826 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -221,9 +221,11 @@ endif()
 execute_process (
      COMMAND python -c
      "import site, sys; sys.stdout.write(site.getusersitepackages())"
-     OUTPUT_VARIABLE PYTHON_MODULE_INSTALL_DIR
+     OUTPUT_VARIABLE PYTHON_USER_SITE_PACKAGES
    )
 
+SET(PYTHON_MODULE_INSTALL_DIR ${PYTHON_USER_SITE_PACKAGES} CACHE PATH)
+
 set(JAVA_MODULE_INSTALL_DIR ${LIBRARY_INSTALL_DIR})
 set(LUA_MODULE_INSTALL_DIR ${LIBRARY_INSTALL_DIR})
 
```

I'll post up a PR as soon as I clean this up (the CACHE change should probably go for all the MODULE_INSTALL_DIR variables).


>I notice that this is Python 3: Is there a new Cmake flag that I should be setting? I've been unsuccessful in finding any new items.

Are you using  Arch? `/usr/bin/python` points to python 3 there, which would explain the issue.

**Comment by ainola** [comment]
Yes, this is on Arch.... duh! I was reading into the issue incorrectly. Your patch works great! Thanks for that.

**Comment by kunstmusik** [comment]
This looks to be integrated into develop now: closing out issue.
