### ISSUE TITLE
Build error on develop

### ISSUE THREAD

**Issue by hlolli** [csound/csound#831]
Yet another can't build post :)

```
/home/hlolli/csound/csound/interfaces/csPerfThread.hpp:208:10: note:   no known conversion for argument 4 from ‘const double*’ to ‘const float*’
make[2]: *** [interfaces/CMakeFiles/_csnd6.dir/build.make:81: interfaces/CMakeFiles/_csnd6.dir/__/python_interfacePYTHON_wrap.cxx.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1976: interfaces/CMakeFiles/_csnd6.dir/all] Error 2
make: *** [Makefile:163: all] 
Error 2
```

unrelated question, I want to try the ableton link opcodes, but I didn't see them with `csound -z`. Some flag I need to give cmake for the ableton link opcodes to work?

**Comment by vlazzarini** [comment]
you sure this is not leftover from an earlier build? Looks like a doubles versus float version mismatch of some kind.

It's building fine otherwise travis would be broken. I'll close this and you can ask for help in the list.

**Comment by hlolli** [comment]
ah, took me short time to figure out what was going on here. I was installing with emscripten bit earlier and renamed the float-version.h.in. Which is a seperate question, why we use installation variable within a c header file. But to be discussed another time. Thanks!
