### ISSUE TITLE
Lack of consistency between chnget and chnset

### ISSUE THREAD

**Issue by rorywalsh** [csound/csound#835]
We discussed this on the mailing list before the last release. @kunstmusik summaries the issue as follows:

> chnget looks to check if names change for k-rate out:
> 
> https://github.com/csound/csound/blob/develop/OOps/bus.c#L661-L686
> 
> but chnset does not look to do the same:
> 
> https://github.com/csound/csound/blob/develop/OOps/bus.c#L846-L861

**Comment by vlazzarini** [comment]
done.
