### ISSUE TITLE
Csound doesn't run on Mac

### ISSUE THREAD

**Issue by Maxpumpkin** [csound/csound#836]
Good evening everybody!
I ask your help because I've downloaded Csound app for Mac OS X v.6.09.1.
Initially did run normally,but suddenly it had stop to run.When I click on the icon of the application,it appears the logo of the program just for few istant but the program doesn't start.The version of my operative system is OS X El Capitan Version 10.11.6.
I hope you can help me to solve this trouble.
Best regards to everybody!

**Comment by rorywalsh** [comment]
You mean CsounQT?

**Comment by Maxpumpkin** [comment]
Yes!

**Comment by joachimheintz** [comment]
we just had a similar question here: 
https://github.com/csound/csound/issues/834

but CsoundQt is not Csound. instead there are many frontends for csound, 
and csoundqt is only one of them.  an explanation is for instance given 
in the "Csound and Frontends" paragraph of:
http://write.flossmanuals.net/csound/a-make-csound-run/

can you please ask for help either on the csoundqt mailing list:
https://sourceforge.net/projects/qutecsound/lists/qutecsound-users

or in the general csound mailing (as there are many users who also use 
csoundqt as frontend, and this list is much bigger than the csoundqt list):
https://listserv.heanet.ie/cgi-bin/wa?SUBED1=CSOUND&A=1

thanks -
	joachim

**Comment by Maxpumpkin** [comment]
Thanks a lot!
