### ISSUE TITLE
asio4all not listed in Csound6_x64_6.09.1 WIN7

### ISSUE THREAD

**Issue by cvrn** [csound/csound#837]
asio4all is not listed in Csound --devices in Csound6_x64_6.09.1 WIN7.
Switching back to Csound 6.07 asio4all is listed and works.

**Comment by cvrn** [comment]
Update: Same issue in Csound6_x64_6.09.2beta2: does not work with asio4all

Back to Csound6_x64_6.08: works with asio4all

**Comment by cvrn** [comment]
Update: After replacing rtpa.dll - according to Stevens advice - with rtpa.dll from 6.08 and it worked perfectly.

**Comment by kunstmusik** [comment]
This looks to be an issue with the installer build and should be double-checked for next 6.x release (6.10).

**Comment by kunstmusik** [comment]
@rorywalsh Is this issue one that can be closed?

**Comment by rorywalsh** [comment]
Just checked with 6.10. asio4all seems to be working fine.
