### ISSUE TITLE
Implement comparisons for arrays

### ISSUE THREAD

**Issue by gesellkammer** [csound/csound#840]
Comparison operators in csound are different than other operators. On scalars they can be converted via the ternary operator: `kout = kin > k1 ? 1 : 0`. This is not possible for arrays and for audio variables. For audio variables there are workarounds, like the opcodes `select` and `cmp`. For arrays these operators are missing. Implementing these comparisons as user defined opcodes is very inefficient at the moment. 

What is needed is the implementation of <, >, ==, !=, >= and <= for arrays:

```csound
kA[] fillarray ...
kOut[] = kA > k1
```

and also

```csound
kA[] fillarray ...
kB[] fillarray ...
kOut[] = kA > kB
```

Where kOut will hold an array of the same size as kA with the element by element comparison of kA[kidx] > k1 in the first case, and kA[kidx] > kB[kidx] for the second case, true being 1 and false being 0

Use case:

For additive synthesis with a high number of oscillators I need to iterate over large arrays at k-time, which hold the values for freq., amp., etc. These loops consume a lot of CPU. On the other hand, using native operations over arrays (+, *, ceil, sqrt, etc.) is very efficient. Comparison operators are missing. They would make such loops much faster.

**Comment by kunstmusik** [comment]
I took a stab at this within the C++ arrayops file using:

```
inline MYFLT arrlt(MYFLT v1, MYFLT v2) { return (v1 < v2) ? 1.0 : 0.0;  }
inline MYFLT arrlte(MYFLT v1, MYFLT v2) { return (v1 <= v2) ? 1.0 : 0.0;  }
inline MYFLT arrgt(MYFLT v1, MYFLT v2) { return (v1 > v2) ? 1.0 : 0.0;  }
inline MYFLT arrgte(MYFLT v1, MYFLT v2) { return (v1 >= v2) ? 1.0 : 0.0;  }
inline MYFLT arreq(MYFLT v1, MYFLT v2) { return (v1 == v2) ? 1.0 : 0.0;  }
inline MYFLT arrnoteq(MYFLT v1, MYFLT v2) { return (v1 != v2) ? 1.0 : 0.0;  }

...

 csnd::plugin<ArrayOp2<arrlt>>(csound, "<", "i[]", "i[]i[]",
      csnd::thread::i);
  csnd::plugin<ArrayOp2<arrlt>>(csound, "<", "k[]", "k[]k[]",
      csnd::thread::ik);
  csnd::plugin<ArrayOp2<arrlte>>(csound, "<=", "i[]", "i[]i[]",
      csnd::thread::i);
  csnd::plugin<ArrayOp2<arrlte>>(csound, "<=", "k[]", "k[]k[]",
      csnd::thread::ik);
  csnd::plugin<ArrayOp2<arrgt>>(csound, ">", "i[]", "i[]i[]",
      csnd::thread::i);
  csnd::plugin<ArrayOp2<arrgt>>(csound, ">", "k[]", "k[]k[]",
      csnd::thread::ik);
  csnd::plugin<ArrayOp2<arrgte>>(csound, ">=", "i[]", "i[]i[]",
      csnd::thread::i);
  csnd::plugin<ArrayOp2<arrgte>>(csound, ">=", "k[]", "k[]k[]",
      csnd::thread::ik);
  csnd::plugin<ArrayOp2<arreq>>(csound, "==", "i[]", "i[]i[]",
      csnd::thread::i);
  csnd::plugin<ArrayOp2<arreq>>(csound, "==", "k[]", "k[]k[]",
      csnd::thread::ik);
  csnd::plugin<ArrayOp2<arrnoteq>>(csound, "!=", "i[]", "i[]i[]",
      csnd::thread::i);
  csnd::plugin<ArrayOp2<arrnoteq>>(csound, "!=", "k[]", "k[]k[]",
      csnd::thread::ik);
```

This compiled fine, however when writing a test CSD file it revealed that the parser would need to be rewritten as it assumes <. <=, >, >=, !=, and == are "boolean expressions".  

I think the easiest solution would be to not try to overload operators and use named opcodes, such as array_lt, array_lte, and so on.  I did a test by defining:

```
  csnd::plugin<ArrayOp2<arrlt>>(csound, "<", "i[]", "i[]i[]",
      csnd::thread::i);
  csnd::plugin<ArrayOp2<arrlt>>(csound, "<", "k[]", "k[]k[]",
      csnd::thread::ik)
```

with the code above and the test.csd

```csound
<CsoundSynthesizer>
<CsOptions>
</CsOptions>
; ==============================================
<CsInstruments>

sr	=	48000
ksmps	=	1
;nchnls	=	2
0dbfs	=	1

instr 1	
karr1[] fillarray 0,1,2,3,0,1,2,3
karr2[] fillarray 0,-1,2,3.1,0,4,5,-1

karr3[] = array_lt(karr1,karr2)

printk2 karr3[0]
printk2 karr3[1]
printk2 karr3[2]
printk2 karr3[3]
printk2 karr3[4]
printk2 karr3[5]
printk2 karr3[6]
printk2 karr3[7]

turnoff

endin

</CsInstruments>
; ==============================================
<CsScore>
i1 0 1


</CsScore>
</CsoundSynthesizer>
```

correctly yielded results of

```
 i1     0.00000
 i1     0.00000
 i1     0.00000
 i1     1.00000
 i1     0.00000
 i1     1.00000
 i1     1.00000
 i1     0.00000
```

If the named opcode idea works for you, this should be quick to implement. 

(Requesting @vlazzarini and @jpffitch to chime in and review this)

**Comment by gesellkammer** [comment]
Thanks for taking a look at it. I would be great if we could avoid more 
quirks and simply overload the comparison operators. I opened this issue 
after implementing it myself as part of the "cmp" opcode, which reads:

kIn[] fillarray ...
kOut[] = cmp(kIn, "<", k1)

This works okay and is overloaded for both arrays and audio signals. It is 
a lot faster than a loop in csound. But the simplicity and beauty of
 
kOut[] = kIn < k1

would be really nice to have.

**Comment by kunstmusik** [comment]
As it is, I'd prefer any language parser changes like this to go into Csound 7 (feature/parser3 branch) where it'd be simpler to work on and wouldn't require implementing twice as parser3 differs enough to make it a bit of a pain to do both in CS6 and 7.  If you can use cmp in CS6 for now, then how about targeting this change for CS7?

**Comment by gesellkammer** [comment]
Yes, CS7 would be fine.
