### ISSUE TITLE
manual example FLsavesnap_simple.csd

### ISSUE THREAD

**Issue by strapparts** [csound/csound#841]
On version 6.09.1 the example FLsavesnap_simple.csd work well.
On version 6.03.2 not work , giving message: "segmentation violation". BUT transfering those lines of code:

ivalSM1 FLvalue "", 70, 20, 270, 20
gksliderA, gislidSM1 FLslider "Slider", -4, 4, 0, 3, ivalSM1, 250, 20, 20, 20

after all FLbutton, the example run.
Greetings A.S.

**Comment by jpffitch** [comment]
I am confused; 6.09 is later than 6.03 so why are we worrying?

**Comment by strapparts** [comment]
Excuse me, you're right, it's not necessary, because in the last Csound version running on Windows Xp, that is 6.07 beta, this example runs well, then Windows Xp users can use this version.



  ----- Original Message -----

**Comment by strapparts** [comment]
Hi Rory,
I installed Cabbage32 on Windows Xp and I receive a similar message:
impossible to locate a component: MSVCP140D.dll.
I installed all Visual Studio Redistibutable (see attached .jpg), but I always get the same message.
Do you have a suggestion?
Cheers
Andrea S.

---
Questa e-mail è stata controllata per individuare virus con Avast antivirus.
https://www.avast.com/antivirus

**Comment by gogins** [comment]
Built with debug. The debug dlls can't be redistributed. Need to be built
for release.

**Comment by jpffitch** [comment]
Can this issue be close?  I cannot see exactly what the issue is supposed to be, old version?  Incorrecr distribution on another system?

**Comment by strapparts** [comment]
Yes, it can be closed. Thank you. Greetings

Il 08/gen/2018 2:47 PM, "John ffitch" <notifications@github.com> ha scritto:
