### ISSUE TITLE
looptseg cases segfault..

### ISSUE THREAD

**Issue by rorywalsh** [csound/csound#844]
The following instrument will cause a segfault if its run for longer than 2 seconds. 

```csound
instr 1
kweightpoint looptseg 0.5, 0, 0, 0.1, 14, 1, 2, 6, 1
endin
```

**Comment by jpffitch** [comment]
Yes, looks like reading beyond an array. I have a version that does not 
cras but I really do not know wat it is supposed to do
==Jon

**Comment by rorywalsh** [comment]
It's not an opcode I've ever used before, but one of the guys on the Cabbage forum was having issues with it. The example in the docs is fine. Perhaps we are sending bogus values to it?

**Comment by jpffitch** [comment]
There are n segment definitions but the code read the time of  n+1 segment.  This is clearly wrong -- used for interpolation I think.  Without understanding the code either we stop the loop one segment earlier, or do not interpolate in the last segment.

The code is devoid of comments or descriptions

==John

⁣Sent from Blue ​

**Comment by vlazzarini** [comment]
who is the author?

**Comment by rorywalsh** [comment]
According to the manual it was written by a certain Mr.ffitch!

**Comment by jpffitch** [comment]
Gabriel

**Comment by jpffitch** [comment]
I have committed code that I _think_ is right

**Comment by rorywalsh** [comment]
Iain has just explained how looptseg needs to end on a value. If an additional value is added to the code above it works fine. I'm not sure if the fix you put through yesterday now means one doesn't need an extra parameter for the code to work, but if so it may have broken other things. A warning or init error might be nice to display in this case?

**Comment by vlazzarini** [comment]
looks like it needs the correct 'type' code in oentry to check for the number of arguments (e.g. 
even or odd).

**Comment by kunstmusik** [comment]
Is this issue fixed?

**Comment by vlazzarini** [comment]
it can't be solved with type spec, it needs to be an i-time check on number of parameters passed.

**Comment by vlazzarini** [comment]
I think John has fixed this. I'll  close the issue now
