### ISSUE TITLE
import CsoundAC in python not working (OS X)

### ISSUE THREAD

**Issue by MulB** [csound/csound#848]
I installed csound6.09.1-OSX-universal.dmg under OSX 10.11.6 and wanted to
try CsoundAC in python.

When I start python and import CsoundAC, _Csound.so wants to load 
/Users/victor/src/csound6/installer/macosx/2017-07-10-011053/csound6/build/libCsoundAC.6.0.dylib which of course is not found, see the python error message below.

There seems to be a wrong path hard coded in _CsoundAC.so.

Inspecting _CsoundAC.so with otool -L shows also another strange dylib path:

/Library/Frameworks/CsoundLib64.framewok/Versions/6.0/libcsnd6.6.0.dylib

(CsoundLib64.framewok instead of CsoundLib64.framework)

Thanks,

Michael

Error message:

$ /usr/bin/python
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import CsoundAC
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/CsoundAC.py", line 17, in <module>
    _CsoundAC = swig_import_helper()
  File "/Library/Python/2.7/site-packages/CsoundAC.py", line 16, in swig_import_helper
    return importlib.import_module('_CsoundAC')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: dlopen(/Library/Python/2.7/site-packages/_CsoundAC.so, 2): Library not loaded: /Users/victor/src/csound6/installer/macosx/2017-07-10-011053/csound6/build/libCsoundAC.6.0.dylib
  Referenced from: /Library/Python/2.7/site-packages/_CsoundAC.so
  Reason: image not found

**Comment by MulB** [comment]
Since no one seems to care so far I guess that CsoundAC is of minor importance for the Csound team. Maybe it should be removed from the standard distribution?
After making some fixes in the shell script that builds the release (some install_name_tool calls need to be changed and added) I can build Csound in a way that allows to import CsoundAC from python but there are other issues. In particular, leaving Python after importing CsoundAC generates a segmentation fault during Csound's "tidy up".

For me this was part of several experiments with Supercollider and Csound to make a decision in which direction to go.

Michael

**Comment by kunstmusik** [comment]
@MulB Thanks for following up with this information.  I wouldn't say no one cares, its just an odd situation and a busy time for things to go unnoticed unfortunately. Last I heard, CsoundAC was being considered for separate release from Csound by its author (@gogins) but I do not know when/whether that is still happening.  Also, @gogins does not use OSX, and those doing development of Csound on OSX don't use CsoundAC, but it is packaged together out of courtesy. 

For the interim, the information given points out the problem with the release script.  Perhaps @vlazzarini can look into correcting this for 6.10, which we are the middle of trying to get sorted out before the Csound conference in a couple of weeks.

**Comment by gogins** [comment]
I have not decided to move CsoundAC out of the distribution. I think that
will depend on whether it is feasible to build CsoundAC for WebAssembly, in
that case I would move it, otherwise not.

**Comment by vlazzarini** [comment]
yes it's in my todo list to fix the installer script. There are so many libraries, all of them needing some sort of install name fix that it has been hard to get all of them right. We depend on user reports such as this ones for some components we don't use ourselves. I guess CsoundAC does not havd a user base on OSX.

**Comment by vlazzarini** [comment]
I have modified the script to fix the issues listed here. I can't speak for the crash, that might need a separate ticket which @gogins might be able to deal with. I am closing this ticket as the installer has been fixed for 6.10.

**Comment by MulB** [comment]
Many thanks, @vlazzarini. I appreciate your extensive work on Csound.

 

Maybe the following observations are helpful:

 

- There are some files installed to ~/Library/Python/2.7/lib/python/site-packages/

  while running the installer script. This is, however, not the location the pkg

  installs these files to. Thus, if one builds Csound from source, the following 6

  files remain installed that don't belong to the distribution:

 


-- Installing: /Users/username/Library/Python/2.7/lib/python/site-packages/_csnd6.so

-- Installing: /Users/username/Library/Python/2.7/lib/python/site-packages/csnd6.py

-- Installing: /Users/username/Library/Python/2.7/lib/python/site-packages/ctcsound.py

-- Installing: /Users/username/Library/Python/2.7/lib/python/site-packages/icsound.py

-- Installing: /Users/username/Library/Python/2.7/lib/python/site-packages/_CsoundAC.so

-- Installing: /Users/username/Library/Python/2.7/lib/python/site-packages/CsoundAC.py



 

- I made the following changes in the release-build.sh script:

 


< install_name_tool -change $BUILD_DIR/libcsnd6.6.0.dylib /Library/Frameworks/CsoundLib64.framewok/Versions/6.0/libcsnd6.6.0.dylib $FRAMEWORK64_DIR/Versions/6.0/Resources/Python/Current/_CsoundAC.so

---

> install_name_tool -change $BUILD_DIR/libcsnd6.6.0.dylib /Library/Frameworks/CsoundLib64.framework/Versions/6.0/libcsnd6.6.0.dylib $FRAMEWORK64_DIR/Versions/6.0/Resources/Python/Current/_CsoundAC.so

 

> install_name_tool -change $DEPS_BASE/lib/libfltk_forms.1.3.dylib @loader_path/../../../../../libs/libfltk_forms.1.3.dylib $FRAMEWORK64_DIR/Versions/6.0/Resources/Python/Current/_CsoundAC.so

 

> install_name_tool -change $BUILD_DIR/libCsoundAC.6.0.dylib /Library/Frameworks/CsoundLib64.framework/Versions/6.0/libCsoundAC.6.0.dylib $FRAMEWORK64_DIR/Versions/6.0/Resources/Python/Current/_CsoundAC.so



 

Michael

 



Gesendet: Samstag, 16. September 2017 um 11:34 Uhr
Von: vlazzarini <notifications@github.com>
An: csound/csound <csound@noreply.github.com>
Cc: MulB <mulbrich@gmx.net>, Mention <mention@noreply.github.com>
Betreff: Re: [csound/csound] import CsoundAC in python not working (OS X) (#848)


I have modified the script to fix the issues listed here. I can't speak for the crash, that might need a separate ticket which @gogins might be able to deal with. I am closing this ticket as the installer has been fixed for 6.10.

**Comment by vlazzarini** [comment]
thanks, I'd forgotten about the fltk link. I have not yet committed the changes. I'll see why the other files are being included in the installer.
