### ISSUE TITLE
CsoundQt still crash with Csound

### ISSUE THREAD

**Issue by caecos** [csound/csound#849]
I have tried the latest version of CsoundQt 0.9.5-beta with Csound 6.09.2 beta 2 and is still crash. It is exactly the same problem as with the previous CsoundQt .09.4/Csound 6.09.1 in beta version before it was fixed.

**Comment by jpffitch** [comment]
This is most likely a  QT problem not a csound one.

**Comment by caecos** [comment]
Hi John,

You are right, it is a QT problem.

Regards,

Marc

De : John ffitch [mailto:notifications@github.com]
Envoyé : mercredi 27 septembre 2017 15:59
À : csound/csound <csound@noreply.github.com>
Cc : caecos <caecos@hotmail.ca>; Author <author@noreply.github.com>
Objet : Re: [csound/csound] CsoundQt still crash with Csound (#849)


This is most likely a QT problem not a csound one.
