### ISSUE TITLE
v6.09 for linux plays some scores at half speed

### ISSUE THREAD

**Issue by pdrezet** [csound/csound#851]
I have built v6.09 from source and found that some scores now play slow. 
I have built on Debian Jessie using the standard cmake command in the csound build document. I have tried single precision and default double precision variants.
The scores sample rate is 44.1KHz and the sounds are sourced from wav files also sampled at 44.1KHz.
This issue is specific only to some scores, whilst others play fine.

The scores play fine on v5.12 (built from source) and the standard debian package (v6.05).

**Comment by kunstmusik** [comment]
Need more information to identify the problem. Could you submit a test CSD
that demonstrates the problem?

**Comment by pdrezet** [comment]
I'll try to find a smaller example that exhibits the issue as the current script requires large numbers of wav files.
Also I've found that the same issue occurs with with the prebuilt Debian 6.09.1, so this problem appears to be 6.09.1 specific. The soundscape played fine on v6.05. (Changing issue title)

**Comment by jpffitch** [comment]
Do you use loscil?  There was a major error in it, now fixed.

Would be nice to nail this before v6.10

==John ff


⁣Sent from TypeApp ​

**Comment by pdrezet** [comment]
Yes we are using loscil - we'll try v6.10 out and report back.

**Comment by kunstmusik** [comment]
Closing: Assumed to be fixed in 6.10.0.  If issue still persists, please file a new issue against 6.10.0.
