### ISSUE TITLE
ladspa header not recognised

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#852]
DSSI4CS: Loading first instance.
DSSI4CS: About to load descriptor function for plugin 0 of 1.
DSSI4CS: LADSPA Plugin Detected
INIT ERROR in instr 0: DSSI4CS: Unable to find ladspa_descriptor() function or
dssi_descriptor() function in plugin file "/usr/lib/ladspa/delay.so".
Are you sure this is a LADSPA or DSSI plugin file ?
gihandle	dssiinit	"/usr/lib/ladspa/delay.so"	1	1	
header init errors
inactive allocs returned to freespace
end of score.		   overall amps:      0.0      0.0
	   overall samples out of range:        0        0
2 errors in performance
Elapsed time at end of performance: real: 0.006s, CPU: 0.011s

and the csd:

<CsoundSynthesizer>
<CsInstruments>
sr=48000
ksmps=32
nchnls=2

gihandle dssiinit "/usr/lib/ladspa/delay.so", 1, 1	

	instr 1	;activate DSSI
dssilist
print gihandle
	endin
</CsInstruments>
<CsScore>
i1	0.0	2	
e
</CsScore>
</CsoundSynthesizer>

the ladspa plugin is seen with a utility i installed:
menno@menno-P5K ~ $ ladspalist
# 1044 Sine Oscillator (Freq:audio, Amp:audio)
> a: Frequency (Hz) (0 to 0.5)
> a: Amplitude (0 to ...)
< a: Output

# 1045 Sine Oscillator (Freq:audio, Amp:control)
> a: Frequency (Hz) (0 to 0.5)
> k: Amplitude (0 to ...)
< a: Output

# 1046 Sine Oscillator (Freq:control, Amp:audio)
> k: Frequency (Hz) (0 to 0.5)
> a: Amplitude (0 to ...)
< a: Output

# 1047 Sine Oscillator (Freq:control, Amp:control)
> k: Frequency (Hz) (0 to 0.5)
> k: Amplitude (0 to ...)
< a: Output

# 1043 Simple Delay Line
> k: Delay (Seconds) (0 to 5)
> k: Dry/Wet Balance (0 to 1)
> a: Input
< a: Output

# 1050 White Noise Source
> k: Amplitude (0 to ...)
< a: Output

# 1048 Mono Amplifier
> k: Gain (0 to ...)
> a: Input
< a: Output

# 1049 Stereo Amplifier
> k: Gain (0 to ...)
> a: Input (Left)
< a: Output (Left)
> a: Input (Right)
< a: Output (Right)

# 1041 Simple Low Pass Filter
> k: Cutoff Frequency (Hz) (0 to 0.5)
> a: Input
< a: Output

# 1042 Simple High Pass Filter
> k: Cutoff Frequency (Hz) (0 to 0.5)
> a: Input
< a: Output

**Comment by jpffitch** [comment]
Yes I see the error.  I have read the code and single stepped.  It sees
there is a ladspa_descriptor function, but the call to this returns NULL
and hence it fails.  I am out off my knowledge area here.
==John ffitch

**Comment by jpffitch** [comment]
I have determined this is user error.  Change the dssiiit line to
gihandle dssiinit "/usr/lib/ladspa/delay.so", 0, 1
and ot works (for me).

Will close issue shortly

**Comment by tjingboem** [comment]
yes, it is user error (mine that is). 
Thanks for investigating, greetings.
