### ISSUE TITLE
Parser error messages have typos

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#854]
The error message at https://github.com/csound/csound/blob/f7029ee42fc971d311e1ea17d646f3bf2da391a7/Engine/new_orc_parser.c#L273 should probably be `"Parsing failed due to syntax errors\n"`.

The error message at https://github.com/csound/csound/blob/f7029ee42fc971d311e1ea17d646f3bf2da391a7/Engine/new_orc_parser.c#L275 should probably be `"Parsing failed due to no input!\n"`.

**Comment by kunstmusik** [comment]
I took a look at changing this in these files which is straightforward, but then I realized that these strings are also used as keys in the translation files in po/*.po.  

@jpffitch For a message change like this, is the process to update it in the file, then update within all of the po files? If so, whom do we need to contact regarding the translations?

**Comment by jpffitch** [comment]
The script update in po directory does the first part.  For translations I look after American and Francois does the French.  Others are ad-hoc.


The tester script looks at changes outstanding

⁣Sent from TypeApp ​

**Comment by kunstmusik** [comment]
Closing: fixed by @jpffitch  in commit https://github.com/csound/csound/commit/b96c2d044d13047471689fe9db88ae62c1f5ea6a
