### ISSUE TITLE
loscil: kcps argument receives only integer numbers, with console message "put0"

### ISSUE THREAD

**Issue by strapparts** [csound/csound#855]
Hi,
if I write this line:
asig loscil .8, 1.2, p4, 1
I listen the same of:
asig loscil .8, 1, p4, 1
Greetings
Andrea Strappa

**Comment by jpffitch** [comment]
Version?  loscil hadmajor problems in 6.09 and fixed in 6.10
ad plase complete csd file is much easier

**Comment by jpffitch** [comment]
Works for me on 6.10

**Comment by strapparts** [comment]
Thank you for your replay.
I have problems with 6.09.1, Windows64.
In http://csound.github.io/download.html I see 6.09.1  I see 6.09.1 version.
Could you tell me where is 6.10 installer?
Greetings A. Strappa

Da: John ffitch
Inviato: domenica 1 ottobre 2017 22:19
A: csound/csound
Cc: strapparts; Author
Oggetto: Re: [csound/csound] loscil: kcps argument receives only integernumbers, with console message "put0" (#855)

Version? loscil hadmajor problems in 6.09 and fixed in 6.10
ad plase complete csd file is much easier

**Comment by jpffitch** [comment]
Due for release as soon as possible.

⁣Sent from Blue ​

**Comment by hlolli** [comment]
I believe I also encountered these put0 from loscil. Glad this got discovered and fixed.

**Comment by jpffitch** [comment]
The put0 message was only tracing saying which way a test went.  Commented out now as code was fixed

**Comment by strapparts** [comment]
Very well! When I get home I'll install 6.10 version and I test it. Thank
you

Il 01/ott/2017 10:19 PM, "John ffitch" <notifications@github.com> ha
scritto:
