### ISSUE TITLE
csoundSetStringChannel().. 

### ISSUE THREAD

**Issue by rorywalsh** [csound/csound#857]
(possibly related to https://github.com/csound/csound/issues/856#issuecomment-333767964)

Updating string channels in Csound at perf-time works fine, but it doesn't seem possible when using the API? Here's an example .cpp file and corresponding .csd file.

https://gist.github.com/rorywalsh/8b1f3ef287f18c6f43a21a2ded4755c1
https://gist.github.com/rorywalsh/cf7e02b49f422b7c8a4e09321d2c2754

**Comment by vlazzarini** [comment]
Did you try creating the channel with chn_S in the CSD first? Maybe the channel is created as a numeric one and the setting fails.

**Comment by vlazzarini** [comment]
To be quick, I've tested it on Python:

```
import ctcsound

cs = ctcsound.Csound()
cs.compileOrc('''
instr 1
S1 chnget "string"
printks S1, 0
endin
''')
cs.start()
cs.inputMessage('i 1 0 1')
cs.setStringChannel('string', 'hello...\n')
cs.performKsmps()
cs.setStringChannel('string', '...goodbye\n')
cs.performKsmps()
```
and ran it

```
ligeti:debug victor$ python3 setstring.py 
time resolution is 1000.000 ns
virtual_keyboard real time MIDI plugin for Csound
WARNING: STK opcodes not available: define environment variable RAWWAVE_PATH
(points to rawwaves directory) to use STK opcodes.
0dBFS level = 32768.0
--Csound version 6.10 beta (double samples) Oct  3 2017 
[commit: da9dfebca45abfc80b41260725bd4ff17becfcce]
libsndfile-1.0.25
WARNING: STK opcodes not available: define environment variable RAWWAVE_PATH
(points to rawwaves directory) to use STK opcodes.
rtaudio: PortAudio module enabled ... 
using callback interface
rtmidi: PortMIDI module enabled
graphics suppressed, ascii substituted
0dBFS level = 32768.0
orch now loaded
audio buffered in 1024 sample-frame blocks
writing 2048-byte blks of shorts to test.aif (AIFF)
SECTION 1:
new alloc for instr 1:
hello...
...goodbye
inactive allocs returned to freespace
end of score.		   overall amps:      0.0
	   overall samples out of range:        0
0 errors in performance
Elapsed time at end of performance: real: 0.007s, CPU: 0.007s
1024 2048 sample blks of shorts written to test.aif (AIFF)
```
So the API setting of strings work.

**Comment by vlazzarini** [comment]
and your example works here also (if I run only instr 2, so that the string channel is not updated by
Csound).

**Comment by rorywalsh** [comment]
That's odd. It's not working for me with the very latest dev branch on Linux, built a few moments ago. I've followed your lead and simplified the example to this:

```cpp
#include <stdio.h>
#include "csound.hpp"
#include <iostream>

using namespace std;

int main(int argc, char *argv[])
{
string userString = "";

Csound* csound = new Csound();
std::string orc = 
"sr = 44100\n\
ksmps = 32\n\
nchnls = 2\n\
0dbfs = 1\n\
\n\
instr 2\n \
 if changed:k(chnget:S(\"stringChannel\"))==1 then \n\
     printks chnget:S(\"stringChannel\"), 0\n\
 endif \n\
endin\n";

csound->SetOption("-+rtaudio=jack");
csound->SetOption("-odac");

csound->CompileOrc(orc.c_str());
csound->Start();

csound->InputMessage("i2 0 3600");
csound->SetStringChannel("string", "hello...\n");
csound->PerformKsmps();
csound->SetStringChannel("string", "...goodbye\n");
csound->PerformKsmps();

return 0;
}
```

**Comment by vlazzarini** [comment]
wrong channel name in your orchestra code.

**Comment by rorywalsh** [comment]
Yikes! Thanks Victor.

**Comment by rorywalsh** [comment]
While we're on the subject, parts of my code base still uses csoundSetChannel() to set string channels. When I swap them out for csoundSetStringChannel() my applications no longer work in the same way. I'm wondering if csoundSetStringChannel() has to be called between calls to performKsmps() as shown in the code above.

**Comment by vlazzarini** [comment]
I am not sure the C function csoundSetChannel() is threadsafe, but csoundSetStringChannel() is. That might affect the behaviour.
