### ISSUE TITLE
Extract feature crashes

### ISSUE THREAD

**Issue by cscomposer** [csound/csound#860]
Dear Csounders,
I tested (and i need) the extract feature –xfile.txt (that dr. Lazzarini fixed on GIT sources on 6.03) on 6.06 and 6.09 (OSX) and it crashes always CsoundQt!
I need this old feature for an important goal: to hear single sounds and voices from a long score articulated in more sections: for this purpose don’t seem valid the other features avalaibles:
-the advance feature (a 0 0 xsec)
-the skip section “x”
-the "setscoreposition" opcode, valid apparently without sections
-the "Evaluate selection", avalaible in CsoundQt, interesting but not so practice and general I I find this extract feature valid to control each voice/instrument and time point (or attack point) of score!
Greetings and gratulations for ICSC!
Giovanni Damiani

**Comment by vlazzarini** [comment]
does it crash on the terminal?

**Comment by cscomposer** [comment]
Yes, also, the Terminal hangs on   ... extracting ...

**Comment by cscomposer** [comment]
the command line is -xextract.txt that says just "f 3:0  t 4:0" (hear section 3)

**Comment by vlazzarini** [comment]
can we have your CSD?

**Comment by vlazzarini** [comment]
I see there is a problem in reading the extract.txt file (extract.c). @jpffitch  do you know anything about this code?

**Comment by cscomposer** [comment]
of course, i am sorry it'a big file out of order but functional and without external files (pure synthesis standalone); in the past I used the extract feature. Thanks!
[extract.txt](https://github.com/csound/csound/files/1382243/extract.txt)

[p141moui inizio DCratioBaseAUDIOschedule2 2 copia.csd.zip](https://github.com/csound/csound/files/1382245/p141moui.inizio.DCratioBaseAUDIOschedule2.2.copia.csd.zip)

**Comment by vlazzarini** [comment]
I have identified a problem in the extract file reading, but there might be other issues as well.

**Comment by cscomposer** [comment]
in 6.03 you fixed a bug (see post with NicB)...

**Comment by vlazzarini** [comment]
yes I remember. I see some changes from 2017, which may be related.

**Comment by vlazzarini** [comment]
I fixed the extract reading, but the extraction is not right, I am getting a "unexpected EOF!!" 
error from the parser.

**Comment by jpffitch** [comment]
Not at all familiar  with this feature but I do notice oddities like
....
carrying p-fields
swrite: output, sect16 line2 p15 ramp has illegal forward or backward ref
swrite: output, sect16 line2 p16 ramp has illegal forward or backward ref
swrite: output, sect16 line4 p15 ramp has illegal forward or backward ref
swrite: output, sect16 line4 p16 ramp has illegal forward or backward ref
sort: illegal opcode x(78)
swrite: unexpected opcode x, section 18 line 2
sort: illegal opcode x(78)
swrite: unexpected opcode x, section 20 line 2
sort: illegal opcode x(78)
swrite: unexpected opcode x, section 28 line 2

This suggests x is not recognised by sort.  The illegal ramp is odd but 
actually it is not a ramp but constant.  I tink I need to create asimple 
case to understand how it is supposed to work!

**Comment by vlazzarini** [comment]
Try with trapped

**Comment by cscomposer** [comment]
With Boulanger's Trapped also unsuccessful, 
cannot open extract file extract.txt

**Comment by vlazzarini** [comment]
yes, but I think John is already near finding the solution

**Comment by jpffitch** [comment]
I have it working except I am seeing spurious messages

sort: illegal opcode x(78)
swrite: unexpected opcode x, section 18 line 2

Not sure if they matter but have not found out from whence they arise

Version in git is certainly better

**Comment by jpffitch** [comment]
Tryng on trapped isOK too.  Will open a ticket for te spurious x opcode

**Comment by vlazzarini** [comment]
Maybe there is an x being inserted in the score string?

**Comment by jpffitch** [comment]
but there should not be and so far reading the code I cannot see how it 
happens
