### ISSUE TITLE
Csound install problem

### ISSUE THREAD

**Issue by kounich** [csound/csound#866]
Impossible to open the .app.
Someone have a solution. I'm a novice.
Thanks

Process:               CsoundQt-d-py-cs6 [1751]
Path:                  /Applications/CsoundQt-d-py-cs6.app/Contents/MacOS/CsoundQt-d-py-cs6
Identifier:            CsoundQt-d-py-cs6
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           CsoundQt-d-py-cs6 [1751]
User ID:               501

Date/Time:             2017-10-30 23:22:08.749 +0100
OS Version:            Mac OS X 10.11.6 (15G1108)
Report Version:        11
Anonymous UUID:        E50A3D35-D62C-DAFE-FEDF-A87AA77202F1

Time Awake Since Boot: 7700 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: CsoundLib64.framework/Versions/6.0/CsoundLib64
  Referenced from: /Applications/CsoundQt-d-py-cs6.app/Contents/MacOS/CsoundQt-d-py-cs6
  Reason: image not found

Binary Images:
    0x7fff6757e000 -     0x7fff675b5a47  dyld (360.22) <DC81CC9D-651A-3A45-8809-928282052BD3> /usr/lib/dyld
    0x7fff9425b000 -     0x7fff946d1ff7  com.apple.CoreFoundation (6.9 - 1259) <51D1F34F-9FEC-3EF2-8382-2D13D75F845A> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff9ed89000 -     0x7fff9eddafff  com.apple.audio.CoreAudio (4.3.0 - 4.3.0) <EA7D4F3B-062B-3C81-A98C-C89264D00D48> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio

Model: MacBookPro12,1, BootROM MBP121.0167.B17, 2 processors, Intel Core i5, 2,7 GHz, 8 GB, SMC 2.28f7
Graphics: Intel Iris Graphics 6100, Intel Iris Graphics 6100, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1867 MHz, 0x80CE, 0x4B3445364533303445452D45474346000000
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1867 MHz, 0x80CE, 0x4B3445364533303445452D45474346000000
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x133), Broadcom BCM43xx 1.0 (7.21.95.175.1a6)
Bluetooth: Version 4.4.6f1 17910, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
PCI Card: pci1b21,612, AHCI Controller, Thunderbolt@195,0,0
Serial ATA Device: APPLE SSD SM0128G, 121,33 GB
Serial ATA Device: ST2000LM003 HN-M201RAD, 2 TB
USB Device: USB 3.0 Bus
USB Device: USB3.0 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB2.0 Hub
USB Device: Portable USB Drive
USB Device: My Passport 0748
USB Device: Keyboard Hub
USB Device: USB OPTICAL MOUSE
USB Device: Apple Keyboard
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1
Thunderbolt Device: Rugged mini, LaCie, 1, 5.4

**Comment by jpffitch** [comment]
Not my area but it looks as if you have csoundQt but not csound.  csoundQt is a front end, not the csound system.

**Comment by joachimheintz** [comment]
hi -

we will be happy to help, but you are not in the right place here, as 
john mentioned.

please do this:

1. read http://write.flossmanuals.net/csound/a-make-csound-run/ and 
follow the instructions for mac (in short: first install the .pkg, then 
open the CsoundQt .dmg and drag it to the Applications folder).

2. if it don't work, join the CsoundQt mailing list:
https://lists.sourceforge.net/lists/listinfo/qutecsound-users
(it is good to join even if you don't have problems)

then try to describe what you did, and what your system is.

hope this helps, good luck -

	joachim
