### ISSUE TITLE
Csound 6.09.1 install hangs on OS X (10.11.6)

### ISSUE THREAD

**Issue by crimsonWombat** [csound/csound#867]
Finally got around to installing 6.09.1 and the install is hanging on the "verify" when I launch the install package (csoudn6.01.1-OSX-unversal.pkg)

I'm sure if this were a general problem it would have been noticed before but can someone suggest where I should look on my system for the cause?

System OS X 10.11.6 (El Capitan).

Thanks.

**Comment by jpffitch** [comment]
Any progress on this?  /in particular does it fail wit 6.10?

**Comment by kunstmusik** [comment]
Closing as 6.10.0 is now released and no feedback on this issue.  If issue shows up again, please refile issue against 6.10.0 installer.
