### ISSUE TITLE
Skipping scheduled events with strings 

### ISSUE THREAD

**Issue by ErrorThink** [csound/csound#868]
[neumes-debug.txt](https://github.com/csound/csound/files/1439737/neumes-debug.txt)
The problem is that the attached csd renders silence for me. No errors, but it skips all the scheduled events with a string in p4 for the first 297 seconds. The last two events seem to work fine. 

However, if I comment out those last two events, then it happily renders  everything from the beginning.
The lines to comment/uncomment are from  1782 to 1828. I've indicated this in the CSD.

In my tests I found: 
* Adding even more scheduled events after 297 seconds, will still render those events. It's only the first 297 seconds which are silent.
* Replacing compilestr in instr 6 with just a print statement doesn't fix the issue (i.e. nothing prints for the first 297 seconds - so, as Victor noted, probably not compilestr).
* Reducing the size of some of the strings (i.e. keeping the scheduled event, and keeping the string, but deleting all the text in some of the strings), lets it render sucessfully from the beginning.
* Printing all the strings (replacing all the 'schedule 6', with printf_i), seems fine. They all print.

So - it seems to be something about the amount of string being scheduled, even across lots of events. 

This is a large CSD: I've attached it here (as .txt - github complains about .csd), but it's also sent as an attachment to the Csound list.

**Comment by jpffitch** [comment]
Was this fixed?

**Comment by kunstmusik** [comment]
I do not think it has been.

**Comment by vlazzarini** [comment]
not quite sure, I have a vague memory of us realising this was to do with memory, but not sure if we fixed it (@kunstmusik do you know?)

Victor Lazzarini
Dean of Arts, Celtic Studies, and Philosophy
Maynooth University
Ireland

On 18 Nov 2017, at 18:47, John ffitch <notifications@github.com<mailto:notifications@github.com>> wrote:


Was this fixed?

**Comment by vlazzarini** [comment]
I guess the line events memory in linevent.c might be a good place to start.

Victor Lazzarini
Dean of Arts, Celtic Studies, and Philosophy
Maynooth University
Ireland

On 18 Nov 2017, at 18:51, Steven Yi <notifications@github.com<mailto:notifications@github.com>> wrote:

I do not think it has been.

**Comment by vlazzarini** [comment]
Ok, problem seemed to be there alright; pointers getting confused after reallocation. I pushed a fix, which seems to pass the CSD test. Needs to be checked by @ErrorThink
