### ISSUE TITLE
VCPKG Export for Windows build

### ISSUE THREAD

**Issue by stekyne** [csound/csound#870]
Hi all,

I've just seen there is an export command for VCPKG where you can build and package (the packages) for a project and import them afterwards either via cmake toolchain file or as a nuget package.

So we could end up packaging the dependencies into a zip file and incorporate that into the build files. We could leave the current mechanism and leave it optional but I'd imagine most users just want to build csound and not worry about the dependencies.

This solves a couple of problems I think.
1. The build time will be dramatically reduced. 
2. VCPKG folder can grow to be enormous (multiple GB) and it seems unnecessary for most users who just want to develop/use Csound. 
3. There is a problem where the dependencies aren't being moved to the build output directory during the build, we can just copy all the files in this package from the script.

Negatives:
1. Where to store a file that could be 100-200 megs? Has to be publicly accessible. Potentially, the Appveyor build could spit this out and local builds just pull this down from the latest build. I think this makes sense.
2. Updating a dependency means re-generating this package and getting users to re-download it. Not sure how big a problem this is.

@kunstmusik @gogins @csound/developers Any thoughts?

**Comment by gogins** [comment]
I much prefer the existing system which works fine.

The local build script can have an option to skip updating the dependencies.

Best,
Mike

**Comment by stekyne** [comment]
Doesn't seem to be much interest/appetite so I'll close.

**Comment by kunstmusik** [comment]
@stekyne I missed this. I'm all for faster builds, the current system takes a long time.  I wonder though if there aren't things we could improve first before going the route of caching binaries?

**Comment by stekyne** [comment]
It's the nature of VCPKG that makes it slow. It downloads source, builds debug/release mode, caches it locally. I guess it's only really the first build that is very slow so maybe it's not that bad but it definitely eats up a lot of space. 

This exporting feature is kind of the only alternative I can think of but I'm happy to hear other ideas. Outside of getting the dependencies, the build is reasonably fast.
