### ISSUE TITLE
include csound6~ with w

### ISSUE THREAD

**Issue by snobbiggie** [csound/csound#873]

**Comment by snobbiggie** [comment]
...ith Appveyor build of Windows installer. 
csound6~ runs fine with 32bit pd on macOS/OSX, should be the same on Windows?

**Comment by kunstmusik** [comment]
The Mac build is 32-bit and 64-bit (fat binary, i386 and x86_64 combined into same file). This is not possible on Windows to have fat binaries. You would need a completely separate 32-bit Windows build.
