### ISSUE TITLE
CsoundQT and the download bat script for VS?

### ISSUE THREAD

**Issue by rorywalsh** [csound/csound#875]
I wanted to try building a debug version of Csound on Windows. The download script is insisting on cloning CsoundQT. Is this necessary, it's a large repo 200MBs. I've modified my local script but I think it should be optional and disabled by default.

**Comment by stekyne** [comment]
Yeah I completely agree and I've suggested that before. It only needs to be done in the Appveyor.yml file.

**Comment by kunstmusik** [comment]
+1 I have no interest to download CsoundQT as part of my local build.

**Comment by jpffitch** [comment]
Any progress on this?

**Comment by stekyne** [comment]
I'll try and do this this week

**Comment by gogins** [comment]
What format should we use then? I would like to keep the build number in
the release filenames.

Best,
Mike

**Comment by stekyne** [comment]
I'm just going to move th e CsoundQt build and package stufd from downloadDependencies.ps1 to appveyor.yml. The filenames will be the same. Unless I'm missing something.

**Comment by stekyne** [comment]
#883 Fixed in this PR. I'll close the ticket.
