### ISSUE TITLE
build issues with Visual Studio..

### ISSUE THREAD

**Issue by rorywalsh** [csound/csound#876]
Hi guys, I'm a little late to the party here but I'm anxious to get a debug build of Csound going on Windows. I'm having issues with FLTK. I assume I should see an FLTK folder in the staging area after running the download script? I don't. When I call generateProject.bat (I had to set the generator to 2017), I get the following error:

  ```
Could NOT find FLTK (missing: FLTK_LIBRARIES FLTK_INCLUDE_DIR
  FLTK_FLUID_EXECUTABLE)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.8/Modules/FindFLTK.cmake:293 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  C:/Users/rory/sourcecode/vcpkg/scripts/buildsystems/vcpkg.cmake:182 (_find_package)
  msvc/Custom-vs.cmake:4 (find_package)
  CMakeLists.txt:200 (include)

-- Configuring incomplete, errors occurred! 
````

However, when I scroll up through the entire download script output I see no mention of FLTK at all? Any ideas on how to fix this?

**Comment by stekyne** [comment]
It's downloaded via VCPKG. Can you check that it is installed there?
Something like: f:\dev\GitHub\vcpkg\installed\x64-windows\bin

You should have some FLTK binaries in there.

**Comment by rorywalsh** [comment]
Yup. I see them. So I'll need to add these manually to the CMake commands in the generateProject.ps1? I won't get a chance to try this till tomorrow at some stage. I'll let you know. Thanks.

**Comment by stekyne** [comment]
No, they're found via the cmake VCPKG file that gets passed in. It looks like your source code is well out of date actually.

**Comment by rorywalsh** [comment]
That's strange. It's a fresh clone. Maybe I accidentally cloned the master
branch instead of the dev tip. I'll try again later and let you know.

**Comment by rorywalsh** [comment]
Thanks @stekyne , you were right. Switching to the dev branch did the trick.
