### ISSUE TITLE
vbaplsinit broken in csound 6.09

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#877]
it seems that vbap is broken. this simple example produces nonsense output as can be seen in the attached screenshot.

`<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 8
0dbfs = 1

vbaplsinit 2, 8,  0, 45, 90, 135, 200, 245, 290, 315 

instr 1

aNoise rand 1
kAzi linseg 0, p3, 360
a1, a2, a3, a4, a5, a6, a7, a8 vbap aNoise, kAzi, 0, 0
out a1, a2, a3, a4, a5, a6, a7, a8

endin

</CsInstruments>
<CsScore>
i 1 0 4
</CsScore>
</CsoundSynthesizer>`

this is new in csound 6.09; in 6.08 it works.
![screenshot_2017-11-17_18-47-42](https://user-images.githubusercontent.com/2196394/32961398-af715c46-cbc8-11e7-8522-c78b6f9603de.png)

**Comment by jpffitch** [comment]
It looks OK with 4 speakers, so suggests that it is not vbaplsinit but 
vbap that is the problem

**Comment by joachimheintz** [comment]
you are right.  i assumed this because vbap and vbap8 had the same result.
four speakers are ok, five already confused.

**Comment by jpffitch** [comment]
I have made progress.  It is vbaplsinit.  I experimented with 5 outputs an saw an oddity.  Fixing that means 5 works but 8 outputs is still rubbish.  Anyway I have identified the area of concern but too late now until after sleep

⁣Sent from TypeApp ​

**Comment by jpffitch** [comment]
Fixed in git.  It was a confusion (on my part) between the number of speakers and the size of a matrix.

**Comment by joachimheintz** [comment]
i tested and it looks good.
thanks for the quick fix.
