### ISSUE TITLE
Macro with arguments in latest 6.10 (win installer)

### ISSUE THREAD

**Issue by Oeyvind** [csound/csound#882]
Macros with arguments seems not to work in Csound 6.10 (installed from the Win installer of Nov 22).

Test orchestra:

```
<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

    instr 1
#define BLAM(N) #
i$N. = 11
#
$BLAM(2)
print i2
    endin
</CsInstruments>
<CsScore>
i1 0 1
e
</CsScore>
</CsoundSynthesizer>
```

Console output:

```
C:\Cabbage_VST\CabbageEfx>csound macrotest.csd
0dBFS level = 32768.0
--Csound version 6.10 (double samples) Nov 22 2017
[commit: eaaefaa6db4ebe992375642957b0b4068016fc19]
libsndfile-1.0.29pre1
UnifiedCSD:  macrotest.csd
STARTING FILE
Creating options
Creating orchestra
closing tag
Creating score
rtaudio: PortAudio module enabled ...
using callback interface
defining argument `BLAM``N as...#2#
Undefined macro: '$`BLAM``N.'
error: syntax error, unexpected T_OPCODE  (token "i") from file macrotest.csd (1)
 line 1:
>>>i  <<<
Parsing failed due to invalid input!
Stopping on parser failure
cannot compile orchestra
end of score.              overall amps:      0.0
           overall samples out of range:        0
1 errors in performance
Elapsed time at end of performance: real: 0.006s, CPU: 0.006s
```

**Comment by vlazzarini** [comment]
This works
```
instr 1
#define BLAM(N) # i$N = 11 #

$BLAM(2)
print i2
endin
```

**Comment by vlazzarini** [comment]
but note that
```
instr 1
i2. = 11
print i2
endin
```

doesn't

**Comment by Oeyvind** [comment]
It is a little bit unclear for me what you mean by the second example (that does not work), as it is not complete(?). But it is remarkable that the example I posted works if I omit the macro terminator (i$N works, but not i$N.). Maybe that was what you meant?

Now, we should allow (and enforce) the macro terminator, shouldn't we?

**Comment by nwhetsell** [comment]
It may be a little easier to read the example with syntax highlighting:

```csound-csd
<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

    instr 1
#define BLAM(N) #
i$N. = 11
#
$BLAM(2)
print i2
    endin
</CsInstruments>
<CsScore>
i1 0 1
e
</CsScore>
</CsoundSynthesizer>
```

To add syntax highlighting to CSDs in GitHub comments, write

````markdown
```csound-csd
⟨CSD contents⟩
```
````

(Full disclosure: I’m the author of the [language module](https://github.com/nwhetsell/language-csound) that [GitHub Linguist](https://github.com/github/linguist) uses for Csound syntax highlighting.)

As best as I can tell, the orchestra should expand to

```csound
    instr 1

i2 = 11

print i2
    endin
```

Based on http://csound.com/docs/manual/dollar.html, the period following `$N` should terminate the macro name and be excluded from the expanded orchestra.

**Comment by vlazzarini** [comment]
There is no mention of terminator here though:

http://csound.com/docs/manual/define.html

and my example was following that syntax. Maybe @jpffitch can enlighten us?

**Comment by jpffitch** [comment]
Clearly a bug in the csound_pre.lex file.  Will take a lookn now

**Comment by jpffitch** [comment]
Fixed  in git -- and score case as well
