### ISSUE TITLE
Orch. macros bug in ver. 6.10 

### ISSUE THREAD

**Issue by iainmccurdy** [csound/csound#884]
The following code gives an 'undefined macro' error on 6.10 but works fine on 6.09.

```
kNAME1   =   440
#define MACROTEXT(arg)
#
aOut vco2 0.2, k$arg.1
#
$MACROTEXT(NAME)
```
The problem comes from trying to append the 1 on the end of k$arg using a full stop as a separator.

**Comment by jpffitch** [comment]
Already fixed.
