### ISSUE TITLE
Ableton Link Opcodes fail to compile (Android)

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#886]
stevenyi@DESKTOP-7JU96PN MINGW64 ~/work/csound/csound/android
$ ./build-all.sh
NDK_BUILD_COMMAND = /c/Users/stevenyi/work/android-ndk-r11c/ndk-build.cmd
Building in  ableton_link_opcodes
[armeabi] Compile++ thumb: ableton_link_opcodes <= ableton_link_opcodes.cpp
jni/../../../../Opcodes/ableton_link_opcodes.cpp:120:10: fatal error: 'ifaddrs.h' file not found
#include "ifaddrs.h"
         ^
1 error generated.
make: *** [obj/local/armeabi/objs/ableton_link_opcodes/__/__/__/__/Opcodes/ableton_link_opcodes.o] Error 1

**Comment by jpffitch** [comment]
Code says

#if defined(__ANDROID__)
/* Ableton Link preupposes GNU libc, but we are using clang.
  * So we must replace all the ifaddrs code.
  * Pretend that ifaddrs.h has been included:
  */
#define _IFADDRS_H
// Put in our own ifaddrs.h from 
https://raw.githubusercontent.com/libpd/abl_lin
k/master/external/android-ifaddrs/ifaddrs.h.
//////////////////////////////////////////////////////////////////////////////
/*
  * libjingle
  * Copyright 2013, Google Inc.
  *
  * Redistribution and use in source and binary forms, with or without
  * modification, are permitted provided that the following conditions are 
met:
  *
  *  1. Redistributions of source code must retain the above copyright 
notice,
  *     this list of conditions and the following disclaimer.
  *  2. Redistributions in binary form must reproduce the above copyright 
notice,
  *     this list of conditions and the following disclaimer in the 
documentation
  *     and/or other materials provided with the distribution.
  *  3. The name of the author may not be used to endorse or promote 
products
  *     derived from this software without specific prior written 
permission.
......

**Comment by gogins** [comment]
What is our current version of Android Studio?

Best,
Mike

**Comment by kunstmusik** [comment]
Using latest Android Studio Stable (3.0.1).  This has to do with compiling
with NDK though.  The message shows this was built using r11c; r16c (the
latest NDK) causes crashes while compiling for me, but I think it may have
to do with armeabi. (I'm going to propose removal of armeabi on the user
list in a moment.)

**Comment by kunstmusik** [comment]
@gogins I see that the build file for Android ableton link opcodes:

https://github.com/csound/csound/blob/develop/android/pluginlibs/ableton_link_opcodes/jni/Android.mk#L6

is setup to only build on your system.  (I looked and did not see any other instructions on what to do.) 

All of the other opcode libs have their dependencies accounted for with the android/downloadDependencies.sh script.  This allows anyone to build the rest of the pluginlibs. I would suggest removing the hardcoded ABLETON_LINK_HOME in that mk file and set up the project in a way that could be built by others. 

For the moment, I will plan to release Csound for Android SDK for 6.10 without the ableton link opcodes.  If you can provide a fix before Friday I'll be happy to test.

**Comment by gogins** [comment]
I take it you are not building the Csound for Android _app_ that I put in
the Google Play app store. If you are, please let me know and I will fix
the downloadDependencies.sh script. If not, I will still fix it, but later,
when I have time to rebuild the app.

Best,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by kunstmusik** [comment]
@gogins The building of Ableton link opcodes is orthogonal to the the building of Csound for Android app. (The opcode libs are built on their own outside of the building of the app.) 

As mentioned in email exchange with you last year, the setup for Csound Application has a custom keystore--again, setup to work only on your system--that prevents anyone else (like me) from building and running the app. You can see this here:

https://github.com/csound/csound/blob/develop/android/CsoundForAndroid/CsoundApplication/build.gradle#L4-L11

https://github.com/csound/csound/blob/develop/android/CsoundForAndroid/CsoundApplication/build.gradle#L25

I alerted you to this last year and even made a fix so I and others could build it (the commit comment says as much):

https://github.com/csound/csound/commit/85adbf3b6aceffc909d05337830f78f1339f94d7

but you overwrote that shortly after:

https://github.com/csound/csound/commit/47597c188986f3d444de1871283c5bfbbbde3be5

I've since stopped building CsoundApplication regularly considering I did my part to introduce a fix and it was overwritten.  (I do try to build it before releases, and I did try to build yesterday and it again failed with the same issue of keystore.) 

From your last message it looks like this will not be ready for 6.10 so I I will plan to proceed without these opcodes for the release. I suspect it's a minor issue anyways since I don't think anyone uses the opcode libs for their own apps, and would probably only use them via the CsoundApp which you're publishing.

**Comment by kunstmusik** [comment]
This is still broken and does not compile. Reopening.

**Comment by vlazzarini** [comment]
This is a very old issue and it's marked as a bug. We need to move on with it. Any suggestions?

**Comment by stekyne** [comment]
I thought the idea was to remove these kinds of opcodes from the core library and let the author maintain them / integrate them with the package manager?

**Comment by vlazzarini** [comment]
yes, I think that's the idea alright.

**Comment by vlazzarini** [comment]
moved the build to plugins repo so closing this.
