### ISSUE TITLE
After-touch set to init 127, issue with Roli Seaboard

### ISSUE THREAD

**Issue by alcomposer** [csound/csound#888]
I have been using Csound with the Roli Seaboard, and there is an issue with aftouch returning 127 as first value when a Note-On is received.

I have been able to build Csound with Init FL(127.0) changed to FL(0.0) and this fixes the behavior of aftertouch.

It would be great to have a global variable in the .csd that allowed users to set the after-touch init value to 0.0, default would be 127 to keep backwards compatibility.

This is discussed here: http://csound.1045644.n5.nabble.com/Csnd-MPE-aftouch-opcode-td5759523.html
And here: http://forum.cabbageaudio.com/t/roli-seaboard-mpe-with-cabbage/839/43

Cheers,
Alex

**Comment by jpffitch** [comment]
implemented via pull request and in 6.10
