### ISSUE TITLE
 make itype [, xdata1, xdata2, ...]  in OSCsend(A) optional

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#890]
change OSCsend kwhen, ihost, iport, idestination, itype [, xdata1, xdata2, ...] so that  itype [, xdata1, xdata2, ...]  are optional.
Please have a look at http://csound.1045644.n5.nabble.com/Csnd-OSCsendA-td5759524.html#a5759609 for the reason.

**Comment by vlazzarini** [comment]
shouldn't this be

OSCsend kwhen, ihost, iport, idestination[, itype, xdata1, xdata2, ...] 

i.e. itype is optional?

**Comment by tjingboem** [comment]
yes, my OSCsend command was copied from the manual. 
the OSCsend(A) command you mention is the one that was hoping for.

**Comment by vlazzarini** [comment]
Is this about OSCsend or OSCsendA?

**Comment by vlazzarini** [comment]
OSCsend now accepts 4 required args only. OSCsend is much better than OSCsendA, which will be deprecated (don't use it)

**Comment by tjingboem** [comment]
don't know.
There is no manual page for OSCsendA and i have just started to use OSC to
control Ardour on a second computer. So OSC is quite new to me.
Why not OSCsend to start with?

Is OSCsendA using a different system or library?

**Comment by vlazzarini** [comment]
Just use OSCsend, forget about OSCsendA
========================
Prof. Victor Lazzarini
Dean of Arts, Celtic Studies, and Philosophy,
Maynooth University,
Maynooth, Co Kildare, Ireland
Tel: 00 353 7086936
Fax: 00 353 1 7086952

**Comment by Oeyvind** [comment]
But Menno's issue applies to OSCsend too. ... or is that already fixed?

**Comment by vlazzarini** [comment]
yep, committed to git. Tested with
```
instr 1
k1 init 1
OSCsend k1, "127.0.0.1", 10000, "/test/"
endin
```

**Comment by Oeyvind** [comment]
Haha, you're fast!
