### ISSUE TITLE
remove some OSC opcodes?

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#894]
i saw that OSCsendA was deleted.
What are OSCinitM and OSCsend_lo?
Can they be removed as well or should they need a manual page?

**Comment by jpffitch** [comment]
OSCinitM is to start muticast OSC messages

OSCsed_lo is te ol version ofOSCsend usingg liblo; te new version sends 
directly.  e still use liblo for receipt

The second will be removed we we ave sufficiet cofidence in the new code.

i thught OSCiitM was documented; will take a look

**Comment by tjingboem** [comment]
Also, i notice the buchla opcode, but my Csound version is from 12 dec.

There is no manual page yet. This issue is mentioned by Dr. B. :buchla opcode? #59 in the manual issues.
My manual version is from 16 dec.

**Comment by jpffitch** [comment]
This opcode is not working as I do not understand max or pd

**Comment by jpffitch** [comment]
Closing issue as OSCsendA now  deleted and multicast version documented
