### ISSUE TITLE
AppVeyor Windows Installer: Does not install into same path as previous installers

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#897]
As discussed in this csound-devel mailing list thread (https://listserv.heanet.ie/cgi-bin/wa?A2=ind1712&L=CSOUND-DEV&P=35913), the Windows installer on AppVeyor has been reported to install into a different location than prior installers.  Experimentation shows:

1. If the user has Csound already installed, the installer will install into that path (i.e., C:\Program Files\Csound_x64)
2. If the user does not have Csound installed, the installer will install into a different path: C:\Program files\csound-windows-x64

The latter location was noted as being problematic when used due to programs like CsoundQt and tutorial material for plugin building referring to the original path (C:|Program Files\Csound_x64).

**Comment by rorywalsh** [comment]
It looks like [this ](https://github.com/csound/csound/commit/51edf43fb9483aecbd792dbda0743891d0332ec6#diff-6b9fa0d1219340cf714491074c61307b) commit did the damage.

**Comment by stekyne** [comment]
Did this get fixed?

**Comment by rorywalsh** [comment]
Yes. Can be closed.
