### ISSUE TITLE
AppVeyor Windows Installer: CsoundQt virtual keyboard broken

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#898]
As discussed in this csound-devel mailing list thread (https://listserv.heanet.ie/cgi-bin/wa?A2=ind1712&L=CSOUND-DEV&P=35913), the Windows installer on AppVeyor has been reported to include a version of CsoundQt that has the virtual keyboard broken. The cause was identified by Tarmo as being that the version of CsoundQt, built by AppVeyor, does not build using RtMIDI support, thus breaking the virtual keyboard.  

Using pre-built CsoundQt rather than building could be done to fix the issue.

**Comment by stekyne** [comment]
Can we close this if it's related to CsoundQT? Or was it fixed anyway?

**Comment by rorywalsh** [comment]
Fixed by using the official CsoundQT release.
