### ISSUE TITLE
AppVeyor Windows Installer: HTML Manual missing for CsoundQt

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#899]
As discussed in this csound-devel mailing list thread (https://listserv.heanet.ie/cgi-bin/wa?A2=ind1712&L=CSOUND-DEV&P=35913), the Windows installer on AppVeyor has been reported to be missing the Csound Manual.  This is evident by loading CsoundQt and finding the Csound Manual missing.

**Comment by stekyne** [comment]
Was this fixed?

**Comment by rorywalsh** [comment]
Yes. Can be closed.
