### ISSUE TITLE
AppVeyor Windows Installer: HDF5 opcodes not building

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#900]
The AppVeyor build is failing to build HDF5 opcodes. This was discussed in this csound-devel mailing list thread (https://listserv.heanet.ie/cgi-bin/wa?A2=ind1712&L=CSOUND-DEV&P=27424).  The cause is that the downloadDependencies script is trying to download version 1.8.19 of hdf5 which no longer exists from the FTP. AppVeyor continued to build with 1.8.19 until the cache was cleared, and now fails as it does when trying to build locally:

```[00:14:38] Downloading: 
[00:14:38] http://support.hdfgroup.org/ftp/HDF5/current18/bin/windows/hdf5-1.8.19-Std-win7_64-vs2015.zip
[00:14:43] Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
[00:14:43] At C:\projects\csound\msvc\downloadDependencies.ps1:153 char:7
[00:14:43] +       $webclient.DownloadFile($uriList[$i], $cachedFile)
[00:14:43] +       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[00:14:43]     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
[00:14:43]     + FullyQualifiedErrorId : WebException
[00:14:43]  
```

The download/build scripts need to be updated to use a newer version of hdf5 that is available from the server (or possibly modified to use hdf5 from vcpkg).

**Comment by stekyne** [comment]
The problem is using the "current18" URL as that will always be changing. If you go back a few directories, the older versions are there.

https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.20/bin/windows/hdf5-1.8.20-Std-win7_64-vs14.zip

**Comment by stekyne** [comment]
What was the error when trying to use the VCPKG version? I think we should try and get that working. If the VCPKG version is broken then we need to open a ticket and get it resolved.

**Comment by kunstmusik** [comment]
Last I tried, using vcpkg to install hdf5 downloaded some msi you had to
install manually, then you had to run vpckg a second time to install hdf5.
After that, linking with hdf5 failed. I don't have logs from that time.
I'd like it if if we used vcpkg as much as possible.

**Comment by stekyne** [comment]
https://github.com/Microsoft/vcpkg/issues/755

I'm looking at this now. Looks like you need to install MSMPI for the parallel features of HDF5, which we don't even use. We could workaround by installing that dependency before the VCPKG install. I'll try and follow up first though with the VCPKG team.

**Comment by kunstmusik** [comment]
Thanks @stekyne.  I think I tried installing MSMPI automatically on AppVeyor and seem to remember there being some failure, but I can't recall exactly what happened there.  I've subscribed to the VCPKG issue and will follow along there and here.

**Comment by stekyne** [comment]
Well I didn't get a reply. I'm just going to update the source with the right link and maintain the way we have been getting pre-built HDF5.
