### ISSUE TITLE
Csound 6.10.0 requires ALSA to build on Travis CI, segfaults when run

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#901]
Building Csound 6.10.0 from [source](https://github.com/csound/csound/archive/6.10.0.tar.gz) appears to require ALSA, which wasn’t the case with Csound 6.09.1 and earlier. In addition, when attempting to run Csound on Travis CI after installing ALSA, a segfault occurs.

Here’s a Travis CI job that builds Csound 6.09.1, builds a Node.js add-on, and then tests it: https://travis-ci.org/nwhetsell/csound-api/jobs/320441339. All the tests pass.

Here’s a Travis CI job that attempts to build Csound 6.10.0, but the build fails because alsa/seq_event.h is missing: https://travis-ci.org/nwhetsell/csound-api/jobs/320436418.

Here’s a Travis CI job that builds Csound 6.10.0 after running `sudo apt-get build-dep csound`, but a segfault (seemingly related to ALSA) occurs when running tests: https://travis-ci.org/nwhetsell/csound-api/jobs/320439664.

**Comment by vlazzarini** [comment]
It looks like it’s the DSSI opcodes that are asking for ALSA. Maybe it’s a case of fixing
CMake to look for it before attempting to build them.

**Comment by nwhetsell** [comment]
Here’s what I ran to attempt to build Csound 6.10.0 on Travis CI: https://github.com/nwhetsell/csound-api/blob/8139580a00ac2a818583e16c637f23a60129b4b2/.travis.yml#L11-L19.

Where should `-DUSE_ALSA=0` go?

(For the sake of comparison here’s what I’m running to build Csound 6.09.1: https://github.com/nwhetsell/csound-api/blob/016ae409259206cbea92ef1906abc1ff1d6dacae/.travis.yml#L11-L19.)

**Comment by vlazzarini** [comment]
-DUSE_ALSA=0 and -DBUILD_DSSI_OPCODES=0 are cmake options you could try.

**Comment by nwhetsell** [comment]
Passing `-D BUILD_DSSI_OPCODES=0` to CMake [did the trick](https://travis-ci.org/nwhetsell/csound-api/jobs/320471767), thanks.
