### ISSUE TITLE
is OSCsend correct?

### ISSUE THREAD

**Issue by tjingboem** [csound/csound#904]
To try and geta grip on this issue, I used the liblo tools, to find out how we could control Ardour on
the second machine. For example, to stop the moving playhead:
oscsend osc.udp://192.168.1.xxx:3819 /transport_stop
These instructionsare according to the Ardour manual:
http://manual.ardour.org/using-control-surfaces/controlling-ardour-with-osc/

After numerous attempts i found out that in Csound stops the playhead of
Ardour with:
OSCsend     1, "192.168.1.xxx", 3819, "/transport_stop", "i", 1
instead of
OSCsend     1, "192.168.1.xxx", 3819, "/transport_stop"
that i was expecting because of the oscsend util. 

I am aware of the recent change to OSCsend to have the type as well as the value optional.

I'm on Linux Mint, --Csound version 6.10.1 (double samples) Dec 23 2017.

**Comment by vlazzarini** [comment]
maybe the oscsend util sends an  1. OSCsend doesn’t. I don’t know whether the OSC standard inidicates that a 1 should be sent if there are no parameters.

**Comment by vlazzarini** [comment]
There is something here about messages without type args, which are not part of the standard, but sometimes were used. However, there is nothing about their form.

http://opensoundcontrol.org/spec-1_0

I don’t know whether we should providea bespoke solution for Ardour.

**Comment by tjingboem** [comment]
okay, Victor. This is a step forward in that now i can make contact with someone from Ardour and have something to talk about. I'll try to find out if Ardour is 'that special ' and come back with an answer!
thanks sofar!

**Comment by vlazzarini** [comment]
I have sent a message to Robin Gareus about this already.

**Comment by vlazzarini** [comment]
For the time being, I have made OSCsend conform to this, that is, sends a "i" with a payload of 1 whenever there is no type/payload defined. In GIT now. Once we know that is the right way to go or otherwise, we'll change it or keep it that way.

**Comment by vlazzarini** [comment]
Hey Victor,

Ardour does not expect the int but optionally allows it.

This is for compatibility with TouchOSC [1] which always sends a single
parameter (float or int) for all events ( buttons 1 for press, 0 for
release). It's a stupid application of the OSC spec,  but TouchOSC is
very popular :( Ardour actually expects a float, but liblo does
automatically coerce types if a received message matches the path [2].

For Ardour 5.x, the following 3 are all equivalent:

 oscsend osc.udp://localhost:3819 /transport_play
 oscsend osc.udp://localhost:3819 /transport_play i 1
 oscsend osc.udp://localhost:3819 /transport_play f 1

same for /transport_stop.


Does csound assume an empty string when the itype parameter is not given
or just error and not send a message?

The user's non-working example below is

 OSCsend 1, "192.168.1.xxx", 3819, "/transport_stop"

which is not valid. According to [2] it should be

 OSCsend 1, "192.168.1.xxx", 3819, "/transport_stop", ""


It might be helpful to dump the message that is sent (if any). Or dump
the messages on the Ardour side of things:
Ardour Prefs > Control Surfaces > OSC > Settings > Debug


HTH,
robin

[1] https://hexler.net/software/touchosc
[2]
http://liblo.sourceforge.net/docs/group__liblolowlevel.html#ga56c5f1d587c215c27e92e6436e12b1a3
[3] http://www.csounds.com/manual/html/OSCsend.html

**Comment by vlazzarini** [comment]
So it looks like the right thing is to send an empty string for types and no payload.

**Comment by tjingboem** [comment]
Yes! Playbackhead of Adour is running now on the same machine and just did
a quick test:

OSCsend 1, "192.168.1.xxx", 3819, "/transport_stop", ""

this works - great!

I'll will do some tests when i have more time in the days to come and hope
to gather information for a nice Wiki page.
I'll be reporting back here, so please do not close this issue yet.

Thanks Victor!

**Comment by vlazzarini** [comment]
did you recompile Csound from git?

**Comment by tjingboem** [comment]
yes - this morning

**Comment by vlazzarini** [comment]
try again, I've just pushed some changes. Now you should be to just do

OSCsend 1, "192.168.1.xxx", 3819, "/transport_stop"

**Comment by tjingboem** [comment]
rebuild and:
OSCsend 1, "192.168.1.xxx", 3819, "/transport_stop"
and 
OSCsend 1, "192.168.1.xxx", 3819, "/transport_play"

work now with Ardour
