### ISSUE TITLE
Port bob~ filter from PD

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#906]
The bob~ filter from PD is a ladder filter that uses "a differential equation solver to imitate an analogue circuit". 

Source code: https://github.com/pure-data/pure-data/blob/master/extra/bob~/bob~.c
Discussion: http://msp.ucsd.edu/Publications/icmc15.pdf

Suggest opcode signature of:

```csound
asig    bob    ain, xcut, xres, xsat [, ioversample, iskip]
```

*NOTES*
The bob~ filter is compared against other filters in https://github.com/ddiakopoulos/MoogLadders  
This filter is also used as the basis of VCV Rack's VCF filter: https://github.com/VCVRack/Fundamental/blob/master/src/VCF.cpp

**Comment by jpffitch** [comment]
Gleb did this
