### ISSUE TITLE
Problem with double backslash in csoundInputMessage

### ISSUE THREAD

**Issue by ssaue** [csound/csound#908]
When using csoundInputMessage with the following argument ""i 1 0 1 \"C:\\Program Files\\Hadron/\"", the fourth p-field is interpreted as "C:Program FilesHadron/". In earlier version (at least a year ago) this was correctly interpreted as "C:\Program Files\Hadron/" instead.

I looked at linevent.c: Line 340 says if(c == '\\') { cp++; c = *cp;}. Could this be the problem?

**Comment by vlazzarini** [comment]
it could be, but it might break something else, so we will need to look very carefully.

**Comment by vlazzarini** [comment]
removing that line seems to fix your issue, but breaks #861. Awkward one.

**Comment by vlazzarini** [comment]
Ok, I think I fixed this. Tested with
```
<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

instr 1

S1 = p4
printf_i "%s\n", 1, S1

endin

instr 2

scoreline_i "i1 0 1 \"C:\\Program Files\\Hadron/\""

endin

</CsInstruments>
<CsScore>
i2 0 1
</CsScore>
</CsoundSynthesizer>
```
resulting in

```
SECTION 1:
new alloc for instr 2:
new alloc for instr 1:
C:\Program Files\Hadron/
```

**Comment by ssaue** [comment]
This works fine for me. The double backslashes in the windows path are
preserved now. Should I close this issue, or is that the responsibility of
someone else?

Sigurd

ons. 3. jan. 2018 kl. 17:51 skrev vlazzarini <notifications@github.com>:
