### ISSUE TITLE
CMake: Disable linear_algebra opcodes for float build

### ISSUE THREAD

**Issue by berntisak** [csound/csound#910]
Building Csound with floats fails when trying to build the linear_algebra opcodes. I saw in an old email thread that they are double only, so can Opcodes/CMakeLists.txt  be changed from 

`option(BUILD_LINEAR_ALGEBRA_OPCODES "Build the Linear Algebra Opcodes" ON)
`

to something like (I dont know cmake very well, so this might be wrong):

```
if (USE_DOUBLE) 
option(BUILD_LINEAR_ALGEBRA_OPCODES "Build the Linear Algebra Opcodes" ON)
endif()
```

**Comment by gogins** [comment]
Yes, I will create an issue and do this.

Thanks,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

On Tue, Jan 9, 2018 at 5:26 PM, Bernt Isak Wærstad <notifications@github.com

**Comment by gogins** [comment]
Oh, I see you already created the issue. I'm assigning it to myself.

**Comment by fsateler** [comment]
The solution should be to have `check_deps(BUILD_LINEAR_ALGEBRA_OPCIODES USE_DOUBLE)`. Making the option itself conditional is likely to lead to confusion.

**Comment by gogins** [comment]
Thanks,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by vlazzarini** [comment]
done
