### ISSUE TITLE
Impossible installing CSound with Mac OS X 10.12.6

### ISSUE THREAD

**Issue by Galgano56** [csound/csound#911]
I didn't manage to install CSound on my Macbook Air, that uses OS X 10.12.6. Could anyone help me?

**Comment by vlazzarini** [comment]
Maybe you can ask the list and if there is an issue, then open a ticket.

**Comment by Galgano56** [comment]
I'm sorry. What is the place in Csound community where I can get help? I'm
new and don't understand the community rules very well. I looked for an
address where to post my question, but I didn't manage to find any more
appropriate. Up to now nobody seems to have discussed the issue of Csound
compatibility with Mac OS X 10.12.6. Could you help me?

2018-01-10 13:40 GMT+01:00 vlazzarini <notifications@github.com>:

**Comment by jpffitch** [comment]
Join the mailing list at csound@listserv.heanet.ie

If you have difficulty with that mail me at jpff@codemist.co.uk and I will register you

⁣Sent from Blue ​
