### ISSUE TITLE
Crashes on Exit on Windows 10 and does not play audio

### ISSUE THREAD

**Issue by alvarofasrew** [csound/csound#913]
Laptop Lenovo W550S
Windows 10 64 bit
16Gb RAM

**Comment by kunstmusik** [comment]
* What version of Csound is this? (6.10.0 ?) 
* Is this with CsoundQt or Csound commandline?  
* Do you have an example CSD to test here?

**Comment by alvarofasrew** [comment]
Thank you Steven for your quick response.

Version 6.10.0
CsoundQt
Don't have because it crashes every time.

**Comment by kunstmusik** [comment]
CsoundQt probably needs attention from one of its developers.  One thing you might try though is if you previous had Csound installed, it could be that there is something from a previous install that causes a problem now.  If you did have a previous Csound installation, try uninstalling the current Csound, check where you had it installed and make sure there's nothing left, then reinstall Csound and try again. 

One last thing: are you using CsoundQt that is in the installer?  If so, you might try last CsoundQt (I believe 0.9.5) provided by CsoundQt project.

**Comment by vlazzarini** [comment]
Another thing to try:
using ‘run on terminal’ from CsoundQT and
checking if it does the same thing.

**Comment by vlazzarini** [comment]
Opened an issue at CsoundQT. You should follow it from there. It references this one.
https://github.com/CsoundQt/CsoundQt/issues/256

**Comment by alvarofasrew** [comment]
No previous Csound installed on this laptop. And yes I'm using CsoundQt
that is in the installer.

"you might try last CsoundQt (I believe 0.9.5) provided by CsoundQt
project." Gonna try

**Comment by vlazzarini** [comment]
this issue is closed, please comment on the open issue in the CsoundQT repo.
