### ISSUE TITLE
realtime MIDI on Windows..

### ISSUE THREAD

**Issue by rorywalsh** [csound/csound#922]
Looks like MIDI input is not working with the latest Windows release. Neither MIDI interfaces are working, portmidi, or winmme.

**Comment by vlazzarini** [comment]
winmme should be winmm

**Comment by rorywalsh** [comment]
Typo.

**Comment by vlazzarini** [comment]
does not work with winmm either? is the rtwinmm.dll there at all in the plugins dir?

**Comment by rorywalsh** [comment]
My bad, it works with winmm, just not portmidi

**Comment by rorywalsh** [comment]
I've added pmidi.dll to the Windows installer.
