### ISSUE TITLE
Build Fails when CMAKE_C_FLAGS are edited in Custom.cmake

### ISSUE THREAD

**Issue by stephenhensley** [csound/csound#923]
Line 158 of CMakeLists.txt uses the CMAKE_CXX_FLAGS for the C_FLAGS instead of the CMAKE_C_FLAGS.

When building with edited flags (on Raspberry Pi, in my case), the edited flags don't get used by the compiler, and building can fail.

**Comment by vlazzarini** [comment]
thanks for spotting this typo, introduced recently. Fixed now in git.
