### ISSUE TITLE
VCPKG-MSVC: Replace manual builds with more VCPKGs

### ISSUE THREAD

**Issue by stekyne** [csound/csound#926]
Portaudio - 
This package wasn't originally used because it does not contain ASIO as a feature. However, we can manually extract the ASIO SDK into VCPKG and it will build with ASIO support.

Portmidi - 
This package has been added in the last 2 months so we can remove the manual build.

Fluidsynth - 
Currently in the processing of adding it myself to VCPKG. Should be done soon.

Liblo - 
Needs to be added to VCPKG but should be straightforward. 

HDF5 - 
This has been fixed in VCPKG. It (VCPKG) now has feature-packages. This remove the MSPI dependency so we can install the vanilla version without issue.

This will remove a lot of manual builds from the downloadDependency.ps1 script. It also could lead to us adding libcsound as a VCPKG itself. It will automatically pull down the dependencies within VCPKG then. 

There are a few other files that we download so I have to figure out what to do with them. Maybe add them as submodules or something like that.

**Comment by kunstmusik** [comment]
Awesome, thanks so much for looking into this!

**Comment by stekyne** [comment]
@kunstmusik I've nearly got this going. Just with libsndfile, you switched the build to static to get around some issue. Can you remember what it was and what was the test case? Just to ensure I've not re-introduced it.

**Comment by kunstmusik** [comment]
Yes, see these two threads:

http://csound.1045644.n5.nabble.com/Csnd-dev-Windows-Problem-again-with-libsndfile-critical-td5759488.html
http://csound.1045644.n5.nabble.com/Csnd-dev-libsndfile-and-MSVC-build-td5757593.html

**Comment by stekyne** [comment]
Just to update. This is done from Csound's end but there is one issue left in VCPKG. Should reduce the build time and clean it up in general. There will be 13 packages in VCPKG that we make of us of then. It can also be used for other platforms (Mac/Linux) if a full build from source is required.

**Comment by stekyne** [comment]
Will be fixed by #1208. Closing now
