### ISSUE TITLE
i have a question .......

### ISSUE THREAD

**Issue by farhadilaghihosseini** [csound/csound#929]
Hi, i have a question...
how can i take a random number from the fillarray ????

for example....

  iviertelnote = 1
  gkarrayRtm_1[] fillarray  iviertelnote, iviertelnote/2, iviertelnote/3, iviertelnote/4, iviertelnote/5

inster rtm

  ktimes timeinsts 
  isectionDur = 59
  
     ksaxophone_position init 0
  if ktimes >= 2 && ktimes < isectionDur*2 then
       ksaxophone_1  linseg 0, isectionDur*2, isectionDur*2 
         ksaxophone_position = 1
           krtm randomh     =======> ?????  i need hier one of the parameter from (gkarrayRtm)
  endif
endin

**Comment by joachimheintz** [comment]
hi -
this is an issue tracker, not a forum.
please post your question on the csound user mailing list.

**Comment by rorywalsh** [comment]
Or any of the channels listed here:
http://csound.com/community.html
