### ISSUE TITLE
Ableton Link opcodes failing on Windows build

### ISSUE THREAD

**Issue by stekyne** [csound/csound#930]
https://ci.appveyor.com/project/csound/csound/build/6.11.1468

There are a lot of build errors for this project. Either they need to be fixed or else we remove it from the build. Any thoughts on it?

**Comment by vlazzarini** [comment]
is that all opcodes failing?

**Comment by vlazzarini** [comment]
it appears the ableton API might have changed.

**Comment by stekyne** [comment]
Apologies, I was away the last few days. I had submitted a fix for this but didn't seem to pull down the tag correctly. I'll try and get that working and reintroduce it back into the build.

**Comment by vlazzarini** [comment]
sounds good
