### ISSUE TITLE
csound~ and Ableton Live 10

### ISSUE THREAD

**Issue by merlinusambrosius** [csound/csound#931]
I am using Csound 6.07, as csound~ doesn't work with any Csound version after 6.07.  Anyways, Live 10 is out now, and the csound~ Max4Live object doesn't seem to work when you add a device to a track.  However, when you jump into the editor, it works, but only while in the editor.

**Comment by vlazzarini** [comment]
Can you open this in the Csound tilde tracker? It's a separate project.
https://github.com/csound/csound_tilde

**Comment by merlinusambrosius** [comment]
Got it, thanks!
