### ISSUE TITLE
Sound artifact on stereo sample playback

### ISSUE THREAD

**Issue by sorenjakobsen** [csound/csound#935]
The issue is experienced on Windows 10/x64 with the following score and sound file.

```
<CsoundSynthesizer>
<CsOptions>
-o dac
</CsOptions>
<CsInstruments>
sr = 44100
ksmps = 32
nchnls = 2
0dbfs  = 1
instr 1
al, ar loscil3 1.0, 1.2, 123, 1
outs al, ar
endin
</CsInstruments>
<CsScore>
f 123 0 0 -1 "test123.wav" 0 0 0
i 1 0 2
e
</CsScore>
</CsoundSynthesizer>
```

[test123.zip](https://github.com/csound/csound/files/1762691/test123.zip)

**Comment by vlazzarini** [comment]
Thanks. I have it fixed now in GIT. You can try it by downloading the next appveyor-produced installer if you are on Windows.

https://ci.appveyor.com/project/csound/csound

**Comment by sorenjakobsen** [comment]
Thank you, it works!:)
