### ISSUE TITLE
Android: Libfluid Opcodes not working (Invalid instrument number)

### ISSUE THREAD

**Issue by ghost** [csound/csound#936]
I can't get the Libfluid Opcodes to work properly. 
```
CsoundObj csoundObj = new CsoundObj(false, true);

        csoundObj.SetOption("-odac");
        csoundObj.SetOption("--opcode-lib=libfluidOpcodes.so");

        String orc = "sr = 44100\n" +
                "ksmps = 32  \n" +
                "nchnls = 2\n" +
                "0dbfs  = 1\n" +
                "\n" +
                "gienginenum1\tfluidEngine\n" +
                "\n" +
                "isfnum1\tfluidLoad \"/sdcard/Download/sf_GMbank.sf2\", gienginenum1, 1\n" +
                "\t\tfluidProgramSelect\tgienginenum1, 1, isfnum1, 0, 1\n" +
                "\n" +
                "instr 1\n" +
                "  ichannel   = 1\n" +
                "  ikey       = p4\n" +
                "  ivelocity  = p5\n" +
                "\tfluidNote gienginenum1, ichannel, ikey, ivelocity\n" +
                "endin\n" +
                "\n" +
                "instr 100\n" +
                "  iamplitude1 = 7\n" +
                "  iamplitude2 = 7\n" +
                "aleft1, aright1 fluidOut   gienginenum1\n" +
                "                outs       (aleft1 * iamplitude1),  \\\n" +
                "                           (aright1 * iamplitude1)\n" +
                "endin";
        csoundObj.compileOrc(orc);
        csoundObj.startCsound(new File(""));
        String sco1 = "i1 0 3  60  100";
        csoundObj.sendScore(sco1);
        String sco2 = "i100 0 10";
        csoundObj.sendScore(sco2);
```
Csound only gives me

> I/AndroidCsound: insert_score_event(): invalid instrument number or name 1
I/AndroidCsound: insert_score_event(): invalid instrument number or name 100

Am I doing something wrong or is it a bug?

**Comment by gogins** [comment]
Work where? Are you using the Csound for Android app from the Google play
store, or did you build the app, or did you build your own app based on the
Android SDK?

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by ArthusVonCamelot** [comment]
Using the Android SDK. I put the libfluidOpcodes.so in the same folder like the other .so files from the Android SDK. I use the precompiled version from the website.

**Comment by gogins** [comment]
When you say the precompiled libfluidOpcodes.so, you mean a version of this
file that comes with the CsoundAndroid SDK files?

You are not doing any native compilation, correct?

You may need to preload plugin opcodes before you run Csound, like this
from the Csound for Android app:

        // Pre-load plugin opcodes, not only to ensure that Csound
        // can load them, but for easier debugging if they fail to load.
        File file = new File(OPCODE6DIR);
        File[] files = file.listFiles();
        for (int i = 0; i < files.length; i++) {
            String pluginPath = files[i].getAbsoluteFile().toString();
            try {
                System.load(pluginPath);
            } catch (Throwable e) {
                postMessage(e.toString() + "\n");
            }
        }







-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by ArthusVonCamelot** [comment]
Yes, I took the files from the CsoundAndroid SDK files. I tried your code with
`String OPCODE6DIR = context.getApplicationInfo().nativeLibraryDir;`
But it still did not work (same error `invalid instrument number or name`).
Also
`System.loadLibrary("fluidOpcodes");`
did not help.

I don't think loading the library is the problem, since it tells me:
```
I/AndroidCsound: Loading command-line libraries:
I/AndroidCsound:   libfluidOpcodes.so
```
Maybe it's something related to accessing sdcard for loading the sound font?

**Comment by gogins** [comment]
In the Csound for Android app there is code for copying soundfonts etc.
from assets for the app to an accessible directory.  If you have them in
the user Downloads directory it should work. Of course your app has to be
given the right permissions in its manifest.

Regards,
Mike

**Comment by ArthusVonCamelot** [comment]
@gogins This brings me one step further:
```
 final String OPCODE6DIR = context.getApplicationInfo().nativeLibraryDir;

        File file = new File(OPCODE6DIR);
        File[] files = file.listFiles();

        for (File file1 : files) {
            String pluginPath = file1.getAbsoluteFile()
                    .toString();
            try {
                System.load(pluginPath);
            } catch (Throwable e) {
                e.printStackTrace();
            }
        }
        // This must be set before the Csound object is created.
        csnd6.csndJNI.csoundSetGlobalEnv("OPCODE6DIR", OPCODE6DIR);

        CsoundObj csoundObj = new CsoundObj();
        csoundObj.setMessageLoggingEnabled(true);

        csoundObj.SetOption("-odac");
        csoundObj.SetOption("--opcode-lib=libfluidOpcodes.so");

        String orc = "sr = 44100\n" +
                "ksmps = 32  \n" +
                "nchnls = 2\n" +
                "0dbfs  = 1\n" +
                "\n" +
                "gienginenum1\tfluidEngine\n" +
                "\n" +
                "isfnum1\tfluidLoad \"/storage/emulated/0/19Trumpet.sf2\", gienginenum1, 1\n" +
                "\t\tfluidProgramSelect\tgienginenum1, 1, isfnum1, 0, 56\n" +
                "\n" +
                "instr 1\n" +
                "  ichannel   = 1\n" +
                "  ikey       = p4\n" +
                "  ivelocity  = p5\n" +
                "\tfluidNote gienginenum1, ichannel, ikey, ivelocity\n" +
                "endin\n" +
                "\n" +
                "instr 100\n" +
                "  iamplitude1 = 7\n" +
                "  iamplitude2 = 7\n" +
                "aleft1, aright1 fluidOut   gienginenum1\n" +
                "                outs       (aleft1 * iamplitude1),  \\\n" +
                "                           (aright1 * iamplitude1)\n" +
                "endin\n";
        csoundObj.compileOrc(orc);

        csoundObj.startCsound(new File(""));

        Log.d("D", "OPCODE6DIR has been set to: " + OPCODE6DIR);
        csoundObj.sendScore("i1 0 3  60  100");
        csoundObj.sendScore("i100 0 10");
```
I've added the `csoundSetGlobalEnv`. Now it does not show the error message anymore (Invalid instrument number), but there is still no sound and the application crashes.
```
D/CsoundObj: creating new AndroidCsound: 0
D/D: OPCODE6DIR has been set to: /data/app/…/lib/arm64
D/CsoundObj: THREAD START
I/AndroidCsound: setOpenSlCallbacks
I/AndroidCsound: ==set callbacks
I/AndroidCsound: ==callbacks set
D/CsoundObj: Loading command-line libraries:
D/CsoundObj:   libfluidOpcodes.so
D/CsoundObj: graphics suppressed, ascii substituted
D/CsoundObj: 0dBFS level = 1.0
D/OpenGLRenderer: HWUI GL Pipeline
D/CsoundObj: Created fluidEngine 0x0x7cb2752000 with sampling rate = 44100.000000, chorus on, reverb on, channels 256, voices 4096.
D/CsoundObj: Loading SoundFont : /storage/emulated/0/19Trumpet.sf2.
D/CsoundObj: inactive allocs returned to freespace
Disconnected from the target VM, address: 'localhost:8629', transport: 'socket'
```
The above included CSD works with the CSDPlayer from Playstore, but fails with all my self-compiled versions of CSDPlayer.

**Comment by gogins** [comment]
It sounds like maybe your target architecture or compiler flags are not as
good for your device as the ones used for the play store app.

On Mar 7, 2018 17:12, "ArthusVonCamelot" <notifications@github.com> wrote:

@gogins <https://github.com/gogins> This brings me one step further:

 final String OPCODE6DIR = context.getApplicationInfo().nativeLibraryDir;

        File file = new File(OPCODE6DIR);
        File[] files = file.listFiles();

        for (File file1 : files) {
            String pluginPath = file1.getAbsoluteFile()
                    .toString();
            try {
                System.load(pluginPath);
            } catch (Throwable e) {
                e.printStackTrace();
            }
        }
        // This must be set before the Csound object is created.
        csnd6.csndJNI.csoundSetGlobalEnv("OPCODE6DIR", OPCODE6DIR);

        CsoundObj csoundObj = new CsoundObj();
        csoundObj.setMessageLoggingEnabled(true);

        csoundObj.SetOption("-odac");
        csoundObj.SetOption("--opcode-lib=libfluidOpcodes.so");

        String orc = "sr = 44100\n" +
                "ksmps = 32  \n" +
                "nchnls = 2\n" +
                "0dbfs  = 1\n" +
                "\n" +
                "gienginenum1\tfluidEngine\n" +
                "\n" +
                "isfnum1\tfluidLoad
\"/storage/emulated/0/19Trumpet.sf2\", gienginenum1, 1\n" +
                "\t\tfluidProgramSelect\tgienginenum1, 1, isfnum1, 0, 56\n" +
                "\n" +
                "instr 1\n" +
                "  ichannel   = 1\n" +
                "  ikey       = p4\n" +
                "  ivelocity  = p5\n" +
                "\tfluidNote gienginenum1, ichannel, ikey, ivelocity\n" +
                "endin\n" +
                "\n" +
                "instr 100\n" +
                "  iamplitude1 = 7\n" +
                "  iamplitude2 = 7\n" +
                "aleft1, aright1 fluidOut   gienginenum1\n" +
                "                outs       (aleft1 * iamplitude1),  \\\n" +
                "                           (aright1 * iamplitude1)\n" +
                "endin\n";
        csoundObj.compileOrc(orc);

        csoundObj.startCsound(new File(""));

        Log.d("D", "OPCODE6DIR has been set to: " + OPCODE6DIR);
        csoundObj.sendScore("i1 0 3  60  100");
        csoundObj.sendScore("i100 0 10");

I've added the csoundSetGlobalEnv. Now it does not show the error message
anymore (Invalid instrument number), but there is still no sound and the
application crashes.

D/CsoundObj: creating new AndroidCsound: 0
D/D: OPCODE6DIR has been set to: /data/app/…/lib/arm64
D/CsoundObj: THREAD START
I/AndroidCsound: setOpenSlCallbacks
I/AndroidCsound: ==set callbacks
I/AndroidCsound: ==callbacks set
D/CsoundObj: Loading command-line libraries:
D/CsoundObj:   libfluidOpcodes.so
D/CsoundObj: graphics suppressed, ascii substituted
D/CsoundObj: 0dBFS level = 1.0
D/OpenGLRenderer: HWUI GL Pipeline
D/CsoundObj: Created fluidEngine 0x0x7cb2752000 with sampling rate =
44100.000000, chorus on, reverb on, channels 256, voices 4096.
D/CsoundObj: Loading SoundFont : /storage/emulated/0/19Trumpet.sf2.
D/CsoundObj: inactive allocs returned to freespace
Disconnected from the target VM, address: 'localhost:8629', transport: 'socket'

The above included CSD works with the CSDPlayer from Playstore, but fails
with all my self-compiled versions of CSDPlayer.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/csound/csound/issues/936#issuecomment-371269165>, or mute
the thread

**Comment by ArthusVonCamelot** [comment]
I've checked out your project [csound-extended](https://github.com/gogins/csound-extended). This works now on my arm-v7 device, but not on my arm64-v8 device. On that device it only crashes after starting Csound.

```
I/Csound6: Csound is starting...
D/CsoundOboe:: STARTING FILE
I/Csound6: STARTING FILE
D/CsoundOboe:: Creating options
I/Csound6: Creating options
D/CsoundOboe:: Creating orchestra
I/Csound6: Creating orchestra
D/CsoundOboe:: closing tag
I/Csound6: closing tag
D/CsoundOboe:: Creating score
I/Csound6: Creating score
D/CsoundOboe:: CsoundOboe::Start...
I/Csound6: CsoundOboe::Start...
D/CsoundOboe:: graphics suppressed, ascii substituted
I/Csound6: graphics suppressed, ascii substituted
D/CsoundOboe:: 0dBFS level = 1.0
I/Csound6: 0dBFS level = 1.0
W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
D/CsoundOboe:: Created fluidEngine 0x0x7cafabe800 with sampling rate = 44100.000000, chorus on, reverb on, channels 256, voices 4096.
I/Csound6: Created fluidEngine 0x0x7cafabe800 with sampling rate = 44100.000000, chorus on, reverb on, channels 256, voices 4096.
D/CsoundOboe:: Loading SoundFont : /storage/emulated/0/19Trumpet.sf2.
I/Csound6: Loading SoundFont : /storage/emulated/0/19Trumpet.sf2.
W/google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
W/google-breakpad: Chrome build fingerprint:
W/google-breakpad: 6.11.0
W/google-breakpad: 10
W/google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
Disconnected from the target VM, address: 'localhost:8675', transport: 'socket'
```
I will try to solve the issue with that device and than find out whats the problem in this project.
Any further help greatly appreciated.

**Comment by gogins** [comment]
If you could email or share a link to your CSD and SoundFont, I will be
happy to test it.

Thanks,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by ArthusVonCamelot** [comment]
I've replaced my used SoundFont everywhere by the standard shipped with Csound, it can be found in [csound/samples](https://github.com/csound/csound/blob/develop/samples/sf_GMbank.sf2).

**CSD file**
```
<CsoundSynthesizer>
<CsOptions>
-odac
</CsOptions>
<CsInstruments>
sr = 44100
ksmps = 32  
nchnls = 2
0dbfs  = 1

gienginenum1	fluidEngine

isfnum1	fluidLoad "/storage/emulated/0/sf_GMbank.sf2", gienginenum1, 1
		fluidProgramSelect	gienginenum1, 1, isfnum1, 0, 1

instr 2
  ichannel   = 1
  ikey       = p4
  ivelocity  = p5
	fluidNote gienginenum1, ichannel, ikey, ivelocity
endin

instr 100
  iamplitude1 = 7
  iamplitude2 = 7
aleft1, aright1 fluidOut   gienginenum1
                outs       (aleft1 * iamplitude1),  \
                           (aright1 * iamplitude1)
endin
</CsInstruments>
<CsScore>
i 2 0 3  60  100
i 100 0 10
</CsScore>
</CsoundSynthesizer>
```
I suspect it will work for you since the Playstore version also works for both devices.

**Comment by ArthusVonCamelot** [comment]
I've found out the reason for this behavior.

Since I compile this for a 64-bit architecture, the pointers produced in fluidOpcodes.cpp are 64 Bits long (e.g. `fluid_synth_t *fluidSynth`). They get converted to `MYFLT` with the function `void tof(A *a, F *f) `. `MYFLT` is currently a `float` and thus only able to store 4 Byte which are only 32 Bits. The first Byte of the pointer gets ripped of and it tries to access a wrong address.

@gogins How did you solve this problem in the Playstore build, did you change `MYFLT` to `double`? Or is there a possibility to run a 32-bit version on arm64-v8?

**Comment by gogins** [comment]
I don't know but the problem could be solved by defining MYFLT as double.
 Perhaps that is what happened without my realizing.

Thanks for the information,  which i think is correct.

Regards,
Mike

**Comment by phuongtd** [comment]
Hi all,

I'm also having the issue of not being able to load sound fonts with my Android app when running on 64-bit architecture. It runs well on 32 bit but on 64 bit it always show the message "fluid: unable to load ... .sf2". I know very little about C and C++ so could you please help me get the latest .so files as I don't know how to build the libs from C and C++ code?

Thank you very much for your support!

Peter

**Comment by jpffitch** [comment]
Any progress on this issue?  
Sounds like assuming a pointer will fit in a MYFLT is a real problem, and would fail on any build with float

Last comment sounds like a different issue

**Comment by kunstmusik** [comment]
Closing this as out-of-date.
