### ISSUE TITLE
Installing CSound on a RPiZeroW

### ISSUE THREAD

**Issue by Modularius** [csound/csound#939]
Hi, I've been trying to install csound on the Raspberry Pi Zero W. The cpu on the chip seems to be ARMv6 and I've had some trouble getting it to install.

But having got it installed I get "Illegal Instruction" errors and Segmentation Faults.
So I ran in in gdb and got the output:
0xb6cccf20 in csound_aops_init_tables (csound=0x36008)
at home/pi/csound/csound/00ps/aops.c:52
csound->cpsocfrc[i] = POWER(FL(2.0), (MYFLT)i / OCTRES) * ONEPT;

I'm trying to use the C library API with a program I'm making.

Could anyone suggest anything?

Many Thanks,

Daniel Kirk.

**Comment by vlazzarini** [comment]
We need more details and code. By your description you seem to have written a host application using the API and ran it with some Csound code. Can you post the C code for your host program?
What is the Csound code driving this example?

**Comment by Modularius** [comment]
Sure, I'll post my the minimal "working" code. The relevant code is in my csound constructor. Most of this is commented out however, the only csound function is 

    ud.csound = csoundCreate(NULL);

This must be causing the problem.


The rest of my code is:

////////////////   csoundFilter.h

namespace effectLIB {

class csound {
    public:
        csound();
    };

}


////////////////   csoundFilter.c


#include <math.h>
#include <stdlib.h>
#include <algorithm>
#include <cassert>
#include <csound/csound.h>

#include "CsoundFilter.h"

using namespace effectLIB;

typedef struct {
  int result;
  CSOUND *csound;
  int PERF_STATUS;
} userData;

uintptr_t csThread(void *_data);

userData ud;

int finish;
void *ThreadID;
MYFLT *input;
MYFLT *output;

const char *script =
"<CsoundSynthesizer> \n"
    "<CsOptions> -odac </CsOptions> \n"
    "<CsInstruments> \n"
        "instr 1                             \n"
        "ain chnget \"input\"                \n"
        "chnset \"output\" aout              \n"
        "endin                               "
    "</CsInstruments> \n"
    "<CsScore> \n"
        "i1 0 100000"
    "</CsScore> \n"
"</CsoundSynthesizer> \n";

csound::csound()
{
    ud.csound = csoundCreate(NULL);
    /*ud.result = csoundCompileCsdText(ud.csound, script);
    if(!ud.result)
        ud.result = csoundStart(ud.csound);

    if (!ud.result) {
        ud.PERF_STATUS = 1;
        ThreadID = csoundCreateThread(csThread, (void *)&ud);
        csoundGetAudioChannel(ud.csound,"input",input);
        csoundGetAudioChannel(ud.csound,"output",output);
    }*/
}

uintptr_t csThread(void *_data)
{
    userData* udata = (userData*)_data;
    if (!udata->result)
    {
      while ((csoundPerformKsmps(udata->csound) == 0) && (udata->PERF_STATUS == 1));
      csoundDestroy(udata->csound);
    }
    udata->PERF_STATUS = 0;
    return 1;
}

**Comment by vlazzarini** [comment]
you are not giving a CSD, but just orchestra code, therefore the API function you need is a different one, csoundCompileOrc

Victor Lazzarini
Dean of Arts, Celtic Studies, and Philosophy
Maynooth University
Ireland

On 23 Mar 2018, at 12:28, Modularius <notifications@github.com<mailto:notifications@github.com>> wrote:


Sure, I'll post my the minimal "working" code. The relevant code is in my csound constructor. Most of this is commented out however, the only csound function is

ud.csound = csoundCreate(NULL);


This must be causing the problem.

The rest of my code is:

//////////////// csoundFilter.h

namespace effectLIB {

class csound {
public:
csound();
};

}

//////////////// csoundFilter.c

#include <math.h>
#include <stdlib.h>
#include
#include
#include <csound/csound.h>

#include "CsoundFilter.h"

using namespace effectLIB;

typedef struct {
int result;
CSOUND *csound;
int PERF_STATUS;
} userData;

uintptr_t csThread(void *_data);

userData ud;

int finish;
void *ThreadID;
MYFLT *input;
MYFLT *output;

const char *script =
" \n"
" -odac \n"
" \n"
"instr 1 \n"
"ain chnget "input" \n"
"chnset "output" aout \n"
"endin "
" \n"
" \n"
"i1 0 100000"
" \n"
" \n";

csound::csound()
{
ud.csound = csoundCreate(NULL);
/*ud.result = csoundCompileCsdText(ud.csound, script);
if(!ud.result)
ud.result = csoundStart(ud.csound);

if (!ud.result) {
    ud.PERF_STATUS = 1;
    ThreadID = csoundCreateThread(csThread, (void *)&ud);
    csoundGetAudioChannel(ud.csound,"input",input);
    csoundGetAudioChannel(ud.csound,"output",output);
}*/


}

uintptr_t csThread(void _data)
{
userData udata = (userData*)_data;
if (!udata->result)
{
while ((csoundPerformKsmps(udata->csound) == 0) && (udata->PERF_STATUS == 1));
csoundDestroy(udata->csound);
}
udata->PERF_STATUS = 0;
return 1;
}

**Comment by Modularius** [comment]
Do I not need to call "csoundCreate(NULL);"? In the code I posted I didn't even get to the point of compiling anything. In fact that part of the code is commented out as I wanted to trace the source of the error.

**Comment by jpffitch** [comment]
The script is almost a csd, just missing the <> tags for the options, orchedtrZ and score, and the CsSynthesiser

⁣Sent from TypeApp ​

**Comment by jpffitch** [comment]
And there are embedded double quotes


⁣Sent from TypeApp ​

**Comment by Modularius** [comment]
Ahh, it does actually have the tags, they must have been removed when I copied and pasted into the text window.

Unfortunately it's still failing on "csoundCreate(NULL);"

I've screenshotted my ssh output from my RPi, (I can't figure out how to copy and paste from it for some reason).

![image](https://user-images.githubusercontent.com/24866109/37829859-98f7161c-2e98-11e8-8d59-0aeacc85a35d.png)

**Comment by vlazzarini** [comment]
sorry, I see something is commented out. But if you are getting a problem on running Csound in the terminal, then there is something wrong with the build.

Is your c/c++ compiler toolchain installed correctly? Can you compile and run other programs?

**Comment by Modularius** [comment]
I believe so is there anyway I can test it? Sorry I'm a bit of a noob when it comes to compiling from source

**Comment by vlazzarini** [comment]
I think this might be to do with fpu flags. Did you happen to set a Custom.cmake with compilation flags such as -mfpu=... etc?

**Comment by Modularius** [comment]
Sure, when following the build.md instructions for raspberry pi I got the following errors

![image](https://user-images.githubusercontent.com/24866109/37830839-63d25480-2e9b-11e8-9bab-729f4b10a4c6.png)

Many hundreds of errors later I got

![image](https://user-images.githubusercontent.com/24866109/37830816-49de6866-2e9b-11e8-828b-620a1c253234.png)

**Comment by Modularius** [comment]
Yes I edited the Custom.cmake file and got it to compile by adding
set(CMAKE_C_FLAGS, "$(CMAKE_C_FLAGS) -mfloat-abi=hard -mfpu=neon")

**Comment by vlazzarini** [comment]
See this

https://github.com/csound/csound/blob/develop/BUILD.md#raspian

it is possible that NEON support is not available even though it passes the compilation. You can try disabling the vector code, and leave out setting the fpu flags.

**Comment by vlazzarini** [comment]
That is likely the problem. There is no NEON support for rpi zero, so the FPU flag will produce wrong code. Just replace that with

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DPFFFT_SIMD_DISABLE")

and rebuild. Then test the command line again.

**Comment by Modularius** [comment]
Thanks I'll try that.

**Comment by Modularius** [comment]
Thank you it worked! I thought I had tried that before but it still wouldn't compile. Thank you.
