### ISSUE TITLE
tvconv produces no sound

### ISSUE THREAD

**Issue by maxwellpollack** [csound/csound#940]
No matter what I try, I can't seem to get any sound out of this opcode.  OSX 10.13.3

```
<CsoundSynthesizer>
<CsOptions>
-odac
</CsOptions>
<CsInstruments>
sr = 44100
ksmps = 32
0dbfs = 1

instr 1
  asin1 oscils 1,442,0
  asin2 oscils 1,440,0
  asig tvconv asin1,asin2,1,1,256,512
  out asig
endin

</CsInstruments>
<CsScore>
i 1 0 10
</CsScore>
</CsoundSynthesizer>
```

**Comment by vlazzarini** [comment]
I am getting a sound out of your example, although very distorted (since you are convolving two sine waves at full amp). If you have queries about how this opcode is supposed to work, please ask at the forums or discussion lists.

**Comment by maxwellpollack** [comment]
On further investigation, it seems that tvconv only fails when running from the CLI. Using Cabbage to run this score, tvconv produces output normally. Perhaps this is an issue with my configuration?

**Comment by vlazzarini** [comment]
it’s nothing to do with tvconv, your Csound code is problematic. Please use the mailing list or slack forum to ask questions.

**Comment by jpffitch** [comment]
I think there is a problem and I hav identfied a possible explanation. 
Unfortunately for me the code is in C++ which I barely can understand.

**Comment by vlazzarini** [comment]
The problem was in the lates git and did not affect released code. It's fixed now.
