### ISSUE TITLE
Audio error

### ISSUE THREAD

**Issue by noemichloe** [csound/csound#941]
When playing music samples or others, the sound play is broken. The sound is always interrupted and sounds choppy. I would like to know why that is. I tried to change the samplerate and the buffer size too, but unfortunately that did not help. I would like to get help for it! thank you in advance

I have macOS High Sierra 10.13.3

**Comment by kunstmusik** [comment]
@noemichloe I think we'd need more information to determine if this is a bug or not.  Could you provide:

1. Operating System
2. Version of Csound
3. Example CSD/project that illustrates the project
4. Is this using csound commandline tool or some other frontend program (like CsoundQT)?

(You might also get good response asking about this on the user mailing list or on Slack.)

**Comment by gogins** [comment]
What environment (GUI, command line, Web browser)? If browser, what browser?

What operating system?

What model of computer/device?

Attaching a small piece that reproduces the problem would be helpful.

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by noemichloe** [comment]
Thank you for your quick answers!

1. Operating System: macOS High Sierra, Version 10.13.3 
2. Model of computer: MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)
3. Version of CSound: Version 0.9.5 (Using Csound version:6100 Precision:double (64-bit))
4. Web browser: Safari

It is CsoundQT.

Unfortunately, I do not have my own piece to illustrate the problem. I can only bring the piece Kung-Xanadu.csd as an example (or all other songs do not work either). Not even the simple sine wave on "Hello World" works.

**Comment by joachimheintz** [comment]
i think something is wrong with your audio settings in csoundqt.  please 
have a look here:
http://csoundqt.github.io/pages/configuring-csoundqt.html
http://csoundqt.github.io/pages/tips-and-tricks.html

please move to the csoundqt mailing list with further questions:
https://lists.sourceforge.net/lists/listinfo/qutecsound-users

we will be happy to help there, but this is a csound bug tracker.

**Comment by kunstmusik** [comment]
@noemichloe Any news?  Wondering if things were sorted out and if we can close this issue now.

**Comment by noemichloe** [comment]
Hi!
Yes I just had to change the number of threads. now the sound is coming!

Thank you for your help!

Noémi

**Comment by kunstmusik** [comment]
Glad that's sorted out! Will now close this issue.
