### ISSUE TITLE
Csound for Android 6.11.1 file output problem

### ISSUE THREAD

**Issue by ErrorThink** [csound/csound#945]
The Csound for Android app currently in the play store (update April 2 2018) produces audio files that some players have problems playing. In my tests rendering a stereo 44100 wav file, the audio player (Samsung Music Player) fails to open the file, and a message is displayed - "Sorry, the player does not support this type of file". 
Some players such as VLC play the file fine, although the end of the file is slightly truncated. Rendering the file with the same CSD in an earlier version of the Csound app (6.09beta), produces a playable file that seems to occupy slightly more space on disk.

**Comment by ErrorThink** [comment]
One more observation: An Audio Editor (Lexis Audio Editor), complains the files have no fmt chunk.

**Comment by vlazzarini** [comment]
Two things to say: 6.11 has not yet been released so the version you are using may be based on code under development.

The second thing is that without a CSD we can’t check it.

**Comment by vlazzarini** [comment]
@jpff could this be as result of the changes in format codes?

**Comment by jpffitch** [comment]
I doubt this is reated as the changes wete made to reading a file not 
writing.

Sounds more like not closing the file which would rewrite the header 
length.  Need to see an example; is it Android only?

**Comment by ErrorThink** [comment]
OK, CSD below. It's just a trivial oscil output.
A link to download the failing wav file output is here: https://drive.google.com/file/d/1YFHriKqiswlnvV_GeLm18831VG_XKoXn/view?usp=drivesdk

If you like, you can compare it to a wav file generated by the previous release (6.09beta). This one works:
https://drive.google.com/file/d/1OE1y8tbRnRvXvGNQAFrB6r2_7mFwjztH/view?usp=drivesdk

I'm aware the version numbers don't align with Csound releases, and may be considered experimental, but this is The Csound app in the Play Store. I'd rather not build it myself, and, even if I did... I think Android's auto-updates would periodically replace it with the 'official' Play Store version anyway (at least they do with an older apk I've been using).

```
<CsoundSynthesizer>
<CsOptions>
-otestout.wav
</CsOptions>
<CsInstruments>
sr=44100
ksmps=10
nchnls=2

instr 1

ares oscil 10000, 440

outs ares * p4, ares * (1 - p4)

endin



</CsInstruments>
<CsScore>
i1 0 0.15 1
i1 0.25 0.15 0
i1 0.5 0.15 0.5
e
</CsScore>
</CsoundSynthesizer>
 




```

**Comment by ErrorThink** [comment]
Just confirmed file output - and UDP - are working in the new release. Thank you so much for fixing this. Much appreciated!
