### ISSUE TITLE
add optional parameter to mode opcode

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#950]
the fact that "This filter becomes unstable if sr/xfreq < pi (e.g xfreq > 14037 Hz @ 44 kHz)" is sometimes hard to handle in a live performance situation.  inserting a line like

   kFreq limit kFreq, 20, 14000

can easily be forgotten and slows down the performance. (but if this frequency is exceeded, the filter is not only unstable, but crashes in my experience.)

my suggestion is to add an optional parameter icheck:
0 (= defaiult): no check of the incoming frequency
1: incoming frequency > sr/pi are limited to sr/pi
2: incoming frequency > sr/pi are bypassed (no output is produced)

**Comment by jpffitch** [comment]
Sounds sane

⁣Sent from TypeApp ​

**Comment by stekyne** [comment]
In my opinion, if it's known the filter will blow up above some upper limit, the opcode should probably just clamp any higher values to that maximum and not allow the user to override that. When would you ever want it to go above that?

**Comment by jpffitch** [comment]
It is Steven Yi's code so I would like to hear his opiion.

I have some questions....does it always blow up or ould one sray fora 
k-cycle?   Is forcing freq to sr/pi bettwer than silence?  Should it be an 
error?

**Comment by kunstmusik** [comment]
Clamping sounds like a good idea.  Maybe we clamp now by default and add an
argument for idisable_clamp that users can turn on if they need it for
backwards compatibility? (Yes, their pieces would need updating for 6.11+,
but my guess is that this may help more than harm.)

**Comment by jpffitch** [comment]
Joachim, can you try the version in git?  It limits the frequenct one can set.  Hope I got it right.

**Comment by joachimheintz** [comment]
i think it is not yet quite right.  with this code, i get not any more 
an "inf", but a scattered sound and some 3.x as overall amps for the 
second call (= 15000 hz input at sr=44100):

instr 1
aMode mode rand:a(.1), p4, 1
out aMode, aMode
endin
schedule 1, 0, 1, 14000
schedule 1, 1, 1, 15000

**Comment by jpffitch** [comment]
Possibly I confused freq with a ratio.  Will look again soon.

⁣Sent from TypeApp ​

**Comment by jpffitch** [comment]
For 14000 frequency I am seeing my new code not used but output values of 0.75 with 0dbfs at 1.  At 15000 I reset the value to 14036, just below sr/pi and get amplitude of about 3.  Seems OK for me
```
<CsInstruments>
0dbfs = 1.0
sr = 44100
instr 1
kl line p4, p3, p5
aMode mode rand:a(.1), kl, 1
out aMode*0.2
endin
</CsInstruments>
<CsScore>
i1 0 10 10000 15000
e
</CsScore>```

If I set the limit to 100 less than sr/pi it remains reasonably bounded,  but I guess the value should depend on sr in a ratio fashion?

**Comment by joachimheintz** [comment]
the problem is when you have no line.  can you try this score:

i1 0 10 15000 15000

it gives a crackled output for me.

**Comment by jpffitch** [comment]
Yes that is what you asked for.  input is crackly and the resonance 
amplifies it

**Comment by joachimheintz** [comment]
not sure i understand you properly, but this is not what i asked for.

**Comment by jpffitch** [comment]
I mean that is what the csd asks for.  The filter has a large amplitude response well before the sr/pi value.  Version in git clamps at 440Hz below the theoretical limit.


The input is white noise and when the filter becomes hi-pass the crackling of the noise is amplified.  I tried limiting it to sr/pi and it is not infinite but amplifies about 100 fold

I can revert easily, but your original proposal is not what you want!

⁣Sent from TypeApp ​

**Comment by joachimheintz** [comment]
i have pulled from git again and tested, and it works perfectly now for 
me.  i can set 15000 or higher frequencies but the behaviour stays 
stable.  thanks!

should we add a note in the manual which replaces this one:
"Warning
This filter becomes unstable if sr/xfreq < pi (e.g xfreq > 14037 Hz @ 44 
kHz)"

something like:
"As this filter becomes unstable if sr/xfreq < pi (e.g xfreq > 14037 Hz 
@ 44 kHz), xfreq is limited to sr/pi-440Hz internally" (you will put it 
better)
