### ISSUE TITLE
DLL Errors when running CSountQT On Windows 7 64bit

### ISSUE THREAD

**Issue by MelvinPoindexter** [csound/csound#952]
Greetings.
I've downloaded the the Csound6.11.0-Windows_x64-installer.exe, and installed it. When I try loading
CSoundQT, I get the following errors:
"The program can't start because libfluidsynth-2.dll is not missing from your computer"
"The program can't start because python27.dll is not missing from your computer.".
I also get these and other similar dll errors when attempting to run Csound from the command prompt, as well as the Csound command prompt in the windows Programs Menu.

I was able to download a copy of Python27.dll, but I can't for the life of me find any file called
libfluidsynth-2.dll, anywhere on the web using Google. Can anyone tell me where I can download
this dll? IF not is it possible to disable looking for this file and still use csound or csoundqt?

Thanks you for your time.

**Comment by kunstmusik** [comment]
@MelvinPoindexter : I think the python dll should be a result of agreeing to install the python-related stuff in the installer. For the libfluidsynth-2.dll, that looks to be a problem with the installer.  (I'm guessing that the systems that were tested upon had copies of it elsewhere, thus not raising an issue at that point.)  You should be able to look in the opcode library folder and find the fluidOpcodes.dll and delete that as a workaround for the short term.

@stekyne : I see in the AppVeyor log that libfluidsynth-2.dll is being built but I'm not quite sure I understand the history of what's happened here (I have a libfluidsynth.dll, not one with -2 here on my system.)   Any thoughts?

**Comment by stekyne** [comment]
copy : Cannot find path 'C:\projects\csound\msvc\staging\fluidsynthbuild\src\Release\libfluidsynth.dll' because it 
[00:14:57] does not exist. 

Something seems to have changed. I'll keep looking

**Comment by MelvinPoindexter** [comment]
@kunstmusik :
Python error is not a big problem. I could either re-install it, omitting the Python option, or just download the dll from the web and put it in the CSound main program folder. I did the latter. Still getting the libfluidsynth-2.dll though. Thank you @stekyne for looking into it.

**Comment by rorywalsh** [comment]
Here's the output from Csound:
```

WARNING: could not open library 'C:\Program Files\Csound6_x64\plugins64\fluidOpcodes.dll' (-1)
UnifiedCSD:  C:/Program Files/Csound6_x64/doc/manual/examples/fluidEngine.csd
```

And here's the contents of C:\Program Files\Csound6_x64\plugins64:

```
c:\Program Files\Csound6_x64\plugins64>ls
ampmidid.dll  emugens.dll       getftargs.dll       osc.dll         rtpa.dll             stackops.dll
arrayops.dll  exciter.dll       hdf5ops.dll         padsynth.dll    rtwinmm.dll          stdutil.dll
buchla.dll    fareygen.dll      image.dll           platerev.dll    scansyn.dll          stkops.dll
cellular.dll  fluidOpcodes.dll  ipmidi.dll          pmidi.dll       scugens.dll          system_call.dll
chua.dll      fractalnoise.dll  linear_algebra.dll  pvsops.dll      select.dll           virtual.dll
cs_date.dll   framebuffer.dll   liveconv.dll        py.dll          serial.dll           widgets.dll
doppler.dll   ftsamplebank.dll  mixer.dll           quadbezier.dll  signalflowgraph.dll

```

Odd that Csound reports it can't find it. It's size look to be in line with other dlls there.

**Comment by vlazzarini** [comment]
It doesn’t say that. It says it can’t be opened, because the fluidsynth DLL is not packaged

**Comment by MelvinPoindexter** [comment]
@gogins :
I will try that, but I don't have fluid synth installed. It looks to me like it needs to be compiled. Trying to avoid that if possible. I also having troubles finding it on any of the DLL download sites. Is there a link to download it from somewhere?

**Comment by rorywalsh** [comment]
@kunstmusik true.. 
@vlazzarini also true...
@stekyne The Windows installer does attempt to copy the fluid stuff over
https://github.com/csound/csound/blob/develop/installer/windows/csound6_x64_appveyor.iss#L207
But I guess it can't if that folder is somehow empty? 
@MelvinPoindexter You can try grabbing the [Csound6.10 zip](https://github.com/csound/csound/releases/download/6.10.0/csound-windows-x64-6.10.0.zip) and try putting the libfluidsynth.dll into the Csound bin folder. If that doesn't work, perhaps try changing the name as @gogins suggests.

**Comment by stekyne** [comment]
Yeah Rory, the file is missing but fluidsynth as a project seems to be emitting libfluidsynth-2.dll instead. I might have to raise a ticket with the fluidsynth team to see why. The failed copy I pasted earlier could be modified I guess in the short term. 

I think this has shown though that we need to need to have more checks to fail the build on missing dependencies :/

**Comment by MelvinPoindexter** [comment]
Thank you @rorywalsh , I'll give it a try.

**Comment by vlazzarini** [comment]
We've replaced the installer, which should now contain the correct files.

**Comment by MelvinPoindexter** [comment]
Thank you all for your help. @rorywalsh 's suggestion worked. But now that the installer is fixed ( thank you @vlazzarini ), I'll try that again as well, and keep you all posted...probably tomorrow.

**Comment by stekyne** [comment]
Is this fixed so? Might need to be closed

**Comment by rorywalsh** [comment]
The latest installer for Windows ships with libfluidsynth.dll, but the dll needs to be renamed to libfuildsynth-2.dll before the fluid opcodes will run properly.

**Comment by vlazzarini** [comment]
So the replaced installer still has the wrong dll name? How come? The script was changed. Can any of you running windows fix this then? You will need to get a branch off 6.11, fix the script then get the packages off appveyor.

**Comment by rorywalsh** [comment]
Let me do an uninstall and clean install first. Maybe something messed up
in the install. I should have checked before reopening the issue.

**Comment by rorywalsh** [comment]
It seems that uninstalling first resolved the issue. Closing this again.
