### ISSUE TITLE
Csound 6.11.0 macOS installer seems to be for beta version

### ISSUE THREAD

**Issue by nwhetsell** [csound/csound#953]
Csound 6.11.0 for macOS as installed using the installer in https://github.com/csound/csound/releases/download/6.11.0/Csound6.11.0-OSX-universal.dmg seems to be for a beta version:

```
$ csound --version
time resolution is 1000.000 ns
0dBFS level = 32768.0
--Csound version 6.11 beta (double samples) May  9 2018
[commit: 9b981ce5160313175575b24cddb513ab322b5815]
libsndfile-1.0.28
end of score.		   overall amps:      0.0
	   overall samples out of range:        0
0 errors in performance
Elapsed time at end of performance: real: 0.000s, CPU: 0.000s
```

This may be a related issue: calls to `csoundInitialize` result in something like `time resolution is 1000.000 ns` being printed to standard error. This appears to be coming from

https://github.com/csound/csound/blob/9b981ce5160313175575b24cddb513ab322b5815/Top/csound.c#L3806-L3809

**Comment by vlazzarini** [comment]
replaced installer.
