### ISSUE TITLE
segfault in Csound 6.11 when using negative instrument durations with subinstr

### ISSUE THREAD

**Issue by adamfreese** [csound/csound#962]
Minimal working example

```csound
<CsoundSynthesizer>

<CsOptions>
-odac
</CsOptions>

<CsInstruments>
sr = 44100
kr = 4410
ksmps = 10
nchnls = 1
0dbfs = 1

instr 1
  aMono oscil 1/6, p4, 1
  aLeft = aMono
  aRight = aMono
  out aMono
endin

instr 2
  aMono subinstr 1, p4
  out aMono
endin

</CsInstruments>

<CsScore>

f1   0  4096  10   1

t 0 192

i2      0    -1     300
i.      +     1     200
i.      +     .     100

</CsScore>
</CsoundSynthesizer>
```

Expected behavior: three subsequent tones at the specified frequencies.
Observed behavior: segfault at the start of the 100 Hz tone.

Using Csound 6.11 on Linux. Songs that played in 6.10 are now segfaulting in 6.11. It seems (from constructing the minimal example) that the segfault occurs when (1) there is a negative p3 value followed by a positive p3 value and (2) the positive p3 valued tone is followed by any other tone (negative or positive p3 value).

I use negative p3 values for glissandi. I've tried using event_i instead of subinstr as a workaround, but with event_i it seems once a single negative p3 value is used, tival returns 1 for every subsequent tone in the same instrument (even if it's in a group of untied notes). But I think this is a separate bug and I still need to construct a minimal example.

**Comment by vlazzarini** [comment]
It’s an odd use of + with a negative p3 (+ means pp2 + pp3, and in this case would give a -1 start time).

Does the problem go away if you don’t use subinstr?

**Comment by vlazzarini** [comment]
Now got to the bottom of this with better diagnostics and I believe it's fixed in git develop.

**Comment by adamfreese** [comment]
Yes, the problem is fixed in the git develop.

**Comment by vlazzarini** [comment]
thx for confirming it.
