### ISSUE TITLE
Appveyor: Create script to find VC redist directory to avoid build breakages

### ISSUE THREAD

**Issue by stekyne** [csound/csound#965]
Currently the VCredist folder is hardcoded in appveyor.yml. The packaging of the build will break whenever appveyor will update the VS version. There needs to be an automated way to find the right folder. It should just be a case of looking in the folder "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Redist\MSVC\" and whatever single folder is there (or largest version number) should be appended to make the path.

**Comment by kunstmusik** [comment]
@stekyne I think I've fixed this with https://github.com/csound/csound/commit/1fb73f3a0eebb64f19cc3d0ed03221c5c7a9316c, https://github.com/csound/csound/commit/7419b7c689481b2ccedc875137b093e2ffc8f23f, and https://github.com/csound/csound/commit/0d6f09774299688736be5bff940ceb0f92e6ec47.  Could you confirm if my change is what you were thinking for this issue?  If so, let's close this.

**Comment by stekyne** [comment]
Oh nice, looks good to me!
