### ISSUE TITLE
Problem with compiling files with csound~ in Max/MSP

### ISSUE THREAD

**Issue by RaphaelVilani** [csound/csound#968]
Hello,

I'd like to ask for help in a strange issue that I'm having with the csound~ 1.1.3 object.

The problem is that any .csd file I try to open with the csound~ object cannot be compiled. The Max console shows the following message: 

csound~: UnifiedCSD:   [The directory of the .csd, but, for some reason, always with a different mistake, like an extra or missing slash, an extra letter, so on...]
csound~: Reading CSD failed ... stopping 
csound~: csoundCompile() failed.

When I double click the object it tells me the following:

csound~: Could not convert [the directory, but again, with a random mistake] to FSRef.

Now, what I found specially strange is that, using the help file of the csound~ object, all seems to work fine, but if I change the .csd file, the problem reapears (even if I change to an exact copy of the .csd used in the help file)
If I just copy and paste the hole help file in another patch, it stops working and the "Could not convert to FSRef problem"  message appears again.

Can anyone help me?

This is happening in a Mac 10.12.3, with Max 7.3.5 and, as I said, the csound object is the 1.1.3, with Csound 6.04 installed.

Thanks in advance!!

**Comment by vlazzarini** [comment]
Please open a ticket in the csound tilde repository: https://github.com/csound/csound_tilde.

This is for Csound issues only
