### ISSUE TITLE
digiIOBela troubles

### ISSUE THREAD

**Issue by giuliomoro** [csound/csound#975]
This is using the csound-6.11.2-bela.deb provided by  @vlazzarini  today which adds support for digiIO.

@thetechnobear said:
> Im a little confused on the syntax, as Im not sure Csound has pass by reference, 
> i.e. for read would you not need
> 
> ksig digiIOBela kinsig, kpin, kdir
> 
> so something like
> 
> kDummy digiIOBela 0, 2, 0 ; read
> kDummy digiIOBela 0, 2, 1; write
> 
> anyway, Ive tried both
> digiIOBela kDummy, 2, 0
> kDummy digiIOBela 2, 0
> 
> and both appear to be failing....
> 
> unfortunately I dont see any errors (as seems normal with csound) , rather I can tell because the rest of the instrument is not going anything. 
> (i.e. as far as i can tell, if compilation fails due to syntax errors/unknown opcodes, then the instrument fails to get created)
> 
> do you have a link to your source code, perhaps then the syntax will make more sense to me :)
> 
> UPDATE: actually Ive just found there are errors in the console log, so Im going to look at those see if I can work out whats wrong

**Comment by vlazzarini** [comment]
There was a problem with argument count (I had 2 when I needed 3). I have sent in a new deb package to Giulio.

The syntax is

```
digiIOBela ksig, kpin, kdir
```

the first parameter has to be an existing variable if direction is 0 (input from Bela):
```
kdata init 0
digiIOBela kdata, 2, 0
// kdata now has the data from the pin
```

**Comment by giuliomoro** [comment]
Here's the package, however there is a known bug with the kontrol rate one, that I just emailed to Victor. The audio rate should work though.

[csound-6.11.2-bela.deb.zip](https://github.com/csound/csound/files/2180217/csound-6.11.2-bela.deb.zip)

**Comment by vlazzarini** [comment]
Is this bug to do with pinModeOnce vs pinMode? I think that is alright (see my email reply)

**Comment by vlazzarini** [comment]
This is an update using pinMode() for k-rate, which addresses the issue above

[csound-6.11.2-bela.deb.zip](https://github.com/csound/csound/files/2180260/csound-6.11.2-bela.deb.zip)

**Comment by TheTechnobear** [comment]
still seem to be getting same issue

[code]
		kPin = 2
		kDir = 1
		kSig = 0 
		digiIOBela kSig,kPin,kDir
[/code]


Unable to find opcode entry for 'digiIOBela' with matching argument types:
[mFound: (null) digiIOBela kkk


[code]
		aPin = 2
		aDir = 1
		aSig = 0 
		digiIOBela aSig,aPin,aDir
[/code]		

[mUnable to find opcode entry for 'digiIOBela' with matching argument types:
[mFound: (null) digiIOBela aaa


root@salt:~# ls -la /usr/bin/belacsound 
-rwxr-xr-x 1 root root 154916 Jul 10 11:52 /usr/bin/belacsound

**Comment by vlazzarini** [comment]
I am sorry, I had a couple of typos in the code that caused this. I think this might be OK now
[csound-6.11.2-bela.deb.zip](https://github.com/csound/csound/files/2180946/csound-6.11.2-bela.deb.zip)

**Comment by giuliomoro** [comment]
great I am adding this `deb` to the Bela source now. Mark, Victor, if you want to put together an example that uses this feature, please make a pull request on the Bela `dev` branch

**Comment by vlazzarini** [comment]
Thanks for this @TheTechnobear and for bearing with me. I don't have a Bela here to test things so I can't run the code I compile.

**Comment by TheTechnobear** [comment]
no worries @vlazzarini tricky to code blind :) ,  thanks for doing this and so quickly 👍
