### ISSUE TITLE
csoundrc not being sourced

### ISSUE THREAD

**Issue by spinnylights** [csound/csound#980]
With the latest commit (65c1341 at this time), it seems that my .csoundrc in my home folder is not being sourced. This was working as of commit 42e8567. I'm getting around it with a shell alias but it would be nice to use the proper feature.

Its contents are "-B 4096 -b 2048 -+rtaudio=jack". I'm using Arch Linux kernel v. 4.17.5.

**Comment by jpffitch** [comment]
It seems to work for me.

You say .csoundrc but it has used .csound6rc ever since csound6; was .csoundrc in csound4 and 5

Please confirm that this is a typo.

**Comment by spinnylights** [comment]
Ah, okay, thanks, that was my issue—I was using a .csoundrc. I wonder why it was working before—maybe I set something up I don't remember?

Would y'all accept a pull request over at csound/manual to make this more clear? I only see the change specified explicitly in the csound6 release notes, and notably not in the "Command Line Parameter File" section.

**Comment by jpffitch** [comment]
Always happy to get manual corrections/improvements.

⁣Sent from TypeApp ​
