### ISSUE TITLE
name collision: extract and libextractor

### ISSUE THREAD

**Issue by dvzrv** [csound/csound#985]
[GNU libextractor](https://www.gnu.org/software/libextractor/) also ships an executable named `extract`.

As they both end up in `/usr/bin` on Arch Linux, [this leads to a name collision](https://bugs.archlinux.org/task/59193).

What is the use-case for csound's extract? Can I just rename it on packaging to something else (e.g. `csound-extract`), or is the executable expected to be around for some other functionality to work as intended?

**Comment by jpffitch** [comment]
extract has been so called  for decades!  The name of the bnary is 
unimportant but the name of the utility (as in -U extract) is built into 
te calling mechanism.

Actually I think we should review all the names of the utilies an helper 
progrms.

**Comment by jpffitch** [comment]
Looking more closely at the case of extract yes you can safely rename it, or even delete it if you do not want it.

I have opened a discussion on renaming in general

**Comment by dvzrv** [comment]
@jpffitch thanks for the fast feedback! I will rename it to `csound-extract`.
