### ISSUE TITLE
Score calculation problem

### ISSUE THREAD

**Issue by Excentertex** [csound/csound#986]
The  following statement:

`i 107		0		27.4			16000	[44100/@9472680]	10	0
`
Is converted into the following (tested with csound -t 0):

`i 107 0x0p+0 0x0p+0 0x1.b666666666666p+4 0x1.b666666666666p+4 16000 0 10 0
`
Apart from the hex output, it also shows that the calculation results in 0. Replacing it by hand with 0.00262856483459 yields the correct result. This behaviour has changed as this used to work correctly.

Used CSound version: 6.12 beta.

-D-

**Comment by jpffitch** [comment]
Same error as before I think; trucation in calculation.  Will loo
Hex output looks correct to me

**Comment by Excentertex** [comment]
In another score file, I have yet another calculation error. No idea if they are related or not.

The following statement compiles correctly:

`#define J #0#  ; bypass loop control
i 112 [ 5+$J*4 ] 0.2   [ 8000-$J*200 ] 1000 2 100 0 0 19768`

But this one immediately causes a segfault:

`i 112 [ 5.234+$J*4 ] 0.2   [ 8000-$J*200 ] 1000 2 100 0 0 19768`

Of course, I ruled out instrument and table problems.

If needed I can provide both sourcefiles in full.

-D-

**Comment by Excentertex** [comment]
Confirmed to be reproducible on many more source files with FP arguments in [ ... ] constructs.

**Comment by jpffitch** [comment]
A number of internal problems accumulated to create this.  I think I have 
it patched, but there may be a better way.  Please test from github

**Comment by Excentertex** [comment]
Just a thought on "there might be a better way": would it be a valid solution to revert back to %g *and* increase buffer size for snprintf to appropriately fit large FP numbers? (I see you increased to 28 characters anyway).

**Comment by Excentertex** [comment]
Fixed for now.
