### ISSUE TITLE
csound 6.11.0 source tarball changed!

### ISSUE THREAD

**Issue by dvzrv** [csound/csound#989]
I have downloaded and packaged csound 6.11.0 for Arch Linux some time in May (file time stamp is from May 13th).
However, [the current source tarball](https://github.com/csound/csound/archive/6.11.0.tar.gz) is not the same anymore! My file timestamp from May 13th also makes me wonder, as the supposed release date is May 15th. 
@vlazzarini did you somehow upload a new version of it? I'm curious to find out, as I now have potentially packaged some garbage for users and that would be pretty bad. Worst case the current (or my?) tarball is compromised, best case, someone just re-uploaded.

My 6.11.0:
`5e75c3c2ecbc02f5f190280682d60540d4181bd333592bcecfb34efdd725e6c841379706d30d5666e0deed575c5b8de9f1ae84a78dfb213480b149904313ef65  csound-6.11.0.tar.gz`

Current 6.11.0:
`0261a9ed83d1545c4a29ab1e64dfe6ee72b3c4529b8c2107b81d6753a3fd76614aca12d59fc6d59b5cc093be4f631e41fdb3d57121bc4eeb67d6ca44c3ad01ad  6.11.0.tar.gz`

**Comment by dvzrv** [comment]
Looking at this [release note merge](https://github.com/csound/csound/commit/b7cfc7ec9f7f684a935a79944ab964ceb16b162d), I guess I can opt for "someone changed the uploaded file", which leads me to the question: why?

**Comment by vlazzarini** [comment]
not sure because the source tarball is produced automatically by github from a git tag, so I don’t think anyone uploaded it manually.

Are the numbers in the file name the git commit hash?

**Comment by dvzrv** [comment]
@vlazzarini no, those are sha512sums of the files (mine is just renamed by the build system during download)

**Comment by dvzrv** [comment]
Judging from the diff of the two (in attachment), the current version lacks all the vst4cs things, but were still around in my version.
This shouldn't happen and can only be explained by someone force pushing a tag or similar.

[current.txt](https://github.com/csound/csound/files/2255346/current.txt)

**Comment by vlazzarini** [comment]
Ah, I see. Yes, I think what happened was that we needed to rewrite history to remove all the VST stuff in the repo. I guess that might have made github update the released tarball automatically. 

I'll tell you, this VST stuff has caused major difficulties for us. We're still trying to deal with issues in the develop branch commit history caused by the fact that we had to scramble to get rid of it (or face removal).

**Comment by dvzrv** [comment]
Oh shite... you were also threatened by Steinberg???
They also forced @x42 to remove free headers from his software.

Major annoyance... guess they *really* want people to use their new fancy BS.
Certainly not me....

**Comment by x42** [comment]
I only ever shipped vestige (not Steinberg's VST SDK) and was likely hit as false positive (the vestige header was named aeffectx.h). The only thing I did was rename the file (to vestige.h) and clarify that it has been cleanly and legally reverse engineered.  In my case the DMCA was not enforced, the repo is still online as-is.

Some further discussion on the subject:  https://github.com/zeromus/openvi/issues/1

**Comment by dvzrv** [comment]
Well, guess I'll rerelease the package then. However, a patch-level bump would've been nice for this, but probably not so easy under these circumstances!

**Comment by vlazzarini** [comment]
yes, we had a github takedown notice with 24 hours to act. I went quickly and cleared the repo, but some devs recommitted stuff without noticing and I had to rush to do it twice more before the period expired. Now we have a set of duplicate commits in develop that we'll have to cherry-pick before we release 6.12.

**Comment by vlazzarini** [comment]
btw, I think we might have had vestige as well (I don't know for sure, since it did not come from me originally), but I did not want to contest it. In general, I was never happy with any of that in the Csound repo leaving us hostage to fortune.

**Comment by jpffitch** [comment]
vestige is GPL so problematic.

**Comment by gogins** [comment]
On Linux you can use use CsoundVST and the vst4cs opcodes from
https://www.dropbox.com/s/hl3pamim4942jq9/csound-vst-0.2.0-Linux.tar.gz?dl=0
.

I think it would be a good idea to implement a Csound LV2 plugin and enable
Csound to host LV2 plugins. The LV2 license is compatible with the Csound
license. Support for LV2 seems to be fairly widespread on Linux. Notably,
the great Pianoteq piano emulation runs on Linux as an LV2 plugin (in
addition to running as a native VST plugin).

Regards,
Mike

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com
