### ISSUE TITLE
request for 'schedulek' opcode

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#994]
it would be nice to have 'schedulek' as k-time variant for the 'schedule' opcode.

currently we have to use the 'event' opcode which has two disadvantages:
1. it cannot take strings as p-fields
2. we have to write "i" to generate a score event

also for teaching csound i'd appreciate to have the consistency in names of using schedule/schedulek  rather than schedule/event.

**Comment by vlazzarini** [comment]
Isn’t there schedkwhen etc already?

**Comment by jpffitch** [comment]
```

 schedkwhen — Adds a new score event generated by a k-rate trigger.
schedkwhennamed — Similar to schedkwhen but uses a named instrument at init-time.
schedule — Adds a new score event.
schedwhen — Adds a new score event.
```

**Comment by joachimheintz** [comment]
yes but schedkwhen is much more complicated.  the request is to have a 
simple

	schedulek  kinsnum, kwhen, kdur [,kp4] [,kp5] [...]

**Comment by jpffitch** [comment]
Firing a note every k-cycle does seem unnecessary

**Comment by joachimheintz** [comment]
the request is to have a substitution of event "i".  again these are the rationales:
1. main reason: event "i" cannot handle strings as p-fields:
  event "I", "my_instr", 0, 1, "my_string"
  is not possible, whereas
  schedule "my_instr", 0, 1, "my_string"
  is, and a proposed
  schedulek "my_instr", 0, 1, "my_string"
  could handle this as well.
2. readability of code.

**Comment by kunstmusik** [comment]
> Firing a note every k-cycle does seem unnecessary

I think the opcode proposal is not intended to be used every k-cycle, just at perf-time, probably within a k-rate conditional.

**Comment by jpffitch** [comment]
I have implemented scheduek opcodes as an experiment.  Can you see if they work OK for you.

**Comment by jpffitch** [comment]
I will close after the holidays if I do not hear to the contrary.
