### ISSUE TITLE
chnclear with multiple arguments

### ISSUE THREAD

**Issue by joachimheintz** [csound/csound#995]
it would be handy to write
chnclear "out1", "out2", "out3", "out4"

currently chnclear can only take one argument, so we have to write instead
chnclear "out1"
chnclear "out2"
chnclear "out3"
chnclear "out4"

**Comment by joachimheintz** [comment]
i think something is wrong.  it is a bit hard to say because it seems to 
work on command line, but it hangs csoundqt.

this happens for any simple usage of chnclear, so also not using the new 
feature.  for instance the manual example of chnclear.

when i checkout the previous git, it works.  so i am pretty sure it is 
because of your code, but cannot say more, as i do not get any error 
messages.

**Comment by jpffitch** [comment]
It runs the manual example and the manual example enhanced to clear two 
channels.  I do not have csiunrQT so cannot test that.  If I understad you 
correctly it worked from the command line -- and that is all I have

If it hangs I suspect the channel locking/unlocking

Ca csoudqt be run under gdb or valgrind?

**Comment by jpffitch** [comment]
Try new  version.  I saw some problem when I tried valgrind
