### ISSUE TITLE
Windows: Add Faust to Windows build

### ISSUE THREAD

**Issue by stekyne** [csound/csound#997]
Faust opcodes only work on Linux/OSX at present, should be possible to build and include on Windows also.

**Comment by maurocsound** [comment]
It's possible and it works. I used the "MSYS2 MinGW 64bit" environment to build faust lib. Let me know if you need help.

**Comment by maurocsound** [comment]
I don't know if this could help but I made a [zip file](https://github.com/csound/csound/files/2320956/Faust.DLLs.for.Csound.zip) with all the DLLs necessary to make faust opcodes work with the current Csound6 64bit binary package.

These are the DLLs that should be placed inside the C:\Windows\System32 dir:

libfaust.dll
LLVM.dll
libffi-6.dll
libgcc_s_seh-1.dll
libwinpthread-1.dll
libstdc++-6.dll

Instead, "faustops.dll" should be placed in C:\Program Files\Csound6_x64\plugins64

**Comment by maurocsound** [comment]
Did you know this? https://sourceforge.net/projects/pthreads4w/
It's an opensource implementation of the POSIX threads API for Windows, so that you shouldn't change your source code to compile it with MSVC.

**Comment by vlazzarini** [comment]
That's up to the Windows maintainers. They call the shots on which threading library to use. I am just making it easier for them to build this code with MSVC.

**Comment by kunstmusik** [comment]
@maurocsound We originally (pre-Csound 5) used native Windows threads. In Csound 5 we switched to using pthreads everywhere.  We found that actually caused problems:

1. When dynamically linking, Csound API based applications could cause crashes when loaded within host applications that also used pthreads which may have been compiled with different settings.
2. Performance is better with native Windows threads. 
3. Csound 6 was easier to compile with Visual Studio when using native threads. (One less dependency to deal with.)

In Csound 6, when we moved to compiling with Visual Studio, we removed dependency on pthreads and reintroduced Windows-specific wrappers for our Csound Thread API.  Even though we could get around issues when statically compiling pthreads into our build artifacts, in general I think we're safer off in not having a dependency on pthreads for Windows.  If building a library with pthreads, best to do so statically.

We should also consider moving these opcodes to a separate project at some point, once we can get back to working on the package manager as well as looking at the separate installer build project.

**Comment by maurocsound** [comment]
@kunstmusik : ok, thanks for the info. 
But what you mean when you say "We should also consider moving these opcodes to a separate project at some point"?

**Comment by vlazzarini** [comment]
He means that we will eventually place them on a separate repository, with its own CMake script etc and the opcodes will become an add-on to the system. We have done this with some parts of the codebase, but have not yet moved opcodes out of the tree. Eventually we might move almost everything that has extra dependencies (fluidsynth, python opcodes, widget opcodes, etc.). Possibly this will happen in Csound 7.

**Comment by maurocsound** [comment]
Ok, it makes sense. So there will be an installer for Csound7 with only the internal opcodes and then various downloadable plugins for the opcodes that needs extra dependencies?

**Comment by kunstmusik** [comment]
Pretty much. The idea is that we make it easy for 3rd parties to create and
release plugins on their own and make it easy for users to access and use
those plugins.  This also frees up core developers to work on the core and
not spend their time debugging and fixing code that they don't know or want
to spend time on.

The model to use package managers is pretty common (e.g., Pure Data with
Deken, SC3 with Quarks). We can look at those communities to know what to
expect when we we get the package manager system going.  (Also, can just
look at how Linux distributions package Csound and various plugins into
packages today.)

**Comment by stekyne** [comment]
I've managed to build the current Faust tip with CMake using MSVC. They haven't got an official version released since starting the switch from whatever the last build system was so not quite sure what to do there. Also another problem with not having llvm-config in the prebuilt binaries. This means having to build llvm locally. Further complication to the process. I might just upload the binaries somewhere online to allow our build to work for this.

I assume the llvm backend is required? Is there a version of Faust that is required or will the latest do?

**Comment by stekyne** [comment]
I've found a possible solution for the build issue. llvm-config is required for Faust to build but it doesn't come with the official llvm distribution on Windows. https://github.com/vovkos/llvm-package-windows contains the correct binaries. For the appveyor build, this will have to be downloaded, extracted and added to the path to be used in the build. 

The build instructions themselves are described with this: https://github.com/grame-cncm/faust/issues/209.

**Comment by stekyne** [comment]
https://github.com/csound/plugins/actions/runs/5495329913 I've added the Faust opcodes to the plugins repo. Seeing as they now release binaries themselves for Faust, it was easy to add.
