### ISSUE TITLE
website and bug report as last resort

### ISSUE THREAD

**Issue by jimlynnjulian** [csound/csound#998]
Hello,

   This is not a Csound bug report. This is a csound web site bug report.
A problem at : "http://csoundjournal.com/articleIndex.html"
The Issue index page attempts to link to the above page but fails.
The link used, has a Capital 'A' in article. The real page does not, as illustrated above.

I attempted to locate a contact email address but found none on that site or on csound.com.
Most sites have a webmaster's email address at the bottom of a page, or elsewhere.

I brought up the csounds.com page and found three links with missing images.

I am running a Dell laptop with a current Win10Pro and the current Chrome browser.
My laptop is using the 2.5Ghz band of my wifi on a 60Mbs cable modem.

Hope this helps.
Jim Julian
Using Csound, off and on, for over fifteen years.
Thanks for the software.
Feel free to close this, having read the content.

**Comment by jpffitch** [comment]
Just to clarify, the link on http://coundjournal.com/articleindex.html is wrong.  Maybe Steven has access or Iain?




⁣Sent from TypeApp ​

**Comment by kunstmusik** [comment]
I have access and have pushed a fix. I'll let Jim and Iain know about the change too. Thanks @jimlynnjulian for the report!
