### ISSUE TITLE
Assign operator with multiple values?

### ISSUE THREAD

**Issue by maurocsound** [csound/csound#999]
From the syntax description of the assign operator "=" in the reference manual (https://csound.com/docs/manual/assign.html) it should be possible to do multiple assignments in one assign statement. 
So, instead of doing: 

kx3 = kx2
kx2 = kx1
kx1 = kx0

you could do:

kx3, kx2, kx1 = kx2, kx1, kx0

But the above statement to me doesn't work... At least on Windows...

**Comment by kunstmusik** [comment]
Interesting, I wonder if this got lost when we switched the Flex/Bison parser.  Also, I did modify code in CS7 (the feature/parser3 branch) years ago to optimize out assignments when right-hand side is an expression (e.g., function-call).  I suppose if the above is restored, it may require some reworking of what I did in CS7 to be compatible, but seems worth it.

**Comment by maurocsound** [comment]
From my recent experiments (in Csound6.10) in comparing native opcode speed vs Csound implementation vs Faust code JIT-compiled (https://github.com/csound/csound/issues/969#issuecomment-415976935), I noticed that:
1) Sample-by-sample computation written in Csound language are very very slow;
2) when you do sample-by-sample computations directly in Csound language, each little and apparently insignificant optimization (like in the multiple assignment example in the first post of this thread) could give you a nice boost at runtime. 

I suspect this happens because the part of the Csound engine that translates internally (in RAM) the csd source code into a linked list of opcode nodes, doesn't do the optimizations that a modern compiler does (so, its performance are much more affected by the style in which the programmer writes its code) and the Csound internal "reader/interpreter" of this linked list of opcodes has to do various things, before and after each opcode execution, that slow down very much the overall performance. In my experience, a mathematical expression written in Csound code is about 20 times slower than a native opcode that does the same computation.

P.S.: An example of how a different programming style could make the difference in performance:

`kVar = aVar[0]`

is about 2x slower than:

`kVar vaget 0, aVar`

I think that many users would prefer and use the first version, because it's easier to understand, but they don't know that it is 2 times slower than the second one, probably because it writes the contents of aVar[0] into a temp variable before assigning it to kVar... Ideally, the Csound engine should recognize that, in this specific case, the temp variable is not needed.

**Comment by jpffitch** [comment]
On Sun, 26 Aug 2018, maurocsound wrote:

> P.S.: An example of how a different programming style could make the
> difference in performance:
> 
> kVar = aVar[0]
> 
> is about 2x slower than:
> 
> kVar vaget 0, aVar
>

The first form needs an explicit down sampling.  Not sure abiut what 
hapens in second form --- would need to see the compiltion via -v

**Comment by jpffitch** [comment]
Muktile assignment was apparently introduced in 5.11  Not sure I still have that code around.  No memory of this but that does not men much.

Never saw it in the bison parser I drafted but I will look.

**Comment by jpffitch** [comment]
Narrowing down to
2010-02-13  john ffitch  <jpff@codemist.co.uk>

        * OOps/aops.c (minit): Ensure a,b=b,a works

Still looking for code

**Comment by kunstmusik** [comment]
@maurocsound Could you file an issue to look at optimizing out the additional assignment? These things were supposed to go into Engine/csound_orc_optimize.c but looks like they were never done.

**Comment by jpffitch** [comment]
1:  Multiple assignment is in the code but not the parser

2: Extra assignment is optimised.  But the example given is not that case as there is a downsample operation as well

**Comment by jpffitch** [comment]
Fixed the paser but problems remain, like 
kk, ka[2] = 1,2
will probable fail.  Still closer

Not committed until more tests

**Comment by kunstmusik** [comment]
@jpffitch I don't think extra assignment is optimized. Quick test using:

https://gist.github.com/kunstmusik/d04730797ec35a2583c84db757fffd9e

and running with `csound --verbose white_noise.csd` shows:

```
xin args:       ain
init.a args:    asig    0
=.k args:       kndx    0
<.0 args:       #B0     kndx    ksmps
cnkgoto args:   #B0     __synthetic_303:
##array_get args:       #k1     ain     kndx
##mul.kk args:  #k2     #k1     0.5
=.k args:       #k3     #k2
##array_set args:       asig    #k3     kndx
##add.kk args:  #k4     kndx    1
=.k args:       kndx    #k4
kgoto args:     __synthetic_302:
xout args:      asig
```

for the half_amp UDO.  Note the =.k lines like `=.k args:       #k3     #k2` which aren't necessary.

**Comment by kunstmusik** [comment]
Slightly better example:

https://gist.github.com/kunstmusik/5bd09df8445fcdee6a350264dba7cef3

```
xin args:       ain
init.a args:    asig    0
=.k args:       kndx    0
<.0 args:       #B0     kndx    ksmps
cnkgoto args:   #B0     __synthetic_303:
##array_get args:       #k1     ain     kndx
=.k args:       kval    #k1
##mul.kk args:  #k2     kval    0.5
=.k args:       #k3     #k2
##array_set args:       asig    #k3     kndx
##add.kk args:  #k4     kndx    1
=.k args:       kndx    #k4
kgoto args:     __synthetic_302:
xout args:      asig
```

**Comment by jpffitch** [comment]
definitely used to  -- I remember struggling with it.  Peraps it is incomplete?

btw committed mltiple assignment parsing

**Comment by kunstmusik** [comment]
I found the commit I did to the parser3 branch that dealt with rewriting trees that dealt with function call returns:

https://github.com/csound/csound/commit/bf815b23d8c2062c77e83c386db6548ca55243e8

Not sure it's an exact fit for the global assignment issue, but the principle is similar.  We should do a pass in the optimization code to look at

**Comment by maurocsound** [comment]
@kunstmusik wrote:
> Could you file an issue to look at optimizing out the additional assignment? These things were supposed to go into Engine/csound_orc_optimize.c but looks like they were never done.

Done: https://github.com/csound/csound/issues/1001 ;-)

**Comment by maurocsound** [comment]
If you implement the multiple assignment for "=", if it's not too difficult, by extension I think it could be implemented also for: 
```
+=
-=
*=
/=
```

**Comment by jpffitch** [comment]
Not at all easy as it reacts with multcore.
btw multiple assignments is implemented in github now.  It was just a parser issue, and trivial to fix

**Comment by jpffitch** [comment]
This issue confuses a special case of ksmps=1 with a general case.

I know I wrote this code somewhere
